--Order of scripts to run 

CREATE TABLE IRA_DISTRIBUTION_REASON
             (REASON_ID NUMBER(10), REASON_CODE VARCHAR2(50),REASON_DESC VARCHAR2(500),SAVINGS_CREDIT_TRANCODE  NUMBER(15,0),
			  CHECKING_CREDIT_TRANCODE NUMBER(15,0),CD_DEBIT_TRANCODE NUMBER(15,0),
			 PRIMARY KEY(REASON_ID));

CREATE TABLE IRA_DISTRIBUTION_SEQUENCE(SIMPLE_DIST_ID NUMBER(10) PRIMARY KEY);

--for cdorder list
CREATE TABLE IRA_CDORDERING_SEQUENCE(SEQUENCE_ID NUMBER(10), SEQUENCE_NUMBER NUMBER(10),ACCOUNT VARCHAR2(20),
		                     DIST_SEQ_ID NUMBER(10),PRIMARY KEY(SEQUENCE_ID) ,
                                     FOREIGN KEY (DIST_SEQ_ID) REFERENCES IRA_DISTRIBUTION_SEQUENCE(SIMPLE_DIST_ID),
									 FOREIGN KEY (ACCOUNT) REFERENCES DEPOSIT(ACCOUNT_ID));
ALTER TABLE IRA_CDORDERING_SEQUENCE RENAME column ACCOUNT TO ACCOUNT_ID;								 

--Main distribution Instruction
CREATE TABLE IRA_DISTRIBUTION_INSTRUCTION(DIST_INST_ID NUMBER(10),REASON_ID NUMBER(10),INSTITUTION_ID  VARCHAR2(30),DISTRIBUTION_AMOUNT VARCHAR2(20),
                              EXCESS_CONTRIBUTION_YEAR VARCHAR2(10),EXCESS_CONTRIBUTION_AMOUNT VARCHAR2(20),EFFECTIVE_START_DATE DATE,
                              DISTRIBUTION_FREQUENCY VARCHAR2(20),DISTRIBUTION_DAY_OF_MONTH NUMBER(5),SAVINGS_PLAN_NUMBER VARCHAR2(20),   
							  FEDERAL_TAX_RATE VARCHAR2(10),STATE_TAX_RATE VARCHAR2(10), MODIFIED_BY VARCHAR2(20),NEXT_DISTRIBUTION_DATE DATE,
							  LAST_DISTRIBUTED_DATE DATE,
                              DISTRIBUTION_SEQ_ID NUMBER(10), 
                              PRIMARY KEY(DIST_INST_ID),
                              FOREIGN KEY (DISTRIBUTION_SEQ_ID) REFERENCES IRA_DISTRIBUTION_SEQUENCE(SIMPLE_DIST_ID),
                              FOREIGN KEY (REASON_ID) REFERENCES IRA_DISTRIBUTION_REASON(REASON_ID));                             

--Distribution Head
create table IRA_DISTRIBUTION_HEAD(DISTRIBUTION_HEAD_ID NUMBER(10),DISTRIBUTION_PERCENTAGE  NUMBER(5), 
                               DISTRIBUTION_MODE VARCHAR2(20),ACCOUNT_NO VARCHAR2(100),DIST_INST_ID NUMBER(10),
                               PRIMARY KEY(DISTRIBUTION_HEAD_ID),
                               FOREIGN KEY (DIST_INST_ID) REFERENCES IRA_DISTRIBUTION_INSTRUCTION(DIST_INST_ID));
  
CREATE SEQUENCE IRA_DISTRIBUTION_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IRA_DISTRIBUTION_HEAD_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IRA_DIST_SEQ_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IRA_DISTRIBUTION_CD_ORDER_SEQ START WITH 1 INCREMENT BY 1;

--savings plan Parameters ,contribution config 
alter table savings_plan_contr_config add (UNIQUE_ID  NUMBER(15,0));
CREATE SEQUENCE SAVINGS_PLAN_CONT_CONFIG_SEQ START WITH 1 INCREMENT BY 1;

--Parameters plan applicable products screen
alter table plan_applicable_products add (UNIQUE_ID  NUMBER(15,0));
CREATE SEQUENCE PLAN_APP_PROD_SEQ  START WITH 1 INCREMENT BY 1;

--ALTER TABLE DEPOSIT ADD CD_PRE_DIST_CHECK_AMOUNT  NUMBER(20,5) DEFAULT 0;
--ALTER TABLE DEPOSIT ADD CD_PRE_DIST_PENALTY_AMOUNT NUMBER(20,5) DEFAULT 0;

--For Storing the CD money and its related Dist Instruction
create table DIST_INST_CD_PRE_AMOUNTS(
ID NUMBER(10) PRIMARY KEY,
DIST_INST_ID NUMBER(20,5) NOT NULL,
ACCOUNT VARCHAR2(30) NOT NULL,
CD_PRE_DIST_CHECK_AMOUNT  NUMBER(20,5),
CD_PRE_DIST_PENALTY_AMOUNT NUMBER(20,5),
FOREIGN KEY (DIST_INST_ID) REFERENCES IRA_DISTRIBUTION_INSTRUCTION(DIST_INST_ID),
FOREIGN KEY (ACCOUNT) REFERENCES DEPOSIT(ACCOUNT_ID));

--Check Processing
alter table PAYMENT_AUTHORIZATION add  savings_plan_no number(20,0);
alter table ACCOUNT_CHECK_PAYMENT add  savings_plan_no number(20,0);
