INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY, MAX_LENGTH, DATA_EXPRESSION)
  VALUES((select max(property_definition_id)+1 from property_definition), (SELECT entity_type_definition_id FROM entity_type_definition WHERE TYPE_NAME = 'LoanRepayment'), 'CollectNextPastDueBillAmount', 13, 'CollectNextPastDueBillAmount', 0, 1, 0, 'java.lang.Boolean:false', 0, 
  'java.lang.Boolean:{default={true=Yes, false=No}}', 0, 1, 0, 0, 1, 1, 0, 'U', 0, 1, 999, '.*');

INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
  VALUES((select max(property_definition_id) from property_definition), 0, 0, 1, 0, 'ACCOUNT_CREATED');
INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
  VALUES((select max(property_definition_id) from property_definition), 0, 0, 1, 0, 'DEFAULT');
INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'INQUIRY');
  
  
 update property_definition  set DEFAULT_VALUE='java.lang.Boolean:true' where Property_name='IsNewRateShouldRecorded';
 
