--coupon book properties

--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES(PROPDEFID_SEQ.nextval,(select ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION where TYPE_NAME='CouponBook'), 'DateofFirstCoupon', 8, 'Date of First Coupon', 5, 0, 0, NULL, 0, 'com.vsoftcorp.time.Date:{default={}}', 0, 1, 0, 0, 1, 1, 0, 'UC', 0, 0  
--)
--;
--
--
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(PROPDEFID_SEQ.currval, 0, 0, 1, 0, 'INQUIRY')
--;
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(PROPDEFID_SEQ.currval, 0, 0, 1, 0, 'DEFAULT')
--;
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(PROPDEFID_SEQ.currval, 0, 0, 1, 0, 'ACCOUNT_CREATED')
--;
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES(PROPDEFID_SEQ.nextval, (select ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION where TYPE_NAME='CouponBook'),'NumberofCoupons', 9, 'Number of Coupons', 2, 0, 0, NULL, 0, 'java.lang.Integer:{default={}}', 0, 1, 0, 0, 1, 1, 0, 'UC', 0, 0 )
--;
--
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(PROPDEFID_SEQ.currval, 0, 0, 1, 0, 'ACCOUNT_CREATED')
--;
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(PROPDEFID_SEQ.currval, 0, 0, 1, 0, 'INQUIRY')
--;
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(PROPDEFID_SEQ.currval, 0, 0, 1, 0, 'DEFAULT')
--;
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES(PROPDEFID_SEQ.nextval,(SELECT  ENTITY_TYPE_DEFINITION_ID   FROM ENTITY_TYPE_DEFINITION where TYPE_NAME='CouponBook'), '1stCouponIndex', 10, '1st Coupon Index', 2, 0, 0, 'java.lang.Integer:1', 0, 'java.lang.Integer:{default={}}', 0, 1, 0, 0, 1, 1, 0, 'UC', 0, 0  
--)
--;
--
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(PROPDEFID_SEQ.currval, 0, 0, 1, 0, 'INQUIRY')
--;
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(PROPDEFID_SEQ.currval, 0, 0, 1, 0, 'DEFAULT')
--;
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(PROPDEFID_SEQ.currval, 0, 0, 1, 0, 'ACCOUNT_CREATED')
--;
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES(PROPDEFID_SEQ.nextval,(SELECT  ENTITY_TYPE_DEFINITION_ID   FROM ENTITY_TYPE_DEFINITION where TYPE_NAME='CouponBook'), 'Maximumcouponsperbook', 12, 'Maximum coupons per book', 2, 0, 0, 'java.lang.Integer:60', 0, 'java.lang.Integer:{default={}}', 0, 1, 0, 0, 1, 1, 0, 'UC', 0, 0 )
--;
--
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(PROPDEFID_SEQ.currval, 0, 0, 1, 0, 'ACCOUNT_CREATED');
--
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(PROPDEFID_SEQ.currval, 0, 0, 1, 0, 'INQUIRY');
--
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(PROPDEFID_SEQ.currval, 0, 0, 1, 0, 'DEFAULT');
--
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES(PROPDEFID_SEQ.nextval, (SELECT  ENTITY_TYPE_DEFINITION_ID   FROM ENTITY_TYPE_DEFINITION where TYPE_NAME='CouponBook'), 'Couponreorderingleadperiod', 13, 'Coupon re-ordering lead period', 6, 0, 0, 'com.vsoftcorp.time.Duration:DAY:15', 0, 'com.vsoftcorp.time.Duration:{default={}}', 0, 0, 0, 0, 1, 1, 0, 'UC', 0, 0)
--;
--
--
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(PROPDEFID_SEQ.currval, 0, 0, 1, 0, 'DEFAULT');
--
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(PROPDEFID_SEQ.currval, 0, 0, 1, 0, 'ACCOUNT_CREATED');
--
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(PROPDEFID_SEQ.currval, 0, 0, 1, 0, 'INQUIRY');
--  
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES(PROPDEFID_SEQ.nextval, (select ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION where TYPE_NAME='CouponBook'), 'Couponorderingleadperiod', 7, 'Couponorderingleadperiod', 6, 0, 0, 'com.vsoftcorp.time.Duration:DAY:15', 0, 'com.vsoftcorp.time.Duration:{default={}}', 0, 0, 0, 0, 1, 1, 0, 'c', 0, 0);
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(PROPDEFID_SEQ.currval, 1, 0, 0, 0, 'DEFAULT');
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(PROPDEFID_SEQ.currval, 1, 0, 0, 0, 'ACCOUNT_CREATED');
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(PROPDEFID_SEQ.currval, 1, 0, 0, 0, 'INQUIRY');
--  
--                    
--                     
--
--
--
---- mail code association 
--
--INSERT INTO ENTITY_TYPE_DEFINITION(ENTITY_TYPE_DEFINITION_ID, TYPE_NAME, TYPE_DESCRIPTION, ENTITY_TYPE_INSTANCE_CLASS, BASE_ENTITY_TYPE_DEF_ID, LOOKUP, SYSTEM, TEMPLATE)
--  VALUES((select max(ENTITY_TYPE_DEFINITION_ID)+1 from ENTITY_TYPE_DEFINITION), 'MailCode', 'Mail Code', 'com.vsoftcorp.loan.model.entities.MailCode', NULL, 1, 0, NULL);
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES(PROPDEFID_SEQ.nextval, (select max(ENTITY_TYPE_DEFINITION_ID) from ENTITY_TYPE_DEFINITION), 'Code', 0, 'Code', 1, 1, 0, NULL, 0, 'java.lang.String:{default={}}', 0, 1, 0, 0, 1, 1, 0, 'C', 0, 1);
--
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(PROPDEFID_SEQ.currval, 0, 0, 1, 0, 'INQUIRY');
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(PROPDEFID_SEQ.currval, 0, 0, 1, 0, 'ACCOUNT_CREATED');
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(PROPDEFID_SEQ.currval, 0, 0, 1, 0, 'DEFAULT');
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES(PROPDEFID_SEQ.nextval, (select max(ENTITY_TYPE_DEFINITION_ID) from ENTITY_TYPE_DEFINITION), 'Description', 1, 'Description', 1, 1, 0, NULL, 0, 'java.lang.String:{default={}}', 0, 1, 0, 0, 1, 1, 0, 'C', 0, 0);
--
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(PROPDEFID_SEQ.currval, 0, 0, 1, 0, 'INQUIRY');
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(PROPDEFID_SEQ.currval, 0, 0, 1, 0, 'DEFAULT');
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(PROPDEFID_SEQ.currval, 0, 0, 1, 0, 'ACCOUNT_CREATED');
--  
--  
--  INSERT INTO ASSOCIATE_DEFINITION(ASSOCIATE_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, ASSOCIATE_NAME, ASSOCIATE_INDEX, ASSOCIATE_DESCRIPTION, ASSOCIATE_TYPE_DEFINITION_ID, ASSOCIATE_TYPE_OVERRIDEN, MULTIPLICITY, MULTIPLICITY_OVERRIDEN, ASSOCIATION_TYPE, ASSOCIATION_TYPE_OVERRIDEN, LAZY, LAZY_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, COPY, COPY_OVERRIDEN, DEFAULT_INSTANCE, DEFAULT_INSTANCE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, TEMPLATE, TEMPLATE_OVERRIDEN)
--  VALUES(ASSOCIATEID_SEQ.nextval,(select ENTITY_TYPE_DEFINITION_ID from ENTITY_TYPE_DEFINITION where type_name = 'CouponBook'), 'MailCode', 0, 'Mail Code', (select max(ENTITY_TYPE_DEFINITION_ID) from ENTITY_TYPE_DEFINITION), 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, NULL, 0, 0, 1, 1, 0, 'UC', NULL, 0 );
--
--INSERT INTO ASSOCIATE_PRESENTER_ATTRIBUTES(ASSOCIATE_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(ASSOCIATEID_SEQ.currval, 0, 0, 1, 0, 'ACCOUNT_CREATED');
--INSERT INTO ASSOCIATE_PRESENTER_ATTRIBUTES(ASSOCIATE_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(ASSOCIATEID_SEQ.currval, 0, 0, 1, 0, 'DEFAULT');
--INSERT INTO ASSOCIATE_PRESENTER_ATTRIBUTES(ASSOCIATE_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES(ASSOCIATEID_SEQ.currval, 0, 0, 0, 0, 'INQUIRY');
--
--
--
--
--INSERT INTO ENTITY_TYPE_INSTANCE(ENTITY_TYPE_INSTANCE_ID, TYPE_NAME, TYPE_DESCRIPTION, STATUS, ENTITY_TYPE_INST_CLASS_NAME)
--  VALUES(ENTITYTYPEINSTID_SEQ.nextval, 'MailCode', 'Mail Code', 1, 'com.vsoftcorp.loan.model.entities.MailCode');
--
--INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
--  VALUES(ENTITYTYPEINSTID_SEQ.currval, 'Code', 'java.lang.String:B');
--INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
--  VALUES(ENTITYTYPEINSTID_SEQ.currval, 'Description', 'java.lang.String:Mailed back to your Operations Center');
--insert into ASSOCIATE_DEF_VALID_VALUES (ASSOCIATE_DEFINITION_ID,ENTITY_TYPE_INSTANCE_ID) 
--values(ASSOCIATEID_SEQ.currval,ENTITYTYPEINSTID_SEQ.currval);
--
--
--
--INSERT INTO ENTITY_TYPE_INSTANCE(ENTITY_TYPE_INSTANCE_ID, TYPE_NAME, TYPE_DESCRIPTION, STATUS, ENTITY_TYPE_INST_CLASS_NAME)
--  VALUES(ENTITYTYPEINSTID_SEQ.nextval, 'MailCode', 'Mail Code', 1, 'com.vsoftcorp.loan.model.entities.MailCode');
--INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
--  VALUES(ENTITYTYPEINSTID_SEQ.currval, 'Code', 'java.lang.String:M');
--INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
--  VALUES(ENTITYTYPEINSTID_SEQ.currval, 'Description', 'java.lang.String:Mailing directly to the borrower');
--insert into ASSOCIATE_DEF_VALID_VALUES (ASSOCIATE_DEFINITION_ID,ENTITY_TYPE_INSTANCE_ID) 
--values(ASSOCIATEID_SEQ.currval,ENTITYTYPEINSTID_SEQ.currval);
--
--INSERT INTO ENTITY_TYPE_INSTANCE(ENTITY_TYPE_INSTANCE_ID, TYPE_NAME, TYPE_DESCRIPTION, STATUS, ENTITY_TYPE_INST_CLASS_NAME)
--  VALUES(ENTITYTYPEINSTID_SEQ.nextval, 'MailCode', 'Mail Code', 1, 'com.vsoftcorp.loan.model.entities.MailCode');
--INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
--  VALUES(ENTITYTYPEINSTID_SEQ.currval, 'Code', 'java.lang.String:C');
--INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
--  VALUES(ENTITYTYPEINSTID_SEQ.currval, 'Description', 'java.lang.String:Mailing to Canada');
--insert into ASSOCIATE_DEF_VALID_VALUES (ASSOCIATE_DEFINITION_ID,ENTITY_TYPE_INSTANCE_ID) 
--values(ASSOCIATEID_SEQ.currval,ENTITYTYPEINSTID_SEQ.currval);
--
--INSERT INTO ENTITY_TYPE_INSTANCE(ENTITY_TYPE_INSTANCE_ID, TYPE_NAME, TYPE_DESCRIPTION, STATUS, ENTITY_TYPE_INST_CLASS_NAME)
--  VALUES(ENTITYTYPEINSTID_SEQ.nextval, 'MailCode', 'Mail Code', 1, 'com.vsoftcorp.loan.model.entities.MailCode');
--INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
--  VALUES(ENTITYTYPEINSTID_SEQ.currval, 'Code', 'java.lang.String:X');
--INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
--  VALUES(ENTITYTYPEINSTID_SEQ.currval, 'Description', 'java.lang.String:Mailing to Mexico');
--insert into ASSOCIATE_DEF_VALID_VALUES (ASSOCIATE_DEFINITION_ID,ENTITY_TYPE_INSTANCE_ID) 
--values(ASSOCIATEID_SEQ.currval,ENTITYTYPEINSTID_SEQ.currval);
--
--INSERT INTO ENTITY_TYPE_INSTANCE(ENTITY_TYPE_INSTANCE_ID, TYPE_NAME, TYPE_DESCRIPTION, STATUS, ENTITY_TYPE_INST_CLASS_NAME)
--  VALUES(ENTITYTYPEINSTID_SEQ.nextval, 'MailCode', 'Mail Code', 1, 'com.vsoftcorp.loan.model.entities.MailCode');
--INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
--  VALUES(ENTITYTYPEINSTID_SEQ.currval, 'Code', 'java.lang.String:F');
--INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
--  VALUES(ENTITYTYPEINSTID_SEQ.currval, 'Description', 'java.lang.String:Sent to any other country');
--insert into ASSOCIATE_DEF_VALID_VALUES (ASSOCIATE_DEFINITION_ID,ENTITY_TYPE_INSTANCE_ID) 
--values(ASSOCIATEID_SEQ.currval,ENTITYTYPEINSTID_SEQ.currval);
--
--
--update ASSOCIATE_DEFINITION  set DEFAULT_INSTANCE=(select ENTITY_TYPE_INSTANCE_ID from PROPERTY where PROPERTY_NAME='Code' and VALUE='java.lang.String:B') where ASSOCIATE_NAME='MailCode';
--
--
----update PROPERTY_DEFINITION set MANDATORY=1 where PROPERTY_NAME='NextCouponDate';
--
----deleting the properties which is already existed 
--
--delete from PROPERTY_PRESENTER_ATTRIBUTES where PROPERTY_DEFINITION_ID in
--(select PROPERTY_DEFINITION_ID From PROPERTY_DEFINITION where PROPERTY_NAME in ('CouponStartDate','CouponBookType','CouponBookTerm','ContinuousOrder',
--'OrderNow','CouponThroughDate'));
--
--delete from PROPERTY_DEFINITION where PROPERTY_NAME in ('CouponStartDate','CouponBookType','CouponBookTerm','ContinuousOrder',
--'OrderNow','CouponThroughDate');

--tables for order
CREATE
	SEQUENCE COUPON_ORDER_INS_ID_SEQ INCREMENT BY 1 START WITH 10000 ORDER;
CREATE
	TABLE COUPON_BOOK_ORDER_INSTRUCTION 
	(
		ACCOUNT_ID NVARCHAR2(30),
		COUPON_ORDER_INS_ID NVARCHAR2(30),
		NO_OF_COUPONS NUMBER(10),
                MAIL_CODE NVARCHAR2(30),
		FIRST_COUPON_DUE_DATE DATE,
		FIRST_COUPON_INDEX NUMBER(10),
		CREATION_DATE DATE,
        STATUS NVARCHAR2(10),
        ORDER_DATE DATE
	);
CREATE
	SEQUENCE COUPON_BOOK_SPEC_SEQ INCREMENT BY 1 START WITH 10000 ORDER;
CREATE
	TABLE COUPON_BOOK_SPECIFICATION 
	(
		COUPON_BOOK_SPEC_ID NVARCHAR2(30),
		PROPERTY_NUMBER NVARCHAR2(30),
		ACCOUNT_NUMBER NVARCHAR2(30),
		CUSTOMER_NAME NVARCHAR2(100),
		FIRST_COUPON_INDEX NUMBER(10),
		MAIL_CODE NVARCHAR2(30),
		FIRST_COUPON_DATE DATE,
		CREATION_DATE DATE,
		STATUS NVARCHAR2(10),
		ADDRESS_LINES NVARCHAR2(150),
		STATE NVARCHAR2(30),
		CITY NVARCHAR2(30),
		POSTAL_INDEX_NUMBER NVARCHAR2(30),
		COUNTRY_ISO_CODE NVARCHAR2(20),
		EXTRACTED_DATE DATE,
        NOTE_DATE DATE,
		DATE_NEXT_DUE DATE,
		DATE_LAST_COUPON DATE,
		PAYMENT_FREQUENCY NUMBER(10) ,
		LATE_CHARGE_AMOUNT NVARCHAR2(20),
		PRINCIPAL_BALANCE NVARCHAR2(20),
		INSTITUTION_NAME NVARCHAR2(30),
		INSTITUTION_ID NVARCHAR2(30),
		GRACE_PERIOD NVARCHAR2(30),
		LOAN_TERM NVARCHAR2(30),
		NO_OF_COUPONS NUMBER(10),
		SCHEDULED_AMOUNT NVARCHAR2(30), 
		COUPON_ORDER_INS_ID NVARCHAR2(30),
		INTEREST_CAL_TYPE NVARCHAR2(30)
	);
	
CREATE
	SEQUENCE COUPON_PAYMENT_ID_SEQ INCREMENT BY 1 START WITH 10000 ORDER;
CREATE
	TABLE COUPON_BOOK_PAYMENT_DETAILS 
	(  COUPON_BOOK_SPEC_ID NVARCHAR2(30),
		COUPON_BOOK_PAYMENT_ID NVARCHAR2(30),
		NO_OF_PAYMENTS NUMBER(10),
		START_DATE DATE,
		AMOUNT NVARCHAR2(30) 
	);


CREATE
	SEQUENCE COUPON_BOOK_SUMM_SEQ INCREMENT BY 1 START WITH 10000 ORDER;
CREATE
	TABLE COUPON_BOOK_SUMMARY_DETAILS 
	(
		COUPON_BOOK_SUMM_ID NVARCHAR2(30),
		NO_OF_ACCOUNTS NUMBER(10),
		EXTRACTED_DATE DATE
	);
	
	
insert into  LOAN_EXCEPTION_CODE_LOOKUP (EXCEPTION_CODE_ID,DESCRIPTION)
values ('70','Coupon book processing failed') ;

--delete from PROPERTY where PROPERTY_NAME in ('CouponStartDate','CouponBookType','CouponBookTerm','ContinuousOrder',
--'OrderNow','CouponThroughDate');


ALTER TABLE COUPON_BOOK_PAYMENT_DETAILS ADD(LATE_CHARGE NVARCHAR2(30));

ALTER TABLE COUPON_BOOK_SPECIFICATION
ADD(SSN_OR_TIN VARCHAR2(30));
