
CREATE TABLE TEMPLATE_DEFINITION
  (
    "CREATED_DATE" DATE,
    "CREATED_USER"              VARCHAR2(4000 BYTE),
    "IS_VISIBLE"                NUMBER(38,0),
    "ENTITY_TYPE_DEFINITION_ID" NUMBER(30,0),
    "IS_APPL_FOR_PRODUCT"       NUMBER(38,0),
    "IS_APPL_FOR_CUSTOMER"      NUMBER(38,0),
    CONSTRAINT "TEMPLATE_ENTITY_FK" FOREIGN KEY ("ENTITY_TYPE_DEFINITION_ID") REFERENCES ENTITY_TYPE_DEFINITION ("ENTITY_TYPE_DEFINITION_ID"));



CREATE TABLE TEMPLATE_PRODUCT_MAPPING
  (
    "ENTITY_TYPE_DEFINITION_ID" NUMBER(30,0),
    "PRODUCT_UID"               NUMBER(30,0),
    CONSTRAINT "TEMPLATE_DEF_FK" FOREIGN KEY ("ENTITY_TYPE_DEFINITION_ID") REFERENCES  ENTITY_TYPE_DEFINITION ("ENTITY_TYPE_DEFINITION_ID"),
    CONSTRAINT "TEMPLATE_PROD_FK" FOREIGN KEY ("PRODUCT_UID") REFERENCES PRODUCT ("PRODUCT_UID"));


CREATE TABLE ENTITY_INST_ACCOUNT_MAPPING
  (
    "ENTITY_TYPE_INSTANCE_ID" NUMBER(30,0),
    "UNIQUE_ID"               NUMBER(38,0),
    CONSTRAINT "ENTITY_INST_TYPE_FK" FOREIGN KEY ("ENTITY_TYPE_INSTANCE_ID") REFERENCES ENTITY_TYPE_INSTANCE ("ENTITY_TYPE_INSTANCE_ID"),
    CONSTRAINT "UNIQUE_FK" FOREIGN KEY ("UNIQUE_ID") REFERENCES APPL_PRODUCT ("UNIQUE_ID"));
  
    
CREATE TABLE CUST_ENTITY_INST_MAPPING
  (
    "PARTY_ID"                VARCHAR2(20 BYTE),
    "ENTITY_TYPE_INSTANCE_ID" NUMBER(30,0),
    CONSTRAINT "PARTY_CUST_MAPPING_FK" FOREIGN KEY ("PARTY_ID") REFERENCES PARTY ("PARTY_ID"),
    CONSTRAINT "ENTITY_INST_CUST_MAPPING_FK" FOREIGN KEY ("ENTITY_TYPE_INSTANCE_ID") REFERENCES ENTITY_TYPE_INSTANCE ("ENTITY_TYPE_INSTANCE_ID"));
    
    ALTER TABLE TEMPLATE_DEFINITION ADD PRODUCT_CATEGORY NUMBER;
