	CREATE TABLE "SERVICE_REQUEST" 
	("SERVICE_REQUEST_ID" NUMBER(30,0) NOT NULL ENABLE, 
	"SERVICE_REQUEST_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"SERVICE_REQUEST_CODE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"SERVICE_CATEGORY" VARCHAR2(100 BYTE), 
	"REQUEST_TYPE" VARCHAR2(100 BYTE), 
	"POST_AUTOMATICALLY" NUMBER, 
	  CONSTRAINT "SERVICE_REQUEST_PK" PRIMARY KEY ("SERVICE_REQUEST_ID"), 
	  CONSTRAINT "REQUEST_CODE_UNIQUE" UNIQUE ("SERVICE_REQUEST_CODE"));
	  
	  
	CREATE TABLE INSTITUTION_CHANNELS("CHANNEL_ID"     NUMBER(20,0),"INSTITUTION_ID" NUMBER(20,0),
	"CHANNEL_NAME"   VARCHAR2(30 BYTE),CONSTRAINT "INSTITUTION_CHANNELS_PK_DP" PRIMARY KEY ("CHANNEL_ID"));
	insert into INSTITUTION_CHANNELS values(101,1,'DEBITCARD');
	insert into INSTITUTION_CHANNELS values(102,1,'INTERNET BANKING');
	insert into INSTITUTION_CHANNELS values(103,1,'IVR');
	insert into INSTITUTION_CHANNELS values(104,1,'PUNCHCARD');
	insert into INSTITUTION_CHANNELS values(105,1,'IPS');


	CREATE TABLE "SERVICE_REQ_CHANNEL_MAPPING" 
	("SERVICE_REQUEST_ID" NUMBER(30,0), 
	"CHANNEL_ID" NUMBER(30,0), 
	  CONSTRAINT "SERVICE_REQUEST_ID_FK" FOREIGN KEY ("SERVICE_REQUEST_ID")
	    REFERENCES "SERVICE_REQUEST" ("SERVICE_REQUEST_ID") ENABLE, 
	  CONSTRAINT "CHANNEL_FK" FOREIGN KEY ("CHANNEL_ID")
	    REFERENCES "INSTITUTION_CHANNELS" ("CHANNEL_ID") ENABLE);
 
	
	CREATE TABLE "FEE_CATEGORY" 
    ("FEE_CATEGORY_ID" NUMBER(30,0) NOT NULL ENABLE, 
	"FEE_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"SERVICE_REQUEST_ID" NUMBER(30,0), 
	  CONSTRAINT "FEE_CATEGORY_PK" PRIMARY KEY ("FEE_CATEGORY_ID"), 
	  CONSTRAINT "SERVICE_REQUEST_FK" FOREIGN KEY ("SERVICE_REQUEST_ID")
		REFERENCES "SERVICE_REQUEST" ("SERVICE_REQUEST_ID") ENABLE);
 
	
	CREATE TABLE "FEE_RATE" 
   ("FEE_RATE_ID" NUMBER(30,0) NOT NULL ENABLE, 
	"RATE_TYPE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"EFF_START_DATE" DATE, 
	"EFF_END_DATE" DATE, 
	"ASSESSMENT_FREQ" VARCHAR2(100 BYTE), 
	"MIN_FEE_RATE" NUMBER(20,4), 
	"MAX_FEE_RATE" NUMBER(20,4), 
	"FEE_CATEGORY_ID" NUMBER(30,0), 
	"FIXED_RATE" NUMBER(20,4), 
	"UNIT" NUMBER(20,4), 
	"REFERENCE_PARAM" VARCHAR2(100 BYTE), 
	"PERCENT_VALUE" NUMBER(20,4), 
	"FEE_RATE_BASIS" NUMBER(30,0), 
	  CONSTRAINT "FEE_RATE_PK" PRIMARY KEY ("FEE_RATE_ID"), 
	  CONSTRAINT "FEE_CATEGORY_FK" FOREIGN KEY ("FEE_CATEGORY_ID")
	    REFERENCES "FEE_CATEGORY" ("FEE_CATEGORY_ID") ENABLE);
 

    CREATE TABLE "FEE_RATE_CHANNEL_MAPPING" 
    ("FEE_RATE_ID" NUMBER(30,0), 
	"CHANNEL_ID" NUMBER(30,0), 
	 CONSTRAINT "FEE_RATE_ID_FKY" FOREIGN KEY ("FEE_RATE_ID")
	  REFERENCES "FEE_RATE" ("FEE_RATE_ID") ENABLE, 
	 CONSTRAINT "CHANNEL_ID_FKY" FOREIGN KEY ("CHANNEL_ID")
	  REFERENCES "INSTITUTION_CHANNELS" ("CHANNEL_ID") ENABLE);
 

    CREATE TABLE "FEE_RATE_TIER_BASIS" 
    ("TIER_BASIS_ID" NUMBER(30,0) NOT NULL ENABLE, 
	"LOW_VALUE" NUMBER(20,4), 
	"HIGH_VALUE" NUMBER(20,4), 
	"TIER_PRICE" NUMBER(20,4), 
	"UNIT" NUMBER(20,4), 
	"PERCENT_VALUE" NUMBER(20,4), 
	"FEE_RATE_ID" NUMBER(30,0), 
	 CONSTRAINT "TIER_BASIS_PRICING_PK" PRIMARY KEY ("TIER_BASIS_ID") ENABLE, 
	 CONSTRAINT "FEE_RATE_FK" FOREIGN KEY ("FEE_RATE_ID")
	  REFERENCES "FEE_RATE" ("FEE_RATE_ID") ENABLE);
 

    CREATE TABLE "FEE_PACKAGE" 
    ("FEE_PKG_ID" NUMBER(30,0) NOT NULL ENABLE, 
	"FEE_PACKAGE_TYPE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"PKG_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"PKG_CODE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CHARGE_ON_OVERDRAWN_ACC" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CONSOLIDATE_CHARGES" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"BALANCE_BASIS" VARCHAR2(100 BYTE), 
	"EARNING_RATE_BASIS" VARCHAR2(100 BYTE), 
	"FDIC_BAL_ASSESSMENT" VARCHAR2(100 BYTE), 
	"RESERVE_PERCENT" NUMBER(20,4), 
	"FDIC_ASSESSMENT_REQD" NUMBER(*,0), 
	"EARNING_BASIS" VARCHAR2(100 BYTE), 
	"CALUCATION_METHOD" VARCHAR2(100 BYTE), 
	"FIXED_EARNING_RATE" NUMBER(20,4), 
	 CONSTRAINT "FEE_PACKAGE_PK" PRIMARY KEY ("FEE_PKG_ID") ENABLE);
 

    CREATE TABLE "PACKAGE_LINE_ITEM" 
    ("PKG_LINE_ITEM_ID" NUMBER(30,0) NOT NULL ENABLE, 
	"PKG_LINE_ITEM_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"FEE_PKG_ID" NUMBER(30,0), 
	"FEE_CATEGORY_ID" NUMBER(30,0), 
	 CONSTRAINT "PACKAGE_LINE_ITEM_PK" PRIMARY KEY ("PKG_LINE_ITEM_ID") ENABLE, 
	 CONSTRAINT "FEE_PKG_FK" FOREIGN KEY ("FEE_PKG_ID")
	  REFERENCES "FEE_PACKAGE" ("FEE_PKG_ID") ENABLE, 
	 CONSTRAINT "FEE_CATE_FK" FOREIGN KEY ("FEE_CATEGORY_ID")
	  REFERENCES "FEE_CATEGORY" ("FEE_CATEGORY_ID") ENABLE);
	  
	  
    CREATE TABLE "LINE_ITEM_SERVICE_REQ_MAPPING" 
    ("PKG_LINE_ITEM_ID" NUMBER(30,0), 
	"SERVICE_REQUEST_ID" NUMBER(30,0), 
	  CONSTRAINT "LINE_ITEM_FK" FOREIGN KEY ("PKG_LINE_ITEM_ID")
	    REFERENCES "PACKAGE_LINE_ITEM" ("PKG_LINE_ITEM_ID") ENABLE, 
	  CONSTRAINT "SERVICE_REQ_FK" FOREIGN KEY ("SERVICE_REQUEST_ID")
	    REFERENCES "SERVICE_REQUEST" ("SERVICE_REQUEST_ID") ENABLE);
 
 
	CREATE TABLE "FEE_PKG_ASSESSMENT_FREQ" 
    ("FEE_PKG_ASSESS_FREQ_ID" NUMBER(30,0), 
	"FEE_PKG_ID" NUMBER(30,0), 
	"ASSESSMENT_FREQ" VARCHAR2(100 BYTE), 
	 CONSTRAINT "FEE_PKG_ASSESS_FK" FOREIGN KEY ("FEE_PKG_ID")
	  REFERENCES "FEE_PACKAGE" ("FEE_PKG_ID") ENABLE);
 

    CREATE TABLE "SERVICE_REQUEST_INSTANCE" 
    ("SERVICE_REQUEST_INSTANCE_ID" NUMBER(30,0) NOT NULL ENABLE, 
	"TRANSACTION_AMOUNT" NUMBER(20,4), 
	"TRANSACTION_DATE" DATE, 
	"ACCOUNT_ID" VARCHAR2(30 BYTE), 
	"SERVICE_REQUEST_ID" NUMBER(30,0), 
	"SERVICE_REQUEST_TYPE" VARCHAR2(100 BYTE), 
	"CHANNEL_ID" NUMBER(30,0), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	  CONSTRAINT "SRVC_REQUEST_FK" FOREIGN KEY ("SERVICE_REQUEST_ID")
	    REFERENCES "SERVICE_REQUEST" ("SERVICE_REQUEST_ID") ENABLE, 
	  CONSTRAINT "INST_CHANNEL_ID_FK" FOREIGN KEY ("CHANNEL_ID")
	    REFERENCES "INSTITUTION_CHANNELS" ("CHANNEL_ID") ENABLE, 
	  CONSTRAINT "DEPOSIT_ACC_FK" FOREIGN KEY ("ACCOUNT_ID")
	    REFERENCES "DEPOSIT" ("ACCOUNT_ID") ENABLE);
 

    CREATE TABLE "PACKAGE_ANALYSIS_HISTORY" 
    ("PKG_ANALYSIS_HIST_ID" NUMBER(30,0) NOT NULL ENABLE, 
	"FEE_PKG_ID" NUMBER(30,0), 
	"ANALYSIS_DATE" DATE, 
	"TOTAL_SRVC_CHARGE_AMT" NUMBER(20,4), 
	"FEE_PACKAGE_TYPE" VARCHAR2(100 BYTE), 
	"AVERAGE_LEDGER_BALANCE" NUMBER(20,4), 
	"AVERAGE_COLLECTED_FUNDS" NUMBER(20,4), 
	"RESERVE_BALANCE" NUMBER(20,4), 
	"INVESTABLE_BALANCE" NUMBER(20,4), 
	"EARNING_CREDIT_AMOUNT" NUMBER(20,4), 
	"CARRY_FWD_EARNING_CREDIT_AMT" NUMBER(20,4), 
	"NET_SERVICE_CHARGE" NUMBER(20,4), 
	"ANALYSIS_PERIOD" NUMBER(20,0), 
	"ACCOUNT_ID" VARCHAR2(30 BYTE), 
	  CONSTRAINT "PACKAGE_ANALYSIS_HISTORY_PK" PRIMARY KEY ("PKG_ANALYSIS_HIST_ID") ENABLE, 
	  CONSTRAINT "FEE_FK" FOREIGN KEY ("FEE_PKG_ID")
	    REFERENCES "FEE_PACKAGE" ("FEE_PKG_ID") ENABLE, 
	 CONSTRAINT "ACC_ANA_FK" FOREIGN KEY ("ACCOUNT_ID")
	  REFERENCES "DEPOSIT" ("ACCOUNT_ID") ENABLE);
 

 
    CREATE TABLE "PKG_LINE_ITEM_ANALYSIS_HISTORY" 
    ("PKG_LINE_ITEM_HIST_ID" NUMBER(30,0) NOT NULL ENABLE, 
	"SERVICE_REQUEST_COUNT" NUMBER(20,0), 
	"SRVC_REQ_UNIT_PRICE" NUMBER(20,4), 
	"SRVC_CHARGE_AMT" NUMBER(20,4), 
	"TOTAL_TRANSC_AMT" NUMBER(20,4), 
	"PKG_LINE_ITEM_ID" NUMBER(30,0), 
	"PKG_ANALYSIS_HISTORY_ID" NUMBER(30,0), 
	  CONSTRAINT "PKG_LINE_ITEM_ANALYSIS_HI_PK" PRIMARY KEY ("PKG_LINE_ITEM_HIST_ID") ENABLE, 
	  CONSTRAINT "PKG_LINE_ITEM_FK" FOREIGN KEY ("PKG_LINE_ITEM_ID")
	    REFERENCES "PACKAGE_LINE_ITEM" ("PKG_LINE_ITEM_ID") ENABLE, 
	  CONSTRAINT "PKG_HIS_FK" FOREIGN KEY ("PKG_ANALYSIS_HISTORY_ID")
	    REFERENCES "PACKAGE_ANALYSIS_HISTORY" ("PKG_ANALYSIS_HIST_ID") ENABLE);
		
		
    CREATE TABLE "SRVC_CHRG_ACC_INSTANCE" 
    ("SRVC_CHRG_ACC_INST_ID" NUMBER(30,0) NOT NULL ENABLE, 
	"ACCOUNT_ID" VARCHAR2(40 BYTE), 
	"FEE_PKG_ID" NUMBER(30,0), 
	"PKG_LINE_ITEM_ID" NUMBER(30,0), 
	"NEXT_ANALYSIS_DATE" DATE, 
	"LAST_ANALYSIS_DATE" DATE, 
	 CONSTRAINT "SRVC_CHRG_ACC_PK" PRIMARY KEY ("SRVC_CHRG_ACC_INST_ID") ENABLE, 
	 CONSTRAINT "ACC_FK" FOREIGN KEY ("ACCOUNT_ID")
	  REFERENCES "DEPOSIT" ("ACCOUNT_ID") ENABLE, 
	 CONSTRAINT "FEE_PG_FK" FOREIGN KEY ("FEE_PKG_ID")
	  REFERENCES "FEE_PACKAGE" ("FEE_PKG_ID") ENABLE, 
	 CONSTRAINT "PKG_LINE_FK" FOREIGN KEY ("PKG_LINE_ITEM_ID")
	  REFERENCES "PACKAGE_LINE_ITEM" ("PKG_LINE_ITEM_ID") ENABLE);
 
	CREATE TABLE "EARNING_RATE_TIER_BASIS" 
    ("EARNING_RATE_BASIS_ID" NUMBER(30,0) NOT NULL ENABLE, 
	"FEE_PKG_ID" NUMBER(30,0), 
	"EARNING_RATE" NUMBER(20,4), 
	"FROM_BALANCE" NUMBER(20,4), 
	"TO_BALANCE" NUMBER(20,4), 
	  CONSTRAINT "EARNING_RATE_BASIS_ID_PK" PRIMARY KEY ("EARNING_RATE_BASIS_ID") ENABLE, 
	  CONSTRAINT "EARNING_RATE_FEE_PKG_ID_FK" FOREIGN KEY ("FEE_PKG_ID")
	    REFERENCES "FEE_PACKAGE" ("FEE_PKG_ID") ENABLE);
		
	CREATE TABLE SERVICE_REQ_PRODUCT_MAPPING
	("PRODUCT_UID"        NUMBER(20,0),
    "SERVICE_REQUEST_ID" NUMBER(30,0),
      CONSTRAINT "PRODUCT_FK" FOREIGN KEY ("PRODUCT_UID") REFERENCES PRODUCT ("PRODUCT_UID"),
      CONSTRAINT "SERVICE_REQU_FK" FOREIGN KEY ("SERVICE_REQUEST_ID") REFERENCES SERVICE_REQUEST ("SERVICE_REQUEST_ID"));

	CREATE TABLE FEE_PACKAGE_PRODUCT_MAPPING
	("PRODUCT_UID" NUMBER(20,0),
    "FEE_PKG_ID"  NUMBER(20,0),
	  CONSTRAINT "FEE_PK_FKY" FOREIGN KEY ("FEE_PKG_ID") REFERENCES FEE_PACKAGE ("FEE_PKG_ID"),
      CONSTRAINT "PRODUCT_FEE_FK" FOREIGN KEY ("PRODUCT_UID") REFERENCES PRODUCT ("PRODUCT_UID"));
		
 
	ALTER TABLE DEPOSIT
    ADD (ASSESSMENT_FREQUENCY VARCHAR2(100 BYTE),
		NEXT_ANALYSIS_DATE DATE,
		IS_MINOR NUMBER,
		LAST_ANALYSIS_DATE DATE,
		FEE_PKG_ID NUMBER(30,0),
		MINOR_SVC_CHRG_PKG_ID NUMBER(30,0));


	ALTER TABLE DEPOSIT
		ADD CONSTRAINT "FEE_PKG_FKY" FOREIGN KEY ("FEE_PKG_ID") REFERENCES FEE_PACKAGE ("FEE_PKG_ID");

	ALTER TABLE DEPOSIT
		ADD CONSTRAINT "MINOR_SRV_CHG_FK" FOREIGN KEY ("MINOR_SVC_CHRG_PKG_ID") REFERENCES FEE_PACKAGE ("FEE_PKG_ID");


	ALTER TABLE ACCOUNT_APPLICATION
    ADD (ASSESSMENT_FREQUENCY VARCHAR2(100 BYTE),
		NEXT_ANALYSIS_DATE DATE,
		LAST_ANALYSIS_DATE DATE,
		FEE_PKG_ID NUMBER(30,0));


	ALTER TABLE ACCOUNT_APPLICATION
	  ADD CONSTRAINT "ACC_APPL_FEE_PKG_FKEY" FOREIGN KEY ("FEE_PKG_ID") REFERENCES FEE_PACKAGE ("FEE_PKG_ID");

	ALTER TABLE ENTRY_TYPE
	  ADD (SERVICE_REQUEST_ID NUMBER(30,0),TRANSACTION_TYPE VARCHAR2(100 BYTE));	 
	 
	ALTER TABLE ENTRY_TYPE 
	  ADD CONSTRAINT "ENTRY_TYPE_SRVC_REQ_ID" FOREIGN KEY (SERVICE_REQUEST_ID) 
	  REFERENCES SERVICE_REQUEST(SERVICE_REQUEST_ID) ENABLE;	 
		
	CREATE SEQUENCE FEE_CATEGORY_ID_SEQ MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 100 ORDER NOCYCLE ;

	CREATE SEQUENCE FEE_RATE_ID_SEQ MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 1 CACHE 100 ORDER NOCYCLE ;

	CREATE SEQUENCE FEE_PKG_ID_SEQ MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 100 ORDER NOCYCLE ;

	CREATE SEQUENCE SERVICE_REQUEST_ID_SEQ MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 100 ORDER NOCYCLE ;
	
	CREATE SEQUENCE INSTITUTION_CHANNELS_SEQ MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER NOCYCLE ;

	CREATE SEQUENCE TIER_BASIS_ID_SEQ MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 100 ORDER NOCYCLE ;

	CREATE SEQUENCE PKG_LINE_ITEM_ID_SEQ MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 100 ORDER NOCYCLE ;

	CREATE SEQUENCE FEE_PKG_ASSESS_FREQ_SEQ MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER NOCYCLE ;

	CREATE SEQUENCE SRVC_CHRG_ACC_INST_ID_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER NOCYCLE ;

	CREATE SEQUENCE PKG_ANALYSIS_HIST_ID_SEQ MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER NOCYCLE ;

	CREATE SEQUENCE PKG_LINE_ITEM_ANALYSIS_SEQ MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER NOCYCLE ;

	CREATE SEQUENCE EARNING_RATE_BASIS_ID_SEQ MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER NOCYCLE ;
	
  ALTER TABLE PACKAGE_ANALYSIS_HISTORY ADD PREV_EARNING_CREDIT_AMT NUMBER(20,4);
  
  CREATE TABLE "SRVC_CHRG_APPL_INSTANCE" 
    ("SRVC_CHRG_APPL_INST_ID" NUMBER(30,0) NOT NULL ENABLE, 
	"APPLICATION_ID" NUMBER(15), 
	"FEE_PKG_ID" NUMBER(30,0), 
	"PKG_LINE_ITEM_ID" NUMBER(30,0), 
	"NEXT_ANALYSIS_DATE" DATE, 
	"LAST_ANALYSIS_DATE" DATE, 
	 CONSTRAINT "SRVC_CHRG_APP_PK" PRIMARY KEY ("SRVC_CHRG_APPL_INST_ID") ENABLE, 
	 CONSTRAINT "APP_FK" FOREIGN KEY ("APPLICATION_ID")
	  REFERENCES "ACCOUNT_APPLICATION" ("UNIQUE_ID") ENABLE, 
	 CONSTRAINT "FEE_PAC_FK" FOREIGN KEY ("FEE_PKG_ID")
	  REFERENCES "FEE_PACKAGE" ("FEE_PKG_ID") ENABLE, 
	 CONSTRAINT "PAC_LINE_FK" FOREIGN KEY ("PKG_LINE_ITEM_ID")
	  REFERENCES "PACKAGE_LINE_ITEM" ("PKG_LINE_ITEM_ID") ENABLE);
    
	  
ALTER TABLE ACCOUNT_APPLICATION ADD IS_MINOR NUMBER(38);

ALTER TABLE ACCOUNT_APPLICATION ADD MINOR_SRVC_CHRG_PKG_ID VARCHAR2(40);

alter table fee_package modify(consolidate_charges null);

	CREATE SEQUENCE SERVICE_RQST_INSTANCE_ID_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER NOCYCLE ;