CREATE TABLE TRANSACTIONS_279 ( 
    ACCOUNT_NO         	VARCHAR2(30) NULL,
    PLAN_ID            	VARCHAR2(30) NULL,
    EFFECTIVE_DATE     	DATE NULL,
    DISTRIBUTION_AMOUNT	NUMBER NULL 
    );
    
CREATE OR REPLACE VIEW PARTY_VW as
 SELECT P.PARTY_ID, O.BUSINESS_NAME, PE.FIRST_NAME, PE.LAST_NAME,PE.MIDDLE_NAME,PE.EMPLOYER_NAME, P.PARTY_TYPE, NVL(O.BUSINESS_NAME , PE.FIRST_NAME||' '||pe.middle_name||' '||pe.last_name ) PARTY_NAME 
 FROM PARTY P, PERSON PE, ORGANIZATION O 
 WHERE P.PARTY_ID = PE.PARTY_ID(+) 
 AND P.PARTY_ID = O.PARTY_ID (+);
 
alter table hold_payment_maintenance add(PERIOD_BASIS varchar2(100));

alter table DEPOSIT_ACCOUNT_INSTRUCTION add(PERIOD_BASIS varchar2(100));
--------
CREATE TABLE CYCLE_GRP_NEW_ACCTS AS
SELECT ACCOUNT_NO,INSTITUTION_ID,CURRENT_STATEMENT_CYCLE CYCLE_CODE,ACCOUNT_ID FROM DEPOSIT_ACCOUNT_VW
WHERE ACCOUNT_ID IN
((SELECT ACCOUNT_ID FROM DEPOSIT_ACCOUNT_VW
MINUS
SELECT ACCOUNT_ID FROM CYCLE_GROUP_ACCTS_CONFIG)
UNION
(SELECT AML.ACCOUNT_ID ACCOUNT_ID
FROM MAINTENANCE_LOG ML, ACCOUNT_MAINTENANCE_LOG AML,ACCOUNT A
WHERE ML.ENTRY_ID = AML.ENTRY_ID
AND   AML.ACCOUNT_ID = A.ACCOUNT_ID
AND TRIM(FIELD_CHANGED) LIKE '%currentStatementCycle'
AND TRUNC(EFFECTIVE_DATE_FROM) > (SELECT TRUNC(LAST_PROCESSED_DATE) FROM INSTITUTION I WHERE I.INSTITUTION_ID=A.INSTITUTION_ID)
AND TRUNC(EFFECTIVE_DATE_FROM) <= (SELECT TRUNC(NEXT_BUSINESS_DATE) FROM INSTITUTION I WHERE I.INSTITUTION_ID=A.INSTITUTION_ID)));

-----------------
ALTER TABLE entry_type ADD TRANSACTION_CATEGORY varchar2(2) DEFAULT '0';
ALTER TABLE OD_PROTECTION_OPTION ADD OPT_IN_ATM NUMBER(2);
ALTER TABLE OD_PROTECTION_OPTION ADD OPT_IN_INTERNET_BANKING NUMBER(2);
---------

CREATE OR REPLACE VIEW REG_D_ACTIVITY_REPORT_VW AS SELECT D.ACCOUNT_NO,
  DAV.ACCOUNT_ID,
  DAV.INSTITUTION_ID,
  DAV.ACCOUNT_TYPE_ID,
  D.REGD_COMPUTING_PERIOD,
  RAD.STATUS,
  DAV.LAST_STMT_DATE,
  I.INSTITUTION_NAME
FROM REGD_ACTIVITY_DETAILS RAD,
  DEPOSIT_ACCOUNT_VW DAV,DEPOSIT D,
  institution i
WHERE D.ACCOUNT_ID=RAD.ACCOUNT_ID
AND DAV.INSTITUTION_ID=I.INSTITUTION_ID
AND DAV.ACCOUNT_ID=RAD.ACCOUNT_ID;

---
alter table interest_codes modify TAX_WITH_HOLD_PERCENTAGE NUMBER(10, 4)  DEFAULT 0.28;

ALTER TABLE deposit ADD OVERDRAFT_BEHAVIOUR NUMBER(8) default 0;