CREATE TABLE "USER_FREQUENT_HABITS" (
    "UNIQUE_ID" Number(30),
	"INSTITUTION_ID"  VARCHAR2(30),
    "BRANCH_ID" VARCHAR2(30),
    "USER_ID" VARCHAR2(50),
    "LOG_DATE" Date,
    "ACTIVITY_NAME" VARCHAR2(60),
   CONSTRAINT "USER_FREQUENT_HABITS_PK" PRIMARY KEY ("UNIQUE_ID") ENABLE);
   
create sequence USER_FREQ_HABITS_SEQ minvalue 1 maxvalue 9999999999 increment by 1 start with 1;