alter table PROD_CAT_DEF_FEATURES add PRODUCT_LEVEL_VISIBILITY NUMBER(1);

CREATE TABLE "PROD_CAT_FEATURE_GROUP_ORDER" (
    "UNIQUE_ID" NUMBER(15) NOT NULL ENABLE, 
	  "PRODUCT_CATEGORY" NUMBER(15) NOT NULL ENABLE,
    "GROUP_NAME" VARCHAR2(100),
    "PRIORITY" NUMBER(15),
   CONSTRAINT "PROD_CAT_FEA_GRP_ORDER_PK" PRIMARY KEY ("UNIQUE_ID") ENABLE);

create sequence PROD_CAT_FEAT_GRP_SEQ minvalue 1 maxvalue 9999999999 increment by 1 start with 1;

CREATE TABLE DEPOSIT_COMMENT
  (
    ID                NUMBER(10),
    ACCOUNT_NUMBER   VARCHAR2(20),
    ACCOUNT_NAME      VARCHAR2(100),
    ACTION_DATE       DATE,
    NEXT_ACTION_DATE DATE,
    BUSINESS_DATE    DATE,
    CREATED_DATE      DATE,
    USER_DEF_COMMNETS VARCHAR2(200),
    CREATED_BY        VARCHAR2(20),
    COMMENT_TYPE      VARCHAR2(30),
    STAND_COMMENT     NUMBER(10),
    AUTO_COMMENT      NUMBER(10)
  );
 
 
  CREATE SEQUENCE DEPOSIT_COMMENT_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 999999999
    NOMINVALUE
    NOCYCLE
    CACHE 20
    NOORDER;
