CREATE TABLE LOAN_OFFICER_USER_MAPPING (

    ID                      		NUMBER(5),
    LOGIN_USER          	   		VARCHAR2(10),
    LOAN_OFFICER                    VARCHAR2(10),
    BRANCH                      	VARCHAR2(10));
  	
CREATE SEQUENCE LOAN_OFFICER_USER_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOMINVALUE NOCYCLE ORDER;