CREATE TABLE LOAN_OFFICER_USER_MAPPING (

    ID                      		NUMBER(5) NOT NULL ,
    LOGIN_USER          	   		VARCHAR2(20),
    LOAN_OFFICER                    VARCHAR2(20),
    BRANCH                      	VARCHAR2(10),
    CONSTRAINT LOAN_OFFICER_USER_MAPPING_PK PRIMARY KEY (ID));
  	
CREATE SEQUENCE LOAN_OFFICER_USER_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOMINVALUE NOCYCLE ORDER;