--update LOAN_LEDGER_POSTING_PARAMETERS set AFFECTS_CREDIT_LIFE_REBATE= 1, AFFECTS_ACC_HEALTH_REBATE= 1, AFFECTS_SPECIAL_RES_REBATE_1= 1, 
--AFFECTS_SPECIAL_RES_REBATE_2= 1,AFFECTS_COLLATERAL_INS_REBATE= 1 where UNIQUE_ID=1502;
--
--update LOAN_LEDGER_POSTING_PARAMETERS 
--set AFFECTS_PRINCIPAL_DUE=1,  AFFECTS_INTEREST_DUE=1, AFFECTS_ESCROW_DUE=1, AFFECTS_NONESCROW_DUE=1, AFFECTS_ESCROW_BALANCE=1,
-- AFFECTS_NONESCROW_BALANCE=1  where UNIQUE_ID in (1951, 1744, 1544);

--update LOAN_LEDGER_POSTING_PARAMETERS 
--set AFFECTS_PRINCIPAL_DUE=1  where UNIQUE_ID in (1528);

alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_DATE_LAST_ACTIVITY              default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_ORIG_LOAN_BALANCE             default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_PRINCIPAL_BALANCE             default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_PRINCIPAL_DUE                 default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_INTEREST_DUE                  default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_ESCROW_DUE                    default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_ESCROW_BALANCE                default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_NONESCROW_DUE                 default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_NONESCROW_BALANCE             default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_BANK_REBATE                   default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_CREDIT_LIFE_PREMIUM           default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_CREDIT_LIFE_REBATE            default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_ACC_HEALTH_PREMIUM            default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_ACC_HEALTH_REBATE             default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_OTHER_FEE_DUE                 default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_COLLATERAL_INS_DUE            default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_COLLATERAL_INS_PREMIUM        default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_COLLATERAL_INS_REBATE         default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_UNAPPLIED_FUND                default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_PARTIAL_PAYMENT               default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_COLL_LATE_CHARGE              default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_UNCOLL_LATE_CHARGE            default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_WAIVED_LATE_CHARGE            default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_DATE_LAST_TRANSACTION         default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_DATE_NEXT_DUE                 default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_LINE_OF_CREDIT                default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_UNUSED_LINE_OF_CREDIT         default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_NET_PAYOFF                    default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_PAYMENT_MAID                  default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_RETURNED_CHECKS               default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_INTEREST_YTD                  default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_INTEREST_MTD                  default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_INTEREST_LTD                  default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_ACCRUED_INTEREST              default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_LOAN_STATUS                   default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_PAYOUT_CODE                   default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_DATE_CLOSED                   default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_NEXTESCROWDISBURSEDATE        default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_PRINCIPAL_PAID_TO_DATE        default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_INTEREST_PAID_TO_DATE         default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_FUTURE_PAYMENT_COUNT          default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_DATE_PREVIOUS_ACTIVITY        default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_SPECIAL_RES_REBATE_1          default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_SPECIAL_RES_REBATE_2          default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_UNUSED_LCF_DUE                default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_PAYMENT_NUMBER                default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_ACCRUED_INTEREST_MTD          default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_ACCRUED_INTEREST_YTD          default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_ACCUMULATED_INTEREST          default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_NEXT_NONESCDISBURDATE         default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_DEALER_RESERVE_REBATE         default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_DEALER_HOLDBACK_REBATE        default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_SPECIAL_RESERVE1              default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_SPECIAL_RESERVE2              default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_LAST_STMT_BALANCE             default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_LAST_STMT_DATE                default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_LAST_PAYMENT_DATE             default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_DEALER_INTEREST               default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_DEALER_ACCRUED_INT            default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_DEALER_ACCUMULATED_INT        default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_ACCRUED_CHARGE1               default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_ACCUMULATED_CHARGE1           default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_ACCRUED_CHARGE2               default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_ACCUMULATED_CHARGE2           default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_UNUSED_LINE_COMMIT_FEE        default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_ACCRDUNUSEDLINECOMMFEE        default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_ACCUMUNUSEDLINECOMMFEE        default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_LOW_BORROWING_YTD             default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_AGGREGATE_BAL_YTD             default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_TAX_PAID_YTD                  default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_PRE_YEAR_TAX_PAID             default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_PRE_YEAR_INT_PAID             default 0; 

ALTER TABLE LOAN_LEDGER_POSTING_PARAMETERS
ADD AFFECTS_LAST_CURT_AMOUNT NUMBER(1) DEFAULT 0;

ALTER TABLE LOAN_LEDGER_POSTING_PARAMETERS
ADD AFFECTS_LAST_CURT_DATE NUMBER(1) DEFAULT 0;

alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_LAST_CURT_AMOUNT              default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_LAST_CURT_DATE                default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_ACCRUED_INTEREST_NET          default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_DLR_INT_MTD                   default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_DLR_INT_YTD                   default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_DLR_INT_LTD                   default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_DLR_REBATE                    default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_DLR_HB_REBATE                 default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_AMORTIZED_BAL                 default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_PRNCP_DUE_DATE                default 0; 
alter table LOAN_LEDGER_POSTING_PARAMETERS modify  AFFECTS_INT_DUE_DATE                  default 0;

 
------------------LOAN_LEDGER_POSTING_PARAMETERS------------------
ALTER TABLE LOAN_LEDGER_POSTING_PARAMETERS ADD
AFFECTS_SCHD_PYMNT_DUE_DATE NUMBER (1) DEFAULT 0;
ALTER TABLE LOAN_LEDGER_POSTING_PARAMETERS ADD AFFECTS_MATURITY_DATE
NUMBER (1) DEFAULT 0;
ALTER TABLE LOAN_LEDGER_POSTING_PARAMETERS ADD AFFECTS_REMAIN_TERM
NUMBER (1) DEFAULT 0;
ALTER TABLE LOAN_LEDGER_POSTING_PARAMETERS ADD AFFECTS_ORGINAL_TERM
NUMBER (1) DEFAULT 0;
ALTER TABLE LOAN_LEDGER_POSTING_PARAMETERS ADD
AFFECTS_EXT_INT_ASSESSED_LTD NUMBER (1) DEFAULT 0;
ALTER TABLE LOAN_LEDGER_POSTING_PARAMETERS ADD
AFFECTS_EXT_INT_ASSESSED_YTD NUMBER (1) DEFAULT 0;
ALTER TABLE LOAN_LEDGER_POSTING_PARAMETERS ADD AFFECTS_EXT_INT_PAID_LTD
NUMBER (1) DEFAULT 0;
ALTER TABLE LOAN_LEDGER_POSTING_PARAMETERS ADD AFFECTS_EXT_INT_PAID_YTD
NUMBER (1) DEFAULT 0;
ALTER TABLE LOAN_LEDGER_POSTING_PARAMETERS ADD AFFECTS_TIMES_EXT_YTD
NUMBER (1) DEFAULT 0;
ALTER TABLE LOAN_LEDGER_POSTING_PARAMETERS ADD AFFECTS_TIMES_EXT_LTD
NUMBER (1) DEFAULT 0;
ALTER TABLE LOAN_LEDGER_POSTING_PARAMETERS ADD AFFECTS_LAST_TRAN_AMOUNT
NUMBER (1) DEFAULT 0;
ALTER TABLE LOAN_LEDGER_POSTING_PARAMETERS ADD AFFECTS_LAST_PYMNT_AMOUNT
NUMBER (1) DEFAULT 0;
ALTER TABLE LOAN_LEDGER_POSTING_PARAMETERS ADD AFFECTS_BANK_DISCOUNT
NUMBER (1) DEFAULT 0;
ALTER TABLE LOAN_LEDGER_POSTING_PARAMETERS ADD AFFECTS_LAST_EXT_DATE
NUMBER (1) DEFAULT 0;




------------------LOAN_ACCOUNT------------------
ALTER TABLE LOAN_ACCOUNT ADD LAST_TRANSACTION_AMOUNT NUMBER (20,6)
DEFAULT 0;
ALTER TABLE LOAN_ACCOUNT ADD LAST_PAYMENT_AMOUNT NUMBER (20,6) DEFAULT 0;

------------------LOAN_ACCOUNT_DAY------------------
ALTER TABLE LOAN_ACCOUNT_DAY ADD OPENING_SCHD_PYMNT_DUE_DATE DATE ;
ALTER TABLE LOAN_ACCOUNT_DAY ADD OPENING_MATURITY_DATE  DATE ;
ALTER TABLE LOAN_ACCOUNT_DAY ADD OPENING_ORIGINAL_TERM   VARCHAR2(50);
ALTER TABLE LOAN_ACCOUNT_DAY ADD OPENING_REMAINING_TERM   VARCHAR2(50);
ALTER TABLE LOAN_ACCOUNT_DAY ADD OPENING_EXTN_INT_ASSESSED_LTD
NUMBER(20,6)  DEFAULT 0;
ALTER TABLE LOAN_ACCOUNT_DAY ADD OPENING_EXTN_INT_ASSESSED_YTD
NUMBER(20,6)    DEFAULT 0;
ALTER TABLE LOAN_ACCOUNT_DAY ADD OPENING_EXTN_INT_PAID_LTD  NUMBER(20,6)
 DEFAULT 0;
ALTER TABLE LOAN_ACCOUNT_DAY ADD OPENING_EXTN_INT_PAID_YTD  NUMBER(20,6)
   DEFAULT 0;
ALTER TABLE LOAN_ACCOUNT_DAY ADD OPENING_TIMES_EXTN_YTD   NUMBER(10)
DEFAULT 0;
ALTER TABLE LOAN_ACCOUNT_DAY ADD OPENING_TIMES_EXTN_LTD   NUMBER(10)
DEFAULT 0;
ALTER TABLE LOAN_ACCOUNT_DAY ADD OPENING_LAST_TRAN_AMOUNT
NUMBER(20,6)  DEFAULT 0;
ALTER TABLE LOAN_ACCOUNT_DAY ADD OPENING_LAST_PYMNT_AMOUNT
NUMBER(20,6)  DEFAULT 0;
ALTER TABLE LOAN_ACCOUNT_DAY ADD OPENING_BANK_DISCOUNT
NUMBER(20,6)  DEFAULT 0;


ALTER TABLE LOAN_ACCOUNT_DAY ADD SCHD_PYMNT_DUE_DATE   VARCHAR2(50);
ALTER TABLE LOAN_ACCOUNT_DAY ADD MATURITY_DATE   VARCHAR2(50);
ALTER TABLE LOAN_ACCOUNT_DAY ADD ORIGINAL_TERM  VARCHAR2(50);
ALTER TABLE LOAN_ACCOUNT_DAY ADD REMAINING_TERM  VARCHAR2(50);
ALTER TABLE LOAN_ACCOUNT_DAY ADD EXTN_INT_ASSESSED_LTD NUMBER(20,6)
DEFAULT 0;
ALTER TABLE LOAN_ACCOUNT_DAY ADD EXTN_INT_ASSESSED_YTD NUMBER(20,6)
DEFAULT 0;
ALTER TABLE LOAN_ACCOUNT_DAY ADD EXTN_INT_PAID_LTD NUMBER(20,6)  DEFAULT 0;
ALTER TABLE LOAN_ACCOUNT_DAY ADD EXTN_INT_PAID_YTD NUMBER(20,6)  DEFAULT 0;
ALTER TABLE LOAN_ACCOUNT_DAY ADD TIMES_EXTN_YTD  NUMBER(10)   DEFAULT 0;
ALTER TABLE LOAN_ACCOUNT_DAY ADD TIMES_EXTN_LTD  NUMBER(10)   DEFAULT 0;
ALTER TABLE LOAN_ACCOUNT_DAY ADD LAST_TRAN_AMOUNT NUMBER(20,6)  DEFAULT 0;
ALTER TABLE LOAN_ACCOUNT_DAY ADD LAST_PYMNT_AMOUNT NUMBER(20,6)  DEFAULT 0;
ALTER TABLE LOAN_ACCOUNT_DAY ADD BANK_DISCOUNT NUMBER(20,6)  DEFAULT 0;


 -------ADDING LOAN ENTRY TYPE FOR SIL
insert into ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, DEBIT_OR_CREDIT, DESCRIPTION, ACCOUNT_CATEGORY)
values ((select max(UNIQUE_ID) from ENTRY_TYPE) + 1,
 (select max(UNIQUE_ID) from ENTRY_TYPE) + 1,
 null, '1', 'Loan Extension', '2');

insert into LOAN_ENTRY_TYPE (UNIQUE_ID, ACCOUNT_TYPE_ID, TRAN_TYPE_GROUP_ID, EVENT_TYPE_ID, IS_MONETARY)
values ((select max(UNIQUE_ID) from ENTRY_TYPE),
'208', 'REGULAR', '42',  '0');

--INSERT INTO LOAN_LEDGER_POSTING_PARAMETERS(UNIQUE_ID, INSTITUTION_ID, ENTRY_TYPE_ID, ACCOUNT_TYPE_ID,
--AFFECTS_BANK_DISCOUNT, AFFECTS_PRINCIPAL_BALANCE, AFFECTS_ACCRUED_INTEREST_NET,AFFECTS_ACCRUED_INTEREST, AFFECTS_DATE_NEXT_DUE,
--AFFECTS_SCHD_PYMNT_DUE_DATE, AFFECTS_MATURITY_DATE, AFFECTS_ORGINAL_TERM, AFFECTS_REMAIN_TERM,
--AFFECTS_EXT_INT_ASSESSED_LTD, AFFECTS_EXT_INT_ASSESSED_YTD, AFFECTS_EXT_INT_PAID_LTD, AFFECTS_EXT_INT_PAID_YTD,
--AFFECTS_TIMES_EXT_YTD, AFFECTS_TIMES_EXT_LTD,
--AFFECTS_LAST_EXT_DATE,
--AFFECTS_DATE_LAST_ACTIVITY, AFFECTS_DATE_PREVIOUS_ACTIVITY)
--
--    VALUES((select max(UNIQUE_ID) from ENTRY_TYPE),
-- '1', (select max(UNIQUE_ID) from ENTRY_TYPE), '208',
--1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1);


-------ADDING LOAN ENTRY TYPE FOR IL
insert into ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, DEBIT_OR_CREDIT, DESCRIPTION, ACCOUNT_CATEGORY)
values ((select max(UNIQUE_ID) from ENTRY_TYPE) + 1,
 (select max(UNIQUE_ID) from ENTRY_TYPE) + 1,
 null, '1', 'Loan Extension', '2');

insert into LOAN_ENTRY_TYPE (UNIQUE_ID, ACCOUNT_TYPE_ID, TRAN_TYPE_GROUP_ID, EVENT_TYPE_ID, IS_MONETARY)
values ((select max(UNIQUE_ID) from ENTRY_TYPE),
'207', 'REGULAR', '42',  '0');

--INSERT INTO LOAN_LEDGER_POSTING_PARAMETERS(UNIQUE_ID, INSTITUTION_ID, ENTRY_TYPE_ID, ACCOUNT_TYPE_ID,
--
--AFFECTS_BANK_DISCOUNT, AFFECTS_PRINCIPAL_BALANCE, AFFECTS_ACCRUED_INTEREST_NET,AFFECTS_ACCRUED_INTEREST, AFFECTS_DATE_NEXT_DUE,
--AFFECTS_SCHD_PYMNT_DUE_DATE, AFFECTS_MATURITY_DATE, AFFECTS_ORGINAL_TERM, AFFECTS_REMAIN_TERM,
--AFFECTS_EXT_INT_ASSESSED_LTD, AFFECTS_EXT_INT_ASSESSED_YTD, AFFECTS_EXT_INT_PAID_LTD, AFFECTS_EXT_INT_PAID_YTD,
--AFFECTS_TIMES_EXT_YTD, AFFECTS_TIMES_EXT_LTD,
--AFFECTS_LAST_EXT_DATE,
--AFFECTS_DATE_LAST_ACTIVITY, AFFECTS_DATE_PREVIOUS_ACTIVITY)
--    VALUES((select max(UNIQUE_ID) from ENTRY_TYPE),
-- '1', (select max(UNIQUE_ID) from ENTRY_TYPE), '207',
--1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1);


-------ADDING LOAN ENTRY TYPE FOR Mort
insert into ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, DEBIT_OR_CREDIT, 
DESCRIPTION, ACCOUNT_CATEGORY)
values ((select max(UNIQUE_ID) from ENTRY_TYPE) + 1,
 (select max(UNIQUE_ID) from ENTRY_TYPE) + 1,
 null, '1', 'Loan Extension', '2');

insert into LOAN_ENTRY_TYPE (UNIQUE_ID, ACCOUNT_TYPE_ID, 
TRAN_TYPE_GROUP_ID, EVENT_TYPE_ID, IS_MONETARY)
values ((select max(UNIQUE_ID) from ENTRY_TYPE),
'110', 'REGULAR', '42',  '0');

--INSERT INTO LOAN_LEDGER_POSTING_PARAMETERS(UNIQUE_ID, INSTITUTION_ID, 
--ENTRY_TYPE_ID, ACCOUNT_TYPE_ID,
--
--AFFECTS_BANK_DISCOUNT, AFFECTS_PRINCIPAL_BALANCE, 
--AFFECTS_ACCRUED_INTEREST_NET,AFFECTS_ACCRUED_INTEREST, 
--AFFECTS_DATE_NEXT_DUE,
--AFFECTS_SCHD_PYMNT_DUE_DATE, AFFECTS_MATURITY_DATE, 
--AFFECTS_ORGINAL_TERM, AFFECTS_REMAIN_TERM,
--AFFECTS_EXT_INT_ASSESSED_LTD, AFFECTS_EXT_INT_ASSESSED_YTD, 
--AFFECTS_EXT_INT_PAID_LTD, AFFECTS_EXT_INT_PAID_YTD,
--AFFECTS_TIMES_EXT_YTD, AFFECTS_TIMES_EXT_LTD,
--AFFECTS_LAST_EXT_DATE,
--AFFECTS_DATE_LAST_ACTIVITY, AFFECTS_DATE_PREVIOUS_ACTIVITY)
--    VALUES((select max(UNIQUE_ID) from ENTRY_TYPE),
-- '1', (select max(UNIQUE_ID) from ENTRY_TYPE), '110',
--1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1);


--update  LOAN_LEDGER_POSTING_PARAMETERS set AFFECTS_INT_DUE_DATE=1, AFFECTS_PRNCP_DUE_DATE=1 where UNIQUE_ID in (
--select UNIQUE_ID from LOAN_ENTRY_TYPE where ACCOUNT_TYPE_ID in(207, 208, 110) and EVENT_TYPE_ID='42');


ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD (EFFECTIVE_PRINCIPAL_BAL number(20,2));
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD (EFFECTIVE_ESCROW_BAL number(20,2));
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD (EFFECTIVE_AH_BAL number(20,2));

ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD (EFFECTIVE_DATE_NEXT_DUE DATE);

--update LOAN_LEDGER_POSTING_PARAMETERS SET AFFECTS_INTEREST_PAID_TO_DATE=0;







