--update property_definition set VALID_VALUES = 'java.lang.Integer:{default={8=Earthquake Insurance,9=SpecialInsurance,6=Pvt Mortgage Ins(PMI),1=Hazard Insurance,7=Flood Insurance,11=Credit Life Insurance, 12=A/H Ins, 13=Accident Death Ins}}'
--where property_name like 'EscrowType' and ENTITY_TYPE_DEFINITION_ID=472;
--
--update property_definition set DESCRIPTION_FIELD = 0 where 
--property_name in ('DateLastPremiumPaid', 'FundIncludeInBalance');
--
--
--update property_definition set primary = 0 where 
--property_name in ('DateLastPremiumPaid', 'FundIncludeInBalance', 'EscrowType');

ALTER TABLE LOAN_ACCOUNT ADD ( NO_OF_DAYS_PAST_DUE NUMBER(10));

ALTER TABLE LOAN_ACCOUNT ADD(ORIGINAL_LOAN_TERM VARCHAR2(30));
ALTER TABLE LOAN_ACCOUNT ADD(EXTENSION_ID NUMBER(20));

CREATE TABLE EXTENSION_NEW(
	UNIQUE_ID NUMBER(20),
	EXT_INTEREST_ASSESS_LTD NUMBER(20,5),
	EXT_INTEREST_ASSESS_YTD NUMBER(20,5),
	EXT_CHARGES_PAID_YTD NUMBER(20,5),
	EXT_CHARGES_PAID_LTD NUMBER(20,5),
	TIMES_EXT_LTD NUMBER(10),
	TIMES_EXT_YTD NUMBER(10),
	LAST_EXT_DATE DATE,
	EXT_EXPIRATION_DATE DATE
);

CREATE TABLE EXTENSION_HISTORY(
	UNIQUE_ID NUMBER(20),
	EXTENSION_DATE DATE,
	EXTENSION_TYPE NUMBER(3),
	NO_OF_PAYMENTS_EXTENDED NUMBER(10),
	EXTENSION_INTEREST NUMBER(20,5),
	PAYMENT_STATUS NUMBER(3),
	COMMENTS VARCHAR2(100),
	EXTENSION_ID NUMBER(20)
);


CREATE SEQUENCE EXTENSION_HIS_UID_SEQ START WITH 1;
CREATE SEQUENCE EXTENSION_UID_SEQ START WITH 1;

ALTER TABLE EXTENSION_NEW ADD(EXT_INTEREST_PAID_LTD NUMBER(20));
ALTER TABLE EXTENSION_NEW ADD(EXT_INTEREST_PAID_YTD NUMBER(20));

--UPDATE ENTITY_TYPE_DEFINITION SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.Anchor' WHERE
--TYPE_NAME LIKE 'Anchor';
--
--UPDATE ENTITY_TYPE_DEFINITION SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.CreditTenants' WHERE
--TYPE_NAME LIKE 'CreditTenants';
--
--UPDATE ENTITY_TYPE_DEFINITION SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.FlatsDetails' WHERE
--TYPE_NAME LIKE 'FlatsDetails';
--
--UPDATE ENTITY_TYPE_DEFINITION SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.ApartmentDetails' WHERE
--TYPE_NAME LIKE 'ApartmentDetails';
--
--UPDATE ENTITY_TYPE_DEFINITION SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.HotelVariables',
--TYPE_NAME='HotelVariables' WHERE 
--TYPE_NAME LIKE 'HotelVaribles';
--
--UPDATE ENTITY_TYPE_DEFINITION SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.AnchoredShoppingCentreVariables' WHERE
--TYPE_NAME LIKE 'AnchoredShoppingCentreVariables';
--
--update ENTITY_TYPE_DEFINITION set TYPE_DESCRIPTION = 'Hotel Variables' where ENTITY_TYPE_DEFINITION_ID = 42002;
--
--INSERT
--	INTO PROPERTY_DEFINITION
--	(
--		PROPERTY_DEFINITION_ID,
--		ENTITY_TYPE_DEFINITION_ID,
--		PROPERTY_NAME,
--		PROPERTY_INDEX,
--		PROPERTY_DESCRIPTION,
--		VALUE_TYPE_DEFINITION_ID,
--		DESCRIPTION_FIELD,
--		DESCRIPTION_FIELD_OVERRIDEN,
--		DEFAULT_VALUE,
--		DEFAULT_VALUE_OVERRIDEN,
--		VALID_VALUES,
--		VALID_VALUES_OVERRIDEN,
--		MANDATORY,
--		MANDATORY_OVERRIDEN,
--		HIDDEN,
--		HIDDEN_OVERRIDEN,
--		EDITABLE,
--		EDITABLE_OVERRIDEN,
--		INHERITED,
--		CAN_EDIT_DEFINITION,
--		CAN_DELETE_DEFINITION,
--		CATEGORY_OVERRIDEN,
--		CATEGORY,
--		PRIMARY_OVERRIDEN,
--		PRIMARY
--	)
--VALUES
--	(
--		(SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION),
--		41483,
--		'BalloonPaymentAmount',
--		7,
--		'Balloon Payment Amount',
--		8,
--		0,
--		0,
--		NULL,
--		0,
--		'com.vsoftcorp.finance.Money:{default={}}',
--		0,
--		0,
--		0,
--		0,
--		0,
--		1,
--		0,
--		0,
--		1,
--		1,
--		0,
--		'U',
--		0,
--		0
--	);

ALTER TABLE loan_Account ADD  NEXT_DUE_DATE_BEFORE_POST date ;

ALTER TABLE LOAN_ACCOUNT
ADD DAY_LATECHARGE_AMOUNT NUMBER(10,2) DEFAULT 0;

ALTER TABLE LOAN_ACCOUNT
ADD NO_OF_DAYS_PASTDUE_BEFOREPOST NUMBER(10) DEFAULT 0;

ALTER TABLE LOAN_ACCOUNT ADD(TAX_EXEMPTION_CODE NUMBER(20));

ALTER TABLE LOAN_ACCOUNT DROP COLUMN ORIGINAL_LOAN_TERM;

ALTER TABLE EXTENSION_NEW DROP COLUMN EXT_CHARGES_PAID_YTD;

ALTER TABLE EXTENSION_NEW DROP COLUMN EXT_CHARGES_PAID_LTD;

ALTER TABLE LOAN_ACCOUNT ADD(DATE_LAST_MAINTAINED date);
