UPDATE LOAN_ACCOUNT  SET INTEREST_PAID_PYTD=0 WHERE INTEREST_PAID_PYTD IS NULL;
ALTER TABLE LOAN_ACCOUNT ADD (LATE_CHARGE_ASSESSED_LIFE NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(FUTURE_PAYMENT NUMBER(20,5));

--UPDATE ASSOCIATE_DEFINITION SET ENTITY_TYPE_DEFINITION_ID=489 WHERE
--ASSOCIATE_NAME LIKE 'RateChangeHistory' and ASSOCIATE_DEFINITION_ID='569';
--
--UPDATE ASSOCIATE_DEFINITION SET ENTITY_TYPE_DEFINITION_ID=489 WHERE
--ASSOCIATE_NAME LIKE 'PaymentAdjustmentHistory' and ASSOCIATE_DEFINITION_ID='6623';
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION), 531, 'CouponThroughDate', 4, 'Coupon Through Date', 5, 0, 0, NULL, 0, 'com.vsoftcorp.time.Date:{default={}}', 0, 0, 0, 0, 1, 0, 0, 'UC', 0, 0);
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION), 41302, 'DailyAccrualInsurance', 11, 'Daily Accrual Insurance', 3, 0, 0, NULL, 0, 'java.lang.Double:{default={}}', 0, 0, 0, 0, 1, 0, 0, 'u', 0, 0);
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION), 41302, 'InsuranceAccrualInterest', 11, 'Insurance Accrual Interest', 3, 0, 0, NULL, 0, 'java.lang.Double:{default={}}', 0, 0, 0,  0, 1, 0, 0, 'u', 0, 0);
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION), 41302, 'InsuranceAccumulatedInterest', 11, 'Insurance Accumulated Interest', 3, 0, 0, NULL, 0, 'java.lang.Double:{default={}}', 0, 0, 0, 0, 1, 0, 0, 'u', 0, 0);
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION), 702, 'OriginalIndexDate', 7, 'Original Index Date', 5, 0, 0, NULL, 0, 'com.vsoftcorp.time.Date:{default={}}', 0, 0, 0, 0, 1, 0, 0, 'U', 0, 0);

drop table ASSET_INSURANCE;

drop table CREDIT_LINE CASCADE CONSTRAINT;

alter table loan_account drop column PRIMARY_OFFICER;
alter table loan_account drop column COLLECTION_OFFICER;
alter table loan_account drop column COLLECTION_OFFICER_CODE;
alter table loan_account drop column LOAN_PURPOSE_CODE;
alter table loan_account drop column INTEREST_BASE_CODE;
alter table loan_account drop column CALL_REPORT_CODE;
alter table loan_account drop column REPAYMENT_MODE;
alter table loan_account drop column PRINT_BILLING_NOTICE;
alter table loan_account drop column PRINT_COUPON_BOOK;
alter table loan_account drop column AUTO_DRAFT;
alter table loan_account drop column ANNUAL_PERCENTAGE_RATE;
alter table loan_account drop column FREQUENCY_PRINCIPAL;
alter table loan_account drop column LINE_OF_CREDIT;
alter table loan_account drop column AVAILED_LOAN_AMOUNT;
alter table loan_account drop column EXAMINER_CLASSIFICATION_CODE;
alter table loan_account drop column BALLOON_PAYMENT;
alter table loan_account drop column FIRST_PAYMENT_DATE;
alter table loan_account drop column LATE_CHARGE_CODE;
alter table loan_account drop column IS_AMORTIZED;
alter table loan_account drop column LOAN_TYPE_ID;
alter table loan_account drop column DAYS_IN_A_YEAR;
alter table loan_account drop column CHARGE_DISC1;
alter table loan_account drop column CHARGE_DISC2;
alter table loan_account drop column CHARGE_CODE1;
alter table loan_account drop column CHARGE_CODE2;
alter table loan_account drop column PROPERTY_OR_COLLATERAL;
alter table loan_account drop column PRINCIPLE_BILLING_AMOUNT;
alter table loan_account drop column PAYMENTS_SCHEDULED;
alter table loan_account drop column PRINT_PAST_DUE_NOTICE;
alter table loan_account drop column NEXT_PRINCIPLE_DUE;
alter table loan_account drop column MINIMUM_INTEREST_CHARGE;
alter table loan_account drop column LATE_CHRG_INDICATOR;
alter table loan_account drop column APPLY_PAYMENTS_AS_BILLED;
alter table loan_account drop column NEXT_REVIEW_DATE;
alter table loan_account drop column PRINCIPAL_INTEREST_PAYMENT;
alter table loan_account drop column PREPAYMENT_PENALTY_CODE;
alter table loan_account drop column PREPAYMENT_PENALTY;
alter table loan_account drop column LINE_OF_CREDIT_ID; 
