CREATE TABLE "AUTO_COMMENT_MAP" (
    "ID"                    NUMBER(10) PRIMARY KEY,
    "EVENT_ID"              VARCHAR2(30),
    "COMMENT_ID"            VARCHAR2(50)
    );
    
CREATE SEQUENCE "AUTO_COMMENT_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOMINVALUE NOCYCLE ORDER;