 CREATE TABLE "EXTRACT_FILE_LOG" (

 	  "ID"                          NUMBER(10) PRIMARY KEY,
    "FILE_ID"                   NUMBER(30,5),
    "FILE_NAME"      		    VARCHAR2(50), 
    "FILE_STATUS"           	NUMBER(20,5),
    "RESPONSE_STATUS"           NUMBER(20,5),
    "NUMBER_OF_RECORDS"			NUMBER(30),
    "CREATED_DATE"				DATE
    );
    
    CREATE SEQUENCE "EXTRACT_FILE_LOG_ID_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOMINVALUE NOCYCLE ORDER;

CREATE TABLE "MGIC_FILE_EXTRACT" (

 	  "ID"                          NUMBER(10) PRIMARY KEY,
    "RECORD_TYPE"                   VARCHAR2(30),
    "CERTIFICATE_NUMBER"            VARCHAR2(50), 
    "SERVICE_LOAN_NUMBER"           VARCHAR2(50), 
    "COVERAGE_BEGIN_DATE"           DATE,
    "PREMIUM_CALC_MORTGAGE_AMT"     NUMBER(20,5),
    "RATE_PERIOD_CODE"       	    VARCHAR2(20),
    "NO_OF_PERIODS_BILLED"   		NUMBER(10),
    "PREMIUM_RATE"                  NUMBER(20,5),
    "PREMIUM_TAX_RATE"				NUMBER(20,5),
    "PREMIUM_AMT_DUE"               NUMBER(20,5),
   	"PREMIUM_TAX_DUE"		        NUMBER(20,5),
    "SRC_OF_PREMIUM_TAXES"          VARCHAR2(50), 
    "RENEWAL_OPTION"		        VARCHAR2(50), 
    "BILL_FREQUECY_PERIOD"		    VARCHAR2(50), 
    "REF_NON_REF_PREMIUM_CODE"		VARCHAR2(50), 
    "BILL_PERIOD_FACTOR"            VARCHAR2(50), 
    "COVERAGE_TYPE"                 VARCHAR2(40),
    "BORROWER_NAME"                 VARCHAR2(100),
    "BORROWER_SSN"                  VARCHAR2(30),
    "RECORD_STATUS"                 NUMBER(10),
    "FILLER"                        VARCHAR2(100),
    "FILE_ID"						NUMBER(30,5),
    "STATUS_MESSAGE"				VARCHAR2(350),
    "ACCOUNT_NUM_CHANGED"			NUMBER(5) DEFAULT 0,
    "BILL_DUE_DATE"					DATE,
    "CREATED_DATE"					DATE,
     CONSTRAINT FK_EXSTO FOREIGN KEY(FILE_ID) REFERENCES EXTRACT_FILE_LOG(ID));
  	
  	
CREATE SEQUENCE "MGIC_FILE_EXTRACT_ID_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOMINVALUE NOCYCLE ORDER;
