 INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(007, '007', 0, 207, null, 'Escrow Interest Payment ', '1');
INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(207, '207', 1, 007, null, 'Escrow Interest Payment Reversal', '1');
INSERT INTO ENTRY_TYPE(UNIQUE_ID,ID,INSTITUTION_ID,DEBIT_OR_CREDIT,DESCRIPTION,ACCOUNT_CATEGORY,POSTING_SEQUENCE,IS_REVERSAL)
VALUES(8807, '8807', NULL, '0', 'EscrowInterestPayment', 2, NULL, '0');
INSERT INTO LOAN_ENTRY_POSTING_RULE(POSTING_RULE_ID, affects_escrow_balance) VALUES(8807, 1);
INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID) VALUES(8807,8807,8807,8807);
insert into loan_event_entry_type_link values(007,8807);

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (007,(SELECT unique_id FROM entry_type WHERE ID='1903'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (207,(SELECT unique_id FROM entry_type WHERE ID='1803'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_ESCROW_BALANCE=1 WHERE POSTING_RULE_ID=8807;