INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(62, '062', 0, 262, null, 'Loan Modification-Customer Repayment', '1');
INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(262, '262', 1, 62, null, 'Loan Modification-Customer Repayment Reversal', '0');
INSERT INTO ENTRY_TYPE(UNIQUE_ID,ID,INSTITUTION_ID,DEBIT_OR_CREDIT,DESCRIPTION,ACCOUNT_CATEGORY,POSTING_SEQUENCE,IS_REVERSAL)
  VALUES(8862, '8862', null, '0', 'Loan Modification-Customer Repayment', 2, NULL, '0');
ALTER TABLE LOAN_ENTRY_POSTING_RULE ADD  AFF_LOAN_MODIFY_CUST_RPMENT NUMBER(20) DEFAULT 0;
INSERT INTO LOAN_ENTRY_POSTING_RULE(POSTING_RULE_ID, AFF_LOAN_MODIFY_CUST_RPMENT) VALUES(8862,1);
INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID) VALUES(8862,8862,8862,8862);
insert into loan_event_entry_type_link values(62,8862);


INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (062,(SELECT unique_id FROM entry_type WHERE ID='1977'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (262,(SELECT unique_id FROM entry_type WHERE ID='1877'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_CUSTOMER_PARTIAL_AMT=1 WHERE POSTING_RULE_ID=8862;



INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(63, '063', 0, 263, null, 'Loan Modification-Regular Repayment', '1');
INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(263, '263', 1, 63, null, 'Loan Modification-Regular Repayment Reversal', '0');
INSERT INTO ENTRY_TYPE(UNIQUE_ID,ID,INSTITUTION_ID,DEBIT_OR_CREDIT,DESCRIPTION,ACCOUNT_CATEGORY,POSTING_SEQUENCE,IS_REVERSAL)
  VALUES(8863, '8863', null, '0', 'Loan Modification-Regular Repayment', 2, NULL, '0');
ALTER TABLE LOAN_ENTRY_POSTING_RULE ADD  AFF_LOAN_MODIFY_REG_RPMENT NUMBER(20) DEFAULT 0;
INSERT INTO LOAN_ENTRY_POSTING_RULE(POSTING_RULE_ID, AFF_LOAN_MODIFY_REG_RPMENT) VALUES(8863,1);
INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID) VALUES(8863,8863,8863,8863);
insert into loan_event_entry_type_link values(63,8863);

--customer partial bucket
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (063,(SELECT unique_id FROM entry_type WHERE ID='1977'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (263,(SELECT unique_id FROM entry_type WHERE ID='1877'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_CUSTOMER_PARTIAL_AMT=1 WHERE POSTING_RULE_ID=8863;
--principle
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (063,(SELECT unique_id FROM entry_type WHERE ID='1901'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (263,(SELECT unique_id FROM entry_type WHERE ID='1801'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_PRINCIPAL_BALANCE=1 WHERE POSTING_RULE_ID=8863;
--Interest
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (063,(SELECT unique_id FROM entry_type WHERE ID='1905'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (263,(SELECT unique_id FROM entry_type WHERE ID='1805'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_INTEREST_PAID=1 WHERE POSTING_RULE_ID=8863;
--acct inter net
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (063,(SELECT unique_id FROM entry_type WHERE ID='1923'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (263,(SELECT unique_id FROM entry_type WHERE ID='1823'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_ACCRUED_INT_NET=1 WHERE POSTING_RULE_ID=8863;
--other fee
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (063,(SELECT unique_id FROM entry_type WHERE ID='1904'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (263,(SELECT unique_id FROM entry_type WHERE ID='1804'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_OTHER_FEE_DUE=1 WHERE POSTING_RULE_ID=8863;
--collected late charge
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (063,(SELECT unique_id FROM entry_type WHERE ID='1902'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (263,(SELECT unique_id FROM entry_type WHERE ID='1802'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_COLL_LATE_CHARGE=1 WHERE POSTING_RULE_ID=8863;
--un collected late charge
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (063,(SELECT unique_id FROM entry_type WHERE ID='1907'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (263,(SELECT unique_id FROM entry_type WHERE ID='1807'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_UNCOLL_LATE_CHARGE=1 WHERE POSTING_RULE_ID=8863;
--sales tax
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (063,(SELECT unique_id FROM entry_type WHERE ID='1990'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (263,(SELECT unique_id FROM entry_type WHERE ID='1890'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_SALES_TAX_AMOUNT=1 WHERE POSTING_RULE_ID=8863;
--unapplied fund
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (063,(SELECT unique_id FROM entry_type WHERE ID='1909'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (263,(SELECT unique_id FROM entry_type WHERE ID='1809'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_UNAPPLIED_FUND=1 WHERE POSTING_RULE_ID=8863;
--credit life fund
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (063,(SELECT unique_id FROM entry_type WHERE ID='1906'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (263,(SELECT unique_id FROM entry_type WHERE ID='1806'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_CREDIT_LIFE_BAL=1 WHERE POSTING_RULE_ID=8863;
--ah (doubt)
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (063,(SELECT unique_id FROM entry_type WHERE ID='1908'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (263,(SELECT unique_id FROM entry_type WHERE ID='1808'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_AH_BALANCE=1 WHERE POSTING_RULE_ID=8863;




--customer partial bucket for bankruptcy payment
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (095,(SELECT unique_id FROM entry_type WHERE ID='1877'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (295,(SELECT unique_id FROM entry_type WHERE ID='1977'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_CUSTOMER_PARTIAL_AMT=1 WHERE POSTING_RULE_ID=8895;





  
 
 
  
  





