INSERT INTO ENTITY_TYPE_INSTANCE(ENTITY_TYPE_INSTANCE_ID, TYPE_NAME, TYPE_DESCRIPTION, STATUS, ENTITY_TYPE_INST_CLASS_NAME)
  VALUES((SELECT MAX(ENTITY_TYPE_INSTANCE_ID)+1 FROM ENTITY_TYPE_INSTANCE), 'DistributionHead', 'Distribution Head', 1, 'com.vsoftcorp.loan.model.entities.DistributionHead');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES((SELECT MAX(ENTITY_TYPE_INSTANCE_ID) FROM ENTITY_TYPE_INSTANCE), 'Code', 'java.lang.String:49');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES((SELECT MAX(ENTITY_TYPE_INSTANCE_ID) FROM ENTITY_TYPE_INSTANCE), 'Description', 'java.lang.String:Yield');
  
  
update loan_entry_posting_rule set aff_yield_amt=1 where posting_rule_id=80;