UPDATE PROPERTY_DEFINITION SET PROPERTY_NAME='OriginalAppraisedValue',PROPERTY_DESCRIPTION='Original Appraised Value' WHERE PROPERTY_NAME LIKE 'AppraisedEvaluationValue';
UPDATE PROPERTY_DEFINITION SET PROPERTY_NAME='OriginalAppraisalDate',PROPERTY_DESCRIPTION='Original Appraisal Date'  WHERE PROPERTY_NAME LIKE 'AppraisalEvaluationDate';
UPDATE PROPERTY_DEFINITION SET PROPERTY_NAME='OriginalLTV',PROPERTY_DESCRIPTION='Original LTV'  WHERE PROPERTY_NAME LIKE 'LoanToValueRatio';
