CREATE OR REPLACE VIEW "ACTIVITY_LOG_VW" ( "UNIQUE_ID", "LINKED_ACCOUNT","DELETED_ACCOUNT","ACCOUNT_NUMBER", "CARD_NUMBER", "STATUS_CODE", "CARD_STATUS", "LIMIT_GROUP", "EMBOSS_NAME", "ACCOUNT_TYPE", "FIRST_NAME", "LAST_NAME", "MIDDLE_NAME", "ADDRESS_LINE1", "ADDRESS_LINE2", "WORK_PHONE", "HOME_PHONE", "SSN_TIN", "PID", "MMN", "DOB", "CITY", "STATE", "ZIP" )
AS
SELECT DISTINCT DS.SUBCRIPTION_ID,
CASE WHEN (DA.IS_PRIMARY !=1 AND DA.UPDATED_DATE BETWEEN SYSDATE-1 AND SYSDATE) THEN DA.ACCOUNT_NUMBER END AS LINKED_ACCOUNT,
CASE WHEN (DAU.REV_TYPE =2 AND DAU.UPDATED_DATE BETWEEN SYSDATE-1 AND SYSDATE) THEN DAU.ACCOUNT_NUMBER END AS DELETE_ACCOUNT,
DS.PRIMARY_ACCOUNT_NUMBER,
DS.SUBSCRIPTION_NUMBER,
DAV.STATUS_CODE,
DS.STATUS,
LG.NAME,
DU.EMBOSS_LINE1,
DAV.ACCOUNT_TYPE_ID,
PE.FIRST_NAME,
PE.LAST_NAME,
PE.MIDDLE_NAME,
GA.LINE_1,
GA.LINE_2,
CASE
WHEN HTA.PHONE IS NOT NULL
AND CTA.PHONE IS NOT NULL
THEN HTA.PHONE
ELSE WTA.PHONE
END AS CUST_DAYTIME_PHONE,
CASE
WHEN CTA.PHONE IS NOT NULL
THEN CTA.PHONE
ELSE HTA.PHONE
END AS CUST_EVENING_PHONE,
SSN_TIN.PARTY_REGISTERD_ID,
DL.PARTY_REGISTERD_ID,
PE.MOTHERS_MAIDEN_NAME,
PE.DATE_OF_BIRTH,
GA.CITY,
GA.STATE,
GA.ZIP_1
FROM PARTY_ACCOUNT_ROLE_VW PARV,
DEBITCARD_SUBSCRIPTION DS,
DEPOSIT_ACCOUNT_VW DAV,
LIMIT_GROUP LG,
DEBITCARD_USER DU,
PERSON PE,
ACCOUNT_STATEMENT_GENERATOR ASG,
ACCOUNT_STATEMENT_ADDRESS ASA ,
PARTY_ADDRESS PA,
GEOGRAPHIC_ADDRESS GA,
TELECOM_ADDRESS WTA,
TELECOM_ADDRESS HTA,
TELECOM_ADDRESS CTA,
WEB_ADDRESS WA,
(SELECT MAX(ADDRESS_ID) ADDRESS_ID,
PARTY_ID
FROM PARTY_ADDRESS
WHERE ADDRESS_USE = 'WORK_PHONE'
GROUP BY PARTY_ID
) TPAW ,
(SELECT MAX(ADDRESS_ID) ADDRESS_ID,
PARTY_ID
FROM PARTY_ADDRESS
WHERE ADDRESS_USE = 'HOME_PHONE'
GROUP BY PARTY_ID
) TPAH ,
(SELECT MAX(ADDRESS_ID) ADDRESS_ID,
PARTY_ID
FROM PARTY_ADDRESS
WHERE ADDRESS_USE = 'CELL_PHONE'
GROUP BY PARTY_ID
) TPCP ,
(SELECT MAX(ADDRESS_ID) ADDRESS_ID,
PARTY_ID
FROM PARTY_ADDRESS
WHERE ADDRESS_USE = 'WEB'
GROUP BY PARTY_ID
)WPA,
( SELECT * FROM PARTY_REGISTERED_IDS WHERE TYPE IN ('SSN','TIN')
) SSN_TIN,
( SELECT * FROM PARTY_REGISTERED_IDS WHERE TYPE LIKE 'DRIVER%'
) DL,
DEBITCARD_ACCOUNTS DA,
DEBITCARD_ACCOUNTS_AUD DAU,
MAINTENANCE_LOG_VW MV,
PARTY_ASSOC_MAINT_LOG PV,
PARTY_INSTITUTION_ASSOCIATION PIA
WHERE DS.PRIMARY_ACCOUNT_NUMBER=DAV.ACCOUNT_NO
AND MV.ACCOUNT_ID(+) =DAV.ACCOUNT_ID
AND PV.UNIQUE_ASSOCIATION_ID(+)=PIA.UNIQUE_ASSOCIATION_ID
AND PIA.PARTY_ID =PARV.PARTY_ID
AND DS.LIMIT_GROUP_ID =LG.LIMIT_GROUP_ID
AND DS.PRIMARY_USER_ID =DU.USER_ID
AND PARV.PARTY_ID =DU.CORE_PARTY_ID
AND DU.CORE_PARTY_ID =PE.PARTY_ID
AND ASG.ACCOUNT_ID =DAV.ACCOUNT_ID
AND ASG.UNIQUE_ID =ASA.UNIQUE_ID
AND ASA.UNIQUE_PARTY_ADDRESS_ID=PA.UNIQUE_PARTY_ADDRESS_ID
AND PA.ADDRESS_ID =GA.ADDRESS_ID
AND DU.CORE_PARTY_ID =TPAW.PARTY_ID(+)
AND DU.CORE_PARTY_ID =TPAH.PARTY_ID(+)
AND DU.CORE_PARTY_ID =TPCP.PARTY_ID(+)
AND DU.CORE_PARTY_ID =WPA.PARTY_ID(+)
AND TPAW.ADDRESS_ID = WTA.ADDRESS_ID(+)
AND TPAH.ADDRESS_ID = HTA.ADDRESS_ID(+)
AND TPCP.ADDRESS_ID = CTA.ADDRESS_ID(+)
AND WPA.ADDRESS_ID =WA.ADDRESS_ID(+)
AND DU.CORE_PARTY_ID =SSN_TIN.PARTY_ID(+)
AND DU.CORE_PARTY_ID =DL.PARTY_ID(+)
AND DS.SUBCRIPTION_ID =DA.SUBCRIPTION_ID(+)
AND DS.SUBCRIPTION_ID = DAU.SUBCRIPTION_ID(+)
AND (TRUNC(DS.STATUS_TIME) BETWEEN TRUNC(SYSDATE-1) AND TRUNC(SYSDATE)
OR TRUNC(MV.ENTRY_DATE) BETWEEN TRUNC(SYSDATE-1) AND TRUNC(SYSDATE)
OR TRUNC(PV.ENTRY_DATE) BETWEEN TRUNC(SYSDATE-1) AND TRUNC(SYSDATE));