DELETE FROM LIMIT_GROUP;

INSERT INTO LIMIT_GROUP (LIMIT_GROUP_ID, NAME, DESCRIPTION) VALUES (1, 'BASIC', 'BASIC');
INSERT INTO LIMIT_GROUP (LIMIT_GROUP_ID, NAME, DESCRIPTION) VALUES (2, 'STANDARD', 'STANDARD');
INSERT INTO LIMIT_GROUP (LIMIT_GROUP_ID, NAME, DESCRIPTION) VALUES (3, 'VIP', 'VIP');