INSERT INTO LIMIT_GROUP (LIMIT_GROUP_ID, NAME, DESCRIPTION) VALUES (LIMITGRPID_SEQ.NEXTVAL, 'BASIC', 'BASIC');
INSERT INTO LIMIT_GROUP (LIMIT_GROUP_ID, NAME, DESCRIPTION) VALUES (LIMITGRPID_SEQ.NEXTVAL, 'STANDARD', 'STANDARD');
INSERT INTO LIMIT_GROUP (LIMIT_GROUP_ID, NAME, DESCRIPTION) VALUES (LIMITGRPID_SEQ.NEXTVAL, 'VIP', 'VIP');

INSERT INTO DEBITCARD_SUBSCRIPTION_TYPE (TYPE_ID, NAME, DESCRIPTION, REISSUE_TERM, LIMIT_GROUP_ID) 
	VALUES (SUBS_TYPEID_SEQ.NEXTVAL, 'CONSUMER', 'CONSUMER', 36, 2);
INSERT INTO DEBITCARD_SUBSCRIPTION_TYPE (TYPE_ID, NAME, DESCRIPTION, REISSUE_TERM, LIMIT_GROUP_ID) 
	VALUES (SUBS_TYPEID_SEQ.NEXTVAL, 'BUSINESS', 'BUSINESS', 36, 2);
