update PROPERTY_PRESENTER_ATTRIBUTES set hidden=0 where PROPERTY_DEFINITION_ID in(select PROPERTY_DEFINITION_ID from 
PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID in(select ENTITY_TYPE_DEFINITION_ID from ENTITY_TYPE_DEFINITION 
where TYPE_NAME='DealerParticipation') and property_name='PaidToDealer');

update PROPERTY_PRESENTER_ATTRIBUTES set hidden=0 where PROPERTY_DEFINITION_ID in(select PROPERTY_DEFINITION_ID from 
PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID in(select ENTITY_TYPE_DEFINITION_ID from ENTITY_TYPE_DEFINITION 
where TYPE_NAME='DealerParticipation') and property_name='DealerHoldbackRebate');

update PROPERTY_PRESENTER_ATTRIBUTES set hidden=0 where PROPERTY_DEFINITION_ID in(select PROPERTY_DEFINITION_ID from 
PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID in(select ENTITY_TYPE_DEFINITION_ID from ENTITY_TYPE_DEFINITION 
where TYPE_NAME='DealerParticipation') and property_name='DealerRebateAmount');

update PROPERTY_PRESENTER_ATTRIBUTES set hidden=0 where PROPERTY_DEFINITION_ID in(select PROPERTY_DEFINITION_ID from 
PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID in(select ENTITY_TYPE_DEFINITION_ID from ENTITY_TYPE_DEFINITION 
where TYPE_NAME='DealerParticipation') and property_name='RemainingTerm');

update PROPERTY_PRESENTER_ATTRIBUTES set hidden=0 where PROPERTY_DEFINITION_ID in(select PROPERTY_DEFINITION_ID from 
PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID in(select ENTITY_TYPE_DEFINITION_ID from ENTITY_TYPE_DEFINITION 
where TYPE_NAME='DealerParticipation') and property_name='DealerRatio');

update PROPERTY_PRESENTER_ATTRIBUTES set hidden=0 where PROPERTY_DEFINITION_ID in(select PROPERTY_DEFINITION_ID from 
PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID in(select ENTITY_TYPE_DEFINITION_ID from ENTITY_TYPE_DEFINITION 
where TYPE_NAME='DealerParticipation') and property_name='DealerRate');