update ASSOCIATE_PRESENTER_ATTRIBUTES set HIDDEN = 0 where ASSOCIATE_DEFINITION_ID = 572;

update ASSOCIATE_PRESENTER_ATTRIBUTES set HIDDEN = 0 where ASSOCIATE_DEFINITION_ID = 6623;

update ASSOCIATE_PRESENTER_ATTRIBUTES set HIDDEN = 0 where ASSOCIATE_DEFINITION_ID = 569;
