update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE='1' where PROPERTY_DEFINITION_ID in 
(select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID in 
(select ENTITY_TYPE_DEFINITION_ID from ENTITY_TYPE_DEFINITION where TYPE_NAME='InterestCalculation')) and state_name='ACCOUNT_CREATED';

update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE='1' where PROPERTY_DEFINITION_ID in 
(select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID in 
(select ENTITY_TYPE_DEFINITION_ID from ENTITY_TYPE_DEFINITION where TYPE_NAME='InterestCalculation')) and state_name='DEFAULT';

update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE='1' where PROPERTY_DEFINITION_ID in 
(select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID in 
(select ENTITY_TYPE_DEFINITION_ID from ENTITY_TYPE_DEFINITION where TYPE_NAME='CollateralProperty')) and state_name='ACCOUNT_CREATED';

update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE='1' where PROPERTY_DEFINITION_ID in 
(select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID in 
(select ENTITY_TYPE_DEFINITION_ID from ENTITY_TYPE_DEFINITION where TYPE_NAME='CollateralProperty')) and state_name='DEFAULT';

update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE='1' where PROPERTY_DEFINITION_ID in 
(select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID in 
(select ENTITY_TYPE_DEFINITION_ID from ENTITY_TYPE_DEFINITION where TYPE_NAME='CollateralTitle')) and state_name='ACCOUNT_CREATED';

update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE='1' where PROPERTY_DEFINITION_ID in 
(select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID in 
(select ENTITY_TYPE_DEFINITION_ID from ENTITY_TYPE_DEFINITION where TYPE_NAME='CollateralTitle')) and state_name='DEFAULT';
