--Added script for MG fields effect for Advance transaction.
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (005,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1881'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (205,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1981'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (005,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1884'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (205,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1984'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (005,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1885'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (205,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1985'));