INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(77, '077', 0, 277, null, ' Interest YTD Credit Adjustment', '1');
INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(277, '277', 1, 77, null, 'Interest YTD Credit Adjustment REVERSAL', '1');
  
INSERT INTO ENTRY_TYPE(UNIQUE_ID,ID,INSTITUTION_ID,DEBIT_OR_CREDIT,DESCRIPTION,ACCOUNT_CATEGORY,POSTING_SEQUENCE,IS_REVERSAL)
VALUES(8877, '8877', null, '0', 'Interest YTD Credit Adjustment', 2, NULL, '0');
ALTER TABLE LOAN_ENTRY_POSTING_RULE ADD AFFECTS_INTEREST_PAID_YTD NUMBER(20) DEFAULT 0;
INSERT INTO LOAN_ENTRY_POSTING_RULE(POSTING_RULE_ID, AFFECTS_INTEREST_PAID_YTD) VALUES(8877, 1);
INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID) VALUES(8877,8877,8877,8877);
  
insert into loan_event_entry_type_link values(77,8877);
 
insert into event_type values('77','Interest YTD Credit Adjustment','REGULAR');





INSERT INTO ENTRY_TYPE(UNIQUE_ID,ID,INSTITUTION_ID,DEBIT_OR_CREDIT,DESCRIPTION,ACCOUNT_CATEGORY,POSTING_SEQUENCE,IS_REVERSAL)
    values((select max(unique_id)+1 from entry_type),'1889',null,'0','INTEREST PAID YTD',2,NULL,0);

INSERT INTO ENTRY_TYPE(UNIQUE_ID,ID,INSTITUTION_ID,DEBIT_OR_CREDIT,DESCRIPTION,ACCOUNT_CATEGORY,POSTING_SEQUENCE,IS_REVERSAL)
    values((select max(unique_id)+1 from entry_type),'1989',null,'1','INTEREST PAID YTD',2,NULL,0);

INSERT INTO LOAN_ENTRY_POSTING_RULE(POSTING_RULE_ID, AFFECTS_INTEREST_PAID_YTD) VALUES(89, 1);

INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID) 
    VALUES((select unique_id from entry_type where id='1889'), 89, (select unique_id from entry_type where id='1989'), 89);

INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID) 
    VALUES((select unique_id from entry_type where id='1989'), 89, (select unique_id from entry_type where id='1889'), 89);
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (077,(SELECT unique_id FROM entry_type WHERE ID='1989'));



----------------------------------------------------------------------------------------------------------------------
INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(78, '078', 0, 278, null, 'Interest YTD Debit Adjustment', '1');
INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
 VALUES(278, '278', 1, 78, null, 'Interest YTD Debit Adjustment REVERSAL', '1');
  
INSERT INTO ENTRY_TYPE(UNIQUE_ID,ID,INSTITUTION_ID,DEBIT_OR_CREDIT,DESCRIPTION,ACCOUNT_CATEGORY,POSTING_SEQUENCE,IS_REVERSAL)
VALUES(8878, '8878', null, '0', 'Interest YTD Debit Adjustment', 2, NULL, '0');

INSERT INTO LOAN_ENTRY_POSTING_RULE(POSTING_RULE_ID, AFFECTS_INTEREST_PAID_YTD) VALUES(8878, 1);
INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID) VALUES(8878,8878,8878,8878);
  
insert into loan_event_entry_type_link values(78,8878);

UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_INTEREST_PAID_YTD=1 WHERE POSTING_RULE_ID=8878;

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (078,(SELECT unique_id FROM entry_type WHERE ID='1889'));

insert into event_type values('78','Interest YTD Debit Adjustment','REGULAR');




--scripts merged from 4.0 to 4.3 for AccruedInterestCredit and Debit Adjustment
INSERT INTO ENTRY_TYPE(UNIQUE_ID,ID,INSTITUTION_ID,DEBIT_OR_CREDIT,DESCRIPTION,ACCOUNT_CATEGORY,POSTING_SEQUENCE,IS_REVERSAL)
VALUES(8829, '8829', null, '0', 'Accrued Interest - Debit Adjustment', 2, NULL, '0');

INSERT INTO ENTRY_TYPE(UNIQUE_ID,ID,INSTITUTION_ID,DEBIT_OR_CREDIT,DESCRIPTION,ACCOUNT_CATEGORY,POSTING_SEQUENCE,IS_REVERSAL)
VALUES(8839, '8839', null, '0', 'Accrued Interest - Credit Adjustment', 2, NULL, '0');

insert into loan_event_entry_type_link values(29,8829);

insert into loan_event_entry_type_link values(39,8839);

insert into loan_entry_type values(8829,8829,8829,8829);

insert into loan_entry_type values(8839,8839,8839,8839);






  
  