--Added scripts for Update the fields in Nightly.

UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_TOTAL_AVAILABLE_AMOUNT=1 WHERE POSTING_RULE_ID='9999'
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_TERM_LOAN_LIMIT_USED=1 WHERE POSTING_RULE_ID='9999'
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_UNUSED_TERM_LOAN_LIMIT=1 WHERE POSTING_RULE_ID='9999'
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_CREDIT_LINE_LIMIT_USED=1 WHERE POSTING_RULE_ID='9999'
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_UNUSED_CREDIT_LINE_LIMIT=1 WHERE POSTING_RULE_ID='9999'
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_TOTAL_AVAILABLE_AMOUNT=1 WHERE POSTING_RULE_ID='8805'
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_CREDIT_LINE_LIMIT_USED=1 WHERE POSTING_RULE_ID='8805'
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_UNUSED_CREDIT_LINE_LIMIT=1 WHERE POSTING_RULE_ID='8805'