UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_NA_DATE=1 WHERE POSTING_RULE_ID='8874';
 
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_LOAN_STATUS=1 WHERE POSTING_RULE_ID='8874';

UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_CHARGE_OFF_DATE=1 WHERE POSTING_RULE_ID='8876';
 
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_LOAN_STATUS=1 WHERE POSTING_RULE_ID='8876';