CREATE TABLE LOAN_TERMS
(
ID NUMBER(10) NOT NULL,
FREQUENCY VARCHAR2(30),
PRODUCT_CODE VARCHAR2(20),
PRODUCT_DESCRIPTION VARCHAR2(20),
PRIMARY KEY (ID)
); 

CREATE SEQUENCE LOAN_TERMS_ID_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOMINVALUE NOCYCLE ORDER;

CREATE TABLE LOAN_PERIOD_INTEREST_RATE(
ID NUMBER(5) NOT NULL ENABLE,
LOAN_PRODUCT_CODE VARCHAR2(20),
EFFECTIVE_DATE DATE,
TILL_PERIOD VARCHAR2(30),
RATE_OF_INTEREST NUMBER(10,2),
ENTER_BY VARCHAR2(20),
CREATED_DATE DATE DEFAULT SYSDATE,
CONSTRAINT INTEREST_ID_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE LOAN_PERIOD_INT_RATE_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOMINVALUE NOCYCLE ORDER; 