CREATE TABLE ORIGINATOR_SETTLEMENT_MAPPING (MAPPING_UID NUMBER(20) NOT NULL ENABLE,
ORIGINATOR_ID varchar2(50),SETTLEMENT_ID varchar2(50),
CONSTRAINT "ORG_SETT_MAP_PK" PRIMARY KEY ("MAPPING_UID") ENABLE);

create sequence ORIG_SETTLE_MAP_UID_SEQ minvalue 1 maxvalue 9999999999 increment by 1 start with 1;
   
ALTER TABLE ENTRY_TYPE MODIFY REVERSAL_ENTRY_TYPE_ID VARCHAR2(30);