update property_presenter_attributes set hidden=0 where property_definition_id in(select property_definition_id from property_definition where property_name like 'PastDueEscrow');

--adding multiple columns to loan.
ALTER TABLE LOAN ADD ACTUAL_INSURANCE_ACCR NUMBER(20,5);

ALTER TABLE LOAN ADD PAYMENT_YTD NUMBER(20,5);

ALTER TABLE LOAN ADD PAYMENT_LYR NUMBER(20,5);

ALTER TABLE LOAN ADD PRINCIPLE_PAID_YTD NUMBER(20,5);

ALTER TABLE LOAN ADD MTD_AVG_BAL NUMBER(20,5);

ALTER TABLE LOAN ADD QTD_AVG_BAL NUMBER(20,5);

ALTER TABLE LOAN ADD YTD_AVG_BAL NUMBER(20,5);

ALTER TABLE LOAN ADD LAST_ADV_AMOUNT NUMBER(20,5);

ALTER TABLE LOAN ADD LAST_ADV_DATE DATE;

ALTER TABLE LOAN ADD DATE_LAST_CB_BUILD DATE;

ALTER TABLE LOAN ADD LATE_CHARGES_LYR NUMBER(20,5);

ALTER TABLE LOAN ADD LATE_CHARGES_PYR NUMBER(20,5);


ALTER TABLE EXTENSION_NEW ADD EXTENSION_FEES NUMBER(20,5);

ALTER TABLE EXTENSION_HISTORY ADD  EXTENSION_FEES NUMBER(20,5);


INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN,INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
  VALUES(PROPDEFID_SEQ.nextval,(SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE 'EscrowDetail'), 'EscrowPaymentLastYear', 17, 'EscrowPaymentLastYear', 8, 0, 0, NULL, 0, 'com.vsoftcorp.finance.Money:{default={}}', 0, 0, 0, 0, 1, 0, 0, 'UC', 0, 0);

INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
  VALUES(PROPDEFID_SEQ.currval, 0, 0, 1, 0, 'DEFAULT'); 
INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
  VALUES(PROPDEFID_SEQ.currval, 0, 0, 0, 0, 'INQUIRY'); 
INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
  VALUES(PROPDEFID_SEQ.currval, 0, 0, 1, 0, 'ACCOUNT_CREATED'); 




