alter table LEDGER_POSTING_PARAMETERS drop column AFFECTS_REVERSAL_TRANCODE;
alter table LEDGER_POSTING_PARAMETERS drop column AFFECTS_WITHHELD_YTDTAX;

--loan parameters
-- (check with max count for sequences)
create sequence BSV_LOAN_EVENT_ID_SEQ start with 1;

alter table LOAN_ENTRY_TYPE modify REVERSAL_ENTRY_TYPE_ID null;


CREATE TABLE EVENT_DISTRIBUTION
(
   UNIQUE_ID decimal(10) PRIMARY KEY NOT NULL,
   DISTRIBUTION_TYPE varchar2(10),
   EVENT_TYPE_ID decimal(10)
);

CREATE TABLE EVENT_PERCENTAGE_DISTRIBUTION
(
   UNIQUE_ID decimal(10) PRIMARY KEY NOT NULL,
   DISTRIBUTION_ID decimal(10) NOT NULL,
   PRINCIPAL varchar2(10),
   INTEREST varchar2(10),
   ESCROW varchar2(10),
   AH varchar2(10),
   LATE_CHARGE varchar2(10),
   OTHER_FEES varchar2(10),
   UNAPPLIED_FUND varchar2(10),
   ORIGINATION_FEE varchar2(10),
   CREDIT_LIFE varchar2(10)
);

create sequence EVENT_DISTRIBUTION_ID_SEQ start with 1;
create sequence EVENT_PERCENTAGE_DIS_ID_SEQ start with 1;

ALTER TABLE EVENT_PERCENTAGE_DISTRIBUTION
ADD CONSTRAINT EVENT_DISTRIBUTION_ID_FK
FOREIGN KEY (DISTRIBUTION_ID)
REFERENCES EVENT_DISTRIBUTION(UNIQUE_ID)
;

-- Institution & Branch Parameters

alter table INSTITUTION_ADDRESS modify INSTITUTION_ID null;

create sequence FRABA_ID_SEQ start with 100;

-- Product Parameters

CREATE TABLE PROD_CATEGORY_FEATURES
   (    "FEATURE_UID" NUMBER,
        "PROD_CATEGORY_ID" NUMBER NOT NULL ENABLE,
        "UNIQUE_ID" NUMBER NOT NULL ENABLE,
        "PRIORITY" NUMBER,
        CONSTRAINT "PROD_CATEGORY_FEATURES_PK" PRIMARY KEY ("UNIQUE_ID")
); 
 
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (6,1,41,1);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (7,1,42,2);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (3,1,43,3);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (1,1,44,4);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (41,1,45,5);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (14,1,46,6);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (4,1,47,7);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (2,1,48,8);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (11,1,49,9);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (47,1,50,10);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (133,1,51,11);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (143,1,52,12);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (132,1,54,13);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (17,1,55,14);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (101,1,56,15);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (12,1,57,16);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (42,1,58,17);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (13,1,59,18);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (44,1,60,20);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (128,1,61,21);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (127,1,62,22);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (38,1,63,23);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (125,1,64,24);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (122,1,65,25);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (118,1,66,26);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (138,1,67,27);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (30,1,68,28);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (140,1,69,29);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (141,1,70,30);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (142,1,71,31);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (139,1,72,32);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (15,1,73,33);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (126,1,74,34);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (16,1,75,35);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (137,1,76,36);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (124,1,77,37);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (123,1,78,38);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (130,1,79,19);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (6,2,80,1);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (7,2,82,2);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (3,2,83,3);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (1,2,84,4);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (2,2,85,5);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (8,2,86,6);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (9,2,87,7);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (133,2,88,8);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (101,2,89,9);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (47,2,90,10);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (143,2,91,11);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (132,2,92,12);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (42,2,93,13);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (4,2,94,14);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (176,2,95,15);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (5,2,96,16);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (38,2,97,17);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (125,2,98,18);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (122,2,99,19);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (118,2,100,20);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (138,2,101,21);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (30,2,102,22);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (140,2,103,23);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (141,2,104,24);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (142,2,105,25);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (139,2,106,26);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (137,2,107,27);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (124,2,108,28);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (123,2,109,29);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (10,3,110,1);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (19,3,111,2);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (36,3,112,3);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (37,3,113,4);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (34,3,114,5);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (35,3,115,6);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (32,3,116,7);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (33,3,117,8);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (26,3,118,9);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (6,3,119,10);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (41,3,120,11);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (14,3,121,12);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (1,3,122,13);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (2,3,123,14);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (143,3,124,15);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (20,3,125,16);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (12,3,126,17);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (4,3,127,18);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (42,3,128,19);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (40,3,129,20);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (27,3,130,21);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (43,3,131,22);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (25,3,132,23);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (24,3,133,24);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (100,3,134,25);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (22,3,135,26);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (136,3,136,27);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (21,3,137,28);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (13,3,138,29);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (29,3,139,30);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (17,3,140,31);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (47,3,141,32);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (135,3,142,33);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (38,3,143,34);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (45,3,144,35);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (125,3,145,36);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (46,3,149,37);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (118,3,150,38);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (44,3,151,39);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (23,3,152,40);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (138,3,153,41);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (30,3,154,42);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (31,3,155,43);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (39,3,156,44);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (124,3,157,45);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (123,3,158,46);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (103,3,159,47);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (11,5,160,1);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (6,5,161,2);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (7,5,162,3);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (3,5,163,4);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (1,5,164,5);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (41,5,165,6);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (14,5,166,7);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (2,5,167,8);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (133,5,168,9);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (12,5,169,10);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (42,5,170,11);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (4,5,171,12);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (13,5,172,13);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (17,5,173,14);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (47,5,174,15);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (101,5,175,16);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (125,5,176,17);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (122,5,177,18);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (38,5,178,19);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (143,5,179,20);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (132,5,180,21);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (138,5,181,22);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (118,5,182,23);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (30,5,183,24);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (140,5,184,25);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (141,5,185,26);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (139,5,186,27);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (15,5,187,28);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (126,5,188,29);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (16,5,189,30);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (137,5,190,31);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (142,5,191,32);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (130,5,192,33);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (127,5,193,34);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (128,5,194,35);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (44,5,195,36);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (124,5,196,37);
--Insert into PROD_CATEGORY_FEATURES ("FEATURE_UID","PROD_CATEGORY_ID","UNIQUE_ID","PRIORITY") values (123,5,197,38);


-- Interest Rate Parameters

CREATE TABLE ZONE
(
   ZONE_ID decimal(10) PRIMARY KEY NOT NULL,
   ZONE_NAME varchar2(50),
   INSTITUTION_ID decimal(12)
);

CREATE TABLE ZONE_BRANCH_MAPPING
(
   ZONE_ID decimal(10),
   BRANCH_ID decimal(12)
);

create sequence ZONE_SEQ start with 1;

