DROP TABLE LEGAL_ACTION_CODE;

CREATE TABLE LEGAL_ACTION_CODE_LOOKUP
  (
  	"UNIQUE_ID" NUMBER(5) NOT NULL ENABLE,
  	"LEGAL_ACTION_CODE" 	VARCHAR2(20)  NOT NULL ENABLE,
    "LEAGAL_ACTION_DESCRIPTION" VARCHAR2(200),
    PRIMARY KEY (UNIQUE_ID));

CREATE TABLE REASON_CODE_LOOKUP
  (
  	"UNIQUE_ID" NUMBER(5) NOT NULL ENABLE,
  	"REASON_CODE" 	VARCHAR2(20)  NOT NULL ENABLE,
    "REASON_DESCRIPTION" VARCHAR2(200),
    PRIMARY KEY (UNIQUE_ID));
    
ALTER TABLE LOAN DROP COLUMN LEGAL_ACTION_CODE_ID ;
    
ALTER TABLE LOAN ADD LEGAL_ACTION_CODE_ID VARCHAR2(20);

ALTER TABLE LOAN ADD REASON_CODE_ID VARCHAR2(20);

------------------------------------------------Legal_Action_Code_LookUp Insert Scripts-----------------------------------------------------
    
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(1,'0','To Delete a Referral Action Code (Fannie Mae Liquidation)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(2,'1','Re-add to Active File (Fannie Mae Liquidation)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(3,'6','Format Forbearance Plan');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(4,'8','Type II Special Forbearance Trail Payment Plan (HUD)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(5,'9','Forberance –Payments Reduce or Suspended');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(6,'10','Partial Claim Started (HUD)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(7,'11','Repyament Plan in Review');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(8,'12','Repyament Plan');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(9,'13','Partial Payment (Fannie Mae Liquidation)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(10,'13','Paid in Full (HUD)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(11,'15','Bankruptcy/Litigation (Fannie Mae Liquidation)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(12,'15','Pre-Foreclosure Sale Program (HUD) Short Sale Approved/Marketing Property (Fannie Mae)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(13,'17','Short Sale Approved/Offer Received ');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(14,'1A','Foreclosure Sale Held (HUD)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(15,'1G','Eviction Completed (HUD)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(16,'20','Refferred for Deed-in-Lieu or Assignment (Fannie Mae Liquidation)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(17,'20','Reinstatement (Full/partial) (HUD)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(18,'21','Reinstated by Assumptor (HUD)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(19,'22','Servicing Transferred or Sold (HUD)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(20,'24','Government Seizure');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(21,'25','Cancel (HUD)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(22,'26','Refinance');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(23,'27','Assumption (Fannie Mae)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(24,'28','Modification');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(25,'29','Charge-off');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(26,'30','Referred for Foreclosure (Fannie Mae Liquidation)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(27,'30','Third-Party Sale');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(28,'31','Probate');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(29,'32','Military Indulgence');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(30,'33','Contested or Litigated Foreclosure');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(31,'34','Natural Disaster (HUD)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(32,'3B','Prequalified for 601 (HUD)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(33,'3L','Bankrupty Chapter 7- Asset Case (Fannie Mae)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(34,'3M','Bankruptcy- Property Surrendered (Fannie Mae)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(35,'35','Bankruptcy Cramdown Scheduled (Freddie Mac)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(36,'36','FHA-HAMP Standalone Partial Claim Started');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(37,'37','FHA-HAMP Standalone Modification Started');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(38,'38','Appeal of Loan Modification (Freddie Mac)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(39,'39','FHA-HAMP Trial Modification Plan');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(40,'40','Inactive Loan (Freddie Mac Exception)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(41,'41','FHA-HAMP Modification Started');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(42,'42','Delinquent');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(43,'43','Referred to Foreclosure – Status Foreclosure');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(44,'44','Mortgage Release');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(45,'45','Foreclosure Completed');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(46,'46','Property Conveyed to HUD (HUD)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(47,'47','Deed-in-Lieu Completed (HUD)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(48,'48','Claim Without Conveyance (HUD)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(49,'49','Assignment Completed');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(50,'50','Reinstate Loan (Freddie Mac Exception)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(51,'50','Loss Mitigation (MC)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(52,'54','PMI Rescission (Fannie Mae)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(53,'59','Chapter 12 Bankruptcy');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(54,'60','Payoff');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(55,'61','Payoff-Mortgage Prepaid (Freddie Mac Exception)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(56,'61','Second Lien Considerations');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(57,'62','Veterans Affairs – No Bid');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(58,'63','Veterans Affairs – Refund');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(59,'64','Veterans Affairs – Buydown');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(60,'65','Payoff-Mortgage Repurchased (Freddie Mac Exception)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(61,'65','Chapter 7 Bankruptcy');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(62,'65','Repurchase (Fannie Mae Liquidation)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(63,'66','Payoff-Mortgage Converted (Freddie Mac Exception)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(64,'66','Chapter 11 Bankruptcy');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(65,'67','Repurchase (Fannie Mae Liquidation)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(66,'67','Chapter 13 Bankruptcy');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(67,'68','1st Legal Action to Start Foreclosure');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(68,'69','Bankruptcy Plan Confirmed');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(69,'70','Liquidated—Held for Sale (Fannie Mae Liquidation)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(70,'70','Transfer to REO and Deed-in-Lieu');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(71,'71','Liquidated—Third Party Sale/Condemnation (Fannie Mae Liquidation)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(72,'71','Third-Party Foreclosure Sale (Freddie mac Exception)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(73,'71','Foreclosure Sale Scheduled (Freddie Mac)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(74,'72','Pending Conveyance (Fannie Mae Liquidation)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(75,'73','Property Redeemed (HUD)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(76,'74','*BPO or Appraisal Obtained (Freddie Mac)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(77,'75','No Activity to Report (Freddie Mac)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(78,'76','Bankruptcy Court Clearance Obtained');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(79,'77','Foreclosure Deed Recorded');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(80,'78','Borrower Program Assistance Received');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(81,'80','Breach Letter Sent');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(82,'80','Principal Balance Correction (Freddie Mac)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(83,'94','Judgement of Decree Entered (Fannie Mae)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(84,'95','Foreclosure Sale Continued (Fannie Mae)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(85,'98','Reinstated After Loss Mitigation (HUD)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(86,'99','Exception (Action Code Needed)(HUD)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(87,'AO','Ineligible for Loss Mitigation (HUD)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(88,'AA','Complete Financials Received and In Review');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(89,'AH','Streamlined Financials Received and In Review');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(90,'AP','Ineligible for Loss Mitigation Due to No Response');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(91,'AQ','Option Failure (HUD)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(92,'AS','HUD FC Moratorium (HUD)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(93,'AW','Date First Right Party Contact');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(94,'AX','Date Last Right Party Contact (Freddie Mac)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(95,'AY','Date Advised Property Listed (Freddie Mac)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(96,'BE','Title Issue in Progress (Fannie Mae)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(97,'BF','Trial Modification (Fannie Mae)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(98,'BG','Pre-File Mediation /Mediation (Fannie Mae)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(99,'H3','BPO Ordered');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(100,'H4','Soliciation Letter Sent');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(101,'H5','Complete Response Package Received (Freddie Mac)');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(102,'H6','Eligible for HAMP');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(103,'H7','HAMP in Review');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(104,'H8','HAMP Modification Agreement Sent');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(105,'H9','HAMP Modification Agreement Received');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(106,'HA','Workout in Preview');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(107,'HB','Short Sale in Review');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(108,'HC','Short Sale Denied');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(109,'HD','Modification in Review');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(110,'HE','Ineligible for Modification');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(111,'HF','Short Sale Agreement Borrower Execution');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(112,'1E','Eviction Started');
INSERT INTO LEGAL_ACTION_CODE_LOOKUP VALUES(113,'RO','Real Estate Owned (REO)');

------------------------------------------------Reason_code_LookUp Insert Scripts-----------------------------------------------------


INSERT INTO REASON_CODE_LOOKUP VALUES(1,'001','Death of Principal Mortgagor');
INSERT INTO REASON_CODE_LOOKUP VALUES(2,'002','Illness of Principal Mortgagor');
INSERT INTO REASON_CODE_LOOKUP VALUES(3,'003','Illness of Family Member');
INSERT INTO REASON_CODE_LOOKUP VALUES(4,'004','Death of Family Member');
INSERT INTO REASON_CODE_LOOKUP VALUES(5,'005','Marital Difficulties');
INSERT INTO REASON_CODE_LOOKUP VALUES(6,'006','Curtailment of Income');
INSERT INTO REASON_CODE_LOOKUP VALUES(7,'007','Excessive Obligations');
INSERT INTO REASON_CODE_LOOKUP VALUES(8,'008','Abandoment of Property');
INSERT INTO REASON_CODE_LOOKUP VALUES(9,'009','Distant Employment Transfer');
INSERT INTO REASON_CODE_LOOKUP VALUES(10,'010','Neighborhood Problem');
INSERT INTO REASON_CODE_LOOKUP VALUES(11,'011','Property Problem');
INSERT INTO REASON_CODE_LOOKUP VALUES(12,'012','Inability to Sell Property');
INSERT INTO REASON_CODE_LOOKUP VALUES(13,'013','Inability to Rent Property');
INSERT INTO REASON_CODE_LOOKUP VALUES(14,'014','Military Service');
INSERT INTO REASON_CODE_LOOKUP VALUES(15,'015','Other');
INSERT INTO REASON_CODE_LOOKUP VALUES(16,'016','Unemployment ');
INSERT INTO REASON_CODE_LOOKUP VALUES(17,'017','Business Failure');
INSERT INTO REASON_CODE_LOOKUP VALUES(18,'019','Casualty Loss');
INSERT INTO REASON_CODE_LOOKUP VALUES(19,'022','Energy Environment Costs');
INSERT INTO REASON_CODE_LOOKUP VALUES(20,'023','Servicing Problems');
INSERT INTO REASON_CODE_LOOKUP VALUES(21,'026','Payment Adjustment');
INSERT INTO REASON_CODE_LOOKUP VALUES(22,'027','Payment Dispute');
INSERT INTO REASON_CODE_LOOKUP VALUES(23,'029','Transger of Ownership Pending');
INSERT INTO REASON_CODE_LOOKUP VALUES(24,'030','Fraud');
INSERT INTO REASON_CODE_LOOKUP VALUES(25,'031','Unable to Contact Borrower');
INSERT INTO REASON_CODE_LOOKUP VALUES(26,'032','Contaminated Drywall');
INSERT INTO REASON_CODE_LOOKUP VALUES(27,'034','Eligible Disaster Area');
INSERT INTO REASON_CODE_LOOKUP VALUES(28,'INC','Incarceration');
INSERT INTO REASON_CODE_LOOKUP VALUES(29,'HAF','Home Affordable Foreclosure Alternative');
INSERT INTO REASON_CODE_LOOKUP VALUES(30,'HMP','Home Affordable Modification Program');   