--ALTER TABLE DEPOSIT_ACCOUNT ADD (PLAN_ID VARCHAR2(30),ASSIGNED_BRANCH VARCHAR2(30));

--UPDATE DEPOSIT_ACCOUNT DA  SET (PLAN_ID,ASSIGNED_BRANCH) = (SELECT D.PLAN_ID,D.ASSIGNED_BRANCH  FROM DEPOSIT D WHERE
--D.ACCOUNT_ID = DA.ACCOUNT_ID);

--ALTER TABLE DEPOSIT DROP  column PLAN_ID;
--ALTER TABLE DEPOSIT DROP  column ASSIGNED_BRANCH;