alter table PROPERTY_DEFINITION add (
        MAX_LENGTH number(3),
        DATA_EXPRESSION varchar2(50)
);

update PROPERTY_DEFINITION set DATA_EXPRESSION = '.*', MAX_LENGTH = 999;

ALTER TABLE PROPERTY_DEFINITION
MODIFY (
 MAX_LENGTH DEFAULT 999, DATA_EXPRESSION DEFAULT '.*');

ALTER TABLE PROPERTY_DEFINITION
     MODIFY MAX_LENGTH NUMBER(3,0) NOT NULL;
     
     
ALTER TABLE PROPERTY_DEFINITION
     MODIFY DATA_EXPRESSION VARCHAR2(50) NOT NULL;