ALTER TABLE LOAN
MODIFY (
 INTEREST_PAID_MTD DEFAULT 0,            
 PAST_PRINCIPLE_DUE DEFAULT 0,           
 LAST_CURT_AMOUNT DEFAULT 0,             
 LAST_TRANSACTION_AMOUNT DEFAULT 0,      
 LAST_PAYMENT_AMOUNT DEFAULT 0,          
 DAY_LATECHARGE_AMOUNT DEFAULT 0,        
 NO_OF_DAYS_PASTDUE_BEFOREPOST DEFAULT 0,
 PRINCIPLE_BALANCE DEFAULT 0,            
 ACCRUED_INTEREST DEFAULT 0,             
 UNAPPLIED_FUNDS DEFAULT 0,              
 LATE_FEES_DUE DEFAULT 0,                
 OTHER_FEES_DUE DEFAULT 0,               
 PAYMENTS_MADE DEFAULT 0,                
 AMORTIZED_BALANCE DEFAULT 0,            
 PARTIAL_PAYMENT DEFAULT 0,              
 INTEREST_PAID_YTD DEFAULT 0,            
 INTEREST_PAID_LTD DEFAULT 0,            
 LATE_FEES_PAID_YTD DEFAULT 0,           
 LATE_FEES_PAID_LTD DEFAULT 0,           
 AMT_LC_WAIVED DEFAULT 0,                
 ACCRUED_INTEREST_NET DEFAULT 0,         
 INTEREST_PAST_DUE DEFAULT 0,            
 PER_DIEM DEFAULT 0,                     
 LAST_STATEMENT_BAL DEFAULT 0,           
 PRE_STATEMENT_BAL DEFAULT 0,            
 CHARGE_OFF_AMOUNT DEFAULT 0,            
 FUTURE_PAYMENT_COUNT DEFAULT 0,         
 NO_RETURNED_CHECKS DEFAULT 0);
 
Alter table Loan drop column ACCOUNT_TYPE_ID;


ALTER TABLE LOAN
    DROP CONSTRAINT L_ACCID_FK;


alter table LOAN_ACCOUNT add LOAN_ID VARCHAR2(30);