--Loan Related Scripts
-- Below four updates takes care of existing loan accounts accounts that were created before the refactored code base.
update  LOAN l set DEFINITION_TYPE='STANDARD' where l.ACCOUNT_ID in (SELECT ACCOUNT_ID from LOAN_ACCOUNT);
UPDATE 	LOAN l SET DEFINITION_ID=(SELECT la.ACCOUNT_ID from LOAN_ACCOUNT la where l.ACCOUNT_ID =la.ACCOUNT_ID);
UPDATE LOAN_ACCOUNT SET LOAN_ID=ACCOUNT_ID WHERE LOAN_ID IS NULL;
Alter table LOAN add INSTITUTION_ID VARCHAR2(30);
UPDATE 	LOAN l SET INSTITUTION_ID=(SELECT la.INSTITUTION_ID from ACCOUNT la where l.ACCOUNT_ID =la.ACCOUNT_ID);

Drop table LOAN_PARTICIPATION;

CREATE SEQUENCE PARTICIPATION_ID_SEQ
    INCREMENT BY 1
    START WITH 111
    MAXVALUE 9999999999999999999999999999
    NOMINVALUE
    NOCYCLE
    CACHE 5
    ORDER;
    
CREATE
	TABLE LOAN_PARTICIPATION 
	(
		PARTICIPATION_ID VARCHAR2(30),
		PARTICIPATION_INTEREST_RATE  NUMBER(20,5),
		PARTICIPATION_WITH_RESOURCE VARCHAR2(30),
		PROCESSING_FEE_TYPE VARCHAR2(30),
		PROCESSING_FEE_PERCENTAGE NUMBER(20,5), 
		PROCESSING_FEE_AMOUNT NUMBER(20,5),
		PRINCIPAL_REPAYMENT_METHOD VARCHAR2(30),
		PARTICIPATION_COMMENTS VARCHAR2(30),
		NOTE_DATE DATE,
		MATURITY_DATE DATE,
		LOAN_AMOUNT NUMBER(20,5),
        LOAN_TERM NVARCHAR2(30),
        CALLREPORT_CODE VARCHAR2(30),
		INVESTOR_ID VARCHAR2(30),
		LOAN_ID VARCHAR2(30),
		ACCOUNT_ID VARCHAR2(30),
        SOLD_LOAN_CONTRACT_ID NUMBER(15,0),
        PARTICIPATION_STATUS VARCHAR2(30)
	);
	
CREATE SEQUENCE INVESTOR_ID_SEQ
    INCREMENT BY 1
    START WITH 100
    MAXVALUE 9999999999999999999999999999
    NOMINVALUE
    NOCYCLE
    CACHE 5
    ORDER;
    
    
CREATE
	TABLE INVESTOR
	(
		INVESTOR_ID VARCHAR2(30),
		INVESTOR_CODE VARCHAR2(30),
		INVESTOR_NAME VARCHAR2(30),
        INVESTOR_ADDRESS VARCHAR2(30),
        INVESTOR_PHONE VARCHAR2(30),
        INVESTOR_TIN VARCHAR2(30)
	); 

 
  
ALTER TABLE LOAN_PARTICIPATION
ADD CONSTRAINT pk_participation
PRIMARY KEY (PARTICIPATION_ID);

ALTER TABLE INVESTOR
ADD CONSTRAINT pk_investor
PRIMARY KEY (INVESTOR_ID);


ALTER TABLE LOAN_PARTICIPATION
ADD FOREIGN KEY (investor_id)
REFERENCES INVESTOR(INVESTOR_ID);


ALTER TABLE LOAN_PARTICIPATION
ADD FOREIGN KEY (account_id)
REFERENCES LOAN_ACCOUNT(ACCOUNT_ID);


ALTER TABLE LOAN
ADD FOREIGN KEY (institution_id)
REFERENCES INSTITUTION(INSTITUTION_ID);

ALTER TABLE LOAN
drop CONSTRAINT L_ACCT_ID_UK;


ALTER TABLE LOAN
ADD CONSTRAINT pk_loan
PRIMARY KEY (ACCOUNT_ID);

ALTER TABLE LOAN_PARTICIPATION
ADD FOREIGN KEY (loan_id)
REFERENCES LOAN(ACCOUNT_ID);

ALTER TABLE LOAN_ACCOUNT
ADD FOREIGN KEY (loan_id)
REFERENCES LOAN(ACCOUNT_ID);






	
