alter table Loan add  CURT_AMOUNT_PREPAID_LOANS  NUMBER(20);


INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','8820');


alter table LOAN_ACCOUNT_MONETARY_EVENT ADD CLOSING_LIFE_AH_BAL NUMBER(20) DEFAULT 0 ;
alter table LOAN_ENTRY_POSTING_RULE ADD AFFECTS_AHLIFE_DUE NUMBER(20) DEFAULT 0 ;
alter table LOAN_ENTRY_POSTING_RULE ADD AFFECTS_AHLIFE_BALANCE NUMBER(20) DEFAULT 0 ;
alter table BILLING_BUCKET ADD BILLED_NONESCROW NUMBER(20) DEFAULT 0;
alter table BILLING_BUCKET ADD PAID_AH_LIFE NUMBER(20) DEFAULT 0;
