INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(89, '089', 0, 289, null, 'Bankruptcy Customer Payment', '1');
INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(289, '289', 1, 89, null, 'Bankruptcy Customer Payment Reveral', '0');
INSERT INTO ENTRY_TYPE(UNIQUE_ID,ID,INSTITUTION_ID,DEBIT_OR_CREDIT,DESCRIPTION,ACCOUNT_CATEGORY,POSTING_SEQUENCE,IS_REVERSAL)
  VALUES(8889, '8889', null, '0', 'Bankruptcy Customer Payment', 2, NULL, '0');
ALTER TABLE LOAN_ENTRY_POSTING_RULE ADD  AFF_BANKRUPTCY_CUST_PAYMENT NUMBER(20) DEFAULT 0;
INSERT INTO LOAN_ENTRY_POSTING_RULE(POSTING_RULE_ID, AFF_BANKRUPTCY_CUST_PAYMENT) VALUES(8889,1);
INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID) VALUES(8889,8889,8889,8889);
insert into loan_event_entry_type_link values(89,8889);


INSERT INTO ENTRY_TYPE(UNIQUE_ID,ID,INSTITUTION_ID,DEBIT_OR_CREDIT,DESCRIPTION,ACCOUNT_CATEGORY,POSTING_SEQUENCE,IS_REVERSAL)
    values((select max(unique_id)+1 from entry_type),'1877',null,'0','CUSTOMER PARTIAL AMT',2,NULL,0);
INSERT INTO ENTRY_TYPE(UNIQUE_ID,ID,INSTITUTION_ID,DEBIT_OR_CREDIT,DESCRIPTION,ACCOUNT_CATEGORY,POSTING_SEQUENCE,IS_REVERSAL)
    values((select max(unique_id)+1 from entry_type),'1977',null,'1','CUSTOMER PARTIAL AMT',2,NULL,0);
ALTER TABLE LOAN_ENTRY_POSTING_RULE ADD  AFF_CUSTOMER_PARTIAL_AMT NUMBER(20) DEFAULT 0;
INSERT INTO LOAN_ENTRY_POSTING_RULE(POSTING_RULE_ID, AFF_CUSTOMER_PARTIAL_AMT) VALUES(77, 1);
INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID) 
    VALUES((select unique_id from entry_type where id='1877'), 77, (select unique_id from entry_type where id='1977'), 77);
INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID) 
    VALUES((select unique_id from entry_type where id='1977'), 77, (select unique_id from entry_type where id='1877'), 77);
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (089,(SELECT unique_id FROM entry_type WHERE ID='1977'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (289,(SELECT unique_id FROM entry_type WHERE ID='1877'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_CUSTOMER_PARTIAL_AMT=1 WHERE POSTING_RULE_ID=8889;


ALTER TABLE LOAN ADD CUSTOMER_PARTIAL_PAID_AMOUNT NUMBER(15,5) DEFAULT 0;