INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(87, '087', 0, 287, null, 'Principal Payment From Partial', '1');
INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(287, '287', 1, 87, null, 'Principal Payment From Partial Reversal', '0');
INSERT INTO ENTRY_TYPE(UNIQUE_ID,ID,INSTITUTION_ID,DEBIT_OR_CREDIT,DESCRIPTION,ACCOUNT_CATEGORY,POSTING_SEQUENCE,IS_REVERSAL)
  VALUES(8887, '8887', null, '0', 'Principal Payment From Partial', 2, NULL, '0');
ALTER TABLE LOAN_ENTRY_POSTING_RULE ADD  AFF_PRINCIPLE_PAYMENT_PARTIAL NUMBER(20) DEFAULT 0;
INSERT INTO LOAN_ENTRY_POSTING_RULE(POSTING_RULE_ID, AFF_PRINCIPLE_PAYMENT_PARTIAL) VALUES(8887,1);
INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID) VALUES(8887,8887,8887,8887);
insert into loan_event_entry_type_link values(87,8887);

INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(88, '088', 0, 288, null, 'LateFee Payment From Partial', '1');
INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(288, '288', 1, 88, null, 'LateFee Payment From Partial Reversal', '0');
INSERT INTO ENTRY_TYPE(UNIQUE_ID,ID,INSTITUTION_ID,DEBIT_OR_CREDIT,DESCRIPTION,ACCOUNT_CATEGORY,POSTING_SEQUENCE,IS_REVERSAL)
  VALUES(8888, '8888', null, '0', 'LateFee Payment From Partial', 2, NULL, '0');
ALTER TABLE LOAN_ENTRY_POSTING_RULE ADD  AFF_LATEFEE_PAYMENT_PARTIAL NUMBER(20) DEFAULT 0;
INSERT INTO LOAN_ENTRY_POSTING_RULE(POSTING_RULE_ID, AFF_LATEFEE_PAYMENT_PARTIAL) VALUES(8888,1);
INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID) VALUES(8888,8888,8888,8888);
insert into loan_event_entry_type_link values(88,8888);

--principle
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (087,(SELECT unique_id FROM entry_type WHERE ID='1801'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (287,(SELECT unique_id FROM entry_type WHERE ID='1901'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_PRINCIPAL_BALANCE=1 WHERE POSTING_RULE_ID=8887;

--trustee partial paid amount
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (087,(SELECT unique_id FROM entry_type WHERE ID='1891'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (287,(SELECT unique_id FROM entry_type WHERE ID='1991'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_TRUSTE_PARTIAL_AMT=1 WHERE POSTING_RULE_ID=8887;


--collected late charge
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (088,(SELECT unique_id FROM entry_type WHERE ID='1902'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (288,(SELECT unique_id FROM entry_type WHERE ID='1802'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_COLL_LATE_CHARGE=1 WHERE POSTING_RULE_ID=8888;

--un collected late charge
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (088,(SELECT unique_id FROM entry_type WHERE ID='1807'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (288,(SELECT unique_id FROM entry_type WHERE ID='1907'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_UNCOLL_LATE_CHARGE=1 WHERE POSTING_RULE_ID=8888;

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (088,(SELECT unique_id FROM entry_type WHERE ID='1891'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (288,(SELECT unique_id FROM entry_type WHERE ID='1991'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_TRUSTE_PARTIAL_AMT=1 WHERE POSTING_RULE_ID=8888;