INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(60, '060', 0, 260, null, 'Loan Remittance', '1');
INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(260, '260', 1, 60, null, 'Loan Remittance Reversal', '0');
INSERT INTO ENTRY_TYPE(UNIQUE_ID,ID,INSTITUTION_ID,DEBIT_OR_CREDIT,DESCRIPTION,ACCOUNT_CATEGORY,POSTING_SEQUENCE,IS_REVERSAL)
  VALUES(8860, '8860', null, '0', 'Loan Remittance', 2, NULL, '0');
ALTER TABLE LOAN_ENTRY_POSTING_RULE ADD  AFF_LOAN_REMITTANCE NUMBER(20) DEFAULT 0;
INSERT INTO LOAN_ENTRY_POSTING_RULE(POSTING_RULE_ID, AFF_LOAN_REMITTANCE) VALUES(8860,1);
INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID) VALUES(8860,8860,8860,8860);
insert into loan_event_entry_type_link values(60,8860);


INSERT INTO ENTRY_TYPE(UNIQUE_ID,ID,INSTITUTION_ID,DEBIT_OR_CREDIT,DESCRIPTION,ACCOUNT_CATEGORY,POSTING_SEQUENCE,IS_REVERSAL)
    values((select max(unique_id)+1 from entry_type),'1878',null,'0','REMIT PRINCIPLE AMT',2,NULL,0);
INSERT INTO ENTRY_TYPE(UNIQUE_ID,ID,INSTITUTION_ID,DEBIT_OR_CREDIT,DESCRIPTION,ACCOUNT_CATEGORY,POSTING_SEQUENCE,IS_REVERSAL)
    values((select max(unique_id)+1 from entry_type),'1978',null,'1','REMIT PRINCIPLE AMT',2,NULL,0);
ALTER TABLE LOAN_ENTRY_POSTING_RULE ADD  AFF_REMIT_PRINCIPLE_AMT NUMBER(20) DEFAULT 0;
INSERT INTO LOAN_ENTRY_POSTING_RULE(POSTING_RULE_ID, AFF_REMIT_PRINCIPLE_AMT) VALUES(78, 1);
INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID) 
    VALUES((select unique_id from entry_type where id='1878'), 78, (select unique_id from entry_type where id='1978'), 78);
INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID) 
    VALUES((select unique_id from entry_type where id='1978'), 78, (select unique_id from entry_type where id='1878'), 78);
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (060,(SELECT unique_id FROM entry_type WHERE ID='1878'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (260,(SELECT unique_id FROM entry_type WHERE ID='1978'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_REMIT_PRINCIPLE_AMT=1 WHERE POSTING_RULE_ID=8860;


INSERT INTO ENTRY_TYPE(UNIQUE_ID,ID,INSTITUTION_ID,DEBIT_OR_CREDIT,DESCRIPTION,ACCOUNT_CATEGORY,POSTING_SEQUENCE,IS_REVERSAL)
    values((select max(unique_id)+1 from entry_type),'1879',null,'0','REMIT INTEREST AMT',2,NULL,0);
INSERT INTO ENTRY_TYPE(UNIQUE_ID,ID,INSTITUTION_ID,DEBIT_OR_CREDIT,DESCRIPTION,ACCOUNT_CATEGORY,POSTING_SEQUENCE,IS_REVERSAL)
    values((select max(unique_id)+1 from entry_type),'1979',null,'1','REMIT INTEREST AMT',2,NULL,0);
ALTER TABLE LOAN_ENTRY_POSTING_RULE ADD  AFF_REMIT_INTEREST_AMT NUMBER(20) DEFAULT 0;
INSERT INTO LOAN_ENTRY_POSTING_RULE(POSTING_RULE_ID, AFF_REMIT_INTEREST_AMT) VALUES(79, 1);
INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID) 
    VALUES((select unique_id from entry_type where id='1879'), 79, (select unique_id from entry_type where id='1977'), 79);
INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID) 
    VALUES((select unique_id from entry_type where id='1979'), 79, (select unique_id from entry_type where id='1879'), 79);
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (060,(SELECT unique_id FROM entry_type WHERE ID='1879'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (260,(SELECT unique_id FROM entry_type WHERE ID='1979'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_REMIT_INTEREST_AMT=1 WHERE POSTING_RULE_ID=8860;


ALTER TABLE LOAN_ENTRY_POSTING_RULE ADD AFF_LAST_REMIT_DATE NUMBER(20) DEFAULT 0;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_LAST_REMIT_DATE=1 WHERE POSTING_RULE_ID=8860;


ALTER TABLE LOAN_ENTRY_POSTING_RULE ADD AFF_SALES_DISB_DATES NUMBER(20) DEFAULT 0;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_SALES_DISB_DATES=1 WHERE POSTING_RULE_ID=8879;