ALTER TABLE COUPON_BOOK_SPECIFICATION ADD  ESCROW_BALANCE NUMBER(20,5);

ALTER TABLE COUPON_BOOK_SPECIFICATION ADD  INTEREST_RATE NUMBER(20,5);

ALTER TABLE COUPON_BOOK_SPECIFICATION ADD  NEXT_INT_ADJ_DATE DATE;

ALTER TABLE COUPON_BOOK_SPECIFICATION ADD  PREPAYMENT_PENALTY VARCHAR2(100);

ALTER TABLE COUPON_BOOK_SPECIFICATION ADD  LATE_PAYMENT_FEE_PERCENTAGE NUMBER(20,5);

ALTER TABLE COUPON_BOOK_SPECIFICATION ADD  MATURITY_DATE DATE;

ALTER TABLE COUPON_BOOK_SPECIFICATION ADD  PARTIAL_FUNDS NUMBER(20,5);

ALTER TABLE COUPON_BOOK_SPECIFICATION ADD  NUM_OF_PAYMENTS NUMBER(20);

ALTER TABLE COUPON_BOOK_SPECIFICATION ADD  COLLATERAL_ADDRESS_1 VARCHAR2(100);

ALTER TABLE COUPON_BOOK_SPECIFICATION ADD  COLLATERAL_ADDRESS_2 VARCHAR2(100);

ALTER TABLE COUPON_BOOK_SPECIFICATION ADD  COLLATERAL_CITY VARCHAR2(100);

ALTER TABLE COUPON_BOOK_SPECIFICATION ADD  COLLATERAL_COUNTRY VARCHAR2(100);

ALTER TABLE COUPON_BOOK_SPECIFICATION ADD  COLLATERAL_STATE VARCHAR2(100);

ALTER TABLE COUPON_BOOK_SPECIFICATION ADD  COLLATERAL_ZIP VARCHAR2(100);
