
INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(90, '090', 0, 290, null, 'Participation Transfer Credit Adjustment', '0');
INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(290, '290', 1, 90, null, 'Participation Transfer Creidt Adjustment Reversal', '1');
INSERT INTO ENTRY_TYPE(UNIQUE_ID,ID,INSTITUTION_ID,DEBIT_OR_CREDIT,DESCRIPTION,ACCOUNT_CATEGORY,POSTING_SEQUENCE,IS_REVERSAL)
VALUES(8890, '8890', null, '0', 'Participation Transfer Credit Adjustment', 2, NULL, '0');

ALTER TABLE LOAN_ENTRY_POSTING_RULE ADD  AFF_PART_TRAN_CREDIT_ADJ NUMBER(20) DEFAULT 0;
 INSERT INTO LOAN_ENTRY_POSTING_RULE(POSTING_RULE_ID, AFF_PART_TRAN_CREDIT_ADJ) VALUES(8890,1);
 
 INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID) VALUES(8890,8890,8890,8890);
  
 insert into loan_event_entry_type_link values(90,8890);
 
-------------------------------------------------------- 
 
INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(91, '091', 0, 291, null, 'Participation Transfer Debit Adjustment', '0');
INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(291, '291', 1, 91, null, 'Participation Transfer Debit Adjustment Reversal', '1');
INSERT INTO ENTRY_TYPE(UNIQUE_ID,ID,INSTITUTION_ID,DEBIT_OR_CREDIT,DESCRIPTION,ACCOUNT_CATEGORY,POSTING_SEQUENCE,IS_REVERSAL)
VALUES(8891, '8891', null, '0', 'Participation Transfer Debit Adjustment', 2, NULL, '0');

ALTER TABLE LOAN_ENTRY_POSTING_RULE ADD  AFF_PART_TRAN_DEBIT_ADJ NUMBER(20) DEFAULT 0;
 INSERT INTO LOAN_ENTRY_POSTING_RULE(POSTING_RULE_ID, AFF_PART_TRAN_DEBIT_ADJ) VALUES(8891,1);
 
 INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID) VALUES(8891,8891,8891,8891);
  
 insert into loan_event_entry_type_link values(91,8891);
 
 ---------------------------------------------------------
 
 UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_PRINCIPAL_BALANCE=1 WHERE POSTING_RULE_ID=8890;
  UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_PRINCIPAL_BALANCE=1 WHERE POSTING_RULE_ID=8891;