update loan_event_type set description= 'Initial Funding' where EVENT_TYPE_ID = '1' ;
update loan_event_type set description= 'Interest Payment' where EVENT_TYPE_ID = '13' ;
update loan_event_type set description= 'Escrow Payment' where EVENT_TYPE_ID =	'14' ;
update loan_event_type set description= 'Loan Payoff payment' where EVENT_TYPE_ID ='15' ;
update loan_event_type set description= 'Late Charge Payment' where EVENT_TYPE_ID = '16';
update loan_event_type set description= 'Life -A/H Payment' where EVENT_TYPE_ID = '17';
update loan_event_type set description= 'Origination Fee Payment' where EVENT_TYPE_ID =	'18';
update loan_event_type set description= 'Principal Debit Adjustment' where EVENT_TYPE_ID ='21';
update loan_event_type set description= 'Late Charge Paid Debit Adjustment' where EVENT_TYPE_ID ='22';
update loan_event_type set description= 'Other Fee Debit Adjustment' where EVENT_TYPE_ID ='24';
update loan_event_type set description= 'Interest Paid - Debit Adjustment' where EVENT_TYPE_ID ='25';
update loan_event_type set description= 'Principal - Credit Adjustment' where EVENT_TYPE_ID ='31';
update loan_event_type set description= 'Interest Paid - Credit Adjustment' where EVENT_TYPE_ID ='35';
update loan_event_type set description= 'Escrow Disbursement' where EVENT_TYPE_ID ='40';
update loan_event_type set description= 'Life -A/H Disbursement' where EVENT_TYPE_ID ='41';
update loan_event_type set description= 'END DAY' where EVENT_TYPE_ID ='99';
update loan_event_type set description= 'Regular Payment' where EVENT_TYPE_ID ='110';
update loan_event_type set description= 'Curtailment Non True Payment' where EVENT_TYPE_ID ='120';
update loan_event_type set description= 'Curtailment Payment' where EVENT_TYPE_ID ='121'; 
update loan_event_type set description= 'Initial Funding Reversal' where EVENT_TYPE_ID ='201';
update loan_event_type set description= 'Interest Payment Reversal' where EVENT_TYPE_ID ='213';
update loan_event_type set description= 'Escrow Payment Reversal' where EVENT_TYPE_ID ='214';
update loan_event_type set description= 'Loan Payoff Reversal' where EVENT_TYPE_ID ='215';
update loan_event_type set description= 'Late Charge Payment Reversal' where EVENT_TYPE_ID ='216';
update loan_event_type set description= 'Life-A/H Payment Reversal' where EVENT_TYPE_ID ='217';
update loan_event_type set description= 'Origination Fee Payment Reversal' where EVENT_TYPE_ID ='218';
update loan_event_type set description= 'Principal- Debit Adjustment Reversal' where EVENT_TYPE_ID ='221';
update loan_event_type set description= 'Late Charge Paid- Debit Adjustment Reversal' where EVENT_TYPE_ID ='222';
update loan_event_type set description= 'Other Fee- Debit Adjustment Reversal' where EVENT_TYPE_ID ='224';
update loan_event_type set description= 'Interest Paid - Debit Adjustment Reversal' where EVENT_TYPE_ID ='225';
update loan_event_type set description= 'Principal- Credit Adjustment Reversal' where EVENT_TYPE_ID ='231';
update loan_event_type set description= 'Interest Paid - Credit Adjustment Reversal' where EVENT_TYPE_ID ='235';
update loan_event_type set description= 'Escrow Disbursement Reversal' where EVENT_TYPE_ID ='240';
update loan_event_type set description= 'Life -A/H Disbursement Reversal' where EVENT_TYPE_ID ='241';
update loan_event_type set description= 'END DAY Reversal' where EVENT_TYPE_ID ='299';
update loan_event_type set description= 'Regular Payment Reversal' where EVENT_TYPE_ID ='310';
update loan_event_type set description= 'Curtailment Non True Payment Reversal' where EVENT_TYPE_ID ='320';
update loan_event_type set description= 'Curtailment Payment Reversal' where EVENT_TYPE_ID ='321';

update loan_event_type set debit_or_credit='0' where EVENT_TYPE_ID='1';
update loan_event_type set debit_or_credit='0' where EVENT_TYPE_ID='5';
update loan_event_type set debit_or_credit='1' where EVENT_TYPE_ID='13';
update loan_event_type set debit_or_credit='1' where EVENT_TYPE_ID='14';
update loan_event_type set debit_or_credit='1' where EVENT_TYPE_ID='15';
update loan_event_type set debit_or_credit='1' where EVENT_TYPE_ID='16';
update loan_event_type set debit_or_credit='1' where EVENT_TYPE_ID='17';
update loan_event_type set debit_or_credit='1' where EVENT_TYPE_ID='18';
update loan_event_type set debit_or_credit='1' where EVENT_TYPE_ID='19';
update loan_event_type set debit_or_credit='0' where EVENT_TYPE_ID='21';
update loan_event_type set debit_or_credit='0' where EVENT_TYPE_ID='22';
update loan_event_type set debit_or_credit='0' where EVENT_TYPE_ID='24';
update loan_event_type set debit_or_credit='0' where EVENT_TYPE_ID='25';
update loan_event_type set debit_or_credit='1' where EVENT_TYPE_ID='31';
update loan_event_type set debit_or_credit='1' where EVENT_TYPE_ID='32';
update loan_event_type set debit_or_credit='1' where EVENT_TYPE_ID='33';
update loan_event_type set debit_or_credit='1' where EVENT_TYPE_ID='34';
update loan_event_type set debit_or_credit='1' where EVENT_TYPE_ID='35';
update loan_event_type set debit_or_credit='0' where EVENT_TYPE_ID='40';
update loan_event_type set debit_or_credit='0' where EVENT_TYPE_ID='41';
update loan_event_type set debit_or_credit='1' where EVENT_TYPE_ID='110';
update loan_event_type set debit_or_credit='1' where EVENT_TYPE_ID='120';
update loan_event_type set debit_or_credit='1' where EVENT_TYPE_ID='121';
update loan_event_type set debit_or_credit='1' where EVENT_TYPE_ID='201';
update loan_event_type set debit_or_credit='1' where EVENT_TYPE_ID='205';
update loan_event_type set debit_or_credit='0' where EVENT_TYPE_ID='213';
update loan_event_type set debit_or_credit='0' where EVENT_TYPE_ID='214';
update loan_event_type set debit_or_credit='0' where EVENT_TYPE_ID='215';
update loan_event_type set debit_or_credit='0' where EVENT_TYPE_ID='216';
update loan_event_type set debit_or_credit='0' where EVENT_TYPE_ID='217';
update loan_event_type set debit_or_credit='0' where EVENT_TYPE_ID='218';
update loan_event_type set debit_or_credit='0' where EVENT_TYPE_ID='219';
update loan_event_type set debit_or_credit='1' where EVENT_TYPE_ID='221';
update loan_event_type set debit_or_credit='1' where EVENT_TYPE_ID='222';
update loan_event_type set debit_or_credit='1' where EVENT_TYPE_ID='224';
update loan_event_type set debit_or_credit='1' where EVENT_TYPE_ID='225';
update loan_event_type set debit_or_credit='0' where EVENT_TYPE_ID='231';
update loan_event_type set debit_or_credit='0' where EVENT_TYPE_ID='232';
update loan_event_type set debit_or_credit='0' where EVENT_TYPE_ID='233';
update loan_event_type set debit_or_credit='0' where EVENT_TYPE_ID='234';
update loan_event_type set debit_or_credit='0' where EVENT_TYPE_ID='235';
update loan_event_type set debit_or_credit='1' where EVENT_TYPE_ID='240';
update loan_event_type set debit_or_credit='1' where EVENT_TYPE_ID='241';
update loan_event_type set debit_or_credit='0' where EVENT_TYPE_ID='242';
update loan_event_type set debit_or_credit='0' where EVENT_TYPE_ID='310';
update loan_event_type set debit_or_credit='0' where EVENT_TYPE_ID='320';
update loan_event_type set debit_or_credit='0' where EVENT_TYPE_ID='321';

update loan_event_type set event_group='0' where event_type_id='99';

update loan_event_type set event_group='1' where event_type_id='299';
