ALTER TABLE LOAN_APPLICATION_EVENT ADD REQUESTOR_NAME VARCHAR2(30);
ALTER TABLE LOAN_APPLICATION_EVENT ADD REQUESTOR_CONTACTNUM VARCHAR2(30);
ALTER TABLE LOAN_APPLICATION_EVENT ADD CHANNEL VARCHAR2(30);
ALTER TABLE LOAN_APPLICATION_EVENT ADD VERSION_DETAILS VARCHAR2(30);
ALTER TABLE LOAN_APPLICATION_EVENT ADD WEB_BROWSER VARCHAR2(30);
ALTER TABLE LOAN_APPLICATION_EVENT ADD APPROVER_NAME VARCHAR2(100);
ALTER TABLE LOAN_APPLICATION_EVENT ADD APPROVED_IP VARCHAR2(30);

alter table INSTITUTION add  RATE_CHANGE_PROCESS number(4) default 0;