CREATE TABLE "ORIGINATOR_MASTER" (
    "ORIGINATOR_UID" NUMBER(30,0) NOT NULL ENABLE, 
	  "ORIGINATOR" NUMBER(30,0),
    "DESCRIPTION" VARCHAR2(100),
    "FREQUENCY" VARCHAR2(50),
    "SOURCE" VARCHAR2(50),
    "TIME" DATE,
    "FILEFORMATE" VARCHAR2(100),
    "OFFSET_ACCOUNT" VARCHAR2(50),
    "SUSPENSE_ACCOUNT" VARCHAR2(50),
    "SRC_FILE_NAME" VARCHAR2(100),
    "TARGET_FILE_NAME" VARCHAR2(100),
    "INSTITUTION_ID" VARCHAR2(30),
   CONSTRAINT "ORIGINATOR_MASTER_PK" PRIMARY KEY ("ORIGINATOR_UID") ENABLE);

create sequence ORIGINATOR_MASTER_UID_SEQ minvalue 1 maxvalue 9999999999 increment by 1 start with 1;


CREATE TABLE "STATEMENT_CODES_MASTER" (
    "STATEMENT_CODE_UID" NUMBER(30,0) NOT NULL ENABLE, 
	  "STATEMENT_CODE" NUMBER(30,0) NOT NULL UNIQUE,
    "DESCRIPTION" VARCHAR2(100),
    "INSTITUTION_ID" VARCHAR2(30),
   CONSTRAINT "STATEMENT_CODES_MASTER_PK" PRIMARY KEY ("STATEMENT_CODE_UID") ENABLE);

create sequence STMNT_CODES_MASTER_UID_SEQ minvalue 1 maxvalue 9999999999 increment by 1 start with 1;


CREATE TABLE "TRANSACTION_CODES_MASTER" (
    "TRANSACTION_CODE_UID" NUMBER(30,0) NOT NULL ENABLE, 
	  "TRANSACTION_CODE" NUMBER(30,0) NOT NULL UNIQUE,
    "INDICATOR" VARCHAR2(50),
    "INSTITUTION_ID" VARCHAR2(30),
   CONSTRAINT "TRANSACTION_CODES_MASTER_PK" PRIMARY KEY ("TRANSACTION_CODE_UID") ENABLE);

create sequence TRANS_CODES_MASTER_UID_SEQ minvalue 1 maxvalue 9999999999 increment by 1 start with 1;

CREATE TABLE "SETTLEMENT_TYPE_CODES_MASTER" (
    "SETTLEMENT_TYPE_UID" NUMBER(30,0) NOT NULL ENABLE, 
	  "SETTLEMENT_TYPE_CODE" NUMBER(30,0),
    "DESCRIPTION" VARCHAR2(50),
    "INSTITUTION_ID" VARCHAR2(30),
   CONSTRAINT "SETTLE_TYPE_CODES_MASTER_PK" PRIMARY KEY ("SETTLEMENT_TYPE_UID") ENABLE);

create sequence SETTLE_CODES_MASTER_UID_SEQ minvalue 1 maxvalue 9999999999 increment by 1 start with 1;


CREATE TABLE "SETTLEMNT_TRANS_DEFINITION" (
    "UNIQUE_ID" NUMBER(30,0) NOT NULL ENABLE, 
	  "ORIGINATOR_UID" NUMBER(30,0) ,
    "STATEMENT_CODE_UID" NUMBER(30,0),
    "SETTLEMENT_TYPE_UID" NUMBER(30,0),
    "TRANSACTION_CODE_UID" NUMBER(30,0),
    "TRANS_DESC_TYPE" VARCHAR2(50),
     "DESCRIPTION" VARCHAR2(100),
    "INSTITUTION_ID" VARCHAR2(30),
   CONSTRAINT "MAPPING_PK" PRIMARY KEY ("UNIQUE_ID") ENABLE,
   CONSTRAINT "ORIGINATOR_FK" FOREIGN KEY ("ORIGINATOR_UID") REFERENCES "ORIGINATOR_MASTER" ("ORIGINATOR_UID") ENABLE,
   CONSTRAINT "STATEMENT_CODE_FK" FOREIGN KEY ("STATEMENT_CODE_UID") REFERENCES "STATEMENT_CODES_MASTER" ("STATEMENT_CODE_UID") ENABLE,
   CONSTRAINT "SETTLEMENT_TYPE_FK" FOREIGN KEY ("SETTLEMENT_TYPE_UID") REFERENCES "SETTLEMENT_TYPE_CODES_MASTER" ("SETTLEMENT_TYPE_UID") ENABLE,
   CONSTRAINT "TRANSACTION_CODE_FK" FOREIGN KEY ("TRANSACTION_CODE_UID") REFERENCES "TRANSACTION_CODES_MASTER" ("TRANSACTION_CODE_UID") ENABLE);
   
create sequence "SETTLEMNT_TRANS_DEFI_SEQ" minvalue 1 maxvalue 9999999999 increment by 1 start with 1;


CREATE TABLE "SETTLEMENT_ACC_MAPPING" (
    "UNIQUE_ID" NUMBER(30,0) NOT NULL ENABLE, 
     "RTN" VARCHAR2(50),
	  "ORIGINATOR_UID" NUMBER(30,0) ,
    "SETTLEMENT_TYPE_UID" NUMBER(30,0),
     "SETTLEMENT_ACCOUNT" VARCHAR2(50),
     "INSTITUTION_ID" VARCHAR2(30),
   CONSTRAINT "SETTLEMENT_ACC_MAP_PK" PRIMARY KEY ("UNIQUE_ID") ENABLE,
   CONSTRAINT "ORIGINATOR_SETTLE_FK" FOREIGN KEY ("ORIGINATOR_UID") REFERENCES "ORIGINATOR_MASTER" ("ORIGINATOR_UID") ENABLE,
   CONSTRAINT "SETTLEMENT_TYPE_SETTLE_FK" FOREIGN KEY ("SETTLEMENT_TYPE_UID") REFERENCES "SETTLEMENT_TYPE_CODES_MASTER" ("SETTLEMENT_TYPE_UID") ENABLE);

create sequence "SETTLEMNT_ACC_MAPPING_SEQ" minvalue 1 maxvalue 9999999999 increment by 1 start with 1;
