  CREATE TABLE "IRA_PRECHECK_REGISTER" 
   (	"IRA_PRE_CHECK_ID" NUMBER(15,0), 
	"PRECHECK_AMOUNT" VARCHAR2(30), 
        "DISTRIBUTION_AMOUNT" VARCHAR2(30), 
        "FEDERAL_TAX" VARCHAR2(30), 
         "STATE_TAX" VARCHAR2(30), 
        "NEXT_DISTRIBUTION_DATE" DATE, 
        "PRE_CHECK_ISSUANCE_DATE" DATE, 
        "POSTING_DATE" DATE, 
        "IRA_PLAN_NUMBER" VARCHAR2(30), 
        "INSTITUTION_NUMBER" VARCHAR2(30), 
                
	 PRIMARY KEY ("IRA_PRE_CHECK_ID")
    );
    
  CREATE SEQUENCE IRA_PRECHECK_REG_ID_SEQ
       START WITH     1
       INCREMENT BY   1
       NOCACHE
       NOCYCLE;
       
       
  CREATE TABLE "IRA_CD_DISTR_DETAILS" 
   (	"IRA_CD_DISTR_DET_ID" NUMBER(10,0), 
	"ACCOUNT_NUMBER" VARCHAR2(100), 
	"DISTRIBUTION_AMOUNT" VARCHAR2(30), 
	"IRA_PRE_CHECK_ID" NUMBER(15,0), 
	 PRIMARY KEY ("IRA_CD_DISTR_DET_ID"),
 	 FOREIGN KEY ("IRA_PRE_CHECK_ID")
	 REFERENCES "IRA_PRECHECK_REGISTER" ("IRA_PRE_CHECK_ID") 
         
   );
     
        
    CREATE SEQUENCE IRA_CD_DISTR_ID_SEQ
       START WITH     1
       INCREMENT BY   1
       NOCACHE
       NOCYCLE;
       
   CREATE TABLE "TAX_WITHHOLDING_DETAILS" 
   (	"TAX_WITH_HOLD_DET_ID" NUMBER(15,0), 
	"TAXABLE_AMOUNT" VARCHAR2(30), 
        "PAID_TAX" VARCHAR2(30), 
        "TAX_APPLIED_DATE" DATE,
        "ENTRY_DATE" DATE,
        
         "ACCOUNT_NUMBER" VARCHAR2(30), 
         "TYPE_OF_TAX" VARCHAR2(30), 
        "CUST_NAME" VARCHAR2(30), 
          "INSTITUTION_NUMBER" VARCHAR2(30), 
             INST_NAME VARCHAR2(100) ,  
	 PRIMARY KEY ("TAX_WITH_HOLD_DET_ID")
    );
    
      
       CREATE SEQUENCE TAX_WITH_HOLD_DET_ID_SEQ
       START WITH     1
       INCREMENT BY   1
       NOCACHE
       NOCYCLE;
       
       
       
       

    CREATE OR REPLACE VIEW TAX_WITHHOLDING_DET_VW AS
    SELECT "TAX_WITH_HOLD_DET_ID","TAXABLE_AMOUNT" 
            "PAID_TAX" , "TAX_APPLIED_DATE" ,"ENTRY_DATE" 
            , "ACCOUNT_NUMBER" ,  "TYPE_OF_TAX" , "CUST_NAME" , 
              "INSTITUTION_NUMBER" ,INST_NAME 
    FROM TAX_WITHHOLDING_DETAILS;

       
       
      
     ALTER TABLE PAYMENT_AUTHORIZATION ADD FEDERAL_TAX VARCHAR2(20);
     ALTER TABLE PAYMENT_AUTHORIZATION ADD STATE_TAX VARCHAR2(20);
         
         
     ALTER TABLE ACCOUNT_CHECK_PAYMENT ADD FEDERAL_TAX VARCHAR2(20);
     ALTER TABLE ACCOUNT_CHECK_PAYMENT ADD STATE_TAX VARCHAR2(20);
         
        
     ALTER TABLE PERSON ADD DECEASED NUMBER(10,2) default 1;
     ALTER TABLE PERSON ADD DISABLED NUMBER(10,2) default 1;
     
    ALTER TABLE IRA_PRECHECK_REGISTER ADD TRANSFER_AMOUNT VARCHAR2(20);
    ALTER TABLE IRA_PRECHECK_REGISTER ADD CHECK_NUMBER VARCHAR2(20);
    ALTER TABLE IRA_PRECHECK_REGISTER ADD PC_ACCOUNT_NUMBER VARCHAR2(20);
    ALTER TABLE IRA_PRECHECK_REGISTER ADD PC_ACCOUNT_TYPE VARCHAR2(20);
    ALTER TABLE IRA_PRECHECK_REGISTER ADD INST_NAME VARCHAR2(100);
  
    ALTER TABLE IRA_PRECHECK_REGISTER ADD CUST_NAME VARCHAR2(50);
    
    ALTER TABLE IRA_PRECHECK_REGISTER ADD ACCOUNT_NUMBERS VARCHAR2(100);
    
    ALTER TABLE IRA_PRECHECK_REGISTER ADD INSTRUCTION_ID NUMBER(30,2);
      
    ALTER TABLE IRA_PRECHECK_REGISTER ADD ID NUMBER(30,2);
    
    ALTER TABLE IRA_PRECHECK_REGISTER RENAME column DISTRIBUTION_AMOUNT TO TOTAL_DISTRIBUTION_AMOUNT;
     
    ALTER TABLE IRA_CD_DISTR_DETAILS ADD REMAINING_AMOUNT VARCHAR2(20);
    
    ALTER TABLE IRA_PRECHECK_REGISTER ADD   FOREIGN KEY (ID) REFERENCES PAYMENT_AUTHORIZATION (ID) ; 
    
    
    CREATE OR REPLACE VIEW TAX_WITHHOLDING_DET_VW AS
    SELECT "TAX_WITH_HOLD_DET_ID","TAXABLE_AMOUNT" 
            "PAID_TAX" , "TAX_APPLIED_DATE" ,"ENTRY_DATE" 
            , "ACCOUNT_NUMBER" ,  "TYPE_OF_TAX" , "CUST_NAME" , 
              "INSTITUTION_NUMBER" ,INST_NAME 
    FROM TAX_WITHHOLDING_DETAILS;
    
    ALTER TABLE IRA_PRECHECK_REGISTER ADD DISTRIBUTION_AMOUNT VARCHAR2(20);
    
      CREATE OR REPLACE VIEW IRA_DISTR_HIST_VW AS
    SELECT ipr.IRA_PRE_CHECK_ID, ipr.INSTRUCTION_ID,TOTAL_DISTRIBUTION_AMOUNT,FEDERAL_TAX,STATE_TAX
      ,POSTING_DATE,NEXT_DISTRIBUTION_DATE,PRE_CHECK_ISSUANCE_DATE,IRA_PLAN_NUMBER
      ,CUST_NAME,INSTITUTION_NUMBER,TRANSFER_AMOUNT,CHECK_NUMBER,PC_ACCOUNT_NUMBER,
       PC_ACCOUNT_TYPE,INST_NAME,ACCOUNT_NUMBER,IPR.DISTRIBUTION_AMOUNT,REMAINING_AMOUNT
      FROM IRA_PRECHECK_REGISTER IPR,IRA_CD_DISTR_DETAILS ICDD
  
      where ipr.IRA_PRE_CHECK_ID = icdd.IRA_PRE_CHECK_ID;
      
 DROP TABLE TAX_WITHHOLDING_DETAILS;

 CREATE TABLE "TAX_WITHHOLDING_DETAILS" 
     (	"TAX_WITH_HOLD_DET_ID" NUMBER(15,0), 
          "TAXABLE_AMOUNT" VARCHAR2(30), 
          "PAID_TAX" VARCHAR2(30), 
          "TAX_APPLIED_DATE" DATE,
          "ENTRY_DATE" DATE,
          
           "ACCOUNT_NUMBER" VARCHAR2(30), 
           "TYPE_OF_TAX" VARCHAR2(30), 
          "CUST_NAME" VARCHAR2(30), 
            "INSTITUTION_NUMBER" VARCHAR2(30), 
               INST_NAME VARCHAR2(100) ,  
           PRIMARY KEY ("TAX_WITH_HOLD_DET_ID")
      );
      
ALTER TABLE DEPOSIT ADD TIMES_NSF_PREV_YEAR NUMBER(10) default 0;
ALTER TABLE TAX_WITHHOLDING_DETAILS DROP COLUMN ACCOUNT_NUMBER;
ALTER TABLE TAX_WITHHOLDING_DETAILS ADD  ACCOUNT_NUMBER VARCHAR2(400);
 ALTER TABLE IRA_PRECHECK_REGISTER ADD ENTRY_DATE DATE;
   
   ALTER TABLE IRA_PRECHECK_REGISTER ADD PAYMENT_MODE varchar2(30);
   
   ALTER TABLE IRA_PRECHECK_REGISTER ADD DIST_FREQUENCY varchar2(30);
   
   ALTER TABLE IRA_PRECHECK_REGISTER ADD DISTR_REASON varchar2(30);
   
   
  CREATE OR REPLACE VIEW IRA_DISTR_HIST_VW AS
			SELECT ipr.IRA_PRE_CHECK_ID, ipr.INSTRUCTION_ID,TOTAL_DISTRIBUTION_AMOUNT,FEDERAL_TAX,STATE_TAX
			,POSTING_DATE,NEXT_DISTRIBUTION_DATE,PRE_CHECK_ISSUANCE_DATE,IRA_PLAN_NUMBER
			,CUST_NAME,INSTITUTION_NUMBER,TRANSFER_AMOUNT,CHECK_NUMBER,PC_ACCOUNT_NUMBER,
			PC_ACCOUNT_TYPE,INST_NAME,ACCOUNT_NUMBER,icdd.DISTRIBUTION_AMOUNT,icdd.REMAINING_AMOUNT,
			IPR.DIST_FREQUENCY,IPR.PAYMENT_MODE
			
			
			FROM IRA_PRECHECK_REGISTER IPR,IRA_CD_DISTR_DETAILS ICDD,INSTITUTION INST
			
			
			
			where ipr.IRA_PRE_CHECK_ID = icdd.IRA_PRE_CHECK_ID
			
			AND IPR.INSTITUTION_NUMBER = INST.INSTITUTION_ID
			
			and TRUNC(IPR.ENTRY_DATE) = TRUNC(INST.LAST_PROCESSED_DATE);
			
			
CREATE OR REPLACE VIEW TAX_WITHHOLDING_DET_VW AS
	SELECT "TAX_WITH_HOLD_DET_ID","TAXABLE_AMOUNT", 
	        "PAID_TAX" , "TAX_APPLIED_DATE" ,"ENTRY_DATE" 
	        , "ACCOUNT_NUMBER" ,  "TYPE_OF_TAX" , "CUST_NAME" , 
	          "INSTITUTION_NUMBER" ,"INST_NAME" 
	FROM TAX_WITHHOLDING_DETAILS;
	
 CREATE TABLE "DISTR_REJECTION_DETAILS" 
     (	  "DISRT_REJ_ID" NUMBER(15,0), 
          "CUST_NAME" VARCHAR2(30), 
          "DISTR_REASON" VARCHAR2(30), 
          "ACCOUNT_NUMBERS" VARCHAR2(130), 
          "DISTR_AMOUNT" VARCHAR2(30), 
          "TOTAL_CDS_AMOUNT" VARCHAR2(30), 
          "ENTRY_DATE" DATE,
          "DISTRIBUTION_DATE" DATE,
          DISTR_TYPE VARCHAR2(30), 
                
          "INSTITUTION_NUMBER" VARCHAR2(30), 
          "INST_NAME" VARCHAR2(100) ,  
           PRIMARY KEY ("DISRT_REJ_ID")
      );
      
      
CREATE OR REPLACE VIEW DISTR_REJECTION_DET_VW AS
	SELECT "DISRT_REJ_ID","CUST_NAME" ,
	        "DISTR_REASON" , "ACCOUNT_NUMBERS" ,"DISTR_AMOUNT" 
	        , "TOTAL_CDS_AMOUNT" ,  "ENTRY_DATE" , "DISTRIBUTION_DATE" , 
	          "INSTITUTION_NUMBER" ,"INST_NAME","DISTR_TYPE" 
	FROM DISTR_REJECTION_DETAILS DRD,INSTITUTION INST
	
	WHERE DRD.INSTITUTION_NUMBER = INST.INSTITUTION_ID
	
	and TRUNC(DRD.ENTRY_DATE) = TRUNC(INST.LAST_PROCESSED_DATE);
	
CREATE SEQUENCE DISTR_REJECTION_ID_SEQ
       START WITH     1
       INCREMENT BY   1
       NOCACHE
       NOCYCLE;
  
ALTER TABLE TAX_WITHHOLDING_DETAILS MODIFY ACCOUNT_NUMBER VARCHAR2(300);


ALTER TABLE DISTR_REJECTION_DETAILS MODIFY DISTR_REASON VARCHAR2(100);
ALTER TABLE IRA_PRECHECK_REGISTER  MODIFY DISTR_REASON VARCHAR2(100);


    CREATE TABLE "LAST_DISTR_NOTICE_DETAILS" 
     (	  "LST_DISTR_NOTICE_ID" NUMBER(15,0), 
          "CUST_NAME" VARCHAR2(30), 
          "DISTR_REASON" VARCHAR2(30), 
          "ACCOUNT_NUMBERS" VARCHAR2(130), 
          "DISTR_AMOUNT" VARCHAR2(30), 
          "TOTAL_CDS_AMOUNT" VARCHAR2(30), 
          "ENTRY_DATE" DATE,
          "DISTRIBUTION_DATE" DATE,
          DISTR_TYPE VARCHAR2(30), 
          ACCOUNT_NUMBER VARCHAR2(30), 
          SAVINGS_PLAN_NO VARCHAR2(30), 
          "INSTITUTION_NUMBER" VARCHAR2(30), 
          "INST_NAME" VARCHAR2(100) ,  
           PRIMARY KEY ("LST_DISTR_NOTICE_ID")
      );
      
   CREATE SEQUENCE LST_DISTR_NOTICE_ID_SEQ
       START WITH     1
       INCREMENT BY   1
       NOCACHE
       NOCYCLE;
       
       
       
   CREATE OR REPLACE FORCE VIEW "LAST_DISTR_NOTICE_VW" AS
            SELECT  "CUST_NAME" , "DISTR_REASON","ACCOUNT_NUMBERS", "DISTR_AMOUNT","TOTAL_CDS_AMOUNT", "ENTRY_DATE" 
          "DISTRIBUTION_DATE"," DISTR_TYPE","ACCOUNT_NUMBER"," SAVINGS_PLAN_NO","INSTITUTION_NUMBER", "INST_NAME"
     
          FROM LAST_DISTR_NOTICE_DETAILS

       order by SAVINGS_PLAN_NO asc;
       
       

  CREATE OR REPLACE FORCE VIEW "ACCOUNT_DETAILS_VW" ("ACCOUNT_ID", "ACCOUNT_NO", "INSTITUTION_ID", "ACCOUNT_TYPE_ID", "LEDGER_BALANCE", 
  "AVAILABLE_BALANCE", "BUSINESS_DATE", "CURRENT_BALANCE", "UNCOLLECTED_BALANCE", "OVERDRAFT_CODE", "CREATION_DATE", "DATE_LAST_MAINTAINED", 
  "RETURNS_LAST_YR", "TIMES_NSF_CURR_PERIOD", "TIMES_NSF_YTD", "TIMES_OD_CURR_PERIOD", "TIMES_OD_YTD", "OVERDRAFT_LIMIT", 
  "NO_CHRG_BACK_ITEMS_YR_TO_DATE", "TIMES_OD_PRYR", "DATE_OPENED", "DATE_LAST_DEPOSIT", "AVG_BALANCE_CURRENT_PERIOD", "YTD_AVERAGE_BALANCE", 
  "TIMES_NSF_PREV_YEAR") AS 
  (SELECT acc.account_id,de.ACCOUNT_NO,acc.INSTITUTION_ID,de.account_type_id, de.LEDGER_BALANCE,de.AVAILABLE_BALANCE,
  de.BUSINESS_DATE, de.CURRENT_BALANCE,de.UNCOLLECTED_BALANCE,de.OVERDRAFT_CODE,de.CREATION_DATE,
  de.DATE_LAST_MAINTAINED,de.RETURNS_LAST_YR, de.TIMES_NSF_CURR_PERIOD,de.TIMES_NSF_YTD, de.TIMES_OD_CURR_PERIOD,
  de.TIMES_OD_YTD,de.OVERDRAFT_LIMIT,de.NO_CHRG_BACK_ITEMS_YR_TO_DATE,de.TIMES_OD_PRYR, acc.DATE_OPENED, 
  de.DATE_LAST_DEPOSIT, de.AVG_BALANCE_CURRENT_PERIOD, de.YTD_AVERAGE_BALANCE,de.TIMES_NSF_PREV_YEAR  FROM ACCOUNT acc, DEPOSIT
  de WHERE acc.ACCOUNT_ID = de.ACCOUNT_ID );

 CREATE OR REPLACE FORCE VIEW "HOLD_PAYMENT_VIEW" ("INSTRUCTION_ID", "ACCOUNT_ID", "CREATED_DATE", "EFFECTIVE_EXPIRE_DATE", "HOLD_AMOUNT", "ACCOUNT_NO", "HOLD_TYPE") AS 
  (   select dai.instruction_id, dai.account_id, dai.created_date, dai.effective_expire_date, hp.hold_amount, 
        d.account_no,hp.HOLD_TYPE_ID   
        from deposit_account_instruction dai, hold_payment hp, deposit d
    where dai.instruction_id = hp.instruction_id
    and dai.account_id = d.account_id
    and hp.hold_status = 1
  );


  CREATE OR REPLACE FORCE VIEW "STOP_PAYMENT_VIEW" ("INSTRUCTION_ID", "ACCOUNT_ID", "CREATED_DATE", "EFFECTIVE_EXPIRE_DATE", "FEE_AMOUNT") AS 
  (select dai.instruction_id, dai.account_id, dai.created_date, dai.effective_expire_date, 
spi.fee_amount from deposit_account_instruction dai, stop_payment_instruction spi
where dai.instruction_id = spi.instruction_id
and spi.stop_status = 1);