--Loan_Entry_Posting_Rule-

--Coloum Name=AFFECTS_PAYMENT_SPREAD

ALTER TABLE LOAN_ENTRY_POSTING_RULE
       ADD ( "AFFECTS_PAYMENT_SPREAD" NUMBER(1,0) DEFAULT 0 NOT NULL );

UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_PAYMENT_SPREAD =1  WHERE POSTING_RULE_ID = 9999;

--Coloum Name=AFFECTS_SPLIT_PAYMENT_ASBILL


ALTER TABLE LOAN_ENTRY_POSTING_RULE
       ADD ( "AFFECTS_SPLIT_PAYMENT_ASBILL" NUMBER(1,0) DEFAULT 0 NOT NULL );

UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_SPLIT_PAYMENT_ASBILL =1  WHERE POSTING_RULE_ID = 9999;


--EntryName-DailyAccrualFactor

--Coloum Name=AFFECTS_DAILY_ACCRUED_FACTOR



ALTER TABLE LOAN_ENTRY_POSTING_RULE
       ADD ( "AFFECTS_DAILY_ACCRUED_FACTOR" NUMBER(1,0) DEFAULT 0 NOT NULL );



INSERT INTO LOAN_ENTRY_POSTING_RULE(POSTING_RULE_ID) VALUES(58)  ;

UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_DAILY_ACCRUED_FACTOR =1  WHERE POSTING_RULE_ID = 58;


INSERT INTO ENTRY_TYPE(UNIQUE_ID,ID,INSTITUTION_ID,DEBIT_OR_CREDIT,DESCRIPTION,ACCOUNT_CATEGORY,POSTING_SEQUENCE)
    values(1858, '1858' , null , '0' , 'CredifLife Daily Accured Factor' , 2 ,1);

INSERT INTO ENTRY_TYPE(UNIQUE_ID,ID,INSTITUTION_ID,DEBIT_OR_CREDIT,DESCRIPTION,ACCOUNT_CATEGORY,POSTING_SEQUENCE)
    values(1958, '1958' , null , '1' , 'CredifLife Daily Accured Factor' , 2 ,1);

INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID)
    VALUES(1858, 58, 1958, 58);
INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID)
    VALUES(1958 ,58 ,1858 ,58);


insert into LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) values (99,1858);
insert into LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) values (299,1958);






