delete from  ENTRY_TYPE where UNIQUE_ID=1738;

delete from  LOAN_ENTRY_TYPE_LINK where ENTRY_TYPE_ID=1738;

delete from  LOAN_LEDGER_POSTING_PARAMETERS where UNIQUE_ID=1738;

DELETE FROM Loan_entry_type_LINK WHERE  ENTRY_TYPE_ID='1301' AND 
CHILD_ENTRY_TYPE_ID='1902';


INSERT INTO LOAN_ENTRY_TYPE_LINK (ENTRY_TYPE_ID,CHILD_ENTRY_TYPE_ID)
    VALUES('22110','1802');
INSERT INTO LOAN_ENTRY_TYPE_LINK (ENTRY_TYPE_ID,CHILD_ENTRY_TYPE_ID)
    VALUES('32110','1902');


delete from LOAN_ENTRY_TYPE_LINK 
where ENTRY_TYPE_ID in ('1725', '1744','1799') 
and CHILD_ENTRY_TYPE_ID in ('1907', '1908');

INSERT INTO LOAN_ENTRY_TYPE_LINK VALUES('1799','1902');
 
insert into LOAN_ENTRY_TYPE_LINK (ENTRY_TYPE_ID, CHILD_ENTRY_TYPE_ID) values ('1725','1906');
insert into LOAN_ENTRY_TYPE_LINK (ENTRY_TYPE_ID, CHILD_ENTRY_TYPE_ID) values ('1744','1906');
insert into LOAN_ENTRY_TYPE_LINK (ENTRY_TYPE_ID, CHILD_ENTRY_TYPE_ID) values ('1799','1906');


-- Initial Fund
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_LAST_TRAN_AMOUNT=1  WHERE POSTING_RULE_ID = 8881;

----removing entries for last_tran_date(20) and last_stmt_bal(30)
-- ENTRY_TYPE and LOAN_ENTRY_TYPE
delete from ENTRY_TYPE where UNIQUE_ID in ('1820', '1920', '1830', '1930');
delete from LOAN_ENTRY_TYPE where ENTRY_TYPE_ID in ('1820', '1920', '1830', '1930');

--LOAN_ENTRY_POSTING_RULE
delete from LOAN_ENTRY_POSTING_RULE where POSTING_RULE_ID in ('20', '30');
				
update LOAN_EVENT_TYPE set EVENT_GROUP = 0 where EVENT_TYPE_ID in ('42');
update LOAN_EVENT_TYPE set EVENT_GROUP = 1 where EVENT_TYPE_ID in ('242');








