CREATE TABLE USER_ACTIVITY_MASTER
(INSTITUTION_ID	VARCHAR2(5),
ACTIVITY_CODE	NUMBER(5),
ACTIVITY_DESCRIPTION	VARCHAR2(300),
PARENT_ACTIVITY_CODE	NUMBER(5),
ACTIVITY_TYPE	VARCHAR2(20),
CONSTRAINT "USER_ACTIVITY_MASTER_PK" PRIMARY KEY ("ACTIVITY_CODE") ENABLE);

CREATE TABLE USER_ACTIVITY_LOG
(INSTITUTION_ID	VARCHAR2(5),
UALH_ID	NUMBER(10),
BRANCH_ID	VARCHAR2(5),
CHANNEL_ID	NUMBER(30),
USER_ID	VARCHAR2(30),
ACTIVITY_CODE	NUMBER(5),
PARENT_ACTIVITY_CODE	NUMBER(5),
ACTIVITY_TYPE	VARCHAR2(20),
ORIGINATION_UALH_ID	NUMBER(10),
CUSTOMER_ID	VARCHAR2(60),
ACCOUNT_NUMBER	VARCHAR2(60),
BUSINESS_DATETIME	TIMESTAMP,
SYSTEM_DATETIME	TIMESTAMP,
ACTIVITY_MODE	VARCHAR2(1),
DETAIL_RECORD	VARCHAR2(1),
OTHER_DETAILS   VARCHAR2(600),
CONSTRAINT "USER_ACTIVITY_LOG_PK" PRIMARY KEY ("UALH_ID") ENABLE,
CONSTRAINT "ACTIVITY_CODE_FK" FOREIGN KEY ("ACTIVITY_CODE") REFERENCES USER_ACTIVITY_MASTER ("ACTIVITY_CODE") ENABLE);

CREATE SEQUENCE USER_ACTIVITY_LOG_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1;

CREATE TABLE USER_ACTIVITY_LOG_DETAIL
(INSTITUTION_ID	VARCHAR2(5),
UALD_ID	NUMBER(10),
UALH_ID	NUMBER(10),
FIELD_NAME	VARCHAR2(30),
OLD_VALUE	VARCHAR2(600),
NEW_VALUE	VARCHAR2(600),
CONSTRAINT "USER_ACTIVITY_LOG_DTL_PK" PRIMARY KEY ("UALD_ID") ENABLE,
CONSTRAINT "UALH_ID_FK" FOREIGN KEY ("UALH_ID") REFERENCES USER_ACTIVITY_LOG ("UALH_ID") ENABLE);

CREATE SEQUENCE USER_ACTIVITY_LOG_DETAIL_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1;
