
ALTER TABLE LOAN_ACCOUNT DROP (NON_ESCROW_BALANCE);
ALTER TABLE LOAN_ACCOUNT DROP (BEG_ESCROW_BAL);
ALTER TABLE LOAN_ACCOUNT DROP (DEPOSIT_TO_ESCROW);
ALTER TABLE LOAN_ACCOUNT DROP (ESCROW_DISBURSEMETS);
ALTER TABLE LOAN_ACCOUNT DROP (ESCROW_DISBURSEMENTS_IRS);
ALTER TABLE LOAN_ACCOUNT DROP (ESCROW_PAST_DUE);
ALTER TABLE LOAN_ACCOUNT DROP (NON_ESCROW_PAST_DUE);
ALTER TABLE LOAN_ACCOUNT DROP (ESCROW_BALANCE);
ALTER TABLE LOAN_ACCOUNT DROP (LAST_ESCROW_ANALYSIS_DATE);
ALTER TABLE LOAN_ACCOUNT DROP (LOAN_TERM);
ALTER TABLE LOAN_ACCOUNT DROP (APPROVED_LOAN_AMOUNT);
ALTER TABLE LOAN_ACCOUNT DROP (CURRENT_MATURITY_DATE);
ALTER TABLE LOAN_ACCOUNT DROP (DAILY_DEALER_INT_ACCRUAL);
ALTER TABLE LOAN_ACCOUNT DROP (UNUSED_LINE_COMMITMENT_AMT);
ALTER TABLE LOAN_ACCOUNT DROP (PRINCIPAL_BILLED_AMT);
ALTER TABLE LOAN_ACCOUNT DROP (BILLED_ESCROW_DUE);
ALTER TABLE LOAN_ACCOUNT DROP (ACCRUED_TO_DATE);
ALTER TABLE LOAN_ACCOUNT DROP (CURRENT_INTEREST_RATE);
ALTER TABLE LOAN_ACCOUNT DROP (NEXT_INTEREST_AMOUNT_DUE);
ALTER TABLE LOAN_ACCOUNT DROP (BILL_STATUS_CODE);
ALTER TABLE LOAN_ACCOUNT DROP (LIFE_INSURANCE_REBATE);
ALTER TABLE LOAN_ACCOUNT DROP (ACC_INSURANCE_REBATE);
ALTER TABLE LOAN_ACCOUNT DROP (BLOCK_ID);
ALTER TABLE LOAN_ACCOUNT DROP (ACC_INSURANCE_TERM);
ALTER TABLE LOAN_ACCOUNT DROP (CREDIT_LIFE_TERM);
ALTER TABLE LOAN_ACCOUNT DROP (START_DATE);
ALTER TABLE LOAN_ACCOUNT_REBATE DROP (DISCOUNT);

-- LOAN ACCOUNT REBATE
ALTER TABLE LOAN_ACCOUNT_REBATE ADD(COLLATERAL_INSURANCE_REBATE NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT_REBATE ADD(DEALER_HOLD_BACK_REBATE NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT_REBATE ADD(SPECIAL_RESRVE_1_REBATE NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT_REBATE ADD(SPECIAL_RESRVE_2_REBATE NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT_REBATE ADD(DEALER_REBATE NUMBER(20,5));

-- COLLATERAL
ALTER TABLE COLLATERAL ADD(TITLE_OUT_CODE VARCHAR2(30));
ALTER TABLE COLLATERAL ADD(COLLATERAL_INSUR_EXP_DATE  DATE);

-- VARIABLE INTEREST RATE
ALTER TABLE VARIABLE_INTEREST_RATE ADD(NEW_INTEREST_RATE  NUMBER(20,5));
ALTER TABLE VARIABLE_INTEREST_RATE ADD(NEW_NONESCROW_AMOUNT  NUMBER(20,5));
ALTER TABLE VARIABLE_INTEREST_RATE ADD(CURRENT_INDEX  NUMBER(20,5));
ALTER TABLE VARIABLE_INTEREST_RATE ADD(NEW_ESCROW_AMOUNT  NUMBER(20,5));
ALTER TABLE VARIABLE_INTEREST_RATE ADD(PREVIOUS_INDEX_DATE  DATE);
ALTER TABLE VARIABLE_INTEREST_RATE ADD(CURRENT_INDEX_DATE  DATE);

-- ESCROW HEAD
ALTER TABLE ESCROW_HEAD ADD(DISBURSEMENTS_FREQ  VARCHAR2(30));
ALTER TABLE ESCROW_HEAD ADD(DISBURSED_AMOUNT_YTD  NUMBER(20,5));

ALTER TABLE LOAN_ACCOUNT_REBATE DROP (DEALER_REBATE);
ALTER TABLE LOAN_ACCOUNT_REBATE DROP (REBATE);
ALTER TABLE LOAN_ACCOUNT_REBATE DROP (CREDIT_LIFE_REBATE);
ALTER TABLE LOAN_ACCOUNT_REBATE DROP (ACCIDENT_AND_HEALTH_REBATE);
ALTER TABLE LOAN_ACCOUNT_REBATE DROP (CREDIT_LIFE_PREMIUM);
ALTER TABLE LOAN_ACCOUNT_REBATE DROP (ACCIDENT_AND_HEALTH_PREMIUM);

ALTER TABLE LOAN_ACCOUNT  ADD (ACCUMULATED_INTEREST NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT  ADD (AVERAGE_BALANCE_LIFE NUMBER(20,5));

ALTER TABLE LOAN_ACCOUNT DROP (COMMENTS); 
ALTER TABLE LOAN_ACCOUNT DROP (INTEREST_BILLED_AMT);
ALTER TABLE LOAN_ACCOUNT DROP (BILLED_CHARGE1_AMT);
ALTER TABLE LOAN_ACCOUNT DROP (BILLED_CHARGE2_AMT);
ALTER TABLE LOAN_ACCOUNT DROP (BILLED_UNUSEDLINE_C0MMIT_FEE);
ALTER TABLE LOAN_ACCOUNT DROP (BILLED_LINE_C0MMITMENT_FEE);
ALTER TABLE LOAN_ACCOUNT DROP (BILLED_DEALER_INTEREST);
ALTER TABLE LOAN_ACCOUNT DROP (NEXT_ESCROW_DUE);
ALTER TABLE LOAN_ACCOUNT DROP (NON_ESCROW_DUE);
ALTER TABLE LOAN_ACCOUNT DROP (INT_BILLING_DATE);
ALTER TABLE LOAN_ACCOUNT DROP (PRINCIPAL_BILLING_DATE);
ALTER TABLE LOAN_ACCOUNT DROP (FREQUENCY_INTEREST);
ALTER TABLE LOAN_ACCOUNT DROP (PERCENTAGE_PAYMENT_AMOUNT);
ALTER TABLE LOAN_ACCOUNT DROP (LATE_CHARGE_FIXED_AMT);
ALTER TABLE LOAN_ACCOUNT DROP (MAXIMUM_AMOUNT);
ALTER TABLE LOAN_ACCOUNT DROP (MINIMUM_AMOUNT);
ALTER TABLE LOAN_ACCOUNT DROP (MAX_LATE_CHARGE_PER_YEAR);
ALTER TABLE LOAN_ACCOUNT DROP (GRACE_PERIOD);
ALTER TABLE LOAN_ACCOUNT DROP (NEXT_DISBURSEMENT_DATE);
ALTER TABLE LOAN_ACCOUNT DROP (COUPON_FLAG);
ALTER TABLE LOAN_ACCOUNT DROP (COUPON_STAT_DATE);
ALTER TABLE LOAN_ACCOUNT DROP (FIXED_PAYMENT_CODE);
ALTER TABLE LOAN_ACCOUNT DROP (ACCRUED_DLR_INT_DUE);
ALTER TABLE LOAN_ACCOUNT DROP (DEALER_NUMBER);

-- SET UP FOR MANDATORY AND DEFAULT VALUES

--UPDATE PROPERTY_DEFINITION SET DEFAULT_VALUE='com.vsoftcorp.finance.Money:USD 0.00'
--WHERE VALUE_TYPE_DEFINITION_ID=8 AND DEFAULT_VALUE IS NULL;

UPDATE LOAN_ACCOUNT SET PER_DIEM=0 WHERE PER_DIEM IS NULL;
UPDATE LOAN_ACCOUNT SET PRINCIPLE_BALANCE=0 WHERE PRINCIPLE_BALANCE IS NULL;

ALTER TABLE LOAN_ACCOUNT MODIFY PER_DIEM NOT NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY PER_DIEM DEFAULT 0;
ALTER TABLE LOAN_ACCOUNT MODIFY LOAN_STATUS NOT NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY PRINCIPLE_BALANCE NOT NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY PRINCIPLE_BALANCE DEFAULT 0;

ALTER table LOAN_ACCOUNT ADD (DAY_BANK_EARNED_AMOUNT NUMBER(10,2));

--DELETE FROM PROPERTY_DEFINITION WHERE PROPERTY_DEFINITION_ID IN(1765,1766);







