alter table LOAN_ACCOUNT_DAY drop column OPENING_PRNCP_DUE_DATE;
alter table LOAN_ACCOUNT_DAY drop column PRNCP_DUE_DATE;

alter table LOAN_ACCOUNT_DAY add OPENING_PRNCP_DUE_DATE date ;
alter table LOAN_ACCOUNT_DAY add PRNCP_DUE_DATE VARCHAR2(20) ;

alter table LOAN_ACCOUNT_DAY drop column OPENING_INT_DUE_DATE;
alter table LOAN_ACCOUNT_DAY drop column INT_DUE_DATE;

alter table LOAN_ACCOUNT_DAY add OPENING_INT_DUE_DATE date ;
alter table LOAN_ACCOUNT_DAY add INT_DUE_DATE VARCHAR2(20) ;

----removing apply future payment- said by  Sandeep
delete from event_type  where EVENT_TYPE_ID='11,2';


update ENTRY_TYPE set  DESCRIPTION='Late Charge Payment' where UNIQUE_ID='17111';

-------removing advance, cl, ah pymnts
delete from event_type  where EVENT_TYPE_ID in ('5', '17', '18'); 

--update  LOAN_LEDGER_POSTING_PARAMETERS set AFFECTS_OTHER_FEE_DUE=1 where UNIQUE_ID=11101;
--
--update LOAN_LEDGER_POSTING_PARAMETERS set AFFECTS_ACCRUED_INTEREST_NET=1  where UNIQUE_ID= 17010;
--
--update  LOAN_LEDGER_POSTING_PARAMETERS set AFFECTS_OTHER_FEE_DUE=1 where UNIQUE_ID=1951;

update ENTRY_TYPE set DESCRIPTION='Late Charge Payment' where  UNIQUE_ID= 1701;

--ALTER TABLE LOAN_ACCOUNT ADD ( ACCRUED_INTEREST_LTD NUMBER(10,5));

--update LOAN_LEDGER_POSTING_PARAMETERS set ACCOUNT_TYPE_ID = '110' where UNIQUE_ID = '31110';
--
--update LOAN_LEDGER_POSTING_PARAMETERS set AFFECTS_PAYOUT_CODE=1, AFFECTS_DATE_CLOSED=1, AFFECTS_LOAN_STATUS=1
--where UNIQUE_ID in ('1511','1525', '1725', '1728');
--
--update LOAN_LEDGER_POSTING_PARAMETERS set  AFFECTS_LOAN_STATUS=1
--where UNIQUE_ID in ('19020');
--
--update LOAN_LEDGER_POSTING_PARAMETERS set AFFECTS_DATE_CLOSED =1, AFFECTS_LOAN_STATUS =1, AFFECTS_PAYOUT_CODE=1
-- where UNIQUE_ID in (1725, 11101);
--
--update LOAN_LEDGER_POSTING_PARAMETERS set AFFECTS_LOAN_STATUS=0 
--where UNIQUE_ID in ('1701', '1512');


--INSERT INTO ENTITY_TYPE_INSTANCE(ENTITY_TYPE_INSTANCE_ID, TYPE_NAME, TYPE_DESCRIPTION, STATUS)
--  VALUES(6700, 'DistributionHead', 'Distribution Head', 1);
--
--INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
--  VALUES(6700, 'Code', 'java.lang.String:06');
--INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
--  VALUES(6700, 'Description', 'java.lang.String:Life-AH');
--
--UPDATE PROPERTY SET VALUE='java.lang.String:05' WHERE PROPERTY_NAME LIKE 'Code'  AND ENTITY_TYPE_INSTANCE_ID=332;
--UPDATE PROPERTY SET VALUE='java.lang.String:01' WHERE PROPERTY_NAME LIKE 'Code'  AND ENTITY_TYPE_INSTANCE_ID=336;
----UPDATE PROPERTY SET VALUE='java.lang.String:02' WHERE PROPERTY_NAME LIKE 'Code'  AND ENTITY_TYPE_INSTANCE_ID=334;
----UPDATE PROPERTY SET VALUE='java.lang.String:06' WHERE PROPERTY_NAME LIKE 'Code'  AND ENTITY_TYPE_INSTANCE_ID=335;
----UPDATE PROPERTY SET VALUE='java.lang.String:04' WHERE PROPERTY_NAME LIKE 'Code'  AND ENTITY_TYPE_INSTANCE_ID=336;

--DELETE FROM COLLECTION_ASSOCIATE_VALUES WHERE ASSOCIATE_ID IN (221,222,223);

alter table LOAN_LEDGER_POSTING_PARAMETERS drop column AFFECTS_CREDIT_LIFE_DUE;

alter table LOAN_LEDGER_POSTING_PARAMETERS drop column AFFECTS_ACC_HEALTH_DUE;

--update LOAN_LEDGER_POSTING_PARAMETERS set AFFECTS_NONESCROW_BALANCE=1
--where UNIQUE_ID in ('1725', '1728', '1729', '1744');


---mort
insert into LOAN_ENTRY_TYPE_LINK(ENTRY_TYPE_ID, CHILD_ENTRY_TYPE_ID)
values('1951', '1909');

---SIL
insert into LOAN_ENTRY_TYPE_LINK(ENTRY_TYPE_ID, CHILD_ENTRY_TYPE_ID)
values('1725', '1909');
insert into LOAN_ENTRY_TYPE_LINK(ENTRY_TYPE_ID, CHILD_ENTRY_TYPE_ID)
values('1728', '1909');
insert into LOAN_ENTRY_TYPE_LINK(ENTRY_TYPE_ID, CHILD_ENTRY_TYPE_ID)
values('1799', '1909');
insert into LOAN_ENTRY_TYPE_LINK(ENTRY_TYPE_ID, CHILD_ENTRY_TYPE_ID)
values('1744', '1909');

insert into LOAN_ENTRY_TYPE_LINK(ENTRY_TYPE_ID, CHILD_ENTRY_TYPE_ID)
values('1744', '1903');


------RO78
insert into LOAN_ENTRY_TYPE_LINK(ENTRY_TYPE_ID, CHILD_ENTRY_TYPE_ID)
values('1544', '1909');

insert into LOAN_ENTRY_TYPE_LINK(ENTRY_TYPE_ID, CHILD_ENTRY_TYPE_ID)
values('1525', '1909');
insert into LOAN_ENTRY_TYPE_LINK(ENTRY_TYPE_ID, CHILD_ENTRY_TYPE_ID)
values('1525', '1904');
