--UPDATE PROPERTY_DEFINITION SET PROPERTY_DESCRIPTION='Description' WHERE PROPERTY_DESCRIPTION LIKE 'Product Description' AND ENTITY_TYPE_DEFINITION_ID=485;

UPDATE ACCOUNT_OWNER SET RESPONSIBILITY_TYPE='17'
WHERE UNIQUE_PARTY_ROLE_ID IN (SELECT AO.UNIQUE_PARTY_ROLE_ID  FROM ACCOUNT A,LOAN_ACCOUNT LA,PARTY_ACCOUNT_ROLE PAR,ACCOUNT_OWNER AO
                                WHERE A.ACCOUNT_ID=LA.ACCOUNT_ID
                                 AND A.ACCOUNT_ID=PAR.ACCOUNT_ID
                                 AND PAR.UNIQUE_PARTY_ROLE_ID=AO.UNIQUE_PARTY_ROLE_ID
                                 AND AO.RESPONSIBILITY_TYPE='9');


UPDATE ACCOUNT_OWNER SET RESPONSIBILITY_TYPE='19'
WHERE UNIQUE_PARTY_ROLE_ID IN (SELECT AO.UNIQUE_PARTY_ROLE_ID    FROM ACCOUNT A,LOAN_ACCOUNT LA,PARTY_ACCOUNT_ROLE PAR,ACCOUNT_OWNER AO
                        WHERE A.ACCOUNT_ID=LA.ACCOUNT_ID AND
                        A.ACCOUNT_ID=PAR.ACCOUNT_ID AND
                        PAR.UNIQUE_PARTY_ROLE_ID=AO.UNIQUE_PARTY_ROLE_ID AND
                        AO.RESPONSIBILITY_TYPE='5');

UPDATE LOAN_ACCOUNT SET ACCRUED_INTEREST=0 WHERE ACCRUED_INTEREST IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY ACCRUED_INTEREST NOT NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY ACCRUED_INTEREST DEFAULT 0;

-- delete loan officers between 8001 and 8084
--delete from ENTITY_TYPE_INSTANCE where ENTITY_TYPE_INSTANCE_ID >=8001 and ENTITY_TYPE_INSTANCE_ID<=8084;
--delete from PROPERTY where ENTITY_TYPE_INSTANCE_ID >=8001 and ENTITY_TYPE_INSTANCE_ID<=8084;
--
--
--Update Property set value = 'java.lang.String:Purchase Cemetery Plots' where value = 'java.lang.String:Purchase Cemetary Plots';
--Update Property set value = 'java.lang.String:Purchase Cemetery Plot' where value = 'java.lang.String:Purchase Cemetary Plot';
--
--
--update property_definition set VALID_VALUES = 'java.lang.Integer:{default={}}' where ENTITY_TYPE_DEFINITION_id = 42002 and property_name like 'Flag';
--
--update ASSOCIATE_DEFINITION set ASSOCIATE_NAME = 'ApartmentDetails', ASSOCIATE_DESCRIPTION = 'Apartment Details' 
--where ENTITY_TYPE_DEFINITION_id = 42001 and ASSOCIATE_NAME like 'FlatsDetails';
--
--INSERT INTO PROPERTY_DEFINITION 
--(PROPERTY_DEFINITION_ID                                          ,ENTITY_TYPE_DEFINITION_ID,PROPERTY_NAME               ,PROPERTY_INDEX,PROPERTY_DESCRIPTION            , VALUE_TYPE_DEFINITION_ID,DESCRIPTION_FIELD,DESCRIPTION_FIELD_OVERRIDEN,DEFAULT_VALUE,DEFAULT_VALUE_OVERRIDEN,VALID_VALUES                                           ,VALID_VALUES_OVERRIDEN,MANDATORY,MANDATORY_OVERRIDEN,HIDDEN,HIDDEN_OVERRIDEN,EDITABLE,EDITABLE_OVERRIDEN,INHERITED,CAN_EDIT_DEFINITION,CAN_DELETE_DEFINITION,CATEGORY_OVERRIDEN,CATEGORY,PRIMARY_OVERRIDEN,PRIMARY) VALUES
--((SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION) ,42003                    ,'AnchoredShoppingCentreType',2             ,'Anchored Shopping Centre Type' ,2                        ,0                ,0                          ,null         ,0                      ,'java.lang.Integer:{default={0=Strip Mall,1=Enclosed}}',0                     ,0        ,0                  ,0     ,0               ,1       ,0                 ,0        ,1                  ,1                    ,0                 ,'u'     ,0                ,0      )
--;
--
--DELETE FROM COLLECTION_ASSOCIATE_VALUES WHERE ASSOCIATE_ID IN (221,223);
--
--DELETE FROM PROPERTY WHERE ENTITY_TYPE_INSTANCE_ID in (337,339);
--
--DELETE FROM COLLECTION_ASSOCIATE WHERE ASSOCIATE_ID in (221,223);
--DELETE FROM ASSOCIATE WHERE ASSOCIATE_ID in (221,223);
--DELETE FROM ENTITY_TYPE_INSTANCE WHERE ENTITY_TYPE_INSTANCE_ID in (337,339);

DELETE FROM POSTING_SEQUENCE WHERE POSTING_SEQUENCE_ID in (337,339);

--UPDATE PROPERTY SET VALUE='java.lang.String:Simple Interest' where entity_type_instance_id = 338 and property_name = 'Description';
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION), 471, 'DateLastPremiumPaid', 6, 'Date Last Premium Paid', 5, 1, 0, NULL, 0, 'com.vsoftcorp.time.Date:{default={}}', 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 'U', 0, 1);
--
--UPDATE PROPERTY_DEFINITION SET VALID_VALUES='java.lang.Integer:{default={1=Hazard Insurance,6=Pvt Mortgage Ins(PMI,7=Flood Insurance,8=Earthquake Insurance,9=Special Insurance,10=Credit Life Insurance,11=A/H-Life Insurance}}' where PROPERTY_DEFINITION_ID='6382';
--
--update ASSOCIATE_DEFINITION set MANDATORY = 1 where associate_name = 'PostingSequence';
--
--update ASSOCIATE_DEFINITION set DEFAULT_INSTANCE = 338, ASSOCIATION_TYPE = 1 where ASSOCIATE_NAME = 'PostingSequence';  
