-- loan account

UPDATE LOAN_ACCOUNT SET CHARGE_OFF_AMOUNT=0 WHERE CHARGE_OFF_AMOUNT IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY CHARGE_OFF_AMOUNT DEFAULT 0;

UPDATE LOAN_ACCOUNT SET PRE_PAID_AMOUNT=0 WHERE PRE_PAID_AMOUNT IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY PRE_PAID_AMOUNT DEFAULT 0;

UPDATE LOAN_ACCOUNT SET SUBSIDY_BALANCE=0 WHERE SUBSIDY_BALANCE IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY SUBSIDY_BALANCE DEFAULT 0;

UPDATE LOAN_ACCOUNT SET CURRENT_MONTH_EARNINGS=0 WHERE CURRENT_MONTH_EARNINGS IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY CURRENT_MONTH_EARNINGS DEFAULT 0;

UPDATE LOAN_ACCOUNT SET PAST_DUE_DEALER_INTEREST=0 WHERE PAST_DUE_DEALER_INTEREST IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY PAST_DUE_DEALER_INTEREST DEFAULT 0;

UPDATE LOAN_ACCOUNT SET PAST_DUE_LINE_COMMIT_FEE=0 WHERE PAST_DUE_LINE_COMMIT_FEE IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY PAST_DUE_LINE_COMMIT_FEE DEFAULT 0;

UPDATE LOAN_ACCOUNT SET DAILY_CHARG1_ACCRUAL=0 WHERE DAILY_CHARG1_ACCRUAL IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY DAILY_CHARG1_ACCRUAL DEFAULT 0;

UPDATE LOAN_ACCOUNT SET DAILY_CHARG2_ACCRUAL=0 WHERE DAILY_CHARG2_ACCRUAL IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY DAILY_CHARG2_ACCRUAL DEFAULT 0;

UPDATE LOAN_ACCOUNT SET DAILY_UNUSED_LINE_COMMIT_FEE=0 WHERE DAILY_UNUSED_LINE_COMMIT_FEE IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY DAILY_UNUSED_LINE_COMMIT_FEE DEFAULT 0;

UPDATE LOAN_ACCOUNT SET LAST_STATEMENT_BAL=0 WHERE LAST_STATEMENT_BAL IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY LAST_STATEMENT_BAL DEFAULT 0;

UPDATE LOAN_ACCOUNT SET PRE_STATEMENT_BAL=0 WHERE PRE_STATEMENT_BAL IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY PRE_STATEMENT_BAL DEFAULT 0;

UPDATE LOAN_ACCOUNT SET UNAPPLIED_FUNDS=0 WHERE UNAPPLIED_FUNDS IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY UNAPPLIED_FUNDS DEFAULT 0;

UPDATE LOAN_ACCOUNT SET PAST_PRINCIPLE_DUE=0 WHERE PAST_PRINCIPLE_DUE IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY PAST_PRINCIPLE_DUE DEFAULT 0;

UPDATE LOAN_ACCOUNT SET PRINCIPAL_DUE=0 WHERE PRINCIPAL_DUE IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY PRINCIPAL_DUE DEFAULT 0;

UPDATE LOAN_ACCOUNT SET PAST_DUE_CHARGE1_AMT=0 WHERE PAST_DUE_CHARGE1_AMT IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY PAST_DUE_CHARGE1_AMT DEFAULT 0;

UPDATE LOAN_ACCOUNT SET PAST_DUE_CHARGE2_AMT=0 WHERE PAST_DUE_CHARGE2_AMT IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY PAST_DUE_CHARGE2_AMT DEFAULT 0;

UPDATE LOAN_ACCOUNT SET PAST_DUE_UNUSEDLINE_COMMIT_FEE=0 WHERE PAST_DUE_UNUSEDLINE_COMMIT_FEE IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY PAST_DUE_UNUSEDLINE_COMMIT_FEE DEFAULT 0;

UPDATE LOAN_ACCOUNT SET ACCRUED_CHARGE1_AMT=0 WHERE ACCRUED_CHARGE1_AMT IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY ACCRUED_CHARGE1_AMT DEFAULT 0;

UPDATE LOAN_ACCOUNT SET ACCRUED_CHARGE2_AMT=0 WHERE ACCRUED_CHARGE2_AMT IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY ACCRUED_CHARGE2_AMT DEFAULT 0;

UPDATE LOAN_ACCOUNT SET ACCRUED_UNUSED_LCF=0 WHERE ACCRUED_UNUSED_LCF IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY ACCRUED_UNUSED_LCF DEFAULT 0;

UPDATE LOAN_ACCOUNT SET TAXES_PAID_YTD=0 WHERE TAXES_PAID_YTD IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY TAXES_PAID_YTD DEFAULT 0;

UPDATE LOAN_ACCOUNT SET INTEREST_PAST_DUE=0 WHERE INTEREST_PAST_DUE IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY INTEREST_PAST_DUE DEFAULT 0;

UPDATE LOAN_ACCOUNT SET ACCRUED_INTEREST=0 WHERE ACCRUED_INTEREST IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY ACCRUED_INTEREST DEFAULT 0;

UPDATE LOAN_ACCOUNT SET INTEREST_PAID_LTD=0 WHERE INTEREST_PAID_LTD IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY INTEREST_PAID_LTD DEFAULT 0;

UPDATE LOAN_ACCOUNT SET INTEREST_PAID_YTD=0 WHERE INTEREST_PAID_YTD IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY INTEREST_PAID_YTD DEFAULT 0;

UPDATE LOAN_ACCOUNT SET INTEREST_PAID_MTD=0 WHERE INTEREST_PAID_MTD IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY INTEREST_PAID_MTD DEFAULT 0;

UPDATE LOAN_ACCOUNT SET LAST_ADDL_PRINCIPAL_AMOUNT=0 WHERE LAST_ADDL_PRINCIPAL_AMOUNT IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY LAST_ADDL_PRINCIPAL_AMOUNT DEFAULT 0;

UPDATE LOAN_ACCOUNT SET OTHER_FEES_DUE=0 WHERE OTHER_FEES_DUE IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY OTHER_FEES_DUE DEFAULT 0;

UPDATE LOAN_ACCOUNT SET LATE_FEES_DUE=0 WHERE LATE_FEES_DUE IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY LATE_FEES_DUE DEFAULT 0;

UPDATE LOAN_ACCOUNT SET LATE_FEES_PAID_LTD=0 WHERE LATE_FEES_PAID_LTD IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY LATE_FEES_PAID_LTD DEFAULT 0;

UPDATE LOAN_ACCOUNT SET AMT_LC_WAIVED=0 WHERE AMT_LC_WAIVED IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY AMT_LC_WAIVED DEFAULT 0;

UPDATE LOAN_ACCOUNT SET LATE_FEES_PAID_YTD=0 WHERE LATE_FEES_PAID_YTD IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY LATE_FEES_PAID_YTD DEFAULT 0;

UPDATE LOAN_ACCOUNT SET ACCRUED_INTEREST_NET=0 WHERE ACCRUED_INTEREST_NET IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY ACCRUED_INTEREST_NET DEFAULT 0;

UPDATE LOAN_ACCOUNT SET LAST_CURT_AMOUNT=0 WHERE LAST_CURT_AMOUNT IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY LAST_CURT_AMOUNT DEFAULT 0;

UPDATE LOAN_ACCOUNT SET PAST_DUE_AMOUNT=0 WHERE PAST_DUE_AMOUNT IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY PAST_DUE_AMOUNT DEFAULT 0;

UPDATE LOAN_ACCOUNT SET AMORTIZED_BALANCE=0 WHERE AMORTIZED_BALANCE IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY AMORTIZED_BALANCE DEFAULT 0;

UPDATE LOAN_ACCOUNT SET ACCRUED_INTEREST_LTD=0 WHERE ACCRUED_INTEREST_LTD IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY ACCRUED_INTEREST_LTD DEFAULT 0;

UPDATE LOAN_ACCOUNT SET DAY_BANK_EARNED_AMOUNT=0 WHERE DAY_BANK_EARNED_AMOUNT IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY DAY_BANK_EARNED_AMOUNT DEFAULT 0;

UPDATE LOAN_ACCOUNT SET AVERAGE_BALANCE_LIFE=0 WHERE AVERAGE_BALANCE_LIFE IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY AVERAGE_BALANCE_LIFE DEFAULT 0;

UPDATE LOAN_ACCOUNT SET PARTIAL_PAYMENT=0 WHERE PARTIAL_PAYMENT IS NULL;
ALTER TABLE LOAN_ACCOUNT MODIFY PARTIAL_PAYMENT DEFAULT 0;

-- billing bucket

UPDATE BILLING_BUCKET SET BILLED_PRINCIPAL=0 WHERE BILLED_PRINCIPAL IS NULL;
ALTER TABLE BILLING_BUCKET MODIFY BILLED_PRINCIPAL DEFAULT 0;

UPDATE BILLING_BUCKET SET BILLED_INTEREST=0 WHERE BILLED_INTEREST IS NULL;
ALTER TABLE BILLING_BUCKET MODIFY BILLED_INTEREST DEFAULT 0;

UPDATE BILLING_BUCKET SET BILLED_ESCROW=0 WHERE BILLED_ESCROW IS NULL;
ALTER TABLE BILLING_BUCKET MODIFY BILLED_ESCROW DEFAULT 0;

UPDATE BILLING_BUCKET SET BILLED_LATE_CHARGES=0 WHERE BILLED_LATE_CHARGES IS NULL;
ALTER TABLE BILLING_BUCKET MODIFY BILLED_LATE_CHARGES DEFAULT 0;

UPDATE BILLING_BUCKET SET BILLED_OTHER_FEES=0 WHERE BILLED_OTHER_FEES IS NULL;
ALTER TABLE BILLING_BUCKET MODIFY BILLED_OTHER_FEES DEFAULT 0;

UPDATE BILLING_BUCKET SET BILLED_NONESCROW=0 WHERE BILLED_NONESCROW IS NULL;
ALTER TABLE BILLING_BUCKET MODIFY BILLED_NONESCROW DEFAULT 0;

UPDATE BILLING_BUCKET SET PAID_PRINCIPAL=0 WHERE PAID_PRINCIPAL IS NULL;
ALTER TABLE BILLING_BUCKET MODIFY PAID_PRINCIPAL DEFAULT 0;

UPDATE BILLING_BUCKET SET PAID_ESCROW=0 WHERE PAID_ESCROW IS NULL;
ALTER TABLE BILLING_BUCKET MODIFY PAID_ESCROW DEFAULT 0;

UPDATE BILLING_BUCKET SET PAID_INTEREST=0 WHERE PAID_INTEREST IS NULL;
ALTER TABLE BILLING_BUCKET MODIFY PAID_INTEREST DEFAULT 0;

UPDATE BILLING_BUCKET SET PAID_AH_LIFE=0 WHERE PAID_AH_LIFE IS NULL;
ALTER TABLE BILLING_BUCKET MODIFY PAID_AH_LIFE DEFAULT 0;

UPDATE BILLING_BUCKET SET BILLED_DEALER_INTEREST=0 WHERE BILLED_DEALER_INTEREST IS NULL;
ALTER TABLE BILLING_BUCKET MODIFY BILLED_DEALER_INTEREST DEFAULT 0;

UPDATE BILLING_BUCKET SET PAID_DEALER_INTEREST=0 WHERE PAID_DEALER_INTEREST IS NULL;
ALTER TABLE BILLING_BUCKET MODIFY PAID_DEALER_INTEREST DEFAULT 0;

-- delinquent billing bucket

ALTER TABLE DELQ_BILLING_BUCKET_NEW DROP COLUMN BILLED_PRINCIPAL;
ALTER TABLE DELQ_BILLING_BUCKET_NEW ADD(PAST_DUE_PRINCIPAL NUMBER(20,5));

UPDATE DELQ_BILLING_BUCKET_NEW SET PAST_DUE_PRINCIPAL=0 WHERE PAST_DUE_PRINCIPAL IS NULL;
ALTER TABLE DELQ_BILLING_BUCKET_NEW MODIFY PAST_DUE_PRINCIPAL DEFAULT 0;

ALTER TABLE DELQ_BILLING_BUCKET_NEW DROP COLUMN BILLED_INTEREST;
ALTER TABLE DELQ_BILLING_BUCKET_NEW ADD(PAST_DUE_INTEREST NUMBER(20,5));

UPDATE DELQ_BILLING_BUCKET_NEW SET PAST_DUE_INTEREST=0 WHERE PAST_DUE_INTEREST IS NULL;
ALTER TABLE DELQ_BILLING_BUCKET_NEW MODIFY PAST_DUE_INTEREST DEFAULT 0;

ALTER TABLE DELQ_BILLING_BUCKET_NEW DROP COLUMN BILLED_ESCROW;
ALTER TABLE DELQ_BILLING_BUCKET_NEW ADD(PAST_DUE_ESCROW NUMBER(20,5));

UPDATE DELQ_BILLING_BUCKET_NEW SET PAST_DUE_ESCROW=0 WHERE PAST_DUE_ESCROW IS NULL;
ALTER TABLE DELQ_BILLING_BUCKET_NEW MODIFY PAST_DUE_ESCROW DEFAULT 0;


ALTER TABLE DELQ_BILLING_BUCKET_NEW DROP COLUMN NON_ESCROW_DUE;
ALTER TABLE DELQ_BILLING_BUCKET_NEW ADD(PAST_NON_ESCROW_DUE NUMBER(20,5));

UPDATE DELQ_BILLING_BUCKET_NEW SET PAST_NON_ESCROW_DUE=0 WHERE PAST_NON_ESCROW_DUE IS NULL;
ALTER TABLE DELQ_BILLING_BUCKET_NEW MODIFY PAST_NON_ESCROW_DUE DEFAULT 0;

ALTER TABLE DELQ_BILLING_BUCKET_NEW DROP COLUMN BILLED_DealerInterest;
ALTER TABLE DELQ_BILLING_BUCKET_NEW ADD(PAST_DUE_DEALER_INT NUMBER(20,5));

UPDATE DELQ_BILLING_BUCKET_NEW SET PAST_DUE_DEALER_INT=0 WHERE PAST_DUE_DEALER_INT IS NULL;
ALTER TABLE DELQ_BILLING_BUCKET_NEW MODIFY PAST_DUE_DEALER_INT DEFAULT 0;

UPDATE DELQ_BILLING_BUCKET_NEW SET PAID_PRINCIPAL=0 WHERE PAID_PRINCIPAL IS NULL;
ALTER TABLE DELQ_BILLING_BUCKET_NEW MODIFY PAID_PRINCIPAL DEFAULT 0;

UPDATE DELQ_BILLING_BUCKET_NEW SET PAID_ESCROW=0 WHERE PAID_ESCROW IS NULL;
ALTER TABLE DELQ_BILLING_BUCKET_NEW MODIFY PAID_ESCROW DEFAULT 0;

UPDATE DELQ_BILLING_BUCKET_NEW SET PAID_INTEREST=0 WHERE PAID_INTEREST IS NULL;
ALTER TABLE DELQ_BILLING_BUCKET_NEW MODIFY PAID_INTEREST DEFAULT 0;

UPDATE DELQ_BILLING_BUCKET_NEW SET PAID_AH_LIFE=0 WHERE PAID_AH_LIFE IS NULL;
ALTER TABLE DELQ_BILLING_BUCKET_NEW MODIFY PAID_AH_LIFE DEFAULT 0;

UPDATE DELQ_BILLING_BUCKET_NEW SET PAID_CREDIT_LIFE=0 WHERE PAID_CREDIT_LIFE IS NULL;
ALTER TABLE DELQ_BILLING_BUCKET_NEW MODIFY PAID_CREDIT_LIFE DEFAULT 0;

UPDATE DELQ_BILLING_BUCKET_NEW SET PAID_LATE_FEE=0 WHERE PAID_LATE_FEE IS NULL;
ALTER TABLE DELQ_BILLING_BUCKET_NEW MODIFY PAID_LATE_FEE DEFAULT 0;

UPDATE DELQ_BILLING_BUCKET_NEW SET PAID_OTHER_FEE=0 WHERE PAID_OTHER_FEE IS NULL;
ALTER TABLE DELQ_BILLING_BUCKET_NEW MODIFY PAID_OTHER_FEE DEFAULT 0;

UPDATE DELQ_BILLING_BUCKET_NEW SET PAID_DealerInterest=0 WHERE PAID_DealerInterest IS NULL;
ALTER TABLE DELQ_BILLING_BUCKET_NEW MODIFY PAID_DealerInterest DEFAULT 0;

ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM modify DESCRIPTION VARCHAR2(300);

alter table LOAN_POSTBLE_ACC_HISTORY_ITEM modify DESCRIPTION VARCHAR2(300);

CREATE OR REPLACE VIEW PARTY_VW AS select p.party_id, o.business_name, pe.first_name, pe.last_name, pe.employer_name, p.party_type, p.party_name from party p,person pe,organization o where p.party_id = pe.party_id(+) and p.party_id  = o.party_id (+); 

CREATE OR REPLACE VIEW PARTY_ACCOUNT_ROLE_VW AS SELECT A.ACCOUNT_NO, PV.PARTY_TYPE, PV.PARTY_NAME, PV.BUSINESS_NAME, PV.FIRST_NAME,par.account_id, PV.LAST_NAME, PV.EMPLOYER_NAME, AO.RESPONSIBILITY_TYPE, PR.ROLE_CREATION_DATE, PR.BUSINESS_DATE, PIA.ASSOCIATION_DATE, PIA.RELATIONSHIP_WITH_INSTITUTION, PIA.ASSIGNED_OFFICER,PV.PARTY_ID, PIA.INSTITUTION_ID, PIA.INSTITUTION_ASSOCIATION_ID, PR.UNIQUE_PARTY_ROLE_ID, PR.ROLE_TYPE_ID, PR.UNIQUE_ASSOCIATION_ID FROM PARTY_ROLE PR, PARTY_ACCOUNT_ROLE PAR, PARTY_VW PV, ACCOUNT_OWNER AO, PARTY_INSTITUTION_ASSOCIATION PIA, ACCOUNT A WHERE PR.UNIQUE_PARTY_ROLE_ID = PAR.UNIQUE_PARTY_ROLE_ID AND PAR.UNIQUE_PARTY_ROLE_ID = AO.UNIQUE_PARTY_ROLE_ID AND PIA.PARTY_ID = PV.PARTY_ID AND A.ACCOUNT_ID = PAR.ACCOUNT_ID AND PR.UNIQUE_ASSOCIATION_ID = PIA.UNIQUE_ASSOCIATION_ID;

CREATE OR REPLACE VIEW "INSTITUTION_TEMP_VW" 
AS
SELECT
        I.INSTITUTION_ID,
        I.REGION_NAME INSTITUTIONNAME,
        TAI.PHONE PHONE,
        GA1.LINE_1 INSTITUTIONLINE1,
        GA1.LINE_2 INSTITUTIONLINE2,
        GA1.CITY INSTITUTIONCITYNAME,
        GA1.STATE INSTITUTIONSTATENAME,
        GA1.ZIP_1 INSTITUTIONZIPNAME
FROM
        INSTITUTION I,
        INSTITUTION_ADDRESS GIA,
        INSTITUTION_ADDRESS TIA,
        GEOGRAPHIC_ADDRESS GA1,
        TELECOM_ADDRESS TAI
WHERE
        I.INSTITUTION_ID=GIA.INSTITUTION_ID AND
        I.INSTITUTION_ID=TIA.INSTITUTION_ID AND
        GIA.ADDRESS_ID=GA1.ADDRESS_ID AND
        TIA.ADDRESS_ID=TAI.ADDRESS_ID;

CREATE OR REPLACE VIEW "PARTY_INFORMATION_TEMP_VW" 
AS
SELECT 
    pi.INSTITUTION_ASSOCIATION_ID,
    PA.ACCOUNT_ID,
	PE.FIRST_NAME BORROWERFIRSTNAME,
	PE.LAST_NAME BORROWERLASTNAME,
	PE.MIDDLE_NAME BORROWERMIDDLENAME,
	PE.PREFIX BORROWERPREFIX,
    PAR.PARTY_ID,
	GA2.LINE_1 PERSONADDRESSLINE1,
	GA2.LINE_2 PERSONADDRESSLINE2,
	GA2.CITY PERSONCITY,
	GA2.STATE PERSONSTATE,
	GA2.ZIP_1 PERSONADDRESSZIPCODE ,
    ao.responsibility_type,
    HP.PHONE HOMEPHONE,
    BP.PHONE BUSINESSPHONE 
FROM
	PARTY_ACCOUNT_ROLE PA,
	PARTY_ROLE PR,
	PARTY_INSTITUTION_ASSOCIATION PI,
    PARTY PAR,
	PERSON PE,
    PARTY_ADDRESS PAB,
    PARTY_ADDRESS PAH,
    TELECOM_ADDRESS HP,
    TELECOM_ADDRESS BP,
	ACCOUNT_OWNER AO,
	GEOGRAPHIC_ADDRESS GA2,
	PARTY_ADDRESS PS ,LOAN_ACCOUNT LA
WHERE
	PA.UNIQUE_PARTY_ROLE_ID=PR.UNIQUE_PARTY_ROLE_ID AND
	PR.UNIQUE_ASSOCIATION_ID=PI.UNIQUE_ASSOCIATION_ID(+) AND
	PI.PARTY_ID=PAR.PARTY_ID(+) AND
    PAR.PARTY_ID=PE.PARTY_ID(+) AND
	PA.UNIQUE_PARTY_ROLE_ID=AO.UNIQUE_PARTY_ROLE_ID AND
	PAR.PARTY_ID=PS.PARTY_ID(+) AND
	PS.ADDRESS_ID=GA2.ADDRESS_ID(+) AND
	PS.ADDRESS_USE(+)='HOME' AND
    PAR.PARTY_ID=PAB.PARTY_ID(+) AND
    PAR.PARTY_ID=PAH.PARTY_ID(+) AND
    PAB.ADDRESS_ID=BP.ADDRESS_ID(+) AND
    PAB.ADDRESS_USE(+)='WORK_PHONE' AND
    PAH.ADDRESS_ID=HP.ADDRESS_ID(+) AND
    PAH.ADDRESS_USE(+)='HOME_PHONE' AND
    PA.ACCOUNT_ID=LA.ACCOUNT_ID;

INSERT INTO LOAN_ACCOUNT_HISTORY_ITEM 
(TRANSACTION_ID,ACCOUNT_ID,POST_DATE,EFFECTIVE_DATE,ENTRY_DATE,AMOUNT,DESCRIPTION,TRAN_CODE) 
SELECT LAT.TRANSACTION_ID,LAT.ACCOUNT_ID,LAT.POSTING_DATE,LAT.EFFECTIVE_DATE,LAT.POSTING_DATE,LAT.AMOUNT,LAT.TRANSACTION_DESCRIPTION,LAT.TRANS_CODE
 FROM ACCOUNT A,LOAN_ACCOUNT LA,LOAN_ACCOUNT_TRANSACTION LAT WHERE
A.ACCOUNT_ID=LA.ACCOUNT_ID AND LA.ACCOUNT_ID=LAT.ACCOUNT_ID AND A.ACCOUNT_TYPE_ID='207';

update loan_account_history_item set IS_REVERSABLE = '1'  where IS_REVERSABLE is null;

UPDATE LOAN_ACCOUNT SET PAY_OUT_CODE=0 WHERE PAY_OUT_CODE IS NULL;

UPDATE LOAN_ACCOUNT SET PAYMENTS_MADE=0 WHERE PAYMENTS_MADE IS NULL;

UPDATE LOAN_ACCOUNT SET NO_RETURNED_CHECKS=0 WHERE NO_RETURNED_CHECKS IS NULL;

delete from LOAN_OFFICER where OFFICER_ID in(6661,6662,6663,6664,6665,6666,6667,6668);

--delete  from ENTITY_TYPE_INSTANCE where ENTITY_TYPE_INSTANCE_ID in (6661,6662,6663,6664,6665,6666,6667,6668);
--delete  from PROPERTY where ENTITY_TYPE_INSTANCE_ID in (6661,6662,6663,6664,6665,6666,6667,6668);

DROP SEQUENCE ENTITYTYPEINSTID_SEQ;
CREATE SEQUENCE ENTITYTYPEINSTID_SEQ
    INCREMENT BY 1
    START WITH 10000
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    CACHE 20
    NOORDER;


--update LOAN_LEDGER_POSTING_PARAMETERS set AFFECTS_DATE_CLOSED =0, AFFECTS_LOAN_STATUS =0, AFFECTS_PAYOUT_CODE=0
-- where UNIQUE_ID in (1725, 11101, 1525, 1728);
--
--update LOAN_LEDGER_POSTING_PARAMETERS set AFFECTS_DATE_CLOSED =0, AFFECTS_LOAN_STATUS =0, AFFECTS_PAYOUT_CODE=0
-- where UNIQUE_ID in (1725, 11101, 1525, 1728);

delete from ENTRY_TYPE where UNIQUE_ID=1302;
delete from loan_ENTRY_TYPE where UNIQUE_ID=1302;
delete from LOAN_ENTRY_TYPE_LINK where ENTRY_TYPE_ID=1302;
delete  from DISTRIBUTION_RULE where DISTRIBUTION_RULE_ID=302;
delete  from  PERCENTAGE_DISTRIBUTION_RULE where DISTRIBUTION_RULE_ID=302;
--delete from LOAN_LEDGER_POSTING_PARAMETERS where UNIQUE_ID=1302;
