
-------------- deleting existing entries
DELETE FROM LOAN_ENTRY_TYPE WHERE UNIQUE_ID=1518;


INSERT INTO EVENT_TYPE (EVENT_TYPE_ID,EVENT_TYPE_NAME,EVENT_TYPE_GROUP_ID) 
VALUES ('31','Regular Payment Reversal','REVERSAL');

INSERT INTO EVENT_TYPE (EVENT_TYPE_ID,EVENT_TYPE_NAME,EVENT_TYPE_GROUP_ID) 
VALUES ('26','Late Charge Payment Reversal','REVERSAL');


-------------------------Entry_TYPE

----518
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES((select max(UNIQUE_ID) from ENTRY_TYPE) + 1, (select max(UNIQUE_ID) from ENTRY_TYPE) + 1, null, '2', 0, 'Regular Payment Reversal');

INSERT INTO LOAN_ENTRY_TYPE(UNIQUE_ID, ACCOUNT_TYPE_ID,  TRAN_TYPE_GROUP_ID, EVENT_TYPE_ID,   IS_MONETARY)
VALUES((select max(UNIQUE_ID) from ENTRY_TYPE), '207',  'REVERSAL', '31', 0);


----718
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES((select max(UNIQUE_ID) from ENTRY_TYPE) + 1, (select max(UNIQUE_ID) from ENTRY_TYPE) + 1,  null, '2', 0, 'Regular Payment Reversal');
----718
INSERT INTO LOAN_ENTRY_TYPE(UNIQUE_ID, ACCOUNT_TYPE_ID,  TRAN_TYPE_GROUP_ID, EVENT_TYPE_ID,   IS_MONETARY)
VALUES((select max(UNIQUE_ID) from ENTRY_TYPE), '208',  'REVERSAL', '31', 0);

--522
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES((select max(UNIQUE_ID) from ENTRY_TYPE) + 1, (select max(UNIQUE_ID) from ENTRY_TYPE) + 1,  null, '2', 0, 'Late Charge Payment Reversal');
--522
INSERT INTO LOAN_ENTRY_TYPE(UNIQUE_ID, ACCOUNT_TYPE_ID,  TRAN_TYPE_GROUP_ID, EVENT_TYPE_ID,   IS_MONETARY)
VALUES((select max(UNIQUE_ID) from ENTRY_TYPE), '207',  'REVERSAL', '26', 0);

--722
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES((select max(UNIQUE_ID) from ENTRY_TYPE) + 1, (select max(UNIQUE_ID) from ENTRY_TYPE) + 1, null, '2', 0, 'Late Charge Payment Reversal');
--722
INSERT INTO LOAN_ENTRY_TYPE(UNIQUE_ID, ACCOUNT_TYPE_ID,  TRAN_TYPE_GROUP_ID, EVENT_TYPE_ID,   IS_MONETARY)
VALUES((select max(UNIQUE_ID) from ENTRY_TYPE), '208',  'REVERSAL', '26', 0);


delete from ENTRY_TYPE where UNIQUE_ID='1512';
delete from LOAN_ENTRY_TYPE where UNIQUE_ID='1512';
delete from LOAN_ENTRY_TYPE_LINK where ENTRY_TYPE_ID='1512';
--delete from LOAN_LEDGER_POSTING_PARAMETERS where  UNIQUE_ID='1512';

ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD (STMT_DESC VARCHAR(200));


INSERT INTO LOAN_ENTRY_TYPE_LINK VALUES(40410,1801);
INSERT INTO LOAN_ENTRY_TYPE_LINK VALUES (40410,1802);

INSERT INTO LOAN_ENTRY_TYPE_LINK VALUES(40411,1801);
INSERT INTO LOAN_ENTRY_TYPE_LINK VALUES (40411,1802);

INSERT INTO LOAN_ENTRY_TYPE_LINK VALUES(40412,1801);
INSERT INTO LOAN_ENTRY_TYPE_LINK VALUES (40412,1802);

INSERT INTO LOAN_ENTRY_TYPE_LINK VALUES(40413,1801);
INSERT INTO LOAN_ENTRY_TYPE_LINK VALUES (40413,1802);

UPDATE ACCOUNT_OWNER SET RESPONSIBILITY_TYPE='9'
WHERE UNIQUE_PARTY_ROLE_ID IN (SELECT AO.UNIQUE_PARTY_ROLE_ID  FROM ACCOUNT A,LOAN_ACCOUNT LA,PARTY_ACCOUNT_ROLE PAR,ACCOUNT_OWNER AO
                                WHERE A.ACCOUNT_ID=LA.ACCOUNT_ID
                                 AND A.ACCOUNT_ID=PAR.ACCOUNT_ID
                                 AND PAR.UNIQUE_PARTY_ROLE_ID=AO.UNIQUE_PARTY_ROLE_ID
                                 AND AO.RESPONSIBILITY_TYPE='17');


UPDATE ACCOUNT_OWNER SET RESPONSIBILITY_TYPE='5'
WHERE UNIQUE_PARTY_ROLE_ID IN (SELECT AO.UNIQUE_PARTY_ROLE_ID    FROM ACCOUNT A,LOAN_ACCOUNT LA,PARTY_ACCOUNT_ROLE PAR,ACCOUNT_OWNER AO
                        WHERE A.ACCOUNT_ID=LA.ACCOUNT_ID AND
                        A.ACCOUNT_ID=PAR.ACCOUNT_ID AND
                        PAR.UNIQUE_PARTY_ROLE_ID=AO.UNIQUE_PARTY_ROLE_ID AND
                        AO.RESPONSIBILITY_TYPE='19');

update ENTRY_TYPE set DESCRIPTION='LateCharge' where DESCRIPTION='Late Charge';
update ENTRY_TYPE set DESCRIPTION='OtherFees' where DESCRIPTION='Other Fees';
update ENTRY_TYPE set DESCRIPTION='AccidentalHealthLife' where DESCRIPTION='Accidental Health Life';

update ENTRY_TYPE set DESCRIPTION='Late Charge' where DESCRIPTION='LateCharge';
update ENTRY_TYPE set DESCRIPTION='Other Fees' where DESCRIPTION='OtherFees';
update ENTRY_TYPE set DESCRIPTION='Accidental Health Life' where DESCRIPTION='AccidentalHealthLife';

--delete

delete from LOAN_ENTRY_TYPE_LINK where ENTRY_TYPE_ID in (40410,40411,40412,40413);

update LOAN_ACCOUNT set CONTRACT_ID = null;

--delete from UNIQUE_ASSOCIATE where ASSOCIATE_ID in (select associate_id from associate where ENTITY_TYPE_INSTANCE_ID >= 7020);
--delete from ASSOCIATE where ENTITY_TYPE_INSTANCE_ID >= 7020;
--delete from PROPERTY where ENTITY_TYPE_INSTANCE_ID >=7020;
--delete from ENTITY_TYPE_INSTANCE where ENTITY_TYPE_INSTANCE_ID >= 7020;

-- added for statements 
CREATE OR REPLACE VIEW LOAN_ACCOUNT_HISTORY_ITEM_VW AS SELECT * FROM LOAN_ACCOUNT_HISTORY_ITEM;












