UPDATE PARTY_ROLE SET ROLE_TYPE_ID=13 WHERE UNIQUE_PARTY_ROLE_ID IN(
SELECT UNIQUE_PARTY_ROLE_ID FROM ACCOUNT_OWNER WHERE RESPONSIBILITY_TYPE=17);

UPDATE PARTY_ROLE SET ROLE_TYPE_ID=14 WHERE UNIQUE_PARTY_ROLE_ID IN(
SELECT UNIQUE_PARTY_ROLE_ID FROM ACCOUNT_OWNER WHERE RESPONSIBILITY_TYPE=19);