UPDATE RESPONSIBILITY_TYPE_LOOKUP SET ENABLED=1,ACCOUNT_CATEGORY=2 WHERE ID IN (21,19,18,17,22,2,4);

UPDATE RESPONSIBILITY_TYPE_LOOKUP SET DESCRIPTION='CO_BORROWER' WHERE ID=19;

UPDATE PROPERTY_DEFINITION SET DEFAULT_VALUE='com.vsoftcorp.common.InterestRate:0.0#YEAR:1' WHERE
PROPERTY_NAME LIKE 'LoanProductInterestRate' AND VALUE_TYPE_DEFINITION_ID=10;
 
UPDATE PROPERTY_DEFINITION  SET DEFAULT_VALUE='java.lang.Integer:1' WHERE PROPERTY_NAME LIKE 'PastdueHistoryRecordDay';
 
ALTER TABLE Loan_Terms MODIFY PRODUCT_DESCRIPTION varchar2(100);

ALTER TABLE PARTY MODIFY RELATIONSHIP_OFFICER varchar2(100); 

ALTER TABLE INSTITUTION ADD  EXCESS_ESCROW_OTHER_CHARGE NUMBER(1) DEFAULT 0 ;
ALTER TABLE INSTITUTION ADD  EXCESS_ESCROW_LATE_CHARGE NUMBER(1) DEFAULT 0;
ALTER TABLE INSTITUTION ADD  EXCESS_ESCROW_PAST_DUE NUMBER(1) DEFAULT 0;