CREATE TABLE RELEASE_DOCUMENT (
    ID                      	NUMBER(10) PRIMARY KEY,
    DATE_CREATED                DATE,
    CREATED_BY                  VARCHAR2(10), 
    ACCOUNT_NUMBER          	VARCHAR2(10),
    CUSTOMER_NAME              	VARCHAR2(40),
    BENEFICIARY_NAME        	VARCHAR2(40),
    LEGAL_DESCRIPTION        	VARCHAR2(250),
    ZIP    		                VARCHAR2(10),
    RECORDED_DATE               DATE,
    INSTITUTION 		        VARCHAR2(100));
  	
CREATE SEQUENCE RELEASE_DOCUMENT_ID_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOMINVALUE NOCYCLE ORDER;