CREATE TABLE "ESCROW_DISBURSEMENT_HISTORY" (

 	"ID"                           NUMBER(10) PRIMARY KEY,
    "ACCOUNT_NUMBER"               VARCHAR2(20),
    "CUSTOMER_NAME"                VARCHAR2(70), 
    "AGENCY_CODE"         		   VARCHAR2(30),
    "CREATED_BY"                  VARCHAR2(20),
    "DISBURSEMENT_AMOUNT"			NUMBER(20,2),
    "AGENCY_NAME"					VARCHAR2(50),
    "DISBURSEMENT_MODE"				VARCHAR2(20),
    "CHECK_NUMBER" 					VARCHAR2(20),
    "ESCROW_DISB_DATE"				DATE,
    "CREATED_DATE"					DATE);
    
CREATE SEQUENCE "ESCROW_DISB_HIST_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOMINVALUE NOCYCLE ORDER;