
UPDATE PAYMENT_ACCOUNT SET EXTRACT_TRANSCATION_TYPE=0 WHERE NATURE_OF_PAYMENT=0;
UPDATE PAYMENT_ACCOUNT SET EXTRACT_TRANSCATION_TYPE=2 WHERE NATURE_OF_PAYMENT in (1,2,3,4,6,7,8,9,10);
UPDATE PAYMENT_ACCOUNT SET EXTRACT_TRANSCATION_TYPE=3 WHERE NATURE_OF_PAYMENT in (5);