
CREATE TABLE CHARGEOFF_RECOVERY_ACCOUNT (
ACCOUNT_ID VARCHAR2(30),
RECOVERY_ACCOUNT_NO VARCHAR2(30),
INSTITUTION_ID VARCHAR2(30),
NOTICE_SIGNATORY_NAME VARCHAR2(500),
NOTICE_SIGNATORY_DESIGNATION VARCHAR2(100)
);

ALTER TABLE CHARGEOFF_RECOVERY_ACCOUNT
ADD CONSTRAINT CHARGEOFF_RECOVERY_ACCT_ID_PK PRIMARY KEY(ACCOUNT_ID);

ALTER TABLE CHARGEOFF_RECOVERY_ACCOUNT ADD ( CONSTRAINT CHARGEOFF_RECOVERY_ACCT_ID_FK
	FOREIGN KEY(ACCOUNT_ID)
	REFERENCES ACCOUNT(ACCOUNT_ID));
	
alter table account add (VERSION_NO number default 0);

alter table transaction_posttoday add(ORIGIN_INSTITUTION_ID varchar2(30));


ALTER TABLE AUTOMATIC_TRANSFER_INSTRUCTION
	ADD (  LAST_PROCESSED_DATE DATE ) ;



CREATE	OR REPLACE	VIEW "AUTOMATIC_TRANSFER_VW" AS 
SELECT
	AUTO_TRANS_UNIQUE_ID,
	SOURCE_ACCOUNT,
	SOURCE.ACCOUNT_NO SOURCE_ACC_NO,
	SOURCE.INSTITUTION_ID SOURCE_INST_NO,
	SOURCE.ACCOUNT_TYPE_ID SOURCE_ACC_TYPE_ID,
	TARGET_ACCOUNT,
	TARGET.ACCOUNT_NO TARGET_ACC_NO,
	TARGET.INSTITUTION_ID TARGET_INST_NO,
	TARGET.ACCOUNT_TYPE_ID TARGET_ACC_TYPE_ID,
	TRANSFER_MONEY,
	case when instr(TRANSFER_FREQUENCY,'#')=0 then TRANSFER_FREQUENCY 
	else  substr(TRANSFER_FREQUENCY,0,instr(TRANSFER_FREQUENCY,'#')-1) end TRANSFER_FREQUENCY,
	NUMBER_OF_TRANSFERS,
	START_DATE,
	END_DATE,
	AUTOMATIC_TRANSFER,
	IS_VARIABLE_AMOUNT,
    IS_ACTIVE,
    AT.LAST_PROCESSED_DATE
FROM
	AUTOMATIC_TRANSFER_INSTRUCTION AT,
	ACCOUNT SOURCE,
	ACCOUNT TARGET 
WHERE
	AT.SOURCE_ACCOUNT=SOURCE.ACCOUNT_ID AND
	AT.TARGET_ACCOUNT=TARGET.ACCOUNT_ID;

ALTER TABLE TRANSACTION_POSTTODAY ADD ( REVERSAL_DATE DATE );

--alter table CYCLE_GROUP_ACCTS_CONFIG drop constraint CYC_GR_ACCT_AID_UK;
--DROP INDEX CYC_GR_ACCT_AID_UK;

alter table CYCLE_GROUP_ACCTS_CONFIG drop constraint CYC_GR_ACCT_AID_UK drop index;

alter table TRANSACTION_POSTTODAY add ( TERMINAL_IDENTIFICATION_CODE varchar2(6) );
alter table TRANSACTION_POSTTODAY add ( TERMINAL_LOCATION varchar2(27) );
alter table TRANSACTION_POSTTODAY add ( TERMINAL_CITY varchar2(15) );
alter table TRANSACTION_POSTTODAY add ( TERMINAL_STATE varchar2(2) );

alter table ACCOUNT_HISTORY_ITEM add ( ACH_STANDARD_ENTRY_CLASS_CODE varchar2(15));
alter table ACCOUNT_HISTORY_ITEM add ( TERMINAL_IDENTIFICATION_CODE varchar2(6) );
alter table ACCOUNT_HISTORY_ITEM add ( TERMINAL_LOCATION varchar2(27) );
alter table ACCOUNT_HISTORY_ITEM add ( TERMINAL_CITY varchar2(15) );
alter table ACCOUNT_HISTORY_ITEM add ( TERMINAL_STATE varchar2(2) );

alter table INSTITUTION add PARENT_ID number(5);
alter table INSTITUTION add PARENT_NAME VARCHAR2(50);
