--indexes ---script added which is removed from previous file(Reconcilation_create_scrips)
create unique index indx01 on RECONCILE_TRANSACTIONS(ID) ;
CREATE INDEX IND_DEBITCARD_SUBSC_1 ON DEBITCARD_SUBSCRIPTION(PRIMARY_USER_ID);
CREATE INDEX IND_DEBITCARD_SUBSC_2 ON DEBITCARD_SUBSCRIPTION(SUBSCRIBER_ID);
CREATE INDEX IND_DEBITCARD_USER ON DEBITCARD_USER(PARTY_ID);