CREATE TABLE RECONCILE_TRANSACTIONS ( 
	ID                    	NUMBER(15,0) NOT NULL,
	STAR_FILE_ID          	NUMBER(15,0) NOT NULL,
	BUSINESS_DATE         	VARCHAR2(4) NOT NULL,
	MSG_TYPE              	VARCHAR2(4) NOT NULL,
	PAN                   	VARCHAR2(19) NULL,
	PROCESSING_CD         	VARCHAR2(6) NULL,
	TRANSACTION_AMOUNT    	NUMBER(12,2) NULL,
	TX_AMOUNT_FEE         	VARCHAR2(9) NULL,
	REPL_TRAN             	NUMBER(12,2) NULL,
	REPL_TRAN_FEE         	VARCHAR2(9) NULL,
	RESPONSE_CD           	VARCHAR2(2) NULL,
	REVERSAL_REASON       	VARCHAR2(4) NULL,
	ACCEPTOR_ID           	VARCHAR2(8) NULL,
	RETRIEVAL_REF         	VARCHAR2(12) NULL,
	LOCAL_TRANSACTION_TIME	VARCHAR2(6) NULL,
	LOCAL_TRANSACTION_DATE	VARCHAR2(4) NULL,
	AUTH_AGENT_INST       	VARCHAR2(11) NULL,
	ACQU_INST_ID          	VARCHAR2(11) NULL,
	ISSUER_NW_ID          	VARCHAR2(3) NULL,
	ACQUIRER_NW_ID        	VARCHAR2(3) NULL,
	PROCESSOR_ID          	VARCHAR2(6) NULL,
	PLASTIC_NO            	VARCHAR2(3) NULL,
	NATIONAL_POS          	VARCHAR2(10) NULL,
	TRACE_NUMBER          	VARCHAR2(6) NULL,
	ACQU_COUNTRY          	VARCHAR2(3) NULL,
	CONV_RATE             	VARCHAR2(8) NULL,
	AUTH_ID_RESP          	VARCHAR2(6) NULL,
	CURRENCY_TRAN_CODE    	VARCHAR2(3) NULL,
	CURRENCY_SET_CODE     	VARCHAR2(3) NULL,
	PSEUDO_TERMINAL       	VARCHAR2(6) NULL,
	REIMBURSE_ATT         	VARCHAR2(2) NULL,
	UFB_FEE               	VARCHAR2(7) NULL,
	RECORD_FLAG           	VARCHAR2(1) NULL,
	EXP_BILL_CODE         	VARCHAR2(3) NULL,
	INT_TX_CODE           	VARCHAR2(2) NULL,
	CARD_ACC_NAME         	VARCHAR2(40) NULL,
	MERCHANT_NAME         	VARCHAR2(25) NULL,
	ACQ_ID                	VARCHAR2(2) NULL,
	ISS_ID                	VARCHAR2(2) NULL,
	ACCOUNT_ID1           	VARCHAR2(28) NULL,
	ACCOUNT_ID2           	VARCHAR2(28) NULL,
	ADD_RESP_DATA         	VARCHAR2(15) NULL,
	MATCHED_FLAG          	NUMBER(1,0) NOT NULL,
	BANK_ID               	NUMBER(5,0) NULL 
	);



CREATE TABLE STAR_USER_FILE ( 
	ID       	NUMBER(15,0) NOT NULL,
	FILE_NAME	VARCHAR2(25) NOT NULL,
	STATUS   	VARCHAR2(15) NULL 
	);


CREATE TABLE BANK_RECONCILE_TOTALS ( 
	BANK_ID      	NUMBER(5,0) NULL,
	FILE_ID      	NUMBER(5,0) NULL,
	TOTAL_CREDITS	NUMBER(20,5) NULL,
	TOTAL_DEBITS 	NUMBER(20,5) NULL 
	);

create table matched_rec_Transactions(
transaction_id number,
id number);

--sequences 

CREATE SEQUENCE STAR_FILE_ID START WITH 28095 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE RECONCILE_TX_ID START WITH 52773031 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE RECONCILE_TRAILERTOTALS_ID START WITH 26893 INCREMENT BY 1 NOCACHE NOCYCLE;


