ALTER TABLE PARTY_REGISTERED_IDS MODIFY (OTHER_INFO VARCHAR2(2000));
 
ALTER TABLE  ACH_WARE_HOUSE_ENTRY add  REASON  VARCHAR2(20);

ALTER TABLE DEPOSIT_ACCOUNT ADD  DATE_PREVIOUS_ACTIVITY DATE;

ALTER TABLE DEPOSIT_ACCOUNT ADD  DATE_LAST_KITING_CP DATE;

ALTER TABLE DEPOSIT_ACCOUNT ADD  OLD_KITE_BALANCE NUMBER(20,5);

ALTER TABLE DEPOSIT_ACCOUNT ADD  OLD_KITE_DEBITS VARCHAR2(20);

ALTER TABLE DEPOSIT_ACCOUNT ADD  OLD_KITE_CREDITS  VARCHAR2(20);

CREATE OR REPLACE VIEW DEPOSIT_ACCOUNT_VW AS
select A.ACCOUNT_NO,A.INSTITUTION_ID,A.PRODUCT_ID,A.ACCOUNT_CATEGORY, A.ACCOUNT_TYPE_ID,A.BUSINESS_DATE,
DA.* from ACCOUNT A,DEPOSIT_ACCOUNT DA where A.ACCOUNT_ID=DA.ACCOUNT_ID ;

alter table stop_payment_maintenance modify (OLD_DESCRIPTION VARCHAR2(500),new_DESCRIPTION VARCHAR2(500));

alter table hold_payment_maintenance modify (OLD_DESCRIPTION VARCHAR2(500),new_DESCRIPTION VARCHAR2(500));

alter table DEPOSIT_ACCOUNT add IS_PUBLIC_FUND number(1,0);
  
CREATE OR REPLACE VIEW DEPOSIT_ACCOUNT_VW AS
select A.ACCOUNT_NO,A.INSTITUTION_ID,A.PRODUCT_ID,A.ACCOUNT_CATEGORY, A.ACCOUNT_TYPE_ID,A.BUSINESS_DATE,
DA.* from ACCOUNT A,DEPOSIT_ACCOUNT DA where A.ACCOUNT_ID=DA.ACCOUNT_ID ;

alter table account_history_item add(account_no VARCHAR2(30),ACCOUNT_TYPE_ID VARCHAR2(30),INSTITUTION_ID VARCHAR2(30),
entry_type_id number(15),company_description VARCHAR2(500));

alter table dda_52_temp add(ORG_TRANS_CODE VARCHAR2(50));

ALTER TABLE DEPOSIT_ACCOUNT rename column DATE_LAST_KITING_CP to DATE_LAST_KITING_CURR_PERIOD;

ALTER TABLE DEPOSIT_ACCOUNT ADD (OLD_INTEREST_RATE NUMBER(15,5));

ALTER TABLE DEPOSIT_ACCOUNT ADD (OPENING_BALANCE NUMBER(20,5) ) ;

ALTER TABLE DEPOSIT_ACCOUNT ADD (NO_TIMES_EXCESS_MMA_RPT NUMBER(10));

CREATE OR REPLACE VIEW DEPOSIT_ACCOUNT_VW AS
select A.ACCOUNT_NO,A.INSTITUTION_ID,A.PRODUCT_ID,A.ACCOUNT_CATEGORY, A.ACCOUNT_TYPE_ID,A.BUSINESS_DATE,
DA.* from ACCOUNT A,DEPOSIT_ACCOUNT DA where A.ACCOUNT_ID=DA.ACCOUNT_ID ;


