ALTER TABLE LOAN_ACCOUNT ADD(NEXT_ESCROW_AMOUNT_DUE NUMBER(20,5),PRINCIPLE_BILLING_AMOUNT NUMBER(20,5),
PAST_DUE_DATE DATE,PRINCIPLE_PAST_DUE NUMBER(20,5));

ALTER TABLE ESCROW_HEAD ADD(TAX_ID VARCHAR2(30),PREVIOUS_AMOUNT_DUE NUMBER(20,5),EXPIRY_DATE DATE,AMOUNT_YEAR_TO_DATE NUMBER(20,5));

ALTER TABLE LOAN_ACCOUNT_TRANSACTION ADD(PAYMENT_DUE_DATE DATE);

ALTER TABLE MTG_LAT_TEMP ADD(PAYMENT_DUE_DATE DATE);

CREATE OR REPLACE VIEW LOAN_ACCOUNT_VW AS SELECT A.ACCOUNT_NO,A.INSTITUTION_ID,A.PRODUCT_ID,A.ACCOUNT_CATEGORY, A.ACCOUNT_TYPE_ID,
A.BUSINESS_DATE,A.DATE_OPENED,A.CREATION_DATE,LA.* 
from ACCOUNT A,LOAN_ACCOUNT LA where A.ACCOUNT_ID=LA.ACCOUNT_ID;


ALTER TABLE LOAN_ACCOUNT_TRANSACTION  ADD TRAN_CODE_INDICATOR VARCHAR2(20);

ALTER TABLE LOAN_ACCOUNT_TRANSACTION  ADD INPUT_TYPE_CODE VARCHAR2(20);

ALTER TABLE LOAN_ACCOUNT_TRANSACTION  ADD SERIAL_NUMBER VARCHAR2(20);

ALTER TABLE IL_51_LAT_TEMP  ADD TRAN_CODE_INDICATOR VARCHAR2(20);

ALTER TABLE IL_51_LAT_TEMP  ADD INPUT_TYPE_CODE VARCHAR2(20); 

ALTER TABLE    SIL_LAT_5051_TEMP  ADD   DATE_INT_PAID_TO DATE;

ALTER TABLE    LOAN_ACCOUNT_TRANSACTION    ADD   DATE_INT_PAID_TO DATE;

ALTER TABLE    LOAN_ACCOUNT_TRANSACTION    ADD  BRANCH_NO  VARCHAR2(20);

ALTER TABLE    LOAN_ACCOUNT_TRANSACTION    ADD  PRIN_DUE_DATE  DATE  ;

ALTER TABLE    LOAN_ACCOUNT_TRANSACTION    ADD  INT_DUE_DATE  DATE  ;

ALTER TABLE    LOAN_ACCOUNT_TRANSACTION    ADD  DATE_DEALER_INT_PAID_TO  DATE  ;

ALTER TABLE    LOAN_ACCOUNT_TRANSACTION    ADD  BILLED_PDU_PRIN  VARCHAR2(20) ;

ALTER TABLE    LOAN_ACCOUNT_TRANSACTION    ADD  LATE_CHARGE  VARCHAR2(20) ;

ALTER TABLE    LOAN_ACCOUNT_TRANSACTION    ADD CANCELLATION_FEE VARCHAR2(20) ;

ALTER TABLE    LOAN_ACCOUNT_TRANSACTION    ADD  DEALER_INT  VARCHAR2(20) ;

ALTER TABLE    LOAN_ACCOUNT_TRANSACTION    ADD MEMO_INTEREST  VARCHAR2(20) ;

ALTER TABLE    LOAN_ACCOUNT_TRANSACTION    ADD  MEMO_FEES1  VARCHAR2(20) ;

ALTER TABLE    LOAN_ACCOUNT_TRANSACTION    ADD MEMO_FEES2  VARCHAR2(20) ;

ALTER TABLE    LOAN_ACCOUNT_TRANSACTION    ADD  POSTED VARCHAR2(20) ;


ALTER TABLE    LOAN_ACCOUNT_TRANSACTION    ADD SEQUENCE_NBR  VARCHAR2(20) ;

ALTER TABLE    LOAN_ACCOUNT_TRANSACTION    ADD SERIAL_NBR VARCHAR2(20) ;

ALTER TABLE    LOAN_ACCOUNT_TRANSACTION    ADD  UNUSED_LINE_COMMT_FEE  VARCHAR2(20) ;

ALTER TABLE    LOAN_ACCOUNT_TRANSACTION    ADD  FIELD_INDICATOR VARCHAR2(20) ;

CREATE TABLE IL51_ACC_HIST_TODAY_TEMP ( 
	INSTITUTION_ID 	VARCHAR2(50) NULL,
	ACCOUNT_TYPE_ID	VARCHAR2(50) NULL,
	BRANCH_ID      	VARCHAR2(50) NULL,
	ACCOUNT_NO     	VARCHAR2(50) NULL,
	POST_DATE      	DATE NULL,
	TRANS_CODE     	VARCHAR2(50) NULL,
	AMOUNT         	NUMBER(20,5) NULL,
	EFFECTIVE_DATE 	DATE NULL,
	POST_STATUS    	VARCHAR2(50) NULL,
	TRACE          	VARCHAR2(50) NULL,
	CHEQUE         	VARCHAR2(50) NULL , 
	TRAN_CODE_INDICATOR  VARCHAR2(20),
	INPUT_TYPE_CODE   VARCHAR2(20)
	);

create index il51_account_no  on   IL51_ACC_HIST_TODAY_TEMP( ACCOUNT_NO);

create index il51_inst_id   on   IL51_ACC_HIST_TODAY_TEMP( INSTITUTION_ID);

create index il51_post_date  on   IL51_ACC_HIST_TODAY_TEMP( post_date);

create index il51_trans_code    on   IL51_ACC_HIST_TODAY_TEMP(trans_code);
