CREATE TABLE PAYMENT_DISTRIBUTION
(
PAYMENT_DISTRIBUTION_ID NUMBER(20,0) NOT NULL,
AUTO_TRANS_UNIQUE_ID NUMBER(30,0),
TYPE NUMBER(5,0)
);

CREATE SEQUENCE PAYMENT_DISTRIBUTION_SEQ INCREMENT BY 1 START WITH 1;

CREATE TABLE FIXED_DISTRIBUTION
(
PAYMENT_DISTRIBUTION_ID NUMBER(20,0),
TYPE NUMBER(5,0),
VALUE NUMBER(20,5)
);

CREATE TABLE PERCENTAGE_DISTRIBUTION
(
PAYMENT_DISTRIBUTION_ID NUMBER(20,0),
TYPE NUMBER(5,0),
VALUE NUMBER(20,5)
);

CREATE TABLE TRANSFER_INSTRUCTION
(
AUTO_TRANS_UNIQUE_ID NUMBER(30,0) NOT NULL,
TYPE NUMBER(5,0),
TOTAL_AMOUNT NUMBER(20,5),
FREQUENCY VARCHAR2(100)
);

CREATE TABLE IRA_DISTRIBUTION
(
DISTRIBUTION_ID NUMBER(20,0) NOT NULL,
ACCOUNT_ID VARCHAR2(60),
UNIQUE_PARTY_ROLE_ID NUMBER(15,0),
AUTO_TRANS_UNIQUE_ID NUMBER(30,0),
DATE_OF_DEATH DATE,
PROCEEDS_CODE NUMBER(5,0),
REASON VARCHAR2(20),
FOR_TRANSFER_ONLY VARCHAR2(20),
EXCESS_CONTRIBUTION_ID NUMBER(20,0),
RECIPIENT_IRA_PLAN varchar2(25),
DATE_CREATED DATE,
USER_NAME VARCHAR2(50)
);

Create table EXCESS_CONTRIBUTION
(EXCESS_CONTRIBUTION_ID number(20),
TAX_YEAR varchar2(10),
AMOUNT_EXCESS_CONTRIBUTION number(20,5),
SAME_YEAR number(1,0),
AMOUNT_SAME_YEAR number(20,5),
YEAR_AFTER number(1,0),
AMOUNT_YEAR_AFTER number(20,5),
AFTER_MAY31 number(1,0),
EARNING_ATTRIBUTE number(20,5)
);

CREATE SEQUENCE IRA_EXCESS_CONTRIBUTION_SEQ INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE IRA_DISTRIBUTION_SEQ INCREMENT BY 1 START WITH 1;

CREATE TABLE ACCOUNT_PAYEE
(
UNIQUE_PARTY_ROLE_ID NUMBER(20,0) NOT NULL,
RESPONSIBILITY_TYPE NUMBER(5,0)
);

CREATE SEQUENCE ACCOUNT_PAYEE_SEQ INCREMENT BY 1 START WITH 1;

--New fields from IAT ENTRY DETAIL RECORD

--Number of Addenda Records 	M	Numeric
ALTER TABLE ACH_WARE_HOUSE_ENTRY ADD(NO_OF_ADDENDA_RECORDS NUMBER(4));

-- Gateway Operator OFAC Screening Indicator	O	Alpha Numeric	1
ALTER TABLE ACH_WARE_HOUSE_ENTRY ADD(PRIMARY_OFAC_SCREENING_IND NUMBER(1));

--Secondary OFAC Screening Indicator	O	Alpha Numeric	1
ALTER TABLE ACH_WARE_HOUSE_ENTRY ADD(SECONDARY_OFAC_SCREENING_IND NUMBER(1));

--New fields from IAT BATCH HEADER

--IAT Indicator	O	Alpha Numeric	05-20	16
ALTER TABLE ACH_WARE_HOUSE_ENTRY ADD(IAT_INDICATOR VARCHAR2(16));

--Foreign Exchange Indicator	M	Alpha Numeric	21-22	2
ALTER TABLE ACH_WARE_HOUSE_ENTRY ADD(FOREIGN_EXCHANGE_INDICATOR VARCHAR2(2));

--Foreign Exchange Reference Indicator	R	Numeric	23-23	1
ALTER TABLE ACH_WARE_HOUSE_ENTRY add(FOREIGN_EXCHANGE_REF_IND VARCHAR2(1));

--Foreign Exchange Reference 	R	Alpha Numeric	24-38	15
ALTER TABLE ACH_WARE_HOUSE_ENTRY ADD(FOREIGN_EXCHANGE_REFERENCE VARCHAR2(15));

--ISO Destination Country Code	M	Alpha Numeric	39-40	2
ALTER TABLE ACH_WARE_HOUSE_ENTRY ADD(ISO_DESTINATION_COUNTRY_CODE VARCHAR2(2));

--ISO Origination Currency Code	M	Alpha Numeric	64-66	3
ALTER TABLE ACH_WARE_HOUSE_ENTRY ADD(ISO_ORIGINATION_CURRENCY_CODE VARCHAR2(3));

--ISO Destination Currency Code	M	Alpha Numeric	67-69	3
ALTER TABLE ACH_WARE_HOUSE_ENTRY ADD(ISO_DEST_CURRENCY_CODE VARCHAR2(3));

/*--Originator Status Code M	Alpha Numeric	79-79	1		
--0 - ADV file prepared by an ACH Operator. 
--1 - This code identifies the Originator as a depository financial institution which has agreed to be bound by these -- rules. 2 - This code identifies --the Originator as a federal government entity or agency not subject to theserules. 
**/
ALTER TABLE ACH_WARE_HOUSE_ENTRY ADD(ORIGINATOR_STATUS_CODE  VARCHAR2(1));

--0 No addenda record follows the entry 1 One or more addenda records follow the entry 
ALTER TABLE ACH_WARE_HOUSE_ENTRY ADD(ADDENDA_RECORD_INDICATOR NUMBER(1));

ALTER TABLE ACH_WARE_HOUSE_ENTRY ADD(ORIGINATING_DFI_ID VARCHAR2(10));

ALTER TABLE AUTOMATIC_TRANSFER_INSTRUCTION MODIFY COMMENTS VARCHAR2(100);

alter table deposit_account add (PREV_AMT_CREDITS_CURR_PERIOD number(20,5) default 0);

alter table deposit_account add (PREV_AMT_DEBITS_CURR_PERIOD number(20,5) default 0);

alter table deposit_account add (prev_NO_DEBITS_CURRENT_PERIOD number(10,0) default 0);

alter table deposit_account add (prev_NO_CREDITS_CURRENT_PERIOD number(10,0) default 0);

alter table deposit_account add (PREV_NO_ACH_DEBITS_CURR_PERIOD number(10,0) default 0);

alter table deposit_account add (PREV_NO_TRANSIT_ITEMS number(10,0) default 0);

alter table deposit_account add (PREV_NO_OF_CHECKS number(10,0) default 0);

alter table deposit_account add (PREV_FED_WITHOLD_AMT_CURR_PTD number(20,5) default 0);

alter table deposit_account add (PREV_NO_DEPOSITS_CURR_PERIOD number(10,0) default 0);

alter table deposit_account add (PREV_NO_ATM_DEBITS number(10,0) default 0);

alter table deposit_account add (PREV_SRV_CHRG_ACT_CURR_PERIOD number(20,5) default 0);

alter table deposit_account add (PREV_SRV_CHRG_MAINTCURR_PERIOD number(20,5) default 0);

alter table deposit_account add (PREV_TIMES_OD_CURR_PERIOD number(10,0) default 0);

alter table deposit_account add (PREV_TIMES_NSF_CURR_PERIOD number(10,0) default 0);

alter table deposit_account add (PREV_NO_DAYS_OD_CURR_PERIOD number(10,0) default 0);

alter table deposit_account add (PREV_INTEREST_PAID_PTD VARCHAR2(30) default 0);

alter table deposit_account add (PREV_AGGR_BALANCE_CURR_PERIOD number(20,5) default 0);

alter table deposit_account add (PREV_NO_ENCLOSURE_CURR_PERIOD number(10,0) default 0);

alter table deposit_account add (PREV_TIMES_KITING_CURR_PERIOD number(10,0) default 0);

alter table deposit_account add (PREV_NO_OF_POSTING_DAYS number(10,0) default 0);

ALTER TABLE PRODUCT_TYPE ADD IS_NEW_ACCT_ALLOWED NUMBER(1,0) DEFAULT 1;

ALTER TABLE ACH_CORESOFT_TRANCODE_MAP ADD(RETURNS_TRANCODE NUMBER(5));

ALTER TABLE ACH_CORESOFT_TRANCODE_MAP ADD(UNIQUE_ID NUMBER(5,0));

ALTER TABLE ACH_CORESOFT_TRANCODE_MAP ADD(STANDARD_ENTRY_CLASS_CODE VARCHAR2(10));

alter table account_history_item add DEBITCARD_NO varchar2(19);

ALTER TABLE STOP_PAYMENT_INSTRUCTION ADD SOURCE_TYPE NUMBER(1);

ALTER TABLE STOP_PAYMENT_MAINTENANCE ADD OLD_SOURCE_TYPE NUMBER(1);

ALTER TABLE STOP_PAYMENT_MAINTENANCE ADD NEW_SOURCE_TYPE NUMBER(1);