DELETE FROM APPL_PRODUCT_FORM;

DELETE FROM PRODUCT_FORM_TEMPLATE;

DELETE FROM FORM_TEMPLATE;

ALTER TABLE FORM_TEMPLATE ADD SRC_PDF_NAME VARCHAR2(100);

ALTER TABLE FORM_TEMPLATE ADD SOURCE NUMBER;

ALTER TABLE FORM_TEMPLATE ADD CUST_ACC_LEVEL VARCHAR(50);