ALTER TABLE PRODUCT_TYPE ADD CUSTOMER_TYPE Number(20);

create sequence QUESTION_ID_SEQ start with 53 increment by 1;
-- kiran doubt file
create sequence ANSWER_ID_SEQ start with 137 increment by 1;

alter table PROD_QUES_IDS drop constraint PROD_QUES_IDS_PQID_FK;

ALTER TABLE IRA_DISTRIBUTION_INSTRUCTION  ADD FEDERAL_TAX_AMOUNT VARCHAR2(20);
ALTER TABLE IRA_DISTRIBUTION_INSTRUCTION  ADD STATE_TAX_AMOUNT VARCHAR2(20);

ALTER TABLE IRA_DISTRIBUTION_INSTRUCTION  ADD WITHHELD_STATE VARCHAR2(3);

ALTER TABLE IRA_DISTRIBUTION_INSTRUCTION  ADD TAX_WITHHELD VARCHAR2(2);

ALTER TABLE SAVINGS_PLAN_DIST_TRANSACTIONS ADD STATUS  NUMBER(1);

update SAVINGS_PLAN_DIST_TRANSACTIONS  set status='1' where status is null;

ALTER TABLE SAVINGS_PLAN_CONT_TRANSACTIONS ADD STATUS  NUMBER(1);

update SAVINGS_PLAN_CONT_TRANSACTIONS  set status='1' where status is null;