CREATE or REPLACE VIEW "ACCOUNT_DETAILS_VW"  ("ACCOUNT_ID", "ACCOUNT_NO", "INSTITUTION_ID", "ACCOUNT_TYPE_ID", "LEDGER_BALANCE", "AVAILABLE_BALANCE", "BUSINESS_DATE", "CURRENT_BALANCE", "UNCOLLECTED_BALANCE", "OVERDRAFT_CODE", "CREATION_DATE", "DATE_LAST_MAINTAINED", "RETURNS_LAST_YR", "TIMES_NSF_CURR_PERIOD", "TIMES_NSF_YTD", "TIMES_OD_CURR_PERIOD", "TIMES_OD_YTD", "OVERDRAFT_LIMIT","NO_CHRG_BACK_ITEMS_YR_TO_DATE", "TIMES_OD_PRYR") AS
  (SELECT acc.account_id,de.ACCOUNT_NO,acc.INSTITUTION_ID,de.account_type_id, de.LEDGER_BALANCE,de.AVAILABLE_BALANCE,de.BUSINESS_DATE,
  de.CURRENT_BALANCE,de.UNCOLLECTED_BALANCE,de.OVERDRAFT_CODE,de.CREATION_DATE,de.DATE_LAST_MAINTAINED,de.RETURNS_LAST_YR,
  de.TIMES_NSF_CURR_PERIOD,de.TIMES_NSF_YTD,de.NO_CHRG_BACK_ITEMS_YR_TO_DATE,de.TIMES_OD_PRYR,
  de.TIMES_OD_CURR_PERIOD,de.TIMES_OD_YTD,de.OVERDRAFT_LIMIT FROM ACCOUNT acc, DEPOSIT de
  WHERE acc.ACCOUNT_ID = de.ACCOUNT_ID
 );
 
 CREATE or REPLACE VIEW "ACCOUNT_DETAILS_VW"  ("ACCOUNT_ID", "ACCOUNT_NO", "INSTITUTION_ID", "ACCOUNT_TYPE_ID", "LEDGER_BALANCE",
"AVAILABLE_BALANCE",
"BUSINESS_DATE", "CURRENT_BALANCE", "UNCOLLECTED_BALANCE", "OVERDRAFT_CODE", "CREATION_DATE", "DATE_LAST_MAINTAINED",
"RETURNS_LAST_YR", "TIMES_NSF_CURR_PERIOD", "TIMES_NSF_YTD", "TIMES_OD_CURR_PERIOD", "TIMES_OD_YTD", "OVERDRAFT_LIMIT",
"NO_CHRG_BACK_ITEMS_YR_TO_DATE", "TIMES_OD_PRYR") AS
  (SELECT acc.account_id,de.ACCOUNT_NO,acc.INSTITUTION_ID,de.account_type_id, de.LEDGER_BALANCE,de.AVAILABLE_BALANCE,de.BUSINESS_DATE,
  de.CURRENT_BALANCE,de.UNCOLLECTED_BALANCE,de.OVERDRAFT_CODE,de.CREATION_DATE,de.DATE_LAST_MAINTAINED,de.RETURNS_LAST_YR,
  de.TIMES_NSF_CURR_PERIOD,de.TIMES_NSF_YTD,
  de.TIMES_OD_CURR_PERIOD,de.TIMES_OD_YTD,de.OVERDRAFT_LIMIT,de.NO_CHRG_BACK_ITEMS_YR_TO_DATE,de.TIMES_OD_PRYR FROM ACCOUNT acc, DEPOSIT de
  WHERE acc.ACCOUNT_ID = de.ACCOUNT_ID
 );
 
 CREATE OR REPLACE VIEW "ACCOUNT_DETAILS_VW" ("ACCOUNT_ID", "ACCOUNT_NO", "INSTITUTION_ID", "ACCOUNT_TYPE_ID", "LEDGER_BALANCE", "AVAILABLE_BALANCE", "BUSINESS_DATE", "CURRENT_BALANCE", "UNCOLLECTED_BALANCE", "OVERDRAFT_CODE", "CREATION_DATE", "DATE_LAST_MAINTAINED", "RETURNS_LAST_YR", "TIMES_NSF_CURR_PERIOD", "TIMES_NSF_YTD", "TIMES_OD_CURR_PERIOD", "TIMES_OD_YTD", "OVERDRAFT_LIMIT", "NO_CHRG_BACK_ITEMS_YR_TO_DATE", "TIMES_OD_PRYR", "DATE_OPENED", "DATE_LAST_DEPOSIT", "AVG_BALANCE_CURRENT_PERIOD", "YTD_AVERAGE_BALANCE") AS 
  (SELECT acc.account_id,de.ACCOUNT_NO,acc.INSTITUTION_ID,de.account_type_id, de.LEDGER_BALANCE,de.AVAILABLE_BALANCE,de.BUSINESS_DATE,
  de.CURRENT_BALANCE,de.UNCOLLECTED_BALANCE,de.OVERDRAFT_CODE,de.CREATION_DATE,de.DATE_LAST_MAINTAINED,de.RETURNS_LAST_YR,
  de.TIMES_NSF_CURR_PERIOD,de.TIMES_NSF_YTD,
  de.TIMES_OD_CURR_PERIOD,de.TIMES_OD_YTD,de.OVERDRAFT_LIMIT,de.NO_CHRG_BACK_ITEMS_YR_TO_DATE,de.TIMES_OD_PRYR, acc.DATE_OPENED, de.DATE_LAST_DEPOSIT, de.AVG_BALANCE_CURRENT_PERIOD, de.YTD_AVERAGE_BALANCE  FROM ACCOUNT acc, DEPOSIT de
  WHERE acc.ACCOUNT_ID = de.ACCOUNT_ID
 );