CREATE TABLE "REVERSAL_MAINTENANCE_LOG" 
   (	"UNIQUE_ID" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"ACTUAL_TRANS_CODE" VARCHAR2(30 BYTE), 
	"REVERSAL_TRANS_CODE" VARCHAR2(30 BYTE), 
	"ACTUAL_AMOUNT" VARCHAR2(30 BYTE), 
	"REVERSAL_AMOUNT" VARCHAR2(30 BYTE), 
	"ACTUAL_POST_DATE" VARCHAR2(30 BYTE), 
	"REVERSAL_POST_DATE" VARCHAR2(30 BYTE), 
	"CHECK_NUMBER" VARCHAR2(30 BYTE), 
	"REVERSAL_REASON" VARCHAR2(60 BYTE), 
	"USER_ID" VARCHAR2(30 BYTE), 
	"BRANCH_NAME" VARCHAR2(60 BYTE), 
	"ACCOUNT_NUMBER" VARCHAR2(30 BYTE), 
	"INSTITUTION_ID" VARCHAR2(20 BYTE), 
	 CONSTRAINT "REVERSAL_MAINTENANCE_LOG_PK" PRIMARY KEY ("UNIQUE_ID"));
	 

CREATE SEQUENCE  "REVERSAL_MAINTENANCE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 ORDER  NOCYCLE ;
 
	 