CREATE TABLE "SERVICE_REQ_POSTING_RULE" 
   (	"UNIQUE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SERVICE_REQUEST_ID" NUMBER(30), 
	"POSTING_RULE_ID" NUMBER(10,0), 
	 CONSTRAINT "SERVICE_REQ_POSTING_RULE_PK" PRIMARY KEY ("UNIQUE_ID"),
  	 CONSTRAINT "SERVICE_REQ_POSTING_RULE_FK1" FOREIGN KEY ("SERVICE_REQUEST_ID")
	  REFERENCES "SERVICE_REQUEST" ("SERVICE_REQUEST_ID"), 
	 CONSTRAINT "SERVICE_REQ_POSTING_RULE_FK2" FOREIGN KEY ("POSTING_RULE_ID")
	  REFERENCES "LEDGER_POSTING_PARAMETERS" ("UNIQUE_ID") 
   );