UPDATE PROPERTY_DEFINITION SET VALID_VALUES='java.lang.Integer:{default={0=All,2=Commercial,1=Consumer,4=Lease,3=Residential}}' 
WHERE PROPERTY_NAME LIKE 'ProductCategory' AND ENTITY_TYPE_DEFINITION_ID IN (SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE 'LoanProduct');

ALTER TABLE INVESTOR ADD FANNIE_MAE_INVESTOR NUMBER(5) DEFAULT 0;

ALTER TABLE INVESTOR ADD LENDER_NO_CHANGED NUMBER(5) DEFAULT 0;

ALTER TABLE INVESTOR ADD LENDER_NO_CHANGED_TIME DATE;

UPDATE PROPERTY_DEFINITION SET MANDATORY=0 WHERE PROPERTY_NAME LIKE 'RoutingTransitNumber' AND ENTITY_TYPE_DEFINITION_ID
 IN (SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE 'ExternalAgency');
 
UPDATE PROPERTY_DEFINITION SET MANDATORY=0 WHERE PROPERTY_NAME LIKE 'EscrowAccountNumber' AND ENTITY_TYPE_DEFINITION_ID
 IN (SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE 'ExternalAgency');
 
UPDATE PROPERTY_DEFINITION SET PROPERTY_INDEX=10 WHERE PROPERTY_NAME LIKE 'DisbursmentMode';
 
UPDATE PROPERTY_DEFINITION SET PROPERTY_INDEX=11 WHERE PROPERTY_NAME LIKE 'EscrowAccountNumber';

