CREATE TABLE STOP_INSTRUCTION_GROUP ("GROUP_ID" NUMBER(10), CONSTRAINT "GROUP_ID_PK" PRIMARY KEY ("GROUP_ID"));
ALTER TABLE STOP_PAYMENT_INSTRUCTION ADD INSTRUCTION_GROUP_ID NUMBER(10);
ALTER TABLE STOP_PAYMENT_INSTRUCTION ADD(CONSTRAINT INST_GROUP_ID_FK FOREIGN KEY(INSTRUCTION_GROUP_ID)
REFERENCES STOP_INSTRUCTION_GROUP(GROUP_ID));
CREATE SEQUENCE STOP_PAYMENT_GROUP_SEQ MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 100 ORDER NOCYCLE ;

ALTER TABLE SAVINGS_PLAN_DIST_TRANSACTIONS ADD ACCOUNT_HISTORY_ID NUMBER(10);

ALTER TABLE SAVINGS_PLAN_DIST_TRANSACTIONS  
ADD CONSTRAINT "ACCT_HIST_ID" FOREIGN KEY (ACCOUNT_HISTORY_ID) REFERENCES ACCOUNT_HISTORY_ITEM(TRANSACTION_ID);
