ALTER TABLE account_application ADD WEEK_END_PROCESSING VARCHAR2(60);
--ALTER TABLE payment_details ADD WEEK_END_PROCESSING VARCHAR2(60);

ALTER TABLE DEPOSIT ADD FREEZE_TXN_TYPE  VARCHAR2(100);
ALTER TABLE DEPOSIT ADD FREEZE_TXN_AMOUNT NUMBER(20,5) DEFAULT 0.00;

ALTER TABLE DEPOSIT ADD CREDIT_FRONT NUMBER(2) default 0;

ALTER TABLE DEPOSIT ADD CREDIT_BACK NUMBER(2) default 0;

ALTER TABLE DEPOSIT ADD DEBIT_FRONT NUMBER(2) default 0;
---------------------------------------------------------------------------------------------------------------------------------------

ALTER TABLE DEPOSIT ADD DEBIT_BACK NUMBER(2) default 0;

ALTER TABLE DEPOSIT ADD (NO_OF_IMAGES_ACROSS_PERPAGE number(10,0) default 0);

ALTER TABLE DEPOSIT ADD (NO_OF_IMAGES_VERTICAL_PERPAGE number(10,0) default 0);

ALTER TABLE DEPOSIT ADD TRUTH_IN_SAVINGS NUMBER(2) default 0;

alter table organization add  CREATION_DATE DATE;

alter table person add  CREATION_DATE DATE;

create table reports_mapping_tran_codes (ID NUMBER(20,5), tran_code VARCHAR2(10),view_name VARCHAR2(500));

ALTER TABLE CYCLE_GROUP_CONFIG ADD APPLICATION_NO VARCHAR2(20);
ALTER TABLE CYCLE_GROUP_CONFIG ADD STATEMENT_GENERATION_DATE DATE;

CREATE TABLE ACCOUNT_STATEMENT_CYCLE (CYCLE_ID NUMBER(10,0),
constraint STATEMENT_CYCLE_ID_PK primary key(CYCLE_ID) ,ACCOUNT_ID VARCHAR2(30) not null);   
 

CREATE TABLE STATEMENT_CYCLE_CODE (UNIQUE_ID NUMBER(30,0) NOT NULL,ACCT_STMT_CYCLE_ID NUMBER(10),
CONSTRAINT STMT_CYCLE_UNIQUE_ID_PK PRIMARY KEY (UNIQUE_ID),CYCLE_CODE varchar2(20),
CONSTRAINT ACCT_STMT_CYCLE_ID_FK FOREIGN KEY (ACCT_STMT_CYCLE_ID) REFERENCES ACCOUNT_STATEMENT_CYCLE (CYCLE_ID));
 

CREATE TABLE STATEMENT_CALENDAR (CALENDAR_ID NUMBER(30,0) NOT NULL,
CONSTRAINT CALENDAR_ID_PK PRIMARY KEY (CALENDAR_ID),CALENDAR_NAME VARCHAR2(100),
ACCT_STMT_CYCLE_ID NUMBER(10),
CONSTRAINT STMT_CYCLE_ID_FK FOREIGN KEY (ACCT_STMT_CYCLE_ID) REFERENCES ACCOUNT_STATEMENT_CYCLE (CYCLE_ID));

CREATE TABLE STATEMENT_CALENDAR_EFF_DATE (ID NUMBER(30,0) NOT NULL,STMT_CALENDAR_ID NUMBER(10),
CONSTRAINT STMT_CAL_EEF_DATE_ID_PK PRIMARY KEY (ID),
FROM_DATE DATE,
TO_DATE DATE,
CONSTRAINT STMT_CALENDAR_ID_FK FOREIGN KEY (STMT_CALENDAR_ID) REFERENCES STATEMENT_CALENDAR (CALENDAR_ID));