update PROPERTY_PRESENTER_ATTRIBUTES set hidden=0 where PROPERTY_DEFINITION_ID in(select PROPERTY_DEFINITION_ID from 
PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID in(select ENTITY_TYPE_DEFINITION_ID from ENTITY_TYPE_DEFINITION 
where TYPE_NAME='PastDueParameters')  and property_name='PastDueCountMethod');