update PROPERTY_PRESENTER_ATTRIBUTES set hidden=0 where PROPERTY_DEFINITION_ID in (select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID in (select ENTITY_TYPE_DEFINITION_ID 
from ENTITY_TYPE_DEFINITION where TYPE_NAME='LoanCustomerRole') 
and PROPERTY_NAME in('ECOACode','ConsumerInformationIndicator')) and STATE_NAME='DEFAULT';