CREATE TABLE COLLECTION_STANDARD_COMMENTS 
   (ID NUMBER(15,5) NOT NULL ENABLE, 
	COMMENTS_DESCRIPTION NVARCHAR2(300), 
	COMMENTS_ID NVARCHAR2(50), 
	COMMENT_STATUS NUMBER(5),
	 CONSTRAINT ID_PK PRIMARY KEY (ID));
--------------------------------------
CREATE SEQUENCE COLLECTION_STD_COMMENTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
----------------------------------------------------
create table LOSS_MITIGATION (
    id             NUMBER(10),
    ACCOUNT_NUMBER       VARCHAR2(10),
    QRPC_DATE            DATE,
    PACKAGE_SENT_DATE    DATE,
    PACKAGE_REC_DATE     DATE,
    PACKAGE_ASIGN_DATE   DATE,
    UNDER_WRITER         VARCHAR(20),
    ADD_DOC_REQ_DATE     DATE,
    ADD_DOC_REC_DATE     DATE,
    REV_SUB_TO_INVE_DATE DATE,
    WORKOUT_APPR_DATE    DATE,
    WORKOUT_TYPE         NUMBER(1),
    WORKOUT_DENIAL_DATE  DATE,
    DENIAL_REASON        VARCHAR(200),
    SUB_PMI_COMP_DATE    DATE,
    BREACH_LETTER_EXP_DATE DATE,
    REFFERED_FCL_DATE    DATE,
    HOUSE_BILL_LETTER_DATE DATE,
    DAY_60_HOLD_EXP_DATE DATE,
    DAY_90_HOLD_EXP_DATE DATE,
    PROP_LISTED_DATE     DATE,
    LIST_PRICE           NUMBER(20,5),
    LIST_AGENT           VARCHAR(20),
    PHOME_NUMBER         VARCHAR(20),
    EMAIL                VARCHAR(100),
    APPRAISED_VALUE      NUMBER(20,5),
    PURCHASE_OFF_REC_DATE DATE,
    PURCHASE_OFF_AMOUNT  NUMBER(20,5),
    FINAL_PURCHASE_OFF_AMOUNT   NUMBER(20,5),
    CLOSING_DATE         DATE,
    VACANCY_DATE         DATE,
    DIL_DOCS_DATE        DATE,
    COMMENTS             VARCHAR(200)
       
);


CREATE SEQUENCE LOSS_MITIGATION_ID_SEQ
    INCREMENT BY 1
    START WITH 101
    MAXVALUE 999999999
    NOMINVALUE
    NOCYCLE
    CACHE 20
    NOORDER;
    
CREATE TABLE COLLECTION_COMMENT
  (
    ID                NUMBER(10),
    ACCOUNT_NUMBER   VARCHAR2(20),
    ACCOUNT_NAME      VARCHAR2(100),
    ACTION_DATE       DATE,
    NEXT_ACTION_DATE DATE,
    BUSINESS_DATE    DATE,
    CREATED_DATE      DATE,
    USER_DEF_COMMNETS VARCHAR2(200),
    CREATED_BY        VARCHAR2(20),
    COMMENT_TYPE      VARCHAR2(30),
    STAND_COMMENT     NUMBER(10),
    AUTO_COMMENT      NUMBER(10)
  );
 
 
  CREATE SEQUENCE COLLECTION_COMMENT_SEQ
    INCREMENT BY 1
    START WITH 101
    MAXVALUE 999999999
    NOMINVALUE
    NOCYCLE
    CACHE 20
    NOORDER;