DELETE FROM PROPERTY_PRESENTER_ATTRIBUTES WHERE PROPERTY_DEFINITION_ID IN (SELECT PROPERTY_DEFINITION_ID FROM PROPERTY_DEFINITION WHERE PROPERTY_NAME ='DisclosureText1');

DELETE FROM PROPERTY_DEFINITION WHERE PROPERTY_NAME='DisclosureText1';

DELETE FROM PROPERTY_PRESENTER_ATTRIBUTES WHERE PROPERTY_DEFINITION_ID IN (SELECT PROPERTY_DEFINITION_ID FROM PROPERTY_DEFINITION WHERE PROPERTY_NAME ='DisclosureText2');

DELETE FROM PROPERTY_DEFINITION WHERE PROPERTY_NAME='DisclosureText2';

DELETE FROM PROPERTY_PRESENTER_ATTRIBUTES WHERE PROPERTY_DEFINITION_ID IN (SELECT PROPERTY_DEFINITION_ID FROM PROPERTY_DEFINITION WHERE PROPERTY_NAME ='DisclosureText3');

DELETE FROM PROPERTY_DEFINITION WHERE PROPERTY_NAME='DisclosureText3';

DELETE FROM PROPERTY_PRESENTER_ATTRIBUTES WHERE PROPERTY_DEFINITION_ID IN (SELECT PROPERTY_DEFINITION_ID FROM PROPERTY_DEFINITION WHERE PROPERTY_NAME ='DisclosureText4');

DELETE FROM PROPERTY_DEFINITION WHERE PROPERTY_NAME='DisclosureText4';

DELETE FROM PROPERTY_PRESENTER_ATTRIBUTES WHERE PROPERTY_DEFINITION_ID IN (SELECT PROPERTY_DEFINITION_ID FROM PROPERTY_DEFINITION WHERE PROPERTY_NAME ='DisclosureText5');

DELETE FROM PROPERTY_DEFINITION WHERE PROPERTY_NAME='DisclosureText5';

DELETE FROM PROPERTY_PRESENTER_ATTRIBUTES WHERE PROPERTY_DEFINITION_ID IN (SELECT PROPERTY_DEFINITION_ID FROM PROPERTY_DEFINITION WHERE PROPERTY_NAME ='StaticFootNoteForJanuary');

DELETE FROM PROPERTY_DEFINITION WHERE PROPERTY_NAME='StaticFootNoteForJanuary';

DELETE FROM PROPERTY_PRESENTER_ATTRIBUTES WHERE PROPERTY_DEFINITION_ID IN (SELECT PROPERTY_DEFINITION_ID FROM PROPERTY_DEFINITION WHERE PROPERTY_NAME ='FootNote1');

DELETE FROM PROPERTY_DEFINITION WHERE PROPERTY_NAME='FootNote1';

DELETE FROM PROPERTY_PRESENTER_ATTRIBUTES WHERE PROPERTY_DEFINITION_ID IN (SELECT PROPERTY_DEFINITION_ID FROM PROPERTY_DEFINITION WHERE PROPERTY_NAME ='FootNote2');

DELETE FROM PROPERTY_DEFINITION WHERE PROPERTY_NAME='FootNote2';

DELETE FROM PROPERTY_PRESENTER_ATTRIBUTES WHERE PROPERTY_DEFINITION_ID IN (SELECT PROPERTY_DEFINITION_ID FROM PROPERTY_DEFINITION WHERE PROPERTY_NAME ='FootNote3');

DELETE FROM PROPERTY_DEFINITION WHERE PROPERTY_NAME='FootNote3';

DELETE FROM PROPERTY_PRESENTER_ATTRIBUTES WHERE PROPERTY_DEFINITION_ID IN (SELECT PROPERTY_DEFINITION_ID FROM PROPERTY_DEFINITION WHERE PROPERTY_NAME ='ImportantMsg');

DELETE FROM PROPERTY_DEFINITION WHERE PROPERTY_NAME='ImportantMsg';


