--insert into RESPONSIBILITY_TYPE_LOOKUP values (19, 'CO_BORROWER');
--INSERT INTO INST_RESP_TYPE_OWNERSHIP_DESIG(ID, INSTITUTION_ID, RESPONSIBILITY_TYPE_ID, ORDER_TO_SORT, AFFIXDESIGKEYWORD, AFFIXPOSITION)
--  VALUES(INST_RESP_TYPE_OWNER_DESIG_SEQ.nextval, '10', 19, 20, NULL, 0);
--INSERT INTO INST_RESP_TYPE_OWNERSHIP_DESIG(ID, INSTITUTION_ID, RESPONSIBILITY_TYPE_ID, ORDER_TO_SORT, AFFIXDESIGKEYWORD, AFFIXPOSITION)
--  VALUES(INST_RESP_TYPE_OWNER_DESIG_SEQ.nextval, '1', 19, 20, NULL, 0);
--INSERT INTO INST_RESP_TYPE_OWNERSHIP_DESIG(ID, INSTITUTION_ID, RESPONSIBILITY_TYPE_ID, ORDER_TO_SORT, AFFIXDESIGKEYWORD, AFFIXPOSITION)
--  VALUES(INST_RESP_TYPE_OWNER_DESIG_SEQ.nextval, '2', 19, 20, NULL, 0);
--INSERT INTO INST_RESP_TYPE_OWNERSHIP_DESIG(ID, INSTITUTION_ID, RESPONSIBILITY_TYPE_ID, ORDER_TO_SORT, AFFIXDESIGKEYWORD, AFFIXPOSITION)
--  VALUES(INST_RESP_TYPE_OWNER_DESIG_SEQ.nextval, '3', 19, 20, NULL, 0);
--INSERT INTO INST_RESP_TYPE_OWNERSHIP_DESIG(ID, INSTITUTION_ID, RESPONSIBILITY_TYPE_ID, ORDER_TO_SORT, AFFIXDESIGKEYWORD, AFFIXPOSITION)
--  VALUES(INST_RESP_TYPE_OWNER_DESIG_SEQ.nextval, '4', 19, 20, NULL, 0);
--INSERT INTO INST_RESP_TYPE_OWNERSHIP_DESIG(ID, INSTITUTION_ID, RESPONSIBILITY_TYPE_ID, ORDER_TO_SORT, AFFIXDESIGKEYWORD, AFFIXPOSITION)
--  VALUES(INST_RESP_TYPE_OWNER_DESIG_SEQ.nextval, '5', 19, 20, NULL, 0);
--INSERT INTO INST_RESP_TYPE_OWNERSHIP_DESIG(ID, INSTITUTION_ID, RESPONSIBILITY_TYPE_ID, ORDER_TO_SORT, AFFIXDESIGKEYWORD, AFFIXPOSITION)
--  VALUES(INST_RESP_TYPE_OWNER_DESIG_SEQ.nextval, '6', 19, 20, NULL, 0);
--INSERT INTO INST_RESP_TYPE_OWNERSHIP_DESIG(ID, INSTITUTION_ID, RESPONSIBILITY_TYPE_ID, ORDER_TO_SORT, AFFIXDESIGKEYWORD, AFFIXPOSITION)
--  VALUES(INST_RESP_TYPE_OWNER_DESIG_SEQ.nextval, '7', 19, 20, NULL, 0);
--INSERT INTO INST_RESP_TYPE_OWNERSHIP_DESIG(ID, INSTITUTION_ID, RESPONSIBILITY_TYPE_ID, ORDER_TO_SORT, AFFIXDESIGKEYWORD, AFFIXPOSITION)
--  VALUES(INST_RESP_TYPE_OWNER_DESIG_SEQ.nextval, '8', 19, 20, NULL, 0);
--INSERT INTO INST_RESP_TYPE_OWNERSHIP_DESIG(ID, INSTITUTION_ID, RESPONSIBILITY_TYPE_ID, ORDER_TO_SORT, AFFIXDESIGKEYWORD, AFFIXPOSITION)
--  VALUES(INST_RESP_TYPE_OWNER_DESIG_SEQ.nextval, '9', 19, 20, NULL, 0);




