--  updating description of an loan entry type.
update ENTRY_TYPE set DESCRIPTION='Credit Life-A/H'  where  DESCRIPTION ='NonEscrow';

--  adding operator id to event
alter table LOAN_ACCOUNT_EVENT add OPERATOT_ID varchar2(50);

--End Day Update scripts for entry type link 
UPDATE LOAN_EVENT_ENTRY_TYPE_LINK SET ENTRY_TYPE_ID=1832 where ENTRY_TYPE_ID=1932 and EVENT_TYPE_ID=99;
UPDATE LOAN_EVENT_ENTRY_TYPE_LINK SET ENTRY_TYPE_ID=1833 where ENTRY_TYPE_ID=1933 and EVENT_TYPE_ID=99;
UPDATE LOAN_EVENT_ENTRY_TYPE_LINK SET ENTRY_TYPE_ID=1834 where ENTRY_TYPE_ID=1934 and EVENT_TYPE_ID=99;
UPDATE LOAN_EVENT_ENTRY_TYPE_LINK SET ENTRY_TYPE_ID=1835 where ENTRY_TYPE_ID=1935 and EVENT_TYPE_ID=99;


ALTER TABLE MAINTENANCE_LOG MODIFY ( "FIELD_CHANGED" VARCHAR2(90) );

ALTER TABLE LOAN_ACCOUNT_EVENT ADD ( TRACE_NO VARCHAR2(50));
ALTER TABLE LOAN_ACCOUNT_EVENT ADD (  BATCH_NO VARCHAR2(50));


ALTER TABLE LOAN_ACCOUNT_EVENT DROP COLUMN OPERATOT_ID;
ALTER TABLE LOAN_ACCOUNT_EVENT ADD (OPERATOR_ID VARCHAR2(50));

alter table loan_account_event add hidden number(1) default 0;

update LOAN_ENTRY_POSTING_RULE set AFFECTS_LAST_STMT_BAL=0 where POSTING_RULE_ID=8881;


INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1839, '1839', null, '2','0', 'Remaining Accrued Interest');    

INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1939, '1939', null, '2','1', 'Remaining Accrued Interest');
    
INSERT INTO LOAN_ENTRY_TYPE (ENTRY_TYPE_ID,ENTRY_NAME,REVERSAL_ENTRY_TYPE_ID,POSTING_RULE_ID) VALUES (1839,39,1939,38);    
INSERT INTO LOAN_ENTRY_TYPE (ENTRY_TYPE_ID,ENTRY_NAME,REVERSAL_ENTRY_TYPE_ID,POSTING_RULE_ID) VALUES (1939,39,1839,38);

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','1839');

ALTER TABLE LOAN_ENTRY_POSTING_RULE ADD AFF_ACC_LST_PROSSED_DATE NUMBER(1) DEFAULT 0;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_ACC_LST_PROSSED_DATE = 1 WHERE POSTING_RULE_ID = 9999;

UPDATE CLASS_CODE_MAPPING SET PRODUCT_CODE='02' ,COLLATERAL_CODE='56' WHERE ACCOUNT_TYPE_ID='110' AND
 CLASS_CODE='280';
UPDATE CLASS_CODE_MAPPING SET PRODUCT_CODE='01' ,COLLATERAL_CODE='05' WHERE ACCOUNT_TYPE_ID='110' AND
 CLASS_CODE='170';


INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(9940, '9940', null, '2','0', 'Escrow Disbursement');    
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(9941, '9941', null, '2','0', 'Life AH Disbursement');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(9112, '9112', null, '2','0', 'Future Payment-Reversal');

INSERT INTO LOAN_ENTRY_POSTING_RULE(POSTING_RULE_ID) VALUES(8840);
INSERT INTO LOAN_ENTRY_POSTING_RULE(POSTING_RULE_ID) VALUES(8841);
INSERT INTO LOAN_ENTRY_POSTING_RULE(POSTING_RULE_ID) VALUES(8112);


INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID)
  VALUES(8840, 8840, 9940, 8840);
INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID)
  VALUES(8841, 8841, 9941, 8841);
INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID)
  VALUES(8112, 8112, 9112, 8112);
INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID)
  VALUES(9940, 9940, 8840, 8840);
INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID)
  VALUES(9941, 9941, 8841, 8841);
INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID)
  VALUES(9112, 9912, 8112, 8112);




-------------------

INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(37, '037', 0, 237, null, 'Late Charge Waive off', '1');
INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(237, '237', 1, 37, null, 'Late Charge Waive off-Reversal', '0');

INSERT INTO loan_event_entry_type_link(EVENT_TYPE_ID, ENTRY_TYPE_ID)
  VALUES(37, 1919);
INSERT INTO loan_event_entry_type_link(EVENT_TYPE_ID, ENTRY_TYPE_ID)
  VALUES(37, 1907);
INSERT INTO  loan_event_entry_type_link(EVENT_TYPE_ID, ENTRY_TYPE_ID)
  VALUES(37, 8837);

INSERT INTO entry_type(UNIQUE_ID, ID, INSTITUTION_ID, DEBIT_OR_CREDIT, DESCRIPTION, ACCOUNT_CATEGORY, POSTING_SEQUENCE)
  VALUES(8837, '8837', null, '1', 'Late Charge Waive off', 2, NULL);
INSERT INTO entry_type(UNIQUE_ID, ID, INSTITUTION_ID, DEBIT_OR_CREDIT, DESCRIPTION, ACCOUNT_CATEGORY, POSTING_SEQUENCE)
  VALUES(99937, '9937', null, '0', 'Late Charge Waive off', 2, NULL);


INSERT INTO LOAN_ENTRY_POSTING_RULE(POSTING_RULE_ID) VALUES(8837);
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_TRAN_AMOUNT =1  WHERE POSTING_RULE_ID = 8837;


INSERT INTO loan_entry_type(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID)
  VALUES(8837, 8837, 99937, 8837);
INSERT INTO loan_entry_type(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID)
  VALUES(99937, 8837, 8837, 8837);

----------

insert into LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER,DESCRIPTION,DEBIT_OR_CREDIT)
values (113,113,2,313,null,'BSV Rejected Event ',null);
insert into LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER,DESCRIPTION,DEBIT_OR_CREDIT)
values (114,114,2,314,null,'BSV Rejected Event',null);
insert into LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER,DESCRIPTION,DEBIT_OR_CREDIT)
values (115,115,2,315,null,'BSV Rejected Event',null);


insert into LOAN_EVENT_ENTRY_TYPE_LINK(EVENT_TYPE_ID,ENTRY_TYPE_ID)values(313,1901);
insert into LOAN_EVENT_ENTRY_TYPE_LINK(EVENT_TYPE_ID,ENTRY_TYPE_ID)values(314,1901);
insert into LOAN_EVENT_ENTRY_TYPE_LINK(EVENT_TYPE_ID,ENTRY_TYPE_ID)values(315,1901);

alter table loan_account_day_summary modify ACCRUED_INTEREST_DIFFERECE varchar2(20);

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('110','1934');

alter table LOAN_ENTRY_POSTING_RULE add AFF_NEW_INTE_RATE NUMBER(1) default 0;
alter table LOAN_ENTRY_POSTING_RULE add AFF_CUR_INT_RATE NUMBER(1) default 0;
alter table LOAN_ENTRY_POSTING_RULE add AFF_RCHISTORY NUMBER(1) default 0;
alter table LOAN_ENTRY_POSTING_RULE add AFF_PCHISTORY NUMBER(1) default 0;

update LOAN_ENTRY_POSTING_RULE set AFF_NEW_INTE_RATE=1,AFF_CUR_INT_RATE=1
,AFF_RCHISTORY=1,AFF_PCHISTORY=1 where POSTING_RULE_ID=9999;



