ALTER TABLE PRODUCT_TYPE ADD AVAIL_ON_MULTI_CUST_TYPES NUMBER(1) DEFAULT 0;

ALTER TABLE DEPOSIT ADD INT_RATE_VARIANCE_EXPIRY_DATE DATE;

ALTER TABLE DEPOSIT ADD ALLOWED_INTEREST_RATE_VARIANCE NUMBER(15,5) DEFAULT 0.00; 

ALTER TABLE party_registered_ids ADD ID_AFFILIATION VARCHAR2(100);

ALTER TABLE party_registered_ids ADD  IS_PRIMARY VARCHAR2(50);

ALTER TABLE account_application ADD APPLICATION_FORMS_COMPLETED NUMBER;

ALTER TABLE INTERESTED_PARTY ADD AUTHORIZATION_FORM_SIGNED NUMBER(1);

ALTER TABLE DYNAMIC_FORMS ADD ACCOUNT_OPENING_EVENT_ID VARCHAR2(30);

CREATE TABLE CD_Product_Type_Mapping(
    UNIQUE_ID NUMBER(30,0) NOT NULL ENABLE,
    CD_PRODUCT_TYPE VARCHAR2(100),
      PRODUCT_TYPE_ID VARCHAR2(100),
   CONSTRAINT "CD_PROD_TYPE_MAPPING_PK" PRIMARY KEY ("UNIQUE_ID") ENABLE );
   
ALTER TABLE product_type_aud ADD AVAIL_ON_MULTI_CUST_TYPES NUMBER(1,0);
ALTER TABLE product_type_aud ADD AVAILONMULTICUSTTYPE_MOD CHAR(1 CHAR);  
ALTER TABLE product_type_aud ADD CUSTOMERTYPE_MOD CHAR(1 CHAR);