UPDATE PROPERTY_DEFINITION SET MANDATORY=1 WHERE PROPERTY_NAME='EscrowConstant' AND ENTITY_TYPE_DEFINITION_ID IN(SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME='EscrowDetail');

UPDATE PROPERTY_DEFINITION SET MANDATORY=1 WHERE PROPERTY_NAME='AnalyzeMethod' AND ENTITY_TYPE_DEFINITION_ID IN(SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME='EscrowDetail'); 

UPDATE PROPERTY_DEFINITION SET MANDATORY=1 WHERE PROPERTY_NAME='PayInterest' AND ENTITY_TYPE_DEFINITION_ID IN(SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME='EscrowDetail'); 

UPDATE PROPERTY_DEFINITION SET MANDATORY=1 WHERE PROPERTY_NAME='EscrowType' AND ENTITY_TYPE_DEFINITION_ID IN(SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE '%Escrow%');

UPDATE PROPERTY_PRESENTER_ATTRIBUTES SET HIDDEN=0,HIDDEN_OVERRIDEN=0,EDITABLE=0,EDITABLE_OVERRIDEN=0  WHERE PROPERTY_DEFINITION_ID IN 
(SELECT PROPERTY_DEFINITION_ID FROM PROPERTY_DEFINITION WHERE PROPERTY_NAME='NextEscrowDue');