alter table coresoft_depo_revision_entity add user_branch_id varchar2(100);

alter table coresoft_depo_revision_entity add USER_INSTITUTION_ID varchar2(100);

CREATE OR REPLACE FORCE VIEW "TXN_INSTITUTION_VW" ("INSTITUTION_ID", "INSTITUTION_NAME", "PARENT_NAME", "PARENT_ID", "LAST_PROCESSED_DATE","NEXT_BUSINESS_DATE")
AS
  SELECT INSTITUTION_ID,
    INSTITUTION_NAME,
    PARENT_NAME,
    PARENT_ID,
    LAST_PROCESSED_DATE,
    NEXT_BUSINESS_DATE
  FROM INSTITUTION;
