CREATE TABLE "REQUEST_MASTER" (
    "REQUEST_ID" NUMBER(30,0) NOT NULL ENABLE, 
	  "REQUEST_NAME" VARCHAR2(100),
   CONSTRAINT "REQUEST_MASTER_PK" PRIMARY KEY ("REQUEST_ID") ENABLE);

create sequence REQUEST_MASTER_UID_SEQ minvalue 1 maxvalue 9999999999 increment by 1 start with 1;


CREATE TABLE "CHANNEL_MASTER" (
    "CHANNEL_ID" NUMBER(30,0) NOT NULL ENABLE, 
	  "CHANNEL_NAME" VARCHAR2(100),
   CONSTRAINT "CHANNEL_MASTER_PK" PRIMARY KEY ("CHANNEL_ID") ENABLE);

create sequence CHANNEL_MASTER_UID_SEQ minvalue 1 maxvalue 9999999999 increment by 1 start with 1;

CREATE TABLE "CHANNEL_REQUEST_MAPPING" (
    "CHANNEL_REQUEST_ID" NUMBER(30,0) NOT NULL ENABLE, 
	  "CHANNEL_ID"  NUMBER(30,0),
    "REQUEST_ID"  NUMBER(30,0),
   CONSTRAINT "CHANNEL_REQUEST_PK" PRIMARY KEY ("CHANNEL_REQUEST_ID") ENABLE ,
   CONSTRAINT "CHANNEL_MASTER_FK" FOREIGN KEY ("CHANNEL_ID") REFERENCES "CHANNEL_MASTER" ("CHANNEL_ID") ENABLE,
   CONSTRAINT "REQUEST_MASTER_FK" FOREIGN KEY ("REQUEST_ID") REFERENCES "REQUEST_MASTER" ("REQUEST_ID") ENABLE);
   
create sequence CHANNEL_REQUEST_SEQ minvalue 1 maxvalue 9999999999 increment by 1 start with 1;


CREATE TABLE "CHANNEL_PRODUCT_AUTHORIZATION" (
    "CHANNEL_PROD_AUTH_ID" NUMBER(30,0) NOT NULL ENABLE, 
	  "PRODUCT_ID"  NUMBER(15),
    "AUTH_REQUIRED"  NUMBER(1),
    "CHANNEL_REQUEST_ID" NUMBER(30,0),
   CONSTRAINT "CHANNEL_PROD_AUTH_PK" PRIMARY KEY ("CHANNEL_PROD_AUTH_ID") ENABLE ,
   CONSTRAINT "PRODUCT_ID_FK" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_UID") ENABLE,
   CONSTRAINT "CHANNEL_REQUEST_FK" FOREIGN KEY ("CHANNEL_REQUEST_ID") REFERENCES "CHANNEL_REQUEST_MAPPING" ("CHANNEL_REQUEST_ID") ENABLE);
   
   create sequence CHANNEL_PRODUCT_AUTH_SEQ minvalue 1 maxvalue 9999999999 increment by 1 start with 1;