CREATE TABLE "CIF_FIELDS_MASTER" (
    "CIF_FIELD_ID" NUMBER(30,0) NOT NULL ENABLE, 
	  "FIELD_NAME" VARCHAR2(200),
    "IS_PERSONAL_CUSTOMER" NUMBER,
    "IS_BUSINESS_CUSTOMER" NUMBER,
   CONSTRAINT "CIF_FIELDS_PK" PRIMARY KEY ("CIF_FIELD_ID") ENABLE);
   
   create sequence CIF_FIELDS_MASTER_SEQ minvalue 1 maxvalue 9999999999 increment by 1 start with 1;
   
   
   CREATE TABLE "CIF_RESPONSIBILITY_MAPPING" (
    "CIF_VALIDATION_ID" NUMBER(30,0) NOT NULL ENABLE, 
	  "RESPONSIBILITY_TYPE"  VARCHAR2(50),
    "VALIDATION_REQUIRED"  NUMBER,
    "CIF_FIELD_ID" NUMBER(30,0),
   CONSTRAINT "CIF_VALIDATION_PK" PRIMARY KEY ("CIF_VALIDATION_ID") ENABLE ,
   CONSTRAINT "CIF_FIELDS_FK" FOREIGN KEY ("CIF_FIELD_ID") REFERENCES "CIF_FIELDS_MASTER" ("CIF_FIELD_ID") ENABLE);
   
 create sequence CIF_VALIDATION_SEQ minvalue 1 maxvalue 9999999999 increment by 1 start with 1;