-- table for all business types
CREATE TABLE BUSINESS_TYPE_MASTER
(
	BUSINESS_ID int NOT NULL,
	BUSINESS_DESCRIPTION VARCHAR2(100) NOT NULL,
	STATUS NUMBER (1) DEFAULT 0,
	CREATED_BY VARCHAR2(30),
	DATE_CREATED DATE,
	MODIFIED_BY VARCHAR2(100),
	DATE_MODIFIED DATE,	
	PRIMARY KEY (BUSINESS_ID)
);

CREATE TABLE BUSINESS_REGID_MAPPING
(
	BUS_REG_UID int NOT NULL,
	BUSINESS_ID NUMBER(10) NOT NULL,
	UNIQUE_REGID NUMBER(10),
	CREATED_BY VARCHAR2(30),
	DATE_CREATED DATE,
	PRIMARY KEY (BUS_REG_UID),
    FOREIGN KEY (BUSINESS_ID) REFERENCES BUSINESS_TYPE_MASTER(BUSINESS_ID),
	FOREIGN KEY (UNIQUE_REGID) REFERENCES ID_TYPE_MASTER(UNIQUE_ID)
);

-- WebAdress new table
CREATE TABLE WEBSITE_ADDRESS 
(
    WEBSITE_URL VARCHAR2(100), 
	ADDRESS_ID NUMBER(10,0) NOT NULL ENABLE, 
	CONSTRAINT "WEBSITEADDR_PK" PRIMARY KEY (ADDRESS_ID) , 
	CONSTRAINT "WEBSITEADDR_ADDRID_FK" FOREIGN KEY (ADDRESS_ID)  REFERENCES ADDRESS (ADDRESS_ID)
);

-- ADDRESS_ADDRTYPE_CHK constraint script:

ALTER TABLE ADDRESS DROP CONSTRAINT ADDRESS_ADDRTYPE_CHK;
ALTER TABLE ADDRESS ADD CONSTRAINT ADDRESS_ADDRTYPE_CHK CHECK (ADDRESS_TYPE IN('GEOGRAPHIC','TELECOM','WEB','WEBSITE')) ENABLE;

ALTER TABLE RESPONSIBILITY_TYPE_LOOKUP ADD ENABLED NUMBER DEFAULT 0;
ALTER TABLE RESPONSIBILITY_TYPE_LOOKUP ADD ACCOUNT_CATEGORY VARCHAR2(50);
--Account_category to decide whether this responsibility is for Deposits and loans

--scripts for ID_TYPE_MASTER table:

ALTER TABLE ID_TYPE_MASTER ADD ALLOW_MULTIPLE_ID NUMBER(1) DEFAULT 0;
ALTER TABLE ID_TYPE_MASTER ADD STATUS NUMBER DEFAULT 0;
ALTER TABLE ID_TYPE_MASTER ADD CHARTER_IND NUMBER DEFAULT 0;
ALTER TABLE ID_TYPE_MASTER ADD SCAN_REQUIRED NUMBER(1) DEFAULT 0;
ALTER TABLE ID_TYPE_MASTER ADD PERSONAL_CUSTOMER_TYPE NUMBER DEFAULT 0;
ALTER TABLE ID_TYPE_MASTER ADD BUSINESS_CUSTOMER_TYPE NUMBER DEFAULT 0;
ALTER TABLE ID_TYPE_MASTER ADD ENABLED NUMBER DEFAULT 0;

ALTER TABLE PARTY_REGISTERED_IDS ADD PRIORITY NUMBER(1);
CREATE TABLE CIF_RESPONSIBILITY_VALIDATIONS
(
	ID int NOT NULL,
	PROPERTY_NAME VARCHAR(100) NOT NULL,
	VALIDATION_REQUIRED NUMBER DEFAULT 0,
	RESPONSIBILITY VARCHAR2(100)
);      

ALTER TABLE PARTY_REGISTERED_IDS ADD CHARTER_IND VARCHAR2(1);