CREATE TABLE RATE_CHANGE_INSTRUCTION
(
ID NUMBER(10) NOT NULL,
PRODUCT_CODE VARCHAR2(30),
PRODUCT_NAME VARCHAR2(200),
EFFECTIVE_DATE DATE,
INTEREST_RATE NUMBER(20,5),
ENTRY_DATE DATE,
OLD_INTEREST_RATE NUMBER(20,5),
PRIMARY KEY (ID)
); 

CREATE SEQUENCE RATECHANGE_INSTRUCTION_ID_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOMINVALUE NOCYCLE ORDER;