 INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(002, '002', 0, 202, null, 'Rate Change Instruction Event', '1');
INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(202, '202', 1, 002, null, 'Rate Change Instruction Event Reversal', '1');
  
 INSERT INTO ENTRY_TYPE(UNIQUE_ID,ID,INSTITUTION_ID,DEBIT_OR_CREDIT,DESCRIPTION,ACCOUNT_CATEGORY,POSTING_SEQUENCE,IS_REVERSAL)
VALUES(8802, '8802', NULL, '0', 'RateChangeInstructionEvent', 2, NULL, '0');

ALTER TABLE LOAN_ENTRY_POSTING_RULE ADD  AFF_RATE_CHANGE_INSTRUCTION NUMBER(20) DEFAULT 0;
 INSERT INTO LOAN_ENTRY_POSTING_RULE(POSTING_RULE_ID, AFF_RATE_CHANGE_INSTRUCTION) VALUES(8802, 1);
 INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID) VALUES(8802,8802,8802,8802);
  
insert into loan_event_entry_type_link values(002,8802);

UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_DATE_LAST_ACTIVITY=1,AFFECTS_PARTIAL_PAYMENT=1,AFFECTS_DATE_NEXT_DUE=1,AFFECTS_PAYMENTS_MADE=1,
AFFECTS_LAST_TRAN_AMOUNT=1,AFFECTS_BILL=1,AFFECTS_LAST_PYMNT_AMOUNT=1,AFFECTS_DTNXTDUBFRPSTNG=1 WHERE POSTING_RULE_ID=8802;

insert into LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) values (002,(select unique_id from entry_type where id='1901'));
insert into LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) values (002,(select unique_id from entry_type where id='1902'));
insert into LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) values (002,(select unique_id from entry_type where id='1907'));
insert into LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) values (002,(select unique_id from entry_type where id='1917'));