CREATE TABLE INST_ALIAS_NAMES      
    (   ID NUMBER(15) ,
		INSTITUTION_ID  VARCHAR2(10) ,
        EXTRACT_FILE_TYPE  VARCHAR2(20) ,
      	LENGTH_OF_INST_NAME  NUMBER(25),
        INSTITUTION_NAME  VARCHAR2(50),
		LENGTH_OF_INST_DESC_NAME  NUMBER(25),
		INSTITUTION_DESC_NAME  VARCHAR2(50)
    );
    
--Applying constraints
    
ALTER TABLE INST_ALIAS_NAMES
ADD CONSTRAINT INST_ALIAS_NAMES_PK_ID PRIMARY KEY(ID);

ALTER TABLE INST_ALIAS_NAMES
ADD CONSTRAINT INST_ALIAS_NAMES_FK_INST_ID FOREIGN KEY (INSTITUTION_ID) REFERENCES INSTITUTION(INSTITUTION_ID); 

ALTER TABLE INST_ALIAS_NAMES ADD(LENGTH_OF_FILE_HDR_ORGNTR_NAME NUMBER(25));

ALTER TABLE INST_ALIAS_NAMES ADD(FILE_HDR_ORGNTR_NAME VARCHAR(50));

ALTER TABLE INST_ALIAS_NAMES ADD(LENGTH_OF_FILE_HDR_DSTNTN_NAME NUMBER(25));

ALTER TABLE INST_ALIAS_NAMES ADD(FILE_HDR_DSTNTN_NAME VARCHAR(50));

ALTER TABLE PARTY_INSTITUTION_ASSOCIATION ADD DATE_W9_VERIFIED_ON_FILE DATE;
    
ALTER TABLE ACH_WARE_HOUSE_ENTRY ADD SCREENING_USER VARCHAR2(9);

ALTER TABLE ACH_WARE_HOUSE_ENTRY ADD SCREENING_DATE_TIME TIMESTAMP;

ALTER TABLE ACH_WARE_HOUSE_ENTRY ADD SCREENING_PROCESSING_DATE DATE;

ALTER TABLE ACCOUNT_HISTORY_ITEM ADD HOLD_INSTRUCTION_ID VARCHAR2(20);

ALTER TABLE PARTY_REGISTERED_IDS ADD IS_DOCUMENT_SCANNED NUMBER(1,0) DEFAULT 0;

ALTER TABLE ACCOUNT ADD SCANNED_SIGNATURE_TYPE NUMBER(1,0) DEFAULT 5;