 

ALTER TABLE LOAN_ENTRY_POSTING_RULE ADD AFF_ESCW_DISB_AMT_YTD NUMBER(1) DEFAULT 0 ;
ALTER TABLE LOAN_ENTRY_POSTING_RULE ADD AFF_ESCW_SUMRY_DISB_AMT_YTD NUMBER(1) DEFAULT 0 ;
ALTER TABLE LOAN_ENTRY_POSTING_RULE ADD AFF_MISCESCWSUMRY_DISB_AMT_YTD NUMBER(1) DEFAULT 0 ;


 
