alter table loan_bills_ltd drop constraint LOAN_BILLS_LTD_ACCID_FK;

--ALTER TABLE loan_account_event
-- DROP constraint SYS_C0086152;
 
 ALTER TABLE loan_account_event
 ADD CONSTRAINT FK_LOAN
 FOREIGN KEY (ACCOUNT_ID)
 REFERENCES LOAN(ACCOUNT_ID);
 
--SYS_C0086154

--ALTER TABLE loan_account_day
-- DROP constraint SYS_C0086154;
 
 ALTER TABLE loan_account_day
 ADD CONSTRAINT FK_LOANDAY_LOAN
 FOREIGN KEY (ACCOUNT_ID)
 REFERENCES LOAN(ACCOUNT_ID);


 ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM
 ADD CONSTRAINT FK_LOANHISTITEM_LOAN
 FOREIGN KEY (ACCOUNT_ID)
 REFERENCES LOAN(ACCOUNT_ID);