--Commented the below already in 1.0.23
--INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, DEBIT_OR_CREDIT, DESCRIPTION, ACCOUNT_CATEGORY, POSTING_SEQUENCE)
--  VALUES(8842, '8842', null, '1', 'Loan Extension', 2, NULL)
--;

INSERT INTO LOAN_ENTRY_POSTING_RULE (POSTING_RULE_ID)VALUES (51);
INSERT INTO LOAN_ENTRY_POSTING_RULE (POSTING_RULE_ID)VALUES (52);

 

UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_ESCW_DISB_AMT_YTD = 1, AFF_ESCW_SUMRY_DISB_AMT_YTD = 1 WHERE POSTING_RULE_ID = 51;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_MISCESCWSUMRY_DISB_AMT_YTD = 1 WHERE POSTING_RULE_ID = 52;

 

 

---Entry Types
--esc disb ytd
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES((select max(unique_id)+1 from entry_type), '1951', null, '2','1', 'ESCROW DISBURSED AMOUNT');
 
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES((select max(unique_id)+1 from entry_type), '1851', null, '2','0', 'ESCROW DISBURSED AMOUNT');

INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES((select max(unique_id)+1 from entry_type), '1952', null, '2','1', 'MISC ESCROW DISBURSED AMOUNT');
 
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES((select max(unique_id)+1 from entry_type), '1852', null, '2','0', 'MISC_ESCROW DISBURSED AMOUNT'); 


INSERT INTO LOAN_ENTRY_TYPE (ENTRY_TYPE_ID,ENTRY_NAME,REVERSAL_ENTRY_TYPE_ID,POSTING_RULE_ID)
VALUES ((select unique_id from entry_type where id='1951'), 51, (select unique_id from entry_type where id='1851'), 51);
 
INSERT INTO LOAN_ENTRY_TYPE (ENTRY_TYPE_ID,ENTRY_NAME,REVERSAL_ENTRY_TYPE_ID,POSTING_RULE_ID)
VALUES ((select unique_id from entry_type where id='1851'), 51, (select unique_id from entry_type where id='1951'), 51);

INSERT INTO LOAN_ENTRY_TYPE (ENTRY_TYPE_ID,ENTRY_NAME,REVERSAL_ENTRY_TYPE_ID,POSTING_RULE_ID)
VALUES ((select unique_id from entry_type where id='1952'), 52, (select unique_id from entry_type where id='1852'), 52);

INSERT INTO LOAN_ENTRY_TYPE (ENTRY_TYPE_ID,ENTRY_NAME,REVERSAL_ENTRY_TYPE_ID,POSTING_RULE_ID)
VALUES ((select unique_id from entry_type where id='1852'), 52, (select unique_id from entry_type where id='1952'), 52);

 

