  
  
  CREATE TABLE ESCROW_DISBURSEMENT_EVENT(
    MONETARY_EVENT_TYPE_ID  NUMBER(10,0) NOT NULL,
    ESCROW_AGENCY_CODE       VARCHAR2(30) NOT NULL,
    ESCROW_AGENCY_TYPE       VARCHAR2(30) NULL,
    ESCROW_DETAIL_ID         NUMBER(25) NOT NULL,
    ESCROW_BILL_DUE_DATE     DATE NOT NULL,
    COLLECTOR_CODE           VARCHAR2(30),

CONSTRAINT ESCW_DISBRS_EVENT_PKEY PRIMARY KEY(MONETARY_EVENT_TYPE_ID),
CONSTRAINT FK_LN_MON_ESCW_DISBRS FOREIGN KEY (MONETARY_EVENT_TYPE_ID)
  REFERENCES LOAN_ACCOUNT_MONETARY_EVENT(MONETARY_EVENT_TYPE_ID)
);


--alter table Loan add  PAY_OFF_ACCRUED_INTEREST  NUMBER(20);

--alter table Loan add  PAY_OFF_ACCRUED_INTEREST_NET  NUMBER(20);

--alter table Loan add  PAY_OFF_DAILY_ACCURAL  NUMBER(20);






