ALTER TABLE entry_type
ADD NEEDS_BALANCING NUMBER(1,0);

ALTER TABLE entry_type
ADD APPLICATION_TYPE varchar2(30);

ALTER TABLE entry_type
ADD OFFSET_TRANCODE varchar2(10);

ALTER TABLE LOAN_EVENT_TYPE
ADD NEEDS_BALANCING NUMBER(1,0);

ALTER TABLE LOAN_EVENT_TYPE
ADD OFFSET_APPLICATION_TYPE varchar2(30);

ALTER TABLE LOAN_EVENT_TYPE
ADD OFFSET_TRANCODE varchar2(10);

update entry_type
set needs_balancing = 0
where id = 93;

update entry_type
set needs_balancing = 1
where id <> 93;

update loan_event_type
set needs_balancing=0;

create sequence GL_TRANSACTION_SEQ;

CREATE TABLE GL_TRANSACTION (    
   	ID NUMBER(19,0) NOT NULL ENABLE, 
    CORE_INSTITUTION_ID VARCHAR2(255), 
    CORE_BRANCH_ID VARCHAR2(255), 
    ACCOUNT_TYPE NUMBER(5,0), 
    PRODUCT_CODE NUMBER(5,0), 
    MONETARY_COMPONENT_CODE NUMBER(20,0), 
    CORE_ACCOUNT_NUMBER VARCHAR2(20), 
    CORE_TRAN_CODE VARCHAR2(11), 
    CORE_DEBIT_CREDIT NUMBER(10,0), 
    CURRENCY VARCHAR2(10), 
    CORE_TRANSACTION_AMOUNT NUMBER(20,5), 
    CORE_EFFECTIVE_DATE DATE, 
    CORE_TRANSACTION_DATE DATE, 
    CORE_DESCRIPTION VARCHAR2(255), 
    INSTITUTION_ID VARCHAR2(255), 
    BRANCH_ID VARCHAR2(255), 
    ACCOUNT_ID VARCHAR2(255), 
    TRANSACTION_TYPE NUMBER(10,0), 
    TRANSACTION_CODE VARCHAR2(255), 
    BATCH_NUMBER NUMBER(10,0), 
    DESCRIPTION VARCHAR2(255), 
    ERROR_INDICATOR VARCHAR2(255), 
    EFFECTIVE_DATE DATE, 
    AMOUNT NUMBER(20,5), 
    TRANSACTION_DATE DATE, 
    SEQ_NUM NUMBER(10,0), 
    ITEM_COUNT NUMBER(10,0), 
    CORE_TRANSACTION_ID NUMBER(20,0), 
    CORE_PRODUCT NUMBER(5,0), 
    CORE_STATUS VARCHAR2(5), 
    CORE_POSTING_STATUS NUMBER(5,0), 
    FILE_NAME VARCHAR2(30), 
    SOURCE_TYPE VARCHAR2(30), 
    CORE_ACCOUNT_CATEGORY VARCHAR2(2), 
    SUMMARIZATION_STATUS VARCHAR2(10), 
     PRIMARY KEY (ID)
);