CREATE TABLE TICKLER_USER_GROUPS 
   	(ID NUMBER(15,5) NOT NULL ENABLE, 
	GROUP_ID NVARCHAR2(50), 
	GROUP_NAME NVARCHAR2(50),
	USER_ID NVARCHAR2(50),
	CREATED_DATE DATE,
	CREATED_BY NVARCHAR2(50),
	DATE_USER_ADDED DATE,
	DATE_USER_DISABLED DATE,
	STATUS NUMBER(5),
	CONSTRAINT TICKLER_USER_GROUPS_PK PRIMARY KEY (ID));
	
CREATE SEQUENCE TICKLER_USER_GROUPS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;