--Added script to make as mandatory for loan officer lending limits.
UPDATE PROPERTY_DEFINITION SET MANDATORY=1,DEFAULT_VALUE='com.vsoftcorp.finance.Money:USD 99999999999.99' WHERE PROPERTY_NAME LIKE 'LendingLimitUnsecuredLoan' AND ENTITY_TYPE_DEFINITION_ID IN (SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE 'LoanOfficer');
UPDATE PROPERTY_DEFINITION SET MANDATORY=1,DEFAULT_VALUE='com.vsoftcorp.finance.Money:USD 99999999999.99' WHERE PROPERTY_NAME LIKE 'LendingLimitSecuredLoan' AND ENTITY_TYPE_DEFINITION_ID IN (SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE 'LoanOfficer');
UPDATE PROPERTY_DEFINITION SET MANDATORY=1,DEFAULT_VALUE='com.vsoftcorp.finance.Money:USD 99999999999.99' WHERE PROPERTY_NAME LIKE 'LendingLimitSecuredByDeposit' AND ENTITY_TYPE_DEFINITION_ID IN (SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE 'LoanOfficer');
UPDATE PROPERTY_DEFINITION SET MANDATORY=1,DEFAULT_VALUE='com.vsoftcorp.finance.Money:USD 99999999999.99' WHERE PROPERTY_NAME LIKE 'LendingLimitRealEstate' AND ENTITY_TYPE_DEFINITION_ID IN (SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE 'LoanOfficer');


