ALTER TABLE FORM_TEMPLATE DROP COLUMN  SOURCE ;

--ALTER TABLE FORM_TEMPLATE ADD CUST_ACC_LEVEL VARCHAR(50);

ALTER TABLE PRODUCT_FORM_TEMPLATE ADD CUSTOMER_TYPE NUMBER(15,0);

CREATE TABLE BUSINESS_PROCESS_TEMPLATE
("BUSINESS_PROCESS_UID" NUMBER(20,0) NOT NULL ENABLE,
"BUSINESS_PROCESS_ID"  NUMBER(20,0),
"DESCRIPTION" VARCHAR(50),
CONSTRAINT "BUSINESS_PROCESS_TEMPLATE_PK" PRIMARY KEY ("BUSINESS_PROCESS_UID"));


CREATE TABLE BUSINESS_PROD_FORM_TEMPLATE
("UNIQUE_ID" NUMBER(15,0) NOT NULL ENABLE,
"BUSINESS_PROCESS_UID" NUMBER(15,0),
"PROD_FORM_TEMP_UID"  NUMBER(15),
"SEQ" NUMBER(15,0),
"SCANNED"  NUMBER,
"PRINTED" NUMBER,
"SAVED_IN_FILE" NUMBER,
CONSTRAINT "BUSINESS_PRODUCT_UNIQUE_PK" PRIMARY KEY ("UNIQUE_ID"),
CONSTRAINT BUSINESS_PRODUCT_UID_FK FOREIGN KEY(BUSINESS_PROCESS_UID) REFERENCES BUSINESS_PROCESS_TEMPLATE(BUSINESS_PROCESS_UID)
ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE);


ALTER TABLE BUSINESS_PROD_FORM_TEMPLATE
ADD (CONSTRAINT PRODUCT_FORM_TEMP_FK FOREIGN KEY(PROD_FORM_TEMP_UID)
REFERENCES PRODUCT_FORM_TEMPLATE(PROD_FORM_TEMP_UID)
ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

CREATE TABLE DYNAMIC_FORMS
("UNIQUE_ID" NUMBER(20) NOT NULL ENABLE,
"BUSINESS_PRODUCT_FORM_UID" Number(20),
"CUSTOMER_ID" VARCHAR(20),
"ACCOUNT_NUMBER" VARCHAR(20),
"LATEST_FORM_PATH" VARCHAR2(200),
"SCANNED_DATE" DATE,
"PRINTED_DATE" DATE,
"PDF_DATE" DATE,
"STATUS" VARCHAR(20),
"VERSION_NO" NUMBER(20),
"PDF_NAME" VARCHAR2(100),
CONSTRAINT "UNIQUE_FORM_PK" PRIMARY KEY ("UNIQUE_ID"),
CONSTRAINT BUSINESS_PRODUCT_FORM_ID_FK FOREIGN KEY(BUSINESS_PRODUCT_FORM_UID)
REFERENCES BUSINESS_PROD_FORM_TEMPLATE(UNIQUE_ID)
ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE);

CREATE SEQUENCE DYNAMIC_FORMS_UID_SEQ INCREMENT BY 1 ;

CREATE SEQUENCE BUSI_PROD_FORM_TEMP_UID_SEQ INCREMENT BY 1;

CREATE SEQUENCE BUSI_PROC_TEMP_UID_SEQ INCREMENT BY 1;

