CREATE OR REPLACE VIEW AUTOMATIC_TRANSFER_VW ( AUTO_TRANS_UNIQUE_ID, SOURCE_ACCOUNT, SOURCE_ACC_NO, SOURCE_INST_NO, SOURCE_ACC_TYPE_ID, TARGET_ACCOUNT, TARGET_ACC_NO, TARGET_INST_NO, TARGET_ACC_TYPE_ID, TRANSFER_MONEY, TRANSFER_FREQUENCY, NUMBER_OF_TRANSFERS, START_DATE, END_DATE, AUTOMATIC_TRANSFER, IS_VARIABLE_AMOUNT, IS_ACTIVE,AUTO_RETRIVAL_COUNT,MAX_AUTO_RETRY_COUNT,NEXT_RETRIVALDATE,NEXT_PROCESSING_DATE,LAST_PROCESSED_DATE,WEEK_END_PROCESSING)
AS
  SELECT AUTO_TRANS_UNIQUE_ID,
    SOURCE_ACCOUNT,
    CASE
      WHEN source.ACCOUNT_CATEGORY='1'
      THEN
        (SELECT account_no FROM deposit WHERE account_id=at.source_account
        )
      ELSE
        (SELECT account_no
        FROM loan_account_vw
        WHERE loanaccount_id=at.source_account
        )
    END SOURCE_ACC_NO,
    SOURCE.INSTITUTION_ID SOURCE_INST_NO,
    SOURCE.contract_type_id SOURCE_ACC_TYPE_ID,
    TARGET_ACCOUNT,
    CASE
      WHEN target.ACCOUNT_CATEGORY='1'
      THEN
        (SELECT account_no FROM deposit WHERE account_id=at.target_account
        )
      ELSE
        (SELECT account_no
        FROM loan_account_vw
        WHERE loanaccount_id=at.target_account
        )
    END TARGET_ACC_NO,
    TARGET.INSTITUTION_ID TARGET_INST_NO,
    TARGET.contract_TYPE_ID TARGET_ACC_TYPE_ID,
    TRANSFER_MONEY,
    CASE
      WHEN instr(TRANSFER_FREQUENCY,'#')=0
      THEN TRANSFER_FREQUENCY
      ELSE SUBSTR(TRANSFER_FREQUENCY,0,instr(TRANSFER_FREQUENCY,'#')-1)
    END TRANSFER_FREQUENCY,
    NUMBER_OF_TRANSFERS,
    START_DATE,
    END_DATE,
    AUTOMATIC_TRANSFER,
    IS_VARIABLE_AMOUNT,
    IS_ACTIVE,
    AUTO_RETRIVAL_COUNT,
    MAX_AUTO_RETRY_COUNT,
    NEXT_RETRIVALDATE,
    AT.NEXT_PROCESSING_DATE,
    AT.LAST_PROCESSED_DATE,
    AT.WEEK_END_PROCESSING
  FROM AUTOMATIC_TRANSFER_INSTRUCTION AT,
    ACCOUNT SOURCE,
    ACCOUNT TARGET
  WHERE AT.SOURCE_ACCOUNT=SOURCE.ACCOUNT_ID
  AND AT.TARGET_ACCOUNT  =TARGET.ACCOUNT_ID; 
  
  