CREATE TABLE BANK_USERS ( 
  	ID         NUMBER(20,5),
	USER_ID   	VARCHAR2(30) NOT NULL,
	USER_NAME     	VARCHAR2(50) NULL 
	);
	
ALTER TABLE PERSON ADD IS_MINOR NUMBER(2);

alter table DEPOSIT add TIMES_OD_MTD NUMBER(10) DEFAULT 0;

alter table DEPOSIT add TIMES_NSF_MTD NUMBER(10) DEFAULT 0;

alter table DEPOSIT add OD_FEE_MTD NUMBER(10,5) DEFAULT 0;
alter table DEPOSIT add RETURNED_ITEM_FEE_MTD NUMBER(10,5) DEFAULT 0;
alter table DEPOSIT add NO_DAYS_OVERDRAWN_MTD NUMBER(10) DEFAULT 0;
alter table DEPOSIT add REFUNDED_CHARGES_MTD NUMBER(10,5) DEFAULT 0;

ALTER TABLE automatic_transfer_instruction  ADD ( NEXT_PROCESSING_DATE DATE);

ALTER TABLE automatic_transfer_instruction  ADD (EFFECTIVE_START_DATE DATE);

alter table NSF_OD_DAU_HISTORY add UNIQUE_ID NUMBER(10);

CREATE SEQUENCE NSF_OD_HISTORY_SEQ MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 100 ORDER NOCYCLE ;

ALTER TABLE INTEREST_INFO_LAST_12_PERIODS DROP constraint IINFOLAST12P_PK;

ALTER TABLE INTEREST_INFO_LAST_12_PERIODS ADD UNIQUE_ID NUMBER(10);
ALTER TABLE INTEREST_INFO_LAST_12_PERIODS ADD PRIMARY KEY (UNIQUE_ID);
CREATE SEQUENCE INTEREST_INFO_SEQ MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 100 ORDER NOCYCLE ;

--index commented because it is not availale suggested by kiran.
--DROP INDEX IINFOLAST12P_PK;
