
CREATE TABLE DEPOSIT_MODE
  (
    "UNIQUE_ID" NUMBER(3,0) NOT NULL ENABLE,
    "MODE_NAME" VARCHAR2(1000 BYTE) NOT NULL ENABLE,
    "AUTOMATIC" NUMBER(1,0) NOT NULL ENABLE,
    CONSTRAINT "DEPOSIT_MODE_PK" PRIMARY KEY ("UNIQUE_ID"));

CREATE TABLE "REG_CC_HOLD_TYPE"
  (
    "UNIQUE_ID"             NUMBER(2,0) NOT NULL ENABLE,
    "HOLD_TYPE_DESCRIPTION" VARCHAR2(30 BYTE) NOT NULL ENABLE,
    "REASON_AVAILABLE"      NUMBER(1,0) NOT NULL ENABLE,
    "DETAILS_REQUIRED"      VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "LOW_HOLD_AMOUNT"       NUMBER(20,5) NOT NULL ENABLE,
    "HIGH_HOLD_AMOUNT"      NUMBER(20,5) NOT NULL ENABLE,
    "HOLD_DAYS"             NUMBER(1,0) NOT NULL ENABLE,
    "TYPE"                  VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "PERIOD_BASIS"          VARCHAR2(20 BYTE),
    CONSTRAINT "REG_CC_HOLD_TYPE_PK" PRIMARY KEY ("UNIQUE_ID") );

CREATE TABLE "REG_CC_HOLD_REASONS"
  (
    "UNIQUE_ID"        NUMBER(2,0) NOT NULL ENABLE,
    "DESCRIPTION"      VARCHAR2(120 BYTE) NOT NULL ENABLE,
    "DETAILS_REQUIRED" NUMBER(1,0) NOT NULL ENABLE,
    CONSTRAINT "REG_CC_HOLD_REASONS_PK" PRIMARY KEY ("UNIQUE_ID"));

CREATE TABLE "REG_CC_HOLD_REASON_MAPPING"
  (
    "UNIQUE_ID"       NUMBER(3,0) NOT NULL ENABLE,
    "DEPOSIT_MODE_ID" NUMBER(2,0) NOT NULL ENABLE,
    "HOLD_TYPE_ID"    NUMBER(2,0) NOT NULL ENABLE,
    "REASON_ID"       VARCHAR2(20 BYTE),
    CONSTRAINT "REG_CC_HOLD_REASON_MAPPIN_PK" PRIMARY KEY ("UNIQUE_ID", "DEPOSIT_MODE_ID", "HOLD_TYPE_ID"), 
    CONSTRAINT "REG_CC_HOLD_REASON_MAPPIN_FK1" FOREIGN KEY ("DEPOSIT_MODE_ID") REFERENCES "DEPOSIT_MODE" ("UNIQUE_ID"),
    CONSTRAINT "REG_CC_HOLD_REASON_MAPPIN_FK2" FOREIGN KEY ("HOLD_TYPE_ID") REFERENCES "REG_CC_HOLD_TYPE" ("UNIQUE_ID") 
  );

CREATE SEQUENCE "REG_CC_HOLD_SEQ" MINVALUE 1 MAXVALUE 1000 INCREMENT BY 1 START WITH 1 CACHE 100 NOORDER NOCYCLE ;

