INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (065,(SELECT unique_id FROM entry_type WHERE ID='1901'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (265,(SELECT unique_id FROM entry_type WHERE ID='1801'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_PRINCIPAL_BALANCE=1 WHERE POSTING_RULE_ID=8865;

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (065,(SELECT unique_id FROM entry_type WHERE ID='1917'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (265,(SELECT unique_id FROM entry_type WHERE ID='1817'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_AMORTIZED_BALANCE=1 WHERE POSTING_RULE_ID=8865;

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (065,(SELECT unique_id FROM entry_type WHERE ID='1923'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (265,(SELECT unique_id FROM entry_type WHERE ID='1823'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_ACCRUED_INT_NET=1 WHERE POSTING_RULE_ID=8865;

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (065,(SELECT unique_id FROM entry_type WHERE ID='1905'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (265,(SELECT unique_id FROM entry_type WHERE ID='1805'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_INTEREST_PAID=1 WHERE POSTING_RULE_ID=8865;

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (065,(SELECT unique_id FROM entry_type WHERE ID='1932'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (265,(SELECT unique_id FROM entry_type WHERE ID='1832'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_PRINCIPAL_DUE=1 WHERE POSTING_RULE_ID=8865;

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (065,(SELECT unique_id FROM entry_type WHERE ID='1933'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (265,(SELECT unique_id FROM entry_type WHERE ID='1833'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_INTEREST_DUE=1 WHERE POSTING_RULE_ID=8865;

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (065,(SELECT unique_id FROM entry_type WHERE ID='1946'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (265,(SELECT unique_id FROM entry_type WHERE ID='1846'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_AH_BALANCE=1 WHERE POSTING_RULE_ID=8865;

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (065,(SELECT unique_id FROM entry_type WHERE ID='1906'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (265,(SELECT unique_id FROM entry_type WHERE ID='1806'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_CREDIT_LIFE_BAL=1 WHERE POSTING_RULE_ID=8865;

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (065,(SELECT unique_id FROM entry_type WHERE ID='1904'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (265,(SELECT unique_id FROM entry_type WHERE ID='1804'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_OTHER_FEE_DUE=1 WHERE POSTING_RULE_ID=8865;

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (065,(SELECT unique_id FROM entry_type WHERE ID='1949'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (265,(SELECT unique_id FROM entry_type WHERE ID='1849'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_PAY_OFF_ACR_INT=1 WHERE POSTING_RULE_ID=8865;

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (065,(SELECT unique_id FROM entry_type WHERE ID='1950'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (265,(SELECT unique_id FROM entry_type WHERE ID='1850'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_SERVICE_FEE_PAID=1 WHERE POSTING_RULE_ID=8865;

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (065,(SELECT unique_id FROM entry_type WHERE ID='1954'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (265,(SELECT unique_id FROM entry_type WHERE ID='1854'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_SERVICE_FEE_NET=1 WHERE POSTING_RULE_ID=8865;

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (065,(SELECT unique_id FROM entry_type WHERE ID='1860'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (265,(SELECT unique_id FROM entry_type WHERE ID='1960'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_GP_PORTION_PRINCIPAL=1 WHERE POSTING_RULE_ID=8865;

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (065,(SELECT unique_id FROM entry_type WHERE ID='1980'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (265,(SELECT unique_id FROM entry_type WHERE ID='1880'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_YIELD_AMT=1 WHERE POSTING_RULE_ID=8865;

UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_DATE_LAST_ACTIVITY=1 WHERE POSTING_RULE_ID=8865;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_PARTIAL_PAYMENT=1 WHERE POSTING_RULE_ID=8865;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_DATE_NEXT_DUE=1 WHERE POSTING_RULE_ID=8865;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_PRINCIPAL_PAID_TO_DATE=1 WHERE POSTING_RULE_ID=8865;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_INTEREST_PAID_TO_DATE=1 WHERE POSTING_RULE_ID=8865;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_BILL=1 WHERE POSTING_RULE_ID=8865;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_PRNCP_DUE_DATE=1 WHERE POSTING_RULE_ID=8865;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_INT_DUE_DATE=1 WHERE POSTING_RULE_ID=8865;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_SBAStatus=1 WHERE POSTING_RULE_ID=8865;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_GP_PORTION_PRINCIPAL=1 WHERE POSTING_RULE_ID=8865;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_GP_CURRENT_BALANCE=1 WHERE POSTING_RULE_ID=8865;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_GP_PORTION_INTEREST=1 WHERE POSTING_RULE_ID=8865;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_GP_PORTION_FEE=1 WHERE POSTING_RULE_ID=8865;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_GP_PORTION_PAYMENT=1 WHERE POSTING_RULE_ID=8865;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_YIELD_AMT=1 WHERE POSTING_RULE_ID=8865;
