 INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(65, '065', 0, 265, null, 'Bankruptcy Participation Event', '1');
INSERT INTO loan_event_type(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(265, '265', 1, 65, null, 'Bankruptcy Participation Event Reversal', '1');

INSERT INTO ENTRY_TYPE(UNIQUE_ID,ID,INSTITUTION_ID,DEBIT_OR_CREDIT,DESCRIPTION,ACCOUNT_CATEGORY,POSTING_SEQUENCE,IS_REVERSAL)
VALUES(8865, '8865',NULL, '0', 'Bankruptcy Participation Event', 2, NULL, '0');

ALTER TABLE LOAN_ENTRY_POSTING_RULE ADD  AFF_BANKRUPTCY_PARTCI_EVENT NUMBER(20) DEFAULT 0;
 INSERT INTO LOAN_ENTRY_POSTING_RULE(POSTING_RULE_ID, AFF_BANKRUPTCY_PARTCI_EVENT) VALUES(8865, 1);
 INSERT INTO LOAN_ENTRY_TYPE(ENTRY_TYPE_ID, ENTRY_NAME, REVERSAL_ENTRY_TYPE_ID, POSTING_RULE_ID) VALUES(8865,8865,8865,8865);
  
insert into loan_event_entry_type_link values(65,8865);
