

--Event to Entry Link
--End Day
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','99999');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','1918');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','1908');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','1910');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','1911');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','1912');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','1913');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','1914');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','1915');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','1807');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','1822');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','1823');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','1824');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','1826');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','1827');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','1828');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','1829');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','1831');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','1917');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','1925');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','1932');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','1933');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','1934');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','1935');


---Init fund
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('1','1801');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('1','1802');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('1','1803');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('1','1804');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('1','1805');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('1','1806');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('1','1918');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('1','1908');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('1','1809');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('1','1910');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('1','1911');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('1','1912');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('1','1913');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('1','1914');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('1','1915');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('1','1816');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('1','1817');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('1','1807');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('1','1819');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('1','1823');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('1','1832');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('1','1833');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('1','1834');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('1','1835');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('1','8881');


--------Reg Pymnt
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('110','1901');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('110','1902');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('110','1904');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('110','1905');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('110','1906');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('110','1917');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('110','1907');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('110','1923');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('110','1932');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('110','1933');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('110','1935');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('110','8882');

---pay off

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('15','1901');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('15','1902');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('15','1903');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('15','1904');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('15','1905');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('15','1906');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('15','1918');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('15','1908');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('15','1910');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('15','1911');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('15','1912');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('15','1913');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('15','1914');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('15','1915');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('15','1917');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('15','1907');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('15','1923');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('15','1932');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('15','1933');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('15','1934');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('15','1935');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('15','8883');

-- Late Charge Payment 
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('16','1901');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('16','1902');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('16','1917');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('16','1907');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('16','8816');

-- Curtailment True Payment
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('121','1901');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('121','1917');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('121','8820');


-- Curtailment Non True Payment
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('120','1901');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('120','1917');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('120','8884');

-- Interest Payment
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('13','1905');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('13','1923');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('13','1933');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('13','8813');

-- Escrow  Payment
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('14','1903');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('14','1934');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('14','8814');

-- Life AH Payment
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('17','1906');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('17','1935');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('17','8817');

-- Credit Memo Principal Payment
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('31','1901');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('31','1917');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('31','8831');

-- Credit Memo LatCharge Payment
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('32','1902');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('32','8832');

-- Credit Memo Escrow Payment
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('33','1903');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('33','8833');

-- Credit Memo Other Fee Payment
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('34','1904');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('34','8834');


-- Debit Memo Principal Payment
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('21','1801');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('21','1817');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('21','8821');

-- Debit Memo LatCharge Payment
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('22','1802');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('22','8822');

-- Debit Memo Escrow Payment
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('23','1803');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('23','8823');

-- Debit Memo Other Fee Payment
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('24','1804');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('24','8824');

-- Origination Fee Payment
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('18','1936');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('18','8818');

----Interest Paid  -Debit Adjustment
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('25','1805');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('25','1823');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('25','8825');

-- Interest Paid  -Credit Adjustment
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('35','1905');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('35','1923');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('35','8835');

