
--Posting Rules
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_PRINCIPAL_BALANCE=1 WHERE POSTING_RULE_ID = 1;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_COLL_LATE_CHARGE=1 WHERE POSTING_RULE_ID = 2;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_ESCROW_BALANCE=1 WHERE POSTING_RULE_ID = 3;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_OTHER_FEE_DUE=1 WHERE POSTING_RULE_ID = 4;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_INTEREST_PAID=1 WHERE POSTING_RULE_ID = 5;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_AHLIFE_BALANCE=1 WHERE POSTING_RULE_ID = 6;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_UNCOLL_LATE_CHARGE=1 WHERE POSTING_RULE_ID = 7;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_ACC_HEALTH_REBATE=1 WHERE POSTING_RULE_ID = 8;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_UNAPPLIED_FUND=1 WHERE POSTING_RULE_ID = 9;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_BANK_REBATE=1 WHERE POSTING_RULE_ID = 10;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_COLLATERAL_INS_REBATE=1 WHERE POSTING_RULE_ID = 11;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_SP_RES1_REBATE=1 WHERE POSTING_RULE_ID = 12;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_SP_RES2_REBATE=1 WHERE POSTING_RULE_ID = 13;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_DEALER_REBATE=1 WHERE POSTING_RULE_ID = 14;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_DLR_HB_REBATE=1 WHERE POSTING_RULE_ID = 15;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_ORIG_LOAN_BALANCE=1 WHERE POSTING_RULE_ID = 16;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_AMORTIZED_BALANCE=1 WHERE POSTING_RULE_ID = 17;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_CREDIT_LIFE_REBATE=1 WHERE POSTING_RULE_ID = 18;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_WAIVED_LATE_CHARGE=1  WHERE POSTING_RULE_ID = 19;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_LAST_TRAN_AMOUNT=1  WHERE POSTING_RULE_ID = 20;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_DAILY_ACC_AMOUNT=1  WHERE POSTING_RULE_ID = 21;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_ACCRUED_INTEREST=1  WHERE POSTING_RULE_ID = 22;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_ACCRUED_INT_NET=1  WHERE POSTING_RULE_ID = 23;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_ACCUMULATED_INT=1  WHERE POSTING_RULE_ID = 24;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_PAST_DUE_AMOUNT=1  WHERE POSTING_RULE_ID = 25;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_DLR_DIALY_ACCR_AMOUNT=1  WHERE POSTING_RULE_ID = 26;

UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_DLR_ACCR_INT=1  WHERE POSTING_RULE_ID = 28;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_SCH_PAYMENT_AMOUNT=1  WHERE POSTING_RULE_ID = 29;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_LAST_STMT_BAL=1  WHERE POSTING_RULE_ID = 30;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_NEW_SCH_PAYMENT_AMOUNT=1  WHERE POSTING_RULE_ID = 31;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_PRINCIPAL_DUE=1  WHERE POSTING_RULE_ID = 32;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_INTEREST_DUE=1  WHERE POSTING_RULE_ID = 33;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_ESCROW_DUE=1  WHERE POSTING_RULE_ID = 34;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_AHLIFE_DUE=1  WHERE POSTING_RULE_ID = 35;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_ORIGNATION_FEE_PAID=1  WHERE POSTING_RULE_ID = 36;




-- Initial Fund

UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_LAST_ACTIVITY	=1  WHERE POSTING_RULE_ID = 8881;																																																																																																																																																																																																																																																													
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_NEXT_DUE	=1  WHERE POSTING_RULE_ID = 8881;																																																																																																																																																																																																																																																													
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_PAYMENTS_MADE	=1  WHERE POSTING_RULE_ID = 8881;																																																																																																																																																																																																																																																													
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_RETURNED_CHECKS	=1  WHERE POSTING_RULE_ID = 8881;																																																																																																																																																																																																																																																													
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LOAN_STATUS	=1  WHERE POSTING_RULE_ID = 8881;																																																																																																																																																																																																																																																													
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_PRINCIPAL_PAID_TO_DATE	=1  WHERE POSTING_RULE_ID = 8881;																																																																																																																																																																																																																																																													
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DISC_INT_REM_TERM	=1  WHERE POSTING_RULE_ID = 8881;																																																																																																																																																																																																																																																													
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DISC_INT_REM_TERM	=1  WHERE POSTING_RULE_ID = 8881;																																																																																																																																																																																																																																																													
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_INTEREST_PAID_TO_DATE	=1  WHERE POSTING_RULE_ID = 8881;																																																																																																																																																																																																																																																													
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_PARTIAL_PAYMENT	=1  WHERE POSTING_RULE_ID = 8881;																																																																																																																																																																																																																																																													
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_FUTURE_PAYMENT_COUNT	=1  WHERE POSTING_RULE_ID = 8881;																																																																																																																																																																																																																																																													
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_INIT_FUND_DATE	=1  WHERE POSTING_RULE_ID = 8881;																																																																																																																																																																																																																																																													
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_STMT_BAL	=1  WHERE POSTING_RULE_ID = 8881;																																																																																																																																																																																																																																																													
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_SCHD_PYMNT_DUE_DATE	=1  WHERE POSTING_RULE_ID = 8881;																																																																																																																																																																																																																																																													



-- Regular Payment 

UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_BILL	=1  WHERE POSTING_RULE_ID = 8882;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_LAST_ACTIVITY	=1  WHERE POSTING_RULE_ID = 8882;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_NEXT_DUE	=1  WHERE POSTING_RULE_ID = 8882;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_PAYMENTS_MADE	=1  WHERE POSTING_RULE_ID = 8882;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_PRINCIPAL_PAID_TO_DATE	=1  WHERE POSTING_RULE_ID = 8882;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_TRAN_AMOUNT	=1  WHERE POSTING_RULE_ID = 8882;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_PARTIAL_PAYMENT	=1  WHERE POSTING_RULE_ID = 8882;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_INT_DUE_DATE	=1  WHERE POSTING_RULE_ID = 8882;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_PRNCP_DUE_DATE	=1  WHERE POSTING_RULE_ID = 8882;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_FUTURE_PAYMENT_COUNT	=1  WHERE POSTING_RULE_ID = 8882;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_PYMNT_AMOUNT	=1  WHERE POSTING_RULE_ID = 8882;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_PAYOUT_CODE	=1  WHERE POSTING_RULE_ID = 8882;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_CLOSED	=1  WHERE POSTING_RULE_ID = 8882;			
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_LOAN_STATUS=1  WHERE POSTING_RULE_ID = 8882;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_DTNXTDUBFRPSTNG=1  WHERE POSTING_RULE_ID = 8882;


--loan payoff
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_BILL	=1  WHERE POSTING_RULE_ID = 8883;				
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_LAST_ACTIVITY	=1  WHERE POSTING_RULE_ID = 8883;				
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_PAYMENTS_MADE	=1  WHERE POSTING_RULE_ID = 8883;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LOAN_STATUS	=1  WHERE POSTING_RULE_ID = 8883;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_PRINCIPAL_PAID_TO_DATE	=1  WHERE POSTING_RULE_ID = 8883;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_TRAN_AMOUNT	=1  WHERE POSTING_RULE_ID = 8883;		
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_PYMNT_AMOUNT	=1  WHERE POSTING_RULE_ID = 8883;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_PAYOUT_CODE	=1  WHERE POSTING_RULE_ID = 8883;		
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_CLOSED	=1  WHERE POSTING_RULE_ID = 8883;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_DTNXTDUBFRPSTNG=1  WHERE POSTING_RULE_ID = 8883;


-- End Day 
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_BILL=1  WHERE POSTING_RULE_ID = 9999;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_DATE_LAST_ACTIVITY=1 WHERE POSTING_RULE_ID = 9999;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_LOAN_STATUS=1 WHERE POSTING_RULE_ID = 9999;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_DISC_INT_REM_TERM=1 WHERE POSTING_RULE_ID = 9999;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_ACCRUEDTO_DATE	=1  WHERE POSTING_RULE_ID = 9999;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_AHINS_DUE_DATE	=1  WHERE POSTING_RULE_ID = 9999;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_PAST_DUE_CUNTERS =1  WHERE POSTING_RULE_ID = 9999;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_LAST_STMT_BAL=1 WHERE POSTING_RULE_ID = 9999;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_DAILY_ACC_AMOUNT=1 WHERE POSTING_RULE_ID = 9999;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_SCHD_PYMNT_DUE_DATE=1 WHERE POSTING_RULE_ID = 9999;


-- Late Charge 
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_LAST_ACTIVITY =1  WHERE POSTING_RULE_ID = 8816;				
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_NEXT_DUE =1  WHERE POSTING_RULE_ID = 8816;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_PAYMENTS_MADE =1  WHERE POSTING_RULE_ID = 8816;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_TRAN_AMOUNT =1  WHERE POSTING_RULE_ID = 8816;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_PARTIAL_PAYMENT =1  WHERE POSTING_RULE_ID = 8816;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_PYMNT_AMOUNT =1  WHERE POSTING_RULE_ID = 8816;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_DTNXTDUBFRPSTNG=1  WHERE POSTING_RULE_ID = 8816;

--Curtailment True
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_LAST_ACTIVITY =1  WHERE POSTING_RULE_ID = 8820;				
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LOAN_STATUS =1  WHERE POSTING_RULE_ID = 8820;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_TRAN_AMOUNT =1  WHERE POSTING_RULE_ID = 8820;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_CURT_AMOUNT =1  WHERE POSTING_RULE_ID = 8820;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_PYMNT_AMOUNT =1  WHERE POSTING_RULE_ID = 8820;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_PAYOUT_CODE =1  WHERE POSTING_RULE_ID = 8820;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_CLOSED =1  WHERE POSTING_RULE_ID = 8820;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_DTNXTDUBFRPSTNG=1  WHERE POSTING_RULE_ID = 8820;

--Curtailment Non True
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_BILL=1  WHERE POSTING_RULE_ID = 8884;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_LAST_ACTIVITY =1  WHERE POSTING_RULE_ID = 8884;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_NEXT_DUE =1  WHERE POSTING_RULE_ID = 8884;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_PAYMENTS_MADE =1  WHERE POSTING_RULE_ID = 8884;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LOAN_STATUS =1  WHERE POSTING_RULE_ID = 8884;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_PRINCIPAL_PAID_TO_DATE =1  WHERE POSTING_RULE_ID = 8884;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_TRAN_AMOUNT =1  WHERE POSTING_RULE_ID = 8884;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_PARTIAL_PAYMENT =1  WHERE POSTING_RULE_ID = 8884;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_CURT_AMOUNT =1  WHERE POSTING_RULE_ID = 8884;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_PYMNT_AMOUNT =1  WHERE POSTING_RULE_ID = 8884;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_PAYOUT_CODE =1  WHERE POSTING_RULE_ID = 8884;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_CLOSED =1  WHERE POSTING_RULE_ID = 8884;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_DTNXTDUBFRPSTNG=1  WHERE POSTING_RULE_ID = 8884;

--Interest Payment 
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_BILL=1  WHERE POSTING_RULE_ID = 8813;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_LAST_ACTIVITY =1  WHERE POSTING_RULE_ID = 8813;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_TRAN_AMOUNT =1  WHERE POSTING_RULE_ID = 8813;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_PYMNT_AMOUNT =1  WHERE POSTING_RULE_ID = 8813;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_DTNXTDUBFRPSTNG=1  WHERE POSTING_RULE_ID = 8813;

--Escrow Payment 
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_BILL=1  WHERE POSTING_RULE_ID = 8814;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_LAST_ACTIVITY =1  WHERE POSTING_RULE_ID = 8814;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_TRAN_AMOUNT =1  WHERE POSTING_RULE_ID = 8814;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_PYMNT_AMOUNT =1  WHERE POSTING_RULE_ID = 8814;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_DTNXTDUBFRPSTNG=1  WHERE POSTING_RULE_ID = 8814;

--Life AH Payment 
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_BILL=1  WHERE POSTING_RULE_ID = 8817;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_LAST_ACTIVITY =1  WHERE POSTING_RULE_ID = 8817;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_TRAN_AMOUNT =1  WHERE POSTING_RULE_ID = 8817;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_PYMNT_AMOUNT =1  WHERE POSTING_RULE_ID = 8817;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_DTNXTDUBFRPSTNG=1  WHERE POSTING_RULE_ID = 8817;

--Creidt Memo Principal Payment 
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_LAST_ACTIVITY =1  WHERE POSTING_RULE_ID = 8821;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_TRAN_AMOUNT =1  WHERE POSTING_RULE_ID = 8821;

--Creidt Memo Late Charge Payment 
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_LAST_ACTIVITY =1  WHERE POSTING_RULE_ID = 8822;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_TRAN_AMOUNT =1  WHERE POSTING_RULE_ID = 8822;

--Creidt Memo Escrow Payment 
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_LAST_ACTIVITY =1  WHERE POSTING_RULE_ID = 8823;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_TRAN_AMOUNT =1  WHERE POSTING_RULE_ID = 8823;

--Creidt Memo Other Fee Payment 
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_LAST_ACTIVITY =1  WHERE POSTING_RULE_ID = 8824;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_TRAN_AMOUNT =1  WHERE POSTING_RULE_ID = 8824;


--Debit Memo Principal Payment 
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_LAST_ACTIVITY =1  WHERE POSTING_RULE_ID = 8831;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_TRAN_AMOUNT =1  WHERE POSTING_RULE_ID = 8831;

--Debit Memo Late Charge Payment 
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_LAST_ACTIVITY =1  WHERE POSTING_RULE_ID = 8832;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_TRAN_AMOUNT =1  WHERE POSTING_RULE_ID = 8832;

--Debit Memo Escrow Payment 
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_LAST_ACTIVITY =1  WHERE POSTING_RULE_ID = 8833;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_TRAN_AMOUNT =1  WHERE POSTING_RULE_ID = 8833;

--Debit Memo Other Fee Payment 
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_LAST_ACTIVITY =1  WHERE POSTING_RULE_ID = 8834;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_TRAN_AMOUNT =1  WHERE POSTING_RULE_ID = 8834;

--Origination Fee Payment
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_LAST_ACTIVITY =1  WHERE POSTING_RULE_ID = 8836;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_TRAN_AMOUNT =1  WHERE POSTING_RULE_ID = 8836;


--Interest Paid  -Debit Adjustment
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_LAST_ACTIVITY =1  WHERE POSTING_RULE_ID = 8837;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_TRAN_AMOUNT =1  WHERE POSTING_RULE_ID = 8837;

--Interest Paid  -Credit Adjustment
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_LAST_ACTIVITY =1  WHERE POSTING_RULE_ID = 8838;
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_TRAN_AMOUNT =1  WHERE POSTING_RULE_ID = 8838;


--CREDIT MEMO LATE CHARGE
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (32,'032',0, 232,35);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (232,'232',1,32,10);					


--CREDIT MEMO ESCROW
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (33,'033',0, 233,34);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (233,'233',1,33,11);				
				

--CREDIT MEMO OTHER FEE
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (34,'034',0, 234,33);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (234,'234',1,34,12);	
				
--Advance Payment
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (5,'005',0, 205,2);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (205,'205',1,5,21);
				
--Future Payment
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (112,'112',2, 312,null);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (312,'312',2,112,null);				
	
--LOAN EXTENSION
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (42,'042',2, 242,null);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (242,'242',2,42,null);	
				
--OTHER FEE
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (19,'019',0, 219,31);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (219,'219',1,19,14);	
		
-- ORIGINATION FEE PAYMENT				
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (18,'018',0, 218,NULL);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (218,'218',1,18,NULL);
				
--Interest Paid  -Debit Adjustment
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (25,'025',0, 225,NULL);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (225,'225',1,25,NULL);

--Interest Paid  -Credit Adjustment
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (35,'035',0,235,NULL);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (235,'235',1,35,NULL);					

-- ESCROW DISBURSEMENT 				
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (40,'040',0, 240,NULL);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (240,'240',1,40,NULL);				
				
-- Life AH DISBURSEMENT 				
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (41,'041',0, 241,NULL);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (241,'241',1,41,NULL);	
				


