CREATE TABLE LOAN_EVENT_TYPE (    
    EVENT_TYPE_ID  				NUMBER(10,0) NOT NULL,
    CORESOFT_EVENT_CODE        	VARCHAR2(10) NOT NULL,
    EVENT_GROUP                 NUMBER(5,0),
    REVERSAL_EVENT_TYPE_ID      NUMBER(10,0),
    POSTING_ORDER               NUMBER(10,0),
    DESCRIPTION                 VARCHAR2(200),
    CONSTRAINT LOAN_EVENT_TYPE_PRIMARYK PRIMARY KEY(EVENT_TYPE_ID)
);

	
DROP TABLE LOAN_ENTRY_TYPE;

CREATE TABLE LOAN_ENTRY_TYPE (     
    ENTRY_TYPE_ID       		NUMBER(10,0) NOT NULL,
    ENTRY_NAME		  			NUMBER(10,0) NOT NULL,
    REVERSAL_ENTRY_TYPE_ID		NUMBER(10,0) NOT NULL,
    POSTING_RULE_ID             NUMBER(10,0) NOT NULL,
    CONSTRAINT LOAN_ENTRY_TYPE_PRIMARYK PRIMARY KEY(ENTRY_TYPE_ID)
);



CREATE TABLE LOAN_ENTRY_POSTING_RULE(
   	POSTING_RULE_ID    NUMBER(10,0) NOT NULL,
   	
    AFFECTS_DATE_LAST_ACTIVITY NUMBER(1) DEFAULT 0,
	AFFECTS_ORIG_LOAN_BALANCE NUMBER(1) DEFAULT 0,
	AFFECTS_PRINCIPAL_BALANCE NUMBER(1) DEFAULT 0,
	AFFECTS_PRINCIPAL_DUE NUMBER(1) DEFAULT 0,
	AFFECTS_INTEREST_DUE NUMBER(1) DEFAULT 0,
	
	AFFECTS_ESCROW_DUE NUMBER(1) DEFAULT 0,
	AFFECTS_ESCROW_BALANCE NUMBER(1) DEFAULT 0,
	AFFECTS_AHLIFE_DUE NUMBER(1) DEFAULT 0,
    AFFECTS_AHLIFE_BALANCE NUMBER(1) DEFAULT 0,
    AFFECTS_BANK_REBATE NUMBER(1) DEFAULT 0,    
	
    AFFECTS_CREDIT_LIFE_REBATE NUMBER(1) DEFAULT 0,    
	AFFECTS_ACC_HEALTH_REBATE NUMBER(1) DEFAULT 0,
    AFFECTS_COLLATERAL_INS_REBATE NUMBER(1) DEFAULT 0,
    AFFECTS_SP_RES1_REBATE NUMBER(1) DEFAULT 0,
    AFFECTS_SP_RES2_REBATE NUMBER(1) DEFAULT 0,
    
    AFFECTS_DEALER_REBATE NUMBER(1) DEFAULT 0,
    AFFECTS_DLR_DIALY_ACCR_AMOUNT NUMBER(1) DEFAULT 0,
    AFFECTS_DLR_ACCR_INT NUMBER(1) DEFAULT 0,
    AFFECTS_DLR_HB_REBATE NUMBER(1) DEFAULT 0,
	
    AFFECTS_OTHER_FEE_DUE NUMBER(1) DEFAULT 0,    
    AFFECTS_UNAPPLIED_FUND NUMBER(1) DEFAULT 0,
	AFFECTS_PARTIAL_PAYMENT NUMBER(1) DEFAULT 0,
	AFFECTS_COLL_LATE_CHARGE NUMBER(1) DEFAULT 0,
	AFFECTS_UNCOLL_LATE_CHARGE NUMBER(1)DEFAULT 0,
	
	AFFECTS_WAIVED_LATE_CHARGE NUMBER(1) DEFAULT 0,
	AFFECTS_DATE_NEXT_DUE NUMBER(1) DEFAULT 0,
	AFFECTS_PAYMENTS_MADE NUMBER(1) DEFAULT 0,
	AFFECTS_RETURNED_CHECKS NUMBER(1) DEFAULT 0,
    AFFECTS_ACCRUED_INTEREST NUMBER(1)DEFAULT 0,       
    
    AFFECTS_LOAN_STATUS NUMBER(1) DEFAULT 0,
    AFFECTS_PAYOUT_CODE NUMBER(1) DEFAULT 0,
    AFFECTS_DATE_CLOSED NUMBER(1) DEFAULT 0,
	AFFECTS_PRINCIPAL_PAID_TO_DATE NUMBER(1) DEFAULT 0,
	
	AFFECTS_INTEREST_PAID_TO_DATE NUMBER(1) DEFAULT 0,
	AFFECTS_FUTURE_PAYMENT_COUNT NUMBER(1) DEFAULT 0,
	AFFECTS_LAST_STMT_BAL NUMBER(1) DEFAULT 0,
	AFFECTS_ACCRUED_INT_NET NUMBER(1) DEFAULT 0,
	
	AFFECTS_LAST_TRAN_AMOUNT NUMBER(1) DEFAULT 0,
	AFFECTS_AMORTIZED_BALANCE NUMBER(1) DEFAULT 0,
	AFFECTS_DAILY_ACC_AMOUNT NUMBER(1) DEFAULT 0,
	AFFECTS_ACCUMULATED_INT NUMBER(1) DEFAULT 0,
	AFFECTS_PAST_DUE_AMOUNT NUMBER(1) DEFAULT 0,
	
	AFFECTS_SCH_PAYMENT_AMOUNT NUMBER(1) DEFAULT 0,
	AFFECTS_NEW_SCH_PAYMENT_AMOUNT NUMBER(1) DEFAULT 0,
	AFFECTS_INTEREST_PAID NUMBER(1) DEFAULT 0,
	AFFECTS_BILL NUMBER(1) DEFAULT 0,
	AFFECTS_DISC_INT_REM_TERM NUMBER(1) DEFAULT 0,
	
	AFFECTS_INT_DUE_DATE NUMBER(1) DEFAULT 0,
	AFFECTS_PRNCP_DUE_DATE NUMBER(1) DEFAULT 0,
	AFFECTS_INIT_FUND_DATE NUMBER(1) DEFAULT 0,
	AFFECTS_LAST_CURT_AMOUNT NUMBER(1) DEFAULT 0,
	AFFECTS_LAST_PYMNT_AMOUNT NUMBER(1) DEFAULT 0,
	
	AFFECTS_SCHD_PYMNT_DUE_DATE NUMBER(1) DEFAULT 0,
	AFFECTS_AHINS_DUE_DATE NUMBER(1) DEFAULT 0,
	AFFECTS_ACCRUEDTO_DATE NUMBER(1) DEFAULT 0,
	AFFECTS_PAST_DUE_CUNTERS NUMBER(1) DEFAULT 0,
	AFFECTS_DTNXTDUBFRPSTNG NUMBER(1) DEFAULT 0,
	AFFECTS_ORIGNATION_FEE_PAID NUMBER(1) DEFAULT 0,
	CONSTRAINT LOANENTRY_PORULE_PRIMARYK PRIMARY KEY(POSTING_RULE_ID)
);		


ALTER TABLE LOAN_ENTRY_TYPE ADD FOREIGN KEY (POSTING_RULE_ID) REFERENCES LOAN_ENTRY_POSTING_RULE(POSTING_RULE_ID);


CREATE SEQUENCE LOAN_ENTRY_POSTING_RULE_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOMINVALUE
	NOCYCLE
	CACHE 20
	ORDER;
	
CREATE TABLE LOAN_EVENT_ENTRY_TYPE_LINK (    
    EVENT_TYPE_ID   NUMBER(10,0) NOT NULL,
    ENTRY_TYPE_ID   NUMBER(10,0) NOT NULL,     
     CONSTRAINT LEETYPELK_PK PRIMARY KEY(EVENT_TYPE_ID,ENTRY_TYPE_ID)
);
	
	
CREATE TABLE LOAN_ACCOUNT_EVENT (     
    EVENT_ID       			NUMBER(10,0) NOT NULL,
    TRAN_CODE               VARCHAR2(10) NOT NULL, 
    LOAN_EVENT_TYPE_ID      NUMBER(10,0) NOT NULL,
    ACCOUNT_ID      		VARCHAR2(30) NOT NULL,
    EFFECTIVE_DATE  		DATE NOT NULL,
    EVENT_DATE     		    DATE NOT NULL,    
    DAY_SEQ_NO              NUMBER(10,0) NULL,
    ADJUSTED_EVENT_ID       NUMBER(10,0) NULL,
    REPLACEMENT_EVENT_ID    NUMBER(10,0) NULL ,
    EXTERNAL_EVENT_ID       NUMBER(10,0),
    PARENT_EVENT_ID         NUMBER(10,0),
    POST_REASON             VARCHAR2(100),
    Event_SOURCE 			NUMBER(2,0) NULL,
    BANK_OLD_TRANCODE		VARCHAR2(10),
	DESCRIPTION             VARCHAR2(200),
	POST_DATE				DATE,
CONSTRAINT LOANACC_EVENT_PKEY PRIMARY KEY(EVENT_ID));

--ALTER TABLE LOAN_ACCOUNT_EVENT ADD FOREIGN KEY (ACCOUNT_ID) REFERENCES LOAN_ACCOUNT(ACCOUNT_ID);
ALTER TABLE LOAN_ACCOUNT_EVENT ADD FOREIGN KEY (LOAN_EVENT_TYPE_ID) REFERENCES LOAN_EVENT_TYPE(EVENT_TYPE_ID);

CREATE SEQUENCE LOAN_EVENT_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOMINVALUE
	NOCYCLE
	CACHE 20
	ORDER;
	
	
CREATE TABLE LOAN_EVENT_MAINTE_LOG_ENTRIES( 
		ENTRY_ID               NUMBER(10) NOT NULL,
		EVENT_ID       		   NUMBER(10,0) NOT NULL,
		EFFECTIVE_DATE         DATE NOT NULL,
		EVENT_DATE             DATE NOT NULL,
		USER_ID                VARCHAR2(50),
		VALUE_CLASS            VARCHAR2(100) NOT NULL,
		OLD_VALUE              VARCHAR2(350),
		NEW_VALUE              VARCHAR2(350),
		FIELD_NAME             VARCHAR2(100) NOT NULL,
		DESCRIPTION            VARCHAR2(100),
		LOG_ACTION 			   VARCHAR2(2),
CONSTRAINT LEMLENTRIES_PKEY PRIMARY KEY(ENTRY_ID));


 CREATE SEQUENCE LOAN_EVENT_LOG_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOMINVALUE
	NOCYCLE
	CACHE 20
	ORDER;
CREATE TABLE DISTRIBUTED_ENTRY (   
    UNIQUE_ID                  NUMBER(15,0) NOT NULL,
    MONETARY_EVENT_ID          NUMBER(15,0),
    AMOUNT                     NUMBER(20,6) NOT NULL,
    DISTRIBUTION_HEAD          NUMBER(10,0) NOT NULL,
    DESCRIPTION                VARCHAR2(300),
CONSTRAINT DIS_ENTRY_PKEY PRIMARY KEY(UNIQUE_ID));

CREATE SEQUENCE DISTRIBUTED_ENTRY_UID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOMINVALUE
	NOCYCLE
	CACHE 20
	ORDER;
	

CREATE TABLE LOAN_ACCOUNT_MONETARY_EVENT (  
    MONETARY_EVENT_TYPE_ID  NUMBER(10,0) NOT NULL,
    AMOUNT                      NUMBER(20,6) NOT NULL,
    CLOSING_PRINCIPAL_BAL       NUMBER(20,6) NULL,
    CLOSING_ESCROW_BAL          NUMBER(20,6) NULL,
    CLOSING_LIFE_AH_BAL         NUMBER(20,6) NULL,
    CLOSING_NXT_PYMNT_DUE_DATE  DATE NULL,
   
CONSTRAINT LOANMON_EVENT_PKEY PRIMARY KEY(MONETARY_EVENT_TYPE_ID));		


DROP TABLE LOAN_POSTBLE_ACC_HISTORY_ITEM;

DROP TABLE LOAN_ACCOUNT_DAY;

CREATE TABLE LOAN_ACCOUNT_DAY(
ACCOUNT_ID VARCHAR2(50) NOT NULL,
DAY_START DATE NOT NULL,
DAY_END  DATE NOT NULL,
OPENING_PRINCIPLE_BALANCE   NUMBER ( 15,2) default 0,
OPENING_COLLECTED_LATE_CHARGE NUMBER ( 15,2) default 0,
OPENING_INTEREST_PAID NUMBER ( 15,2) default 0,
OPENING_INTEREST_EARNED NUMBER( 15,2) default 0,
OPENING_PAST_DUE_DAYS_30_59 NUMBER(10) default 0,
OPENING_PAST_DUE_DAYS_60_89 NUMBER(10) default 0,
OPENING_PAST_DUE_DAYS_90_ABOVE NUMBER(10) default 0,
PRINCIPLE_BALANCE NUMBER ( 15,2) default 0,
COLLECTED_LATE_CHARGE NUMBER ( 15,2) default 0,
INTEREST_PAID NUMBER(15,2) default 0 ,
INTEREST_EARNED NUMBER( 15,2) default 0,
PAST_DUE_DAYS_30_59 NUMBER(10) default 0,
PAST_DUE_DAYS_60_89 NUMBER(10) default 0,
PAST_DUE_DAYS_90_ABOVE  NUMBER(10) default 0,
AGR_PRINCIPLE_BALANCE NUMBER ( 15,2) default 0,

MTD_PRINCIPLE_BALANCE NUMBER ( 15,2) default 0,
MTD_LATE_CHARGE_PAID NUMBER ( 15,2) default 0,
MTD_INTEREST_PAID NUMBER ( 15,2) default 0,
MTD_INTEREST_EARNED  NUMBER ( 15,2) default 0,
MTD_PAST_DUE_DAYS_30_59 NUMBER(10) default 0,
MTD_PAST_DUE_DAYS_60_89 NUMBER(10) default 0,
MTD_PAST_DUE_DAYS_90_ABOVE NUMBER(10) default 0,
MTD_AGR_PRINCIPLE_BALANCE NUMBER( 15,2) default 0,
YTD_PRINCIPLE_BALANCE NUMBER (15,2) default 0,
YTD_LATE_CHARGE_PAID NUMBER ( 15,2) default 0,
YTD_INTEREST_PAID NUMBER ( 15,2) default 0,
YTD_INTEREST_EARNED  NUMBER ( 15,2) default 0,
YTD_PAST_DUE_DAYS_30_59 NUMBER(10) default 0,
YTD_PAST_DUE_DAYS_60_89 NUMBER(10) default 0,
YTD_PAST_DUE_DAYS_90_ABOVE NUMBER(10) default 0,
YTD_AGR_PRINCIPLE_BALANCE NUMBER( 15,2) default 0,
CONSTRAINT LDAY_PKEY PRIMARY KEY(ACCOUNT_ID,DAY_START,DAY_END));

--ALTER TABLE LOAN_ACCOUNT_DAY ADD FOREIGN KEY (ACCOUNT_ID) REFERENCES LOAN_ACCOUNT(ACCOUNT_ID);

alter table loan_account_day add (TIME_UNIT NUMBER);

DROP TABLE BSV_TRANSACTION_TYPE;

CREATE TABLE BSV_LOAN_EVENT_TYPE(
UNIQUE_ID       NUMBER(10,0) NOT NULL,
BSV_EVENT_CODE  VARCHAR2(20) NOT NULL,
STMT_DESC       VARCHAR2(100),
ACCOUNT_TYPE_ID VARCHAR2(50) NOT NULL,
EVENT_TYPE_ID  	NUMBER(10,0)  NOT NULL,
IS_DEFAULT_TRANCODE NUMBER(2,0),
CONSTRAINT BSV_LOAN_PKEY PRIMARY KEY(UNIQUE_ID));


CREATE TABLE IPS_LOAN_EVENT_TYPE(
UNIQUE_ID       NUMBER(10,0) NOT NULL,
TRAN_CODE		VARCHAR2(20) NOT NULL,
ACCOUNT_TYPE_ID VARCHAR2(50) NOT NULL,
BSV_EVENT_TYPE_ID  	NUMBER(10,0)  NOT NULL,
CONSTRAINT IPS_LOAN_PKEY PRIMARY KEY(UNIQUE_ID));

CREATE SEQUENCE IPS_EVENT_TYPE_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOMINVALUE
	NOCYCLE
	CACHE 20
	ORDER;


ALTER TABLE IPS_LOAN_EVENT_TYPE ADD  FOREIGN KEY (BSV_EVENT_TYPE_ID) REFERENCES BSV_LOAN_EVENT_TYPE(UNIQUE_ID);
ALTER TABLE BSV_LOAN_EVENT_TYPE ADD  FOREIGN KEY (EVENT_TYPE_ID) REFERENCES LOAN_EVENT_TYPE(EVENT_TYPE_ID);


CREATE TABLE LOAN_EXCEPTION_CODE_LOOKUP(
EXCEPTION_CODE_ID VARCHAR2(6),
DESCRIPTION       VARCHAR2(200),
CONSTRAINT LACL_PKEY PRIMARY KEY(EXCEPTION_CODE_ID)); 

CREATE TABLE LACC_DAY_EXCEPTION_CODES(
UNIQUE_ID NUMBER(10),
ACCOUNT_ID VARCHAR2(20),
AS_ON_DATE DATE,
CURRENT_BUSINESS_DATE DATE,
EXCEPTION_CODE_ID VARCHAR2(6)
); 

CREATE SEQUENCE LAECODE_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOMINVALUE
	NOCYCLE
	CACHE 20
	ORDER;
	
ALTER TABLE LACC_DAY_EXCEPTION_CODES ADD  FOREIGN KEY (EXCEPTION_CODE_ID) REFERENCES LOAN_EXCEPTION_CODE_LOOKUP(EXCEPTION_CODE_ID);

CREATE TABLE LOAN_ACCOUNT_DAY_SUMMARY(
ACCOUNT_ID VARCHAR2(20),
PROCESSED_DATE DATE,
ACCRUED_INTEREST_DIFFERECE VARCHAR2(6)
); 



