CREATE OR REPLACE VIEW LOAN_ACCOUNT_VW
AS SELECT
	A.ACCOUNT_NO,
	A.INSTITUTION_ID,
	A.PRODUCT_ID,
	A.ACCOUNT_CATEGORY,
	A.ACCOUNT_TYPE_ID,
	A.BUSINESS_DATE,
	A.DATE_OPENED,
	A.CREATION_DATE,
	LA."ACCOUNT_ID",
	LA."CUSTOMER_ID",
	LA."NEXT_PAYMENT_DUE_DATE",
	LA."SCHEDULED_PAYMENT_DATE",
	LA."NEXT_SUBSIDY_AMOUNT",
	LA."PRINCIPLE_BALANCE",
	LA."ACCRUED_INTEREST",
	LA."UNAPPLIED_FUNDS",
	LA."LOSS_DRAFT_FUNDS",
	LA."LATE_FEES_DUE",
	LA."OTHER_FEES_DUE",
	LA."LOAN_STATUS",	
	LA."LAST_MAINTENANCE_DATE",
	LA."CLOSED_DATE",
	LA."OPENING_BRANCH",
	LA."PREVIOUS_OFFICER",
	LA."PAYMENTS_MADE",	
	LA."SPECIAL_MAILING_INSTRUCTIONS",
	LA."CENSUS_TRACK",
	LA."ORDER_COUPON_BOOK_NOW",
	LA."CONTINUES_ORDER_OF_COUPON_BOOK",
	LA."AMORTIZED_BALANCE",
	LA."LAST_ADDL_PRINCIPAL_DATE",
	LA."LAST_ADDL_PRINCIPAL_AMOUNT",
	LA."INTEREST_RATE_TYPE",
	LA."ACCELERATED_RATE_AT_MATURITY",
	LA."GRACE_DAYS_AT_MATURITY",	
	LA."ESCROW_ACCOUNT_ID",
	LA."NON_ACCRUAL",
	LA."ORIGINAL_MATURITY_DATE",
	LA."APPROVED_LIMIT",
	LA."SECONDARY_ACCRUED",
	LA."PARTY_ID",	
	LA."COMBINED_STATEMENT",
	LA."PARTIAL_PAYMENT",
	LA."INTEREST_PAID_YTD",
	LA."INTEREST_PAID_PYTD",
	LA."INTEREST_PAID_LTD",
	LA."LATE_FEES_PAID_YTD",
	LA."LATE_FEES_PAID_PYTD",
	LA."LATE_FEES_PAID_LTD",
	LA."POINTS_PAID_YTD",
	LA."POINTS_PAID_PYTD",
	LA."POINTS_PAID_LTD",
	LA."TAXES_PAID_YTD",
	LA."TAXES_PAID_PYTD",
	LA."TAXES_PAID_LTD",
	LA."ORIGINATION_FEES_YTD",
	LA."ORIGINATION_FEES_PYTD",
	LA."ORIGINATION_FEES_LTD",
	LA."ESCROW_INT_PAID_YTD",
	LA."ESCROW_INT_PAID_PYTD",
	LA."ESCROW_INT_PAID_LTD",
	LA."POINTS_PAID_BY_BORROWER",
	LA."SUBSIDIES_PAID_YTD",	
	LA."CLASS_CODE",
	LA."LAST_PAYMENT_DATE",
	LA."LATE_CHRG_YTD",
	LA."AMT_LC_WAIVED",
	LA."WAIVE_LATE_CHARGE",
	LA."SCHEDULED_PAYMENT_DUE_DATE",
	LA."EMPLOYEE_CODE",
	LA."HOLD4_CODE",
	LA."INTEREST_PAID_TO_DATE",
	LA."MFHASERVFEE",	
	LA."MLOTNBR",
	LA."MPLATNBR",
	LA."MPAGENBR",
	LA."ACCRUED_INTEREST_NET",
	LA."INTEREST_DUE",
	LA."INTEREST_PAST_DUE",
	LA."PER_DIEM",
	LA."DATE_LAST_ACTIVITY",
	LA."CONTRACT_ID",
	LA."LAST_TRANSACTION_DATE",
	LA."PAST_DUE_UNUSEDLINE_COMMIT_FEE",
	LA."PRINCIPAL_DUE",
	LA."FUTURE_PAYMENT_COUNT",
	LA."PRINCIPAL_PAID_TO_DATE",
	LA."WAIVED_LATE_CHARGE",
	LA."UNUSED_LINE_COMMITMENT",
	LA."INVESTOR_NUMBER",
	LA."LAST_STATEMENT_DATE",
	LA."PAY_OUT_CODE",
	LA."NO_RETURNED_CHECKS",
	LA."CURRENT_MONTH_EARNINGS",
	LA."LIFE_INSURANCE_PREMIUM",
	LA."SUBSIDY_BALANCE",
	LA."CREDIT_LIFE_INDICATOR",
	LA."LAST_REVIEW_DATE",
	LA."REVIEW_DATE_FREQ",
	LA."INTEREST_PAID_MTD",
	LA."DATE_PREVIOUS_ACTIVITY",
	LA."FINANCIAL_STMT_EXP_DATE",
	LA."FINANCING_STMT_EXP_DATE",
	LA."PAST_DUE_CHARGE1_AMT",
	LA."PAST_DUE_CHARGE2_AMT",
	LA."PAST_DUE_LINE_COMMIT_FEE",
	LA."PAST_DUE_DEALER_INTEREST",
	LA."PAID_LOAN_CLOCK",
	LA."COUPON_THRU_DATE",
	LA."LAST_STATEMENT_BAL",
	LA."PRE_STATEMENT_BAL",
	LA."PRE_STATEMENT_DATE",
	LA."ACCRUED_CHARGE1_AMT",
	LA."ACCRUED_CHARGE2_AMT",
	LA."CHARGE_OFF_AMOUNT",
	LA."PRE_PAID_AMOUNT",
	LA."DAILY_CHARG1_ACCRUAL",
	LA."DAILY_CHARG2_ACCRUAL",
	LA."DAILY_UNUSED_LINE_COMMIT_FEE",
	LA."PAST_PRINCIPLE_DUE",
	LA."REVIEWER",
	LA."ENTERED_BY" ,
	LA."PREVIOUS_OFFICER_CODE",
	LA."LAST_CURT_AMOUNT",
	LA."LAST_CURT_DATE",
	A."LAST_PROCESSED_DATE" ,
	LA."STMT_CYCLE_CODE"
FROM
	ACCOUNT A,
	LOAN_ACCOUNT LA 
WHERE
	A.ACCOUNT_ID=LA.ACCOUNT_ID;


--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 1 where STATE_NAME = 'DEFAULT' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerAccruedInterest');
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 1 where STATE_NAME = 'INQUIRY' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerAccruedInterest');
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 1 where STATE_NAME = 'ACCOUNT_CREATED' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerAccruedInterest');
--update property_definition set mandatory = 0 where property_name = 'DealerAccruedInterest' and ENTITY_TYPE_DEFINITION_ID = 701;
-- 
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 1 where STATE_NAME = 'DEFAULT' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerAccumulativeInterest');
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 1 where STATE_NAME = 'INQUIRY' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerAccumulativeInterest');
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 1 where STATE_NAME = 'ACCOUNT_CREATED' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerAccumulativeInterest');
--update property_definition set mandatory = 0 where property_name = 'DealerAccumulativeInterest' and ENTITY_TYPE_DEFINITION_ID = 701;
-- 
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 1 where STATE_NAME = 'DEFAULT' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerDailyAccrualAmount');
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 1 where STATE_NAME = 'INQUIRY' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerDailyAccrualAmount');
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 1 where STATE_NAME = 'ACCOUNT_CREATED' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerDailyAccrualAmount');
--update property_definition set mandatory = 0 where property_name = 'DealerDailyAccrualAmount' and ENTITY_TYPE_DEFINITION_ID = 701;
-- 
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 1 where STATE_NAME = 'DEFAULT' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerHoldbackRebate');
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 0 where STATE_NAME = 'INQUIRY' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerHoldbackRebate');
--update PROPERTY_PRESENTER_ATTRIBUTES set HIDDEN = 0 , EDITABLE  = 0 where STATE_NAME = 'ACCOUNT_CREATED' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerHoldbackRebate');
--update property_definition set mandatory = 0 where property_name = 'DealerHoldbackRebate' and ENTITY_TYPE_DEFINITION_ID = 701;
--update property_definition set CATEGORY= 'U' where property_name = 'DealerHoldbackRebate' and ENTITY_TYPE_DEFINITION_ID = 701;
--
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 1 , HIDDEN  = 0 where STATE_NAME = 'DEFAULT' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerHoldbackReserve');
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 0 where STATE_NAME = 'INQUIRY' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerHoldbackReserve');
--update PROPERTY_PRESENTER_ATTRIBUTES set HIDDEN = 0 , EDITABLE  = 1 where STATE_NAME = 'ACCOUNT_CREATED' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerHoldbackReserve');
--update property_definition set mandatory = 0 where property_name = 'DealerHoldbackReserve' and ENTITY_TYPE_DEFINITION_ID = 701;
--update property_definition set CATEGORY= 'U' where property_name = 'DealerHoldbackReserve' and ENTITY_TYPE_DEFINITION_ID = 701;
-- 
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 1 where STATE_NAME = 'DEFAULT' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerInterestpaidLTD');
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 1 where STATE_NAME = 'INQUIRY' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerInterestpaidLTD');
--update PROPERTY_PRESENTER_ATTRIBUTES set HIDDEN = 1 , EDITABLE  = 0 where STATE_NAME = 'ACCOUNT_CREATED' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerInterestpaidLTD');
--update property_definition set mandatory = 0 where property_name = 'DealerInterestpaidLTD' and ENTITY_TYPE_DEFINITION_ID = 701;
-- 
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 1 where STATE_NAME = 'DEFAULT' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerInterestpaidMTD');
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 1 where STATE_NAME = 'INQUIRY' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerInterestpaidMTD');
--update PROPERTY_PRESENTER_ATTRIBUTES set HIDDEN = 1 , EDITABLE  = 0 where STATE_NAME = 'ACCOUNT_CREATED' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerInterestpaidMTD');
--update property_definition set mandatory = 0 where property_name = 'DealerInterestpaidMTD' and ENTITY_TYPE_DEFINITION_ID = 701;
-- 
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 1 where STATE_NAME = 'DEFAULT' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerInterestpaidYTD');
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 1 where STATE_NAME = 'INQUIRY' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerInterestpaidYTD');
--update PROPERTY_PRESENTER_ATTRIBUTES set HIDDEN = 1 , EDITABLE  = 0 where STATE_NAME = 'ACCOUNT_CREATED' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerInterestpaidYTD');
--update property_definition set mandatory = 0 where property_name = 'DealerInterestpaidYTD' and ENTITY_TYPE_DEFINITION_ID = 701;
-- 
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 1 , HIDDEN  = 0 where STATE_NAME = 'DEFAULT' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerRate');
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 0 where STATE_NAME = 'INQUIRY' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerRate');
--update PROPERTY_PRESENTER_ATTRIBUTES set  EDITABLE  = 1 , HIDDEN = 0 where STATE_NAME = 'ACCOUNT_CREATED' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerRate');
--update property_definition set mandatory = 0 where property_name = 'DealerRate' and ENTITY_TYPE_DEFINITION_ID = 701;
--
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 0 where STATE_NAME = 'DEFAULT' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerRatio');
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 0 where STATE_NAME = 'INQUIRY' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerRatio');
--update PROPERTY_PRESENTER_ATTRIBUTES set  EDITABLE  = 0 , HIDDEN = 0 where STATE_NAME = 'ACCOUNT_CREATED' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerRatio');
--update property_definition set mandatory = 0 where property_name = 'DealerRatio' and ENTITY_TYPE_DEFINITION_ID = 701;
-- 
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 1 , HIDDEN  = 1 where STATE_NAME = 'DEFAULT' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerRebateAmount');
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 0 where STATE_NAME = 'INQUIRY' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerRebateAmount');
--update PROPERTY_PRESENTER_ATTRIBUTES set  EDITABLE  = 0 , HIDDEN = 0 where STATE_NAME = 'ACCOUNT_CREATED' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerRebateAmount');
--update property_definition set mandatory = 0 where property_name = 'DealerRebateAmount' and ENTITY_TYPE_DEFINITION_ID = 701;
-- 
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 1 , HIDDEN  = 0 where STATE_NAME = 'DEFAULT' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerReserveAmount');
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 0 where STATE_NAME = 'INQUIRY' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerReserveAmount');
--update PROPERTY_PRESENTER_ATTRIBUTES set  EDITABLE  = 1 , HIDDEN = 0 where STATE_NAME = 'ACCOUNT_CREATED' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'DealerReserveAmount');
--update property_definition set mandatory = 1 where property_name = 'DealerReserveAmount' and ENTITY_TYPE_DEFINITION_ID = 701;
--
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 0 where STATE_NAME = 'DEFAULT' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'EarningDate');
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 0 where STATE_NAME = 'INQUIRY' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'EarningDate');
--update PROPERTY_PRESENTER_ATTRIBUTES set  EDITABLE  = 0 , HIDDEN = 0 where STATE_NAME = 'ACCOUNT_CREATED' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'EarningDate');
--update property_definition set mandatory = 1 where property_name = 'EarningDate' and ENTITY_TYPE_DEFINITION_ID = 701;
--
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 1 where STATE_NAME = 'DEFAULT' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'PaidToDealer');
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 0 where STATE_NAME = 'INQUIRY' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'PaidToDealer');
--update PROPERTY_PRESENTER_ATTRIBUTES set  EDITABLE  = 0 , HIDDEN = 0 where STATE_NAME = 'ACCOUNT_CREATED' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'PaidToDealer');
--update property_definition set mandatory = 0 where property_name = 'PaidToDealer' and ENTITY_TYPE_DEFINITION_ID = 701;
--
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 0 where STATE_NAME = 'DEFAULT' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'RebateBasis');
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 0 where STATE_NAME = 'INQUIRY' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'RebateBasis');
--update PROPERTY_PRESENTER_ATTRIBUTES set  EDITABLE  = 0 , HIDDEN = 0 where STATE_NAME = 'ACCOUNT_CREATED' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'RebateBasis');
--update property_definition set mandatory = 1 where property_name = 'RebateBasis' and ENTITY_TYPE_DEFINITION_ID = 701;
--
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 1 , HIDDEN  = 0 where STATE_NAME = 'DEFAULT' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'RebateMethod');
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 0 where STATE_NAME = 'INQUIRY' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'RebateMethod');
--update PROPERTY_PRESENTER_ATTRIBUTES set  EDITABLE  = 1 , HIDDEN = 0 where STATE_NAME = 'ACCOUNT_CREATED' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'RebateMethod');
--update property_definition set mandatory = 1 where property_name = 'RebateMethod' and ENTITY_TYPE_DEFINITION_ID = 701;
--
--update property_definition set default_value= 'java.lang.Integer:0' where property_name = 'RebateMethod' and ENTITY_TYPE_DEFINITION_ID = 701;
-- 
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 1 , HIDDEN  = 0 where STATE_NAME = 'DEFAULT' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'Recourse');
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 0 where STATE_NAME = 'INQUIRY' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'Recourse');
--update PROPERTY_PRESENTER_ATTRIBUTES set  EDITABLE  = 1 , HIDDEN = 0 where STATE_NAME = 'ACCOUNT_CREATED' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'Recourse');
--update property_definition set mandatory = 0 where property_name = 'Recourse' and ENTITY_TYPE_DEFINITION_ID = 701;
--
--update property_definition set default_value= 'java.lang.Boolean:true' where property_name = 'Recourse' and ENTITY_TYPE_DEFINITION_ID = 701;
--
--
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 1 where STATE_NAME = 'DEFAULT' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'RemitMethod');
--update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE = 0 , HIDDEN  = 1 where STATE_NAME = 'INQUIRY' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'RemitMethod');
--update PROPERTY_PRESENTER_ATTRIBUTES set  EDITABLE  = 0 , HIDDEN = 1 where STATE_NAME = 'ACCOUNT_CREATED' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'RemitMethod');
--update property_definition set mandatory = 0 where property_name = 'RemitMethod' and ENTITY_TYPE_DEFINITION_ID = 701;
--
--
--update PROPERTY_PRESENTER_ATTRIBUTES set  EDITABLE  = 0 , HIDDEN = 0 where STATE_NAME = 'ACCOUNT_CREATED' and PROPERTY_DEFINITION_ID  in (
--select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID = 701 and PROPERTY_NAME = 'RemainingTerm');
--update property_definition set CATEGORY= 'U' where property_name = 'RemainingTerm' and ENTITY_TYPE_DEFINITION_ID = 701;



