alter table LOAN_EVENT_TYPE add DEBIT_OR_CREDIT varchar2(1) NULL;

update LOAN_EVENT_TYPE set  DEBIT_OR_CREDIT = 1 where EVENT_GROUP=0;
update LOAN_EVENT_TYPE set  DEBIT_OR_CREDIT = 0 where EVENT_GROUP=1; 

update LOAN_EVENT_TYPE set  DEBIT_OR_CREDIT = 0 where EVENT_TYPE_ID in (1, 5, 21, 22, 23, 24, 25, 26, 27, 40, 41);
update LOAN_EVENT_TYPE set  DEBIT_OR_CREDIT = 1 where EVENT_TYPE_ID in (201, 205, 221, 222, 223, 224, 225, 226, 227, 240, 241);


alter table LOAN_ACCOUNT_EVENT add(CHEQUE number(20));
alter table LOAN_ACCOUNT_EVENT add(STMT_DESC varchar2(300));
alter table LOAN_ACCOUNT_HISTORY_ITEM add(SEQUENCE_NO varchar2(20));
alter table LOAN_ACCOUNT_EVENT add(SEQUENCE_NO varchar2(20));

CREATE TABLE ENTITY_VERIFICATION(EVENT VARCHAR2(300),NO_OF_NULLS NUMBER(10));
CREATE TABLE PROPERTY_VERIFICATION(PROPERTY VARCHAR2(300),NO_OF_NULLS NUMBER(10));


-- Credit Memo LatCharge Payment
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('32','1907');

-- Debit Memo LatCharge Payment
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('22','1807');


-- Initial Fund
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_TRAN_AMOUNT	=1  WHERE POSTING_RULE_ID = 8881;

----removing entries for last_tran_date(20) and last_stmt_bal(30)
-- ENTRY_TYPE and LOAN_ENTRY_TYPE
delete from ENTRY_TYPE where UNIQUE_ID in ('1820', '1920', '1830', '1930');
delete from LOAN_ENTRY_TYPE where ENTRY_TYPE_ID in ('1820', '1920', '1830', '1930');

--LOAN_ENTRY_POSTING_RULE
delete from LOAN_ENTRY_POSTING_RULE where POSTING_RULE_ID in ('20', '30');


				
update LOAN_EVENT_TYPE set EVENT_GROUP = 0 where EVENT_TYPE_ID in ('42');
update LOAN_EVENT_TYPE set EVENT_GROUP = 1 where EVENT_TYPE_ID in ('242');

update LOAN_EVENT_TYPE set DESCRIPTION='Origination Fee Payment' where CORESOFT_EVENT_CODE = '018';
update LOAN_EVENT_TYPE set DESCRIPTION='Origination Fee Payment Reversal' where CORESOFT_EVENT_CODE = '218';

update LOAN_EVENT_TYPE set DESCRIPTION='Interest Paid - Debit Adjustment' where CORESOFT_EVENT_CODE = '025';
update LOAN_EVENT_TYPE set DESCRIPTION='Interest Paid - Debit Adjustment Reversal' where CORESOFT_EVENT_CODE = '225';

update LOAN_EVENT_TYPE set DESCRIPTION='Interest Paid - Credit Adjustment' where CORESOFT_EVENT_CODE = '035';
update LOAN_EVENT_TYPE set DESCRIPTION='Interest Paid - Credit Adjustment Reversal' where CORESOFT_EVENT_CODE = '235';

update LOAN_EVENT_TYPE set DESCRIPTION='Escrow Disbursement' where CORESOFT_EVENT_CODE = '040';
update LOAN_EVENT_TYPE set DESCRIPTION='Escrow Disbursement Reversal' where CORESOFT_EVENT_CODE = '240';

update LOAN_EVENT_TYPE set DESCRIPTION='Life -A/H Disbursement' where CORESOFT_EVENT_CODE = '041';
update LOAN_EVENT_TYPE set DESCRIPTION='Life -A/H Disbursement Reversal' where CORESOFT_EVENT_CODE = '241';


-- reg pymnt- esc bal  link
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('110','1903');

-- esc disb - esc bal  link
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('40','1803');

-- ah life bal - ahlife bal  link
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('41','1806');

INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1838, '1838', null, '2','0', 'Intialize Accrued Interest');

INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
   VALUES(1938, '1938', null, '2','1', 'Intialize Accrued Interest');

INSERT INTO LOAN_ENTRY_POSTING_RULE (POSTING_RULE_ID)VALUES (38);    

INSERT INTO LOAN_ENTRY_TYPE (ENTRY_TYPE_ID,ENTRY_NAME,REVERSAL_ENTRY_TYPE_ID,POSTING_RULE_ID) VALUES (1838,38,1938,38);

-- REVERSAL ENTRY TYPES
INSERT INTO LOAN_ENTRY_TYPE (ENTRY_TYPE_ID,ENTRY_NAME,REVERSAL_ENTRY_TYPE_ID,POSTING_RULE_ID) VALUES (1938,38,1838,38);


--End Day Link
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('99','1838');



UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_ACCRUED_INTEREST=1  WHERE POSTING_RULE_ID = 38;

ALTER TABLE LOAN_ACCOUNT_EVENT ADD ( RECORDED_TIME DATE);

ALTER TABLE LOAN_ACCOUNT_EVENT ADD ( UNPOSTED_FLAG VARCHAR2(1));

CREATE INDEX lae_account_id_idx ON LOAN_ACCOUNT_EVENT('ACCOUNT_ID') NOLOGGING;

ALTER TABLE LOAN_APPLICATION_EVENT ADD( CREATION_DATE DATE);

ALTER TABLE LOAN_ACCOUNT_DAY_SUMMARY ADD( EFFECTIVE_DATE DATE);

ALTER TABLE LOAN_ACCOUNT_EVENT MODIFY(EVENT_DATE DATE NULL);

