CREATE OR REPLACE VIEW LOAN_ACCOUNT_HISTORY_ITEM_VW AS

select * from LOAN_ACCOUNT_HISTORY_ITEM where TRAN_CODE

in('1801','1802','1803','1804','1805','1806','1809','1836',

'1901','1902','1903','1904','1905','1906','1909','1936');


----LOAN EVENT TYPE
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
				VALUES (111,'111',0, 311,23, 'Regular Payment -Automatic Transfer', 1);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
				VALUES (311,'311',1,111,9, 'Regular Payment -Automatic Transfer Reversal', 0);



----Dummy ENTRY POSTING RULE  - Regular Payment Auto Transfer  
INSERT INTO LOAN_ENTRY_POSTING_RULE (POSTING_RULE_ID)VALUES (8111);
				
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_BILL	=1  WHERE POSTING_RULE_ID = 8111;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_LAST_ACTIVITY	=1  WHERE POSTING_RULE_ID = 8111;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_NEXT_DUE	=1  WHERE POSTING_RULE_ID = 8111;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_PAYMENTS_MADE	=1  WHERE POSTING_RULE_ID = 8111;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_PRINCIPAL_PAID_TO_DATE	=1  WHERE POSTING_RULE_ID = 8111;	
---UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_TRAN_AMOUNT	=1  WHERE POSTING_RULE_ID = 8111;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_PARTIAL_PAYMENT	=1  WHERE POSTING_RULE_ID = 8111;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_INT_DUE_DATE	=1  WHERE POSTING_RULE_ID = 8111;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_PRNCP_DUE_DATE	=1  WHERE POSTING_RULE_ID = 8111;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_FUTURE_PAYMENT_COUNT	=1  WHERE POSTING_RULE_ID = 8111;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_LAST_PYMNT_AMOUNT	=1  WHERE POSTING_RULE_ID = 8111;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_PAYOUT_CODE	=1  WHERE POSTING_RULE_ID = 8111;			
UPDATE LOAN_ENTRY_POSTING_RULE SET	AFFECTS_DATE_CLOSED	=1  WHERE POSTING_RULE_ID = 8111;			
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_LOAN_STATUS=1  WHERE POSTING_RULE_ID = 8111;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_DTNXTDUBFRPSTNG=1  WHERE POSTING_RULE_ID = 8111;




----ENTRY TYPE
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(8111, '8111', null, '2','1', 'Regular Payment Auto Transfer');
    

----LOAN ENTRY TYPE
INSERT INTO LOAN_ENTRY_TYPE (ENTRY_TYPE_ID,ENTRY_NAME,REVERSAL_ENTRY_TYPE_ID,POSTING_RULE_ID) VALUES (8111,8111,8111,8111);


----EVENT ENTRY LINK
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('111','1901');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('111','1902');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('111','1904');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('111','1905');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('111','1906');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('111','1917');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('111','1907');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('111','1923');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('111','1932');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('111','1933');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('111','1935');
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID,ENTRY_TYPE_ID) VALUES('111','8111');


UPDATE LOAN_EVENT_TYPE SET DEBIT_OR_CREDIT=1 WHERE DESCRIPTION='Future Payment';
UPDATE LOAN_EVENT_TYPE SET DEBIT_OR_CREDIT=0 WHERE DESCRIPTION='Future Payment Reversal';





