create table INSTITUTION_CONFIG_PARAMETERS(
UNIQUE_ID NUMBER,
INSTITUTION_ID varchar(50),
OFAC_VERIFICATION_PARAMETER varchar(50),
LAST_OFAC_DATE DATE,
NEXT_OFAC_DATE DATE,
FREQUENCY varchar(50));

ALTER TABLE account_application ADD HOW_LLC_IS_TAXED VARCHAR2(45);
ALTER TABLE deposit_account ADD STATEMENT_HANDLING_OPTION NUMBER(5);
ALTER TABLE FORM_TEMPLATE ADD CUSTOMER_TYPE VARCHAR2(30);