alter table RISK_ASSESSMENT MODIFY REVIEWERS_IDS VARCHAR2(100);

alter table CUSTOMER_ACC_RISK_ASSESMENT add UPDATED_DATE Date;

alter table CUSTOMER_ACC_RISK_ASSESMENT add RATING Number;

CREATE TABLE "RISK_SCORE_RATING_MAPPING" (
    "ID"			NUMBER(30,0) NOT NULL ENABLE,
    "DESCRIPTION" 	VARCHAR2(100),
    "LOW_SCORE" 	NUMBER(30,0),
    "HIGH_SCORE" 	NUMBER(30,0),
    "RATING" 		NUMBER(30,0),
    "CUSTOMER_TYPE" NUMBER(15,0),
   CONSTRAINT "RISK_SCORE_PK" PRIMARY KEY ("ID") ENABLE );

create sequence RISK_SCORE_RATING_ID_SEQ minvalue 1 maxvalue 9999999999 increment by 1 start with 1;

CREATE TABLE MIN_BALANCE_ACCOUNT_MAPPING (
  UNIQUE_ID             NUMBER(15),
  MASTER_ACCOUNT_NO    	VARCHAR2(40),
  MAPPED_ACCOUNT_NO    	VARCHAR2(40));
  
 ALTER TABLE DEPOSIT ADD MINIMUM_BAL_CALCULATION_METHOD VARCHAR2(45);
 
 ALTER TABLE ACCOUNT_APPLICATION ADD DATE_IF_TRUST DATE ;
ALTER TABLE ACCOUNT_APPLICATION ADD TOTAL_NO_OF_BENIFICIARIES VARCHAR2(45);
ALTER TABLE ACCOUNT_APPLICATION ADD BENIFICIARY_INFORMATION VARCHAR2(45);
ALTER TABLE ACCOUNT_APPLICATION ADD SUCCESSOR_CUSTODIAN VARCHAR2(45);
ALTER TABLE ACCOUNT_APPLICATION ADD GRANTOR_NAMES VARCHAR2(45);
ALTER TABLE ACCOUNT_APPLICATION ADD WHO_IS_THE_SECREATARY VARCHAR2(45);
ALTER TABLE ACCOUNT_APPLICATION ADD HOW_IT_IS_TAXED VARCHAR2(45);
ALTER TABLE ACCOUNT_APPLICATION ADD WHO_IS_DESIGNATED_MEMBER VARCHAR2(45);

ALTER TABLE BANK_USERS ADD IS_PERSONAL_BANKER NUMBER(1);

ALTER TABLE BANK_USERS ADD IS_RELATIONSHIP_OFFICER NUMBER(1);

ALTER TABLE PARTY_REGISTERED_IDS ADD COUNTRY_OF_ISSUENCE VARCHAR2(50);

ALTER TABLE DEPOSIT ADD DORMANT_PROCESSING_DATE DATE;
ALTER TABLE deposit ADD HOW_LLC_IS_TAXED VARCHAR2(45);
ALTER TABLE deposit ADD DATE_IF_TRUST DATE ; 
ALTER TABLE deposit ADD TOTAL_NO_OF_BENIFICIARIES VARCHAR2(45); 
ALTER TABLE deposit ADD BENEFICIARY_INFORMATION VARCHAR2(500); 
ALTER TABLE deposit ADD SUCCESSOR_CUSTODIAN VARCHAR2(45); 
ALTER TABLE deposit ADD GRANTOR_NAMES VARCHAR2(45); 
ALTER TABLE deposit ADD WHO_IS_THE_SECREATARY VARCHAR2(45); 
ALTER TABLE deposit ADD HOW_IT_IS_TAXED VARCHAR2(45); 
ALTER TABLE deposit ADD WHO_IS_DESIGNATED_MEMBER VARCHAR2(45);


ALTER TABLE ACCOUNT_APPLICATION RENAME COLUMN BENIFICIARY_INFORMATION TO BENEFICIARY_INFORMATION;
ALTER TABLE ACCOUNT_APPLICATION MODIFY BENEFICIARY_INFORMATION VARCHAR2(500);
create sequence BOND_REDEM_ID_SEQ minvalue 1 maxvalue 9999999999 increment by 1 start with 1;