INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (021,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1884'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (221,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1984'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (031,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1884'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (231,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1984'));

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (021,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1883'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (221,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1983'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (031,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1883'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (231,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1983'));

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (021,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1882'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (221,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1982'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (031,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1882'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (231,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1982'));

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (021,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1881'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (221,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1981'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (031,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1881'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (231,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1981'));

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (021,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1885'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (221,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1985'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (031,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1885'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (231,(SELECT UNIQUE_ID FROM ENTRY_TYPE WHERE ID='1985'));

update loan_entry_posting_rule set AFF_TOTAL_AVAILABLE_AMOUNT=1 where posting_rule_id=8821;

update loan_entry_posting_rule set AFF_TOTAL_AVAILABLE_AMOUNT=1 where posting_rule_id=8831;

update loan_entry_posting_rule set AFF_TERM_LOAN_LIMIT_USED=1 where posting_rule_id=8821;

update loan_entry_posting_rule set AFF_TERM_LOAN_LIMIT_USED=1 where posting_rule_id=8831;

update loan_entry_posting_rule set AFF_UNUSED_TERM_LOAN_LIMIT=1 where posting_rule_id=8821;

update loan_entry_posting_rule set AFF_UNUSED_TERM_LOAN_LIMIT=1 where posting_rule_id=8831;

update loan_entry_posting_rule set AFF_CREDIT_LINE_LIMIT_USED=1 where posting_rule_id=8821;

update loan_entry_posting_rule set AFF_CREDIT_LINE_LIMIT_USED=1 where posting_rule_id=8831;

update loan_entry_posting_rule set AFF_UNUSED_CREDIT_LINE_LIMIT=1 where posting_rule_id=8821;

update loan_entry_posting_rule set AFF_UNUSED_CREDIT_LINE_LIMIT=1 where posting_rule_id=8831;