CREATE OR REPLACE VIEW PARTY_ACCOUNT_ROLE_VW as
SELECT lav.ACCOUNT_NO,
    PV.PARTY_TYPE,
    PV.PARTY_NAME,
    PV.BUSINESS_NAME,
    PV.FIRST_NAME,
    PAR.ACCOUNT_ID,
    PV.LAST_NAME,
    PV.EMPLOYER_NAME,
    AO.RESPONSIBILITY_TYPE,
    PR.ROLE_CREATION_DATE,
    PR.BUSINESS_DATE,
    PIA.ASSOCIATION_DATE,
    PIA.RELATIONSHIP_WITH_INSTITUTION,
    PIA.ASSIGNED_OFFICER,
    PV.PARTY_ID,
    PIA.INSTITUTION_ID,
    PIA.INSTITUTION_ASSOCIATION_ID,
    PR.UNIQUE_PARTY_ROLE_ID,
    PR.ROLE_TYPE_ID,
    PR.UNIQUE_ASSOCIATION_ID
  FROM PARTY_ROLE PR,
    PARTY_ACCOUNT_ROLE PAR,
    PARTY_VW PV,
    ACCOUNT_OWNER AO,
    PARTY_INSTITUTION_ASSOCIATION PIA,
    loan_account_vw lav
  WHERE PR.UNIQUE_PARTY_ROLE_ID = PAR.UNIQUE_PARTY_ROLE_ID
  AND PAR.UNIQUE_PARTY_ROLE_ID  = AO.UNIQUE_PARTY_ROLE_ID
  AND PIA.PARTY_ID              = PV.PARTY_ID
  AND par.account_id            = lav.loanaccount_id  
  AND PR.UNIQUE_ASSOCIATION_ID  = PIA.UNIQUE_ASSOCIATION_ID;