Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (1,'Individual Signature Card','F0008.jasper',1);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (2,'Funds Availability','F0013.pdf',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (3,'Check 21 info','F0011.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (4,'EFT Disclosure Personal','F0012.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (5,'Joint Signature Card','F0009.jasper',1);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (6,'Business Signature Card','F0001.jasper',1);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (7,'Cd Certificate Form','F0014.jasper',1);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (8,'Privacy Notice Form','F0003.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (9,'Miscellaneous Fee Schedule','F0002.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (10,'Savings Certificate of Deposit Disclosure','F0016.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (11,'W9 Form','F0004.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (12,'Partnership Agreement','F0005.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (13,'Corporate Resolution','F0007.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (14,'Unincorporated Resolution','F0006.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (15,'One Up Certificate of Deposit','F0019.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (16,'One Up Certificate of Deposit Disclosure','F0020.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (17,'No Penalty Certificate of Deposit','F0017.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (18,'No Penalty Certificate of Deposit Disclosure','F0018.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (19,'Commercial Checking Disclosure','F0022.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (20,'Interest Checking Disclosure','F0021.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (21,'MMA Disclosure','F0023.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (22,'Regular Savings Account Disclosure','F0026.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (23,'Christmas Club Without Book Disclosure','F0024.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (24,'Christmas Club Disclosure with Book','F0025.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (25,'UDC Business Referral Form','F0027.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (36,'Ira Age Election Form','F0036.jrxml',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (27,'Certificate of Deposit Disclosure','F0028.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (28,'Savings Certificate','F0015.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (29,'Traditional IRA Application','F0029.jrxml',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (30,'Roth IRA Application','F0030.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (31,'CESA Application','F0031.jrxml',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (32,'Request for Transfer or Conversion','F0032.jrxml',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (33,'IRA Rollover or Conversion Review','F0033.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (34,'Request for Direct Rollover','F0034.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (35,'Lifetime Free Checking Disclosure','F0035.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (37,'Indemnity Bond','F0037.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (38,'LLC Resolution','F0038.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (39,'Combined W9 Signature Card','F0039.jasper',1);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (40,'Deposit Account Agreement Disclosure','F0040.pdf',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (41,'Unlawful Internet Gambling','F0045.jasper',0);
Insert into FORM_TEMPLATE (UNIQUE_FORM_ID,FORM_NAME,XML_FILE_NAME,IS_EDITABLE) values (42,'EFT Disclosure Business','F0050.jasper',0);