CREATE OR REPLACE VIEW DEPOSIT_EXTRACT_VW
AS
SELECT DA.account_no DP_Acct_Identifier,
       '' DP_Acct_Identifier_2,
       '' DP_Acct_Identifier_3,
       '' DP_Acct_Identifier_4,
       '' DP_Acct_Identifier_5,
       '' DP_Sub_Acct_Identifier,
       DA.INSTITUTION_ID DP_Bank_No, 
       DECODE( UPPER(PAR_S.PARTY_TYPE),'PERSONAL',PRI_SSN.PARTY_REGISTERD_ID,PRI_TIN.PARTY_REGISTERD_ID) DP_Tax_ID,
       DECODE( UPPER(PAR_S.PARTY_TYPE),'PERSONAL','S','T') DP_Tax_Code,
       B.BRANCH_ID DP_Branch,
       '' DP_Cost_Center,
       'D' DP_Dep_Type,
       'USD' DP_Currency_Type,
       CASE WHEN UPPER(PAR_S.PARTY_TYPE)= 'COMMERCIAL' AND PAR_J2.PARTY_ID IS NOT NULL
       THEN 'P'
       WHEN UPPER(PAR_S.PARTY_TYPE)='PERSONAL' AND PAR_J2.PARTY_ID IS NOT NULL
       THEN 'J'
       WHEN ( UPPER(PAR_S.PARTY_TYPE)='PERSONAL' OR UPPER(PAR_S.PARTY_TYPE)='COMMERCIAL') 
              AND PAR_J2.PARTY_ID IS NULL
       THEN 'S'
       ELSE 'O' END responsiblity_type,           
       CASE WHEN ( PT.PRODUCT_TYPE_ID IN (4,16,3,21,25,19,23,22,24,30,5,7,20,89 ) AND PT.PRODUCT_CATEGORY = 2)
       THEN 'DDA' 
       WHEN ( PT.PRODUCT_TYPE_ID IN (66,67,69,58,68,72,65) AND PT.PRODUCT_CATEGORY = 2)
       THEN 'NOW'
       WHEN ( PT.PRODUCT_TYPE_ID IN (88,55,63,75,60,54,53) AND PT.PRODUCT_CATEGORY = 2)
       THEN 'MMA'
       WHEN PT.PRODUCT_CATEGORY = 1
       THEN 'SAVINGS'
       WHEN PT.PRODUCT_CATEGORY = 3
       THEN 'CD' END product_category,
       CASE WHEN DA.STATUS_CODE IN (0,1,2,3,7,101) THEN 'O'
       WHEN DA.STATUS_CODE IN (4) THEN 'I'
       WHEN DA.STATUS_CODE = 5 THEN 'D'
       WHEN DA.STATUS_CODE = 6 THEN 'R'
       WHEN DA.STATUS_CODE IN (98,99,102) THEN 'C' END status_code,
       NVL2(PAR_S.FIRST_NAME,PAR_S.FIRST_NAME||' ','')||NVL(PAR_S.LAST_NAME,'')||NVL(PAR_S.BUSINESS_NAME,'')    DP_Acct_Title_1,
       NVL2(PAR_J1.FIRST_NAME,PAR_J1.FIRST_NAME||' ','')||NVL(PAR_J1.LAST_NAME,'')||NVL(PAR_J1.BUSINESS_NAME,'')DP_Acct_Title_2,
       NVL2(PAR_J2.FIRST_NAME,PAR_J2.FIRST_NAME||' ','')||NVL(PAR_J2.LAST_NAME,'')||NVL(PAR_J2.BUSINESS_NAME,'')DP_Acct_Title_3,
       NVL2(PAR_J3.FIRST_NAME,PAR_J3.FIRST_NAME||' ','')||NVL(PAR_J3.LAST_NAME,'')||NVL(PAR_J3.BUSINESS_NAME,'')DP_Acct_Title_4,
GA.LINE_1 DP_Street_Add_Ln_1,
GA.LINE_2 DP_Street_Add_Ln_2,
GA.LINE_3 DP_Street_Add_Ln_3,
GA.CITY DP_City,
GA.STATE DP_State,
GA.ZIP_1||GA.ZIP_2 DP_ZIP,
GA.COUNTRY DP_Country,
'' DP_NA_Line_1,
'' DP_NA_Line_2,
'' DP_NA_Line_3,
'' DP_NA_Line_4,
'' DP_NA_Line_5,
'' DP_NA_Line_6,
ROUND(ledger_balance,2) DP_Cur_Bal,
TO_CHAR(DECODE(DA.ACCOUNT_TYPE_ID,22,DA.INTEREST_RATE,NVL(INT_CODE.INT_RATE,0)),'09.999999999') DP_Int_Rate,
ROUND(DA.Accrued_Interest,2) DP_Acc_int,
TO_CHAR(DA.date_last_interest,'YYYYMMDD') DP_Lst_Int_Pd,
TO_CHAR(DA.date_last_deposit,'YYYYMMDD') DP_Lst_Deposit,
CASE WHEN substr(term,INSTR(TERM,':')+1) =7 THEN
     ROUND(substr(term,1,INSTR(TERM,':')-1) * 12)
     WHEN substr(term,INSTR(TERM,':')+1) =6 THEN
     ROUND(substr(term,1,INSTR(TERM,':')-1)*1)
     WHEN substr(term,INSTR(TERM,':')+1) =5 THEN
     ROUND(substr(term,1,INSTR(TERM,':')-1)/4.29)
     WHEN substr(term,INSTR(TERM,':')+1) =4 THEN
     ROUND(substr(term,1,INSTR(TERM,':')-1)/30) END DP_Int_Term_No,
TO_CHAR(DA.maturity_date,'YYYYMMDD') DP_Nxt_Mat,
TO_CHAR(DA.business_date,'YYYYMMDD') DP_Open_DT,
'N' DP_Sweep_Code,
NVL(HOLD_INFO.HOLD_TYPE,'N') DP_Hold_To_Post,
ROUND(DA.Face_amount,2) DP_Issue_val_Amt,
DECODE(ACCOUNT_TYPE_ID,22,'R','') DP_Int_CD_Cde,
NVL(IRA.IRA_CODE,'') Dp_IRA_Cde,
CASE WHEN PA.ACCOUNT_ID IS NOT NULL
     THEN 'BANK'
     WHEN PT.PRODUCT_TYPE_ID = 16
     THEN 'BANK'
     WHEN PT.PRODUCT_TYPE_ID = 4
     THEN 'FED'
     WHEN PT.PRODUCT_TYPE_ID = 23
     THEN 'DUE TO'
     WHEN OWNERSHIP_DESIGNATION = 7 
     THEN 'CORP'
     WHEN PT.PRODUCT_TYPE_ID IN (3,53,60,63,9,49,51,59,41,43,45,47,55,57) 
     THEN 'COMM'    
     ELSE 'RTL' END DP_Deposit_Class_Type,
'' DP_Product_Class_Cde
FROM DEPOSIT_ACCOUNT_VW DA, BRANCH B, PRODUCT_TYPE PT,PAYMENT_ACCOUNT PA,
     (SELECT * FROM PARTY_ACCOUNT_ROLE_VW WHERE RESPONSIBILITY_TYPE IN (9,6)) PAR_S,
     (SELECT * FROM (SELECT PAR.*, RANK() OVER (PARTITION BY ACCOUNT_ID ORDER BY ROWID) SEQ 
                     FROM PARTY_ACCOUNT_ROLE_VW PAR 
                     WHERE RESPONSIBILITY_TYPE =5)
      WHERE SEQ=1 )PAR_J1,
      (SELECT * FROM (SELECT PAR.*, RANK() OVER (PARTITION BY ACCOUNT_ID ORDER BY ROWID) SEQ 
                     FROM PARTY_ACCOUNT_ROLE_VW PAR 
                     WHERE RESPONSIBILITY_TYPE =5)
      WHERE SEQ=2 )PAR_J2,
      (SELECT * FROM (SELECT PAR.*, RANK() OVER (PARTITION BY ACCOUNT_ID ORDER BY ROWID) SEQ 
                     FROM PARTY_ACCOUNT_ROLE_VW PAR 
                     WHERE RESPONSIBILITY_TYPE =5)
      WHERE SEQ=3 )PAR_J3,
     (SELECT DISTINCT PARTY_ID,TYPE,PARTY_REGISTERD_ID FROM PARTY_REGISTERED_IDS WHERE TYPE='SSN') PRI_SSN,
     (SELECT DISTINCT PARTY_ID,TYPE,PARTY_REGISTERD_ID FROM PARTY_REGISTERED_IDS WHERE TYPE='TIN') PRI_TIN,
      ACCOUNT_STATEMENT_GENERATOR ASG,
      ACCOUNT_STATEMENT_ADDRESS ASA,
      PARTY_ADDRESS PA,
      GEOGRAPHIC_ADDRESS GA,
     (select ic1.INTEREST_CODE,ic1.PRODUCT_CATEGORY,iic1.INSTITUTION_ID,
LAG(BALANCE,1,-99999999999.99) OVER (PARTITION BY iic1.INSTITUTION_ID,ic1.PRODUCT_CATEGORY,ic1.INTEREST_CODE ORDER BY iic1.INSTITUTION_ID,ic1.PRODUCT_CATEGORY,ic1.INTEREST_CODE,BALANCE) PREV_BAL,
DECODE(BALANCE,0.01,0,99999999999.99,99999999999.99,-99999999999.99,-99999999999.99,BALANCE-1) CURR_BAL, LAG(INTEREST_RATE,1,0) OVER (PARTITION BY iic1.INSTITUTION_ID,ic1.PRODUCT_CATEGORY,ic1.INTEREST_CODE ORDER BY iic1.INSTITUTION_ID,ic1.PRODUCT_CATEGORY,ic1.INTEREST_CODE,BALANCE) INT_RATE
from 
INTEREST_CODES ic1 , INSTITUTION_INT_CODES iic1 , INTEREST_CODE_RATES ICR1
where ic1.INTEREST_CODE_HIST_UID = iic1.INTEREST_CODE_HIST_UID
AND ICR1.INTEREST_CODE_UID = IC1.UNIQUE_ID
and ic1.product_category in (1,2)
and (ic1.INTEREST_CODE,ic1.PRODUCT_CATEGORY,iic1.INSTITUTION_ID,ic1.INTEREST_CODE_HIST_UID) IN (
select ic.INTEREST_CODE,ic.PRODUCT_CATEGORY,iic.INSTITUTION_ID,max(ic.INTEREST_CODE_HIST_UID)
 from INTEREST_CODES ic , INSTITUTION_INT_CODES iic
where ic.INTEREST_CODE_HIST_UID = iic.INTEREST_CODE_HIST_UID
and ic.product_category in (1,2)
group by ic.INTEREST_CODE,ic.PRODUCT_CATEGORY,iic.INSTITUTION_ID)) int_code,
(SELECT DISTINCT HP.ACCOUNT_ID , 'Y' HOLD_TYPE
FROM DEPOSIT_ACCOUNT_INSTRUCTION DAI , HOLD_PAYMENT HP
WHERE DAI.INSTRUCTION_ID = HP.INSTRUCTION_ID
AND   DAI.EFFECTIVE_EXPIRE_DATE > SYSDATE
AND  HOLD_TYPE_ID IN (3,4)) HOLD_INFO,
(SELECT SPD.PLAN_ID, 
DECODE(SPT.SAVINGS_PLAN_TYPE_ID,1,'T',2,'R',3,'E') IRA_CODE
FROM SAVINGS_PLAN_DETAILS SPD , SAVINGS_PLAN_TYPE SPT
WHERE SPD.SAVINGS_PLAN_TYPE_ID =SPT.UNIQUE_ID) IRA
WHERE DA.ACCOUNT_ID= PAR_S.ACCOUNT_ID
AND   DA.ACCOUNT_ID = PA.ACCOUNT_ID(+)
AND   DA.ACCOUNT_ID= HOLD_INFO.ACCOUNT_ID(+)
AND   DA.PLAN_ID = IRA.PLAN_ID(+)
AND    B.UNIQUE_ID = DA.BRANCH_ID 
AND   PT.UNIQUE_ID =  DA.PRODUCT_ID 
AND DA.ACCOUNT_ID=PAR_J1.ACCOUNT_ID(+)
AND DA.ACCOUNT_ID=PAR_J2.ACCOUNT_ID(+)
AND DA.ACCOUNT_ID=PAR_J3.ACCOUNT_ID(+)
AND DA.INTEREST_CODE = INT_CODE.INTEREST_CODE(+)
AND DA.INSTITUTION_ID = INT_CODE.INSTITUTION_ID(+)
AND DA.LEDGER_BALANCE BETWEEN PREV_BAL(+) AND CURR_BAL(+)
AND INT_CODE.PRODUCT_CATEGORY(+) = DECODE(ACCOUNT_TYPE_ID,21,1,10,2,22,3)
AND PAR_S.PARTY_ID = PRI_SSN.PARTY_ID(+)
AND PAR_S.PARTY_ID = PRI_TIN.PARTY_ID(+)
AND DA.ACCOUNT_ID = ASG.ACCOUNT_ID
AND ASG.UNIQUE_ID = ASA.UNIQUE_ID
AND ASA.UNIQUE_PARTY_ADDRESS_ID = PA.UNIQUE_PARTY_ADDRESS_ID
AND PA.ADDRESS_USE='OTHERS'
AND PA.ADDRESS_ID = GA.ADDRESS_ID;
