-- for Payment Account
alter table payment_account add ACCOUNT_ID NUMBER (30,0);
alter table ledger_posting_parameters add (IS_UNCONDITIONAL_PAYOUT NUMBER default 0);

create table IMPORTANT_CUSTOMER_ACCOUNT(ACCOUNT_ID NVARCHAR2(30),
INSTITUTITON_ID NVARCHAR2(30),ACCOUNT_NO NVARCHAR2(30));

alter table LEDGER_POSTING_PARAMETERS add(ALWAYS_REJECT NUMBER DEFAULT 0,
REASON_CODE NUMBER(3,0) DEFAULT 0);


CREATE TABLE POTENTIAL_CHARGE_OFF_DEP_EVENT (
	UNIQUE_ID NUMBER(20),ACCOUNT_ID VARCHAR2(30),
	EFFECTIVE_DATE DATE,ENTRY_DATE DATE,CHRG_OFF_EVENT_UID NUMBER(20));

ALTER TABLE POTENTIAL_CHARGE_OFF_DEP_EVENT ADD ( CONSTRAINT POTENTIAL_CHRG_OFF_DEP_EVNT_PK PRIMARY KEY(UNIQUE_ID));

ALTER TABLE POTENTIAL_CHARGE_OFF_DEP_EVENT ADD ( CONSTRAINT POTEN_CHRG_OFF_DEP_EVNT_ACC_FK
	FOREIGN KEY(ACCOUNT_ID)	REFERENCES ACCOUNT(ACCOUNT_ID));

CREATE SEQUENCE POTEN_CHRG_OFF_DEP_EVNT_SEQ
    INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    CACHE 20
    ORDER;
    
 CREATE TABLE CHARGE_OFF_EVENT (
	UNIQUE_ID NUMBER(20),
	EFFECTIVE_DATE DATE,
	ENTRY_DATE DATE,
	ACCOUNT_ID VARCHAR2(30)	
	);
	
ALTER TABLE CHARGE_OFF_EVENT ADD ( CONSTRAINT CHARGE_OFF_EVENT_PK PRIMARY KEY(UNIQUE_ID));
	
ALTER TABLE CHARGE_OFF_EVENT ADD ( CONSTRAINT CHARGE_OFF_EVENT_ACC_ID_FK
	FOREIGN KEY(ACCOUNT_ID)
	REFERENCES ACCOUNT(ACCOUNT_ID));

CREATE SEQUENCE CHARGE_OFF_EVENT_SEQ
    INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    CACHE 20
    ORDER;
    
 
CREATE TABLE TRANSFER_FUNDS_EVENT (
	UNIQUE_ID NUMBER(20),
	EFFECTIVE_DATE DATE,
	ENTRY_DATE DATE,
	SOURCE_ACCOUNT_ID VARCHAR2(30),
	TARGET_ACCOUNT_ID VARCHAR2(30),
	AMOUNT NUMBER(20,5),
	POTENTIAL_CHRG_OFF_EVENT_UID NUMBER(20)
	);
	
ALTER TABLE TRANSFER_FUNDS_EVENT ADD ( CONSTRAINT TRANSFER_FUNDS_EVENT_PK PRIMARY KEY(UNIQUE_ID));
	
ALTER TABLE TRANSFER_FUNDS_EVENT ADD ( CONSTRAINT TRANSFER_FUNDS_EVNT_SRC_ACC_ID
	FOREIGN KEY(SOURCE_ACCOUNT_ID)
	REFERENCES ACCOUNT(ACCOUNT_ID));
	
ALTER TABLE TRANSFER_FUNDS_EVENT ADD ( CONSTRAINT TRANSFER_FUNDS_EVNT_TGT_ACC_ID
	FOREIGN KEY(TARGET_ACCOUNT_ID)
	REFERENCES ACCOUNT(ACCOUNT_ID));
	
ALTER TABLE TRANSFER_FUNDS_EVENT ADD ( CONSTRAINT XFERFNDS_POTCHRG_OFF_ENT_ID_FK
	FOREIGN KEY(POTENTIAL_CHRG_OFF_EVENT_UID)
	REFERENCES POTENTIAL_CHARGE_OFF_DEP_EVENT(UNIQUE_ID));

	
CREATE SEQUENCE TRANSFER_FUNDS_EVENT_SEQ
    INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    CACHE 20
    ORDER;

ALTER TABLE CHARGE_OFF_EVENT ADD RECOVERY_ACCOUNT_ID VARCHAR2(30);

ALTER TABLE CHARGE_OFF_EVENT ADD ( CONSTRAINT CHARGE_OFF_EVENT_REC_ACC_ID_FK
	FOREIGN KEY(RECOVERY_ACCOUNT_ID)
	REFERENCES ACCOUNT(ACCOUNT_ID));
	
alter table deposit_account add(CYCLE_GROUP_CYCLE_CODE varchar2(30));
ALTER TABLE CHARGE_OFF_EVENT ADD AMOUNT NUMBER(25,5);

CREATE TABLE FDIC_PARAMETERS (UNIQUE_ID NUMBER(10), INSTITUTION_ID VARCHAR2(10), PRODUCT_CATEGORY NUMBER(5),
PRODUCT_TYPES VARCHAR2(50), THRESHOLD_AMOUNT NUMBER(20,5), THRESHOLD_PERCENTAGE NUMBER(20,5),
IS_RUN_ALLOWED NUMBER(1), PARTY_TYPE VARCHAR2(50));

create sequence FDIC_PARAM_SEQ start with 1 increment by 1;

alter table FDIC_PARAMETERS modify PRODUCT_TYPES varchar2(500);

CREATE TABLE FDIC_FILE (FILE_ID NUMBER(10), FILE_TYPE VARCHAR2(10), FILE_LOAD_DATE Date, FILE_NAME varchar2(50));

CREATE TABLE FDIC_HOLDS (HOLD_ID NUMBER(10),FILE_ID NUMBER(10), ACCOUNT_NUMBER VARCHAR2(25),
 ACCOUNT_IDENTIFIER1 VARCHAR2(25),ACCOUNT_IDENTIFIER2 VARCHAR2(25), ACCOUNT_IDENTIFIER3 VARCHAR2(25), 
ACCOUNT_IDENTIFIER4 VARCHAR2(25),SUB_ACCOUNT_IDENTIFIER VARCHAR2(25), HOLD_ACTION VARCHAR2(10),
 HOLD_AMOUNT NUMBER(14,2),HOLD_DESCRIPTION VARCHAR2(225), STATUS NUMBER(1));

CREATE TABLE FDIC_TRANSACTIONS (TRANSACTION_ID NUMBER(10),FILE_ID NUMBER(10), ACCOUNT_NUMBER VARCHAR2(25), 
ACCOUNT_IDENTIFIER1 VARCHAR2(25),ACCOUNT_IDENTIFIER2 VARCHAR2(25), ACCOUNT_IDENTIFIER3 VARCHAR2(25),
ACCOUNT_IDENTIFIER4 VARCHAR2(25),SUB_ACCOUNT_IDENTIFIER VARCHAR2(25), DEBIT_AMOUNT NUMBER(14,2), 
CREDIT_AMOUNT NUMBER(14,2),TRANSACTION_DESCRIPTION VARCHAR2(225), STATUS NUMBER(1));

create sequence FDIC_FILE_SEQ start with 1 increment by 1;

create sequence FDIC_HOLD_SEQ start with 1 increment by 1;

create sequence FDIC_TRANSACTION_SEQ start with 1 increment by 1;

alter table LEDGER_POSTING_PARAMETERS modify ENTRY_TYPE_ID number (6,0);

alter table deposit_account add RETURNED_ITEM_FEE_PTD number(20,5) default 0;
alter table deposit_account add RETURNED_ITEM_FEE_YTD number(20,5) default 0;
alter table deposit_account add OD_FEE_PTD number(20,5) default 0;
alter table deposit_account add OD_FEE_YTD number(20,5) default 0;

ALTER TABLE DEPOSIT_ACCOUNT ADD (PREV_RETURNED_ITEM_FEE_PTD NUMBER(20,5) default 0);
ALTER TABLE DEPOSIT_ACCOUNT ADD (PREV_OD_FEE_PTD NUMBER(20,5) default 0);

alter table LEDGER_POSTING_PARAMETERS rename column IS_PAYOFF_TRANSACTION to IS_FORCE_CLOSEOUT_TRANSACTION;
ALTER TABLE payment_account add FUNDING_INSTITUTION_NUMBER varchar2(30);

alter table POTENTIAL_CHARGE_OFF_DEP_EVENT add AMOUNT NUMBER(25,5);

alter table LEDGER_POSTING_PARAMETERS add(AFFECTS_ACCOUNT_HISTORY number default 1);

alter table deposit_account rename column DATE_LAST_EXTERNAL_ACTIVITY to DATE_LAST_EXTERNAL_DEBIT_ACTY;

ALTER  TABLE PAYMENT_ACCOUNT  ADD  EXTRACT_TRANSCATION_TYPE  NUMBER(3);

ALTER TABLE FEATURE ADD (IS_ACCOUNT_PROPERTY NUMBER(1,0), PARAM_FEATURE_TYPE VARCHAR2(200));