-- SEQUENCE SCRIPTS

CREATE SEQUENCE LOAN_TRANS_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOMINVALUE
	NOCYCLE
	CACHE 20
	ORDER;




UPDATE LOAN_ACCOUNT_HISTORY_ITEM SET IS_REVERSABLE=0;

ALTER TABLE LOAN_ACCOUNT_DAY ADD  BANK_REBATE number (20,2);
ALTER TABLE LOAN_ACCOUNT_DAY ADD  CL_REBATE number (20,2);
ALTER TABLE LOAN_ACCOUNT_DAY ADD  AH_REBATE number (20,2);
ALTER TABLE LOAN_ACCOUNT_DAY ADD  COL_INS_REBATE number (20,2);
ALTER TABLE LOAN_ACCOUNT_DAY ADD  SP_RSRV1_REBATE number (20,2);
ALTER TABLE LOAN_ACCOUNT_DAY ADD  SP_RSRV2_REBATE number (20,2);
ALTER TABLE LOAN_ACCOUNT_DAY ADD  DEALER_RSRV_REBATE number (20,2);
ALTER TABLE LOAN_ACCOUNT_DAY ADD  DEALER_HB_REBATE number (20,2);

ALTER TABLE LOAN_ACCOUNT_DAY ADD  OPENING_BANK_REBATE number (20,2);
ALTER TABLE LOAN_ACCOUNT_DAY ADD  OPENING_CL_REBATE number (20,2);
ALTER TABLE LOAN_ACCOUNT_DAY ADD  OPENING_AH_REBATE number (20,2);
ALTER TABLE LOAN_ACCOUNT_DAY ADD  OPENING_COL_INS_REBATE number (20,2);
ALTER TABLE LOAN_ACCOUNT_DAY ADD  OPENING_SP_RSRV1_REBATE number (20,2);
ALTER TABLE LOAN_ACCOUNT_DAY ADD  OPENING_SP_RSRV2_REBATE number (20,2);
ALTER TABLE LOAN_ACCOUNT_DAY ADD  OPENING_DEALER_RSRV_REBATE number (20,2);
ALTER TABLE LOAN_ACCOUNT_DAY ADD  OPENING_DEALER_HB_REBATE number (20,2);


alter table LOAN_ACCOUNT_DAY add ACCRD_CL number (20,6);
alter table LOAN_ACCOUNT_DAY add ACCRD_AH number (20,6);
alter table LOAN_ACCOUNT_DAY add ACCRD_UNUSED_LCF number (20,6);
alter table LOAN_ACCOUNT_DAY add BILLED_DEALER_INT_DUE number (20,6);
alter table LOAN_ACCOUNT_DAY add INT_PAID_MTD number (20,6);
alter table LOAN_ACCOUNT_DAY add INT_PAID_YTD number (20,6);

alter table LOAN_ACCOUNT_DAY add OPENING_ACCRD_CL number (20,6);
alter table LOAN_ACCOUNT_DAY add OPENING_ACCRD_AH number (20,6);
alter table LOAN_ACCOUNT_DAY add OPENING_ACCRD_UNUSED_LCF number (20,6);
alter table LOAN_ACCOUNT_DAY add OPENING_BILLED_DEALER_INT_DUE number (20,6);
alter table LOAN_ACCOUNT_DAY add OPENING_INT_PAID_MTD number (20,6);
alter table LOAN_ACCOUNT_DAY add OPENING_INT_PAID_YTD number (20,6);

ALTER TABLE LOAN_ACCOUNT_DAY ADD  OPENING_CLOSED_DATE DATE;
ALTER TABLE LOAN_ACCOUNT_DAY ADD  OPENING_LOAN_STATUS number (10);
ALTER TABLE LOAN_ACCOUNT_DAY ADD  OPENING_PAYOUT_CODE VARCHAR2 (10);
ALTER TABLE LOAN_ACCOUNT_DAY ADD  OPENING_INTEREST_RATE number (10);
ALTER TABLE LOAN_ACCOUNT_DAY ADD  OPENING_UNAPPLIED_FUND number (20,2);
ALTER TABLE LOAN_ACCOUNT_DAY ADD  OPENING_LAST_TRANSACTION_DATE DATE;
ALTER TABLE LOAN_ACCOUNT_DAY ADD  OPENING_LAST_PAYMENT_DATE DATE;
ALTER TABLE LOAN_ACCOUNT_DAY ADD  OPENING_LAST_STMT_DATE DATE;
ALTER TABLE LOAN_ACCOUNT_DAY ADD  OPENING_BALANCE_LAST_STMT number (20,2);
ALTER TABLE LOAN_ACCOUNT_DAY ADD  UNAPPLIED_FUND number (20,2);
ALTER TABLE LOAN_ACCOUNT_DAY ADD  LAST_TRANSACTION_DATE DATE;
ALTER TABLE LOAN_ACCOUNT_DAY ADD  LAST_PAYMENT_DATE DATE;
ALTER TABLE LOAN_ACCOUNT_DAY ADD  LAST_STMT_DATE DATE;
ALTER TABLE LOAN_ACCOUNT_DAY ADD  BALANCE_LAST_STMT number (20,2);
ALTER TABLE LOAN_ACCOUNT_DAY ADD (NO_OF_ENCLOSURES  NUMBER(10));

ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_ACC_DEALER_INT number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_ACC_INT number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_AH_DUE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_CL_DUE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_COLLECTED_LATE_CHARGE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_DATE_NEXT_DUE DATE;
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_ESCROW_BALANCE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_ESCROW_DUE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_FUTURE_PAYMENT_COUNT number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_INT_PAID_TO_DATE DATE;
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_NEXT_DISBURSEMENT_DATE DATE;
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_NON_ESCROW_BALANCE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_LOAN_AMOUNT number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_OTHER_FEE_DUE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_PARTIAL_PAYMENT number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_PAST_AH_DUE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_PAST_CL_DUE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_PAST_DEALER_INT_DUE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_PAST_ESCROW_DUE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_PAST_INT_DUE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_PAST_PRINCIPAL_DUE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_PAYMENTS_MADE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_PER_DIEM number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_PRINCIPLE_BALANCE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_PRINCIPAL_BILLING_DATE DATE;
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_PRINCIPAL_DUE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_PRINCIPAL_PAID_TO_DATE DATE;
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_RET_CHECK_COUNT number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_LATE_CHARGE_DUE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_WAIVED_LATE_CHARGE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_INT_DUE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_NON_ESCROW_DUE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_PAST_NON_ESCROW_DUE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_LCF_DUE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_PAST_LCF_DUE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_INT_PAID number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_BANK_REBATE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_CL_REBATE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_AH_REBATE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_COL_INS_REBATE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_SP_RSRV1_REBATE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_SP_RSRV2_REBATE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_DEALER_RSRV_REBATE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_DEALER_HB_REBATE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_ACCRD_CL number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_ACCRD_AH number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_ACCRD_UNUSED_LCF number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_BILLED_DEALER_INT_DUE number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_INT_PAID_MTD number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_INT_PAID_YTD number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_CLOSED_DATE DATE;
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_LOAN_STATUS number (10);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_PAYOUT_CODE VARCHAR2 (10);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_INTEREST_RATE number (10);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  UNAPPLIED_FUND number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_UNAPPLIED_FUND number (20,2);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_LAST_TRANSACTION_DATE DATE;
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_LAST_PAYMENT_DATE DATE;
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_LAST_STMT_DATE DATE;
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD  OPENING_BALANCE_LAST_STMT number (20,2);

ALTER TABLE LOAN_ACCOUNT ADD(PAST_DUE_FLAG NUMBER(10));

alter table loan_account_day drop column LAST_PAYMENT_DATE;

alter table loan_account_day drop column LAST_STMT_DATE;

alter table loan_account_day drop column LAST_TRANSACTION_DATE;


alter table loan_account_day add  LAST_PAYMENT_DATE VARCHAR2(50);

alter table loan_account_day add LAST_STMT_DATE VARCHAR2(50);

alter table loan_account_day add LAST_TRANSACTION_DATE VARCHAR2(50);

ALTER TABLE LOAN_ACCOUNT DROP CONSTRAINT LA_CC_FK;

ALTER TABLE LOAN_ACCOUNT ADD (INITIAL_FUND_POSTED_DATE  DATE);

ALTER TABLE BILLING_BUCKET ADD (PAID_PRINCIPAL  NUMBER(20,5));
ALTER TABLE BILLING_BUCKET ADD (PAID_ESCROW  NUMBER(20,5));
ALTER TABLE BILLING_BUCKET ADD (PAID_INTEREST  NUMBER(20,5));
ALTER TABLE BILLING_BUCKET ADD (PAID_AH_LIFE  NUMBER(20,5));
ALTER TABLE BILLING_BUCKET ADD (PAID_CREDIT_LIFE  NUMBER(20,5));
ALTER TABLE BILLING_BUCKET ADD (PAID_LATE_FEE  NUMBER(20,5));
ALTER TABLE BILLING_BUCKET ADD (PAID_OTHER_FEE  NUMBER(20,5));
ALTER TABLE BILLING_BUCKET ADD (PAID_SUBSIDY  NUMBER(20,5));

ALTER TABLE DELQ_BILLING_BUCKET_NEW ADD (PAID_PRINCIPAL  NUMBER(20,5));
ALTER TABLE DELQ_BILLING_BUCKET_NEW ADD (PAID_ESCROW  NUMBER(20,5));
ALTER TABLE DELQ_BILLING_BUCKET_NEW ADD (PAID_INTEREST  NUMBER(20,5));
ALTER TABLE DELQ_BILLING_BUCKET_NEW ADD (PAID_AH_LIFE  NUMBER(20,5));
ALTER TABLE DELQ_BILLING_BUCKET_NEW ADD (PAID_CREDIT_LIFE  NUMBER(20,5));
ALTER TABLE DELQ_BILLING_BUCKET_NEW ADD (PAID_LATE_FEE  NUMBER(20,5));
ALTER TABLE DELQ_BILLING_BUCKET_NEW ADD (PAID_OTHER_FEE  NUMBER(20,5));
ALTER TABLE DELQ_BILLING_BUCKET_NEW ADD (PAID_SUBSIDY  NUMBER(20,5));

ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD (DATE_NEXT_DUE  DATE);
ALTER TABLE LOAN_ACCOUNT_HISTORY_ITEM ADD (PAYMENT_NO VARCHAR2(25));

update LOAN_ACCOUNT_HISTORY_ITEM set TRAN_CODE='1801' where TRAN_CODE='01';
update LOAN_ACCOUNT_HISTORY_ITEM set LOAN_ENTRY_TYPE_ID='19020' where LOAN_ENTRY_TYPE_ID='9020';
update LOAN_ACCOUNT_HISTORY_ITEM set LOAN_ENTRY_TYPE_ID='1502' where LOAN_ENTRY_TYPE_ID='502';
update LOAN_ACCOUNT_HISTORY_ITEM set LOAN_ENTRY_TYPE_ID='1801' where LOAN_ENTRY_TYPE_ID='801';
update LOAN_ACCOUNT_HISTORY_ITEM set LOAN_ENTRY_TYPE_ID='17010' where LOAN_ENTRY_TYPE_ID='7010';
