-- ENTITY TYPE DEFINITIONS

CREATE TABLE VALUE_TYPE_DEFINITION ( 
    VALUE_TYPE_DEFINITION_ID	NUMBER(15) NOT NULL,
    TYPE_NAME               	VARCHAR2(50) NOT NULL,
    TYPE_DESCRIPTION               	VARCHAR2(100),
    VALUE_TYPE_CLASS            VARCHAR2(50) NOT NULL,
    DEFAULT_VALUE               VARCHAR2(200) NULL,
    BASE_VALUE_TYPE_DEF_ID	NUMBER(15),
    CONSTRAINT VALUE_TYPE_DEF_PK PRIMARY KEY(VALUE_TYPE_DEFINITION_ID)
);

CREATE SEQUENCE VALUETYPEDEFID_SEQ
    INCREMENT BY 1
    START WITH 100
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    CACHE 20
    NOORDER;

CREATE TABLE PROPERTY_DEFINITION ( 
    PROPERTY_DEFINITION_ID   	NUMBER(15) NOT NULL,
    ENTITY_TYPE_DEFINITION_ID	NUMBER(15) NOT NULL,
    PROPERTY_NAME            	VARCHAR2(50) NOT NULL,
    PROPERTY_INDEX            	NUMBER(10) NOT NULL,
    PROPERTY_DESCRIPTION       	VARCHAR2(100) NOT NULL,
    VALUE_TYPE_DEFINITION_ID 	NUMBER(15) NOT NULL,
    DESCRIPTION_FIELD           NUMBER(1) NOT NULL,
	DESCRIPTION_FIELD_OVERRIDEN NUMBER(1) NOT NULL,
    DEFAULT_VALUE               VARCHAR2(200) NULL,
    DEFAULT_VALUE_OVERRIDEN     NUMBER(1) NULL,
    VALID_VALUES               VARCHAR2(1000) NULL,
    VALID_VALUES_OVERRIDEN     NUMBER(1) NULL,
    MANDATORY               NUMBER(1) NOT NULL,
    MANDATORY_OVERRIDEN     NUMBER(1) NULL,
	HIDDEN               NUMBER(1) NOT NULL,
    HIDDEN_OVERRIDEN     NUMBER(1) NULL,
    EDITABLE              NUMBER(1) NOT NULL,
    EDITABLE_OVERRIDEN     NUMBER(1) NULL,
    INHERITED              NUMBER(1) NOT NULL,
    CAN_EDIT_DEFINITION     NUMBER(1) NOT NULL,
    CAN_DELETE_DEFINITION     NUMBER(1) NOT NULL,
    CATEGORY_OVERRIDEN          	NUMBER(1,0) NULL,
    CATEGORY                    	VARCHAR2(200) NULL,
    PRIMARY_OVERRIDEN          	NUMBER(1,0) NULL,
    PRIMARY                    	NUMBER(1,0) NULL,
    CONSTRAINT PROPERTY_DEF_PK PRIMARY KEY(PROPERTY_DEFINITION_ID)
);

CREATE SEQUENCE PROPDEFID_SEQ
    INCREMENT BY 1
    START WITH 7000
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    CACHE 20
    NOORDER;

CREATE TABLE ASSOCIATE_DEFINITION ( 
    ASSOCIATE_DEFINITION_ID   	NUMBER(15) NOT NULL,
    ENTITY_TYPE_DEFINITION_ID	NUMBER(15) NOT NULL,
    ASSOCIATE_NAME            	VARCHAR2(50) NOT NULL,
    ASSOCIATE_INDEX            	NUMBER(10) NOT NULL,
    ASSOCIATE_DESCRIPTION            	VARCHAR2(100) NOT NULL,
    ASSOCIATE_TYPE_DEFINITION_ID 	NUMBER(15) NOT NULL,
    ASSOCIATE_TYPE_OVERRIDEN 	NUMBER(1) NOT NULL,
    MULTIPLICITY 	NUMBER(1) NOT NULL,
    MULTIPLICITY_OVERRIDEN 	NUMBER(1) NOT NULL,
    ASSOCIATION_TYPE 	NUMBER(1) NOT NULL,
    ASSOCIATION_TYPE_OVERRIDEN 	NUMBER(1) NOT NULL,
    LAZY 	NUMBER(1) NOT NULL,
    LAZY_OVERRIDEN 	NUMBER(1) NOT NULL,
	MANDATORY NUMBER(1) NOT NULL,
    MANDATORY_OVERRIDEN     NUMBER(1) NULL,
    HIDDEN               NUMBER(1) NOT NULL,
    HIDDEN_OVERRIDEN     NUMBER(1) NULL,
    EDITABLE 	NUMBER(1) NOT NULL,
    EDITABLE_OVERRIDEN 	NUMBER(1) NOT NULL,
    COPY 	NUMBER(1) NOT NULL,
    COPY_OVERRIDEN 	NUMBER(1) NOT NULL,
    DEFAULT_INSTANCE    NUMBER(15) NULL,
	DEFAULT_INSTANCE_OVERRIDEN    NUMBER(1) NOT NULL,
    INHERITED              NUMBER(1) NOT NULL,
    CAN_EDIT_DEFINITION     NUMBER(1) NOT NULL,
    CAN_DELETE_DEFINITION     NUMBER(1) NOT NULL,
    CATEGORY_OVERRIDEN          	NUMBER(1,0) NULL,
    CATEGORY                    	VARCHAR2(200) NULL,
    CONSTRAINT ASSOCIATE_DEF_PK PRIMARY KEY(ASSOCIATE_DEFINITION_ID)
);

CREATE SEQUENCE ASSOCDEFID_SEQ
    INCREMENT BY 1
    START WITH 5000
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    CACHE 20
    NOORDER;
    
 CREATE TABLE ASSOCIATE_DEF_VALID_VALUES (
    ASSOCIATE_DEFINITION_ID     NUMBER(15,0) NOT NULL,
    ENTITY_TYPE_INSTANCE_ID     NUMBER(15,0) NOT NULL
    );

CREATE TABLE ENTITY_TYPE_DEFINITION ( 
    ENTITY_TYPE_DEFINITION_ID	NUMBER(15) NOT NULL,
    TYPE_NAME                	VARCHAR2(100) NOT NULL,
    TYPE_DESCRIPTION            VARCHAR2(200),
    ENTITY_TYPE_INSTANCE_CLASS  VARCHAR2(100),
    BASE_ENTITY_TYPE_DEF_ID	NUMBER(15),
    LOOKUP NUMBER(1,0) NULL,
    SYSTEM NUMBER(1,0) NULL,
    CONSTRAINT ENTITY_TYPE_DEF_PK PRIMARY KEY(ENTITY_TYPE_DEFINITION_ID)
);

CREATE SEQUENCE ENTITYTYPEDEFID_SEQ
    INCREMENT BY 1
    START WITH 5000
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    CACHE 20
    NOORDER;
    
    
-- ENTITY TYPE INSTANCE    

CREATE TABLE ENTITY_TYPE_INSTANCE ( 
    ENTITY_TYPE_INSTANCE_ID	NUMBER(15) NOT NULL,
    TYPE_NAME                	VARCHAR2(50) NOT NULL,
    TYPE_DESCRIPTION                	VARCHAR2(100) NOT NULL,
    STATUS NUMBER(1),
    CONSTRAINT ENTITY_TYPE_INST_PK PRIMARY KEY(ENTITY_TYPE_INSTANCE_ID)
);


--alter table ENTITY_TYPE_INSTANCE
--add (STATUS NUMBER(1));

-- update entity_type_instance set status = 1

CREATE SEQUENCE ENTITYTYPEINSTID_SEQ
    INCREMENT BY 1
    START WITH 7000
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    CACHE 20
    NOORDER;

CREATE TABLE PROPERTY ( 
    ENTITY_TYPE_INSTANCE_ID	NUMBER(15) NOT NULL,
    PROPERTY_NAME            	VARCHAR2(50) NOT NULL,
    VALUE               VARCHAR2(1000) NULL,
    CONSTRAINT PROPERTY_PK PRIMARY KEY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME)
);

drop table associate_contact;
drop table ACCOUNT_ASSOCIATES;
drop table RESPONSIBILITY_LIABILITY;
drop table Guarantee;
DROP TABLE ASSOCIATE;

CREATE TABLE ASSOCIATE ( 
    ASSOCIATE_ID	NUMBER(15) NOT NULL,
    ENTITY_TYPE_INSTANCE_ID	NUMBER(15) NOT NULL,
    ASSOCIATE_NAME            	VARCHAR2(50) NOT NULL,
    TYPE_NAME               	VARCHAR2(50) NOT NULL,
    TYPE_DESCRIPTION               	VARCHAR2(100) NOT NULL,
    ASSOCIATION_TYPE               	NUMBER(1) NOT NULL,
    CONSTRAINT ASSOCIATE_PK PRIMARY KEY(ASSOCIATE_ID)
);

CREATE SEQUENCE ASSOCIATEID_SEQ
    INCREMENT BY 1
    START WITH 7000
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    CACHE 20
    NOORDER;

CREATE TABLE UNIQUE_ASSOCIATE ( 
    ASSOCIATE_ID	NUMBER(15) NOT NULL,
    VALUE_ENTITY_TYPE_INSTANCE_ID	NUMBER(15),
    CONSTRAINT UNIQUE_ASSOCIATE_PK PRIMARY KEY(ASSOCIATE_ID)
);

CREATE TABLE COLLECTION_ASSOCIATE ( 
    ASSOCIATE_ID	NUMBER(15) NOT NULL,
    CONSTRAINT COLLECTION_ASSOCIATE_PK PRIMARY KEY(ASSOCIATE_ID)
);

CREATE TABLE COLLECTION_ASSOCIATE_VALUES ( 
    ASSOCIATE_ID	NUMBER(15) NOT NULL,
    COLLECTION_VALUE_INDEX NUMBER(15) NOT NULL,
    ENTITY_TYPE_INSTANCE_ID NUMBER(15) NOT NULL,
    CONSTRAINT COLLECTION_ASSOCIATE_VALUES_PK PRIMARY KEY(ASSOCIATE_ID, COLLECTION_VALUE_INDEX)
);

-- ENTITY TYPE INSTANCE TABLES

CREATE TABLE LOAN_APPLICATION( 
	LOAN_APPLICATION_ID NUMBER(15,0),
	CONTRACT_ID NUMBER(15),
	CONSTRAINT LOAN_APP_ID_PK PRIMARY KEY(LOAN_APPLICATION_ID)
); 

CREATE TABLE LOAN_CONTRACT (
    CONTRACT_ID NUMBER(15,0) NOT NULL,
    CONSTRAINT LOAN_CONTRACT_ID_PK PRIMARY KEY(CONTRACT_ID)
);

CREATE TABLE LOAN_PRODUCT (
    PRODUCT_ID NUMBER(15) NOT NULL,
    CONSTRAINT LOAN_PRODUCT_ID_PK PRIMARY KEY(PRODUCT_ID)
);

CREATE TABLE AUTO_DRAFT ( 
    AUTO_DRAFT_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT AUTO_DRAFT_PK PRIMARY KEY(AUTO_DRAFT_ID)
);

CREATE TABLE COUPON_BOOK ( 
    COUPON_BOOK_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT COUPON_BOOK_PK PRIMARY KEY(COUPON_BOOK_ID)
);

CREATE TABLE BILLING_NOTICE ( 
    BILLING_NOTICE_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT BILLING_NOTICE_PK PRIMARY KEY(BILLING_NOTICE_ID)
);

CREATE TABLE AMORTIZED_INTEREST_CALCULATION  (
   INT_CALC_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT AMORTIZED_INT_CALCN_PK PRIMARY KEY(INT_CALC_ID)
);


CREATE TABLE CALL_REPORT_CODE  (
   CALL_REPORT_CODE_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT CALL_REPORT_CODE_PK PRIMARY KEY(CALL_REPORT_CODE_ID)
);

CREATE TABLE COLLATERAL_NEW  (
   COLLATERAL_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT COLLATERAL_NEW_PK PRIMARY KEY(COLLATERAL_ID)
);

CREATE TABLE COLLATERAL_APPRAISAL_NEW  (
    APPRAISAL_ID NUMBER(15,0) NOT NULL,
    CONSTRAINT COLLATERAL_APPRAISAL_NEW_PK PRIMARY KEY(APPRAISAL_ID)
);

CREATE TABLE  COLLATERAL_CODE (
    COLLATERAL_CODE_ID NUMBER(15,0) NOT NULL,
    CONSTRAINT COLLATERAL_CODE_PK PRIMARY KEY(COLLATERAL_CODE_ID)
);

CREATE TABLE  DEALER_AGENCY (
   AGENCY_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT DEALER_AGENCY_PK PRIMARY KEY(AGENCY_ID)
);

CREATE TABLE  DEALER_PARTICIPATION (
   DL_PART_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT DEALER_PARTICIPATION_PK PRIMARY KEY(DL_PART_ID)
);

CREATE TABLE DEFFERED_INCOME_EXPENSE  (
    DEFFERED_INC_EXP_ID NUMBER(15,0) NOT NULL,
    CONSTRAINT DEFFERED_INCOME_EXPENSE_PK PRIMARY KEY(DEFFERED_INC_EXP_ID)
);

CREATE TABLE DISC_INTEREST_CALCULATION (
    INT_CALC_ID NUMBER(15,0) NOT NULL,
    CONSTRAINT DISC_INTEREST_CALCULATION_PK PRIMARY KEY(INT_CALC_ID)
);


CREATE TABLE DISTRIBUTION_HEAD (
    DISTRIBUTION_HEAD_ID NUMBER(15,0) NOT NULL,
    CONSTRAINT DISTRIBUTION_HEAD_PK PRIMARY KEY(DISTRIBUTION_HEAD_ID)
);


CREATE TABLE ESCROW_DETAIL (
    ESCROW_ID NUMBER(15,0) NOT NULL,
    NEXT_DISBURSEMENT_DATE DATE,
   CONSTRAINT ESCROW_DETAIL_PK PRIMARY KEY(ESCROW_ID)
);


CREATE TABLE ESCROW_DISBURSEMENT  (
  DISBURSEMENT_ID   NUMBER(15,0) NOT NULL,
    CONSTRAINT ESCROW_DISBURSEMENT_PK PRIMARY KEY(DISBURSEMENT_ID)
);

CREATE TABLE  EXAMINER_CLASSIFICATION (
   EXAMINER_CLASSIFICATION_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT EXAMINER_CLASSIFICATION_PK PRIMARY KEY(EXAMINER_CLASSIFICATION_ID)
);

CREATE TABLE  EXTERNAL_AGENCY(
   AGENCY_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT EXTERNAL_AGENCY_PK PRIMARY KEY(AGENCY_ID)
);

CREATE TABLE FIXED_LOAN_INTEREST (
    FIXED_LOAN_INTEREST_ID NUMBER(15,0) NOT NULL,
    CONSTRAINT FIXED_LOAN_INTEREST_PK PRIMARY KEY(FIXED_LOAN_INTEREST_ID)
);


CREATE TABLE  FLOAT_INTEREST_RATE_PENALTY (
    PENALTY_ID NUMBER(15,0) NOT NULL,
    CONSTRAINT FLOAT_INT_RATE_PENALTY_PK PRIMARY KEY(PENALTY_ID)
);

CREATE TABLE  FLOAT_PENALTY_RATE (
   RATE_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT FLOAT_PENALTY_RATE_PK PRIMARY KEY(RATE_ID)
);

CREATE TABLE  GL_ALLOCATION (
   GL_ALLOC_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT GL_ALLOCATION_PK PRIMARY KEY(GL_ALLOC_ID)
);

CREATE TABLE IRREGULAR_PAYMENT_SCHEDULE (
   SCHEDULE_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT IRREGULAR_PAYMENT_SCHEDULE_PK PRIMARY KEY(SCHEDULE_ID)
);

CREATE TABLE  LATE_CHARGE_NEW (
   LATE_CHARGE_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT LATE_CHARGE_NEW_PK PRIMARY KEY(LATE_CHARGE_ID)
);


CREATE TABLE  LOAN_ADVANCE (
   ADVANCE_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT LOAN_ADVANCE_PK PRIMARY KEY(ADVANCE_ID)
);


CREATE TABLE LOAN_OFFICER (
    OFFICER_ID NUMBER(15,0) NOT NULL,
    CONSTRAINT LOAN_OFFICER_PK PRIMARY KEY(OFFICER_ID)
);

CREATE TABLE LOAN_REPAYMENT (
    REPAYMENT_ID NUMBER(15,0) NOT NULL,
    CONSTRAINT LOAN_REPAYMENT_PK PRIMARY KEY(REPAYMENT_ID)
);

CREATE TABLE  PARTICIPANT_BANK (
    BANK_ID NUMBER(15,0) NOT NULL,
    CONSTRAINT PARTICIPANT_BANK_PK PRIMARY KEY(BANK_ID)
);


CREATE TABLE PAST_DUE_PARAMETERS  (
   PARAM_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT PAST_DUE_PARAMETERS_PK PRIMARY KEY(PARAM_ID)
);


CREATE TABLE PAYMENT_ADJUSTMENT  (
    ADJUSTMENT_ID NUMBER(15,0) NOT NULL,
    CONSTRAINT PAYMENT_ADJUSTMENT_PK PRIMARY KEY(ADJUSTMENT_ID)
);

CREATE TABLE PAYMENT_ADJUSTMENT_HISTORY  (
  ADJUSTMENT_ID   NUMBER(15,0) NOT NULL,
    CONSTRAINT PAYMENT_ADJST_HIS_PK PRIMARY KEY(ADJUSTMENT_ID)
);


CREATE TABLE PAYMENT_SCHEDULE  (
   SCHEDULE_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT PAYMENT_SCHEDULE_PK PRIMARY KEY(SCHEDULE_ID)
);

CREATE TABLE PAYOFF  (
   PAYOFF_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT PAYOFF_PK PRIMARY KEY(PAYOFF_ID)
);

CREATE TABLE  PENALTY (
   PENALTY_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT PENALTY_PK PRIMARY KEY(PENALTY_ID)
);

CREATE TABLE POSTING_SEQUENCE (
    POSTING_SEQUENCE_ID NUMBER(15,0) NOT NULL,
    CONSTRAINT POSTING_SEQ_PK PRIMARY KEY(POSTING_SEQUENCE_ID)
);

CREATE TABLE RATE_ADJUSTMENT  (
   RATE_ADJUSTMENT_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT RATE_ADJUSTMENT_PK PRIMARY KEY(RATE_ADJUSTMENT_ID)
);


CREATE TABLE RATE_INDEX  (
   RATE_INDEX_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT RATE_INDEX_PK PRIMARY KEY(RATE_INDEX_ID)
);


CREATE TABLE RATE_INDEX_HISTORY ( 
	RATE_INDEX_HISTORY_ID	NUMBER(15,0) NOT NULL ,
	CONSTRAINT RATE_INDEX_HISTORY_ID_PK	PRIMARY KEY (RATE_INDEX_HISTORY_ID)
	);

CREATE TABLE REGION  (
   REGION_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT REGION_PK PRIMARY KEY(REGION_ID)
);

CREATE TABLE REGULAR_PAYMENT_SCHEDULE (
    SCHEDULE_ID NUMBER(15,0) NOT NULL,
    CONSTRAINT REGULAR_PAYMENT_SCHEDULE_PK PRIMARY KEY(SCHEDULE_ID)
);


CREATE TABLE  REPAYMENT_MODE (
   REPAYMENT_MODE_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT REPAYMENT_MODE_PK PRIMARY KEY(REPAYMENT_MODE_ID)
);

CREATE TABLE SIMPLE_INTEREST_CALCULATION (
   INT_CALC_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT SIMPLE_INTEREST_CALCULATION_PK PRIMARY KEY(INT_CALC_ID)
);

CREATE TABLE VARIABLE_LOAN_INTEREST (
   VARIABLE_LOAN_INTEREST_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT VARIABLE_LOAN_INT_PK PRIMARY KEY(VARIABLE_LOAN_INTEREST_ID)
);

CREATE TABLE NON_ESCROW_INSURANCE (
   NON_ESCROW_INSURANCE_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT NON_ESCROW_INSURANCE_ID_PK PRIMARY KEY(NON_ESCROW_INSURANCE_ID)
);

CREATE TABLE PROPERTY_COLLATERAL_NEW  (
   PROPERTY_COLLATERAL_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT PROPERTY_COLLATE_ID_PK PRIMARY KEY(PROPERTY_COLLATERAL_ID)
);


-- INDEXES

CREATE INDEX ENTITYTYPEDEF_TYPENAME_IDX
    ON ENTITY_TYPE_DEFINITION(TYPE_NAME)
;
CREATE INDEX ENTITYTYPEDEF_TYPENAMEDESC_IDX
    ON ENTITY_TYPE_DEFINITION(TYPE_NAME, TYPE_DESCRIPTION)
;

CREATE INDEX PROPERTYTYPEDEF_PROPNAME_IDX
    ON PROPERTY_DEFINITION(PROPERTY_NAME)
;

CREATE INDEX PROPERTYTYPEDEF_EPROPNAME_IDX
    ON PROPERTY_DEFINITION(ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME)
;

CREATE INDEX ASSOCTYPEDEF_ASSOCNAME_IDX
    ON ASSOCIATE_DEFINITION(ASSOCIATE_NAME)
;

CREATE INDEX ASSOCTYPEDEF_EASSOCNAME_IDX
    ON ASSOCIATE_DEFINITION(ENTITY_TYPE_DEFINITION_ID, ASSOCIATE_NAME)
;

CREATE INDEX ENTITYTYPEINST_TYPENAME_IDX
    ON ENTITY_TYPE_INSTANCE(TYPE_NAME)
;

CREATE INDEX ENTITYTYPEINST_TYPENAMEDES_IDX
    ON ENTITY_TYPE_INSTANCE(TYPE_NAME, TYPE_DESCRIPTION)
;

CREATE INDEX PROPERTY_PROPNAME_IDX
    ON PROPERTY(PROPERTY_NAME)
;

CREATE INDEX ASSOCIATE_ASSOCNAME_IDX
    ON ASSOCIATE(ASSOCIATE_NAME)
;

--CREATE INDEX COLLASSOCIATEVALS_INDEX_IDX
 --   ON COLLECTION_ASSOCIATE_VALUES(ASSOCIATE_ID, COLLECTION_VALUE_INDEX)
--;



CREATE TABLE LOAN_APPLICATION_EVENT ( 
	ID              	NUMBER(15,5) NULL,
	INSTITUTION_ID  	VARCHAR2(10) NULL,
	BRANCH_ID       	VARCHAR2(25) NULL,
	REFERENCE_NUMBER	VARCHAR2(50) NULL,
	ORIGINATION_DATE	DATE NULL,
	BORROWER_NAME   	VARCHAR2(50) NULL,
	OFFICER_CODE    	VARCHAR2(200) NULL,
	LOAN_AMOUNT     	NUMBER(15,5) NULL,
	ACCOUNT_NUMBER  	NUMBER(15) NULL 
	);




CREATE SEQUENCE LOAN_APPLICATION_EVENT_SEQ
    INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    CACHE 20
    NOORDER;

CREATE TABLE EARNING_EXPENSES_HISTORY (
    EARN_EXPE_HISTORY_ID NUMBER(15,0) NOT NULL,
    CONSTRAINT EARN_EXPE_HISTORY_ID_PK PRIMARY KEY(EARN_EXPE_HISTORY_ID)
);

CREATE TABLE ARM_TYPE (
    ARM_TYPE_ID NUMBER(15,0) NOT NULL,
    CONSTRAINT ARM_TYPE_ID_PK PRIMARY KEY(ARM_TYPE_ID)
);

CREATE TABLE VARIABLE_TYPE (
    VARIABLE_TYPE_ID NUMBER(15,0) NOT NULL,
    CONSTRAINT VARIABLE_TYPE_ID_PK PRIMARY KEY(VARIABLE_TYPE_ID)
);

CREATE TABLE INSURANCE_TAX (
    INSURANCE_TAX_ID NUMBER(15,0) NOT NULL,
    CONSTRAINT INSURANCE_TAX_ID_PK PRIMARY KEY(INSURANCE_TAX_ID)
);

CREATE TABLE INSURANCE_ESCROW (
    INSURANCE_ESCROW_ID NUMBER(15,0) NOT NULL,
    CONSTRAINT INSURANCE_ESCROW_ID_PK PRIMARY KEY(INSURANCE_ESCROW_ID)
);

CREATE TABLE AH_LIFE_INSURANCE (
    AH_LIFE_INS_ID NUMBER(15,0) NOT NULL,
    CONSTRAINT AH_LIFE_INS_ID_PK PRIMARY KEY(AH_LIFE_INS_ID)
);

CREATE TABLE RATE_CHANGE_HISTORY (
    RATE_CHG_HISTORY_ID NUMBER(15,0) NOT NULL,
    CONSTRAINT RATE_CHG_HISTORY_ID_PK PRIMARY KEY(RATE_CHG_HISTORY_ID)
);

CREATE TABLE SINGLE_PAY_SCHEDULE (
    SINGLE_PAY_SCHEDULE_ID NUMBER(15,0) NOT NULL,
    CONSTRAINT SINGLE_PAY_SCHEDULE_ID_PK PRIMARY KEY(SINGLE_PAY_SCHEDULE_ID)
);

CREATE TABLE DEMAND_NOTE_SCHEDULE (
    DEMAND_NOTE_SCHEDULE_ID NUMBER(15,0) NOT NULL,
    CONSTRAINT DEMAND_NOTE_SCHEDULE_ID_PK PRIMARY KEY(DEMAND_NOTE_SCHEDULE_ID)
);

CREATE TABLE ALTERNATE_PAYMENT_SCHEDULE (
    ALTERNATE_PAY_SCHEDULE_ID NUMBER(15,0) NOT NULL,
    CONSTRAINT ALTERNATE_PAY_SCHEDULE_ID_PK PRIMARY KEY(ALTERNATE_PAY_SCHEDULE_ID)
);