INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1801, '1801', null, '2','0', 'Principal');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1802, '1802', null, '2','0', 'Late Charge');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1803, '1803', null, '2', '0', 'Escrow');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1804, '1804', null, '2', '0', 'Other Fees');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1805, '1805', null, '2', '0', 'Interest');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1806, '1806', null, '2', '0', 'NonEscrow');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1807, '1807', null, '2', '0', 'Credit Life');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1808, '1808', null, '2', '0', 'Accidental Health Life');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1809, '1809', null, '2', '0', 'UnApplied Fund');

--monetary credit entry types
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1901, '1901', null, '2', null, 'Principal');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1902, '1902', null, '2', null, 'Late Charge');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1903, '1903', null, '2', null, 'Escrow');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1904, '1904', null, '2', null, 'Other Fees');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1905, '1905', null, '2', null, 'Interest');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1906, '1906', null, '2', null, 'NonEscrow');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1907, '1907', null, '2', null, 'Credit Life');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1908, '1908', null, '2', null, 'Accidental Health Life');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1909, '1909', null, '2', null, 'UnApplied Fund');

--IL (RO78) loan transactions
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1525, '1525', null, '2', 1, 'Regular Payment');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1502, '1502', null, '2', 0, 'Initial Funding');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1511, '1511', null, '2', 1, 'Curtailment - True');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1538, '1538', null, '2', 1, 'Late Charge Payment');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1528, '1528', null, '2', 1, 'Curtailment - Non True');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1544, '1544', null, '2', 1, 'Loan Payoff');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1512, '1512', null, '2', 0, 'Reject Transaction');

--reversal
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1518, '1518', null, '2', 0, 'Regular Payment Reversal');



--SIL loan transactions
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1744, '1744', null, '2', 1, 'Loan Payoff');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(17010, '17010', null, '2', 0, 'Initial Funding');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1751, '1751', null, '2', 0, 'Advance');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1736, '1736', null, '2', 1, 'Credit Life Payment');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1737, '1737', null, '2', 1, 'A&H Payment');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1732, '1732', null, '2', 1, 'Interest Payment');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1725, '1725', null, '2', 1, 'Regular Payment');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1728, '1728', null, '2', 1, 'Regular Payment - Future');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1799, '1799', null, '2', 1, 'Apply Future Payment');


--Mortgage loan transactions
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(19020, '19020', null, '2', 0, 'Initial Funding');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(11002, '11002', null, '2', 0, 'Escrow Disbursment');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1301, '1301', null, '2', 1, 'Curtailment -True');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1951, '1951', null, '2', 1, 'Loan Payoff');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1501, '1501', null, '2', 1, 'Escrow Payment');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(11101, '11101', null, '2', 1, 'Regular Payment');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1701, '1701', null, '2', 1, 'Regular Payment');


INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(21207, '21207', null, '2', 0, 'Debit Memo - Principal');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(31207, '31207', null, '2', 1, 'Credit Memo - Principal');

INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(23207, '23207', null, '2', 0, 'Debit Memo - Escrow');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(33207, '33207', null, '2', 1, 'Credit Memo - Escrow');

INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(24207, '24207', null, '2', 0, 'Debit Memo - Other Fee');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(34207, '34207', null, '2', 1, 'Credit Memo - Other Fee');


INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(21208, '21208', null, '2', 0, 'Debit Memo - Principal');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(31208, '31208', null, '2', 1, 'Credit Memo - Principal');

INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(23208, '23208', null, '2', 0, 'Debit Memo - Escrow');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(33208, '33208', null, '2', 1, 'Credit Memo - Escrow');

INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(24208, '24208', null, '2', 0, 'Debit Memo - Other Fee');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(34208, '34208', null, '2', 1, 'Credit Memo - Other Fee');


INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(21110, '21110', null, '2', 0, 'Debit Memo - Principal');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(31110, '31110', null, '2', 1, 'Credit Memo - Principal');

INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(23110, '23110', null, '2', 0, 'Debit Memo - Escrow');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(33110, '33110', null, '2', 1, 'Credit Memo - Escrow');

INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(24110, '24110', null, '2', 0, 'Debit Memo - Other Fee');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(34110, '34110', null, '2', 1, 'Credit Memo - Other Fee');

INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(17110, '17110', null, '2', 1, 'Curtailment -True');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(17111, '17111', null, '2', 1, 'Late Chagre Payment');

INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1810, '1810', null, '2', 0, 'Dealer Interest');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1910, '1910', null, '2', 1, 'Dealer Interest');



