CREATE TABLE EVENT_TYPE(   
	EVENT_TYPE_ID VARCHAR2(30),
	EVENT_TYPE_NAME VARCHAR2(100),	
	EVENT_TYPE_GROUP_ID VARCHAR2(100),
	CONSTRAINT EVENT_TYPE_PRIMARYK PRIMARY KEY(EVENT_TYPE_ID)); 

CREATE TABLE LOAN_ACCOUNT_HISTORY_ITEM (
    TRANSACTION_ID NUMBER(20),
    CURRENCY VARCHAR2(15),
    AMOUNT NUMBER(20,5),
    ACCOUNT_ID VARCHAR2(30),
    DESCRIPTION VARCHAR2(100),    
    POST_DATE   DATE,
    EFFECTIVE_DATE DATE,
    TRAN_CODE  VARCHAR2(10),
    PARENT_TRAN_CODE VARCHAR2(10),
    INSTITUTION_ID VARCHAR2(25), 
	LOAN_ENTRY_TYPE_ID NUMBER(15),
	CHEQUE NUMBER(10),
	SEQUENCE_NO NUMBER(10),	
    EVENT_TYPE_ID VARCHAR2(30),
	ENTRY_DATE DATE,
    REASON_ID NUMBER(10),
	PARENT_TRANSACTION_ID NUMBER(20),
	TRANSACTION_DETAILS VARCHAR2(150),
    IS_REVERSABLE NUMBER(1),
    CONSTRAINT LOAN_ACCHISTITEM_PK PRIMARY KEY(TRANSACTION_ID)
);


CREATE TABLE LOAN_POSTBLE_ACC_HISTORY_ITEM (
    TRANSACTION_ID NUMBER(20),
    CURRENCY VARCHAR2(15),
    AMOUNT NUMBER(20,5),
    ACCOUNT_ID VARCHAR2(30),
    DESCRIPTION VARCHAR2(100),    
    POST_DATE   DATE,
    EFFECTIVE_DATE	DATE,
    POSTED_TO     NUMBER(5,0),
    TRAN_CODE  VARCHAR2(10),
    INSTITUTION_ID VARCHAR2(25), 
    PARENT_TRANSACTION_ID NUMBER(20),
    EVENT_TYPE_ID VARCHAR2(30),
    REASON_ID NUMBER(10),
    IS_REVERSABLE NUMBER(1),
    CONSTRAINT POSTABLE_ACCHISTITEM_PK PRIMARY KEY(TRANSACTION_ID)
);


CREATE TABLE LOAN_ENTRY_TYPE ( 
    UNIQUE_ID      	NUMBER(15,0) NOT NULL,
    ID             	VARCHAR2(10),    
    INSTITUTION_ID 	VARCHAR2(10),
    ACCOUNT_CATEGORY  VARCHAR2(20),
    ACCOUNT_TYPE_ID VARCHAR2(30),
    TRAN_TYPE_GROUP_ID VARCHAR2(100),
    EVENT_TYPE_ID VARCHAR2(30),
    DISTRIBUTION_RULE_ID NUMBER(15,0),
    DEBIT_OR_CREDIT	VARCHAR2(1),
    DESCRIPTION    	VARCHAR2(100),
    IS_MONETARY		NUMBER(1),
    REASON_ID NUMBER(10),	
    TRAN_INDICATOR NUMBER(1),
    CONSTRAINT LOAN_ENTRY_TYPE_PRIMARYK PRIMARY KEY(UNIQUE_ID)
);

CREATE TABLE LOAN_ENTRY_TYPE_LINK (    
    ENTRY_TYPE_ID   VARCHAR2(10) NULL,
    CHILD_ENTRY_TYPE_ID   VARCHAR2(10) NULL              
);

CREATE TABLE BSV_TRANSACTION_TYPE(
   UNIQUE_ID NUMBER(15),
   TRAN_CODE VARCHAR2(30),
   INSTITUTION_ID VARCHAR2(25),
   ACCOUNT_TYPE_ID VARCHAR2(30),
   ENTRY_TYPE_ID NUMBER(15)
);


CREATE TABLE LOAN_LEDGER_POSTING_PARAMETERS(
   	UNIQUE_ID NUMBER(15),
	INSTITUTION_ID VARCHAR2(25),
	ENTRY_TYPE_ID VARCHAR2(10),
    ACCOUNT_TYPE_ID VARCHAR2(30),
    AFFECTS_DATE_LAST_ACTIVITY NUMBER(1),
	AFFECTS_ORIG_LOAN_BALANCE NUMBER(1),
	AFFECTS_PRINCIPAL_BALANCE NUMBER(1),
	AFFECTS_PRINCIPAL_DUE NUMBER(1),
	AFFECTS_INTEREST_DUE NUMBER(1),
	AFFECTS_ESCROW_DUE NUMBER(1),
	AFFECTS_ESCROW_BALANCE NUMBER(1),
	AFFECTS_NONESCROW_DUE NUMBER(1),
    AFFECTS_NONESCROW_BALANCE NUMBER(1),
    AFFECTS_BANK_REBATE NUMBER(1),    
	AFFECTS_CREDIT_LIFE_DUE NUMBER(1),
    AFFECTS_CREDIT_LIFE_PREMIUM NUMBER(1),
    AFFECTS_CREDIT_LIFE_REBATE NUMBER(1),    
	AFFECTS_ACC_HEALTH_DUE NUMBER(1),
    AFFECTS_ACC_HEALTH_PREMIUM NUMBER(1),
    AFFECTS_ACC_HEALTH_REBATE NUMBER(1),    
	AFFECTS_OTHER_FEE_DUE NUMBER(1),    
	AFFECTS_COLLATERAL_INS_DUE NUMBER(1),
    AFFECTS_COLLATERAL_INS_PREMIUM NUMBER(1),
    AFFECTS_COLLATERAL_INS_REBATE NUMBER(1),
    AFFECTS_UNAPPLIED_FUND NUMBER(1),
	AFFECTS_PARTIAL_PAYMENT NUMBER(1),
	AFFECTS_COLL_LATE_CHARGE NUMBER(1),
	AFFECTS_UNCOLL_LATE_CHARGE NUMBER(1),
	AFFECTS_WAIVED_LATE_CHARGE NUMBER(1),
	AFFECTS_DATE_LAST_TRANSACTION NUMBER(1),
	AFFECTS_DATE_NEXT_DUE NUMBER(1),
    AFFECTS_LINE_OF_CREDIT NUMBER(1),
	AFFECTS_UNUSED_LINE_OF_CREDIT NUMBER(1),
	AFFECTS_NET_PAYOFF NUMBER(1),
	AFFECTS_PAYMENT_MAID NUMBER(1),
	AFFECTS_RETURNED_CHECKS NUMBER(1),
	AFFECTS_INTEREST_YTD NUMBER(1),
    AFFECTS_INTEREST_MTD NUMBER(1),
    AFFECTS_INTEREST_LTD NUMBER(1),
    AFFECTS_ACCRUED_INTEREST NUMBER(1),       
    AFFECTS_LOAN_STATUS NUMBER(1),
    AFFECTS_PAYOUT_CODE NUMBER(1),
    AFFECTS_DATE_CLOSED NUMBER(1),
	AFFECTS_NEXTESCROWDISBURSEDATE NUMBER(1),
	AFFECTS_PRINCIPAL_PAID_TO_DATE NUMBER(1),
	AFFECTS_INTEREST_PAID_TO_DATE NUMBER(1),
	AFFECTS_FUTURE_PAYMENT_COUNT NUMBER(1),
	CONSTRAINT LOANLEDGER_POST_PARAM_PRIMARYK PRIMARY KEY(UNIQUE_ID)
);


CREATE TABLE DISTRIBUTION_RULE ( 
        DISTRIBUTION_RULE_ID	NUMBER(15,0) NULL,
        DISTRIBUTION_TYPE_ID	VARCHAR2(30) NULL, 
        CONSTRAINT DISTRIBUTION_RULE_PRIMARYK PRIMARY KEY(DISTRIBUTION_RULE_ID));

CREATE TABLE PERCENTAGE_DISTRIBUTION_RULE (
	DISTRIBUTION_RULE_ID NUMBER(15),
        ENTRY_TYPE_ID VARCHAR2(30),
        PERCENTAGE NUMBER(10)
);

CREATE TABLE DUE_DISTRIBUTION_RULE (
	DISTRIBUTION_RULE_ID NUMBER(15),
        ENTRY_TYPE_ID VARCHAR2(30),
        POSTING_SEQUENCE NUMBER(10),
        MONEY NUMBER(10)
);

CREATE TABLE LOAN_TRANSACTION_POSTTODAY(
        TRANSACTION_ID NUMBER(15,0),
        AMOUNT NUMBER(20,5),
        TRANS_CODE VARCHAR2(10),
        LOAN_ENTRY_TYPE_ID NUMBER(15),
        INSTITUTION_ID VARCHAR2(30),
        ACCOUNT_NUMBER VARCHAR2(30),
        ACCOUNT_ID VARCHAR2(30),
        ACCOUNT_TYPE VARCHAR2(30),
        DESCRIPTION VARCHAR2(100),
        EFFECTIVE_DATE DATE,
        ENTRY_DATE DATE,
        POST_STATUS NUMBER,
        REASON_ID VARCHAR2(10),
        REASON_DESCRIPTION VARCHAR2(200),
        REASON_DETAIL VARCHAR2(200),
        CONSTRAINT LOAN_TRAN_POSTTODAY_PRIMARYK PRIMARY KEY(TRANSACTION_ID));

CREATE TABLE DELQ_BILLING_BUCKET_NEW ( 
    DELQ_BILL_ID    	NUMBER(20,0) NULL,
	ACCOUNT_ID          VARCHAR2(30),   
    BUCKET_NUMBER       NUMBER(20,5) NULL,
    PAST_DUE_DATE   	DATE NULL,
    BILLED_PRINCIPAL	NUMBER(20,5) NULL,
    BILLED_INTEREST 	NUMBER(20,5) NULL,
    BILLED_ESCROW   	NUMBER(20,5) NULL,
	NON_ESCROW_DUE 		NUMBER(20,5) NULL,
    PAID_DATE       	DATE NULL 
    );

CREATE SEQUENCE DELQ_BILL_ID_SEQ;

-- LOAN ACCOUNT HISTORY ITEM
create index lahi_account_id_indx ON LOAN_ACCOUNT_HISTORY_ITEM(ACCOUNT_ID);
create index lahi_parent_tran_id_indx ON LOAN_ACCOUNT_HISTORY_ITEM(PARENT_TRANSACTION_ID);


-- DELINQUENT BILLING BUCKET

create index delq_account_id_indx ON DELQ_BILLING_BUCKET_NEW(ACCOUNT_ID);
create index delq_bill_id_indx ON DELQ_BILLING_BUCKET_NEW(DELQ_BILL_ID);

-- BILLING BUCKET
create index billing_account_id_indx ON BILLING_BUCKET(ACCOUNT_ID);
create index billing_bucket_number_indx ON BILLING_BUCKET(BILLING_BUCKET_NUMBER);

-- added for statements 
CREATE OR REPLACE VIEW LOAN_ACCOUNT_HISTORY_ITEM_VW AS SELECT * FROM LOAN_ACCOUNT_HISTORY_ITEM;

