ALTER TABLE "VALUE_TYPE_DEFINITION"
	ADD ( "SQL_TYPE" NUMBER(15,5) NULL, 
	"CHARACTER_LIMIT" NUMBER(15,5) NULL ); 

UPDATE "VALUE_TYPE_DEFINITION"
SET "SQL_TYPE"=0, "CHARACTER_LIMIT"=19
WHERE "VALUE_TYPE_DEFINITION_ID"=0;

UPDATE "VALUE_TYPE_DEFINITION"
SET "SQL_TYPE"=0, "CHARACTER_LIMIT"=18
WHERE "VALUE_TYPE_DEFINITION_ID"=1;

UPDATE "VALUE_TYPE_DEFINITION"
SET "SQL_TYPE"=1, "CHARACTER_LIMIT"=19
WHERE "VALUE_TYPE_DEFINITION_ID"=2;

UPDATE "VALUE_TYPE_DEFINITION"
SET "SQL_TYPE"=1, "CHARACTER_LIMIT"=18
WHERE "VALUE_TYPE_DEFINITION_ID"=3;

UPDATE "VALUE_TYPE_DEFINITION"
SET "SQL_TYPE"=1, "CHARACTER_LIMIT"=32
WHERE "VALUE_TYPE_DEFINITION_ID"=4;

UPDATE "VALUE_TYPE_DEFINITION"
SET "SQL_TYPE"=2, "CHARACTER_LIMIT"=25
WHERE "VALUE_TYPE_DEFINITION_ID"=5;

UPDATE "VALUE_TYPE_DEFINITION"
SET "SQL_TYPE"=0, "CHARACTER_LIMIT"=29
WHERE "VALUE_TYPE_DEFINITION_ID"=6;

UPDATE "VALUE_TYPE_DEFINITION"
SET "SQL_TYPE"=0, "CHARACTER_LIMIT"=42
WHERE "VALUE_TYPE_DEFINITION_ID"=7;

UPDATE "VALUE_TYPE_DEFINITION"
SET "SQL_TYPE"=1, "CHARACTER_LIMIT"=33
WHERE "VALUE_TYPE_DEFINITION_ID"=8;

UPDATE "VALUE_TYPE_DEFINITION"
SET "SQL_TYPE"=0, "CHARACTER_LIMIT"=18
WHERE "VALUE_TYPE_DEFINITION_ID"=9;

UPDATE "VALUE_TYPE_DEFINITION"
SET "SQL_TYPE"=0, "CHARACTER_LIMIT"=35
WHERE "VALUE_TYPE_DEFINITION_ID"=10;

UPDATE "VALUE_TYPE_DEFINITION"
SET "SQL_TYPE"=0, "CHARACTER_LIMIT"=38
WHERE "VALUE_TYPE_DEFINITION_ID"=11;

--update ENTITY_TYPE_DEFINITION set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.SinglePaySchedule'
--where TYPE_NAME like '%SinglepaySchedule%';






























