--update PROPERTY_DEFINITION set HIDDEN = 1 where PROPERTY_NAME = 'RoundingFactor';

ALTER TABLE ASSOCIATE_DEFINITION
        ADD ( "TEMPLATE" VARCHAR2(200) NULL,
        "TEMPLATE_OVERRIDEN" NUMBER(1,0) NULL );


ALTER TABLE LOAN_APPLICATION add (GENERAL_LEDGER_ENTRIES_ID NUMBER(15,0) NULL);

ALTER TABLE LOAN_ACCOUNT add (GENERAL_LEDGER_ENTRIES_ID NUMBER(15,0) NULL);

ALTER TABLE LOAN_ACCOUNT ADD (ESCROW_BALANCE NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD (LAST_ESCROW_ANALYSIS_DATE DATE);

CREATE TABLE GENERAL_LEDGER_ENTRIES (
    GENERAL_LEDGER_ENTRIES_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT GENERAL_LEDGER_ENTRIES_ID_PK PRIMARY KEY(GENERAL_LEDGER_ENTRIES_ID)
);

CREATE TABLE GENERAL_LEDGER_ENTRY (
    GENERAL_LEDGER_ENTRY_ID  NUMBER(15,0) NOT NULL,
    CONSTRAINT GENERAL_LEDGER_ENTRY_ID_PK PRIMARY KEY(GENERAL_LEDGER_ENTRY_ID)
);



ALTER TABLE ENTITY_TYPE_DEFINITION
        ADD ( "TEMPLATE" VARCHAR2(400) NULL );


--INSERT INTO ENTITY_TYPE_DEFINITION(ENTITY_TYPE_DEFINITION_ID, TYPE_NAME, TYPE_DESCRIPTION, ENTITY_TYPE_INSTANCE_CLASS, BASE_ENTITY_TYPE_DEF_ID, LOOKUP, SYSTEM, TEMPLATE)
--  VALUES(41527, 'GeneralLedgerEntry', 'General Ledger Entry', 'com.vsoftcorp.loan.model.entities.GeneralLedgerEntry', NULL, 0, 0, NULL);
--
--INSERT INTO ENTITY_TYPE_DEFINITION(ENTITY_TYPE_DEFINITION_ID, TYPE_NAME, TYPE_DESCRIPTION, ENTITY_TYPE_INSTANCE_CLASS, BASE_ENTITY_TYPE_DEF_ID, LOOKUP, SYSTEM, TEMPLATE)
--  VALUES(41528, 'GeneralLedgerEntries', 'General Ledger Entries', 'com.vsoftcorp.loan.model.entities.GeneralLedgerEntries', NULL, 0, 0, 'generalLedgerEntriesLayout.xhtml');
--
--INSERT INTO ASSOCIATE_DEFINITION(ASSOCIATE_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, ASSOCIATE_NAME, ASSOCIATE_INDEX, ASSOCIATE_DESCRIPTION, ASSOCIATE_TYPE_DEFINITION_ID, ASSOCIATE_TYPE_OVERRIDEN, MULTIPLICITY, MULTIPLICITY_OVERRIDEN, ASSOCIATION_TYPE, ASSOCIATION_TYPE_OVERRIDEN, LAZY, LAZY_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, COPY, COPY_OVERRIDEN, DEFAULT_INSTANCE, DEFAULT_INSTANCE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, TEMPLATE, TEMPLATE_OVERRIDEN)
--  VALUES(6261, 41528, 'GeneralLedgerEntries', 0, 'General Ledger Entries', 41527, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, NULL, 0, 0, 1, 1, 0, 'U', NULL, 0);
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES(6411, 41527, 'GLAccountNumber', 0, 'GL Account Number', 9, 0, 0, NULL, 0, 'java.lang.String:{default={}}', 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 'U', 0, 0);
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES(6412, 41527, 'GLAccountName', 1, 'GL Account Name', 1, 0, 0, NULL, 0, 'java.lang.String:{default={}}', 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 'U', 0, 0);
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES(6413, 41527, 'Amount', 2, 'Amount', 8, 0, 0, NULL, 0, 'com.vsoftcorp.finance.Money:{default={}}', 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 'U', 0, 0);
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES(6414, 41528, 'TotalCredit', 0, 'Total Credit', 8, 0, 0, NULL, 0, 'com.vsoftcorp.finance.Money:{default={}}', 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 'U', 0, 0);
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES(6415, 41528, 'TotalDebit', 1, 'Total Debit', 8, 0, 0, NULL, 0, 'com.vsoftcorp.finance.Money:{default={}}', 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 'U', 0, 0);
--  
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES(6491, 41527, 'EntryType', 3, 'Entry Type', 2, 0, 0, NULL, 0, 'java.lang.Integer:{default={1=Credit,0=Debit}}', 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 'U', 0, 0);

        
DROP SEQUENCE ENTITYTYPEDEFID_SEQ;

CREATE SEQUENCE ENTITYTYPEDEFID_SEQ
    INCREMENT BY 1
    START WITH 42000
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    CACHE 20
    NOORDER;

DROP SEQUENCE ASSOCDEFID_SEQ;

CREATE SEQUENCE ASSOCDEFID_SEQ
    INCREMENT BY 1
    START WITH 6500
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    CACHE 20
    NOORDER;

--update ASSOCIATE_DEFINITION set MANDATORY='1' where ASSOCIATE_DEFINITION_ID='407'  and ASSOCIATE_NAME='InterestCalculation';

