
-- NAGARJUNA SCRIPTS START
--delete from ENTITY_TYPE_DEFINITION where ENTITY_TYPE_DEFINITION_ID in (42002,42022,42021,42060);
--delete from PROPERTY_DEFINITION where ENTITY_TYPE_DEFINITION_ID in (42002,42022,42021,42060);
--delete from ASSOCIATE_DEFINITION where ENTITY_TYPE_DEFINITION_ID in (42002,42022,42021,42060);
--
---- Alternate Payment Schedule -- Due Day Of Month
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION), 41483, 'DueDayOfMonth', 5, 'Due Day Of Month', 2, 0, 0, NULL, 0, 'java.lang.Integer:{default={}}', 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 'u', 0, 0);
--
---- Regular Payment Schedule - Due Day Of Month
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION), 547, 'DueDayOfMonth', 9, 'Due Day Of Month', 2, 0, 0, NULL, 0, 'java.lang.Integer:{default={}}', 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 'u', 0, 0);
--
---- Demand Note Schedule - Due Day Of Month
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION), 144, 'DueDayOfMonth', 2, 'Due Day Of Month', 2, 0, 0, NULL, 0, 'java.lang.Integer:{default={}}', 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 'u', 0, 0);
--
----AHLife Insurance - Insurance Interest Rate
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION), 41302, 'InsuranceInterestRate', 11, 'Insurance Interest Rate', 10, 0, 0, NULL, 0, 'com.vsoftcorp.common.InterestRate:{default={}}', 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 'u', 0, 0);



CREATE TABLE AMOUNT_ENTRY ( 
    AMOUNT_ENTRY_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT AMOUNT_ENTRY_ID_PK PRIMARY KEY(AMOUNT_ENTRY_ID)
);


--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.AmountEntry' where
--TYPE_NAME='AmountEntry';


CREATE TABLE ASSIGNED_BANK ( 
    ASSIGNED_BANK_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT ASSIGNED_BANK_ID_PK PRIMARY KEY(ASSIGNED_BANK_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.AssignedBank' where
--TYPE_NAME='AssignedBank';


CREATE TABLE ASSIGNED_BRANCH ( 
    ASSIGNED_BRANCH_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT ASSIGNED_BRANCH_ID_PK PRIMARY KEY(ASSIGNED_BRANCH_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.AssignedBranch' where
--TYPE_NAME='AssignedBranch';


CREATE TABLE BORROWER ( 
    BORROWER_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT BORROWER_ID_PK PRIMARY KEY(BORROWER_ID)
);


--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.Borrower' where
--TYPE_NAME='Borrower';

CREATE TABLE CALL_INFORMATION ( 
    CALL_INFORMATION_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT CALL_INFORMATION_ID_PK PRIMARY KEY(CALL_INFORMATION_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.CallInformation' where
--TYPE_NAME='CallInformation';


CREATE TABLE CO_BORROWER ( 
    CO_BORROWER_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT CO_BORROWER_ID_PK PRIMARY KEY(CO_BORROWER_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.CoBorrower' where
--TYPE_NAME='CoBorrower';

CREATE TABLE CO_MAKER ( 
    CO_MAKER_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT CO_MAKER_ID_PK PRIMARY KEY(CO_MAKER_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.CoMaker' where
--TYPE_NAME='CoMaker';


CREATE TABLE COLLATERAL_TYPE ( 
    COLLATERAL_TYPE_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT COLLATERAL_TYPE_ID_PK PRIMARY KEY(COLLATERAL_TYPE_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.CollateralType' where
--TYPE_NAME='CollateralType';

CREATE TABLE DEPOSIT_COLLATERAL_APPRAISAL ( 
    DEPOSIT_COLL_APPRAISAL_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT DEPOSIT_COLL_APPRAISAL_ID_PK PRIMARY KEY(DEPOSIT_COLL_APPRAISAL_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.DepositCollateralAppraisal' where
--TYPE_NAME='DepositCollateralAppraisal';


CREATE TABLE FIXED_AMOUNT_PENALTY ( 
    FIXED_AMOUNT_PENALTY_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT FIXED_AMOUNT_PENALTY_ID_PK PRIMARY KEY(FIXED_AMOUNT_PENALTY_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.FixedAmountPenalty' where
--TYPE_NAME='FixedAmountPenalty';


CREATE TABLE FLAT_INTEREST_RATE_PENALTY ( 
    FLAT_INT_RATE_PENALTY_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT FLAT_INT_RATE_PENALTY_ID_PK PRIMARY KEY(FLAT_INT_RATE_PENALTY_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.FlatInterestRatePenalty' where
--TYPE_NAME='FlatInterestRatePenalty';


CREATE TABLE GUARANTOR ( 
    GUARANTOR_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT GUARANTOR_ID_PK PRIMARY KEY(GUARANTOR_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.Guarantor' where
--TYPE_NAME='Guarantor';

CREATE TABLE HEQ ( 
    HEQ_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT HEQ_ID_PK PRIMARY KEY(HEQ_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.HEQ' where
--TYPE_NAME='HEQ';


CREATE TABLE HAZARD_INSURANCE_AGENCY ( 
    HAZARD_INSURANCE_AGENCY_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT HAZARD_INSURANCE_AGENCY_ID_PK PRIMARY KEY(HAZARD_INSURANCE_AGENCY_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.HazardInsuranceAgency' where
--TYPE_NAME='HazardInsuranceAgency';


CREATE TABLE HOMEOWNERS_CONDO_ASS_AGENCY ( 
    HOMEOWNERS_CONDO_AGENCY_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT HOMEOWNERS_CONDO_AGENCY_ID_PK PRIMARY KEY(HOMEOWNERS_CONDO_AGENCY_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.HomeownersCondoAssociationAgency' where
--TYPE_NAME='HomeownersCondoAssociationAgency';



CREATE TABLE ENDORSER ( 
    ENDORSER_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT ENDORSER_ID_PK PRIMARY KEY(ENDORSER_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.Endorser' where
--TYPE_NAME='Endorser';

CREATE TABLE LOC ( 
    LOC_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT LOC_ID_PK PRIMARY KEY(LOC_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.LOC' where
--TYPE_NAME='LOC';

CREATE TABLE LIFE_AH_INSURANCE_AGENCY ( 
    LIFE_AH_INSURANCE_AGENCY_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT LIFE_AH_INSURANCE_AGENCY_ID_PK PRIMARY KEY(LIFE_AH_INSURANCE_AGENCY_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.LifeAHInsuranceAgency' where
--TYPE_NAME='LifeAHInsuranceAgency';


CREATE TABLE LOAN_OFFICER_TRANSFER ( 
    LOAN_OFFICER_TRANSFER_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT LOAN_OFFICER_TRANSFER_ID_PK PRIMARY KEY(LOAN_OFFICER_TRANSFER_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.LoanOfficerTransfer' where
--TYPE_NAME='LoanOfficerTransfer';


CREATE TABLE MONTHLY_INT_RATE_PENALTY ( 
    MONTHLY_INT_RATE_PENALTY_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT MONTHLY_INT_RATE_PENALTY_ID_PK PRIMARY KEY(MONTHLY_INT_RATE_PENALTY_ID)
);


--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.MonthlyInterestRatePenalty' where
--TYPE_NAME='MonthlyInterestRatePenality';


CREATE TABLE NON_BORROWER ( 
    NON_BORROWER_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT NON_BORROWER_ID_PK PRIMARY KEY(NON_BORROWER_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.NonBorrower' where
--TYPE_NAME='NonBorrower';

CREATE TABLE OTHER_COLL_APPRAISAL ( 
    OTHER_COLL_APPRAISAL_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT OTHER_COLL_APPRAISAL_ID_PK PRIMARY KEY(OTHER_COLL_APPRAISAL_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.OtherCollateralAppraisal' where
--TYPE_NAME='OtherCollateralAppraisal';

CREATE TABLE PMI_AGENCY ( 
    PMI_AGENCY_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT PMI_AGENCY_ID_PK PRIMARY KEY(PMI_AGENCY_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.PMIAgency' where
--TYPE_NAME='PMIAgency';

CREATE TABLE PAST_DUE_NOTICE_SCHEDULE ( 
    PAST_DUE_NOTICE_SCHEDULE_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT PAST_DUE_NOTICE_SCHEDULE_ID_PK PRIMARY KEY(PAST_DUE_NOTICE_SCHEDULE_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.PastDueNoticeSchedule' where
--TYPE_NAME='PastDueNoticeSchedule';

CREATE TABLE PAST_DUE_PERIOD ( 
    PAST_DUE_PERIOD_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT PAST_DUE_PERIOD_ID_PK PRIMARY KEY(PAST_DUE_PERIOD_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.PastDuePeriod' where
--TYPE_NAME='PastDuePeriod';

CREATE TABLE PAYMENT_SCHEDULE_ITEM ( 
    PAYMENT_SCHEDULE_ITEM_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT PAYMENT_SCHEDULE_ITEM_ID_PK PRIMARY KEY(PAYMENT_SCHEDULE_ITEM_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.PaymentScheduleItem' where
--TYPE_NAME='PaymentScheduleItem';


CREATE TABLE STATEMENT ( 
    STATEMENT_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT STATEMENT_ID_PK PRIMARY KEY(STATEMENT_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.Statement' where
--TYPE_NAME='Statement';

CREATE TABLE STOCK_COLL_APPRAISAL ( 
    STOCK_COLL_APPRAISAL_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT STOCK_COLL_APPRAISAL_ID_PK PRIMARY KEY(STOCK_COLL_APPRAISAL_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.StockCollateralAppraisal' where
--TYPE_NAME='StockCollateralAppraisal';

CREATE TABLE TAX_AGENCY ( 
    TAX_AGENCY_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT TAX_AGENCY_ID_PK PRIMARY KEY(TAX_AGENCY_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.TaxAgency' where
--TYPE_NAME='TaxAgency';

CREATE TABLE TITLE_COLLL_APPRAISAL ( 
    TITLE_COLL_APPRAISAL_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT TITLE_COLL_APPRAISAL_ID_PK PRIMARY KEY(TITLE_COLL_APPRAISAL_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.TitleCollateralAppraisal' where
--TYPE_NAME='TitleCollateralAppraisal';

CREATE TABLE BROUGHT_SOLD_PARTICIPATION ( 
    BROUGHT_SOLD_PART_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT BROUGHT_SOLD_PART_ID_PK PRIMARY KEY(BROUGHT_SOLD_PART_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.BroughtSoldParticipation' where
--TYPE_NAME='BroughtSoldParticipation';

CREATE TABLE CREDIT_LINE_FEE_CODE ( 
    CREDIT_LINE_FEE_CODE_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT CREDIT_LINE_FEE_CODE_ID_PK PRIMARY KEY(CREDIT_LINE_FEE_CODE_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.CreditLineFeeCode' where
--TYPE_NAME='CreditLineFeeCode';

CREATE TABLE ESCROW_OTHER ( 
    ESCROW_OTHER_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT ESCROW_OTHER_ID_PK PRIMARY KEY(ESCROW_OTHER_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.EscrowOther' where
--TYPE_NAME='EscrowOther';

CREATE TABLE FLAT_ANNUAL_FEE ( 
    FLAT_ANNUAL_FEE_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT FLAT_ANNUAL_FEE_ID_PK PRIMARY KEY(FLAT_ANNUAL_FEE_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.FlatAnnualFee' where
--TYPE_NAME='FlatAnnualFee';

CREATE TABLE LOAN_PARTICIPATION ( 
    LOAN_PARTICIPATION_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT LOAN_PARTICIPATION_ID_PK PRIMARY KEY(LOAN_PARTICIPATION_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.LoanParticipation' where
--TYPE_NAME='LoanParticipation';

CREATE TABLE NO_CREDIT_LINE_FEE ( 
    NO_CREDIT_LINE_FEE_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT NO_CREDIT_LINE_FEE_ID_PK PRIMARY KEY(NO_CREDIT_LINE_FEE_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.NoCreditLineFee' where
--TYPE_NAME='NoCreditLineFee';


CREATE TABLE PERCENTAGE_BASIS ( 
    PERCENTAGE_BASIS_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT PERCENTAGE_BASIS_ID_PK PRIMARY KEY(PERCENTAGE_BASIS_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.PercentageBasis' where
--TYPE_NAME='PercentageBasis';

--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION), 42061, 'NonEscrowBalance', 0, 'Non Escrow Balance', 8, 0, 0, NULL, 0, 'com.vsoftcorp.finance.Money:{default={}}', 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 'u', 0, 0);
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION), 42061, 'BeginingEscrowBalance', 0, 'Begining  Escrow Balance', 8, 0, 0, NULL, 0, 'com.vsoftcorp.finance.Money:{default={}}', 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 'u', 0, 0);
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION), 42061, 'DepositsToEscrow', 0, 'Deposits To Escrow', 8, 0, 0, NULL, 0, 'com.vsoftcorp.finance.Money:{default={}}', 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 'u', 0, 0);
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION), 42061, 'EscrowDisbursements', 0, 'Escrow Disbursements', 8, 0, 0, NULL, 0, 'com.vsoftcorp.finance.Money:{default={}}', 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 'u', 0, 0);
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION), 42061, 'AmountReportedToIRS', 0, 'Amount Reported To IRS', 8, 0, 0, NULL, 0, 'com.vsoftcorp.finance.Money:{default={}}', 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 'u', 0, 0);
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION), 42061, 'PastDueEscrow', 0, 'Past Due Escrow', 8, 0, 0, NULL, 0, 'com.vsoftcorp.finance.Money:{default={}}', 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 'u', 0, 0);
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION), 42061, 'PastDueNonEscrow', 0, 'Past Due Non Escrow', 8, 0, 0, NULL, 0, 'com.vsoftcorp.finance.Money:{default={}}', 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 'u', 0, 0);
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION), 41302, 'LastEscrowAnalysisDate', 1, 'Last Escrow Analysis Date', 5, 0, 0, NULL, 0, 'com.vsoftcorp.time.Date:{default={}}', 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 'U', 0, 0);
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION), 41302, 'EscrowPaymentChangeDate', 1, 'Escrow Payment Change Date', 5, 0, 0, NULL, 0, 'com.vsoftcorp.time.Date:{default={}}', 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 'U', 0, 0);
--
--
--
--UPDATE ASSOCIATE_DEFINITION SET MANDATORY=0,HIDDEN=0,EDITABLE=1 WHERE ASSOCIATE_NAME LIKE 'EscrowDetail';
--UPDATE ASSOCIATE_DEFINITION SET MANDATORY=0,HIDDEN=0,EDITABLE=1 WHERE ASSOCIATE_NAME LIKE 'EscrowSummary';
--
--
--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.FloatingPenaltyRate' where
--TYPE_NAME='FloatingPenaltyRate';
--
--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.LoanCustomerRole' where
--TYPE_NAME='LoanCustomerRole';
--
--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.RateIndex' where
--TYPE_NAME='RateIndexParameter';
--
--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.LoanPurpose' where
--TYPE_NAME='LoanPurpose';
--
--DELETE FROM PROPERTY_DEFINITION WHERE PROPERTY_NAME LIKE 'NewInterestRate' AND PROPERTY_DEFINITION_ID=296;
--DELETE FROM PROPERTY_DEFINITION WHERE PROPERTY_NAME LIKE 'NewIndexValue' AND PROPERTY_DEFINITION_ID=297;
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES(296, 721, 'NewInterestRate', 9, 'New Interest Rate', 4, 0, 0, NULL, 0, 'com.vsoftcorp.types.Percentage:{default={}}', 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 'U', 0, 0);
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES(297, 721, 'NewIndexValue', 10, 'New Index Value', 4, 1, 0, NULL, 0, 'com.vsoftcorp.types.Percentage:{default={}}', 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 'U', NULL, NULL);
--
--INSERT INTO ASSOCIATE_DEFINITION(ASSOCIATE_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, ASSOCIATE_NAME, ASSOCIATE_INDEX, ASSOCIATE_DESCRIPTION, ASSOCIATE_TYPE_DEFINITION_ID, ASSOCIATE_TYPE_OVERRIDEN, MULTIPLICITY, MULTIPLICITY_OVERRIDEN, ASSOCIATION_TYPE, ASSOCIATION_TYPE_OVERRIDEN, LAZY, LAZY_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, COPY, COPY_OVERRIDEN, DEFAULT_INSTANCE, DEFAULT_INSTANCE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, TEMPLATE, TEMPLATE_OVERRIDEN)
--  VALUES((SELECT MAX(ASSOCIATE_DEFINITION_ID)+1 FROM ASSOCIATE_DEFINITION), 702, 'NewInterestRate', 4, 'New Interest Rate', 721, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, NULL, 0, 0, 1, 1, 0, 'U', NULL, 0);
--
--
--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.NewInterestRate' where
--TYPE_NAME='NewInterestRate';
--
--DELETE FROM ENTITY_TYPE_DEFINITION WHERE ENTITY_TYPE_DEFINITION_ID IN ('801','802','887','888','889','890','41503','41526','503','502');
--DELETE FROM PROPERTY_DEFINITION WHERE ENTITY_TYPE_DEFINITION_ID IN ('801','802','887','888','889','890','41503','41526','503','502');
--DELETE FROM ASSOCIATE_DEFINITION WHERE ENTITY_TYPE_DEFINITION_ID IN ('801','802','887','888','889','890','41503','41526','503','502');
--
--
---- NAGARJUNA SCRIPTS END
--
---- UMA SCRIPTS START
--
---- Tolerance amount to 1.00.
--update property_definition set default_value = 'com.vsoftcorp.finance.Money:USD 1.00' 
--where PROPERTY_DEFINITION_ID = 1296 and ENTITY_TYPE_DEFINITION_ID = 542;
--
----IncludeLateChargeOnPayOff is visible.
--update property_definition set hidden = 0
--where PROPERTY_DEFINITION_ID = 1288 and ENTITY_TYPE_DEFINITION_ID = 542;
--
---- Payoff is non lazy.
--update ASSOCIATE_DEFINITION set lazy = 0 where ASSOCIATE_DEFINITION_ID = 412 and ENTITY_TYPE_DEFINITION_ID = 523;
--
----Case VII: Loan Repayment = Irregular Payment Schedule 
----(parameter module should one more valid value “irregular payment schedule” to loan repayment property.
--
--update PROPERTY_DEFINITION set
--VALID_VALUES = 'java.lang.Integer:{default={3=Sinlge Payment, 5=Rule of 78''s, 2=Interest Only - Principal due at maturity, 0=Principal Plus Interest, 4=Principal Only - Interest due at maturity, 1=Payment Includes Interest, 6=Alternate Payment Schedule, 7 =Irregular Payment Schedule}}'
--where property_name like 'RepaymentMethod' and ENTITY_TYPE_DEFINITION_ID = 523;
--
---- Updating the Variable Loan Interest making Rate Adjustment as mandatory associate.
--update ASSOCIATE_DEFINITION set MANDATORY = 0 where ASSOCIATE_NAME = 'RateAdjustment' and ENTITY_TYPE_DEFINITION_ID = 702;
--
--
---- Moving RateChangeLeadPeriod from Arm type to Rate Adjustment.
--update property_definition set ENTITY_TYPE_DEFINITION_id = 723 where property_name like 'RateChangeLeadPeriod';
--update property_definition set ENTITY_TYPE_DEFINITION_id = 723 where property_name like 'ReDetermineRateIndicator';
--
---- Adding New Field Number of Payments to alternate payment schedule.
--INSERT INTO PROPERTY_DEFINITION (PROPERTY_DEFINITION_ID,ENTITY_TYPE_DEFINITION_ID,PROPERTY_NAME,PROPERTY_INDEX,PROPERTY_DESCRIPTION,VALUE_TYPE_DEFINITION_ID,DESCRIPTION_FIELD,DESCRIPTION_FIELD_OVERRIDEN,DEFAULT_VALUE,DEFAULT_VALUE_OVERRIDEN,VALID_VALUES,VALID_VALUES_OVERRIDEN,MANDATORY,MANDATORY_OVERRIDEN,HIDDEN,HIDDEN_OVERRIDEN,EDITABLE,EDITABLE_OVERRIDEN,INHERITED,CAN_EDIT_DEFINITION,CAN_DELETE_DEFINITION,CATEGORY_OVERRIDEN,CATEGORY,PRIMARY_OVERRIDEN,PRIMARY) VALUES (
--(SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION),41483,'NumberofPayments',5,'Number of Payments',2,0,0,null,0,'java.lang.Integer:{default={}}',0,1,0,0,0,1,0,0,1,1,0,'U',0,0);
--
---- Adding New Associate Definition for variable loan interest - payment adjustment history.
--INSERT INTO ASSOCIATE_DEFINITION (
--ASSOCIATE_DEFINITION_ID,ENTITY_TYPE_DEFINITION_ID,ASSOCIATE_NAME,ASSOCIATE_INDEX,ASSOCIATE_DESCRIPTION,ASSOCIATE_TYPE_DEFINITION_ID,ASSOCIATE_TYPE_OVERRIDEN,MULTIPLICITY,MULTIPLICITY_OVERRIDEN,ASSOCIATION_TYPE,ASSOCIATION_TYPE_OVERRIDEN,LAZY,LAZY_OVERRIDEN,MANDATORY,MANDATORY_OVERRIDEN,HIDDEN,HIDDEN_OVERRIDEN,EDITABLE,EDITABLE_OVERRIDEN,COPY,COPY_OVERRIDEN,DEFAULT_INSTANCE,DEFAULT_INSTANCE_OVERRIDEN,INHERITED,CAN_EDIT_DEFINITION,CAN_DELETE_DEFINITION,CATEGORY_OVERRIDEN,CATEGORY,TEMPLATE,TEMPLATE_OVERRIDEN) 
--VALUES ((
--SELECT MAX(ASSOCIATE_DEFINITION_ID)+1 FROM ASSOCIATE_DEFINITION),702,'PaymentAdjustmentHistory',5,'Payment Adjustment History',704,0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,'U',null,0);
--
--update ENTITY_TYPE_DEFINITION set TYPE_NAME = 'MunicipalSecured29',TYPE_DESCRIPTION = 'Municipal - Secured 29' where ENTITY_TYPE_DEFINITION_ID= 5004;
-- 
--update PROPERTY_DEFINITION set DEFAULT_VALUE = 'java.lang.String:29' where PROPERTY_NAME = 'ProductCode' and ENTITY_TYPE_DEFINITION_id = 5004;
--
--INSERT INTO ENTITY_TYPE_DEFINITION(ENTITY_TYPE_DEFINITION_ID, TYPE_NAME, TYPE_DESCRIPTION, ENTITY_TYPE_INSTANCE_CLASS, BASE_ENTITY_TYPE_DEF_ID, LOOKUP, SYSTEM, TEMPLATE)
--  VALUES(42062, 'MunicipalUnsecured05', 'Municipal - Unsecured 05', 'com.vsoftcorp.loan.model.entities.LoanProduct', 1303, 0, 0, NULL);
--
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION), 42062 , 'MaturityNoticeLeadPeriod', -1, 'Maturity Notice Lead Period', 6, 0, 0, 'com.vsoftcorp.time.Duration:DAY:17', 1, 'com.vsoftcorp.time.Duration:{default={}}', 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, NULL, 0, 0);
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION), 42062, 'ProductCode', -1, 'Product Code', 1, 0, 0, 'java.lang.String:05', 1, 'java.lang.String:{default={}}', 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, NULL, 0, 0);
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION), 42062, 'MaxPeriodCanBackDate', -1, 'Max Period Can BackDate', 6, 0, 0, 'com.vsoftcorp.time.Duration:DAY:30', 1, 'com.vsoftcorp.time.Duration:{default={}}', 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, NULL, 0, 0);
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((SELECT MAX(PROPERTY_DEFINITION_ID)+1MUNICIPAL_UNSECURED_05 FROM PROPERTY_DEFINITION), 42062, 'RateChangeNoticeLeadPeriod', -1, 'Rate Change Notice Lead Period', 6, 0, 0, 'com.vsoftcorp.time.Duration:DAY:15', 1, 'com.vsoftcorp.time.Duration:{default={}}', 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, NULL, 0, 0);
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION), 42062, 'PeriodToClose', -1, 'Period To Close', 6, 0, 0, 'com.vsoftcorp.time.Duration:DAY:60', 1, 'com.vsoftcorp.time.Duration:{default={}}', 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, NULL, 0, 0);
--
--INSERT INTO ASSOCIATE_DEFINITION(ASSOCIATE_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, ASSOCIATE_NAME, ASSOCIATE_INDEX, ASSOCIATE_DESCRIPTION, ASSOCIATE_TYPE_DEFINITION_ID, ASSOCIATE_TYPE_OVERRIDEN, MULTIPLICITY, MULTIPLICITY_OVERRIDEN, ASSOCIATION_TYPE, ASSOCIATION_TYPE_OVERRIDEN, LAZY, LAZY_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, COPY, COPY_OVERRIDEN, DEFAULT_INSTANCE, DEFAULT_INSTANCE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, TEMPLATE, TEMPLATE_OVERRIDEN)
--  VALUES((
--SELECT MAX(ASSOCIATE_DEFINITION_ID)+1 FROM ASSOCIATE_DEFINITION), 42062, 'CallInformation', 5, 'Call Information', 5030, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, NULL, 0, 0, 1, 0, 0, 'P', NULL, 0);


-- Updating property definition for payment type in Payment schedule item.

DROP TABLE MUNICIPAL_05;


-- Updating property definition for payment type in Payment schedule item.

--update PROPERTY_DEFINITION set VALID_VALUES = 'java.lang.Integer:{default={2=Principal & Interest, 0=Principal Only, 1=Interest Only, 3=Payment Includes Interest}}'
--where property_name like 'PaymentType' and ENTITY_TYPE_DEFINITION_id = 41403;
--
--
---- UMA SCRIPTS END
--
---- NAGARJUNA SCRIPTS START
--UPDATE PROPERTY_DEFINITION SET VALUE_TYPE_DEFINITION_ID=10,VALID_VALUES='com.vsoftcorp.common.InterestRate:{default={}}' WHERE PROPERTY_NAME LIKE 'DealerRate' AND PROPERTY_DEFINITION_ID='1736';
--
--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.MunicipalUnsecured05' where
--TYPE_NAME='MunicipalUnsecured05';
--
--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.MunicipalSecured29' where
--TYPE_NAME='MunicipalSecured29';
--
--UPDATE PROPERTY_DEFINITION SET VALUE_TYPE_DEFINITION_ID=10,VALID_VALUES='com.vsoftcorp.common.InterestRate:{default={}}' 


CREATE TABLE LOAN_CUSTOMER_ROLE ( 
    LOAN_CUSTOMER_ROLE_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT LOAN_CUSTOMER_ROLE_ID_PK PRIMARY KEY(LOAN_CUSTOMER_ROLE_ID)
);

CREATE TABLE CUSTOMER_ROLE ( 
    CUSTOMER_ROLE_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT CUSTOMER_ROLE_ID_PK PRIMARY KEY(CUSTOMER_ROLE_ID)
);

--update ENTITY_TYPE_DEFINITION
--set ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.CustomerRole' where
--TYPE_NAME='CustomerRole';


-- NAGARJUNA SCRIPTS END
