-------LoanAccount
ALTER TABLE LOAN_ACCOUNT
ADD LAST_CURT_AMOUNT NUMBER(20,2) ;
 
ALTER TABLE LOAN_ACCOUNT
ADD LAST_CURT_DATE DATE;

-----LOAN_ACCOUNT_DAY
ALTER TABLE LOAN_ACCOUNT_DAY ADD  OPENING_LAST_CURT_AMOUNT  NUMBER(20,2) ;
ALTER TABLE LOAN_ACCOUNT_DAY ADD  OPENING_LAST_CURT_DATE DATE;

ALTER TABLE LOAN_ACCOUNT_DAY ADD  LAST_CURT_AMOUNT  NUMBER(20,2) ;
ALTER TABLE LOAN_ACCOUNT_DAY ADD  LAST_CURT_DATE VARCHAR2(50);

alter table BILLING_BUCKET add BILLED_DEALER_INTEREST NUMBER (15,2);

------Mort_Cr_Db_scripts
 
----------ENTRY_TYPE

INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(1302, '1302', null, '2','0', 'Advance');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(22110, '22110', null, '2','0', 'Debit Memo - Late Charge');
INSERT INTO ENTRY_TYPE(UNIQUE_ID, ID, INSTITUTION_ID, ACCOUNT_CATEGORY, DEBIT_OR_CREDIT, DESCRIPTION)
    VALUES(32110, '32110', null, '2','1', 'Credit Memo - Late Charge');

alter table DELQ_BILLING_BUCKET_NEW add BILLED_DealerInterest number(20,6);
alter table DELQ_BILLING_BUCKET_NEW add PAID_DEALER_INTEREST number(20,6);
 
alter table BILLING_BUCKET add PAID_DEALER_INTEREST number(20,6);
 
alter table LOAN_ACCOUNT_DAY add OPENING_DEALER_INT_MTD number(20,6);
alter table LOAN_ACCOUNT_DAY add OPENING_DEALER_INT_YTD number(20,6);
alter table LOAN_ACCOUNT_DAY add OPENING_DEALER_INT_LTD number(20,6);
alter table LOAN_ACCOUNT_DAY add OPENING_NET_ACCR_INT number(20,6);
  
alter table LOAN_ACCOUNT_DAY add DEALER_INT_MTD number(20,6);
alter table LOAN_ACCOUNT_DAY add DEALER_INT_YTD number(20,6);
alter table LOAN_ACCOUNT_DAY add DEALER_INT_LTD number(20,6);
alter table LOAN_ACCOUNT_DAY add NET_ACCR_INT number(20,6);
               
alter table LOAN_LEDGER_POSTING_PARAMETERS add AFFECTS_DLR_INT_MTD number(1) default 0;
alter table LOAN_LEDGER_POSTING_PARAMETERS add AFFECTS_DLR_INT_YTD number(1) default 0;
alter table LOAN_LEDGER_POSTING_PARAMETERS add AFFECTS_DLR_INT_LTD number(1) default 0;
alter table LOAN_LEDGER_POSTING_PARAMETERS add AFFECTS_DLR_REBATE number(1) default 0;
alter table LOAN_LEDGER_POSTING_PARAMETERS add AFFECTS_DLR_HB_REBATE number(1) default 0;

--update LOAN_LEDGER_POSTING_PARAMETERS set AFFECTS_DLR_REBATE=1, AFFECTS_DLR_HB_REBATE=1 where UNIQUE_ID in (1502, 1525);
--update LOAN_LEDGER_POSTING_PARAMETERS set AFFECTS_DLR_INT_MTD=1, AFFECTS_DLR_INT_YTD=1, AFFECTS_DLR_INT_LTD=1
--where UNIQUE_ID in (1951,11101, 1744, 1732 , 1725, 1728, 1799);

update LOAN_LEDGER_POSTING_PARAMETERS set AFFECTS_UNAPPLIED_FUND=0;

--update LOAN_LEDGER_POSTING_PARAMETERS set AFFECTS_PAYMENT_MAID=1, AFFECTS_PAYOUT_CODE=1, AFFECTS_DATE_CLOSED=1
--where UNIQUE_ID=1951;

alter table LOAN_ACCOUNT_DAY add OPENING_AMORTIZED_BAL number(20,6) default 0;

alter table LOAN_ACCOUNT_DAY add AMORTIZED_BAL number(20,6) default 0;

alter table LOAN_LEDGER_POSTING_PARAMETERS add AFFECTS_AMORTIZED_BAL number(1) default 0;

--update LOAN_LEDGER_POSTING_PARAMETERS set AFFECTS_AMORTIZED_BAL=1 where UNIQUE_ID in (
-- 1525,         
-- 19020,        
-- 1301  ,       
-- 1951 ,        
-- 1502 ,        
-- 1511 ,        
-- 1538 ,        
-- 1528 ,        
-- 1544 ,        
-- 1744 ,        
-- 17010,        
-- 1751 ,        
-- 1725 ,        
-- 1728 ,        
-- 1799 ,        
-- 17110,        
-- 17111,        
-- 1512 ,        
-- 31207,        
-- 21207,        
-- 31208,        
-- 21208,        
-- 1302 
--);

alter table DELQ_BILLING_BUCKET_NEW add PAID_DealerInterest number(20,6) default 0;

update DELQ_BILLING_BUCKET_NEW set PAID_DealerInterest = PAID_DEALER_INTEREST 
where PAID_DEALER_INTEREST is not null;

alter table DELQ_BILLING_BUCKET_NEW drop column PAID_DEALER_INTEREST;
 
-- added for statements 
CREATE OR REPLACE VIEW LOAN_ACCOUNT_HISTORY_ITEM_VW AS SELECT * FROM LOAN_ACCOUNT_HISTORY_ITEM;





 
