-- POSSIBLE OWNER 
ALTER TABLE POSSIBLE_OWNER ADD (ENTITY_TYPE_INSTANCE_ID NUMBER(15));

-- ACCOUNT OWNER
ALTER TABLE ACCOUNT_OWNER ADD (ENTITY_TYPE_INSTANCE_ID NUMBER(15));

-- ACCOUNT APPLICATION
ALTER TABLE ACCOUNT_APPLICATION ADD(REJECT_REASON VARCHAR2(250));
ALTER TABLE ACCOUNT_APPLICATION ADD(REVIEW_FAIL_REASON VARCHAR2(250));
ALTER TABLE ACCOUNT_APPLICATION ADD(REVIEWER VARCHAR2(50));
ALTER TABLE ACCOUNT_APPLICATION ADD(ENTERED_BY VARCHAR2(50));
ALTER TABLE ACCOUNT_APPLICATION ADD(LAST_REVIEWED_DATE DATE);
ALTER TABLE ACCOUNT_APPLICATION ADD (CONTRACT_ID NUMBER(15));

-- LOAN ACCOUNT

ALTER TABLE LOAN_ACCOUNT ADD(CHARGE_OFF_AMOUNT NUMBER(15,5));
ALTER TABLE LOAN_ACCOUNT ADD(PRE_PAID_AMOUNT NUMBER(15,5));
ALTER TABLE LOAN_ACCOUNT ADD (CONTRACT_ID NUMBER(15) NULL);
ALTER TABLE LOAN_ACCOUNT MODIFY (LOAN_TYPE_ID NULL);
ALTER TABLE LOAN_ACCOUNT ADD(LAST_TRANSACTION_DATE date);
ALTER TABLE LOAN_ACCOUNT ADD (PAST_DUE_UNUSEDLINE_COMMIT_FEE number(15,5));
ALTER TABLE LOAN_ACCOUNT ADD (BILLED_UNUSEDLINE_C0MMIT_FEE number(15,5));
ALTER TABLE LOAN_ACCOUNT ADD(PRINCIPAL_DUE NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(FUTURE_PAYMENT_COUNT NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(PRINCIPAL_PAID_TO_DATE DATE);
ALTER TABLE LOAN_ACCOUNT ADD(NEXT_DISBURSEMENT_DATE DATE);
ALTER TABLE LOAN_ACCOUNT ADD(WAIVED_LATE_CHARGE NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(UNUSED_LINE_COMMITMENT NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(INVESTOR_NUMBER VARCHAR2(50));
-- ALTER TABLE LOAN_ACCOUNT ADD(LAST_STATEMENT_DATE DATE);
ALTER TABLE LOAN_ACCOUNT ADD(PAY_OUT_CODE NUMBER(10));
ALTER TABLE LOAN_ACCOUNT ADD(NO_RETURNED_CHECKS NUMBER(10));
ALTER TABLE LOAN_ACCOUNT ADD(DEALER_NUMBER NUMBER(10));
ALTER TABLE LOAN_ACCOUNT ADD(CURRENT_MONTH_EARNINGS NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(LIFE_INSURANCE_PREMIUM  NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(CREDIT_LIFE_TERM  NUMBER(10));
ALTER TABLE LOAN_ACCOUNT ADD(ACC_INSURANCE_TERM  NUMBER(10));
ALTER TABLE LOAN_ACCOUNT ADD(SUBSIDY_BALANCE  NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(CREDIT_LIFE_INDICATOR  NUMBER(10));
ALTER TABLE LOAN_ACCOUNT ADD(LAST_REVIEW_DATE  DATE);
ALTER TABLE LOAN_ACCOUNT ADD(REVIEW_DATE_FREQ  NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(INTEREST_PAID_MTD  NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(DATE_PREVIOUS_ACTIVITY  DATE);
ALTER TABLE LOAN_ACCOUNT ADD(UNUSED_LINE_COMMITMENT_AMT  NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(FINANCIAL_STMT_EXP_DATE  DATE);
ALTER TABLE LOAN_ACCOUNT ADD(FINANCING_STMT_EXP_DATE  DATE);
ALTER TABLE LOAN_ACCOUNT ADD(PRINCIPAL_BILLED_AMT  NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(INTEREST_BILLED_AMT  NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(BILLED_CHARGE1_AMT  NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(BILLED_CHARGE2_AMT  NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(BILL_STATUS_CODE  VARCHAR2(50));
ALTER TABLE LOAN_ACCOUNT ADD(BILLED_LINE_C0MMITMENT_FEE  NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(BILLED_DEALER_INTEREST  NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(BILLED_ESCROW_DUE  NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(DAILY_DEALER_INT_ACCRUAL  NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(DAILY_CHARG1_ACCRUAL  NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(DAILY_CHARG2_ACCRUAL  NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(DAILY_UNUSED_LINE_COMMIT_FEE  NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(PAST_DUE_CHARGE1_AMT  NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(PAST_DUE_CHARGE2_AMT  NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(PAST_DUE_LINE_COMMIT_FEE  NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(PAST_DUE_DEALER_INTEREST  NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(PAID_LOAN_CLOCK  VARCHAR2(30));
ALTER TABLE LOAN_ACCOUNT ADD(ESCROW_PAST_DUE  NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(NON_ESCROW_PAST_DUE  NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(COUPON_STAT_DATE  DATE);
ALTER TABLE LOAN_ACCOUNT ADD(COUPON_THRU_DATE  DATE);
ALTER TABLE LOAN_ACCOUNT ADD(COUPON_FLAG  VARCHAR2(30));
ALTER TABLE LOAN_ACCOUNT ADD(FIXED_PAYMENT_CODE  NUMBER(15));
ALTER TABLE LOAN_ACCOUNT DROP COLUMN PAST_PRINCIPLE_DUE;
ALTER TABLE LOAN_ACCOUNT ADD PAST_PRINCIPLE_DUE NUMBER(20,5);
ALTER TABLE LOAN_ACCOUNT ADD(BEG_ESCROW_BAL NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(DEPOSIT_TO_ESCROW NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(ESCROW_DISBURSEMETS NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(ESCROW_DISBURSEMENTS_IRS NUMBER(20,5));
-- ALTER TABLE LOAN_ACCOUNT ADD(LAST_STATEMENT_BAL NUMBER(20,5));
-- ALTER TABLE LOAN_ACCOUNT ADD(PRE_STATEMENT_BAL NUMBER(20,5));
-- ALTER TABLE LOAN_ACCOUNT ADD(PRE_STATEMENT_DATE DATE);
ALTER TABLE LOAN_ACCOUNT ADD ACCRUED_CHARGE1_AMT NUMBER (20,6);
ALTER TABLE LOAN_ACCOUNT ADD ACCRUED_CHARGE2_AMT NUMBER (20,6);
-- ALTER TABLE LOAN_ACCOUNT ADD STMT_CYCLE_CODE VARCHAR2(50);


-- LOANS BILLS LTD
ALTER TABLE LOAN_BILLS_LTD ADD(NO_TIMES_COLLECTION NUMBER(10));

-- PARTY INSTITUTION ASSOCIATION
ALTER TABLE PARTY_INSTITUTION_ASSOCIATION ADD(COLLATERAL_EXPIRATION_DATE  DATE);
--ALTER TABLE PARTY_INSTITUTION_ASSOCIATION ADD(FINANCIAL_STMT_DATE   DATE);
--ALTER TABLE PARTY_INSTITUTION_ASSOCIATION ADD(FINANCIAL_STMT_LAST_DATE DATE);
--ALTER TABLE PARTY_INSTITUTION_ASSOCIATION ADD(FINANCIAL_STMT_FREQ VARCHAR2(30));

-- LOAN ACCOUNT TRANSACTION
ALTER TABLE LOAN_ACCOUNT_TRANSACTION ADD(TRANSACTION_DESCRIPTION VARCHAR2(50));

-- BILLING BUCKET
CREATE SEQUENCE BILLING_BUCKET_ID_SEQ;
ALTER TABLE BILLING_BUCKET ADD (BILLED_NONESCROW NUMBER(20,5));
ALTER TABLE BILLING_BUCKET ADD (BILLED_CHARGE1 NUMBER(20,5));
ALTER TABLE BILLING_BUCKET ADD (BILLED_CHARGE2 NUMBER(20,5));


CREATE OR REPLACE VIEW LOAN_ACCOUNT_VW AS 
	select A.ACCOUNT_NO,A.INSTITUTION_ID,A.PRODUCT_ID,A.ACCOUNT_CATEGORY,
	A.ACCOUNT_TYPE_ID,A.BUSINESS_DATE,A.DATE_OPENED,A.CREATION_DATE, LA.*
	from ACCOUNT A,LOAN_ACCOUNT LA
	where A.ACCOUNT_ID=LA.ACCOUNT_ID;

-- NEED TO REMOVE ONCE VIEWS ARE READY - SHIVA NARAYANA

CREATE TABLE RATE_INDEX_LKP(
	CODE NUMBER(15) NOT NULL,
	DESCRIPTION VARCHAR2(50) NOT NULL,
	RATE_CHANGE_DATE DATE,
	CURRENT_INDEX_RATE NUMBER(20,10)
);



--INSTUTITION
ALTER TABLE INSTITUTION ADD (REGION_NAME VARCHAR2(50));

--LOAN PURPOSE LOOKUP
ALTER TABLE LOAN_PURPOSE_LOOKUP ADD (LO_CB_TYPE VARCHAR2(10));

--LOAN TYPE LOOKUP
ALTER TABLE LOAN_TYPE_LOOKUP ADD (CL_CBI_TYPE VARCHAR2(10));

CREATE MATERIALIZED VIEW GEOGRAPHIC_ADDRESS_CBI_FDIC_VW AS select 
party.PARTY_ID,
par.UNIQUE_PARTY_ROLE_ID,
address.ADDRESS_ID,
party_address.ADDRESS_USE,
address.ADDRESS_TYPE,
geographic_address.LINE_1 ADDRESS_LINE_1,
geographic_address.LINE_2 ADDRESS_LINE_2,
geographic_address.LINE_3 ADDRESS_LINE_3,
geographic_address.LINE_4 ADDRESS_LINE_4,
geographic_address.CITY,
geographic_address.STATE,
geographic_address.COUNTRY,
geographic_address.ZIP_1 ZIP_CODE
from
PARTY_ACCOUNT_ROLE par,
PARTY_ROLE pr,
PARTY_INSTITUTION_ASSOCIATION pi,
PARTY party,
PARTY_ADDRESS party_address,
ADDRESS address,
GEOGRAPHIC_ADDRESS geographic_address
where
par.UNIQUE_PARTY_ROLE_ID=pr.UNIQUE_PARTY_ROLE_ID AND
pr.UNIQUE_ASSOCIATION_ID=pi.UNIQUE_ASSOCIATION_ID AND	
party.PARTY_ID = pi.PARTY_ID AND
party.PARTY_ID = party_address.PARTY_ID (+) AND
party_address.ADDRESS_ID = address.ADDRESS_ID (+) AND
address.ADDRESS_ID = geographic_address.ADDRESS_ID(+);

-- COLLATERAL TYPE LOOKUP
ALTER TABLE COLLATERAL_TYPE_LOOKUP ADD (CO_CBI_TYPE VARCHAR2(10));

CREATE MATERIALIZED VIEW LOAN_ACCOUNT_CBI_FDIC_VW AS SELECT
	LA.ACCOUNT_ID,
	LA.LOAN_STATUS,
	LA.CLOSED_DATE,
	LA.FREQUENCY_PRINCIPAL,
	LA.NON_ESCROW_DUE,
        LA.PAYMENTS_SCHEDULED,
	LA.PAST_DUE_AMOUNT,
	LA.ACCOUNT_TYPE_ID,
	LA.ACCOUNT_NO,
	LA.CALL_REPORT_CODE,
	LA.LOAN_PURPOSE_CODE,
	LA.OPENING_BRANCH,
	LA.START_DATE,
	LA.NOTE_NUMBER,
	LA.NEXT_PAYMENT_DUE_DATE,
	LA.NEXT_PRINCIPLE_DUE,
	LP.DESCRIPTION LOAN_PURPOSE_DESCRIPTION,
	ATL.ACCOUNT_TYPE,
	LA.INSTITUTION_ID,
	LFL.DESCRIPTION LFL_DESCRIPTION,
	LA.PRINCIPAL_INTEREST_PAYMENT,
	LA.NEXT_ESCROW_DUE,
	LA.LIFE_INSURANCE_REBATE,
	LA.EMPLOYEE_CODE,
	LA.HOLD4_CODE,
	LA.INTEREST_PAID_TO_DATE,
	LA.PRIMARY_OFFICER,
	LA.APPROVED_LOAN_AMOUNT,
	LA.LAST_PAYMENT_DATE,
	LA.INTEREST_RATE_TYPE,
	BR.BRANCH_NAME,
	LCRL.DESCRIPTION CALL_REPORT_DESC,
	LA.PRINCIPLE_BALANCE,
	LA.LATE_FEES_DUE,
	LA.MFHASERVFEE,
	LA.BLOCK_ID CENSUS_TRACK,
	LA.CLASS_CODE,
	LTL.DESCRIPTION CLASS_CODE_DESC ,
	LA.CURRENT_MATURITY_DATE,
	LA.LOAN_TERM,
	C.COLLATERAL_DESC ,
	REN.RENEWAL_DATE,
	EXT.EXTENSION_DATE,
	EXT.NO_OF_EXTENSIONS,
	LBL.RANGE_30_59,
	LBL.RANGE_60_89,
	LBL.RANGE_90_365,
	LA.FIRST_PAYMENT_DATE,
	LA.CURRENT_INTEREST_RATE,
	LA.PARTIAL_PAYMENT,
	LA.ACCRUED_INTEREST,
	REN.NO_OF_RENEWALS,
	VIR.VARIANCE VARIANCE,
	VIR.RATE_CAP_UP RATE_CAP_UP,
	VIR.RATE_CHANGE_TERM RATE_CHANGE_TERM,
	VIR.RATE_CEILING RATE_CEILING ,
	VIR.RATE_INDEX RATE_INDEX,
	EA.CURRENT_BALANCE CURRENT_BALANCE,
	CA.APPRAISAL_DATE APPRAISAL_DATE,
	CA.APPRAISAL_VALUE APPRAISAL_VALUE,
        LA.GRACE_PERIOD LOANGRACEPERIOD,
    	LC.GRACE_PERIOD LATECHARGEGRAGEPERIOD,
    	INST.LAST_PROCESSED_DATE,
	LP.LO_CB_TYPE,
    	LTL.CL_CBI_TYPE,
    	CTL.CO_CBI_TYPE,
    	INST.REGION_NAME INSTITUTION_NAME,
    	LA.DATE_LAST_ACTIVITY
 
FROM
	LOAN_ACCOUNT_VW LA,
	ACCOUNT_TYPE_LOOKUP ATL,
	LOAN_PURPOSE_LOOKUP LP,
	INSTITUTION INST,
	LOAN_BILLS_LTD LBL,
   	LATE_CHARGE lc,
	BRANCH BR,
	LOAN_CALL_REPORT_LKP LCRL,
	ESCROW_ACCOUNT EA,
	VARIABLE_INTEREST_RATE VIR,
	LOANACCOUNT_COLLATERAL_MAPPING LCM,
	COLLATERAL C,
	COLLATERAL_APPRAISAL CA,
	LOAN_FREQUENCY_LOOKUP LFL,
	LOAN_TYPE_LOOKUP LTL,
        COLLATERAL_TYPE_LOOKUP ctl,
	(	SELECT
			R.NO_OF_RENEWALS,
			R.RENEWAL_DATE,
			LA.ACCOUNT_ID 
		FROM
			LOAN_ACCOUNT_VW LA,
			RENEWALS R 
		WHERE
			ROWNUM = 1 AND
			LA.ACCOUNT_ID = R.ACCOUNT_ID(+) 
		ORDER BY
			R.RENEWAL_DATE DESC 
	)
	REN,
	(	SELECT
			E.NO_OF_EXTENSIONS,
			E.EXTENSION_DATE,
			LA.ACCOUNT_ID 
		FROM
			LOAN_ACCOUNT_VW LA,
			EXTENSIONS E 
		WHERE
			ROWNUM = 1 AND
			LA.ACCOUNT_ID = E.ACCOUNT_ID(+) 
		ORDER BY
			E.EXTENSION_DATE DESC 
	)
	EXT 
WHERE
	LA.ACCOUNT_TYPE_ID = ATL.ACCOUNT_TYPE_ID AND
	LA.LOAN_PURPOSE_CODE=LP.UNIQUE_ID(+) AND
	LA.INSTITUTION_ID=INST.INSTITUTION_ID(+) AND
	LA.ACCOUNT_ID = LBL.ACCOUNT_ID(+) AND
	LA.OPENING_BRANCH=BR.UNIQUE_ID(+) AND
	LA.CALL_REPORT_CODE=LCRL.CALL_REPORT_CODE(+) AND
	LA.ESCROW_ACCOUNT_ID = EA.ESCROW_ACCOUNT_ID(+) AND
	LA.ACCOUNT_ID = VIR.ACCOUNT_ID (+) AND
	LCM.ACCOUNT_ID (+)=LA.ACCOUNT_ID AND
	C.COLLATERAL_ID(+)=LCM.COLLATERAL_ID AND
	CA.COLLATERAL_ID(+) =C.COLLATERAL_ID AND
	LA.FREQUENCY_PRINCIPAL = LFL.CODE(+) AND
	LA.CLASS_CODE = LTL.CLASS_CODE(+) AND
	LA.ACCOUNT_ID = EXT.ACCOUNT_ID(+) AND
	LA.ACCOUNT_ID = REN.ACCOUNT_ID(+) and
    	LA.LATE_CHARGE_CODE=LC.LATE_CHARGE_CODE(+) and
    	C.COLLATERAL_TYPE=CTL.COLLATERAL_TYPE(+);

CREATE MATERIALIZED VIEW PARTY_REGISTER_CBI_FDIC_VW AS 
SELECT p.PARTY_ID,prids.PARTY_ID REG_PARTY_ID,prids.TYPE,prids.PARTY_REGISTERD_ID 
from PARTY p,PARTY_REGISTERED_IDS prids where p.PARTY_ID = prids.PARTY_ID (+) AND
prids.TYPE IN ('SSN','TIN');


CREATE MATERIALIZED VIEW PARTY_CBI_FDIC_VW AS SELECT       
    org.BUSINESS_NAME,
    org.BUSINESS_TYPE,
    party.PARTY_ID,
    party.PARTY_TYPE,    
    ao.RESPONSIBILITY_TYPE,
    pi.INSTITUTION_ASSOCIATION_ID, 
    pi.GROUP_ID,
    par.ACCOUNT_ID,
    par.UNIQUE_PARTY_ROLE_ID,
    party.party_name, 	
    person.FIRST_NAME FIRSTNAME,
    person.LAST_NAME LASTNAME,
    person.Suffix,
    person.SEX,
    person.MIDDLE_NAME MIDDLENAME,
    person.DATE_OF_BIRTH,
    PRI.PARTY_REGISTERD_ID REGISTERED_ID,
    pri.type party_register_type,
    tel.PHONE
FROM
	PARTY_ACCOUNT_ROLE par,
	PARTY_ROLE pr,
	PARTY_INSTITUTION_ASSOCIATION pi,
    	PARTY party,
	ORGANIZATION org,
	PERSON person,
   	ACCOUNT_OWNER ao,
	PARTY_REGISTER_CBI_FDIC_VW PRI,
	PARTY_ADDRESS pa,
    	TELECOM_ADDRESS tel
WHERE
	par.UNIQUE_PARTY_ROLE_ID=pr.UNIQUE_PARTY_ROLE_ID AND
	pr.UNIQUE_ASSOCIATION_ID=pi.UNIQUE_ASSOCIATION_ID  AND	
   	party.PARTY_ID = pi.PARTY_ID AND
	par.UNIQUE_PARTY_ROLE_ID=ao.UNIQUE_PARTY_ROLE_ID AND
	pi.PARTY_ID=party.PARTY_ID AND	
	party.PARTY_ID=PRI.PARTY_ID (+) AND
	party.PARTY_ID=person.PARTY_ID(+) AND    
	party.PARTY_ID=org.PARTY_ID(+) AND    
	party.party_id=pa.PARTY_ID(+) AND
	pa.ADDRESS_ID=tel.ADDRESS_ID(+) AND
    	pa.ADDRESS_USE(+)='HOME_PHONE';



create index loan_fdic_vw_account_id ON LOAN_ACCOUNT_CBI_FDIC_VW(ACCOUNT_ID);

create index GEOGRAPHIC_ADDRESS_role_id ON GEOGRAPHIC_ADDRESS_CBI_FDIC_VW(UNIQUE_PARTY_ROLE_ID);

create index PARTY_CBI_FDIC_VW_account_id ON PARTY_CBI_FDIC_VW(ACCOUNT_ID);

create index PARTY_CBI_FDIC_VW_role_id ON PARTY_CBI_FDIC_VW(UNIQUE_PARTY_ROLE_ID);

create index PARTY_CBI_FDIC_VW_party_id ON PARTY_CBI_FDIC_VW(party_id);

create index PARTYCBI_FDIC_VW_party_id on PARTY_REGISTER_CBI_FDIC_VW(party_id);

ALTER TABLE LOAN_ACCOUNT ADD(MISC_LOAN_FEE_INDICATOR VARCHAR2(20));

DELETE FROM BILLING_BUCKET;

ALTER TABLE LOAN_ACCOUNT ADD(ACCRUED_UNUSED_LCF NUMBER(20,5));
ALTER TABLE LOAN_ACCOUNT ADD(ACCRUED_DLR_INT_DUE NUMBER(20,5));






