
--UPDATE ENTITY_TYPE_DEFINITION SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.NewSchedulePayment'
--WHERE TYPE_NAME like 'NewSchedulePayment';
--
--
---- remove condo dues from escrow insurance
--update property_definition set 
--valid_values = 'java.lang.Integer:{default={8=Earthquake Insurance,9=Special Insurance,6=Pvt Mortgage Ins(PMI,1=Hazard Insurance,7=Flood Insurance}}' 
--where valid_values like 'java.lang.Integer:{default={8=Earthquake Insurance,9=Special Insurance,6=Pvt Mortgage Ins(PMI,1=Hazard Insurance,7=Flood Insurance,10=Condo Dues}}';
--
--
---- make esrowtype editable for escrow other
--update PROPERTY_DEFINITION set EDITABLE = 1, EDITABLE_OVERRIDEN = 1 where ENTITY_TYPE_DEFINITION_ID in 
--(select ENTITY_TYPE_DEFINITION_ID from ENTITY_TYPE_DEFINITION where TYPE_NAME like 'EscrowOther');
--
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.NoPenalty'         
--WHERE TYPE_NAME='NoPenalty';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.TaxEscrow' 
--WHERE TYPE_NAME='TaxEscrow';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.CBTLoan' 
--WHERE TYPE_NAME='CBTLoan';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.MobileFamily02' 
--WHERE TYPE_NAME='MobileFamily02';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.MultiFamily03' 
--WHERE TYPE_NAME='MultiFamily03';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.LotsLand04' 
--WHERE TYPE_NAME='LotsLand04';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.Municipals05' 
--WHERE TYPE_NAME='Municipals05';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.HomeEquity06' 
--WHERE TYPE_NAME='HomeEquity06';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.Hotels07' 
--WHERE TYPE_NAME='Hotels07';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.AnchoredShoppingCentre08' 
--WHERE TYPE_NAME='AnchoredShoppingCentre08';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.MobileHomePark10' 
--WHERE TYPE_NAME='MobileHomePark10';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.OfficeBuildings09' 
--WHERE TYPE_NAME='OfficeBuildings09';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.MobileHomePark10' 
--WHERE TYPE_NAME='MobileHomePark10';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.Churches11' 
--WHERE TYPE_NAME='Churches11';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.CommercialBuilding12' 
--WHERE TYPE_NAME='CommercialBuilding12';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.HealthCareFacilities13' 
--WHERE TYPE_NAME='HealthCareFacilities13';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.OtherCommercial14' 
--WHERE TYPE_NAME='OtherCommercial14';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.ARInventory15' 
--WHERE TYPE_NAME='ARInventory15';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.FurnitureFixtures16' 
--WHERE TYPE_NAME='FurnitureFixtures16';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.Equipment17' 
--WHERE TYPE_NAME='Equipment17';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.OvertheRoadTractorTrailers18' 
--WHERE TYPE_NAME='OvertheRoadTractorTrailers18';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.FormLoans19' 
--WHERE TYPE_NAME='FormLoans19';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.CarTrucks20' 
--WHERE TYPE_NAME='CarTrucks20';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.Boats21' 
--WHERE TYPE_NAME='Boats21';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.Aircrafts22' 
--WHERE TYPE_NAME='Aircrafts22';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.MotorcyclesATV23' 
--WHERE TYPE_NAME='MotorcyclesATV23';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.CampersRV24' 
--WHERE TYPE_NAME='CampersRV24';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.SavingCD25' 
--WHERE TYPE_NAME='SavingCD25';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.Stock26' 
--WHERE TYPE_NAME='Stock26';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.Insurance27' 
--WHERE TYPE_NAME='Insurance27';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.NotesReceivableAssessmentsoflease28' 
--WHERE TYPE_NAME='NotesReceivableAssessmentsoflease28';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.UnsecureLoan99' 
--WHERE TYPE_NAME='UnsecureLoan99';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.BankClassification' 
--WHERE TYPE_NAME='BankClassification';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.PropertyCollateralCode' 
--WHERE TYPE_NAME='PropertyCollateralCode';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.StockCollateralCode' 
--WHERE TYPE_NAME='StockCollateralCode';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.TitleCollateralCode' 
--WHERE TYPE_NAME='TitleCollateralCode';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.DepositCollateralCode' 
--WHERE TYPE_NAME='DepositCollateralCode';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.OtherCollateralCode' 
--WHERE TYPE_NAME='OtherCollateralCode';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.PropertyCollateralAppraisal' 
--WHERE TYPE_NAME='PropertyCollateralAppraisal';
--
---- need to ask sandeep
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.PastDueNoticeSchedule' 
--WHERE TYPE_NAME='PastDueNoticeSchedule';
--
--UPDATE ENTITY_TYPE_DEFINITION 
--SET ENTITY_TYPE_INSTANCE_CLASS='com.vsoftcorp.loan.model.entities.PastDuePeriod' 
--WHERE TYPE_NAME='PastDuePeriod';
--
--
--DELETE FROM ENTITY_TYPE_DEFINITION WHERE BASE_ENTITY_TYPE_DEF_ID='561';

CREATE TABLE CLASS_CODE_MAPPING(
UNIQUE_ID NUMBER(10),
ACCOUNT_TYPE_ID VARCHAR2(10),
CLASS_CODE VARCHAR2(10),
DESCRIPTION VARCHAR2(100),
TYPE_CODE VARCHAR2(10),
PRODUCT_CODE VARCHAR2(10),
COLLATERAL_CODE VARCHAR2(10),
PURPOSE_CODE VARCHAR2(10));

CREATE TABLE CBT_LOAN (
    CBT_LOAN_ID NUMBER(15) NOT NULL,
    CONSTRAINT CBT_LOAN_ID_PK PRIMARY KEY(CBT_LOAN_ID)
);

CREATE TABLE SINGLE_FAMILY_01 (
    SINGLE_FAMILY_ID NUMBER(15) NOT NULL,
    CONSTRAINT SINGLE_FAMILY_ID_PK PRIMARY KEY(SINGLE_FAMILY_ID)
);

CREATE TABLE MOBILE_FAMILY_02 (
    MOBILE_FAMILY_ID NUMBER(15) NOT NULL,
    CONSTRAINT MOBILE_FAMILY_ID_PK PRIMARY KEY(MOBILE_FAMILY_ID)
);

CREATE TABLE MULTI_FAMILY_03 (
    MULTI_FAMILY_ID NUMBER(15) NOT NULL,
    CONSTRAINT MULTI_FAMILY_ID_PK PRIMARY KEY(MULTI_FAMILY_ID)
);

CREATE TABLE LOTS_LAND_04 (
    LOTS_LAND_ID NUMBER(15) NOT NULL,
    CONSTRAINT LOTS_LAND_ID_PK PRIMARY KEY(LOTS_LAND_ID)
);

CREATE TABLE MUNICIPAL_05 (
    MUNICIPAL_ID NUMBER(15) NOT NULL,
    CONSTRAINT MUNICIPAL_ID_PK PRIMARY KEY(MUNICIPAL_ID)
);

CREATE TABLE HOME_EQUITY_06 (
    HOME_EQUITY_ID NUMBER(15) NOT NULL,
    CONSTRAINT HOME_EQUITY_ID_PK PRIMARY KEY(HOME_EQUITY_ID)
);


CREATE TABLE HOTEL_07 (
    HOTEL_ID NUMBER(15) NOT NULL,
    CONSTRAINT HOTEL_ID_PK PRIMARY KEY(HOTEL_ID)
);

CREATE TABLE ANCHORED_SHOP_CENTRE_08 (
    ANCHORED_SHOP_CENTRE_ID NUMBER(15) NOT NULL,
    CONSTRAINT ANCHORED_SHOP_CENTRE_ID_PK PRIMARY KEY(ANCHORED_SHOP_CENTRE_ID)
);

CREATE TABLE OFFICE_BUILDING_09 (
    OFFICE_BUILDING_ID NUMBER(15) NOT NULL,
    CONSTRAINT OFFICE_BUILDING_ID_PK PRIMARY KEY(OFFICE_BUILDING_ID)
);


CREATE TABLE MOBILE_HOME_PARK_10 (
    MOBILE_HOME_PARK_ID NUMBER(15) NOT NULL,
    CONSTRAINT MOBILE_HOME_PARK_ID_PK PRIMARY KEY(MOBILE_HOME_PARK_ID)
);

CREATE TABLE CHURCHES_11 (
    CHURCHES_ID NUMBER(15) NOT NULL,
    CONSTRAINT CHURCHES_ID_PK PRIMARY KEY(CHURCHES_ID)
);

CREATE TABLE COMMERCIAL_BUILD_12 (
    COMMERCIAL_BUILD_ID NUMBER(15) NOT NULL,
    CONSTRAINT COMMERCIAL_BUILD_ID_PK PRIMARY KEY(COMMERCIAL_BUILD_ID)
);

CREATE TABLE HEALTH_CARE_FACILITIES_13(
    HEALTH_CARE_ID NUMBER(15) NOT NULL,
    CONSTRAINT HEALTH_CARE_ID_PK PRIMARY KEY(HEALTH_CARE_ID)
);

CREATE TABLE OTHER_COMMERCIAL_14 (
    OTHER_COMM_ID NUMBER(15) NOT NULL,
    CONSTRAINT OTHER_COMM_ID_PK PRIMARY KEY(OTHER_COMM_ID)
);

CREATE TABLE ARINVENTORY_15 (
    AR_INVENTORY_ID NUMBER(15) NOT NULL,
    CONSTRAINT AR_INVENTORY_ID_PK PRIMARY KEY(AR_INVENTORY_ID)
);

CREATE TABLE FURNITURE_FIXTURE_16 (
    FURNITURE_FIXTURE_ID NUMBER(15) NOT NULL,
    CONSTRAINT FURNITURE_FIXTURE_ID_PK PRIMARY KEY(FURNITURE_FIXTURE_ID)
);

CREATE TABLE EUIPMENT_17 (
    EUIPMENT_ID NUMBER(15) NOT NULL,
    CONSTRAINT EUIPMENT_ID_PK PRIMARY KEY(EUIPMENT_ID)
);

CREATE TABLE OVER_ROAD_TRACTORTRAILER_18 (
    OVER_ROAD_TRACTOR_TRAILER_ID NUMBER(15) NOT NULL,
    CONSTRAINT OVER_ROAD_TRACTORTRAILER_ID_PK PRIMARY KEY(OVER_ROAD_TRACTOR_TRAILER_ID)
);

CREATE TABLE FORM_LOANS_19 (
    FORM_LOANS_ID NUMBER(15) NOT NULL,
    CONSTRAINT FORM_LOANS_ID_PK PRIMARY KEY(FORM_LOANS_ID)
);

CREATE TABLE CAR_TRUCKS_20(
    CAR_TRUCKS_ID NUMBER(15) NOT NULL,
    CONSTRAINT CAR_TRUCKS_ID_PK PRIMARY KEY(CAR_TRUCKS_ID)
);

CREATE TABLE BOATS_21(
    BOATS_ID NUMBER(15) NOT NULL,
    CONSTRAINT BOATS_ID_PK PRIMARY KEY(BOATS_ID)
);

CREATE TABLE AIR_CRAFTS_22(
    AIR_CRAFT_ID NUMBER(15) NOT NULL,
    CONSTRAINT AIR_CRAFT_ID_PK PRIMARY KEY(AIR_CRAFT_ID)
);

CREATE TABLE MOTOR_CYCLE_ATV_23(
    MOTOR_CYCLE_ATV_ID NUMBER(15) NOT NULL,
    CONSTRAINT MOTOR_CYCLE_ATV_ID_PK PRIMARY KEY(MOTOR_CYCLE_ATV_ID)
);

CREATE TABLE CAMPERS_RV_24(
    CAMPERS_RV_ID NUMBER(15) NOT NULL,
    CONSTRAINT CAMPERS_RV_ID_PK PRIMARY KEY(CAMPERS_RV_ID)
);

CREATE TABLE SAVING_CD_25(
    SAVING_CD_ID NUMBER(15) NOT NULL,
    CONSTRAINT SAVING_CD_ID_PK PRIMARY KEY(SAVING_CD_ID)
);

CREATE TABLE STOCK_26(
    STOCK_ID NUMBER(15) NOT NULL,
    CONSTRAINT STOCK_ID_PK PRIMARY KEY(STOCK_ID)
);

CREATE TABLE INSURANCE_27(
    INSURANCE_ID NUMBER(15) NOT NULL,
    CONSTRAINT INSURANCE_ID_PK PRIMARY KEY(INSURANCE_ID)
);

CREATE TABLE NOTE_REC_ASSES_OF_LEASE_28(
    NOTE_REC_ASSES_OF_LEASE_ID NUMBER(15) NOT NULL,
    CONSTRAINT NOTE_REC_ASSES_OF_LEASE_ID_PK PRIMARY KEY(NOTE_REC_ASSES_OF_LEASE_ID)
);

CREATE TABLE UNSECURE_LOAN_99(
    UNSECURE_LOAN_ID NUMBER(15) NOT NULL,
    CONSTRAINT UNSECURE_LOAN_ID_PK PRIMARY KEY(UNSECURE_LOAN_ID)
);

CREATE TABLE PROPERTY_COLL_APPRAISAL_NEW ( 
    PROPERTY_COLL_APPRAISAL_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT PROPERTY_COLL_APPRAI_PK PRIMARY KEY(PROPERTY_COLL_APPRAISAL_ID)
);

CREATE TABLE PROPERTY_COLL_CODE ( 
   PROPERTY_COLL_CODE_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT PROPERTY_COLL_CODE_PK PRIMARY KEY(PROPERTY_COLL_CODE_ID)
);

CREATE TABLE TITLE_COLL_CODE ( 
   TITLE_COLL_CODE_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT TITLE_COLL_CODE_ID_PK PRIMARY KEY(TITLE_COLL_CODE_ID)
);

CREATE TABLE STOCK_COLL_CODE ( 
   STOCK_COLL_CODE_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT STOCK_COLL_CODE_ID_PK PRIMARY KEY(STOCK_COLL_CODE_ID)
);

CREATE TABLE DEPOSIT_COLL_CODE ( 
   DEPOSIT_COLL_CODE_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT DEPOSIT_COLL_CODE_ID_PK PRIMARY KEY(DEPOSIT_COLL_CODE_ID)
);

CREATE TABLE OTHER_COLL_CODE ( 
   OTHER_COLL_CODE_ID	NUMBER(15,0) NOT NULL,
    CONSTRAINT OTHER_COLL_CODE_ID_PK PRIMARY KEY(OTHER_COLL_CODE_ID)
);

CREATE TABLE NO_PENALTY ( 
   	NO_PENALTY_ID NUMBER(15,0) NOT NULL,
    CONSTRAINT NO_PENALTY_ID_PK PRIMARY KEY(NO_PENALTY_ID)
);



UPDATE PROPERTY_DEFINITION SET CATEGORY_OVERRIDEN=0 WHERE CATEGORY_OVERRIDEN IS NULL;
UPDATE ASSOCIATE_DEFINITION SET TEMPLATE_OVERRIDEN=0 WHERE TEMPLATE_OVERRIDEN IS NULL;

--INSERT INTO ASSOCIATE_DEFINITION(ASSOCIATE_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, ASSOCIATE_NAME, ASSOCIATE_INDEX, ASSOCIATE_DESCRIPTION, ASSOCIATE_TYPE_DEFINITION_ID, ASSOCIATE_TYPE_OVERRIDEN, MULTIPLICITY, MULTIPLICITY_OVERRIDEN, ASSOCIATION_TYPE, ASSOCIATION_TYPE_OVERRIDEN, LAZY, LAZY_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, COPY, COPY_OVERRIDEN, DEFAULT_INSTANCE, DEFAULT_INSTANCE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, TEMPLATE, TEMPLATE_OVERRIDEN)
--  VALUES((SELECT MAX(ASSOCIATE_DEFINITION_ID)+1 FROM ASSOCIATE_DEFINITION), 421, 'CollectionOfficer', 10, 'Collection Officer', 646, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, NULL, 0, 0, 1, 1, 0, 'U', NULL, 0);



 
 
