CREATE TABLE COUNTRY_MASTER (
    COUNTRY_CODE NUMBER NOT NULL ENABLE,
    COUNTRY_NAME VARCHAR2(5 BYTE),
    CONSTRAINT  COUNTRY_MASTER_PK PRIMARY KEY (COUNTRY_CODE) ENABLE
);

CREATE TABLE STATES_MASTER (
    STATES_UNIQUE_ID NUMBER NOT NULL ENABLE,
    STATE_CODE NUMBER,
    STATE_NAME VARCHAR2(5 BYTE),
    COUNTRY_CODE NUMBER,
    CONSTRAINT  STATES_MASTER_PK PRIMARY KEY (STATES_UNIQUE_ID) ENABLE,
   CONSTRAINT  STATES_MASTER_FK FOREIGN KEY (COUNTRY_CODE) REFERENCES COUNTRY_MASTER(COUNTRY_CODE) ENABLE
); 

CREATE TABLE COUNTY_MASTER (
    COUNTY_UNIQUE_ID NUMBER NOT NULL ENABLE,
    COUNTY_CODE NUMBER,
    COUNTY_NAME VARCHAR2(100 BYTE),
    STATES_UNIQUE_ID NUMBER,
    COUNTRY_CODE NUMBER,
    CONSTRAINT  COUNTY_MASTER_COUNTRY_FK FOREIGN KEY (COUNTRY_CODE) REFERENCES COUNTRY_MASTER(COUNTRY_CODE) ENABLE,
    CONSTRAINT  COUNTY_MASTER_STATE_FK FOREIGN KEY (STATES_UNIQUE_ID) REFERENCES STATES_MASTER(STATES_UNIQUE_ID) ENABLE);
    
    
CREATE TABLE CIP_INFORMATION (
    UNIQUE_ID NUMBER NOT NULL ENABLE,
    CIP_INFORMATION varchar2(2000),
    PARTY_ID VARCHAR2(15),
    CONSTRAINT  CIP_INFORMATION_PK PRIMARY KEY (UNIQUE_ID) ENABLE,
   CONSTRAINT  CIP_INFORMATION_FK FOREIGN KEY (PARTY_ID) REFERENCES PARTY(PARTY_ID) ENABLE
   
);
