
----------------------------------------DeferredIncomeExpense---------------------------------------------

--INSERT INTO ENTITY_TYPE_DEFINITION(ENTITY_TYPE_DEFINITION_ID, TYPE_NAME, TYPE_DESCRIPTION, ENTITY_TYPE_INSTANCE_CLASS, BASE_ENTITY_TYPE_DEF_ID, LOOKUP, SYSTEM)VALUES((select max(ENTITY_TYPE_DEFINITION_ID)+1 from ENTITY_TYPE_DEFINITION), 'DeferredIncomeExpense', 'Deferred Income/Expense', 'com.vsoftcorp.loan.model.entities.DefferedIncomeExpense', NULL, 0, NULL);

----------------------------------------TotalFees property---------------------------------------------

--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((select max(property_definition_id)+1 from property_definition),(select max(ENTITY_TYPE_DEFINITION_ID) from ENTITY_TYPE_DEFINITION), 'TotalFees', 0, 'Total Fees', 8, 0, 0, NULL, 0, 'com.vsoftcorp.finance.Money:{default={}}', 0, 0, 0, 0, 1, 0, 0, 'U', NULL, NULL);
 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'DEFAULT'); 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'INQUIRY'); 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'ACCOUNT_CREATED'); 

----------------------------------------TotalCosts property---------------------------------------------

--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((select max(property_definition_id)+1 from property_definition), (select max(ENTITY_TYPE_DEFINITION_ID) from ENTITY_TYPE_DEFINITION), 'TotalCosts', 1, 'Total Costs', 8, 0, 0, NULL, 0, 'com.vsoftcorp.finance.Money:{default={}}', 0, 0, 0, 0, 1, 0, 0, 'U', NULL, NULL);
  
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'DEFAULT'); 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'INQUIRY'); 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'ACCOUNT_CREATED'); 

----------------------------------------CurrentNetFees property---------------------------------------------

--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN,INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((select max(property_definition_id)+1 from property_definition), (select max(ENTITY_TYPE_DEFINITION_ID) from ENTITY_TYPE_DEFINITION), 'CurrentNetFees', 2, 'Current Net Fees', 8, 0, 0, NULL, 0, 'com.vsoftcorp.finance.Money:{default={}}', 0, 0, 0, 0, 1, 0, 0, 'U', NULL, NULL);

--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'DEFAULT'); 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'INQUIRY'); 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'ACCOUNT_CREATED'); 

----------------------------------------CurrentEffectiveBalance property---------------------------------------------

--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((select max(property_definition_id)+1 from property_definition), (select max(ENTITY_TYPE_DEFINITION_ID) from ENTITY_TYPE_DEFINITION), 'CurrentEffectiveBalance', 3, 'Current Effective Balance', 8, 0, 0, NULL, 0, 'com.vsoftcorp.finance.Money:{default={}}', 0, 0, 0, 0, 1, 0, 0, 'U', NULL, NULL);

--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'DEFAULT'); 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'INQUIRY'); 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'ACCOUNT_CREATED'); 

----------------------------------------TakeEarningExpensesonPayoff property---------------------------------------------

--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((select max(property_definition_id)+1 from property_definition), (select max(ENTITY_TYPE_DEFINITION_ID) from ENTITY_TYPE_DEFINITION), 'TakeEarningExpensesonPayoff', 4, 'Take Earning Expenses on Payoff', 0, 0, 0, 'java.lang.Boolean:true', 0, 'java.lang.Boolean:{default={true=Yes, false=No}}', 0, 0, 0, 0, 1, 0, 0, 'UC', NULL, NULL);

--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 1, 0, 'DEFAULT'); 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 1, 0, 'INQUIRY'); 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 1, 0, 'ACCOUNT_CREATED'); 

----------------------------------------RecalculateEffectiveRate property---------------------------------------------

--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((select max(property_definition_id)+1 from property_definition), (select max(ENTITY_TYPE_DEFINITION_ID) from ENTITY_TYPE_DEFINITION), 'RecalculateEffectiveRate',5 , 'Recalculate Effective Rate', 0, 0, 0, 'java.lang.Boolean:true', 0, 'java.lang.Boolean:{default={true=Yes, false=No}}', 0, 0, 0, 0, 1, 0, 0, 'UC', NULL, NULL);

--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 1, 0, 'DEFAULT'); 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 1, 0, 'INQUIRY');
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 1, 0, 'ACCOUNT_CREATED');

----------------------------------------EarningExpenseMethod property---------------------------------------------

--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((select max(property_definition_id)+1 from property_definition), (select max(ENTITY_TYPE_DEFINITION_ID) from ENTITY_TYPE_DEFINITION), 'EarningExpenseMethod', 6, 'Earning Expense Method', 2, 0, 0, 'java.lang.Integer:0', 0, 'java.lang.Integer:{default={0=Amortize, 1=Straight Line}}', 0, 0, 0,  0, 1, 0, 0, 'UC', NULL, NULL);

--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 1, 0, 'DEFAULT'); 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 1, 0, 'INQUIRY'); 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 1, 0, 'ACCOUNT_CREATED'); 

----------------------------------------EffectiveInterestRate property---------------------------------------------

--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((select max(property_definition_id)+1 from property_definition), (select max(ENTITY_TYPE_DEFINITION_ID) from ENTITY_TYPE_DEFINITION), 'EffectiveInterestRate', 7, 'Effective Interest Rate', 4, 0, 0, NULL, 0, 'com.vsoftcorp.types.Percentage:{default={}}', 0, 0, 0, 0, 1, 0, 0, 'U', NULL, NULL);

--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'DEFAULT'); 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'INQUIRY'); 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'ACCOUNT_CREATED'); 

----------------------------------------NumberOfPayments property---------------------------------------------
update PROPERTY_DEFINITION set PROPERTY_NAME='NumberOfPayments', PROPERTY_DESCRIPTION='Number Of Payments', VALUE_TYPE_DEFINITION_ID=2, 
DESCRIPTION_FIELD=0, DESCRIPTION_FIELD_OVERRIDEN=0, DEFAULT_VALUE=NULL, DEFAULT_VALUE_OVERRIDEN=0, VALID_VALUES='java.lang.Integer:{default={}}', 
VALID_VALUES_OVERRIDEN=0, MANDATORY=0, MANDATORY_OVERRIDEN=0, INHERITED=0, CAN_EDIT_DEFINITION=1, CAN_DELETE_DEFINITION=0, 
CATEGORY_OVERRIDEN=0, CATEGORY='U', PRIMARY_OVERRIDEN=NULL, PRIMARY=NULL
where PROPERTY_DEFINITION_ID in (select PROPERTY_DEFINITION_ID from property_definition where PROPERTY_NAME ='TerminMonths');

--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((select max(property_definition_id)+1 from property_definition), (select max(ENTITY_TYPE_DEFINITION_ID) from ENTITY_TYPE_DEFINITION), 'NumberOfPayments', 8, 'Number Of Payments', 2, 0, 0, NULL, 0, 'java.lang.Integer:{default={}}', 0, 0, 0, 0, 1, 0, 0, 'U', NULL, NULL);
  
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'DEFAULT'); 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'INQUIRY'); 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'ACCOUNT_CREATED'); 

----------------------------------------RemainingPayments property---------------------------------------------
update PROPERTY_DEFINITION set PROPERTY_NAME='RemainingPayments', PROPERTY_DESCRIPTION='Remaining Payments', 
VALUE_TYPE_DEFINITION_ID=2, DESCRIPTION_FIELD=0, DESCRIPTION_FIELD_OVERRIDEN=0, DEFAULT_VALUE=NULL, 
DEFAULT_VALUE_OVERRIDEN=0, VALID_VALUES='java.lang.Integer:{default={}}', VALID_VALUES_OVERRIDEN=0, MANDATORY=0, MANDATORY_OVERRIDEN=0,
INHERITED=0, CAN_EDIT_DEFINITION=1, CAN_DELETE_DEFINITION=0, CATEGORY_OVERRIDEN=0, CATEGORY='U', PRIMARY_OVERRIDEN=NULL, PRIMARY=NULL
where PROPERTY_DEFINITION_ID in (select PROPERTY_DEFINITION_ID from property_definition where PROPERTY_NAME ='TermRemaininginMonths');

--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((select max(property_definition_id)+1 from property_definition), (select max(ENTITY_TYPE_DEFINITION_ID) from ENTITY_TYPE_DEFINITION) , 'RemainingPayments', 9, 'Remaining Payments', 2, 0, 0, NULL, 0, 'java.lang.Integer:{default={}}', 0, 0, 0, 0, 1, 0, 0, 'U', NULL, NULL);

--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'DEFAULT'); 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'INQUIRY'); 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'ACCOUNT_CREATED'); 

----------------------------------------DefferedEarnigMTD property---------------------------------------------

--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((select max(property_definition_id)+1 from property_definition), (select max(ENTITY_TYPE_DEFINITION_ID) from ENTITY_TYPE_DEFINITION) , 'DefferedEarnigMTD', 10, 'Deffered Earnig MTD', 8, 0, 0, NULL, 0, 'com.vsoftcorp.finance.Money:{default={}}', 0, 0, 0, 0, 1, 0, 0, 'U', NULL, NULL);

--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'DEFAULT'); 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'INQUIRY'); 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'ACCOUNT_CREATED'); 

----------------------------------------DefferedEarnigYTD property---------------------------------------------

--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((select max(property_definition_id)+1 from property_definition), (select max(ENTITY_TYPE_DEFINITION_ID) from ENTITY_TYPE_DEFINITION) , 'DefferedEarnigYTD', 11, 'Deffered Earnig YTD', 8, 0, 0, NULL, 0, 'com.vsoftcorp.finance.Money:{default={}}', 0, 0, 0, 0, 1, 0, 0, 'U', NULL, NULL);

--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'DEFAULT'); 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'INQUIRY'); 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'ACCOUNT_CREATED'); 

----------------------------------------DefferedEarnigLTD property---------------------------------------------
  
--INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
--  VALUES((select max(property_definition_id)+1 from property_definition), (select max(ENTITY_TYPE_DEFINITION_ID) from ENTITY_TYPE_DEFINITION) , 'DefferedEarnigLTD', 12, 'Deffered Earnig LTD', 8, 0, 0, NULL, 0, 'com.vsoftcorp.finance.Money:{default={}}', 0, 0, 0, 0, 1, 0, 0, 'U', NULL, NULL);

--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'DEFAULT'); 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'INQUIRY'); 
--INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(property_definition_id) from property_definition), 0, 0, 0, 0, 'ACCOUNT_CREATED');

----------------------------------------AdjustmentType property---------------------------------------------

INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
  VALUES(PROPDEFID_SEQ.nextval, (select max(ENTITY_TYPE_DEFINITION_ID) from entity_type_definition where type_name like 'DeferredIncomeExpense') ,
 'AdjustmentType', 13, 'Adjustment Type', 2, 0, 0, NULL, 0, 'java.lang.Integer:{default={0=Credit, 1=Debit}}', 0, 0, 0, 0, 1, 0, 0, 'U', NULL, NULL);

INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
  VALUES((select max(property_definition_id) from property_definition), 0, 0, 1, 0, 'DEFAULT'); 
INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
  VALUES((select max(property_definition_id) from property_definition), 0, 0, 1, 0, 'INQUIRY'); 
INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
  VALUES((select max(property_definition_id) from property_definition), 0, 0, 1, 0, 'ACCOUNT_CREATED');

----------------------------------------AdjustmentAmount property---------------------------------------------
  
INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
  VALUES(PROPDEFID_SEQ.nextval, (select max(ENTITY_TYPE_DEFINITION_ID) from entity_type_definition where type_name like 'DeferredIncomeExpense') , 'AdjustmentAmount', 14, 'Adjustment Amount', 8, 0, 0, NULL, 0, 'com.vsoftcorp.finance.Money:{default={}}', 0, 0, 0, 0, 1, 0, 0, 'U', NULL, NULL);

INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
  VALUES((select max(property_definition_id) from property_definition), 0, 0, 1, 0, 'DEFAULT'); 
INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
  VALUES((select max(property_definition_id) from property_definition), 0, 0, 1, 0, 'INQUIRY'); 
INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
  VALUES((select max(property_definition_id) from property_definition), 0, 0, 1, 0, 'ACCOUNT_CREATED');


----------------------------------------Fees Collection Association--------------------------------------------- 

--INSERT INTO ASSOCIATE_DEFINITION(ASSOCIATE_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, ASSOCIATE_NAME, ASSOCIATE_INDEX, ASSOCIATE_DESCRIPTION, ASSOCIATE_TYPE_DEFINITION_ID, ASSOCIATE_TYPE_OVERRIDEN, MULTIPLICITY, MULTIPLICITY_OVERRIDEN, ASSOCIATION_TYPE, ASSOCIATION_TYPE_OVERRIDEN, LAZY, LAZY_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, COPY, COPY_OVERRIDEN, DEFAULT_INSTANCE, DEFAULT_INSTANCE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, TEMPLATE, TEMPLATE_OVERRIDEN)
--  VALUES((select max(associate_definition_id)+1 from associate_definition), (select max(ENTITY_TYPE_DEFINITION_ID) from ENTITY_TYPE_DEFINITION), 'Fees', 0, 'Fees', 524, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, NULL, 0, 0, 1, 0, 0, 'U', NULL, 0);

--INSERT INTO ASSOCIATE_PRESENTER_ATTRIBUTES(ASSOCIATE_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(associate_definition_id) from associate_definition), 0, 0, 1, 0, 'ACCOUNT_CREATED');
--INSERT INTO ASSOCIATE_PRESENTER_ATTRIBUTES(ASSOCIATE_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(associate_definition_id) from associate_definition), 0, 0, 1, 0, 'DEFAULT');
--INSERT INTO ASSOCIATE_PRESENTER_ATTRIBUTES(ASSOCIATE_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(associate_definition_id) from associate_definition), 0, 0, 1, 0, 'INQUIRY');

----------------------------------------Costs Collection Association--------------------------------------------- 


--INSERT INTO ASSOCIATE_DEFINITION(ASSOCIATE_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, ASSOCIATE_NAME, ASSOCIATE_INDEX, ASSOCIATE_DESCRIPTION, ASSOCIATE_TYPE_DEFINITION_ID, ASSOCIATE_TYPE_OVERRIDEN, MULTIPLICITY, MULTIPLICITY_OVERRIDEN, ASSOCIATION_TYPE, ASSOCIATION_TYPE_OVERRIDEN, LAZY, LAZY_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, COPY, COPY_OVERRIDEN, DEFAULT_INSTANCE, DEFAULT_INSTANCE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, TEMPLATE, TEMPLATE_OVERRIDEN)
--  VALUES((select max(associate_definition_id)+1 from associate_definition), (select max(ENTITY_TYPE_DEFINITION_ID) from ENTITY_TYPE_DEFINITION), 'Costs', 1, 'Costs', 524, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, NULL, 0, 0, 1, 0, 0, 'U', NULL, 0);
  
--INSERT INTO ASSOCIATE_PRESENTER_ATTRIBUTES(ASSOCIATE_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(associate_definition_id) from associate_definition), 0, 0, 1, 0, 'ACCOUNT_CREATED');
--INSERT INTO ASSOCIATE_PRESENTER_ATTRIBUTES(ASSOCIATE_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(associate_definition_id) from associate_definition), 0, 0, 1, 0, 'DEFAULT');
--INSERT INTO ASSOCIATE_PRESENTER_ATTRIBUTES(ASSOCIATE_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(associate_definition_id) from associate_definition), 0, 0, 1, 0, 'INQUIRY');

----------------------------------------EarningExpensesHistory Collection Association--------------------------------------------- 

--INSERT INTO ASSOCIATE_DEFINITION(ASSOCIATE_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, ASSOCIATE_NAME, ASSOCIATE_INDEX, ASSOCIATE_DESCRIPTION, ASSOCIATE_TYPE_DEFINITION_ID, ASSOCIATE_TYPE_OVERRIDEN, MULTIPLICITY, MULTIPLICITY_OVERRIDEN, ASSOCIATION_TYPE, ASSOCIATION_TYPE_OVERRIDEN, LAZY, LAZY_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, COPY, COPY_OVERRIDEN, DEFAULT_INSTANCE, DEFAULT_INSTANCE_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, TEMPLATE, TEMPLATE_OVERRIDEN)
 --VALUES((select max(associate_definition_id)+1 from associate_definition), (select max(ENTITY_TYPE_DEFINITION_ID) from ENTITY_TYPE_DEFINITION), 'EarningExpensesHistory', 2, 'Earning/Expenses History', 705, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, NULL, 0, 0, 1, 0, 0, 'U', NULL, 0);  

--INSERT INTO ASSOCIATE_PRESENTER_ATTRIBUTES(ASSOCIATE_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(associate_definition_id) from associate_definition), 1, 0, 1, 0, 'ACCOUNT_CREATED');
--INSERT INTO ASSOCIATE_PRESENTER_ATTRIBUTES(ASSOCIATE_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(associate_definition_id) from associate_definition), 1, 0, 1, 0, 'DEFAULT');
--INSERT INTO ASSOCIATE_PRESENTER_ATTRIBUTES(ASSOCIATE_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
--  VALUES((select max(associate_definition_id) from associate_definition), 1, 0, 1, 0, 'INQUIRY');

--------------------------------------------------Amortization_Schedule-----------------------------------------------------------------------

 CREATE TABLE "AMORTIZATION_SCHEDULE" 
   ("AMORTIZATION_SCHEDULE_ID" NUMBER(10,0), 
	"EFFECTIVE_INTEREST_RATE" NUMBER(10,5), 
	"CASH_INFLOW" NUMBER(20,5), 
	"STATED_INTEREST" NUMBER(20,5), 
	"REMAINING_PRINCIPAL" NUMBER(20,5), 
	"INTEREST_INCOME" NUMBER(20,5), 
	"AMORTIZED_NETFEE" NUMBER(20,5), 
	"UNAMORTIZED_NETFEE" NUMBER(20,5), 
	"CARRYING_AMOUNT" NUMBER(20,5), 
	"SCHEDULED_PAYMENT_DUE_DATE" DATE, 
	"CREATION_DATE" DATE DEFAULT sysdate, 
	"ACCOUNT_ID" VARCHAR2(20), 
	"ADJUSTMENT_TYPE" VARCHAR2(20), 
	"ADJUSTMENT_AMOUNT" NUMBER(20,5)
   ); 

--------------------------------------------------Amortization_Schedule_SEQ-----------------------------------------------------------------------

  CREATE SEQUENCE AMORTIZATION_SCHEDULE_SEQ START WITH 1;

ALTER TABLE LOAN_ENTRY_POSTING_RULE ADD AFF_AMORTIZATION NUMBER(20) DEFAULT 0;

--UPDATE loan_entry_posting_rule SET AFF_AMORTIZATION=1 WHERE POSTING_RULE_ID='8882';--Not required for Regular Payment

UPDATE loan_entry_posting_rule SET AFF_AMORTIZATION=1 WHERE POSTING_RULE_ID='8883';

UPDATE loan_entry_posting_rule SET AFF_AMORTIZATION=1 WHERE POSTING_RULE_ID='8820';

UPDATE loan_entry_posting_rule SET AFF_AMORTIZATION=1 WHERE POSTING_RULE_ID='9999';
-------To update/correct property_definition->property_description field value spell mistake
update property_definition set property_description='Deferred Earning MTD' where property_description='Deffered Earnig MTD';
update property_definition set property_description='Deferred Earning LTD' where property_description='Deffered Earnig LTD';
update property_definition set property_description='Deferred Earning YTD' where property_description='Deffered Earnig YTD';

--Updated script for PostingSequence under Amortization Interest Calculation ---------
update ASSOCIATE_PRESENTER_ATTRIBUTES set HIDDEN=0,HIDDEN_OVERRIDEN=0,EDITABLE=1,EDITABLE_OVERRIDEN=0 where ASSOCIATE_DEFINITION_ID in (select ASSOCIATE_DEFINITION_ID from associate_definition where ENTITY_TYPE_DEFINITION_ID in (select ENTITY_TYPE_DEFINITION_ID from entity_type_definition where type_name like 'AmortizedInterestCalculation'));


--UPDATED SCRIPT FOR RATE ADJUSTMENT ROUNDING FACTOR IN VARIABLE LOAN INTEREST TYPE AS EDITABLE---
update PROPERTY_PRESENTER_ATTRIBUTES set EDITABLE=1 where PROPERTY_DEFINITION_ID in (select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where PROPERTY_DEFINITION_ID in (select PROPERTY_DEFINITION_ID from PROPERTY_DEFINITION where property_name like 'RoundingFactor'));

------To add new column to table AMORTIZATION_SCHEDULE to store description of transaction type like Regular Payment, Curtailment and Payoff 
ALTER TABLE AMORTIZATION_SCHEDULE ADD DESCRIPTION VARCHAR(20);

--UPDATED SCRIPT FOR COLLECTION OFFICER IS MANDATORY--
update associate_definition set mandatory=1 where associate_name like 'CollectionOfficer';

--UPDATED SCRIPT FOR HIDING THE DESCRPTION FOR FEES AND COST PROPERTY DESCRIPTION FIELD
update property_definition set description_field='0' where entity_type_definition_id in(select entity_type_definition_id from entity_type_definition where type_name like 'AmountEntry');
