-------To store tickler types-------
CREATE TABLE TICKLER_TYPES 
   (TICKLER_TYPES_ID NUMBER(15,5) NOT NULL ENABLE, 
	DESCRIPTION NVARCHAR2(200), 
	TICKLER_TYPE NVARCHAR2(50), 
	 CONSTRAINT TICKLER_TYPES_PK PRIMARY KEY (TICKLER_TYPES_ID));
         
-------To store tickler item details-------
CREATE TABLE TICKLER_DETAILS 
(TICKLER_DETAILS_ID 	NUMBER(15,5)  NOT NULL ENABLE, 
TICKLER_FOR	NVARCHAR2(20),
ACCOUNT_NUMBER	VARCHAR2(30),
CUSTOMER_ID	VARCHAR2(30),
CUSTOMER_NAME VARCHAR2(100),
TICKLER_TYPES_ID 	NVARCHAR2(50),
DATE_FIRST	DATE,
DATE_NEXT	DATE,
SCHEDULED_CRITERIA	NVARCHAR2(200),
FREQUENCY	NVARCHAR2(20),
EXPIRATION_DATE	DATE,
DATE_FINAL	DATE,
REMINDER_TYPE	NVARCHAR2(50),
MESSAGE	NVARCHAR2(700),
EMAIL_ID	NVARCHAR2(50),
CONTENT_TEMPLATE_FILE_PATH	NVARCHAR2(200),
ASSIGNED_TO	NVARCHAR2(200),
STATUS	NVARCHAR2(50),
CLOSED_DATE	DATE,
CLOSED_BY	NVARCHAR2(50),
CLOSED_COMMENTS	NVARCHAR2(700),
CREATED_ON DATE DEFAULT SYSDATE,
CONSTRAINT TICKLER_DETAILS_PK PRIMARY KEY (TICKLER_DETAILS_ID));
  
-------To store tickler phone call details-------
CREATE TABLE TICKLER_CALL_DETAILS
	(TICKLER_CALL_DETAILS_ID NUMBER(15,5) NOT NULL ENABLE,    
    TICKLER_DETAILS_ID 	NUMBER(15,5),
    PHONE_NUMBER	NUMBER(15,5),
    DATE_OF_CALL	DATE,
    CALL_STATUS	NVARCHAR2(30),
    START_TIME	VARCHAR2(30),
    END_TIME	VARCHAR2(30),
    CALL_COMMENTS	NVARCHAR2(700), 
	 CONSTRAINT TICKLER_CALL_DETAILS_PK PRIMARY KEY(TICKLER_CALL_DETAILS_ID));

-------To create sequence for tickler types-------	 
CREATE SEQUENCE TICKLER_TYPES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
-------To create sequence for tickler item details-------	 
CREATE SEQUENCE TICKLER_DETAILS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
-------To create sequence for tickler phone call details-------	 
CREATE SEQUENCE TICKLER_CALL_DETAILS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;  