--Loan_Maintenance_log

ALTER TABLE LOAN_MAINTENANCE_LOG
    DROP CONSTRAINT LML_ACCID_FK;


ALTER TABLE LOAN_MAINTENANCE_LOG
    ADD ( CONSTRAINT LML_ACCID_FK
	FOREIGN KEY(ACCOUNT_ID)
	REFERENCES LOAN(ACCOUNT_ID)
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

--Billing Bucket
	
ALTER TABLE BILLING_BUCKET
    DROP CONSTRAINT BB_ACCID_FK;

ALTER TABLE BILLING_BUCKET
    ADD ( CONSTRAINT BB_ACCID_FK
	FOREIGN KEY(ACCOUNT_ID)
	REFERENCES LOAN(ACCOUNT_ID)
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
	

update entry_type set debit_or_credit =1  where unique_id in ('1901','1902','1903','1904','1905','1906','1907','1908','1909');