CREATE OR REPLACE VIEW "CHANNEL_EXTRACT_VW" ( "ID", "PARTICIPANT_ID", "CUSTOMER_TYPE", "CUST_ID_NO", "MEMBER_NO", "EXPIRATION_DATE", 
"NO_OF_ACCOUNTS", "DEFAULT_ACCOUNT_TYPE", "DEFAULT_ACCOUNT_QUALIFIER", "ACCOUNT_TYPE", "ACCOUNT_QUALIFIER", "ACCOUNT_NUMBER", 
"NO_OF_PLASTICS", "REISSUE_VALUE", "SPECIAL_HANDLING_INDICATOR", "BLOCKED_CARD_INDICATOR", "NEW_CORE_BRANCH_ID", "PIN_INDICATOR", "PIN_BLOCK", "NO_OF_CHECKS", 
"EMP_SECURITY_LEVEL", "FEE_GROUP_NAME", "LIMIT_GROUP_NAME", "CH_RESTRICT_TRANS_INDICATOR", "CARD_ACTIVATION_INDICATOR", "PRIOR_EXPIRE_DATE", 
"CAVV_CARD_OPTION", "ENTRY_MODE_RESTRICT", "CUST_LNAME", "CUST_FNAME", "CUST_MIDDLE_INTIAL", "CUST_LNAME2", "CUST_FNAME2", 
"CUST_MIDDLE_INTIAL2", "NO_OF_PLASTICS_TO_ISSUE", "CUST_ADDRESS_LINE1", "CUST_ADDRESS_LINE2", "CUST_CITY", "CUST_STATE", "CUST_ZIP", 
"COUNTRY_CODE", "CUST_DAYTIME_PHONE", "CUST_EVENING_PHONE","EMBOSS_NAME", "CUST_REMARKS","CUST_ACCOUNT_DESC", "SSN", "MOTHER_MAIDEN_NAME",
 "DOB", "VRU_PASSWORD", "DRIVERS_LICENSE_NO", "SECOND_EMBOSS_LINE", "CREATION_DATE", "INSTITUTION_ID" )
AS 
SELECT DISTINCT
    isoS.SUBCRIPTION_ID ID,
    to_char('510659') PARTICIPANT_ID,
    IST.NAME CUSTOMER_TYPE,
    ISOS.SUBSCRIPTION_NUMBER CARD_NO,
    to_char('0000') MEMBER_NO,
    ISOS.EXPIRATION_DATE EXPIRATION_DATE,
    to_number(1) NO_OF_ACCOUNTS,
    to_number(001) DEFAULT_ACCOUNT_TYPE,
    to_number(001) DEFAULT_ACCOUNT_QUALIFIER,
    decode(DAV.ACCOUNT_TYPE_ID,'10','01','02') ACCOUNT_TYPE,
    to_number(001) ACCOUNT_QUALIFIER,
    ISOs.PRIMARY_ACCOUNT_NUMBER,
    to_number(01) NO_OF_PLASTICS,
    ISOS.REISSUE_TERM REISSUE_VALUE,
    '' SPECIAL_HANDLING_INDICATOR,
    'N' BLOCKED_CARD_INDICATOR,
    B.NEW_CORE_BRANCH_ID,
    to_number(0) PIN_INDICATOR,
    '06' PIN_BLOCK,
    to_number(00) NO_OF_CHECKS,
    to_number(0) EMP_SECURITY_LEVEL,
    '' FEE_GROUP_NAME,
    LG.NAME LIMIT_GROUP_NAME,
    '' CH_RESTRICT_TRANS_INDICATOR,
    ISOs.STATUS CARD_ACTIVATION_INDICATOR,
    ISOs.PRIOR_EXPIRATION_DATE PRIOR_EXPIRE_DATE,
    '' CAVV_CARD_OPTION,
    '' ENTRY_MODE_RESTRICT,
    P.LAST_NAME CUST_LNAME,
    P.FIRST_NAME CUST_FNAME,
    substr(P.MIDDLE_NAME, 1, 1) CUST_MIDDLE_INTIAL,
    '' CUST_LNAME2,
    '' CUST_FNAME2,
    '' CUST_MIDDLE_INTIAL2,
    to_number(0) NO_OF_PLASTICS_TO_ISSUE,
    ga.LINE_1 CUST_ADDRESS_LINE1,
    ga.LINE_2 CUST_ADDRESS_LINE2,
    ga.CITY CUST_CITY,
    ga.STATE CUST_STATE,
    ga.ZIP_1||' '||ga.ZIP_2 CUST_ZIP,
    decode(ga.COUNTRY,'US', '840', '000' ) COUNTRY_CODE,
	CASE 
		WHEN  hta.phone IS NOT NULL AND 
		cta.phone IS NOT NULL 
		THEN hta.phone  
		ELSE wta.phone  
    END AS CUST_DAYTIME_PHONE,
	CASE 
		WHEN cta.PHONE  IS NOT NULL 
		THEN cta.PHONE  
		ELSE hta.phone  
	END AS CUST_EVENING_PHONE,
            
    Dbc.EMBOSS_LINE1 EMBOSS_NAME,
    '' CUST_REMARKS,
    '' CUST_ACCOUNT_DESC,
    ssn_tin.PARTY_REGISTERD_ID SSN_TIN,
    P.MOTHERS_MAIDEN_NAME MOTHER_MAIDEN_NAME,
    P.DATE_OF_BIRTH DOB,
    '' VRU_PASSWORD,
    dl.PARTY_REGISTERD_ID DRIVERS_LICENSE_NO,
    Dbc.EMBOSS_LINE2 SECOND_EMBOSS_LINE,
    ISOs.STATUS_TIME CREATION_DATE,
    isos.BANK_ID INSTITUTION_ID  
FROM
    PARTY_ACCOUNT_ROLE_VW parvw,   
	party_institution_association pia,   
	account_owner ao,   
	deposit_Account_vw dav,   
	person p,   
	organization org,   
	PARTY_REGISTERED_IDS prid,
	branch b,   
	(	SELECT 
			* 
			FROM 
				PARTY_ADDRESS  
			WHERE 
				ADDRESS_use IN ('OTHERS',
				'HOME_PHONE',
				'WORK_PHONE',
				'CELL_PHONE',
				'WEB')
	)
	PA,   
	geographic_address ga,   
	TELECOM_ADDRESS WTA,   
	TELECOM_ADDRESS HTA,
	TELECOM_ADDRESS CTA,   
	WEB_ADDRESS WA ,   
	(  SELECT 
			address_id,
			PARTY_ID ,
			UNIQUE_PARTY_ADDRESS_ID  
        FROM 
			PARTY_ADDRESS   
        WHERE 
			ADDRESS_USE = 'OTHERS'   
	) 
	OTHERS,
	(  	SELECT 
			MAX(address_id) address_id,
			PARTY_ID   
        FROM 
			PARTY_ADDRESS   
        WHERE 
			ADDRESS_USE = 'WORK_PHONE'   
        GROUP BY 
			party_id   
	)   
	TPAW ,
	( 	SELECT 
			MAX(address_id) address_id,
			PARTY_ID   
        FROM 
			PARTY_ADDRESS   
        WHERE 
			ADDRESS_USE = 'HOME_PHONE'   
        GROUP BY 
			party_id   
	)   
	TPAH ,  
	( 	SELECT 
			MAX(address_id) address_id,
			PARTY_ID   
        FROM 
			PARTY_ADDRESS   
        WHERE 
			ADDRESS_USE = 'CELL_PHONE'   
        GROUP BY 
			party_id   
	)   
	TPCP ,
	(	SELECT 
			MAX(address_id) address_id,
			PARTY_ID   
        FROM 
			PARTY_ADDRESS   
        WHERE 
			ADDRESS_USE = 'WEB'   
        GROUP BY 
			party_id   
	)   
	WPA,   
	(	SELECT 
			* 
		FROM 
			PARTY_REGISTERED_IDS 
		WHERE 
			TYPE IN ('SSN',
			'TIN')
	) 
	ssn_tin,   
	(	SELECT 
			* 
		FROM 
			PARTY_REGISTERED_IDS 
		WHERE 
			TYPE  LIKE 'Driver%'
	) 
	dl,   
	debitcard_SUBSCRIPTION_TYPE IST,   
	debitcard_SUBSCRIPTION ISOS,   
	LIMIT_GROUP LG,   
	SUBSCRIBER sub,   
	debitcard_USER dbc,
	ACCOUNT_STATEMENT_GENERATOR asg,
	ACCOUNT_STATEMENT_ADDRESS asa
WHERE
	isos.LIMIT_GROUP_ID=lg.LIMIT_GROUP_ID 
  AND isos.TYPE_ID=ist.TYPE_ID  
  AND isos.SUBSCRIBER_ID=sub.SUBSCRIBER_ID   
  AND isos.PRIMARY_USER_ID=dbc.USER_ID  
  AND dav.account_no=isos.PRIMARY_ACCOUNT_NUMBER	
  AND parvw.ACCOUNT_ID =dav.ACCOUNT_ID(+)
  AND asg.account_id=dav.account_id	
  AND asg.unique_id=asa.unique_id	
  AND asa.UNIQUE_PARTY_ADDRESS_ID=pa.UNIQUE_PARTY_ADDRESS_ID
	AND parvw.party_id=dbc.core_party_id   
	AND PARVW.UNIQUE_PARTY_ROLE_ID =AO.UNIQUE_PARTY_ROLE_ID   
	AND PARVW.PARTY_ID = PRID.PARTY_ID(+)   
	AND PARVW.PARTY_ID=P.PARTY_ID(+)   
	AND PARVW.PARTY_ID=org.PARTY_ID(+)   
	AND parvw.unique_association_id=pia.unique_association_id   
	AND pia.party_id=parvw.party_id   
	AND pa.UNIQUE_PARTY_ADDRESS_ID=OTHERS.UNIQUE_PARTY_ADDRESS_ID(+)
	AND OTHERS.address_id=ga.address_id(+)
	AND PARVW.PARTY_ID = TPAW.PARTY_ID (+)   
	AND PARVW.PARTY_ID = TPAH.PARTY_ID (+)  
	AND PARVW.PARTY_ID = TPCP.PARTY_ID (+)  
	AND TPAW.ADDRESS_ID = WTA.ADDRESS_ID(+)   
	AND TPAH.ADDRESS_ID = HTA.ADDRESS_ID(+)  
	AND TPCP.ADDRESS_ID = CTA.ADDRESS_ID(+)    
	AND parvw.party_id=WPA.PARTY_ID (+)   
	AND wpa.ADDRESS_ID=WA.ADDRESS_ID(+)   
	AND PARVW.PARTY_ID = SSN_TIN.PARTY_ID(+)     	
	AND PARVW.PARTY_ID = dl.PARTY_ID(+)
	AND DAV.assigned_branch=b.unique_id 
	ORDER BY ISOS.SUBCRIPTION_ID DESC;
