
CREATE TABLE CMF_LOG ( 
	ACTIVITY_UNIQUE_ID	NUMBER(10,0) NOT NULL,
	ACTIVITY_TYPE     	VARCHAR2(3) NULL,
	TIME_STAMP        	DATE NULL,
	INSTITUTION_ID    	VARCHAR2(3) NULL,
	ACCOUNT_TYPE      	VARCHAR2(3) NULL,
	ACCOUNT_NUMBER    	VARCHAR2(20) NULL,
	CARD_NUMBER       	VARCHAR2(20) NULL,
	ACTIVITY_PERFORMED	VARCHAR2(100) NULL 
	);


CREATE TABLE ACTIVITY_CATEGORY_MAPPING ( 
	ACTIVITY_TYPE    	VARCHAR2(3) NULL,
	ACTIVITY_DESC    	VARCHAR2(40) NULL,
	ACTIVITY_CATEGORY	VARCHAR2(10) NULL 
	);


CREATE SEQUENCE CMF_ACTIIVITY_ID_SEQ START WITH 60356484 INCREMENT BY 1;
