CREATE INDEX IND_PARTY_FNAME ON PERSON(FIRST_NAME);
CREATE INDEX IND_PARTY_LNAME ON PERSON(LAST_NAME);
CREATE INDEX IND_PARTY_MNAME ON PERSON(MIDDLE_NAME);

CREATE TABLE PARV_VW AS SELECT * FROM PARTY_ACCOUNT_ROLE_VW ;

CREATE INDEX TEMp_IND ON PARV_VW(ACCOUNT_NO);

