
CREATE OR REPLACE VIEW ORDERED_CARDS_REPORT_VW ( ID, PARTICIPANT_ID, CUSTOMER_TYPE, CUST_ID_NO, MEMBER_NO, EXPIRATION_DATE, NO_OF_ACCOUNTS, DEFAULT_ACCOUNT_TYPE, DEFAULT_ACCOUNT_QUALIFIER, ACCOUNT_TYPE, ACCOUNT_QUALIFIER, ACCOUNT_NUMBER, NO_OF_PLASTICS, REISSUE_VALUE, SPECIAL_HANDLING_INDICATOR, BLOCKED_CARD_INDICATOR, PIN_INDICATOR, PIN_BLOCK, NO_OF_CHECKS, EMP_SECURITY_LEVEL, FEE_GROUP_NAME, LIMIT_GROUP_NAME, CH_RESTRICT_TRANS_INDICATOR, CARD_ACTIVATION_INDICATOR, PRIOR_EXPIRE_DATE, CAVV_CARD_OPTION, ENTRY_MODE_RESTRICT, CUST_LNAME, CUST_FNAME, CUST_MIDDLE_INTIAL, CUST_LNAME2, CUST_FNAME2, CUST_MIDDLE_INTIAL2, NO_OF_PLASTICS_TO_ISSUE, CUST_ADDRESS_LINE1, CUST_ADDRESS_LINE2, CUST_CITY, CUST_STATE, CUST_ZIP, COUNTRY_CODE, CUST_DAYTIME_PHONE, CUST_EVENING_PHONE, EMBOSS_NAME, CUST_REMARKS, CUST_ACCOUNT_DESC, SSN, MOTHER_MAIDEN_NAME, DOB, VRU_PASSWORD, DRIVERS_LICENSE_NO, DRIVERS_LICENSE_EXP_DATE, SECOND_EMBOSS_LINE, ORDERED_TIME, ORDERED_BY, ORDERED_FROM, REJECTED_TIME, REJECT_REMARKS, REJECTED_BY_BRANCH, INSTITUTION_ID )
as
select isos.SUBCRIPTION_ID ID,
       to_char('510659') PARTICIPANT_ID,IST.NAME CUSTOMER_TYPE,ISOS.SUBSCRIPTION_NUMBER CUST_ID_NO,
to_char('0000') MEMBER_NO, ISOS.EXPIRATION_DATE EXPIRATION_DATE, to_number(1) NO_OF_ACCOUNTS , to_number(001) DEFAULT_ACCOUNT_TYPE,
to_number(001) DEFAULT_ACCOUNT_QUALIFIER, ATL.ACCOUNT_TYPE_ID ACCOUNT_TYPE, to_number(001 ) ACCOUNT_QUALIFIER, ISOS.PRIMARY_ACCOUNT_NUMBER ACCOUNT_NUMBER
,to_number(01) NO_OF_PLASTICS, ISOS.REISSUE_TERM REISSUE_VALUE, '' SPECIAL_HANDLING_INDICATOR, 'N' BLOCKED_CARD_INDICATOR
,to_number(0) PIN_INDICATOR, '06' PIN_BLOCK, to_number(00) NO_OF_CHECKS, to_number(0) EMP_SECURITY_LEVEL,
'' FEE_GROUP_NAME, LG.NAME LIMIT_GROUP_NAME, '' CH_RESTRICT_TRANS_INDICATOR, ISOS.STATUS CARD_ACTIVATION_INDICATOR,
ISOS.PRIOR_EXPIRATION_DATE PRIOR_EXPIRE_DATE, '' CAVV_CARD_OPTION, '' ENTRY_MODE_RESTRICT,
P.LAST_NAME CUST_LNAME, decode(P.FIRST_NAME,null,o.BUSINESS_NAME,p.FIRST_NAME) CUST_FNAME,
substr(P.MIDDLE_NAME, 1, 1) CUST_MIDDLE_INTIAL, '' CUST_LNAME2, '' CUST_FNAME2, '' CUST_MIDDLE_INTIAL2, to_number(0) NO_OF_PLASTICS_TO_ISSUE
,ga.LINE_1 CUST_ADDRESS_LINE1, ga.LINE_2 CUST_ADDRESS_LINE2, ga.CITY CUST_CITY, ga.STATE CUST_STATE,ga.ZIP_1||' '||ga.ZIP_2 CUST_ZIP,
ga.COUNTRY COUNTRY_CODE, TAwp.PHONE CUST_DAYTIME_PHONE, TAhp.PHONE CUST_EVENING_PHONE, DBC.EMBOSS_LINE1 EMBOSS_NAME,
'' CUST_REMARKS, '' CUST_ACCOUNT_DESC, ssn_tin.PARTY_REGISTERD_ID SSN, P. MOTHERS_MAIDEN_NAME MOTHER_MAIDEN_NAME, P.DATE_OF_BIRTH DOB,
 '' VRU_PASSWORD, DRID.PARTY_REGISTERD_ID DRIVERS_LICENSE_NO, DRID.EFFECTIVE_END_DATE DRIVERS_LICENSE_EXP_DATE,
DBC.EMBOSS_LINE2 SECOND_EMBOSS_LINE, ISOS.ORDERED_TIME, ISOS.ORDERED_BY, ISOS.ORDERED_FROM, ISOS.REJECTED_TIME, ISOS.REJECT_REMARKS,
ISOS.REJECTED_BY_BRANCH, BA.Institution_ID INSTITUTION_ID
FROM  ACCOUNT AC,
PARTY_ACCOUNT_ROLE_VW parv,
address ad,
party_address pa,
(select p.party_id,max(ta.ADDRESS_ID) ADDRESS_ID from party p,party_address pa,TELECOM_ADDRESS ta
  where p.party_id=pa.party_id
  and pa.address_id=ta.address_id
  and pa.ADDRESS_USE='WORK_PHONE'
  group by p.PARTY_ID ) ta,
(select p.party_id,max(ta.ADDRESS_ID) ADDRESS_ID from party p,party_address pa,TELECOM_ADDRESS ta
  where p.party_id=pa.party_id
  and pa.address_id=ta.address_id
  and pa.ADDRESS_USE='HOME_PHONE'
     group by p.PARTY_ID ) ta1,
ACCOUNT_STATEMENT_ADDRESS asa,
ACCOUNT_STATEMENT_GENERATOR asg,
ACCOUNT_OWNER ao,
        INSTITUTION BA,
        debitcard_SUBSCRIPTION_TYPE IST,
        debitcard_SUBSCRIPTION ISOS,
        LIMIT_GROUP LG,
        SUBSCRIBER sub,
        debitcard_USER dbc,
        ACCOUNT_TYPE_LOOKUP ATL,
        (SELECT * FROM PARTY_REGISTERED_IDS WHERE TYPE='Driver''s License') DRID,Party pr,Person p,Organization o,
  GEOGRAPHIC_ADDRESS ga,Telecom_address tawp,Telecom_address tahp,
(SELECT * FROM PARTY_REGISTERED_IDS WHERE TYPE in ('SSN','TIN')) ssn_tin

WHERE
        isos.LIMIT_GROUP_ID=lg.LIMIT_GROUP_ID and
isos.TYPE_ID=ist.TYPE_ID and
isos.SUBSCRIBER_ID=sub.SUBSCRIBER_ID and
isos.PRIMARY_USER_ID=dbc.USER_ID and
isos.BANK_ID=ba.INSTITUTION_ID and
isos.PRIMARY_ACCOUNT_ID=ac.ACCOUNT_ID(+) and
ac.CONTRACT_TYPE_ID=atl.ACCOUNT_TYPE_ID(+) and
parv.ACCOUNT_ID=ac.ACCOUNT_ID and
parv.PARTY_ID=pr.PARTY_ID and
parv.UNIQUE_PARTY_ROLE_ID=ao.UNIQUE_PARTY_ROLE_ID and
ac.ACCOUNT_ID=asg.ACCOUNT_ID and
asg.UNIQUE_ID=asa.UNIQUE_ID and
asa.UNIQUE_PARTY_ADDRESS_ID=pa.UNIQUE_PARTY_ADDRESS_ID and
pa.ADDRESS_ID=ad.ADDRESS_ID and
ad.ADDRESS_ID=ga.ADDRESS_ID and
pa.party_id=ta.party_id(+) and
pa.party_id=ta1.party_id(+) and
ta.address_id=tawp.address_id(+) and
ta1.address_id=tahp.address_id(+) and
pr.party_id=ssn_tin.party_id and
pr.party_id=drid.party_id(+) and
 pr.party_id=p.party_id(+) and
 pr.party_id=o.party_id(+) and
parv.RESPONSIBILITY_TYPE=9  order by isos.SUBCRIPTION_ID;
