INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(23, '023', 0, 223, 38, 'Escrow Debit Adjustment', '0');

INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID, CORESOFT_EVENT_CODE, EVENT_GROUP, REVERSAL_EVENT_TYPE_ID, POSTING_ORDER, DESCRIPTION, DEBIT_OR_CREDIT)
  VALUES(223, '223', 1, 23, 6, 'Escrow Debit Adjustment Reversal', '1');
 

 
 
	
	
