INSERT INTO CUSTOMER_TYPE_LOOKUP(CUSTOMER_TYPE_ID, CUSTOMER_TYPE)
  VALUES('100', 'Personal');
INSERT INTO CUSTOMER_TYPE_LOOKUP(CUSTOMER_TYPE_ID, CUSTOMER_TYPE)
  VALUES('101', 'Business');
INSERT INTO CUSTOMER_TYPE_LOOKUP(CUSTOMER_TYPE_ID, CUSTOMER_TYPE)
  VALUES('102', 'Government');
INSERT INTO CUSTOMER_TYPE_LOOKUP(CUSTOMER_TYPE_ID, CUSTOMER_TYPE)
  VALUES('103', 'Non profit');
INSERT INTO CUSTOMER_TYPE_LOOKUP(CUSTOMER_TYPE_ID, CUSTOMER_TYPE)
  VALUES('104', 'Others');
  
--INSERT INTO RELATIONSHIP_OFFICER(ID, OFFICER_CODE, OFFICER_ROLE, DESCRIPTION)
--  VALUES(1, 'BM', 'Manager', 'BTM-Brandon'); 
--  
----Commented already these scripts in product 
--
----INSERT INTO PARTY_ROLE_TYPE(ROLE_TYPE_ID, ROLE_TYPE_NAME)
----  VALUES('1', 'Primary Owner');
----INSERT INTO PARTY_ROLE_TYPE(ROLE_TYPE_ID, ROLE_TYPE_NAME)
----  VALUES('10', 'Interested Party');
----INSERT INTO PARTY_ROLE_TYPE(ROLE_TYPE_ID, ROLE_TYPE_NAME)
----  VALUES('11', 'Instrument Holder');
----INSERT INTO PARTY_ROLE_TYPE(ROLE_TYPE_ID, ROLE_TYPE_NAME)
----  VALUES('12', 'Possible Instrument Holder');
----INSERT INTO PARTY_ROLE_TYPE(ROLE_TYPE_ID, ROLE_TYPE_NAME)
----  VALUES('16', 'Recipient');
----INSERT INTO PARTY_ROLE_TYPE(ROLE_TYPE_ID, ROLE_TYPE_NAME)
----  VALUES('6', 'POSSIBLE OWNER');
----INSERT INTO PARTY_ROLE_TYPE(ROLE_TYPE_ID, ROLE_TYPE_NAME)
----  VALUES('7', 'Possible Beneficiary');
----INSERT INTO PARTY_ROLE_TYPE(ROLE_TYPE_ID, ROLE_TYPE_NAME)
----  VALUES('8', 'Account Owner');
----INSERT INTO PARTY_ROLE_TYPE(ROLE_TYPE_ID, ROLE_TYPE_NAME)
----  VALUES('9', 'Beneficiary'); 
--  
-- 
----INSERT INTO ACCOUNT_TYPE_LOOKUP(ACCOUNT_TYPE_ID, ACCOUNT_TYPE)
----  VALUES('10', 'Checking');
----INSERT INTO ACCOUNT_TYPE_LOOKUP(ACCOUNT_TYPE_ID, ACCOUNT_TYPE)
----  VALUES('110', 'Real Estate Loan');
----INSERT INTO ACCOUNT_TYPE_LOOKUP(ACCOUNT_TYPE_ID, ACCOUNT_TYPE)
----  VALUES('207', 'Rule Of 78');
----INSERT INTO ACCOUNT_TYPE_LOOKUP(ACCOUNT_TYPE_ID, ACCOUNT_TYPE)
----  VALUES('208', 'Installment');
----INSERT INTO ACCOUNT_TYPE_LOOKUP(ACCOUNT_TYPE_ID, ACCOUNT_TYPE)
----  VALUES('21', 'Savings');
----INSERT INTO ACCOUNT_TYPE_LOOKUP(ACCOUNT_TYPE_ID, ACCOUNT_TYPE)
----  VALUES('22', 'CD');
 
insert into ACCOUNT_TYPE_LOOKUP (ACCOUNT_TYPE,ACCOUNT_TYPE_ID) values ('General Ledger',90);