--CORESOFT EVENT TYPES

--END DAY
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (99,'099', 2, 299,null);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (299,'299',2,99,null);
				
--INITIAL FUND
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (1,'001',0, 201,1);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (201,'201',1,1,22);
				
-- REGULAR PAYMENT
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (110,'110',0, 310,23);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (310,'310',1,110,9);
				
-- PAYOFF PAYMENT
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (15,'015',0, 215,42);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (215,'215',1,15,3);				

-- LATE CHARGE PAYMENT				
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (16,'016',0, 216,26);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (216,'216',1,16,19);

-- CURTAILEMENT	TRUE		
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (121,'121',0, 321,25);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (321,'321',1,121,20);	

-- CURTAILEMENT	NON TRUE		
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (120,'120',0, 320,25);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (320,'320',1,120,20);
				

-- INTERESTPAYMENT		
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (13,'013',0, 213,30);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (213,'213',1,13,15);	
				
				
-- ESCROW PAYMENT				
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (14,'014',0, 214,27);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (214,'214',1,14,18);
				
--LIFE AH PAYMENT
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (17,'017',0, 217,28);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (217,'217',1,17,16);
				

--DEBIT MEMO PRINCIPAL
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (21,'021',0, 221,36);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (221,'221',1,21,8);			
				
--DEBIT MEMO LATE CHARGE
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (22,'022',0, 222,39);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (222,'222',1,22,5);					

--DEBIT MEMO OTHER FEE
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (24,'024',0, 224,37);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (224,'224',1,24,7);		
				
--CREDIT MEMO PRINCIPAL
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (31,'031',0, 231,32);
INSERT INTO LOAN_EVENT_TYPE(EVENT_TYPE_ID,CORESOFT_EVENT_CODE,EVENT_GROUP,REVERSAL_EVENT_TYPE_ID,POSTING_ORDER)
				VALUES (231,'231',1,31,13);	
