create index ASCII_IDX_1 on maintenance_log(substr(trim("CHANGE_FROM"),1,1));

create index ASCII_IDX_2 on maintenance_log(substr(trim("CHANGE_TO"),1,1));

create index MAINT_LOG_FC_ENTRYDT on maintenance_log(FIELD_CHANGED, ENTRY_DATE);

create index PAR_ACC_ROL_UNI_ACC_IDX on PARTY_ACCOUNT_ROLE(ACCOUNT_ID, UNIQUE_PARTY_ROLE_ID);

ALTER TABLE PARTY_ADDRESS
    ADD ( CONSTRAINT PARTYADDR_ADDRID_FK
	FOREIGN KEY(ADDRESS_ID)
	REFERENCES ADDRESS(ADDRESS_ID)
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
;

create index PA_QUALIFIERS_IDX on PARTY_ADDRESS(QUALIFIERS);

alter table PARTY_ASSOC_MAINT_LOG modify(BRANCH_ID VARCHAR2(30));

create index PIA_CYCLE_CODE_IDX on PARTY_INSTITUTION_ASSOCIATION(CYCLE_CODE); 

create index PIA_IDX1 on PARTY_INSTITUTION_ASSOCIATION(SUBSTR("INSTITUTION_ASSOCIATION_ID",1,10), INSTITUTION_ID);

create index PIA_INST_ID_INSTASSIS_IDX on PARTY_INSTITUTION_ASSOCIATION(INSTITUTION_ID, INSTITUTION_ASSOCIATION_ID);

create index PARTY_REG_ID_NUMID_IDX on PARTY_REGISTERED_IDS(TO_NUMBER("ID"));  

create index PIA_PRID_IDX on PARTY_REGISTERED_IDS(PARTY_REGISTERD_ID);

create index PIA_TYPE_IDX on PARTY_REGISTERED_IDS(TYPE);

create index PRI_LOWER_PRID_IDX on PARTY_REGISTERED_IDS(LOWER("PARTY_REGISTERD_ID"));

create index PER_FN_INDEX on PERSON(LOWER("FIRST_NAME"));

create index PER_LN_INDEX on PERSON(LOWER("LAST_NAME"));

create index IND_PROPERTY on PROPERTY(ENTITY_TYPE_INSTANCE_ID);

create index IND_PROP_DEF on PROPERTY_DEFINITION(ENTITY_TYPE_DEFINITION_ID);

alter table TRANSACTION_POSTTODAY MODIFY(ACCOUNT_ID VARCHAR2(30) , ACCOUNT_NUMBER VARCHAR2(30) , ACCOUNT_TYPE_ID VARCHAR2(30) , COMPANY_CUST_NUMBER VARCHAR2(30) , COMPANY_DESCRIPTION VARCHAR2(200) , COMPANY_ID VARCHAR2(30) , COMPANY_NAME VARCHAR2(100) ,INSTITUTION_ID VARCHAR2(30));

create index TRAN_POSTODAY_IID_RID_PS_IDX on TRANSACTION_POSTTODAY(INSTITUTION_ID, REASON_ID, POST_STATUS);

alter table PARTY ADD(DATE_LAST_MAINTAINED DATE);
