INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(332, 'Code', 'java.lang.String:05');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(332, 'Description', 'java.lang.String:Interest');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(333, 'Code', 'java.lang.String:02');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(333, 'Description', 'java.lang.String:Late Charge');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(334, 'Code', 'java.lang.String:03');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(334, 'Description', 'java.lang.String:Escrow');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(335, 'Code', 'java.lang.String:04');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(335, 'Description', 'java.lang.String:Other Fee');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(336, 'Description', 'java.lang.String:Principal');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(336, 'Code', 'java.lang.String:01');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(6700, 'Description', 'java.lang.String:Credit Life');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(6700, 'Code', 'java.lang.String:06');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(8443, 'Code', 'java.lang.String:09');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(8443, 'Description', 'java.lang.String:Unapplied Fund');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(8444, 'Code', 'java.lang.String:10');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(8444, 'Description', 'java.lang.String:Origination Fee');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50389, 'Description', 'java.lang.String:Accts Receivable & Inventory');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50389, 'Code', 'java.lang.Integer:9');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50390, 'Description', 'java.lang.String:Equipment');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50390, 'Code', 'java.lang.Integer:10');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50391, 'Code', 'java.lang.Integer:11');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50391, 'Description', 'java.lang.String:Brokerage Account');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50392, 'Code', 'java.lang.Integer:12');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50392, 'Description', 'java.lang.String:GSA  on Business Assets');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50611, 'Description', 'java.lang.String:Real Estate Property');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50611, 'Code', 'java.lang.Integer:1');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50612, 'Description', 'java.lang.String:Personal Property / Business Assets');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50612, 'Code', 'java.lang.Integer:2');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50613, 'Code', 'java.lang.Integer:3');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50613, 'Description', 'java.lang.String:Title Liens');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50614, 'Code', 'java.lang.Integer:4');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50614, 'Description', 'java.lang.String:Deposit Collateral');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50615, 'Description', 'java.lang.String:Stock Collateral');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50615, 'Code', 'java.lang.Integer:5');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50616, 'Code', 'java.lang.Integer:6');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50616, 'Description', 'java.lang.String:Life Insurance or Annuity');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50617, 'Code', 'java.lang.Integer:7');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50617, 'Description', 'java.lang.String:Other Collateral');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50618, 'Code', 'java.lang.Integer:8');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50618, 'Description', 'java.lang.String:Unsecured');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50801, 'Description', 'java.lang.String:No Credit Line Fee');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50801, 'Code', 'java.lang.String:0');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50802, 'Description', 'java.lang.String:No Prepayment penalty');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(50802, 'Code', 'java.lang.String:00');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(1859590, 'Description', 'java.lang.String:Acc Health');
INSERT INTO PROPERTY(ENTITY_TYPE_INSTANCE_ID, PROPERTY_NAME, VALUE)
  VALUES(1859590, 'Code', 'java.lang.String:46');
