INSERT INTO ASSOCIATE_DEF_VALID_VALUES(ASSOCIATE_DEFINITION_ID, ENTITY_TYPE_INSTANCE_ID)
  VALUES(413, 50802);
INSERT INTO ASSOCIATE_DEF_VALID_VALUES(ASSOCIATE_DEFINITION_ID, ENTITY_TYPE_INSTANCE_ID)
  VALUES(6182, 50613);