alter table account add(constraint sys_c008030 foreign key(product_instance_uid) 
references appl_product(unique_id) );

create index ACCAPP_AACCNO on ACCOUNT_APPLICATION(ASSIGNED_ACCOUNT_NO);

create index ACC_SMT_ADRS_UID_IDX ON ACCOUNT_STATEMENT_ADDRESS(UNIQUE_ID);

create index APP_SUBDATE ON APPLICATION(SUBMISSION_DATE); 

ALTER TABLE APPLICATION_STMT_ADDRESS DROP CONSTRAINT APP_STMT_ADD_ASID_FK;

alter table APPLICATION_STMT_ADDRESS ADD ( CONSTRAINT APP_STMT_ADD_UPAID_FK
FOREIGN KEY(UNIQUE_PARTY_ADDRESS_ID) REFERENCES PARTY_ADDRESS(UNIQUE_PARTY_ADDRESS_ID));

create index IND_ASSOCIATE_DEF1 ON ASSOCIATE_DEFINITION(ENTITY_TYPE_DEFINITION_ID);

create index IND_ASSOCIATE_DEF2 ON ASSOCIATE_DEFINITION(ASSOCIATE_TYPE_DEFINITION_ID);

--alter table BILLING_BUCKET ADD LAST_MODIFIED_DATE DATE NULL;

alter table BILLING_BUCKET DROP CONSTRAINT BB_ACCID_FK;

ALTER TABLE BILLING_BUCKET
    ADD ( CONSTRAINT BB_ACCID_FK
	FOREIGN KEY(ACCOUNT_ID)
	REFERENCES LOAN_ACCOUNT(ACCOUNT_ID)
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
;


alter table GEOGRAPHIC_ADDRESS MODIFY LINE_2 VARCHAR2(250) ;

alter table install_log ADD (CONSTRAINT INTLOGPK PRIMARY KEY(COMPONENT_NAME,VERSION_NO,
SCRIPT_NAME));

alter table institution drop constraint IT_ITID_FK; 

alter table institution ADD (CONSTRAINT IT_ITID_FK FOREIGN KEY(INSTITUTION_TYPE_ID)
REFERENCES INSTITUTION_TYPE_LOOKUP(INSTITUTION_TYPE_ID) ON DELETE SET NULL
NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

alter table institution drop constraint INST_FRABA_ID_FK;

alter table institution ADD (CONSTRAINT INST_FRABA_ID_FK FOREIGN KEY(FRABA_ID)
REFERENCES FRABA(UNIQUE_ID) ON DELETE SET 
NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
