
-- scripts related to deposit core team

alter table  ACCOUNT_HISTORY_ITEM add ORG_TRANS_CODE VARCHAR2(50);

ALTER TABLE DEPOSIT_ACCOUNT ADD TAX_CODE VARCHAR2(50);

alter table deposit_account add AGG_BALANCE_YTD NUMBER(20,5);

ALTER TABLE DEPOSIT_ACCOUNT ADD DATE_LAST_EXTERNAL_ACTIVITY DATE;

ALTER TABLE DEPOSIT_ACCOUNT ADD STATE_TAX_WHELD_PTD NUMBER(20,5);

create table DEPOSIT_ACCOUNT_DAY_SUMMARY (

ACCOUNT_DAY  DATE,
ACCOUNT_ID	 VARCHAR2(30),
OPENING_BALANCE 			NUMBER(20,5) default 0,
OPENING_AVAILABLE_BALANCE 	NUMBER(20,5) default 0,
OPENING_CURRENT_BALANCE 	NUMBER(20,5) default 0,
OPENING_MINIMUM_BALANCE 	NUMBER(20,5) default 0,
OPENING_SERVICE_CHARGE  	NUMBER(20,5) default 0,
OPENING_ACCRUED_INTEREST 	NUMBER(20,5) default 0,
-- day digest
DEBIT_COUNT			NUMBER(10) default 0,
DEBIT_AMOUNT		NUMBER(20,5) default 0,
CREDIT_COUNT		NUMBER(10) default 0,
CREDIT_AMOUNT		NUMBER(20,5) default 0,
FED_TAX_WITHHELD	NUMBER(20,5) default 0,
ATM_USED_COUNT		NUMBER(10) default 0,
ATM_DEBIT_COUNT		NUMBER(10) default 0,
INTEREST_PAID	NUMBER(20,5) default 0,
ACH_DEBIT_COUNT		NUMBER(10) default 0,

LEDGER_BALANCE		NUMBER(20,5) default 0,
AVAILABLE_BALANCE 	NUMBER(20,5) default 0,
CURRENT_BALANCE 	NUMBER(20,5) default 0,
MINIMUM_BALANCE 	NUMBER(20,5) default 0,
SERVICE_CHARGE  	NUMBER(20,5) default 0,
ACCRUED_INTEREST_FOR_DAY 	NUMBER(20,5) default 0,
TRANSIT_ITEMS_COUNT NUMBER(10)  default 0,
CHECKS_COUNT NUMBER(10)  default 0,
MAINT_SERVICE_CHARGE NUMBER(20,5) default 0,
TIMES_OD NUMBER(10) default 0,
TIMES_NSF NUMBER(10) default 0,
NO_DAYS_OVERDRAWN NUMBER(10) default 0,
-- month digest
MTD_DEBIT_COUNT		NUMBER(10) default 0,
MTD_DEBIT_AMOUNT	NUMBER(20,5) default 0,
MTD_CREDIT_COUNT	NUMBER(10) default 0,
MTD_CREDIT_AMOUNT	NUMBER(20,5) default 0,
MTD_FED_TAX_WITHHELD	NUMBER(20,5) default 0,
MTD_ATM_USED_COUNT		NUMBER(10) default 0,
MTD_ATM_DEBIT_COUNT		NUMBER(10) default 0,
MTD_INTEREST_PAID	NUMBER(20,5) default 0,
MTD_ACH_DEBIT_COUNT		NUMBER(10) default 0,
MTD_AGR_LEDGER_BALANCE	NUMBER(20,5) default 0,
MTD_AGR_AVAILABLE_BALANCE 	NUMBER(20,5) default 0,
MTD_AGR_CURRENT_BALANCE 	NUMBER(20,5) default 0,
MTD_AGR_MINIMUM_BALANCE 	NUMBER(20,5) default 0,
MTD_AGR_SERVICE_CHARGE  	NUMBER(20,5) default 0,
MTD_AGR_ACCRUED_INTEREST 	NUMBER(20,5) default 0,
MTD_TRANSIT_ITEMS_COUNT NUMBER(10) default 0,
MTD_CHECKS_COUNT NUMBER(10) default 0,
MTD_MAINT_SERVICE_CHARGE NUMBER(20,5) default 0,
MTD_TIMES_OD NUMBER(10) default 0,
MTD_TIMES_NSF NUMBER(10) default 0,
MTD_NO_DAYS_OVERDRAWN NUMBER(10) default 0,
-- year digest
YTD_DEBIT_COUNT		NUMBER(10) default 0,
YTD_DEBIT_AMOUNT	NUMBER(20,5) default 0,
YTD_CREDIT_COUNT	NUMBER(10) default 0,
YTD_CREDIT_AMOUNT	NUMBER(20,5) default 0,
YTD_FED_TAX_WITHHELD	NUMBER(20,5) default 0,
YTD_ATM_USED_COUNT		NUMBER(10) default 0,
YTD_ATM_DEBIT_COUNT		NUMBER(10) default 0,
YTD_INTEREST_PAID	NUMBER(20,5) default 0,
YTD_ACH_DEBIT_COUNT		NUMBER(10) default 0,
YTD_AGR_LEDGER_BALANCE	NUMBER(20,5) default 0,
YTD_AGR_AVAILABLE_BALANCE 	NUMBER(20,5) default 0,
YTD_AGR_CURRENT_BALANCE 	NUMBER(20,5) default 0,
YTD_AGR_MINIMUM_BALANCE 	NUMBER(20,5) default 0,
YTD_AGR_SERVICE_CHARGE  	NUMBER(20,5) default 0,
YTD_AGR_ACCRUED_INTEREST 	NUMBER(20,5) default 0,
YTD_TRANSIT_ITEMS_COUNT NUMBER(10) default 0,
YTD_CHECKS_COUNT NUMBER(10) default 0,
YTD_MAINT_SERVICE_CHARGE NUMBER(20,5) default 0,
YTD_TIMES_OD NUMBER(10) default 0,
YTD_TIMES_NSF NUMBER(10) default 0,
YTD_NO_DAYS_OVERDRAWN NUMBER(10) default 0
);

ALTER TABLE DEPOSIT_ACCOUNT_DAY_SUMMARY ADD(CONSTRAINT DEP_ACC_DAY_SUMMARY_PK PRIMARY KEY (ACCOUNT_DAY, ACCOUNT_ID));
ALTER TABLE DEPOSIT_ACCOUNT_DAY_SUMMARY ADD(CONSTRAINT DEP_ACC_DAY_SUM_ACC_ID_FK FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID));

create index dep_day_sum_aid_idx on deposit_account_day_summary(to_number(account_id)) nologging;

alter table ACCOUNT_HISTORY_ITEM modify(description VARCHAR2(300) , trace number(16,0));
create index AHI_acc_id_num_idx on account_history_item(to_number(account_id)) nologging;

-- from loans db project
ALTER TABLE PARTY_ADDRESS ADD(QUALIFIERS VARCHAR2(250));
ALTER TABLE ACCOUNT ADD(STATUS VARCHAR2(20) , CONTRACT_ID NUMBER(15));
ALTER TABLE POSSIBLE_OWNER ADD TARGET_PARTY_ROLE_TYPE_ID NUMBER(20,0);
ALTER TABLE GEOGRAPHIC_ADDRESS  ADD(USPS_VERIFICATION_STATUS VARCHAR2(20));

DROP TABLE TRANSACTION_POSTTODAY;
-- table for persisting the EntryRecord object
CREATE TABLE TRANSACTION_POSTTODAY(
TRANSACTION_ID          NUMBER(20,0),
AMOUNT                  NUMBER(20,5),
TRANS_CODE              NUMBER(10,0),
INSTITUTION_ID          VARCHAR2(30),
ACCOUNT_NUMBER          VARCHAR2(30),
ACCOUNT_ID              VARCHAR2(30),
ACCOUNT_TYPE_ID         VARCHAR2(30),    
DESCRIPTION             VARCHAR2(400),
EFFECTIVE_DATE          DATE,
ENTRY_DATE              DATE,
POST_STATUS             NUMBER(1),
REASON_ID 		VARCHAR2(10),
REASON_DESCRIPTION 	VARCHAR2(300),
REASON_DETAIL 		VARCHAR2(300),
CHEQUE                  NUMBER(10,0),
LOAN_ENTRY_TYPE_ID      NUMBER(15),   
EVENT_ID                NUMBER(15,0),
FILE_NAME               VARCHAR2(200),
PAYMENT_ID              NUMBER(15,0),
POST_DATE               DATE,
SOURCE_NAME             VARCHAR2(60),
TRACE                   NUMBER(16,0),
BATCH_NUMBER 		VARCHAR2(4),
SERIAL_NUMBER 		NUMBER(8),
COMPANY_NAME 		VARCHAR2(100),
COMPANY_DESCRIPTION 	VARCHAR2(200),
COMPANY_CUST_NUMBER     VARCHAR2(30),
COMPANY_ID              VARCHAR2(30)
);

ALTER TABLE TRANSACTION_POSTTODAY ADD ( CONSTRAINT TRANSACTION_POSTTODAY_PK PRIMARY KEY (TRANSACTION_ID));

ALTER TABLE TRANSACTION_POSTTODAY ADD(CONSTRAINT TRANSACTION_POSTDAY_AID_FK FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID));

ALTER TABLE TRANSACTION_POSTTODAY ADD(CONSTRAINT TRANSACTION_POSTDAY_ATID_FK FOREIGN KEY (ACCOUNT_TYPE_ID) REFERENCES ACCOUNT_TYPE_LOOKUP(ACCOUNT_TYPE_ID));

ALTER TABLE TRANSACTION_POSTTODAY ADD(CONSTRAINT TRANSACTION_POSTDAY_ANO_IID_FK FOREIGN KEY (ACCOUNT_NUMBER,INSTITUTION_ID) 
REFERENCES ACCOUNT(ACCOUNT_NO,INSTITUTION_ID));

create index tran_pstdy_dates_iid_ano_idx on transaction_posttoday(EFFECTIVE_DATE, ENTRY_DATE,institution_id,account_number) nologging; 



--ENTRY_TYPE
CREATE TABLE ENTRY_TYPE ( 
	UNIQUE_ID      	NUMBER(10,0) NOT NULL,
	ID             	VARCHAR2(10) NULL,
	INSTITUTION_ID 	VARCHAR2(30) NULL,
	DEBIT_OR_CREDIT	VARCHAR2(1) NULL,
	DESCRIPTION    	VARCHAR2(100) NULL 
	);

ALTER TABLE ENTRY_TYPE ADD(CONSTRAINT ENTRY_TYPE_IID_FK FOREIGN KEY (INSTITUTION_ID) REFERENCES INSTITUTION(INSTITUTION_ID));
ALTER TABLE ENTRY_TYPE 	ADD ( CONSTRAINT ENTRY_TYPE_LOOKUP_PK PRIMARY KEY (UNIQUE_ID));
ALTER TABLE ENTRY_TYPE	ADD ( CONSTRAINT ENTRYTYPE_LKP_ID_IID_UK UNIQUE (ID, INSTITUTION_ID));
	
  


drop table tran_code_lookup;	

--TRAN_CODE_LOOKUP
CREATE TABLE TRAN_CODE_LOOKUP ( 
	UNIQUE_ID      	NUMBER(10,0) NOT NULL,
	TRAN_CODE      	VARCHAR2(10) NULL,
	DEBIT_OR_CREDIT	VARCHAR2(1) NULL,
	ACCOUNT_TYPE_ID	VARCHAR2(30) NULL,
	DESCRIPTION    	VARCHAR2(1000) NULL 
	);

  

ALTER TABLE TRAN_CODE_LOOKUP ADD ( CONSTRAINT ENTRY_TYPE_PK PRIMARY KEY (UNIQUE_ID) NOT DEFERRABLE INITIALLY IMMEDIATE );
ALTER TABLE TRAN_CODE_LOOKUP ADD ( CONSTRAINT ENTRY_TYPE_TC_IID_UK UNIQUE (TRAN_CODE, ACCOUNT_TYPE_ID)	NOT DEFERRABLE INITIALLY IMMEDIATE );

--LEDGER_POSTING_PARAMETERS
CREATE TABLE LEDGER_POSTING_PARAMETERS ( 
	UNIQUE_ID                    	NUMBER(10) NOT NULL,
	INSTITUTION_ID               	VARCHAR2(30) NOT NULL,
	ACCOUNT_TYPE_ID              	VARCHAR2(30) NOT NULL,
	ENTRY_TYPE_ID                	VARCHAR2(10) NOT NULL,
	DESCRIPTION                  	VARCHAR2(150) NOT NULL,
	CORESOFT_ENTRY_TYPE 			NUMBER(3),
	AFFECTS_LEDGER_BALANCE       	NUMBER NOT NULL,
	AFFECTS_REVERSAL_TRANCODE    	NUMBER NOT NULL,
	AFFECTS_LST_ACT_DATE         	NUMBER NOT NULL,
	AFFECTS_LST_DEP_DATE         	NUMBER NOT NULL,
	AFFECTS_CALCULATE_FLOAT      	NUMBER NOT NULL,
	AFFECTS_FULL_BAL_HOLD        	NUMBER NOT NULL,
	AFFECTS_PART_BAL_HOLD        	NUMBER NOT NULL,
	AFFECTS_IF_DORMANT_ACCOUNT   	NUMBER NOT NULL,
	AFFECTS_IF_FROZEN_ACCOUNT    	NUMBER NOT NULL,
	AFFECTS_LST_STATEMENT_BAL    	NUMBER NOT NULL,
	AFFECTS_LST_STATEMENT_DATE   	NUMBER NOT NULL,
	AFFECTS_WITHHELD_YTDTAX      	NUMBER NOT NULL,
	AFFECTS_WITHHELD_PTDTAX      	NUMBER NOT NULL,
	AFFECTS_MIN_BAL              	NUMBER NOT NULL,
	AFFECTS_DATE_LST_WITHDRAWL   	NUMBER NOT NULL,
	AFFECTS_STOP_PAYMENT         	NUMBER NOT NULL,
	AFFECTS_PRINT_NOTICE         	NUMBER NOT NULL,
	AFFECTS_ACT_SER_CHARGES      	NUMBER NOT NULL,
	AFFECTS_IND_SER_CHARGES      	NUMBER NOT NULL,
	AFFECTS_ATM_USED_YTD         	NUMBER NOT NULL,
	AFFECTS_TOTAL_ATM_USED       	NUMBER NOT NULL,
	AFFECTS_ANTICIPATED_INT      	NUMBER NOT NULL,
	TOT_UNPOSTED_PASSBOOK_ITMS   	NUMBER NOT NULL,
	COUNT_UNPOSTED_PASSBOOK_ITMS 	NUMBER NOT NULL,
	AFFECTS_NO_OF_DEPOSITS       	NUMBER NOT NULL,
	AFFECTS_NEW_ACCOUNT_DAYS     	NUMBER NOT NULL,
	AFFECTS_IMMEDIATE_CREDIT     	NUMBER NOT NULL,
	IS_PAYOFF_TRANSACTION         	NUMBER NOT NULL,
	AFFECTS_ACCRUED_INT          	NUMBER NOT NULL,
	AFFECTS_EARNINGS_PERIOD      	NUMBER NOT NULL,
	AFFECTS_INTEREST_PAID         	NUMBER NOT NULL,
	AFFECTS_ACH_CREDIT_COUNT     	NUMBER NOT NULL,
	AFFECTS_ACH_DEBIT_COUNT      	NUMBER NOT NULL,
	AFFECTS_ATM_DEBIT_COUNT      	NUMBER NOT NULL,
	AFFECTS_ATM_CREDIT_COUNT     	NUMBER NOT NULL,
	AFFECTS_TOTAL_DEBIT_COUNT    	NUMBER NOT NULL,
	AFFECTS_AMT_OF_DEBITS        	NUMBER NOT NULL,
	AFFECTS_TOTAL_CREDIT_COUNT   	NUMBER NOT NULL,
	AFFECTS_AMT_OF_CREDITS       	NUMBER NOT NULL,
	AFFECTS_CHARGE_FEE           	NUMBER NOT NULL,
	AFFECTS_GREATER_THAN_BAL     	NUMBER NOT NULL,
	AFECTS_GREATER_DEBIT_LIMIT   	NUMBER NOT NULL,
	AFFECTS_LST_CUST_ACT_DATE    	NUMBER NOT NULL,
	AFFECTS_AMT_LST_DEPOSIT      	NUMBER NOT NULL,
	AFFECTS_AMT_LST_WITHDRAWL    	NUMBER NOT NULL,
	POSTING_SEQUENCE             	NUMBER(10,0) NOT NULL,
	AFECTS_BAL_SUBJECT_TO_PENALTY	NUMBER NOT NULL,
	AFFECTS_INTEREST_FORFEITED   	NUMBER NOT NULL,
	AFECTS_ENCLOSURE_DEBIT_COUNT 	NUMBER NOT NULL,
	AFECTS_ENCLOSURE_CREDIT_COUNT	NUMBER NOT NULL,
	AFFECTS_PRE_AUTHORIZED_COUNT 	NUMBER NOT NULL,
	AFFECTS_CHECK_DRAFT_COUNT    	NUMBER NOT NULL,
	AFFECTS_PAPERLESS_DEBITS     	NUMBER NOT NULL,
	AFFECTS_PAPERLESS_CREDITS    	NUMBER NOT NULL,
	AFFECTS_RETURNED_ITEM_COUNT  	NUMBER NOT NULL,
	AFFECTS_ACCOUNT_ANALYSIS     	NUMBER NOT NULL,
	IS_VALID_FOR_OPEN_ACCOUNT    	NUMBER NOT NULL,
	IS_CLOSEOUT_TRANSACTION      	NUMBER NOT NULL ,
	overdrawn_on_cycleday 		number default 0
	);

  
ALTER TABLE LEDGER_POSTING_PARAMETERS 	ADD ( CONSTRAINT LEDGER_POSTING_PK PRIMARY KEY (UNIQUE_ID) NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE LEDGER_POSTING_PARAMETERS	ADD ( CONSTRAINT LEDPOSTING_IID_ATID_ETID_UK UNIQUE (INSTITUTION_ID, ACCOUNT_TYPE_ID, ENTRY_TYPE_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE );
	
ALTER TABLE LEDGER_POSTING_PARAMETERS ADD ( CONSTRAINT LEDPOSTING_IID_FK FOREIGN KEY(INSTITUTION_ID) REFERENCES INSTITUTION(INSTITUTION_ID)
	 NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
	 
ALTER TABLE LEDGER_POSTING_PARAMETERS	ADD ( CONSTRAINT LEDPOSTING_EID_ATID_FK	FOREIGN KEY(ENTRY_TYPE_ID, ACCOUNT_TYPE_ID)
	REFERENCES TRAN_CODE_LOOKUP(TRAN_CODE, ACCOUNT_TYPE_ID)	 NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
	
ALTER TABLE LEDGER_POSTING_PARAMETERS	ADD ( CONSTRAINT LEDPOSTING_ACCTTYPE_FK	FOREIGN KEY(ACCOUNT_TYPE_ID)
	REFERENCES ACCOUNT_TYPE_LOOKUP(ACCOUNT_TYPE_ID)	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
	
create index LEDPOST_PARAM_ETID_IID_IDX on LEDGER_POSTING_PARAMETERS(ENTRY_TYPE_ID, INSTITUTION_ID) nologging;

-- From _14
-- TAX_RATE
CREATE TABLE TAX_RATE (  
	INSTITUTION_ID VARCHAR2(30) PRIMARY KEY, 
	 ALTERNATE_FED_TAX_RATE NUMBER(20,5),  
	 FED_RATE NUMBER(20,5),  
	ALTERNATE_STATE_TAX_RATE NUMBER(20,5),   
	STATE_RATE NUMBER(20,5)
);

ALTER TABLE TAX_RATE ADD CONSTRAINT TAX_RATE_IID_FK FOREIGN KEY(INSTITUTION_ID) REFERENCES INSTITUTION(INSTITUTION_ID);

-- service_charge
ALTER TABLE SERVICE_CHARGE ADD(
		TC_MAINTENANCE_CHARGE 	NUMBER NULL,
		TC_DORMANT_CHARGE 	NUMBER NULL,
		TC_ACTIVITY_CHARGE 	NUMBER NULL,
		TC_FOREIGNITEM_CHARGE 	NUMBER NULL,
		DESC_DORMANT_CHARGE 	VARCHAR2(50) NULL,
		DESC_ACTIVITY_CHARGE 	VARCHAR2(50) NULL,
		DESC_FOREIGN_CHARGE 	VARCHAR2(50) NULL,
		DESC_MAINTENANCE_CHARGE VARCHAR2(50) NULL
);

ALTER TABLE DEPOSIT_ACCOUNT ADD(LAST_SERVICE_CHARGE NUMBER NULL);

-- HOLD and STOP
--alter table HOLD_PAYMENT add ACCOUNT_ID VARCHAR2(30);
--
--alter table STOP_PAYMENT_INSTRUCTION add ACCOUNT_ID VARCHAR2(30);
--
--update HOLD_PAYMENT hp set hp.ACCOUNT_ID = (
--select acc.ACCOUNT_ID from ACCOUNT acc,DEPOSIT_ACCOUNT_INSTRUCTION dai where acc.ACCOUNT_ID = dai.ACCOUNT_ID and 
--hp.INSTRUCTION_ID = dai.INSTRUCTION_ID);
--
--update STOP_PAYMENT_INSTRUCTION sp set sp.ACCOUNT_ID = (
--select acc.ACCOUNT_ID from ACCOUNT acc,DEPOSIT_ACCOUNT_INSTRUCTION dai where acc.ACCOUNT_ID = dai.ACCOUNT_ID and 
--sp.INSTRUCTION_ID = dai.INSTRUCTION_ID);

ALTER TABLE DEPOSIT_ACCOUNT ADD(NO_OF_ATM_USED_YTD NUMBER(10,0) NULL,
FED_WITHHOLD_AMT_CURR_PERIOD number(10,0) null,
FED_WITHHOLD_AMT_YEAR_TO_DATE number(10,0) null	);

alter table ACCOUNT add( LAST_PROCESSED_DATE date);

create index acct_stmt_gen_accid_idx on account_statement_generator(to_number(account_id)) nologging;

create index instintcodes_iid_idx on INSTITUTION_INT_CODES(INSTITUTION_ID) nologging;
create index brintcodes_brid_idx on BRANCH_INT_CODES(BRANCH_ID) nologging;
create index intcoderates_icuid_idx on INTEREST_CODE_RATES(to_number(INTEREST_CODE_UID)) nologging;
create index int_codes_ichuid_idx on INTEREST_CODES(to_number(INTEREST_CODE_HIST_UID)) nologging;
create index acc_atid_iid_lpdate on account(ACCOUNT_TYPE_ID,INSTITUTION_ID,LAST_PROCESSED_DATE) nologging;

--create index hp_accid_idx on hold_payment(to_number(account_id)) nologging; 
--create index stop_pay_inst_accid_idx on stop_payment_instruction(to_number(account_id)) nologging;

alter table deposit_account add(DATE_FIRST_OVERDRAWN DATE);
alter table deposit_account add(PROCEEDS_ACCOUNT_ID VARCHAR2(20));
alter table deposit_account add constraint dep_acc_procaccid_fk foreign key(PROCEEDS_ACCOUNT_ID) references account(account_id);

CREATE INDEX tran_postoday_iid_rid_ps_idx ON TRANSACTION_POSTTODAY (INSTITUTION_ID,REASON_ID, POST_STATUS);




