-- making current statement cycle not null
--alter table deposit_account modify(current_statement_cycle not null);

-- scripts for the OFAC checked feature. 
ALTER TABLE PARTY ADD OFAC_CHECKED char(1);
-- Purpose of this is to add a new column on TAX_PAYMENT_BUSINESS_EVENT table. Which we need to show on EFTPS report page.

alter table TAX_PAYMENT_BUSINESS_EVENT add (TERMINAL VARCHAR2(100));

--  to change the datatype of Iinterest_earned_life from nvarchar to number:

alter table deposit_account add(interest_earned_life_temp VARCHAR2(20));
update DEPOSIT_ACCOUNT set interest_earned_life_temp = INTEREST_EARNED_LIFE;
update DEPOSIT_ACCOUNT set interest_earned_life = null;
alter table deposit_account modify (interest_earned_life number(20,5));
update DEPOSIT_ACCOUNT set interest_earned_life = to_number(INTEREST_EARNED_LIFE_temp);

--Customer reference "'34227652471"  should be linked to Loan account "342276524770"  and checking account '342276524706'.  @ Bank PHNB
-- Customer reference "31417625251"  should be linked to Loan account "314176252570"  and Saving account '314176252520'     @ Bank BRB
-- checking account '342276524706'.  @ Bank PHNB
-- dropping the reference with other customer

ALTER TABLE PARTY_ACCOUNT_ROLE drop CONSTRAINT PARTY_ACCT_ROLE_UPRID_FK;

ALTER TABLE PARTY_ACCOUNT_ROLE ADD(CONSTRAINT PARTY_ACCT_ROLE_UPRID_FK FOREIGN KEY(UNIQUE_PARTY_ROLE_ID)
REFERENCES PARTY_ROLE(UNIQUE_PARTY_ROLE_ID));
-- handling loan DM issues by revathi
alter table  BILLING_BUCKET  add DELQ_NONESC number(20,5);

create sequence BILLING_BUCKET_seq  start with 1;

ALTER TABLE ESCROW_TRANSACTION ADD ESCROW_PAYEE VARCHAR2(30);


CREATE TABLE KEY_CUST_REASON_CODES (
                UNIQUE_ID NUMBER(15),
                KEY_CUST_CODE VARCHAR2(30),
                KEY_CUST_REASON VARCHAR2(100),
                INSTITUTION_ID VARCHAR2(30)
        );
ALTER TABLE KEY_CUST_REASON_CODES  ADD CONSTRAINT KEY_CUST_CODE_PK PRIMARY KEY(UNIQUE_ID);
ALTER TABLE KEY_CUST_REASON_CODES  ADD CONSTRAINT KEY_CUST_CODE_KCC_IID_UK UNIQUE(KEY_CUST_CODE, INSTITUTION_ID);
ALTER TABLE KEY_CUST_REASON_CODES  ADD CONSTRAINT KEY_CUST_CODE_IID_FK FOREIGN KEY(INSTITUTION_ID) REFERENCES INSTITUTION(INSTITUTION_ID);
        
CREATE SEQUENCE KEY_CUST_REASON_CODES_ID_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOMINVALUE NOCYCLE ORDER;

-- PARTY_ASSOC_KEY_CUST_CODE       
     
CREATE TABLE PARTY_ASSOC_KEY_CUST_CODE (
                PARTY_ASSOCIATION_UID NUMBER(15),
                KEY_CUST_CODE_UID NUMBER(15)
);
        
ALTER TABLE PARTY_ASSOC_KEY_CUST_CODE ADD CONSTRAINT PAR_ASS_KEY_CUST_CODE_PK PRIMARY KEY(PARTY_ASSOCIATION_UID, KEY_CUST_CODE_UID);
ALTER TABLE PARTY_ASSOC_KEY_CUST_CODE ADD CONSTRAINT PAR_ASSOC_UID_FK FOREIGN KEY(PARTY_ASSOCIATION_UID) REFERENCES PARTY_INSTITUTION_ASSOCIATION (UNIQUE_ASSOCIATION_ID);
ALTER TABLE PARTY_ASSOC_KEY_CUST_CODE ADD CONSTRAINT PAR_ASS_KEY_CUST_FK FOREIGN KEY(KEY_CUST_CODE_UID) REFERENCES KEY_CUST_REASON_CODES  (UNIQUE_ID);

-- CYCLE_CODE:(Patch_Scripts)
alter table PARTY_INSTITUTION_ASSOCIATION add CYCLE_CODE VARCHAR2(30);

-- DATE_LAST_ACTIVITY
alter table deposit_account add DATE_LAST_ACTIVITY date;

CREATE SEQUENCE INST_RESP_TYPE_OWNER_DESIG_SEQ START WITH 1 ;

CREATE TABLE RESPONSIBILITY_TYPE_LOOKUP(ID NUMBER(2) PRIMARY KEY , 
DESCRIPTION VARCHAR2(50));

CREATE TABLE INST_RESP_TYPE_OWNERSHIP_DESIG(ID NUMBER(15) PRIMARY KEY, INSTITUTION_ID VARCHAR2(30),
RESPONSIBILITY_TYPE_ID NUMBER(2) , 
ORDER_TO_SORT NUMBER(2),
AFFIXDESIGKEYWORD VARCHAR2(30), 
AFFIXPOSITION NUMBER(1));

ALTER TABLE INST_RESP_TYPE_OWNERSHIP_DESIG ADD CONSTRAINT IN_REP_OWN_DEG_IID_RTID_UK UNIQUE(INSTITUTION_ID,RESPONSIBILITY_TYPE_ID);

ALTER TABLE INST_RESP_TYPE_OWNERSHIP_DESIG ADD CONSTRAINT IN_REP_OWN_DEG_IID_FK FOREIGN KEY (INSTITUTION_ID) 
REFERENCES INSTITUTION(INSTITUTION_ID);

ALTER TABLE INST_RESP_TYPE_OWNERSHIP_DESIG ADD CONSTRAINT IN_REP_OWN_DEG_RTID_FK FOREIGN KEY (RESPONSIBILITY_TYPE_ID) 
REFERENCES RESPONSIBILITY_TYPE_LOOKUP(ID);