

CREATE TABLE CLASSCODE_COLLATERAL ( 
	COLLATERAL_TYPE  	VARCHAR2(20) ,
	LOAN_PURPOSE_CODE	NUMBER(5,0)  
	);

ALTER TABLE CLASSCODE_COLLATERAL ADD CONSTRAINT CC_COLLTEARL_LPC_FK	FOREIGN KEY(LOAN_PURPOSE_CODE)
	REFERENCES LOAN_PURPOSE_LOOKUP(UNIQUE_ID);

--Escrpw payee  table  contaisn mapping between escrow_code and escrow_payee name 
CREATE TABLE ESCROW_PAYEE ( 
	ESCROW_CODE   	NUMBER(15) NULL,
	ESCROW_SHTNAME	VARCHAR2(30) NULL,
	ESCROW_NAME   	VARCHAR2(30) NULL 
	);

ALTER TABLE ESCROW_PAYEE ADD CONSTRAINT ESCROW_PAYEE_PK  PRIMARY KEY (ESCROW_CODE);

--ALTER TABLE ESCROW_TRANSACTION MODIFY(ESCROW_PAYEE NUMBER(15));

alter table ESCROW_TRANSACTION add(ESCROW_PAYEE_temp VARCHAR2(30));
alter table ESCROW_TRANSACTION modify (ESCROW_PAYEE number(15));

ALTER TABLE ESCROW_TRANSACTION ADD CONSTRAINT ESCROW_TRAN_ESCPAY_FK  FOREIGN KEY ( ESCROW_PAYEE) 
REFERENCES  ESCROW_PAYEE(ESCROW_CODE);

 
--ADDING  ESCROW_APYEE NAME IN lOAN ACCOUNT TRANSACTION 

ALTER TABLE  LOAN_ACCOUNT_TRANSACTION ADD ESCROW_PAYEE NUMBER(15);

ALTER TABLE LOAN_ACCOUNT_TRANSACTION ADD CONSTRAINT LOAN_TRAN_ESCPAY_FK  FOREIGN KEY ( ESCROW_PAYEE) 
REFERENCES  ESCROW_PAYEE(ESCROW_CODE);  
  

-- MBLNBR should be migrate to "Block ID" instead of census_track.

ALTER TABLE LOAN_ACCOUNT ADD (BLOCK_ID VARCHAR2(30));

-- creating the view again as we are adding a new column in loan_account table.
CREATE OR REPLACE VIEW LOAN_ACCOUNT_VW ( ACCOUNT_NO, INSTITUTION_ID, PRODUCT_ID, ACCOUNT_CATEGORY, ACCOUNT_TYPE_ID, BUSINESS_DATE, DATE_OPENED, CREATION_DATE, ACCOUNT_ID, CUSTOMER_ID, NOTE_NUMBER, START_DATE, CURRENT_MATURITY_DATE, CURRENT_INTEREST_RATE, INTEREST_BASE_CODE, LINE_OF_CREDIT, NEXT_PAYMENT_DUE_DATE, SCHEDULED_PAYMENT_DATE, NEXT_PRINCIPLE_DUE, NEXT_INTEREST_AMOUNT_DUE, NEXT_ESCROW_DUE, NEXT_SUBSIDY_AMOUNT, PAST_DUE_AMOUNT, APPROVED_LOAN_AMOUNT, AVAILED_LOAN_AMOUNT, PRINCIPLE_BALANCE, ACCRUED_INTEREST, UNAPPLIED_FUNDS, LOSS_DRAFT_FUNDS, LATE_FEES_DUE, OTHER_FEES_DUE, LOAN_STATUS, NEXT_REVIEW_DATE, LAST_MAINTENANCE_DATE, CLOSED_DATE, OPENING_BRANCH, PRIMARY_OFFICER, CALL_REPORT_CODE, EXAMINER_CLASSIFICATION_CODE, PREVIOUS_OFFICER, COLLECTION_OFFICER, REPAYMENT_MODE, APPLY_PAYMENTS_AS_BILLED, FIRST_PAYMENT_DATE, PAYMENTS_SCHEDULED, PAYMENTS_MADE, PRINT_BILLING_NOTICE, PRINT_COUPON_BOOK, PRINT_PAST_DUE_NOTICE, BALLOON_PAYMENT, MINIMUM_INTEREST_CHARGE, SPECIAL_MAILING_INSTRUCTIONS, CENSUS_TRACK, ORDER_COUPON_BOOK_NOW, CONTINUES_ORDER_OF_COUPON_BOOK, LATE_CHARGE_CODE, AMORTIZED_BALANCE, LAST_ADDL_PRINCIPAL_DATE, LAST_ADDL_PRINCIPAL_AMOUNT, INTEREST_RATE_TYPE, ACCELERATED_RATE_AT_MATURITY, GRACE_DAYS_AT_MATURITY, LINE_OF_CREDIT_ID, ESCROW_ACCOUNT_ID, NON_ACCRUAL, ORIGINAL_MATURITY_DATE, APPROVED_LIMIT, SECONDARY_ACCRUED, PREPAYMENT_PENALTY_CODE, PREPAYMENT_PENALTY, COMMENTS, PARTY_ID, LOAN_TERM, FREQUENCY_PRINCIPAL, FREQUENCY_INTEREST, ANNUAL_PERCENTAGE_RATE, COMBINED_STATEMENT, PARTIAL_PAYMENT, INTEREST_PAID_YTD, INTEREST_PAID_PYTD, INTEREST_PAID_LTD, LATE_FEES_PAID_YTD, LATE_FEES_PAID_PYTD, LATE_FEES_PAID_LTD, POINTS_PAID_YTD, POINTS_PAID_PYTD, POINTS_PAID_LTD, TAXES_PAID_YTD, TAXES_PAID_PYTD, TAXES_PAID_LTD, ORIGINATION_FEES_YTD, ORIGINATION_FEES_PYTD, ORIGINATION_FEES_LTD, ESCROW_INT_PAID_YTD, ESCROW_INT_PAID_PYTD, ESCROW_INT_PAID_LTD, POINTS_PAID_BY_BORROWER, SUBSIDIES_PAID_YTD, PROPERTY_OR_COLLATERAL, LIFE_INSURANCE_REBATE, ACC_INSURANCE_REBATE, LATE_CHRG_INDICATOR, AUTO_DRAFT, INT_BILLING_DATE, PRINCIPAL_BILLING_DATE, CLASS_CODE, LAST_PAYMENT_DATE, IS_AMORTIZED, DAYS_IN_A_YEAR, PAST_PRINCIPLE_DUE, PERCENTAGE_PAYMENT_AMOUNT, MAXIMUM_AMOUNT, MINIMUM_AMOUNT, MAX_LATE_CHARGE_PER_YEAR, GRACE_PERIOD, LATE_CHRG_YTD, AMT_LC_WAIVED, WAIVE_LATE_CHARGE, LATE_CHARGE_FIXED_AMT, LOAN_TYPE_ID, SCHEDULED_PAYMENT_DUE_DATE, EMPLOYEE_CODE, HOLD4_CODE, INTEREST_PAID_TO_DATE, MFHASERVFEE, PRINCIPAL_INTEREST_PAYMENT, MLOTNBR, MPLATNBR, MPAGENBR, LOAN_PURPOSE_CODE, NON_ESCROW_DUE, NON_ESCROW_BALANCE,
 DATE_LAST_ACTIVITY ,BLOCK_ID)
AS
select A.ACCOUNT_NO,A.INSTITUTION_ID,A.PRODUCT_ID,A.ACCOUNT_CATEGORY,
A.ACCOUNT_TYPE_ID,A.BUSINESS_DATE,A.DATE_OPENED,A.CREATION_DATE, LA."ACCOUNT_ID",LA."CUSTOMER_ID",LA."NOTE_NUMBER",LA."START_DATE",LA."CURRENT_MATURITY_DATE",LA."CURRENT_INTEREST_RATE",LA."INTEREST_BASE_CODE",LA."LINE_OF_CREDIT",LA."NEXT_PAYMENT_DUE_DATE",LA."SCHEDULED_PAYMENT_DATE",LA."NEXT_PRINCIPLE_DUE",LA."NEXT_INTEREST_AMOUNT_DUE",LA."NEXT_ESCROW_DUE",LA."NEXT_SUBSIDY_AMOUNT",LA."PAST_DUE_AMOUNT",LA."APPROVED_LOAN_AMOUNT",LA."AVAILED_LOAN_AMOUNT",LA."PRINCIPLE_BALANCE",LA."ACCRUED_INTEREST",LA."UNAPPLIED_FUNDS",LA."LOSS_DRAFT_FUNDS",LA."LATE_FEES_DUE",LA."OTHER_FEES_DUE",LA."LOAN_STATUS",LA."NEXT_REVIEW_DATE",LA."LAST_MAINTENANCE_DATE",LA."CLOSED_DATE",LA."OPENING_BRANCH",LA."PRIMARY_OFFICER",LA."CALL_REPORT_CODE",LA."EXAMINER_CLASSIFICATION_CODE",LA."PREVIOUS_OFFICER",LA."COLLECTION_OFFICER",LA."REPAYMENT_MODE",LA."APPLY_PAYMENTS_AS_BILLED",LA."FIRST_PAYMENT_DATE",LA."PAYMENTS_SCHEDULED",LA."PAYMENTS_MADE",LA."PRINT_BILLING_NOTICE",LA."PRINT_COUPON_BOOK",LA."PRINT_PAST_DUE_NOTICE",LA."BALLOON_PAYMENT",LA."MINIMUM_INTEREST_CHARGE",LA."SPECIAL_MAILING_INSTRUCTIONS",LA."CENSUS_TRACK",LA."ORDER_COUPON_BOOK_NOW",LA."CONTINUES_ORDER_OF_COUPON_BOOK",LA."LATE_CHARGE_CODE",LA."AMORTIZED_BALANCE",LA."LAST_ADDL_PRINCIPAL_DATE",LA."LAST_ADDL_PRINCIPAL_AMOUNT",LA."INTEREST_RATE_TYPE",LA."ACCELERATED_RATE_AT_MATURITY",LA."GRACE_DAYS_AT_MATURITY",LA."LINE_OF_CREDIT_ID",LA."ESCROW_ACCOUNT_ID",LA."NON_ACCRUAL",LA."ORIGINAL_MATURITY_DATE",LA."APPROVED_LIMIT",LA."SECONDARY_ACCRUED",LA."PREPAYMENT_PENALTY_CODE",LA."PREPAYMENT_PENALTY",LA."COMMENTS",LA."PARTY_ID",LA."LOAN_TERM",LA."FREQUENCY_PRINCIPAL",LA."FREQUENCY_INTEREST",LA."ANNUAL_PERCENTAGE_RATE",LA."COMBINED_STATEMENT",LA."PARTIAL_PAYMENT",LA."INTEREST_PAID_YTD",LA."INTEREST_PAID_PYTD",LA."INTEREST_PAID_LTD",LA."LATE_FEES_PAID_YTD",LA."LATE_FEES_PAID_PYTD",LA."LATE_FEES_PAID_LTD",LA."POINTS_PAID_YTD",LA."POINTS_PAID_PYTD",LA."POINTS_PAID_LTD",LA."TAXES_PAID_YTD",LA."TAXES_PAID_PYTD",LA."TAXES_PAID_LTD",LA."ORIGINATION_FEES_YTD",LA."ORIGINATION_FEES_PYTD",LA."ORIGINATION_FEES_LTD",LA."ESCROW_INT_PAID_YTD",LA."ESCROW_INT_PAID_PYTD",LA."ESCROW_INT_PAID_LTD",LA."POINTS_PAID_BY_BORROWER",LA."SUBSIDIES_PAID_YTD",LA."PROPERTY_OR_COLLATERAL",LA."LIFE_INSURANCE_REBATE",LA."ACC_INSURANCE_REBATE",LA."LATE_CHRG_INDICATOR",LA."AUTO_DRAFT",LA."INT_BILLING_DATE",LA."PRINCIPAL_BILLING_DATE",LA."CLASS_CODE",LA."LAST_PAYMENT_DATE",LA."IS_AMORTIZED",LA."DAYS_IN_A_YEAR",LA."PAST_PRINCIPLE_DUE",LA."PERCENTAGE_PAYMENT_AMOUNT",LA."MAXIMUM_AMOUNT",LA."MINIMUM_AMOUNT",LA."MAX_LATE_CHARGE_PER_YEAR",LA."GRACE_PERIOD",LA."LATE_CHRG_YTD",LA."AMT_LC_WAIVED",LA."WAIVE_LATE_CHARGE",LA."LATE_CHARGE_FIXED_AMT",LA."LOAN_TYPE_ID",LA."SCHEDULED_PAYMENT_DUE_DATE",LA."EMPLOYEE_CODE",LA."HOLD4_CODE",LA."INTEREST_PAID_TO_DATE",LA."MFHASERVFEE",LA."PRINCIPAL_INTEREST_PAYMENT",LA."MLOTNBR",LA."MPLATNBR",LA."MPAGENBR",LA."LOAN_PURPOSE_CODE",LA."NON_ESCROW_DUE",LA."NON_ESCROW_BALANCE",
LA.DATE_LAST_ACTIVITY,LA.BLOCK_ID
from ACCOUNT A,LOAN_ACCOUNT LA
where A.ACCOUNT_ID=LA.ACCOUNT_ID
 ;
 
 
-- indexes
CREATE INDEX hp_tonum_instrid_idx ON HOLD_PAYMENT(TO_NUMBER("INSTRUCTION_ID"));

CREATE INDEX hp_nvl_hold_amt_idx ON HOLD_PAYMENT(NVL(HOLD_AMOUNT,0));

CREATE INDEX hp_nvl_hold_type_idx ON HOLD_PAYMENT (NVL(HOLD_TYPE_ID,0));

CREATE INDEX DAI_tonum_instrid_idx ON DEPOSIT_ACCOUNT_INSTRUCTION(TO_NUMBER("INSTRUCTION_ID"));

CREATE INDEX DAI_NVL_EFF_EXPIREDT_IDX ON DEPOSIT_ACCOUNT_INSTRUCTION (NVL(EFFECTIVE_EXPIRE_DATE ,TO_DATE('01/01/1001','DD/MM/YYYY')));

CREATE INDEX DAI_NVL_EFF_start_DT_IDX ON DEPOSIT_ACCOUNT_INSTRUCTION (NVL(EFFECTIVE_start_DATE ,TO_DATE('01/01/1001','DD/MM/YYYY')));

