-- CONSTRAINTS

ALTER TABLE PARTY_INSTITUTION_ASSOCIATION ADD CONSTRAINT PARTY_INS_ASS_PK PRIMARY KEY (UNIQUE_ASSOCIATION_ID);

ALTER TABLE PARTY_INSTITUTION_ASSOCIATION ADD CONSTRAINT PARTY_INS_ASS_PID_IID_UK UNIQUE (PARTY_ID, INSTITUTION_ID);
 
ALTER TABLE PARTY_INSTITUTION_ASSOCIATION ADD CONSTRAINT PARTY_INS_ASS_ID_IID_UK UNIQUE (INSTITUTION_ASSOCIATION_ID, INSTITUTION_ID);
 
ALTER TABLE ACCOUNTING_EVENT_PAYMENT ADD CONSTRAINT ACC_EVE_PAY_PK PRIMARY KEY (ACCOUNTING_EVENT_ID, PAYMENT_ID);
   
ALTER TABLE ACCOUNT_APPLICATION ADD CONSTRAINT ACCOUNT_APPLICATION_PK PRIMARY KEY (UNIQUE_ID);
 
ALTER TABLE ACCOUNT_ASSOCIATES ADD CONSTRAINT AASS_PK PRIMARY KEY (PARTY_ID, ASSOCIATE_ID, ACCOUNT_ID);
 
ALTER TABLE ACCOUNT_FORM ADD CONSTRAINT ACCOUNT_FORM_PK PRIMARY KEY (ID);
   
ALTER TABLE ACCOUNT_MAINTENANCE_LOG ADD CONSTRAINT ACC_MAINT_LOG_PK PRIMARY KEY (ENTRY_ID);

ALTER TABLE ACCOUNT_OPENING_EVENT ADD CONSTRAINT ACC_OP_EV_PK PRIMARY KEY (UNIQUE_ID);

ALTER TABLE ACCOUNT_OPENING_EVENT ADD CONSTRAINT ACCOPEV_IID_AOEID_UK UNIQUE (INSTITUTION_ID, ACC_OPENING_EVENT_ID);

ALTER TABLE ACCOUNT_OWNER ADD CONSTRAINT ACCT_OWNR_PK PRIMARY KEY (UNIQUE_PARTY_ROLE_ID);
   
ALTER TABLE ACCOUNT_STATEMENT_ADDRESS ADD CONSTRAINT ACCT_STMT_ADDR_PK PRIMARY KEY (UNIQUE_STMT_ADDR_ID);

ALTER TABLE ACCOUNT_STATEMENT_ADDRESS ADD CONSTRAINT ACCT_STMT_ADDR_UID_UPAID_UK UNIQUE (UNIQUE_ID, UNIQUE_PARTY_ADDRESS_ID);
 
ALTER TABLE ACCOUNT_STATEMENT_GENERATOR ADD CONSTRAINT ACCT_STMT_GEN_ACCID_UK UNIQUE (ACCOUNT_ID);
   
ALTER TABLE ACCOUNT_STATEMENT_GENERATOR ADD CONSTRAINT ACCT_STMT_GEN_PK PRIMARY KEY (UNIQUE_ID);

ALTER TABLE ACCOUNT_TYPE_LOOKUP ADD CONSTRAINT ACTLKP_PK PRIMARY KEY (ACCOUNT_TYPE_ID);
 
ALTER TABLE ACCOUNT_USER_CODE ADD CONSTRAINT ACCUC_PK PRIMARY KEY (ACCOUNT_ID, USER_CODE_ID);
 
ALTER TABLE ACH_BATCH ADD CONSTRAINT ACH_BATCH_PK PRIMARY KEY (ACH_BATCH_ID);
 
ALTER TABLE ACH_BATCH_SUMMARY ADD CONSTRAINT ACH_BATCH_SUMMARY_PK PRIMARY KEY (BATCH_ID);
  
ALTER TABLE ACH_EVENT ADD CONSTRAINT ACH_EVENT_ID_PK PRIMARY KEY (EVENT_ID);
 
ALTER TABLE ACH_FILE ADD CONSTRAINT ACH_FILE_PK PRIMARY KEY (ACH_FILE_ID);

ALTER TABLE ACH_FRABA_SUMMARY ADD CONSTRAINT ACH_FRABA_SUMMARY_PK PRIMARY KEY (ACH_FILE_ID, FRABA_ID);

ALTER TABLE ACH_RECEIVER ADD CONSTRAINT ACH_REC_INSTID_PK PRIMARY KEY (ACH_REC_INST_ID);
 
ALTER TABLE ACH_WARE_HOUSE_ENTRY ADD CONSTRAINT ACH_WARE_HOUSE_ENTRY_PK PRIMARY KEY (ACH_WARE_HOUSE_ENTRY_ID);

ALTER TABLE ACTION_MASTER ADD CONSTRAINT ACMSTR_ACNAME_UK UNIQUE (ACTION_NAME);

ALTER TABLE ACTION_MASTER ADD CONSTRAINT ACMSTR_PK PRIMARY KEY (ACTION_ID);
 
ALTER TABLE ADDRESS ADD CONSTRAINT ADDRESS_ADDRTYPE_CHK CHECK (ADDRESS_TYPE IN('GEOGRAPHIC','TELECOM','WEB')) ;
 
ALTER TABLE ADDRESS ADD CONSTRAINT ADDRESS_PK PRIMARY KEY (ADDRESS_ID);

ALTER TABLE ADDRESS_TYPE_LOOKUP ADD CONSTRAINT ATLKP_PK PRIMARY KEY (ADDRESS_TYPE_ID);

ALTER TABLE ANSWER ADD CONSTRAINT ANSWER_PK PRIMARY KEY (UNIQUE_ID);

ALTER TABLE APPLICATION ADD CONSTRAINT APPLICATION_PK PRIMARY KEY (APPLICATION_ID);

ALTER TABLE APPLICATION ADD CONSTRAINT APPLICATION_AN_IID_UK UNIQUE (APPLICATION_NUMBER, INSTITUTION_ID);

ALTER TABLE APPLICATION ADD CONSTRAINT APPLICATION_STATUS_CHK CHECK (STATUS IN(0,1,2,3,4,5,6,7,8)) ;
 
ALTER TABLE APPLICATION_STMT_ADDRESS ADD CONSTRAINT APP_STMT_ADD_PK PRIMARY KEY (UNIQUE_APPL_STMT_ADDRESS_ID);
  
ALTER TABLE APPLICATION_STMT_ADDRESS ADD CONSTRAINT APP_STMT_ADD_ASID_UPAID_UK UNIQUE (APPL_STATEMENT_ID, UNIQUE_PARTY_ADDRESS_ID);
 
ALTER TABLE APPLICATION_STMT_GENERATOR ADD CONSTRAINT APP_STMT_GEN_PK PRIMARY KEY (APPL_STATEMENT_ID);

ALTER TABLE APPL_CD_PRODUCT ADD CONSTRAINT APPL_CD_PROD_PK PRIMARY KEY (UNIQUE_ID);

ALTER TABLE APPL_CHECKING_PRODUCT ADD CONSTRAINT APPL_CHECKING_PROD_UID_PK PRIMARY KEY (UNIQUE_ID);
 
ALTER TABLE APPL_POTENTIAL_DEPOSIT_EVENT ADD CONSTRAINT APDE_APPL_POT_ID_PK PRIMARY KEY (APPLICATION_ID, POTENTIAL_DEP_EVE_ID);
 
ALTER TABLE APPL_PRODUCT ADD CONSTRAINT APPL_PROD_PK PRIMARY KEY (UNIQUE_ID);
 
ALTER TABLE APPL_PRODUCT_FORM ADD CONSTRAINT APPPRODFORM_APUID_PFTUID_UK UNIQUE (APPL_PRODUCT_UID, PROD_FORM_TEMP_UID);
 
ALTER TABLE APPL_PRODUCT_FORM ADD CONSTRAINT APPL_PROD_FORM_PK PRIMARY KEY (APPL_PRODUCT_FORM_ID);
 
ALTER TABLE APPL_SAVINGS_PRODUCT ADD CONSTRAINT APPL_SAV_PROD_PK PRIMARY KEY (UNIQUE_ID);
 
ALTER TABLE ASSOCIATE ADD CONSTRAINT ASSOCIATE_PK PRIMARY KEY (ASSOCIATE_ID);
 
ALTER TABLE AVERAGE_BALANCE_MONTHLY_DATA ADD CONSTRAINT ABMD_PK PRIMARY KEY (ACCOUNT_ID, MONTH);
 
ALTER TABLE BENEFICIARY ADD CONSTRAINT BEN_BID_PK PRIMARY KEY (BENEFICIARY_ID);
 
ALTER TABLE BILLING_BUCKET ADD CONSTRAINT BB_PK PRIMARY KEY (ACCOUNT_ID, BILLING_BUCKET_NUMBER);

ALTER TABLE BOND ADD CONSTRAINT BOND_PK PRIMARY KEY (BOND_ID);
 
ALTER TABLE BOND_INST_APPL ADD CONSTRAINT BOND_INST_APPL_PK PRIMARY KEY (BOND_INST_APPL_ID);
   
ALTER TABLE BOND_REDEMPTION ADD CONSTRAINT BOND_REDEM_PK PRIMARY KEY (BOND_REDEMPTION_ID);
 
ALTER TABLE BOND_REDEMPTION_INFO ADD CONSTRAINT BOND_RED_INFO_PK PRIMARY KEY (BOND_RED_INFO_ID);
 
ALTER TABLE BRANCH ADD CONSTRAINT BRANCH_UK UNIQUE (BRANCH_ID, INSTITUTION_ID);
 
ALTER TABLE BRANCH ADD CONSTRAINT BRANCH_PK PRIMARY KEY (UNIQUE_ID);
 
ALTER TABLE CALL_REPORT_LKP ADD CONSTRAINT CRLKP_PK PRIMARY KEY (CALL_REPORT_CODE);
 
ALTER TABLE CASH_PAYMENT ADD CONSTRAINT CASH_PAYMENT_PK PRIMARY KEY (PAYMENT_METHOD_ID);
 
ALTER TABLE CHECK_PAYMENT ADD CONSTRAINT CHECK_PAYMENT_PK PRIMARY KEY (PAYMENT_METHOD_ID);

ALTER TABLE CLASS_LOOKUP ADD CONSTRAINT CLKP_PK PRIMARY KEY (CLASS_CODE, INSTITUTION_ID, ACCOUNT_TYPE_ID);
 
ALTER TABLE COLLATERAL_TYPE_LOOKUP ADD CONSTRAINT COLL_TYPE_LKP_PK PRIMARY KEY (COLLATERAL_TYPE);

ALTER TABLE COLLATERAL_UCCEXPIRATION_DATE ADD CONSTRAINT COLL_UCCEXP_PK PRIMARY KEY (COLLATERAL_ID, UCC_EXPIRATION_DATE_ID);

ALTER TABLE CONDITION_MASTER ADD CONSTRAINT CONDMSTR_CONAME_UK UNIQUE (CONDITION_NAME);
 
ALTER TABLE CONDITION_MASTER ADD CONSTRAINT CONDMSTR_PK PRIMARY KEY (CONDITION_ID);
 
ALTER TABLE CONF_STMT_FLAG_LOOKUP ADD CONSTRAINT CONFSTMTFLAGLKP_PK PRIMARY KEY (CONF_STMT_FLAG);
   
ALTER TABLE CORESOFT_TRANCODE_LKP ADD CONSTRAINT CORESOFT_TRANCODE_LKP_PK PRIMARY KEY (TRANCODE_ID);
   
ALTER TABLE CUSTOMER ADD CONSTRAINT CUST_PK PRIMARY KEY (PARTY_ID, INSTITUTION_ID);

ALTER TABLE CUSTOMER ADD CONSTRAINT CUST_CID_IID_UK UNIQUE (CUSTOMER_ID, INSTITUTION_ID);

ALTER TABLE CUSTOMER_GROUP ADD CONSTRAINT CUSTGROUP_PK PRIMARY KEY (GROUP_ID);

ALTER TABLE CUSTOMER_TYPE_LOOKUP ADD CONSTRAINT CTLKP_PK PRIMARY KEY (CUSTOMER_TYPE_ID);

ALTER TABLE DEPOSIT_EVENT ADD CONSTRAINT DEPOSIT_EVENT_PK PRIMARY KEY (EVENT_ID);

ALTER TABLE DEPOSIT_MIS_DATA_CODE_LKP ADD CONSTRAINT DMIS_DATA_CODE_LKP_PK PRIMARY KEY (MIS_DATA_CODE);

ALTER TABLE ELIGIBILITY_QUESTION ADD CONSTRAINT ELIGI_QUEST_PK PRIMARY KEY (UNIQUE_ID);

ALTER TABLE ELIGIBILITY_REVIEW_REPORT ADD CONSTRAINT ELIGI_REV_REP_PK PRIMARY KEY (UNIQUE_ID);
   
ALTER TABLE ELIGIBILITY_REVIEW_TEMPLATE ADD CONSTRAINT ELIGI_REV_TEMPL_PK PRIMARY KEY (UNIQUE_ID);

ALTER TABLE ELIGIBILITY_TEMPLATE_QUESTION ADD CONSTRAINT ELIGI_TEMPL_QUEST_PK PRIMARY KEY (UNIQUE_ID);
 
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMP_PK PRIMARY KEY (EMPLOYEE_ID);

ALTER TABLE ENTITY ADD CONSTRAINT ENTITY_PK PRIMARY KEY (ENTITY_ID);

ALTER TABLE EVENT ADD CONSTRAINT EVENT_PK PRIMARY KEY (EVENT_ID);
   
ALTER TABLE EXAM_CLASSIFICATION_LKP ADD CONSTRAINT ECLKP_PK PRIMARY KEY (EXAMINER_CLASSIFICATION_CODE);
 
ALTER TABLE EXCEPTIONS_ITEM ADD CONSTRAINT EI_PK PRIMARY KEY (TRAN_CODE, ACCOUNT_ID);

ALTER TABLE FEATURE ADD CONSTRAINT FEATURE_PK PRIMARY KEY (FEATURE_UID);
 
ALTER TABLE FORM_TEMPLATE ADD CONSTRAINT FORM_TEMPLATE_PK PRIMARY KEY (UNIQUE_FORM_ID);

ALTER TABLE FORM_TEMPLATE ADD CONSTRAINT FORM_TEMPLATE_ISEDIT_CHK CHECK (IS_EDITABLE IN(0,1)) ;
 
ALTER TABLE FRABA ADD CONSTRAINT FRABA_PK PRIMARY KEY (FRABA_ID);

ALTER TABLE FUNDS_TRANSFER_EVENT ADD CONSTRAINT FUNDS_TRANSFER_EVENT_PK PRIMARY KEY (EVENT_ID);

ALTER TABLE GUARANTEE ADD CONSTRAINT GUAR_PK PRIMARY KEY (GUARANTOR_ID, ACCOUNT_ID);
 
ALTER TABLE HOLD_TYPE_LOOKUP ADD CONSTRAINT HTLKP_PK PRIMARY KEY (HOLD_TYPE_ID);
 
ALTER TABLE IDENTITY_PROOF ADD CONSTRAINT IDENTITY_PROOF_PK PRIMARY KEY (PROOF_ID);
 
ALTER TABLE INSTITUTION ADD CONSTRAINT IT_PK PRIMARY KEY (INSTITUTION_ID);

ALTER TABLE INSTITUTION_ACCT_TRAN_TYPES ADD CONSTRAINT INST_ACC_TRAN_TYPES_PK PRIMARY KEY (INSTITUTION_ID, ACCOUNT_TYPE_ID, TRANSACTION_CODE);

ALTER TABLE INSTITUTION_ADDRESS ADD CONSTRAINT INST_ADDR_PK PRIMARY KEY (UNIQUE_INSTITUTION_ADDRESS_ID);

ALTER TABLE INSTITUTION_GROUP ADD CONSTRAINT IG_PK PRIMARY KEY (CONSORTIUM_ID, INSTITUTION_ID);
 
ALTER TABLE INSTITUTION_SAVINGS_PLAN_TYPE ADD CONSTRAINT INST_SAV_PLAN_TYPE_PK PRIMARY KEY (INSTITUTION_ID, SAVINGS_PLAN_TYPE_ID);

ALTER TABLE INSTITUTION_STOP_PAYS ADD CONSTRAINT ISP_PK PRIMARY KEY (INSTITUTION_ID, ISSUE_MODE);

ALTER TABLE INSTITUTION_TRANSCODE_LOOKUP ADD CONSTRAINT INST_TRANSCODE_LKP_ALL_UK UNIQUE (INSTITUTION_ID, ACCOUNT_TYPE_ID, TRANS_CODE);

ALTER TABLE INSTITUTION_TYPE_LOOKUP ADD CONSTRAINT ITL_PK PRIMARY KEY (INSTITUTION_TYPE_ID);

ALTER TABLE INSTITUTION_USERS ADD CONSTRAINT IU_PK PRIMARY KEY (INSTITUTION_ID, ROLE_ID, USER_ID);

ALTER TABLE INST_HOLDER ADD CONSTRAINT INST_HOLDER_PK PRIMARY KEY (UNIQUE_PARTY_ROLE_ID);

ALTER TABLE INST_PROD_CAT_CLASS_CODE ADD CONSTRAINT IPROD_CAT_CLS_CODE_PK PRIMARY KEY (UNIQUE_ID);

ALTER TABLE INST_PROD_CAT_CLASS_CODE ADD CONSTRAINT IPRODCATCC_IID_PCID_CC_CCD_UK UNIQUE (INSTITUTION_ID, PRODUCT_CATEGORY_ID, CLASS_CODE, CLASS_CODE_DESC);
 
ALTER TABLE INTERESTED_PARTY ADD CONSTRAINT INTERESTED_PARTY_PK PRIMARY KEY (UNIQUE_PARTY_ROLE_ID);

ALTER TABLE INTEREST_BASE_LOOKUP ADD CONSTRAINT INT_BASE_LKP_PK PRIMARY KEY (INTEREST_BASE_CODE);

ALTER TABLE INTEREST_CODES ADD CONSTRAINT INTEREST_CODES_PK PRIMARY KEY (UNIQUE_ID);

ALTER TABLE INTEREST_CODE_RATES ADD CONSTRAINT INTEREST_CODE_RATES_PK PRIMARY KEY (UNIQUE_ID);
   
ALTER TABLE INTEREST_CODE_RATES ADD CONSTRAINT INT_CODE_RATES_ICUID_BAL_UK UNIQUE (INTEREST_CODE_UID, BALANCE);

ALTER TABLE INTEREST_INFO_LAST_12_PERIODS ADD CONSTRAINT IINFOLAST12P_PK PRIMARY KEY (ACCOUNT_ID, DATE_LAST_INTEREST);
 
ALTER TABLE LATE_CHARGE ADD CONSTRAINT LC_PK PRIMARY KEY (LATE_CHARGE_CODE);

ALTER TABLE LEGAL_ENTITY ADD CONSTRAINT LEGALENTITY_PK PRIMARY KEY (ENTITY_ID);
 
ALTER TABLE LIABILITY_TYPE_LKP ADD CONSTRAINT LIABTYPE_PK PRIMARY KEY (LIABILITY_TYPE_ID);
 
ALTER TABLE LIABILITY_TYPE_LKP ADD CONSTRAINT LIABTYPE_LBT_UK UNIQUE (LIABILITY_TYPE);

ALTER TABLE LIQUIDATION_INSTRUCTION ADD CONSTRAINT LIQUID_INSTR_UID_PK PRIMARY KEY (UNIQUE_ID);

ALTER TABLE LOAN_CALL_REPORT_LKP ADD CONSTRAINT LOAN_CRLKP_PK PRIMARY KEY (CALL_REPORT_CODE);

ALTER TABLE LOAN_COUPON_BOOK ADD CONSTRAINT LCB_PK PRIMARY KEY (COUPON_BOOK_NO);

ALTER TABLE LOAN_FREQUENCY_LOOKUP ADD CONSTRAINT LOAN_FREQ_LKP_PK PRIMARY KEY (CODE);

ALTER TABLE LOAN_MAINTENANCE_LOG ADD CONSTRAINT LML_PK PRIMARY KEY (ENTRY_ID);

ALTER TABLE LOAN_MESSAGES ADD CONSTRAINT LM_PK PRIMARY KEY (MESSAGE_ID, ACCOUNT_ID);

ALTER TABLE LOAN_PURPOSE_LOOKUP ADD CONSTRAINT LOAN_PURPOSE_LKP_PK PRIMARY KEY (UNIQUE_ID);
 
ALTER TABLE LOAN_TRANS_CODE_LOOKUP ADD CONSTRAINT TCLKP_PK PRIMARY KEY (TRANS_CODE, ACCOUNT_TYPE_ID);
 
ALTER TABLE LOAN_TYPE_LOOKUP ADD CONSTRAINT LTLKP_PK PRIMARY KEY (CLASS_CODE);
 
ALTER TABLE LOAN_TYPE_PARAMETER ADD CONSTRAINT LN_TYPE_ID_PK PRIMARY KEY (LOAN_TYPE_ID);

ALTER TABLE MAINTENANCE_LOG ADD CONSTRAINT MAINTLOG_PK PRIMARY KEY (ENTRY_ID);
   
ALTER TABLE MATURITY_PERIOD ADD CONSTRAINT MATURITY_PERIOD_PK PRIMARY KEY (UNIQUE_ID);
 
ALTER TABLE MATURITY_PERIOD ADD CONSTRAINT MATURITY_PERIOD_IID_MC_UK UNIQUE (INSTITUTION_ID, MATURITY_CODE);

ALTER TABLE MESSAGE_TYPE_LOOKUP ADD CONSTRAINT MTLKP_PK PRIMARY KEY (MESSAGE_TYPE_ID);

ALTER TABLE NSF_OD_DAU_CHARGE_PARAMETER ADD CONSTRAINT NODCP_PK PRIMARY KEY (TYPE, ACCOUNT_ID);

ALTER TABLE NSF_OD_DAU_HISTORY ADD CONSTRAINT NODH_PK PRIMARY KEY (ENTRY_FOR, ACCOUNT_ID);

ALTER TABLE OD_PROTECTION_PLAN ADD CONSTRAINT OPP_PK PRIMARY KEY (OD_PROTECTION_PLAN_ID);
 
ALTER TABLE ORGANIZATION ADD CONSTRAINT ORGANIZATION_PK PRIMARY KEY (PARTY_ID);

ALTER TABLE OVERDRAFT_LOOKUP ADD CONSTRAINT ODLKP_PK PRIMARY KEY (OVERDRAFT_CODE);

ALTER TABLE OVERDRAFT_TRANSFER_OPTIONS ADD CONSTRAINT OTO_PK PRIMARY KEY (ACCOUNT_ID);

ALTER TABLE PARTICIPANT ADD CONSTRAINT PARTICIPANT_PK PRIMARY KEY (PARTICIPANT_ID);

ALTER TABLE PARTICIPATING_ACCOUNT ADD CONSTRAINT PARTACC_PK PRIMARY KEY (PARTICIPATING_ACCOUNT_ID);

ALTER TABLE PARTICIPATING_TRANSACTION ADD CONSTRAINT PARTTRAN_PK PRIMARY KEY (TRANSACTION_ID);

ALTER TABLE PARTY ADD CONSTRAINT PARTY_PK PRIMARY KEY (PARTY_ID);

ALTER TABLE PARTY_ACCOUNT_ROLE ADD CONSTRAINT PARTY_ACCT_ROLE_PK PRIMARY KEY (UNIQUE_PARTY_ROLE_ID);

ALTER TABLE PARTY_ACCOUNT_ROLES ADD CONSTRAINT PARTYACCROLES_UAID_RID_AID_UK UNIQUE (UNIQUE_ASSOCIATION_ID, ROLE_ID, ACCOUNT_ID);

ALTER TABLE PARTY_ACCOUNT_ROLES ADD CONSTRAINT PARTYACCROLES_PK PRIMARY KEY (UNIQUE_ROLE_ID);

ALTER TABLE PARTY_ADDRESS ADD CONSTRAINT PARTYADDR_PK PRIMARY KEY (UNIQUE_PARTY_ADDRESS_ID);

ALTER TABLE PARTY_ADDRESS_CREDENTIAL ADD CONSTRAINT PARTY_ADDR_CRED_PK PRIMARY KEY (UNIQUE_PARTY_ADDRESS_ID);

ALTER TABLE PARTY_ALIASES ADD CONSTRAINT PARTY_ALIASES_PK PRIMARY KEY (UNIQUE_ALIAS_ID);

ALTER TABLE PARTY_APPLICANT_ROLE ADD CONSTRAINT P_APPL_ROLE_PK PRIMARY KEY (UNIQUE_PARTY_ROLE_ID);

ALTER TABLE PARTY_ASSOC_FIN_CREDENTIAL ADD CONSTRAINT ASSOC_FIN_CRED_PK PRIMARY KEY (UNIQUE_ASSOCIATION_ID);

ALTER TABLE PARTY_ASSOC_MAINTENANCE_LOG ADD CONSTRAINT PARTYASSOC_MAINT_LOG_PK PRIMARY KEY (ENTRY_ID);

ALTER TABLE PARTY_ASSOC_MAINT_LOG ADD CONSTRAINT CHANGE_LOG_ENTRY_ID_PK PRIMARY KEY (CHANGE_LOG_ENTRY_ID);

ALTER TABLE PARTY_ASSOC_SOC_CREDENTIAL ADD CONSTRAINT ASSOC_SOC_CRED_PK PRIMARY KEY (UNIQUE_ASSOCIATION_ID);
 
ALTER TABLE PARTY_PLAN_ROLES ADD CONSTRAINT PARTY_PLAN_ROLES_PK PRIMARY KEY (UNIQUE_PARTY_ROLE_ID);

ALTER TABLE PARTY_REGISTERED_IDS ADD CONSTRAINT PRIDS_PK PRIMARY KEY (ID);

ALTER TABLE PARTY_ROLE ADD CONSTRAINT PARTY_ROLE_PK PRIMARY KEY (UNIQUE_PARTY_ROLE_ID);

ALTER TABLE PARTY_ROLES_APPLICATION ADD CONSTRAINT PARTY_ROLES_APP_PK PRIMARY KEY (APPLICATION_ID);

ALTER TABLE PARTY_ROLE_TYPE ADD CONSTRAINT PARTY_ROLE_TYPE_PK PRIMARY KEY (ROLE_TYPE_ID);

ALTER TABLE PAYMENT ADD CONSTRAINT PAYMENT_PK PRIMARY KEY (PAYMENT_ID);

ALTER TABLE PAYMENT ADD CONSTRAINT PAYMENT_PID_EID_UK UNIQUE (PAYMENT_ID, EVENT_ID);

ALTER TABLE PAYMENT_METHOD ADD CONSTRAINT PAY_METHOD_PK PRIMARY KEY (PAYMENT_METHOD_ID);

ALTER TABLE PAYMENT_POSTING_SEQUENCE ADD CONSTRAINT PPS_ACCID_PK PRIMARY KEY (ACCOUNT_ID, POSTING_FIELD);

ALTER TABLE PENALTY_PARAMETER ADD CONSTRAINT PP_PK PRIMARY KEY (PENALTY_ID);

ALTER TABLE PERIOD_SUMMARY_HISTORY ADD CONSTRAINT PERIOD_SUMMARY_HISTORY_PK PRIMARY KEY (PERIOD_SUMMARY_ENTRY_ID);

ALTER TABLE PERIOD_SUMMARY_HISTORY ADD CONSTRAINT PER_SUM_HIS_ACID_SD_ED_UK UNIQUE (ACCOUNT_ID, PERIOD_SUMMARY_START_DATE, PERIOD_SUMMARY_END_DATE);

ALTER TABLE PERIOD_SUMMARY_INFO ADD CONSTRAINT PERIOD_SUMMARY_INFO_PK PRIMARY KEY (PERIOD_SUMMARY_ENTRY_ID, ENTRY_TYPE);

ALTER TABLE PERSON ADD CONSTRAINT PERSON_PK PRIMARY KEY (PARTY_ID);

ALTER TABLE PERSONAL_CUSTOMER ADD CONSTRAINT PERCUST_PK PRIMARY KEY (PARTY_ID);

ALTER TABLE POLICY_MASTER ADD CONSTRAINT POLMSTR_PNAME_UK UNIQUE (POLICY_NAME);

ALTER TABLE POLICY_MASTER ADD CONSTRAINT POLMSTR_PK PRIMARY KEY (POLICY_ID);
 
ALTER TABLE POSSIBLE_BENEFICIARY ADD CONSTRAINT POSSIBLE_BENEFICIARY_PK PRIMARY KEY (UNIQUE_PARTY_ROLE_ID);

ALTER TABLE POSSIBLE_INST_HOLDER ADD CONSTRAINT POSS_INST_HOLDER_PK PRIMARY KEY (UNIQUE_PARTY_ROLE_ID);

ALTER TABLE POSSIBLE_OWNER ADD CONSTRAINT POSSIBLE_OWNER_PK PRIMARY KEY (UNIQUE_PARTY_ROLE_ID);

ALTER TABLE POTENTIAL_DEPOSIT_EVENT ADD CONSTRAINT POTENTIAL_DEPO_EVT_UID_PK PRIMARY KEY (UNIQUE_ID);

ALTER TABLE POTENTIAL_EVENT_SOURCE ADD CONSTRAINT POTENTIAL_EVT_SRC_PK PRIMARY KEY (UNIQUE_ID);

ALTER TABLE POTENTIAL_EVENT_TARGET ADD CONSTRAINT POT_EVT_TARGET_PK PRIMARY KEY (UNIQUE_ID);

ALTER TABLE POTENTIAL_PLAN_EVENT_SOURCE ADD CONSTRAINT POTENTIAL_PLAN_EVT_SRC_UID_PK PRIMARY KEY (UNIQUE_ID);

ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCT_UID);

ALTER TABLE PRODUCT_FEATURE ADD CONSTRAINT PROD_FEATURE_PK PRIMARY KEY (PROD_FEATURE_UID);

ALTER TABLE PRODUCT_FEATURE_INSTANCE ADD CONSTRAINT PROD_FEATURE_INST_PK PRIMARY KEY (PROD_FEATURE_INST_UID);
 
ALTER TABLE PRODUCT_FEATURE_INSTANCE ADD CONSTRAINT PROD_FEAT_INST_PFUID_APUID_UK UNIQUE (PROD_FEATURE_UID, APPL_PRODUCT_UID);

ALTER TABLE PRODUCT_FORM_TEMPLATE ADD CONSTRAINT PRODUCT_FORM_TEMP_PK PRIMARY KEY (PROD_FORM_TEMP_UID);

ALTER TABLE PRODUCT_QUES ADD CONSTRAINT PROD_QUES_PK PRIMARY KEY (PROD_QUES_ID);

ALTER TABLE PRODUCT_TYPE ADD CONSTRAINT PRODUCT_TYPE_PK PRIMARY KEY (UNIQUE_ID);

ALTER TABLE PRODUCT_TYPE ADD CONSTRAINT PRODTYPE_PC_IID_PTID_UK UNIQUE (PRODUCT_CATEGORY, INSTITUTION_ID, PRODUCT_TYPE_ID);

ALTER TABLE PROD_QUES_IDS ADD CONSTRAINT PROD_QUES_IDS_PK PRIMARY KEY (PROD_QUES_ID);

ALTER TABLE QUESTION ADD CONSTRAINT QUESTION_PK PRIMARY KEY (QUESTION_ID);

ALTER TABLE REPAYMENT_MODE_LKP ADD CONSTRAINT RMLKP_PK PRIMARY KEY (REPAYMENT_MODE);

ALTER TABLE RESOURCE_ACTION ADD CONSTRAINT RESAC_PK PRIMARY KEY (RESOURCE_ID, ACTION_ID);

ALTER TABLE RESOURCE_ACTION_POLICY ADD CONSTRAINT RESACP_PK PRIMARY KEY (RESOURCE_ID, ACTION_ID, POLICY_ID);

ALTER TABLE RESOURCE_MASTER ADD CONSTRAINT RESMSTR_RESNAME_UK UNIQUE (RESOURCE_NAME);
 
ALTER TABLE RESOURCE_MASTER ADD CONSTRAINT RESMSTR_PK PRIMARY KEY (RESOURCE_ID);

ALTER TABLE RESPONSIBILITY_LIABILITY ADD CONSTRAINT RESP_LIAB_ALL_UK UNIQUE (INSTITUTION_ID, ACCOUNT_ID, PARTY_ID, ASSOCIATE_ID, LIABILITY_TYPE_ID);

ALTER TABLE RISK_ASSESSMENT ADD CONSTRAINT RISK_ASS_PK PRIMARY KEY (RISK_ASS_ID);

ALTER TABLE ROLE_LOOKUP ADD CONSTRAINT RLKP_PK PRIMARY KEY (ROLE_ID);
 
ALTER TABLE ROLE_MASTER ADD CONSTRAINT ROLMSTR_RNAME_UK UNIQUE (ROLE_NAME);

ALTER TABLE ROLE_MASTER ADD CONSTRAINT ROLMSTR_PK PRIMARY KEY (ROLE_ID);

ALTER TABLE ROLE_RESOURCE_ACTION ADD CONSTRAINT RLRSAC_PK PRIMARY KEY (ROLE_ID, RESOURCE_ID, ACTION_ID);

ALTER TABLE ROLE_RESOURCE_ACTION_CONDITION ADD CONSTRAINT RLRSACCON_RID_RSID_AID_PK PRIMARY KEY (ROLE_ID, RESOURCE_ID, ACTION_ID, CONDITION_ID);

ALTER TABLE SAVINGS_PLAN_CONTR_CONFIG ADD CONSTRAINT SAVINGS_CONFG_SP_ASSYR_PK PRIMARY KEY (SAVINGS_PLAN_TYPE_ID, ASSESSMENT_YEAR);

ALTER TABLE SAVINGS_PLAN_DIST_SEQ ADD CONSTRAINT SPDS_PK PRIMARY KEY (ACCOUNT_ID);

ALTER TABLE SAVINGS_PLAN_MOD_APPLICATION ADD CONSTRAINT SAV_PLAN_MOD_APP_PK PRIMARY KEY (APPLICATION_ID);
 
ALTER TABLE SAVINGS_PLAN_TYPE ADD CONSTRAINT SAVINGS_PLAN_TYPE_PK PRIMARY KEY (UNIQUE_ID);

ALTER TABLE SAVING_PLAN_MAINTENANCE_LOG ADD CONSTRAINT SAVPLAN_MAINT_LOG_PK PRIMARY KEY (ENTRY_ID);

ALTER TABLE SAV_PLAN_JOINT_LIFE_EXP ADD CONSTRAINT SAV_PLAN_JOINT_LIFE_EXP_PK PRIMARY KEY (ACCOUNT_HOLDER_AGE, SPOUSE_AGE);
   
ALTER TABLE SAV_PLAN_SINGLE_LIFE_EXP ADD CONSTRAINT SAV_PLAN_SINGLE_LIFE_EXP_PK PRIMARY KEY (ACCOUNT_HOLDER_AGE);
 
ALTER TABLE SAV_POTENTIAL_EVENT ADD CONSTRAINT SPE_PLAN_DEP_ID_PK PRIMARY KEY (SAVINGS_PLAN_ID, POT_DEPOSIT_EVENT_ID);

ALTER TABLE SCANNED_FORM ADD CONSTRAINT SCANNED_FORM_PK PRIMARY KEY (SCANNED_FORM_UID);

ALTER TABLE SERVICE_CHARGE ADD CONSTRAINT SERVCHRG_SC_IID_PC_UK UNIQUE (SERVICE_CHARGE_CODE, INSTITUTION_ID, PRODUCT_CATEGORY);

ALTER TABLE SERVICE_CHARGE ADD CONSTRAINT SERVCHRG_PK PRIMARY KEY (UNIQUE_ID);

ALTER TABLE SOCIAL_CREDENTIAL_REPORT ADD CONSTRAINT SOC_CRED_REP_PK PRIMARY KEY (UNIQUE_SOC_REPORT_ID);
 
ALTER TABLE STATUS_LOOKUP ADD CONSTRAINT SLKP_PK PRIMARY KEY (STATUS_CODE, INSTITUTION_ID, ACCOUNT_TYPE_ID);

ALTER TABLE STOCK_COLLATERAL ADD CONSTRAINT STOCKCOLL_PK PRIMARY KEY (COLLATERAL_ID);
   
ALTER TABLE STOP_PAYMENTS ADD CONSTRAINT SP_PK PRIMARY KEY (PK_STOPPMTID);

ALTER TABLE STOP_PAYMENT_EVENT ADD CONSTRAINT STOP_PAYMENT_EVENT_PK PRIMARY KEY (EVENT_ID);

ALTER TABLE STOP_TRANCODE_LKP ADD CONSTRAINT STOP_TRANCODE_LKP_PK PRIMARY KEY (INSTITUTION_ID, TRANCODE_ID, ISSUE_MODE);

ALTER TABLE STOP_TYPE_LOOKUP ADD CONSTRAINT STLKP_PK PRIMARY KEY (UNIQUE_ID);

ALTER TABLE SUB_CLASS_LOOKUP ADD CONSTRAINT SCLKP_PK PRIMARY KEY (SUB_CLASS_CODE, INSTITUTION_ID, ACCOUNT_TYPE_ID);
 
ALTER TABLE TAX_PAYMENT_BUSINESS_EVENT ADD CONSTRAINT TP_EVE_ID_PK PRIMARY KEY (TAX_PAYMENT_EVENT_ID);

ALTER TABLE TAX_PAYMENT_EVENT_PAYMENTS ADD CONSTRAINT TAX_EVE_PAY_ID_PK PRIMARY KEY (TAX_PAYMENT_EVENT_ID, PAYMENT_ID);
 
ALTER TABLE TAX_PAYMENT_MONETARY_EVENT ADD CONSTRAINT TAX_EVE_ID_PK PRIMARY KEY (EVENT_ID);
   
ALTER TABLE TAX_WH_TYPE_LOOKUP ADD CONSTRAINT TWTLKP_PK PRIMARY KEY (TYPE_ID);
 
ALTER TABLE TELECOM_ADDRESS ADD CONSTRAINT TELADDR_PK PRIMARY KEY (ADDRESS_ID);
 
ALTER TABLE TRANSACTION_TYPE_LOOKUP ADD CONSTRAINT TTLKP_PK PRIMARY KEY (TRANSACTION_TYPE_ID, ACCOUNT_TYPE_ID);
 
ALTER TABLE USERS ADD CONSTRAINT USERS_PK PRIMARY KEY (USER_ID);

ALTER TABLE USER_CODE ADD CONSTRAINT UC_PK PRIMARY KEY (USER_CODE_ID);

ALTER TABLE USER_CODE ADD CONSTRAINT UC_UCDESC_UK UNIQUE (USER_CODE_DESC);
 
ALTER TABLE USER_TRANSACTION ADD CONSTRAINT USTR_UID_UK UNIQUE (USER_ID);

ALTER TABLE WEB_ADDRESS ADD CONSTRAINT WEBADDR_PK PRIMARY KEY (ADDRESS_ID);
 
ALTER TABLE WITHDRAWAL_EVENT ADD CONSTRAINT WITHDRAWAL_EVENT_PK PRIMARY KEY (EVENT_ID);

ALTER TABLE DEPOSIT_ACCOUNT ADD CONSTRAINT DA_PK PRIMARY KEY (ACCOUNT_ID);

ALTER TABLE ACCOUNT_HISTORY_ITEM ADD CONSTRAINT AHI_PK PRIMARY KEY (TRANSACTION_ID);
 
ALTER TABLE SAVINGS_PLAN_DETAILS ADD CONSTRAINT SPDET_PK PRIMARY KEY (PLAN_ID);
 
ALTER TABLE TAX_INTEREST_DETAILS ADD CONSTRAINT TID_PK PRIMARY KEY (ACCOUNT_ID, YEAR);

ALTER TABLE CREDIT_LINE ADD CONSTRAINT CL_PK PRIMARY KEY (LINE_OF_CREDIT_ID);
 
ALTER TABLE ESCROW_ACCOUNT ADD CONSTRAINT EA_PK PRIMARY KEY (ESCROW_ACCOUNT_ID);

ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT LA_PK PRIMARY KEY (ACCOUNT_ID);
  
ALTER TABLE ESCROW_TRANSACTION ADD CONSTRAINT ET_PK PRIMARY KEY (TRANSACTION_ID);
  
ALTER TABLE LOAN_ACCOUNT_TRANSACTION ADD CONSTRAINT LAT_PK PRIMARY KEY (TRANSACTION_ID);
 
ALTER TABLE ESCROW_GRANTEE ADD CONSTRAINT EG_PK PRIMARY KEY (GRANTEE_ID);
   
ALTER TABLE ESCROW_HEAD ADD CONSTRAINT EH_PK PRIMARY KEY (ESCROW_HEAD_ID);
 
ALTER TABLE ASSET ADD CONSTRAINT ASSET_PK PRIMARY KEY (ASSET_ID);

ALTER TABLE COLLATERAL ADD CONSTRAINT COLLATERAL_PK PRIMARY KEY (COLLATERAL_ID);
 
ALTER TABLE ESCROW_DUES ADD CONSTRAINT ED_EHID_PK PRIMARY KEY (DUEID, ESCROW_HEAD_ID);

ALTER TABLE TAX_WH_ON_INTEREST_PLAN ADD CONSTRAINT TW_ACCOUNT_ID PRIMARY KEY (ACCOUNT_ID);
 
ALTER TABLE LOAN_ACCOUNT_REBATE ADD CONSTRAINT LACCREBATE_PK PRIMARY KEY (ACCOUNT_ID, SOURCE);

ALTER TABLE SAVINGS_PLAN_TRANSACTIONS ADD CONSTRAINT SPT_TID_UK UNIQUE (TRANSACTION_ID);

ALTER TABLE ACCOUNT ADD CONSTRAINT ACCOUNT_PK PRIMARY KEY (ACCOUNT_ID);

ALTER TABLE ACCOUNT ADD CONSTRAINT ACCOUNT_ACCNO_IID_UK UNIQUE (ACCOUNT_NO, INSTITUTION_ID);

ALTER TABLE DEPOSIT_ACCOUNT_INSTRUCTION ADD CONSTRAINT DA_ACCT_INSTRU_PK PRIMARY KEY (INSTRUCTION_ID);

ALTER TABLE STOP_PAYMENT_INSTRUCTION ADD CONSTRAINT STOP_PAYMENT_INSTRU_PK PRIMARY KEY (INSTRUCTION_ID);

ALTER TABLE LOAN_BILLS_LTD ADD CONSTRAINT LOAN_BILLS_LTD_PK PRIMARY KEY (ACCOUNT_ID);
 
ALTER TABLE HOLD_PAYMENT ADD CONSTRAINT HOLD_PAY_INSTRUCTIONID_PK PRIMARY KEY (INSTRUCTION_ID);
   
ALTER TABLE AUTOMATIC_TRANSFER_INSTRUCTION ADD CONSTRAINT AT_TAR_UNQ_ID PRIMARY KEY (AUTO_TRANS_UNIQUE_ID);

ALTER TABLE CIF_OLD_ACCOUNTNO_MAP ADD CONSTRAINT COALM_OLDINSTACC_UK UNIQUE (OLD_INSTITUTION_ID, OLD_ACCOUNT_NO);

ALTER TABLE ACTIVITY_LOG ADD CONSTRAINT ACTIVITY_UNIQUE_ID_PK PRIMARY KEY (ACTIVITY_UNIQUE_ID);
 
ALTER TABLE INTEREST_CODES_HISTORY ADD CONSTRAINT INT_CODES_HIST_PK PRIMARY KEY (UNIQUE_ID);
   
ALTER TABLE ZIP_CODES_LKP ADD PRIMARY KEY (ZIP);
 
ALTER TABLE GEOGRAPHIC_ADDRESS ADD CONSTRAINT GEOADDR_PK PRIMARY KEY (ADDRESS_ID);
  
ALTER TABLE PARTY_INSTITUTION_ASSOCIATION ADD CONSTRAINT PARTY_INS_ASS_IID_FK FOREIGN KEY (INSTITUTION_ID)
	  REFERENCES INSTITUTION (INSTITUTION_ID) ;
 
ALTER TABLE APPL_SAVINGS_PRODUCT ADD CONSTRAINT APPL_SAV_PROD_UID_FK FOREIGN KEY (UNIQUE_ID)
	  REFERENCES APPL_PRODUCT (UNIQUE_ID);
 
ALTER TABLE ASSET_INSURANCE ADD CONSTRAINT ASSINS_ASSID_FK FOREIGN KEY (ASSET_ID)
	  REFERENCES ASSET (ASSET_ID) ;
 
ALTER TABLE ASSET_INSURANCE ADD CONSTRAINT ASSINS_ICID_FK FOREIGN KEY (INSURANCE_COMPANY_ID)
	  REFERENCES LEGAL_ENTITY (ENTITY_ID) ;
 
ALTER TABLE ASSOCIATE_CONTACT ADD CONSTRAINT ASSCON_ASSID_FK FOREIGN KEY (ASSOCIATE_ID)
	  REFERENCES ASSOCIATE (ASSOCIATE_ID) ;
 
ALTER TABLE AVERAGE_BALANCE_MONTHLY_DATA ADD CONSTRAINT ABMD_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES DEPOSIT_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE BENEFICIARY ADD CONSTRAINT BEN_BID_FK FOREIGN KEY (BENEFICIARY_ID)
	  REFERENCES PARTY_PLAN_ROLES (UNIQUE_PARTY_ROLE_ID) ;
 
ALTER TABLE BILLING_BUCKET ADD CONSTRAINT BB_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES LOAN_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE BILL_MAINTENANCE_LOG ADD CONSTRAINT BML_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES LOAN_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE BOND_INST_APPL ADD CONSTRAINT SEB_INST_APPL_INST_HOLD_FK FOREIGN KEY (POSSIBLE_INST_HOLDER_ID)
	  REFERENCES POSSIBLE_INST_HOLDER (UNIQUE_PARTY_ROLE_ID) ;
 
ALTER TABLE BOND_INST_APPL ADD CONSTRAINT SEB_INST_APPL_INST_FK FOREIGN KEY (INSTITUTION_ID)
	  REFERENCES INSTITUTION (INSTITUTION_ID) ;
 
ALTER TABLE BOND_REDEMPTION ADD CONSTRAINT SEB_REDEM_FK FOREIGN KEY (UNIQUE_INST_HOLDER_ID)
	  REFERENCES INST_HOLDER (UNIQUE_PARTY_ROLE_ID) ;
 
ALTER TABLE BOND_REDEMPTION ADD CONSTRAINT SEB_REDEM_UNIQ_FK FOREIGN KEY (BOND_ID)
	  REFERENCES BOND (BOND_ID) ;
 
ALTER TABLE BOND_REDEMPTION_INFO ADD CONSTRAINT SEB_REDEM_INFO_FK FOREIGN KEY (POSSIBLE_INST_HOLDER_ID)
	  REFERENCES POSSIBLE_INST_HOLDER (UNIQUE_PARTY_ROLE_ID) ;
 
ALTER TABLE BRANCH ADD CONSTRAINT BR_IID_FK FOREIGN KEY (INSTITUTION_ID)
	  REFERENCES INSTITUTION (INSTITUTION_ID) ;
 
ALTER TABLE BRANCH_ADDRESS ADD CONSTRAINT BA_BRID_FK FOREIGN KEY (BRANCH_ID)
	  REFERENCES BRANCH (UNIQUE_ID) ;
 
ALTER TABLE BRANCH_ADDRESS ADD CONSTRAINT BA_BAID_FK FOREIGN KEY (ADDRESS_ID)
	  REFERENCES ADDRESS (ADDRESS_ID) ;
 
ALTER TABLE BRANCH_CONTACT ADD CONSTRAINT BC_ATID_FK FOREIGN KEY (ADDRESS_TYPE_ID)
	  REFERENCES ADDRESS_TYPE_LOOKUP (ADDRESS_TYPE_ID) ;
 
ALTER TABLE BRANCH_CONTACT ADD CONSTRAINT BC_BID_IID_FK FOREIGN KEY (BRANCH_ID)
	  REFERENCES BRANCH (UNIQUE_ID) ;
 
ALTER TABLE BRANCH_ROLE ADD CONSTRAINT BRR_RID_FK FOREIGN KEY (ROLE_ID)
	  REFERENCES ROLE_LOOKUP (ROLE_ID) ;
 
ALTER TABLE BRANCH_ROLE ADD CONSTRAINT BRR_BID_IID_FK FOREIGN KEY (BRANCH_ID)
	  REFERENCES BRANCH (UNIQUE_ID) ;
 
ALTER TABLE CASH_PAYMENT ADD CONSTRAINT CASH_PAYMENT_PMID_FK FOREIGN KEY (PAYMENT_METHOD_ID)
	  REFERENCES PAYMENT_METHOD (PAYMENT_METHOD_ID) ;
 
ALTER TABLE CHECK_PAYMENT ADD CONSTRAINT CHECK_PAYMENT_ID_FK FOREIGN KEY (PAYMENT_METHOD_ID)
	  REFERENCES PAYMENT_METHOD (PAYMENT_METHOD_ID) ;
 
ALTER TABLE CLASS_LOOKUP ADD CONSTRAINT CLKP_IID_FK FOREIGN KEY (INSTITUTION_ID)
	  REFERENCES INSTITUTION (INSTITUTION_ID) ;
 
ALTER TABLE CLASS_LOOKUP ADD CONSTRAINT CLKP_ATID_FK FOREIGN KEY (ACCOUNT_TYPE_ID)
	  REFERENCES ACCOUNT_TYPE_LOOKUP (ACCOUNT_TYPE_ID) ;
 
ALTER TABLE ACCOUNTING_EVENT_PAYMENT ADD CONSTRAINT ACC_EVEPAY_ID_FK FOREIGN KEY (ACCOUNTING_EVENT_ID)
	  REFERENCES EVENT (EVENT_ID) ;
 
ALTER TABLE ACCOUNTING_EVENT_PAYMENT ADD CONSTRAINT ACC_PAY_ID_FK FOREIGN KEY (PAYMENT_ID)
	  REFERENCES PAYMENT (PAYMENT_ID) ;
 
ALTER TABLE ACCOUNT_APPLICATION ADD CONSTRAINT ACCOUNT_APPL_UAOEID_FK FOREIGN KEY (UNIQUE_ACC_OPENING_EVENT_ID)
	  REFERENCES ACCOUNT_OPENING_EVENT (UNIQUE_ID) ;
 
ALTER TABLE ACCOUNT_APPLICATION ADD CONSTRAINT ACCOUNT_APPLICATION_PAID_FK FOREIGN KEY (PARENT_APPLICATION_ID)
	  REFERENCES ACCOUNT_APPLICATION (UNIQUE_ID) ;
 
ALTER TABLE ACCOUNT_APPLICATION ADD CONSTRAINT ACCOUNT_APP_UID_FK FOREIGN KEY (UNIQUE_ID)
	  REFERENCES APPLICATION (APPLICATION_ID);
 
ALTER TABLE ACCOUNT_ASSOCIATES ADD CONSTRAINT AASS_ASSID_FK FOREIGN KEY (ASSOCIATE_ID)
	  REFERENCES ASSOCIATE (ASSOCIATE_ID) ;
 
ALTER TABLE ACCOUNT_FORM ADD CONSTRAINT ACC_FORM_UFID_FK FOREIGN KEY (UNIQUE_FORM_ID)
	  REFERENCES FORM_TEMPLATE (UNIQUE_FORM_ID) ;
 
ALTER TABLE ACCOUNT_MAINTENANCE_LOG ADD CONSTRAINT ACC_MAINT_LOG_EID_FK FOREIGN KEY (ENTRY_ID)
	  REFERENCES MAINTENANCE_LOG (ENTRY_ID) ;
 
ALTER TABLE ACCOUNT_OPENING_EVENT ADD CONSTRAINT ACC_OP_EV_BID_FK FOREIGN KEY (BRANCH_ID)
	  REFERENCES BRANCH (UNIQUE_ID) ;
 
ALTER TABLE ACCOUNT_OWNER ADD CONSTRAINT ACCTOWNR_UPRID_FK FOREIGN KEY (UNIQUE_PARTY_ROLE_ID)
	  REFERENCES PARTY_ACCOUNT_ROLE (UNIQUE_PARTY_ROLE_ID) ;
 
ALTER TABLE WEB_ADDRESS ADD CONSTRAINT WEBADDR_ADDRID_FK FOREIGN KEY (ADDRESS_ID)
	  REFERENCES ADDRESS (ADDRESS_ID) ;
 
ALTER TABLE WITHDRAWAL_EVENT ADD CONSTRAINT WD_EVENT_ID_FK FOREIGN KEY (EVENT_ID)
	  REFERENCES EVENT (EVENT_ID) ;
 
ALTER TABLE STOCK_COLLATERAL ADD CONSTRAINT STOCKCOLL_CID_FK FOREIGN KEY (COLLATERAL_ID)
	  REFERENCES COLLATERAL (COLLATERAL_ID) ;
 
ALTER TABLE STOCK_PRICING ADD CONSTRAINT SP_CID_FK FOREIGN KEY (COLLATERAL_ID)
	  REFERENCES STOCK_COLLATERAL (COLLATERAL_ID) ;
 
ALTER TABLE STOP_PAYMENTS ADD CONSTRAINT SP_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES DEPOSIT_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE STOP_PAYMENT_EVENT ADD CONSTRAINT STOP_PAYMENT_EVENT_ID_FK FOREIGN KEY (EVENT_ID)
	  REFERENCES EVENT (EVENT_ID) ;
 
ALTER TABLE STOP_TRANCODE_LKP ADD CONSTRAINT STOP_TRANCODE_LKP_IID_FK FOREIGN KEY (INSTITUTION_ID)
	  REFERENCES INSTITUTION (INSTITUTION_ID) ;
 
ALTER TABLE STOP_TRANCODE_LKP ADD CONSTRAINT STOP_TRANCODE_LKP_TCID_FK FOREIGN KEY (TRANCODE_ID)
	  REFERENCES CORESOFT_TRANCODE_LKP (TRANCODE_ID) ;
 
ALTER TABLE SUB_CLASS_LOOKUP ADD CONSTRAINT SCLKP_IID_FK FOREIGN KEY (INSTITUTION_ID)
	  REFERENCES INSTITUTION (INSTITUTION_ID) ;
 
ALTER TABLE SUB_CLASS_LOOKUP ADD CONSTRAINT SCLKP_ATID_FK FOREIGN KEY (ACCOUNT_TYPE_ID)
	  REFERENCES ACCOUNT_TYPE_LOOKUP (ACCOUNT_TYPE_ID) ;
 
ALTER TABLE TAX_PAYMENT_BUSINESS_EVENT ADD CONSTRAINT TPBE_UNI_ASSOC_ID_FK FOREIGN KEY (UNIQUE_ASSOCIATION_ID)
	  REFERENCES PARTY_INSTITUTION_ASSOCIATION (UNIQUE_ASSOCIATION_ID) ;
 
ALTER TABLE TAX_PAYMENT_BUSINESS_EVENT ADD CONSTRAINT ACH_REC_ID FOREIGN KEY (ACH_RECEIVER_ID)
	  REFERENCES ACH_RECEIVER (ACH_REC_INST_ID) ;
 
ALTER TABLE TAX_PAYMENT_EVENT_PAYMENTS ADD CONSTRAINT TAX_PAY_EVEPAYS_FK FOREIGN KEY (TAX_PAYMENT_EVENT_ID)
	  REFERENCES TAX_PAYMENT_BUSINESS_EVENT (TAX_PAYMENT_EVENT_ID) ;
 
ALTER TABLE TAX_PAYMENT_EVENT_PAYMENTS ADD CONSTRAINT TAX_PAY_EVEID_FK FOREIGN KEY (PAYMENT_ID)
	  REFERENCES PAYMENT (PAYMENT_ID) ;
 
ALTER TABLE TAX_PAYMENT_MONETARY_EVENT ADD CONSTRAINT TAX_EVENT_ID_FK FOREIGN KEY (EVENT_ID)
	  REFERENCES EVENT (EVENT_ID) ;
 
ALTER TABLE TAX_WH_ON_INTEREST_TYPE ADD CONSTRAINT TWOIT_TID_FK FOREIGN KEY (TYPE_ID)
	  REFERENCES TAX_WH_TYPE_LOOKUP (TYPE_ID) ;
 
ALTER TABLE TAX_WITHHELD ADD CONSTRAINT TW_TRID_FK FOREIGN KEY (TRANSACTION_ID)
	  REFERENCES ACCOUNT_HISTORY_ITEM (TRANSACTION_ID) ON DELETE SET NULL ;
 
ALTER TABLE TAX_WITHHELD ADD CONSTRAINT TW_TID_FK FOREIGN KEY (TYPE_ID)
	  REFERENCES TAX_WH_TYPE_LOOKUP (TYPE_ID) ;
 
ALTER TABLE TELECOM_ADDRESS ADD CONSTRAINT TELADDR_ADDRID_FK FOREIGN KEY (ADDRESS_ID)
	  REFERENCES ADDRESS (ADDRESS_ID) ;
 
ALTER TABLE TITLED_COLLATERAL ADD CONSTRAINT TITCOLL_CID_FK FOREIGN KEY (COLLATERAL_ID)
	  REFERENCES COLLATERAL (COLLATERAL_ID) ;
 
ALTER TABLE TRANSACTION_TYPE_LOOKUP ADD CONSTRAINT TTLKP_ACTID_FK FOREIGN KEY (ACCOUNT_TYPE_ID)
	  REFERENCES ACCOUNT_TYPE_LOOKUP (ACCOUNT_TYPE_ID) ;
 
ALTER TABLE USER_CONTACT ADD CONSTRAINT USCT_UID_FK FOREIGN KEY (USER_ID)
	  REFERENCES USERS (USER_ID) ;
 
ALTER TABLE LOAN_COUPON_BOOK ADD CONSTRAINT LCB_LACCID_FK FOREIGN KEY (LOAN_ACCOUNT_ID)
	  REFERENCES LOAN_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE LOAN_MAINTENANCE_LOG ADD CONSTRAINT LML_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES LOAN_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE LOAN_MAINTENANCE_LOG ADD CONSTRAINT LML_EID_FK FOREIGN KEY (ENTITY_ID)
	  REFERENCES ENTITY (ENTITY_ID) ;
 
ALTER TABLE LOAN_MESSAGES ADD CONSTRAINT LM_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES LOAN_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE LOAN_MESSAGES ADD CONSTRAINT LM_MTID_FK FOREIGN KEY (MESSAGE_TYPE_ID)
	  REFERENCES MESSAGE_TYPE_LOOKUP (MESSAGE_TYPE_ID) ;
 
ALTER TABLE LOAN_MESSAGES ADD CONSTRAINT LM_UID_FK FOREIGN KEY (USER_ID)
	  REFERENCES USERS (USER_ID) ;
 
ALTER TABLE LOAN_NON_ACCRUAL ADD CONSTRAINT LOAN_NON_ACCRUAL_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES LOAN_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE LOAN_TRANS_CODE_LOOKUP ADD CONSTRAINT TCLKP_ACTID_FK FOREIGN KEY (ACCOUNT_TYPE_ID)
	  REFERENCES ACCOUNT_TYPE_LOOKUP (ACCOUNT_TYPE_ID) ;
 
ALTER TABLE MATURITY_PERIOD ADD CONSTRAINT MATURITY_PERIOD_INSTID_FK FOREIGN KEY (INSTITUTION_ID)
	  REFERENCES INSTITUTION (INSTITUTION_ID) ;
 
ALTER TABLE NSF_OD_DAU_CHARGE_PARAMETER ADD CONSTRAINT NODCP_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES DEPOSIT_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE NSF_OD_DAU_HISTORY ADD CONSTRAINT NODH_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES DEPOSIT_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE OD_PROTECTION_OPTION ADD CONSTRAINT OPO_OPPID_FK FOREIGN KEY (OD_PROTECTION_PLAN_ID)
	  REFERENCES OD_PROTECTION_PLAN (OD_PROTECTION_PLAN_ID) ;
 
ALTER TABLE ROLE_RESOURCE_ACTION_CONDITION ADD CONSTRAINT RLRSACCON_RID_RSID_AID_FK FOREIGN KEY (ROLE_ID, RESOURCE_ID, ACTION_ID)
	  REFERENCES ROLE_RESOURCE_ACTION (ROLE_ID, RESOURCE_ID, ACTION_ID) ;
 
ALTER TABLE SAVINGS_PLAN_CONTR_CONFIG ADD CONSTRAINT SAV_PLAN_CONTR_CONFIG_SPTID_FK FOREIGN KEY (SAVINGS_PLAN_TYPE_ID)
	  REFERENCES SAVINGS_PLAN_TYPE (UNIQUE_ID) ;
 
ALTER TABLE SAVINGS_PLAN_DIST_SEQ ADD CONSTRAINT SPDS_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES DEPOSIT_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE SAVINGS_PLAN_MOD_APPLICATION ADD CONSTRAINT SAV_PLAN_MOD_APP_APID_FK FOREIGN KEY (APPLICATION_ID)
	  REFERENCES ACCOUNT_APPLICATION (UNIQUE_ID);
 
ALTER TABLE SAVING_PLAN_MAINTENANCE_LOG ADD CONSTRAINT SAVPLAN_MAINT_LOG_EID_FK FOREIGN KEY (ENTRY_ID)
	  REFERENCES MAINTENANCE_LOG (ENTRY_ID) ;
 
ALTER TABLE SAVING_PLAN_MAINTENANCE_LOG ADD CONSTRAINT SAVPLAN_MAINT_LOG_PID_FK FOREIGN KEY (PLAN_ID)
	  REFERENCES SAVINGS_PLAN_DETAILS (PLAN_ID) ;
 
ALTER TABLE SAV_PLAN_PARTY_ROLES_APPL ADD CONSTRAINT SAVPLAN_PARTYROLESAPP_AID_FK FOREIGN KEY (APPLICATION_ID)
	  REFERENCES PARTY_ROLES_APPLICATION (APPLICATION_ID);
 
ALTER TABLE SAV_POTENTIAL_EVENT ADD CONSTRAINT SPE_POT_EVE_ID_FK FOREIGN KEY (POT_DEPOSIT_EVENT_ID)
	  REFERENCES POTENTIAL_DEPOSIT_EVENT (UNIQUE_ID) ;
 
ALTER TABLE SCANNED_FORM ADD CONSTRAINT SCANNED_FORM_APFUID_FK FOREIGN KEY (APPL_PRODUCT_FORM_ID)
	  REFERENCES APPL_PRODUCT_FORM (APPL_PRODUCT_FORM_ID);
 
ALTER TABLE SERVICE_CHARGE ADD CONSTRAINT SERVCHRG_IID_FK FOREIGN KEY (INSTITUTION_ID)
	  REFERENCES INSTITUTION (INSTITUTION_ID) ;
 
ALTER TABLE SERVICE_CHARGE_TIER ADD CONSTRAINT SERVCHRGTIER_SC_FK FOREIGN KEY (SERVICE_CHARGE_CODE)
	  REFERENCES SERVICE_CHARGE (UNIQUE_ID) ;
 
ALTER TABLE SOCIAL_CREDENTIAL_REPORT ADD CONSTRAINT SOC_CRED_REP_UASSID_FK FOREIGN KEY (UNIQUE_ASSOCIATION_ID)
	  REFERENCES PARTY_ASSOC_SOC_CREDENTIAL (UNIQUE_ASSOCIATION_ID) ;
 
ALTER TABLE STATUS_LOOKUP ADD CONSTRAINT SLKP_IID_FK FOREIGN KEY (INSTITUTION_ID)
	  REFERENCES INSTITUTION (INSTITUTION_ID) ;
 
ALTER TABLE STATUS_LOOKUP ADD CONSTRAINT SLKP_ATID_FK FOREIGN KEY (ACCOUNT_TYPE_ID)
	  REFERENCES ACCOUNT_TYPE_LOOKUP (ACCOUNT_TYPE_ID) ;
 
ALTER TABLE COLLATERAL_UCCEXPIRATION_DATE ADD CONSTRAINT COLL_UCCEXP_CID_FK FOREIGN KEY (COLLATERAL_ID)
	  REFERENCES COLLATERAL (COLLATERAL_ID) ;
 
ALTER TABLE CUSTOMER ADD CONSTRAINT CUST_PID_FK FOREIGN KEY (PARTY_ID)
	  REFERENCES PARTY (PARTY_ID) ;
 
ALTER TABLE CUSTOMER ADD CONSTRAINT CUST_IID_FK FOREIGN KEY (INSTITUTION_ID)
	  REFERENCES INSTITUTION (INSTITUTION_ID) ;
 
ALTER TABLE CUSTOMER ADD CONSTRAINT CUST_CTID_FK FOREIGN KEY (CUSTOMER_TYPE_ID)
	  REFERENCES CUSTOMER_TYPE_LOOKUP (CUSTOMER_TYPE_ID) ;
 
ALTER TABLE CUSTOMER ADD CONSTRAINT CUST_GID_FK FOREIGN KEY (GROUP_ID)
	  REFERENCES CUSTOMER_GROUP (GROUP_ID) ;
 
ALTER TABLE CUSTOMER_CONTACT ADD CONSTRAINT CUSTCC_ATID_FK FOREIGN KEY (ADDRESS_TYPE_ID)
	  REFERENCES ADDRESS_TYPE_LOOKUP (ADDRESS_TYPE_ID) ;
 
ALTER TABLE DEPOSIT_ACCOUNT_BALANCES ADD CONSTRAINT DAB_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES DEPOSIT_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE DEPOSIT_ACCOUNT_INTEREST ADD CONSTRAINT DAI_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES DEPOSIT_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE DEPOSIT_ACCOUNT_OWNERS ADD CONSTRAINT DAO_ACID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES DEPOSIT_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE DEPOSIT_EVENT ADD CONSTRAINT DEP_EVENT_ID_FK FOREIGN KEY (EVENT_ID)
	  REFERENCES EVENT (EVENT_ID) ;
 
ALTER TABLE ELIGIBILITY_QUESTION_ANSWER ADD CONSTRAINT ELIGI_QUEST_ANS_FK FOREIGN KEY (QUESTIONS_ID)
	  REFERENCES ELIGIBILITY_QUESTION (UNIQUE_ID) ;
 
ALTER TABLE ELIGIBILITY_TEMPLATE_QUESTION ADD CONSTRAINT ELIGI_TEMPL_QUEST_FK FOREIGN KEY (ELIGIBILITY_REVIEW_TEMPLATE_ID)
	  REFERENCES ELIGIBILITY_REVIEW_TEMPLATE (UNIQUE_ID) ;
 
ALTER TABLE ELIGIBILITY_TEMPLATE_QUESTION ADD CONSTRAINT ELIGI_TEMPL_QUEST_QUESTID_FK FOREIGN KEY (QUESTION_ID)
	  REFERENCES ELIGIBILITY_QUESTION (UNIQUE_ID) ;
 
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMP_BID_IID_FK FOREIGN KEY (BRANCH_ID)
	  REFERENCES BRANCH (UNIQUE_ID) ;
 
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMP_UID_FK FOREIGN KEY (USER_ID)
	  REFERENCES USERS (USER_ID) ;
 
ALTER TABLE EVENT ADD CONSTRAINT EVENT_BRANCH_ID_FK FOREIGN KEY (BRANCH_ID)
	  REFERENCES BRANCH (UNIQUE_ID) ;
 
ALTER TABLE EXCEPTIONS_ITEM ADD CONSTRAINT EI_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES DEPOSIT_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE EXCESS_CASH_MANAGEMENT ADD CONSTRAINT ECM_SACCID_FK FOREIGN KEY (SOURCE_ACCOUNT_ID)
	  REFERENCES DEPOSIT_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE EXCESS_CASH_MANAGEMENT ADD CONSTRAINT ECM_DACCID_FK FOREIGN KEY (DEST_ACCOUNT_ID)
	  REFERENCES DEPOSIT_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE DEPOSIT_ACCOUNT ADD CONSTRAINT DA_UID_FK FOREIGN KEY (USER_ID)
	  REFERENCES USERS (USER_ID) ;
 
ALTER TABLE DEPOSIT_ACCOUNT ADD CONSTRAINT DA_BID_FK FOREIGN KEY (BRANCH_ID)
	  REFERENCES BRANCH (UNIQUE_ID) ;
 
ALTER TABLE DEPOSIT_ACCOUNT ADD CONSTRAINT DA_PID_FK FOREIGN KEY (PENALTY_ID)
	  REFERENCES PENALTY_PARAMETER (PENALTY_ID) ;
 
ALTER TABLE DEPOSIT_ACCOUNT ADD CONSTRAINT DA_PLANID_FK FOREIGN KEY (PLAN_ID)
	  REFERENCES SAVINGS_PLAN_DETAILS (PLAN_ID) ;
 
ALTER TABLE DEPOSIT_ACCOUNT ADD CONSTRAINT DA_ODCODE_FK FOREIGN KEY (OVERDRAFT_CODE)
	  REFERENCES OVERDRAFT_LOOKUP (OVERDRAFT_CODE) ;
 
ALTER TABLE DEPOSIT_ACCOUNT ADD CONSTRAINT DA_CONFSTMTFLAG_FK FOREIGN KEY (CONF_STMT_FLAG)
	  REFERENCES CONF_STMT_FLAG_LOOKUP (CONF_STMT_FLAG) ;
 
ALTER TABLE DEPOSIT_ACCOUNT ADD CONSTRAINT DA_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES ACCOUNT (ACCOUNT_ID);
 
ALTER TABLE DEPOSIT_ACCOUNT ADD CONSTRAINT DA_CRC_FK FOREIGN KEY (CALL_REPORT_CODE)
	  REFERENCES CALL_REPORT_LKP (CALL_REPORT_CODE) ;
 
ALTER TABLE DEPOSIT_ACCOUNT ADD CONSTRAINT DA_ASSBR_FK FOREIGN KEY (ASSIGNED_BRANCH)
	  REFERENCES BRANCH (UNIQUE_ID) ;
 
ALTER TABLE DEPOSIT_ACCOUNT ADD CONSTRAINT DA_CC_FK FOREIGN KEY (CLASS_CODE)
	  REFERENCES INST_PROD_CAT_CLASS_CODE (UNIQUE_ID) ;
 
ALTER TABLE DEPOSIT_ACCOUNT ADD CONSTRAINT DA_SCC_FK FOREIGN KEY (SERVICE_CHARGE_CODE)
	  REFERENCES SERVICE_CHARGE (UNIQUE_ID) ;
 
ALTER TABLE DEPOSIT_ACCOUNT_TRANSACTIONS ADD CONSTRAINT DAT_ACID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES DEPOSIT_ACCOUNT (ACCOUNT_ID);
 
ALTER TABLE DEPOSIT_ACCOUNT_TRANSACTIONS ADD CONSTRAINT DAT_UID_FK FOREIGN KEY (USER_ID)
	  REFERENCES USERS (USER_ID) ;
 
ALTER TABLE DEPOSIT_ACCOUNT_TRANSACTIONS ADD CONSTRAINT DAT_BID_IID_FK FOREIGN KEY (BRANCH_ID)
	  REFERENCES BRANCH (UNIQUE_ID) ;
 
ALTER TABLE ACCOUNT_HISTORY_ITEM ADD CONSTRAINT AHI_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES DEPOSIT_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE ACCOUNT_HISTORY_ITEM ADD CONSTRAINT ACC_HIS_ITEM_EVENTID_FK FOREIGN KEY (EVENT_ID)
	  REFERENCES EVENT (EVENT_ID) ;
 
ALTER TABLE SAVINGS_PLAN_DETAILS ADD CONSTRAINT SPDET_SPTID_FK FOREIGN KEY (SAVINGS_PLAN_TYPE_ID)
	  REFERENCES SAVINGS_PLAN_TYPE (UNIQUE_ID) ;
 
ALTER TABLE TAX_INTEREST_DETAILS ADD CONSTRAINT TID_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES DEPOSIT_ACCOUNT (ACCOUNT_ID);
 
ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT LA_LCC_FK FOREIGN KEY (LATE_CHARGE_CODE)
	  REFERENCES LATE_CHARGE (LATE_CHARGE_CODE) ;
 
ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT LA_CRC_FK FOREIGN KEY (CALL_REPORT_CODE)
	  REFERENCES LOAN_CALL_REPORT_LKP (CALL_REPORT_CODE) ;
 
ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT LA_RM_FK FOREIGN KEY (REPAYMENT_MODE)
	  REFERENCES REPAYMENT_MODE_LKP (REPAYMENT_MODE) ;
 
ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT LA_OB_FK FOREIGN KEY (OPENING_BRANCH)
	  REFERENCES BRANCH (UNIQUE_ID) ;
 
ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT LA_LOCI_FK FOREIGN KEY (LINE_OF_CREDIT_ID)
	  REFERENCES CREDIT_LINE (LINE_OF_CREDIT_ID) ;
 
ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT LA_INTEREST_BASE_CODE_FK FOREIGN KEY (INTEREST_BASE_CODE)
	  REFERENCES INTEREST_BASE_LOOKUP (INTEREST_BASE_CODE) ;
 
ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT LA_FP_FK FOREIGN KEY (FREQUENCY_PRINCIPAL)
	  REFERENCES LOAN_FREQUENCY_LOOKUP (CODE) ;
 
ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT LA_FI_FK FOREIGN KEY (FREQUENCY_INTEREST)
	  REFERENCES LOAN_FREQUENCY_LOOKUP (CODE) ;
 
ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT LA_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT LA_CC_FK FOREIGN KEY (CLASS_CODE)
	  REFERENCES LOAN_TYPE_LOOKUP (CLASS_CODE) ;
 
ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT LN_TYPE_ID_FK FOREIGN KEY (LOAN_TYPE_ID)
	  REFERENCES LOAN_TYPE_PARAMETER (LOAN_TYPE_ID) ;
 
ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT LA_EACID_FK FOREIGN KEY (ESCROW_ACCOUNT_ID)
	  REFERENCES ESCROW_ACCOUNT (ESCROW_ACCOUNT_ID) ;
 
ALTER TABLE ESCROW_TRANSACTION ADD CONSTRAINT ET_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES LOAN_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE ESCROW_TRANSACTION ADD CONSTRAINT ET_ACTID_FK FOREIGN KEY (ACCOUNT_TYPE_ID)
	  REFERENCES ACCOUNT_TYPE_LOOKUP (ACCOUNT_TYPE_ID) ;
 
ALTER TABLE ESCROW_TRANSACTION ADD CONSTRAINT ET_EACCID_FK FOREIGN KEY (ESCROW_ACCOUNT_ID)
	  REFERENCES ESCROW_ACCOUNT (ESCROW_ACCOUNT_ID) ;
 
ALTER TABLE LOAN_ACCOUNT_TRANSACTION ADD CONSTRAINT LAT_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES LOAN_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE LOAN_ACCOUNT_TRANSACTION ADD CONSTRAINT LAT_ETID_FK FOREIGN KEY (ESCROW_TRANSACTION_ID)
	  REFERENCES ESCROW_TRANSACTION (TRANSACTION_ID) ;
 
ALTER TABLE LOAN_ACCOUNT_TRANSACTION ADD CONSTRAINT LAT_ACTID_FK FOREIGN KEY (ACCOUNT_TYPE_ID)
	  REFERENCES ACCOUNT_TYPE_LOOKUP (ACCOUNT_TYPE_ID) ;
 
ALTER TABLE VARIABLE_INTEREST_RATE ADD CONSTRAINT VIR_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES LOAN_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE TRANSACTION_BILL_ALLOCATION ADD CONSTRAINT TBA_TID_FK FOREIGN KEY (TRANSACTION_ID)
	  REFERENCES LOAN_ACCOUNT_TRANSACTION (TRANSACTION_ID) ON DELETE SET NULL ;
 
ALTER TABLE RENEWALS ADD CONSTRAINT REN_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES LOAN_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE EXTENSIONS ADD CONSTRAINT EXT_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES LOAN_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE ESCROW_HEAD ADD CONSTRAINT EH_GID_FK FOREIGN KEY (GRANTEE_ID)
	  REFERENCES ESCROW_GRANTEE (GRANTEE_ID) ;
 
ALTER TABLE ESCROW_HEAD ADD CONSTRAINT EH_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES LOAN_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE ESCROW_HEAD ADD CONSTRAINT EH_IID_FK FOREIGN KEY (CUSTODIAN_ID)
	  REFERENCES INSTITUTION (INSTITUTION_ID) ;
 
ALTER TABLE ESCROW_HEAD ADD CONSTRAINT EH_EACCID_FK FOREIGN KEY (ESCROW_ACCOUNT_ID)
	  REFERENCES ESCROW_ACCOUNT (ESCROW_ACCOUNT_ID) ;
 
ALTER TABLE COLLATERAL ADD CONSTRAINT COLLATERAL_CID_FK FOREIGN KEY (COLLATERAL_ID)
	  REFERENCES ASSET (ASSET_ID) ;
 
ALTER TABLE COLLATERAL ADD CONSTRAINT COLLATERAL_COLL_TYPE_FK FOREIGN KEY (COLLATERAL_TYPE)
	  REFERENCES COLLATERAL_TYPE_LOOKUP (COLLATERAL_TYPE) ;
 
ALTER TABLE LOANACCOUNT_COLLATERAL_MAPPING ADD CONSTRAINT LACOLLMAP_CID_FK FOREIGN KEY (COLLATERAL_ID)
	  REFERENCES COLLATERAL (COLLATERAL_ID) ;
 
ALTER TABLE LOANACCOUNT_COLLATERAL_MAPPING ADD CONSTRAINT LACOLLMAP_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES LOAN_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE COLLATERAL_APPRAISAL ADD CONSTRAINT CAPP_CID_FK FOREIGN KEY (COLLATERAL_ID)
	  REFERENCES COLLATERAL (COLLATERAL_ID) ;
 
ALTER TABLE PROPERTY_COLLATERAL ADD CONSTRAINT PPTYCOLL_CID_FK FOREIGN KEY (COLLATERAL_ID)
	  REFERENCES COLLATERAL (COLLATERAL_ID) ;
 
ALTER TABLE ESCROW_DUES ADD CONSTRAINT ED_EHID_FK FOREIGN KEY (ESCROW_HEAD_ID)
	  REFERENCES ESCROW_HEAD (ESCROW_HEAD_ID) ;
 
ALTER TABLE TAX_WH_ON_INTEREST_PLAN ADD CONSTRAINT TWIP_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES DEPOSIT_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE LOAN_ACCOUNT_REBATE ADD CONSTRAINT LACCREBATE_LACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES LOAN_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE LOAN_ACCOUNT_REBATE ADD CONSTRAINT LACCREBATE_PARTYID_FK FOREIGN KEY (PARTY_ID)
	  REFERENCES PARTY (PARTY_ID) ;
 
ALTER TABLE SAVINGS_PLAN_TRANSACTIONS ADD CONSTRAINT SPT_TID_FK FOREIGN KEY (TRANSACTION_ID)
	  REFERENCES ACCOUNT_HISTORY_ITEM (TRANSACTION_ID) ON DELETE SET NULL ;
 
ALTER TABLE ACCOUNT ADD CONSTRAINT ACCOUNT_PRODID_FK FOREIGN KEY (PRODUCT_ID)
	  REFERENCES PRODUCT_TYPE (UNIQUE_ID);
 
ALTER TABLE ACCOUNT ADD CONSTRAINT ACCOUNT_ACCTID_FK FOREIGN KEY (ACCOUNT_TYPE_ID)
	  REFERENCES ACCOUNT_TYPE_LOOKUP (ACCOUNT_TYPE_ID) ;
 
ALTER TABLE DEPOSIT_ACCOUNT_INSTRUCTION ADD CONSTRAINT DA_ACCT_INSTRU_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES ACCOUNT (ACCOUNT_ID);
 
ALTER TABLE STOP_PAYMENT_INSTRUCTION ADD CONSTRAINT SPI_SIT_FK FOREIGN KEY (STOP_INSTRUCTION_TYPE)
	  REFERENCES STOP_TYPE_LOOKUP (UNIQUE_ID) ;
 
ALTER TABLE STOP_PAYMENT_INSTRUCTION ADD CONSTRAINT STOP_INSTRUID_FK FOREIGN KEY (INSTRUCTION_ID)
	  REFERENCES DEPOSIT_ACCOUNT_INSTRUCTION (INSTRUCTION_ID);
 
ALTER TABLE LOAN_BILLS_LTD ADD CONSTRAINT LOAN_BILLS_LTD_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES LOAN_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE HOLD_PAYMENT ADD CONSTRAINT HOLD_PAY_INSTRUCTIONID_FK FOREIGN KEY (INSTRUCTION_ID)
	  REFERENCES DEPOSIT_ACCOUNT_INSTRUCTION (INSTRUCTION_ID) ;
 
ALTER TABLE AUTOMATIC_TRANSFER_INSTRUCTION ADD CONSTRAINT AT_SRC_ACC FOREIGN KEY (SOURCE_ACCOUNT)
	  REFERENCES ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE AUTOMATIC_TRANSFER_INSTRUCTION ADD CONSTRAINT AT_TARGET_ACC FOREIGN KEY (TARGET_ACCOUNT)
	  REFERENCES ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE ORGANIZATION ADD CONSTRAINT ORGANIZATION_PID_FK FOREIGN KEY (PARTY_ID)
	  REFERENCES PARTY (PARTY_ID) ;
 
ALTER TABLE OD_PROTECTION_PLAN ADD CONSTRAINT OPP_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES DEPOSIT_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE OVERDRAFT_TRANSFER_OPTIONS ADD CONSTRAINT OTO_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES DEPOSIT_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE PARTICIPATING_ACCOUNT ADD CONSTRAINT PARTACC_DACCID_FK FOREIGN KEY (DEPOSIT_ACCOUNT_ID)
	  REFERENCES DEPOSIT_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE PARTICIPATING_ACCOUNT ADD CONSTRAINT PARTACC_PID_FK FOREIGN KEY (PARTICIPANT_ID)
	  REFERENCES PARTICIPANT (PARTICIPANT_ID) ;
 
ALTER TABLE PARTICIPATING_ACCOUNT ADD CONSTRAINT PARTACC_LACCID_FK FOREIGN KEY (LOAN_ACCOUNT_ID)
	  REFERENCES LOAN_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE PARTICIPATING_TRANSACTION ADD CONSTRAINT PARTTRAN_PACCID_FK FOREIGN KEY (PARTICIPATING_ACCOUNT_ID)
	  REFERENCES PARTICIPATING_ACCOUNT (PARTICIPATING_ACCOUNT_ID) ;
 
ALTER TABLE PARTICIPATING_TRANSACTION ADD CONSTRAINT PARTTRAN_ACTID_FK FOREIGN KEY (ACCOUNT_TYPE_ID)
	  REFERENCES ACCOUNT_TYPE_LOOKUP (ACCOUNT_TYPE_ID) ;
 
ALTER TABLE PARTY_ACCOUNT_ROLE ADD CONSTRAINT P_ACC_ROLE_ACID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES ACCOUNT (ACCOUNT_ID);
 
ALTER TABLE PARTY_ACCOUNT_ROLE ADD CONSTRAINT PARTY_ACCT_ROLE_UPRID_FK FOREIGN KEY (UNIQUE_PARTY_ROLE_ID)
	  REFERENCES PARTY_ROLE (UNIQUE_PARTY_ROLE_ID) ;
 
ALTER TABLE PARTY_ACCOUNT_ROLES ADD CONSTRAINT PARTYACCROLES_UAID_FK FOREIGN KEY (UNIQUE_ASSOCIATION_ID)
	  REFERENCES PARTY_INSTITUTION_ASSOCIATION (UNIQUE_ASSOCIATION_ID) ;
 
ALTER TABLE PARTY_ACCOUNT_ROLES ADD CONSTRAINT PARTYACCROLES_RID_FK FOREIGN KEY (ROLE_ID)
	  REFERENCES PARTY_ROLE_TYPE (ROLE_TYPE_ID) ;
 
ALTER TABLE PARTY_ACCOUNT_ROLES ADD CONSTRAINT PARTYACCROLES_AID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE PARTY_ADDRESS ADD CONSTRAINT PARTYADDR_PARTYID_FK FOREIGN KEY (PARTY_ID)
	  REFERENCES PARTY (PARTY_ID) ;
 
ALTER TABLE PARTY_ALIASES ADD CONSTRAINT PARTY_ALIASES_PID_FK FOREIGN KEY (PARTY_ID)
	  REFERENCES PARTY (PARTY_ID) ;
 
ALTER TABLE PARTY_APPLICANT_ROLE ADD CONSTRAINT P_APPL_ROLE_UAPPID_FK FOREIGN KEY (UNIQUE_APPLICATION_ID)
	  REFERENCES APPLICATION (APPLICATION_ID);
 
ALTER TABLE PARTY_APPLICANT_ROLE ADD CONSTRAINT P_APPL_ROLE_UPRID_FK FOREIGN KEY (UNIQUE_PARTY_ROLE_ID)
	  REFERENCES PARTY_ROLE (UNIQUE_PARTY_ROLE_ID) ;
 
ALTER TABLE PARTY_ASSOC_FIN_CREDENTIAL ADD CONSTRAINT ASSOC_FIN_CRED_ASSOC_ID_FK FOREIGN KEY (UNIQUE_ASSOCIATION_ID)
	  REFERENCES PARTY_INSTITUTION_ASSOCIATION (UNIQUE_ASSOCIATION_ID) ;
 
ALTER TABLE PARTY_ASSOC_MAINTENANCE_LOG ADD CONSTRAINT PARTYASSOC_MAINT_EID_FK FOREIGN KEY (ENTRY_ID)
	  REFERENCES MAINTENANCE_LOG (ENTRY_ID) ;
 
ALTER TABLE PARTY_ASSOC_MAINTENANCE_LOG ADD CONSTRAINT PARTYASSOC_MAINT_LOG_EID_FK FOREIGN KEY (UNIQUE_ASSOCIATION_ID)
	  REFERENCES PARTY_INSTITUTION_ASSOCIATION (UNIQUE_ASSOCIATION_ID) ;
 
ALTER TABLE PARTY_ASSOC_SOC_CREDENTIAL ADD CONSTRAINT ASSOC_SOC_CRED_ASSOC_ID_FK FOREIGN KEY (UNIQUE_ASSOCIATION_ID)
	  REFERENCES PARTY_INSTITUTION_ASSOCIATION (UNIQUE_ASSOCIATION_ID) ;
 
ALTER TABLE PARTY_IDENTITY_PROOF ADD CONSTRAINT PARTY_IDPROOF_PID_FK FOREIGN KEY (PARTY_ID)
	  REFERENCES PARTY (PARTY_ID) ;
 
ALTER TABLE PARTY_IDENTITY_PROOF ADD CONSTRAINT PARTY_IDPROOF_PRID_FK FOREIGN KEY (PARTY_REGISTERD_ID)
	  REFERENCES PARTY_REGISTERED_IDS (ID) ;
 
ALTER TABLE PARTY_IDENTITY_PROOF ADD CONSTRAINT PARTY_IDPROOF_PROOFID_FK FOREIGN KEY (PROOF_ID)
	  REFERENCES IDENTITY_PROOF (PROOF_ID) ;
 
ALTER TABLE POTENTIAL_PLAN_EVENT_SOURCE ADD CONSTRAINT POTENTIAL_PLAN_EVT_SRC_UID_FK FOREIGN KEY (UNIQUE_ID)
	  REFERENCES POTENTIAL_EVENT_SOURCE (UNIQUE_ID) ;
 
ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_PTID_FK FOREIGN KEY (PRODUCT_TYPE_ID)
	  REFERENCES PRODUCT_TYPE (UNIQUE_ID);
 
ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_PSTID FOREIGN KEY (PROD_SUB_TYPE_ID)
	  REFERENCES INST_PROD_CAT_CLASS_CODE (UNIQUE_ID) ;
 
ALTER TABLE PRODUCT_FEATURE ADD CONSTRAINT PROD_FEATURE_PUID_FK FOREIGN KEY (PRODUCT_UID)
	  REFERENCES PRODUCT (PRODUCT_UID);
 
ALTER TABLE PRODUCT_FEATURE ADD CONSTRAINT PROD_FEATURE_FUID_FK FOREIGN KEY (FEATURE_UID)
	  REFERENCES FEATURE (FEATURE_UID);
 
ALTER TABLE PRODUCT_FEATURE_INSTANCE ADD CONSTRAINT PROD_FEATURE_INST_PFUID_FK FOREIGN KEY (PROD_FEATURE_UID)
	  REFERENCES PRODUCT_FEATURE (PROD_FEATURE_UID);
 
ALTER TABLE PRODUCT_FEATURE_INSTANCE ADD CONSTRAINT PROD_FEATURE_INST_APUID_FK FOREIGN KEY (APPL_PRODUCT_UID)
	  REFERENCES APPL_PRODUCT (UNIQUE_ID);
 
ALTER TABLE PRODUCT_FORM_TEMPLATE ADD CONSTRAINT PRODUCT_FORM_TEMPLATE_UFID_FK FOREIGN KEY (UNIQUE_FORM_ID)
	  REFERENCES FORM_TEMPLATE (UNIQUE_FORM_ID) ;
 
ALTER TABLE PRODUCT_FORM_TEMPLATE ADD CONSTRAINT PRODUCT_FORM_TEMPLATE_PUID_FK FOREIGN KEY (PRODUCT_UID)
	  REFERENCES PRODUCT (PRODUCT_UID);
 
ALTER TABLE PRODUCT_QUES ADD CONSTRAINT PROD_QUES_QID_FK FOREIGN KEY (QUESTION_ID)
	  REFERENCES QUESTION (QUESTION_ID) ;
 
ALTER TABLE PRODUCT_QUES ADD CONSTRAINT PROD_QUES_PUID_FK FOREIGN KEY (PRODUCT_UID)
	  REFERENCES PRODUCT (PRODUCT_UID) ;
 
ALTER TABLE PRODUCT_TYPE ADD CONSTRAINT PRODUCT_TYPE_IID_FK FOREIGN KEY (INSTITUTION_ID)
	  REFERENCES INSTITUTION (INSTITUTION_ID) ;
 
ALTER TABLE PROD_QUES_ANS_SCORE ADD CONSTRAINT PROD_QUES_ANS_SCORE_PQID_FK FOREIGN KEY (PRODUCT_QUES_ID)
	  REFERENCES PROD_QUES_IDS (PROD_QUES_ID) ;
 
ALTER TABLE PROD_QUES_ANS_SCORE ADD CONSTRAINT PROD_QUES_ANS_SCORE_AID_FK FOREIGN KEY (ANSWER_ID)
	  REFERENCES ANSWER (UNIQUE_ID) ;
 
ALTER TABLE PROD_QUES_IDS ADD CONSTRAINT PROD_QUES_IDS_PQID_FK FOREIGN KEY (PROD_QUES_ID)
	  REFERENCES PRODUCT_QUES (PROD_QUES_ID) ;
 
ALTER TABLE RESOURCE_ACTION ADD CONSTRAINT RESAC_RID_FK FOREIGN KEY (RESOURCE_ID)
	  REFERENCES RESOURCE_MASTER (RESOURCE_ID) ;
 
ALTER TABLE RESOURCE_ACTION ADD CONSTRAINT RESAC_ACID_FK FOREIGN KEY (ACTION_ID)
	  REFERENCES ACTION_MASTER (ACTION_ID) ;
 
ALTER TABLE RESOURCE_ACTION_POLICY ADD CONSTRAINT RESACP_RID_AID_FK FOREIGN KEY (RESOURCE_ID, ACTION_ID)
	  REFERENCES RESOURCE_ACTION (RESOURCE_ID, ACTION_ID) ;
 
ALTER TABLE RESOURCE_ACTION_POLICY ADD CONSTRAINT RESACP_PID FOREIGN KEY (POLICY_ID)
	  REFERENCES POLICY_MASTER (POLICY_ID) ;
 
ALTER TABLE RESPONSIBILITY_LIABILITY ADD CONSTRAINT RESP_LIAB_IID_FK FOREIGN KEY (INSTITUTION_ID)
	  REFERENCES INSTITUTION (INSTITUTION_ID) ;
 
ALTER TABLE RESPONSIBILITY_LIABILITY ADD CONSTRAINT RESP_LIAB_PID_FK FOREIGN KEY (PARTY_ID)
	  REFERENCES PARTY (PARTY_ID) ;
 
ALTER TABLE RESPONSIBILITY_LIABILITY ADD CONSTRAINT RESP_LIAB_ASID_FK FOREIGN KEY (ASSOCIATE_ID)
	  REFERENCES ASSOCIATE (ASSOCIATE_ID) ;
 
ALTER TABLE RESPONSIBILITY_LIABILITY ADD CONSTRAINT RESP_LIAB_LBTID_FK FOREIGN KEY (LIABILITY_TYPE_ID)
	  REFERENCES LIABILITY_TYPE_LKP (LIABILITY_TYPE_ID) ;
 
ALTER TABLE RISK_ASSESSMENT ADD CONSTRAINT RISK_ASSE_APID_FK FOREIGN KEY (APPL_PROD_ID)
	  REFERENCES APPL_PRODUCT (UNIQUE_ID) ;
 
ALTER TABLE RISK_ASSESSMENT_LINK ADD CONSTRAINT RISK_ASS_LINK_RAV_FK FOREIGN KEY (RISK_ASS_VALUE)
	  REFERENCES RISK_ASSESSMENT (RISK_ASS_ID) ;
 
ALTER TABLE RISK_ASSESSMENT_LINK ADD CONSTRAINT RISK_ASS_LINK_APID_FK FOREIGN KEY (APPL_PROD_ID)
	  REFERENCES APPL_PRODUCT (UNIQUE_ID) ;
 
ALTER TABLE RISK_ASS_QUES_ANS ADD CONSTRAINT RISK_ASS_QA_RAID_FK FOREIGN KEY (RISK_ASS_ID)
	  REFERENCES RISK_ASSESSMENT (RISK_ASS_ID) ;
 
ALTER TABLE RISK_ASS_QUES_ANS ADD CONSTRAINT RISK_ASS_QA_QID_FK FOREIGN KEY (QUESTION_ID)
	  REFERENCES QUESTION (QUESTION_ID) ;
 
ALTER TABLE RISK_ASS_QUES_ANS ADD CONSTRAINT RISK_ASS_QA_AID_FK FOREIGN KEY (ANSWER_ID)
	  REFERENCES ANSWER (UNIQUE_ID) ;
 
ALTER TABLE ROLE_LOOKUP ADD CONSTRAINT RLKP_ITID_FK FOREIGN KEY (INSTITUTION_TYPE_ID)
	  REFERENCES INSTITUTION_TYPE_LOOKUP (INSTITUTION_TYPE_ID) ;
 
ALTER TABLE ROLE_RESOURCE_ACTION ADD CONSTRAINT RLRSAC_RID_FK FOREIGN KEY (ROLE_ID)
	  REFERENCES ROLE_MASTER (ROLE_ID) ;
 
ALTER TABLE ROLE_RESOURCE_ACTION ADD CONSTRAINT RLRSAC_RSID_AID_FK FOREIGN KEY (RESOURCE_ID, ACTION_ID)
	  REFERENCES RESOURCE_ACTION (RESOURCE_ID, ACTION_ID) ;
 
ALTER TABLE FILTER_RISK_ASSE_QUES ADD CONSTRAINT FIL_RISK_ASS_QUES_RAID_FK FOREIGN KEY (RISK_ASS_ID)
	  REFERENCES RISK_ASSESSMENT (RISK_ASS_ID) ;
 
ALTER TABLE FILTER_RISK_ASSE_QUES ADD CONSTRAINT FIL_RISK_ASS_QUES_QID_FK FOREIGN KEY (QUESTION_ID)
	  REFERENCES QUESTION (QUESTION_ID) ;
 
ALTER TABLE FUNDS_TRANSFER_EVENT ADD CONSTRAINT FT_EVENT_ID_FK FOREIGN KEY (EVENT_ID)
	  REFERENCES EVENT (EVENT_ID) ;
 
ALTER TABLE GUARANTEE ADD CONSTRAINT GUAR_GID_FK FOREIGN KEY (GUARANTOR_ID)
	  REFERENCES ASSOCIATE (ASSOCIATE_ID) ;
 
ALTER TABLE GUARANTEE ADD CONSTRAINT GUAR_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES LOAN_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE INSTITUTION ADD CONSTRAINT IT_ITID_FK FOREIGN KEY (INSTITUTION_TYPE_ID)
	  REFERENCES INSTITUTION_TYPE_LOOKUP (INSTITUTION_TYPE_ID) ;
 
ALTER TABLE INSTITUTION ADD CONSTRAINT INST_FRABA_ID_FK FOREIGN KEY (FRABA_ID)
	  REFERENCES FRABA (FRABA_ID);
 
ALTER TABLE INSTITUTION_ACCT_TRAN_TYPES ADD CONSTRAINT INST_ACC_TRAN_TYPES_TCID_FK FOREIGN KEY (TRANCODE_ID)
	  REFERENCES CORESOFT_TRANCODE_LKP (TRANCODE_ID) ;
 
ALTER TABLE INSTITUTION_ADDRESS ADD CONSTRAINT INST_ADDR_IID FOREIGN KEY (INSTITUTION_ID)
	  REFERENCES INSTITUTION (INSTITUTION_ID) ;
 
ALTER TABLE INSTITUTION_ADDRESS ADD CONSTRAINT INST_ADDR_AID FOREIGN KEY (ADDRESS_ID)
	  REFERENCES ADDRESS (ADDRESS_ID) ;
 
ALTER TABLE INSTITUTION_CONTACT ADD CONSTRAINT IC_IID_FK FOREIGN KEY (INSTITUTION_ID)
	  REFERENCES INSTITUTION (INSTITUTION_ID) ;
 
ALTER TABLE INSTITUTION_CONTACT ADD CONSTRAINT IC_ITID_FK FOREIGN KEY (INSTITUTION_TYPE_ID)
	  REFERENCES INSTITUTION_TYPE_LOOKUP (INSTITUTION_TYPE_ID) ;
 
ALTER TABLE INSTITUTION_CONTACT ADD CONSTRAINT IC_ATID_FK FOREIGN KEY (ADDRESS_TYPE_ID)
	  REFERENCES ADDRESS_TYPE_LOOKUP (ADDRESS_TYPE_ID) ;
 
ALTER TABLE INSTITUTION_GROUP ADD CONSTRAINT IG_IID_FK FOREIGN KEY (INSTITUTION_ID)
	  REFERENCES INSTITUTION (INSTITUTION_ID) ;
 
ALTER TABLE INSTITUTION_GROUP ADD CONSTRAINT IG_CID_FK FOREIGN KEY (CONSORTIUM_ID)
	  REFERENCES INSTITUTION (INSTITUTION_ID) ;
 
ALTER TABLE INSTITUTION_ROLE ADD CONSTRAINT IR_RID_FK FOREIGN KEY (ROLE_ID)
	  REFERENCES ROLE_LOOKUP (ROLE_ID) ;
 
ALTER TABLE INSTITUTION_ROLE ADD CONSTRAINT IR_IID_FK FOREIGN KEY (INSTITUTION_ID)
	  REFERENCES INSTITUTION (INSTITUTION_ID) ;
 
ALTER TABLE INSTITUTION_SAVINGS_PLAN_TYPE ADD CONSTRAINT INST_SAV_PLAN_TYPE_IID_FK FOREIGN KEY (INSTITUTION_ID)
	  REFERENCES INSTITUTION (INSTITUTION_ID) ;
 
ALTER TABLE INSTITUTION_SAVINGS_PLAN_TYPE ADD CONSTRAINT INST_SAV_PLAN_TYPE_SPTYPEID_FK FOREIGN KEY (SAVINGS_PLAN_TYPE_ID)
	  REFERENCES SAVINGS_PLAN_TYPE (UNIQUE_ID) ;
 
ALTER TABLE INSTITUTION_TRANSCODE_LOOKUP ADD CONSTRAINT INST_TRANSCODE_LKP_IID_FK FOREIGN KEY (INSTITUTION_ID)
	  REFERENCES INSTITUTION (INSTITUTION_ID) ;
 
ALTER TABLE INSTITUTION_TRANSCODE_LOOKUP ADD CONSTRAINT INST_TRANSCODE_LKP_ACTID_FK FOREIGN KEY (ACCOUNT_TYPE_ID)
	  REFERENCES ACCOUNT_TYPE_LOOKUP (ACCOUNT_TYPE_ID) ;
 
ALTER TABLE INSTITUTION_INT_CODES ADD CONSTRAINT INST_INT_CODES_ICUID_FK FOREIGN KEY (INTEREST_CODE_HIST_UID)
	  REFERENCES INTEREST_CODES_HISTORY (UNIQUE_ID) ;
 
ALTER TABLE INSTITUTION_INT_CODES ADD CONSTRAINT INST_INT_CODES_IID_FK FOREIGN KEY (INSTITUTION_ID)
	  REFERENCES INSTITUTION (INSTITUTION_ID) ;
 
ALTER TABLE BRANCH_INT_CODES ADD CONSTRAINT BR_INT_CODES_ICUID_FK FOREIGN KEY (INTEREST_CODE_HIST_UID)
	  REFERENCES INTEREST_CODES_HISTORY (UNIQUE_ID) ;
 
ALTER TABLE BRANCH_INT_CODES ADD CONSTRAINT BR_INT_CODES_BID_FK FOREIGN KEY (BRANCH_ID)
	  REFERENCES BRANCH (UNIQUE_ID) ;
 
ALTER TABLE PARTY_PLAN_ROLES ADD CONSTRAINT PARTY_PLAN_ROLES_UPRID_FK FOREIGN KEY (UNIQUE_PARTY_ROLE_ID)
	  REFERENCES PARTY_ROLE (UNIQUE_PARTY_ROLE_ID) ;
 
ALTER TABLE PARTY_PLAN_ROLES ADD CONSTRAINT PARTY_PLAN_ROLES_PID_FK FOREIGN KEY (PLAN_ID)
	  REFERENCES SAVINGS_PLAN_DETAILS (PLAN_ID) ;
 
ALTER TABLE PARTY_REGISTERED_IDS ADD CONSTRAINT PRIDS_PID_FK FOREIGN KEY (PARTY_ID)
	  REFERENCES PARTY (PARTY_ID) ;
 
ALTER TABLE PARTY_ROLE ADD CONSTRAINT PARTY_ROLE_UPRID_FK FOREIGN KEY (ROLE_TYPE_ID)
	  REFERENCES PARTY_ROLE_TYPE (ROLE_TYPE_ID) ;
 
ALTER TABLE PARTY_ROLE ADD CONSTRAINT PARTY_ROLE_UAID_FK FOREIGN KEY (UNIQUE_ASSOCIATION_ID)
	  REFERENCES PARTY_INSTITUTION_ASSOCIATION (UNIQUE_ASSOCIATION_ID) ;
 
ALTER TABLE PARTY_ROLES_APPLICATION ADD CONSTRAINT PARTY_ROLES_APP_APID_FK FOREIGN KEY (APPLICATION_ID)
	  REFERENCES APPLICATION (APPLICATION_ID);
 
ALTER TABLE PAYMENT ADD CONSTRAINT PAYMENT_EVENT_ID_FK FOREIGN KEY (EVENT_ID)
	  REFERENCES EVENT (EVENT_ID) ;
 
ALTER TABLE PAYMENT_METHOD ADD CONSTRAINT PAY_METHOD_PID_FK FOREIGN KEY (PAYMENT_ID)
	  REFERENCES PAYMENT (PAYMENT_ID) ;
 
ALTER TABLE PERIOD_SUMMARY_HISTORY ADD CONSTRAINT PERIOD_SUMM_HIS_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES DEPOSIT_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE PERIOD_SUMMARY_INFO ADD CONSTRAINT PER_SUM_INFO_FK_PS_ENTRY_ID FOREIGN KEY (PERIOD_SUMMARY_ENTRY_ID)
	  REFERENCES PERIOD_SUMMARY_HISTORY (PERIOD_SUMMARY_ENTRY_ID) ;
 
ALTER TABLE PERSON ADD CONSTRAINT PERSON_PID_FK FOREIGN KEY (PARTY_ID)
	  REFERENCES PARTY (PARTY_ID) ;
 
ALTER TABLE PERSONAL_CUSTOMER ADD CONSTRAINT PERCUST_UID_FK FOREIGN KEY (USER_ID)
	  REFERENCES USERS (USER_ID) ;
 
ALTER TABLE PLAN_APPLICABLE_PRODUCTS ADD CONSTRAINT PLAN_APP_PROD_MPUIDFK FOREIGN KEY (MASTER_PRODUCT_UID)
	  REFERENCES PRODUCT (PRODUCT_UID) ;
 
ALTER TABLE PLAN_APPLICABLE_PRODUCTS ADD CONSTRAINT PLAN_APP_PROD_PUIDFK FOREIGN KEY (PRODUCT_UID)
	  REFERENCES PRODUCT (PRODUCT_UID) ;
 
ALTER TABLE POSSIBLE_BENEFICIARY ADD CONSTRAINT POSSIBLE_BENEFICIARY_UPRID_FK FOREIGN KEY (UNIQUE_PARTY_ROLE_ID)
	  REFERENCES POSSIBLE_OWNER (UNIQUE_PARTY_ROLE_ID);
 
ALTER TABLE POSSIBLE_INST_HOLDER ADD CONSTRAINT POSS_INST_HOLD_FK FOREIGN KEY (UNIQUE_PARTY_ROLE_ID)
	  REFERENCES PARTY_ROLE (UNIQUE_PARTY_ROLE_ID) ;
 
ALTER TABLE POSSIBLE_OWNER ADD CONSTRAINT POSSIBLE_OWNER_UPRID_FK FOREIGN KEY (UNIQUE_PARTY_ROLE_ID)
	  REFERENCES PARTY_APPLICANT_ROLE (UNIQUE_PARTY_ROLE_ID);
 
ALTER TABLE POTENTIAL_DEPOSIT_EVENT ADD CONSTRAINT POTENTIAL_DEPO_ELIGI_REV_ID_FK FOREIGN KEY (ELIGIBILITY_REVIEW_REPORT_ID)
	  REFERENCES ELIGIBILITY_REVIEW_REPORT (UNIQUE_ID) ;
 
ALTER TABLE POTENTIAL_DEPOSIT_EVENT ADD CONSTRAINT POTENTIAL_DEPO_EVT_SRC_ID_FK FOREIGN KEY (EVENT_SOURCE_ID)
	  REFERENCES POTENTIAL_EVENT_SOURCE (UNIQUE_ID) ;
 
ALTER TABLE POTENTIAL_DEPOSIT_EVENT ADD CONSTRAINT POTENTIAL_DEPO_EVT_EVTRGID_FK FOREIGN KEY (EVENT_TARGET_ID)
	  REFERENCES POTENTIAL_EVENT_TARGET (UNIQUE_ID) ;
 
ALTER TABLE INSTITUTION_USERS ADD CONSTRAINT IU_RID_FK FOREIGN KEY (ROLE_ID)
	  REFERENCES ROLE_LOOKUP (ROLE_ID) ;
 
ALTER TABLE INSTITUTION_USERS ADD CONSTRAINT IU_IID_FK FOREIGN KEY (INSTITUTION_ID)
	  REFERENCES INSTITUTION (INSTITUTION_ID) ;
 
ALTER TABLE INST_HOLDER ADD CONSTRAINT INST_HOLD_FK FOREIGN KEY (UNIQUE_PARTY_ROLE_ID)
	  REFERENCES PARTY_ROLE (UNIQUE_PARTY_ROLE_ID) ;
 
ALTER TABLE INST_PROD_CAT_CLASS_CODE ADD CONSTRAINT IPROD_CAT_CLS_CODE_IID_FK FOREIGN KEY (INSTITUTION_ID)
	  REFERENCES INSTITUTION (INSTITUTION_ID) ;
 
ALTER TABLE INTERESTED_PARTY ADD CONSTRAINT INTERESTED_PARTY_AOEID_FK FOREIGN KEY (ACC_OPENING_EVENT_ID)
	  REFERENCES ACCOUNT_OPENING_EVENT (UNIQUE_ID) ;
 
ALTER TABLE INTERESTED_PARTY ADD CONSTRAINT INTERESTED_PARTY_UPRID_FK FOREIGN KEY (UNIQUE_PARTY_ROLE_ID)
	  REFERENCES PARTY_ROLE (UNIQUE_PARTY_ROLE_ID) ;
 
ALTER TABLE INTEREST_CODES ADD CONSTRAINT INT_CODES_HIST_UID_FK FOREIGN KEY (INTEREST_CODE_HIST_UID)
	  REFERENCES INTEREST_CODES_HISTORY (UNIQUE_ID) ;
 
ALTER TABLE INTEREST_CODE_RATES ADD CONSTRAINT INT_CODE_RATES_ICUID_FK FOREIGN KEY (INTEREST_CODE_UID)
	  REFERENCES INTEREST_CODES (UNIQUE_ID) ;
 
ALTER TABLE INTEREST_INFO_LAST_12_PERIODS ADD CONSTRAINT IINFOLAST12P_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES DEPOSIT_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE INTEREST_RATE_HISTORY ADD CONSTRAINT IRH_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES LOAN_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE LIQUIDATION_INSTRUCTION ADD CONSTRAINT LIQUID_INSTR_UID_FK FOREIGN KEY (PLAN_EVENT_SOURCE_ID)
	  REFERENCES POTENTIAL_PLAN_EVENT_SOURCE (UNIQUE_ID) ;
 
ALTER TABLE LOAN_ACCOUNT_OWNERS ADD CONSTRAINT LAO_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES LOAN_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE GEOGRAPHIC_ADDRESS ADD CONSTRAINT GEOADDR_ADDRID_FK FOREIGN KEY (ADDRESS_ID)
	  REFERENCES ADDRESS (ADDRESS_ID) ON DELETE SET NULL ;
 
ALTER TABLE ACCOUNT_STATEMENT_ADDRESS ADD CONSTRAINT ACCT_STMT_ADDR_UPADID_FK FOREIGN KEY (UNIQUE_PARTY_ADDRESS_ID)
	  REFERENCES PARTY_ADDRESS (UNIQUE_PARTY_ADDRESS_ID) ;
 
ALTER TABLE ACCOUNT_STATEMENT_GENERATOR ADD CONSTRAINT ASG_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE ACCOUNT_USER_CODE ADD CONSTRAINT ACCUC_ACCID_FK FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES LOAN_ACCOUNT (ACCOUNT_ID) ;
 
ALTER TABLE ACCOUNT_USER_CODE ADD CONSTRAINT ACCUC_UCID_FK FOREIGN KEY (USER_CODE_ID)
	  REFERENCES USER_CODE (USER_CODE_ID) ;
 
ALTER TABLE ACCT_PARTY_ROLES_APPLICATION ADD CONSTRAINT ACC_PARTY_ROLES_APP_APID_FK FOREIGN KEY (APPLICATION_ID)
	  REFERENCES PARTY_ROLES_APPLICATION (APPLICATION_ID);
 
ALTER TABLE ACH_BATCH ADD CONSTRAINT ACH_FILE_ID_FK FOREIGN KEY (ACH_FILE_ID)
	  REFERENCES ACH_FILE (ACH_FILE_ID);
 
ALTER TABLE ACH_BATCH_SUMMARY ADD CONSTRAINT ACH_BATCH_SUMMARY_FK FOREIGN KEY (ACH_FILE_ID)
	  REFERENCES ACH_FILE (ACH_FILE_ID);
 
ALTER TABLE ACH_EVENT ADD CONSTRAINT ACHEVENT_WAREHOUSEENTRY_ID_FK FOREIGN KEY (ACH_WARE_HOUSE_ENTRY_ID)
	  REFERENCES ACH_WARE_HOUSE_ENTRY (ACH_WARE_HOUSE_ENTRY_ID) ;
 
ALTER TABLE ACH_EVENT ADD CONSTRAINT ACH_EVENT_ID_FK FOREIGN KEY (EVENT_ID)
	  REFERENCES EVENT (EVENT_ID) ;
 
ALTER TABLE ACH_FRABA_SUMMARY ADD CONSTRAINT ACH_FRABA_SUMMARY_FK1 FOREIGN KEY (ACH_FILE_ID)
	  REFERENCES ACH_FILE (ACH_FILE_ID);
 
ALTER TABLE ACH_FRABA_SUMMARY ADD CONSTRAINT ACH_FRABA_SUMMARY_FK2 FOREIGN KEY (FRABA_ID)
	  REFERENCES FRABA (FRABA_ID);
 
ALTER TABLE ACH_WAREHOUSE_ENTRY_ADDENDA ADD CONSTRAINT ACH_WARE_HOUSE_ENTRY_ID_FK FOREIGN KEY (ACH_WARE_HOUSE_ENTRY_ID)
	  REFERENCES ACH_WARE_HOUSE_ENTRY (ACH_WARE_HOUSE_ENTRY_ID);
 
ALTER TABLE ACH_WARE_HOUSE_ENTRY ADD CONSTRAINT ACH_BATCH_ID_FK FOREIGN KEY (ACH_BATCH_ID)
	  REFERENCES ACH_BATCH_SUMMARY (BATCH_ID);
 
ALTER TABLE ACH_WARE_HOUSE_ENTRY ADD CONSTRAINT FRABA_ID_FK FOREIGN KEY (FRABA_ID)
	  REFERENCES FRABA (FRABA_ID);
 
ALTER TABLE ANSWER ADD CONSTRAINT ANSWER_QID_FK FOREIGN KEY (QUESTION_ID)
	  REFERENCES QUESTION (QUESTION_ID) ;
 
ALTER TABLE APPLICATION ADD CONSTRAINT APPLICATION_IID_FK FOREIGN KEY (INSTITUTION_ID)
	  REFERENCES INSTITUTION (INSTITUTION_ID) ;
 
ALTER TABLE APPLICATION ADD CONSTRAINT APPLICATION_BRANCH_FK FOREIGN KEY (BRANCH)
	  REFERENCES BRANCH (UNIQUE_ID) ;
 
ALTER TABLE APPLICATION ADD CONSTRAINT APPLICATION_PID_FK FOREIGN KEY (PRODUCT_ID)
	  REFERENCES APPL_PRODUCT (UNIQUE_ID);
 
ALTER TABLE APPLICATION_STMT_ADDRESS ADD CONSTRAINT APP_STMT_ADD_ASID_FK FOREIGN KEY (APPL_STATEMENT_ID)
	  REFERENCES APPLICATION_STMT_GENERATOR (APPL_STATEMENT_ID);
 
ALTER TABLE APPLICATION_STMT_GENERATOR ADD CONSTRAINT APP_STMT_GEN_UID_FK FOREIGN KEY (UNIQUE_ID)
	  REFERENCES ACCOUNT_APPLICATION (UNIQUE_ID);
 
ALTER TABLE APPL_CD_PRODUCT ADD CONSTRAINT APPL_CD_PROD_UID_FK FOREIGN KEY (UNIQUE_ID)
	  REFERENCES APPL_PRODUCT (UNIQUE_ID);
 
ALTER TABLE APPL_CHECKING_PRODUCT ADD CONSTRAINT APPL_CHECKING_PROD_UID_FK FOREIGN KEY (UNIQUE_ID)
	  REFERENCES APPL_PRODUCT (UNIQUE_ID);
 
ALTER TABLE APPL_POTENTIAL_DEPOSIT_EVENT ADD CONSTRAINT APDE_POT_ID_FK FOREIGN KEY (POTENTIAL_DEP_EVE_ID)
	  REFERENCES POTENTIAL_DEPOSIT_EVENT (UNIQUE_ID) ;
 
ALTER TABLE APPL_POTENTIAL_DEPOSIT_EVENT ADD CONSTRAINT APDE_APPL_ID_FK FOREIGN KEY (APPLICATION_ID)
	  REFERENCES APPLICATION (APPLICATION_ID) ;
 
ALTER TABLE APPL_PRODUCT ADD CONSTRAINT APPL_PROD_PUID_FK FOREIGN KEY (PRODUCT_UID)
	  REFERENCES PRODUCT (PRODUCT_UID);
 
ALTER TABLE APPL_PRODUCT ADD CONSTRAINT APPL_PROD_CLSCODE_FK FOREIGN KEY (CLASS_CODE)
	  REFERENCES INST_PROD_CAT_CLASS_CODE (UNIQUE_ID) ;
 
ALTER TABLE APPL_PRODUCT_FORM ADD CONSTRAINT APPL_PROD_FORM_APUID_FK FOREIGN KEY (APPL_PRODUCT_UID)
	  REFERENCES APPL_PRODUCT (UNIQUE_ID) ;
 
ALTER TABLE APPL_PRODUCT_FORM ADD CONSTRAINT APPL_PROD_FORM_PFTUID_FK FOREIGN KEY (PROD_FORM_TEMP_UID)
	  REFERENCES PRODUCT_FORM_TEMPLATE (PROD_FORM_TEMP_UID);

 


