ALTER TABLE LOAN_ADVANCE_AUTO_REQUEST DROP column REJECTED_DATE;

ALTER TABLE LOAN_ADVANCE_AUTO_REQUEST ADD  PROCESSED_DATE DATE;

ALTER TABLE LOAN_ADVANCE_AUTO_REQUEST ADD  UNUSED_AVAIL_LIMIT NUMBER(10,6);

ALTER TABLE LOAN_ADVANCE_AUTO_REQUEST ADD  IP_ADDRESS VARCHAR2(20);