ALTER TABLE INSTITUTION ADD  RISK_TOLERANCE_ENABLED NUMBER(4) DEFAULT 0;

ALTER TABLE INSTITUTION ADD  LOAN_ADVANCE_AUTO_APPROVAL NUMBER(4) DEFAULT 0;

ALTER TABLE INSTITUTION ADD  LOAN_ADV_AUTO_APPROVE_LIMIT NUMBER(10,6);