CREATE TABLE LOAN_ADVANCE_AUTO_REQUEST
(
ID NUMBER(10) NOT NULL,
ACCOUNT_NUMBER VARCHAR2(30),
REQUESTED_AMOUNT NUMBER(20,5),
CUSTOMER_ID VARCHAR2(50),
CHANNEL VARCHAR2(10),
VERSION VARCHAR2(10),
BRANCH_ID VARCHAR2(10),
REQUESTED_NAME VARCHAR2(50),
PROCESSING_OFFICER VARCHAR2(50),
STATUS NUMBER(5),
SOURCE VARCHAR2(20),
CREATION_DATE DATE,
RT_NUMBER VARCHAR2(20),
REJECTED_DATE DATE,
PRIMARY KEY (ID)
); 

CREATE SEQUENCE LOAN_ADV_REQUEST_ID_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOMINVALUE NOCYCLE ORDER;