TRUNCATE TABLE DEBITCARD_SUBSCRIPTION_TYPE;

INSERT INTO DEBITCARD_SUBSCRIPTION_TYPE (TYPE_ID, NAME, DESCRIPTION, REISSUE_TERM, LIMIT_GROUP_ID) 
	VALUES (1, 'CONSUMER', 'CONSUMER', 36, 2);
INSERT INTO DEBITCARD_SUBSCRIPTION_TYPE (TYPE_ID, NAME, DESCRIPTION, REISSUE_TERM, LIMIT_GROUP_ID) 
	VALUES (2, 'BUSINESS', 'BUSINESS', 36, 2);