DROP TABLE EXTRACT_MASTER;

CREATE TABLE EXTRACT_MASTER
  (
    EXTRACT_UID    NUMBER(10,0) NOT NULL ENABLE,
    EXTRACT_NAME   VARCHAR2(30 BYTE) NOT NULL ENABLE,
    DESCRIPTION    VARCHAR2(30 BYTE),
    VENDOR_NAME    VARCHAR2(30 BYTE),
    FILE_NAME      VARCHAR2(50 BYTE),
    FILE_EXTENSION VARCHAR2(30 BYTE),
    FREQUENCY      VARCHAR2(30 BYTE),
    LAST_EXECUTION_DATE DATE,
    NEXT_EXECUTION_DATE DATE,
    DELIMITER         VARCHAR2(30 BYTE),
    FORMAT_TYPE       VARCHAR2(30 BYTE),
    MAX_RECORD_LENGTH NUMBER(10,0),
    REMARKS           VARCHAR2(30 BYTE),
    STATUS            VARCHAR2(30 BYTE),
    INSTITUTION_ID    NUMBER(10,0),
    CONSTRAINT EXTRACT_MASTER_PK PRIMARY KEY (EXTRACT_UID) ENABLE
  );
  
CREATE TABLE EXTRACT_LOG
  (
    EXECUTION_UID  NUMBER(30,0) NOT NULL ENABLE,
    EXTRACT_NAME   VARCHAR2(30 BYTE),
    DESCRIPTION    VARCHAR2(30 BYTE),
    VENDOR_NAME    VARCHAR2(30 BYTE),
    FILE_NAME      VARCHAR2(50 BYTE),
    FILE_EXTENSION VARCHAR2(30 BYTE),
    EXECUTION_DATE DATE,
    DATE_GENERATED DATE,
    RECORDS_COUNT VARCHAR2(50 BYTE),
    REMARKS       VARCHAR2(30 BYTE),
    EXTRACT_UID   NUMBER(30,0),
    CONSTRAINT EXTRACT_LOG_PK PRIMARY KEY (EXECUTION_UID) ENABLE,
    CONSTRAINT EXTRACT_MASTER_FK FOREIGN KEY (EXTRACT_UID) REFERENCES EXTRACT_MASTER (EXTRACT_UID) ENABLE
  );