

 CREATE TABLE OFAC_DATA
   (	"ID" NUMBER NOT NULL ENABLE, 
	"POSTED_DATE" DATE, 
	"ENTITY_TYPE" VARCHAR2(20), 
	"ORG_NAME" VARCHAR2(20), 
	"FIRST_NAME" VARCHAR2(20), 
	"MIDDLE_NAME" VARCHAR2(20), 
	"LAST_NAME" VARCHAR2(20), 
	"SSN" VARCHAR2(20), 
	"DOB" DATE, 
	"ID_TYPE" VARCHAR2(20), 
	"ID_ISSUER" VARCHAR2(20), 
	"ID_COUNTRY" VARCHAR2(20), 
	"ID_NUMBER" VARCHAR2(20), 
	"ORIGINAL_LIST_NAME" VARCHAR2(20), 
	"VESSEL_OWNER" VARCHAR2(20), 
	"COLUMN1" VARCHAR2(20), 
	 CONSTRAINT "OFAC_DATA_PK" PRIMARY KEY ("ID"));


  CREATE TABLE DELUXE_ID_VERIFICATION_RESULT
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DELUXE_RESPONSE_ID" NUMBER, 
	"WARNING_NUMBER" VARCHAR2(3), 
	"WARNING_TEXT" VARCHAR2(50), 
	"SEVERITY" VARCHAR2(3), 
	 CONSTRAINT "DELUXE_ID_VERIFICATION_RE_PK" PRIMARY KEY ("ID"));


  CREATE TABLE DELUXE_MATCH_RECORDS
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DELUXE_RESPONSE_ID" NUMBER, 
	"SEVERITY" VARCHAR2(3), 
	"CONTRIBUTOR" VARCHAR2(50), 
	 CONSTRAINT "DELUXE_MATCH_RECORDS_PK" PRIMARY KEY ("ID"));

  CREATE TABLE DELUXE_OFAC
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DELUXE_RESPONSE_ID" NUMBER, 
	"SEVERITY" VARCHAR2(3), 
	 CONSTRAINT "DELUXE_OFAC_PK" PRIMARY KEY ("ID"));


  CREATE TABLE MATCH_RECORD_DATA
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DELUXE_RECORD" NUMBER, 
	"OFAC_RECORD" NUMBER, 
	"MATCH_DATA" VARCHAR2(150), 
	"MATCH_FIELD" VARCHAR2(40), 
	"MATCH_TYPE" VARCHAR2(10), 
	 CONSTRAINT "MATCH_RECORD_DATA_PK" PRIMARY KEY ("ID"));
  

  CREATE TABLE DELUXE_CONSUMER_INFO
   (	"ID" NUMBER NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(40), 
	"LAST_NAME" VARCHAR2(40), 
	"MIDDLE_NAME" VARCHAR2(40), 
	"SSN" VARCHAR2(20), 
	"TAX_ID_NO" VARCHAR2(20), 
	"BIRTH_DATE" DATE, 
	"BIRTH_DATE_SPEC" NUMBER, 
	"GENDER" VARCHAR2(20), 
	"GENDER_SPEC" NUMBER, 
	"TYPE" VARCHAR2(20), 
	"ID_COUNTRY" VARCHAR2(20), 
	"ID_EXPIRY" DATE, 
	"ID_EXPIRY_SPEC" NUMBER, 
	"ID_NUMBER" VARCHAR2(40), 
	"ID_STATE" VARCHAR2(20), 
	"ID_TYPE" VARCHAR2(20), 
	"BUSINESS_NAME" VARCHAR2(40), 
	 CONSTRAINT "DELUXE_CONSUMER_INFO_PK" PRIMARY KEY ("ID"));


  CREATE TABLE DELUXE_CONSUMER_PHONE 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CONSUMER_INFO_ID" NUMBER, 
	"TYPE" VARCHAR2(20), 
	"PHONE_NUMBER" VARCHAR2(20), 
	 CONSTRAINT "DELUXE_CONSUMER_PHONE_PK" PRIMARY KEY ("ID"));


  CREATE TABLE DELUXE_ACCOUNT_INFO 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ACCOUNT_NUMBER" VARCHAR2(20), 
	"AGE_IN_MONTHS" NUMBER(38,0), 
	"CAC_RETURN_ITEM_COUNT" NUMBER(38,0), 
	"COLUMN1" VARCHAR2(20), 
	"CLOSURE_DATE" DATE, 
	"CLOSURE_DATE_SPEC" NUMBER, 
	"COMBINED_LOSS_FEE_REVERSAL" NUMBER, 
	"COMBINED_LOSS_FEE_REV_SPEC" NUMBER, 
	"CONSUMER_ABA" VARCHAR2(20), 
	"CONTRIBUTION_SRC" VARCHAR2(20), 
	"DISPUTE_CODE" VARCHAR2(20), 
	"DISPUTE_DATE" DATE, 
	"DISPUTE_DATE_SPEC" NUMBER, 
	"DISPUTE_REASON" VARCHAR2(20), 
	"FEE_REVERSAL" NUMBER, 
	"FEE_REVERSAL_SPEC" NUMBER, 
	"LOSS_TYPE" VARCHAR2(20), 
	"PAID_DATE" DATE, 
	"PAID_DATE_SPEC" NUMBER, 
	"PAID_STATUS" VARCHAR2(20), 
	"PRINCIPAL_LOSS" NUMBER, 
	"PRINCIPAL_LOSS_SPEC" NUMBER, 
	"SETTLE_DATE" DATE, 
	"SETTLE_DATE_SPEC" NUMBER,
  CONSTRAINT "DELUXE_ACCOUNT_INFO_PK" PRIMARY KEY ("ID"));

    CREATE TABLE DELUXE_CONSUMER_ADDRESS
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CONSUMER_DATA" NUMBER, 
	"OFAC_DATA" NUMBER, 
	"ADDRESS_TYPE" VARCHAR2(20), 
	"ADDRESS_1" VARCHAR2(20), 
	"ADDRESS_2" VARCHAR2(20), 
	"CITY" VARCHAR2(20), 
	"STATE" VARCHAR2(20), 
	"POSTAL_CODE" VARCHAR2(20), 
	"COUNTRY_CODE" VARCHAR2(20), 
	"COUNTRY_NAME" VARCHAR2(20), 
	 CONSTRAINT "DELUXE_CONSUMER_ADDRESS_PK" PRIMARY KEY ("ID"));

  ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN WARNING_NUMBER;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN WARNING_TEXT;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN SEVERITY;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN MATCH_TYPE;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN MATCH_FIELD;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN MATCH_DATA;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN CONSUMER_TYPE;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN SSN;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN LAST_NAME;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN MIDDLE_NAME;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN FIRST_NAME;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN BIRTH_DATE;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN IDENTIFICATION_TYPE;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN IDENTIFICATION_NUMBER;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN IDENTIFICATION_STATE;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN IDENTIFICATION_COUNTRY;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN IDENTIFICATION_EXPIRATIONDATE;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN ADDRESS_TYPE;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN ADDRESS1;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN ADDRESS2;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN CITY;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN STATE;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN POSTAL_CODE;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN COUNTRY_CODE;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN PHONE_TYPE;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN PHONE_NUMBER;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN BUSINESS_NAME;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN TAXID_NUMBER;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN CONSUMER_ABANUMBER;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN ACCOUNT_NUMBER;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN CLOSURE_DATE;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN AGE_IN_MONTHS;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN LOSS_TYPE;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN CACRETURN_ITEMCOUNT;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN CONTRIBUTION_SOURCE;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN PRINCIPAL_LOSS;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN FEE_REVERSAL;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN COMBINEDLOSS_AND_FEEREVERSAL;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN PAID_STATUS;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN PAID_DATE;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN SETTLE_DATE;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN DISPUTE_CODE;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN DISPUTE_REASON;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN DISPUTE_DATE;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN CONTRIBUTOR_NAME;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
DROP COLUMN OFAC_DATA;

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
ADD (CUMULATIVE_LOSS_SPEC NUMBER );

ALTER TABLE PARTY_ASSOC_DELUXE_CREDENTIAL 
ADD (SCHEMA_VERSION VARCHAR2(20) );

CREATE TABLE "DYNAMIC_FORM_EDITED_FIELDS" (
    "ID" NUMBER(30,0) NOT NULL ENABLE,
      "KEY" VARCHAR2(50),
      "VALUE" VARCHAR2(50),
     DYNAMIC_FORM_ID NUMBER(30,0),
   CONSTRAINT "DYNAMIC_FORM_EDITED_FIELDS_PK" PRIMARY KEY ("ID") ENABLE ,
   CONSTRAINT "DYNAMIC_FORMS_FK" FOREIGN KEY ("DYNAMIC_FORM_ID") REFERENCES "DYNAMIC_FORMS" ("UNIQUE_ID") ENABLE);