CREATE TABLE "CYCLE_GROUP_STATEMENT_CALENDAR" ("UNIQUE_ID" NUMBER(30,0) NOT NULL ENABLE, "FROM_DATE" DATE, 
      "TO_DATE" DATE, CYCLE_GROUP_CONFIG_UID NUMBER(30,0),
   CONSTRAINT "STATEMENT_CALENDAR_PK" PRIMARY KEY ("UNIQUE_ID") ENABLE ,
   CONSTRAINT "CYCLE_GROUP_FK" FOREIGN KEY ("CYCLE_GROUP_CONFIG_UID") REFERENCES "CYCLE_GROUP_CONFIG" ("CYCLE_GROUP_CONFIG_UID") ENABLE);

create sequence CYCLE_GROUP_STMT_CALENDAR_SEQ minvalue 1 maxvalue 9999999999 increment by 1 start with 1;

ALTER TABLE CYCLE_GROUP_CONFIG ADD LAST_STATEMENT_GENERATED_DATE DATE;
ALTER TABLE CYCLE_GROUP_CONFIG ADD WEEK_END_PROCESSING VARCHAR2(35);
ALTER TABLE ACCOUNT_APPLICATION ADD PRINT_ON_STATEMENT NUMBER(2) default 0;
ALTER TABLE CYCLE_GROUP_CONFIG RENAME column WEEK_END_PROCESSING to WEEKEND_PROCESSING;

ALTER TABLE PARTY_ADDRESS ADD NICK_NAME VARCHAR2(40) DEFAULT NULL;

ALTER TABLE DEPOSIT ADD DORMANCY_DATE DATE;

ALTER TABLE DEPOSIT ADD ESCHEATMENT_DATE DATE;

ALTER TABLE deposit ADD DAILY_OD_COUNTER NUMBER default 0;


ALTER TABLE TRANSACTION_POSTTODAY ADD ORIGINAL_TRANCODE_ID VARCHAR2(100) DEFAULT NULL;
ALTER TABLE deposit ADD  OD_DAYS_CHANGED_DATE DATE;

CREATE TABLE "FEE_PKG_MAINTENANCE_LOG" (
    "ENTRY_ID" NUMBER(30,0) NOT NULL ENABLE,
      "FEE_PACKAGE_ID" NUMBER(30,0),
      "FEE_PACKAGE_NAME" VARCHAR2(60),
     "FIELD_CHANGED" VARCHAR2(100),
     "OLD_VALUE" VARCHAR2(600),
     "NEW_VALUE" VARCHAR2(600),
     "CLASS_TYPE" VARCHAR2(70),
     "BRANCH_NAME" VARCHAR2(50),
     "USER_ID" VARCHAR2(50),
     "ENTRY_DATE" DATE,
     "TERMINAL" VARCHAR2(50),
   CONSTRAINT "FEE_PKG_MAINTENANCE_LOG_PK" PRIMARY KEY ("ENTRY_ID") ENABLE);
   
   ALTER TABLE TRANSACTION_POSTTODAY  ADD AS_ON_TRAN_LEDGER_BALANCE NUMBER(20,5) NULL;
   
   