CREATE TABLE "ACH_OFAC_MATCHED_ENTRY" (
    "UNIQUE_ID" NUMBER(30,0) NOT NULL ENABLE, 
	  "FIRST_NAME" VARCHAR2(100), 
	  "LAST_NAME" VARCHAR2(100), 
    "ID_COUNTRY" VARCHAR2(100), 
    "ID_TYPE" VARCHAR2(100), 
    "BIRTH_DATE" VARCHAR2(100), 
    "ID_NUMBER" VARCHAR2(100), 
    "AKA_FIRST_NAME" VARCHAR2(100), 
    "AKA_LAST_NAME" VARCHAR2(100), 
     ACH_WARE_HOUSE_ENTRY_ID VARCHAR2(10 BYTE),
   CONSTRAINT "ACH_OFAC_MATCHED_ENTRY_PK" PRIMARY KEY ("UNIQUE_ID") ENABLE ,
   CONSTRAINT "ACH_WARE_HOUSE_ENTRY_FK" FOREIGN KEY ("ACH_WARE_HOUSE_ENTRY_ID") REFERENCES "ACH_WARE_HOUSE_ENTRY" ("ACH_WARE_HOUSE_ENTRY_ID") ENABLE);
   
   CREATE TABLE RETURN_HISTORY_ITEM (
  UNIQUE_ID                     NUMBER(20) NOT NULL ENABLE,
  TRANS_CODE                	NUMBER(10,0) NULL,
  ORIGINAL_TRANSACTION_ID   	NUMBER(20,0) NULL,
  FORCE_POST_TXN_ID	            NUMBER(20,0) NULL,
  FEE_TRANSACTION_ID            NUMBER(20,0) NULL,
  ASSESSED_FEE              	NUMBER(20,5) NULL,
  CHARGED_FEE               	NUMBER(20,5) NULL,
  FORCE_POST_TXN_AMOUNT     	NUMBER(20,5) NULL,
  ORIGINAL_BALANCE            	NUMBER(20,5) NULL,
  STATUS                    	VARCHAR2(30) NULL,
  CONSTRAINT "RETURN_ITEM_HISTORY_PK" PRIMARY KEY ("UNIQUE_ID")
	);