CREATE TABLE AUDIT_TYPE_MASTER(
    UNIQUE_ID    NUMBER(38,0) NOT NULL ENABLE,
    AUDIT_TYPE  VARCHAR2(60 BYTE),
    PRIMARY KEY (UNIQUE_ID));
    
CREATE TABLE MEMBER_TYPE_MASTER(
    UNIQUE_ID    NUMBER(38,0) NOT NULL ENABLE,
    MEMBER_TYPE  VARCHAR2(60 BYTE),
    CONSTRAINT UNIQUE_ID_PK PRIMARY KEY (UNIQUE_ID));
    
ALTER TABLE organization ADD LAST_AUDIT_DATE DATE NULL;

ALTER TABLE organization ADD ASSET_SIZE NUMBER(12,2);
  
ALTER TABLE organization ADD AUDIT_TYPE VARCHAR2(60);

ALTER TABLE organization ADD MEMBER_TYPE VARCHAR2(60);

ALTER TABLE organization ADD MEMBERSHIP_CLOSE_DATE DATE NULL;

ALTER TABLE organization ADD MEMBERSHIP_CLOSE_REASON  VARCHAR2(100) NULL;