CREATE TABLE "MERGE_CREDIT_UNION_HISTORY" (
    "UNIQUE_ID" NUMBER(30,0) NOT NULL ENABLE,
    "MERGE_FROM" VARCHAR2(50),
    "MERGE_TO" VARCHAR2(50) ,
    "MERGE_BY" VARCHAR2(50),
    "MERGED_DATE" DATE,
  CONSTRAINT "MERGE_CREDIT_UNION_HIST_PK" PRIMARY KEY ("UNIQUE_ID") ENABLE);
  
  
CREATE SEQUENCE  MERGE_CREDIT_UNION_HISTORY_SEQ  MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE;