CREATE TABLE "FILE_LOG" (
    "FILE_ID" NUMBER(30,0) NOT NULL ENABLE, 
	  "FILE_NAME" VARCHAR2(100),
    "ORIGINATOR_ID" VARCHAR2(50),
    "FILE_UPLOAD_STATUS" NUMBER(1),
    "UPLOAD_DATE" DATE,
    "REJECT_REASON" NUMBER(1),
    "DETAILED_REASON" VARCHAR2(100),
    "FILE_HEAD" VARCHAR2(100),
    "FILE_TAIL" VARCHAR2(100),
   CONSTRAINT "FILE_LOG_PK" PRIMARY KEY ("FILE_ID") ENABLE);
   
create sequence FILE_LOG_SEQ minvalue 1 maxvalue 9999999999 increment by 1 start with 1;

 CREATE TABLE "BATCH_DETAILS" (
    "BATCH_ID" NUMBER(30,0) NOT NULL ENABLE, 
    "FILE_ID"  NUMBER(30,0) NOT NULL ENABLE, 
	  "BATCH_NAME" VARCHAR2(50),
    "BATCH_AMOUNT" NUMBER(30,2),
    "BATCH_HEADER" VARCHAR2(100),
    "BATCH_TAIL" VARCHAR2(100),
   CONSTRAINT "BATCH_DETAILS_PK" PRIMARY KEY ("BATCH_ID") ENABLE,
   CONSTRAINT "FILE_LOG_FK" FOREIGN KEY ("FILE_ID") REFERENCES "FILE_LOG" ("FILE_ID") ENABLE);  
   
 create sequence BATCH_DETAILS_SEQ minvalue 1 maxvalue 9999999999 increment by 1 start with 1;
 
 
  CREATE TABLE "TRANSACTION_WAREHOUSE" (
    "TRANSACTION_UID" NUMBER(30,0) NOT NULL ENABLE,
    "BATCH_ID" NUMBER(30,0) NOT NULL ENABLE,
    "FILE_ID" VARCHAR2(50), 
	  "FILE_NAME" VARCHAR2(50),
    "RTN" VARCHAR2(50),
    "TRANSACTION_AMOUNT" NUMBER(30,2),
    "SETTLEMENT_ACCOUNT" VARCHAR2(50),
    "STATUS" NUMBER(1),
    "EFFECTIVE_DATE" DATE,
    "SETTLEMENT_DATE" DATE,
    "EFFECTIVE_ENTRY_DATE" DATE,
    "SETTLEMENT_TRANCODE" VARCHAR2(50),
    "OFFSET_TRANCODE" VARCHAR2(50),
    "SUSP_CONTRA_TRANCODE" VARCHAR2(50),
    "SUSPENSE_TRANCODE" VARCHAR2(50),
    "TRANSACTION_DESCRIPTION" VARCHAR2(100),
    "TRANSACTION_RECORD" VARCHAR2(100),
    "TRANSACTION_ADDENDUM" VARCHAR2(100),
   CONSTRAINT "TRANSACTION_WAREHOUSE_PK" PRIMARY KEY ("TRANSACTION_UID") ENABLE,
   CONSTRAINT "BATCH_DETAILS_FK" FOREIGN KEY ("BATCH_ID") REFERENCES "BATCH_DETAILS" ("BATCH_ID") ENABLE);  
   
 create sequence TRANSACTION_WAREHOUSE_SEQ minvalue 1 maxvalue 9999999999 increment by 1 start with 1;
   

alter table settlemnt_trans_definition add SETTLEMENT_TRANCODE varchar2(50);
alter table settlemnt_trans_definition add OFFSET_TRANCODE varchar2(50);
alter table settlemnt_trans_definition add SUSP_CONTRA_TRANCODE varchar2(50);
alter table settlemnt_trans_definition add SUSPENSE_TRANCODE varchar2(50);

alter table institution add AUTO_PROCESS NUMBER(1) Default 1;