-- HOLD and STOP
update HOLD_PAYMENT hp set hp.ACCOUNT_ID = (
select acc.ACCOUNT_ID from ACCOUNT acc,DEPOSIT_ACCOUNT_INSTRUCTION dai where acc.ACCOUNT_ID = dai.ACCOUNT_ID and 
hp.INSTRUCTION_ID = dai.INSTRUCTION_ID);

update STOP_PAYMENT_INSTRUCTION sp set sp.ACCOUNT_ID = (
select acc.ACCOUNT_ID from ACCOUNT acc,DEPOSIT_ACCOUNT_INSTRUCTION dai where acc.ACCOUNT_ID = dai.ACCOUNT_ID and 
sp.INSTRUCTION_ID = dai.INSTRUCTION_ID);



update deposit_account set BAL_FWD_LAST_STMT = 0 where BAL_FWD_LAST_STMT is null;

update LEDGER_POSTING_PARAMETERS set AFFECTS_LST_STATEMENT_DATE=0 where ENTRY_TYPE_ID in(102,202,302);

update service_charge set ALWAYS_CHARGE_ITEMS = 0 where ALWAYS_CHARGE_ITEMS = 'NO';
update service_charge set ALWAYS_CHARGE_ITEMS = 0 where ALWAYS_CHARGE_ITEMS = 'No';
update service_charge set ALWAYS_CHARGE_ITEMS = 1 where ALWAYS_CHARGE_ITEMS = 'YES';
update service_charge set WHEN_TO_ASSESS_CHARGE = 'AT_CYCLE_TIME' where WHEN_TO_ASSESS_CHARGE = 'At Cycle Time';
update service_charge set WHICH_BAL_FOR_TIER = 'AVERAGE' where WHICH_BAL_FOR_TIER = 'Average';
update service_charge set WHICH_BAL_FOR_TIER = 'LOW' where WHICH_BAL_FOR_TIER = 'Low';
update service_charge set WHICH_BAL_FOR_TIER = 'COLLECTED' where WHICH_BAL_FOR_TIER = 'Collected';
update service_charge set WHICH_MAX_BALANCE = 'AVERAGE' where WHICH_MAX_BALANCE = 'Average';
update service_charge set WHICH_MAX_BALANCE = 'LOW' where WHICH_MAX_BALANCE = 'Low';
update service_charge set WHICH_MAX_BALANCE = 'COLLECTED' where WHICH_MAX_BALANCE = 'Collected';
update service_charge set TC_MAINTENANCE_CHARGE = '156';
update service_charge set TC_DORMANT_CHARGE = '156';
update service_charge set TC_ACTIVITY_CHARGE = '161';
update service_charge set TC_FOREIGNITEM_CHARGE = '161';
update service_charge set DESC_DORMANT_CHARGE = 'Dormancy Handling Charge';
update service_charge set DESC_ACTIVITY_CHARGE = 'Activity Charges';
update service_charge set DESC_FOREIGN_CHARGE = 'Transit Items Desposited Charges';
update service_charge set DESC_MAINTENANCE_CHARGE = 'Maintenance Charge';
update service_charge set SERVICE_CHARGE_CODE = 0 where SERVICE_CHARGE_CODE is null;
update service_charge set MAX_BAL_TO_CHARGE = 0 where MAX_BAL_TO_CHARGE is null;
update service_charge set PER_TRANSIT_ITEM_CHARGE = 0 where PER_TRANSIT_ITEM_CHARGE is null;
update service_charge set DORMANCY_CHARGE_AMOUNT = 0 where DORMANCY_CHARGE_AMOUNT is null; 
update service_charge set DORMANCY_MAX_BAL = 0 where DORMANCY_MAX_BAL is null; 

update service_charge_tier set TIER_MAINT_CHARGE = 0 where TIER_MAINT_CHARGE is null;
update service_charge_tier set TIER_BALANCE = 0 where TIER_BALANCE is null;
update service_charge_tier set  NO_FREE_CHECKS = 0 where  NO_FREE_CHECKS is null;

--update DEPOSIT_ACCOUNT set LAST_SERVICE_CHARGE = 0 where LAST_SERVICE_CHARGE is null;
--update deposit_account set AVG_BALANCE_CURRENT_PERIOD = 0 where AVG_BALANCE_CURRENT_PERIOD is null;
--update deposit_account set AVG_UNCOLLECT_BAL_CURR_PERIOD = 0 where AVG_UNCOLLECT_BAL_CURR_PERIOD is null;

-- LEDGER_BALANCE checking null condition

--update DEPOSIT_ACCOUNT set LEDGER_BALANCE=0 where LEDGER_BALANCE is null;

--UNCOLLECTED_BALANCE checking null condition

--update DEPOSIT_ACCOUNT set UNCOLLECTED_BALANCE=0 where UNCOLLECTED_BALANCE is null;


--INTEREST_RATE

update DEPOSIT_ACCOUNT set INTEREST_RATE=0 where INTEREST_RATE is null;


--FED_WITHHOLDING_CODE

update DEPOSIT_ACCOUNT set FED_WITHHOLDING_CODE=0 where FED_WITHHOLDING_CODE is null;

--STATE_WITHHOLDING_CODE

update DEPOSIT_ACCOUNT set STATE_WITHHOLDING_CODE=0 where STATE_WITHHOLDING_CODE is null;

-- INTEREST_CODE

--UPDATE DEPOSIT_ACCOUNT DA SET INTEREST_CODE = '2'
--WHERE da.INTEREST_CODE is null and account_id in (SELECT ACC.account_id
--FROM ACCOUNT ACC,PRODUCT_TYPE PT,DEPOSIT_ACCOUNT_TEMP NCA
--WHERE PT.PRODUCT_TYPE_ID = '63'
--AND PT.PRODUCT_CATEGORY = '2'
--and PT.institution_id='8'
--AND ACC.PRODUCT_ID = PT.UNIQUE_ID
--AND ACC.INSTITUTION_ID = PT.INSTITUTION_ID
--AND ACC.ACCOUNT_NO = NCA.ACCOUNT_NO
--AND ACC.INSTITUTION_ID = NCA.INSTITUTION_ID);

--update deposit_account set NO_CREDITS_CURRENT_PERIOD = 0 where NO_CREDITS_CURRENT_PERIOD is null;
--update deposit_account set NO_DEBITS_CURRENT_PERIOD = 0 where NO_DEBITS_CURRENT_PERIOD is null;
--update deposit_account set NO_ACH_DEBITS_CURRENT_PERIOD = 0 where NO_ACH_DEBITS_CURRENT_PERIOD is null;
--update deposit_account set NO_TRANSIT_ITEMS = 0 where NO_TRANSIT_ITEMS is null;
--update deposit_account set NO_OF_CHECKS = 0 where NO_OF_CHECKS is null;
--update deposit_account set NO_DEPOSITS_CURRENT_PERIOD = 0 where NO_DEPOSITS_CURRENT_PERIOD is null;
--update deposit_account set NO_ATM_DEBITS = 0 where NO_ATM_DEBITS is null;
--update deposit_account set FED_WITHHOLD_AMT_CURR_PERIOD = 0 where FED_WITHHOLD_AMT_CURR_PERIOD is null;
--update deposit_account set SRV_CHRG_ACT_CURR_PERIOD = 0 where SRV_CHRG_ACT_CURR_PERIOD is null;
--update deposit_account set SRV_CHRG_MAINTCURR_PERIOD = 0 where SRV_CHRG_MAINTCURR_PERIOD is null;
--update deposit_account set FED_WITHHOLD_AMT_YEAR_TO_DATE = 0 where FED_WITHHOLD_AMT_YEAR_TO_DATE is null;
--update deposit_account set YTD_INTEREST = 0 where YTD_INTEREST is null;
--update deposit_account set FACE_AMOUNT = 0 where FACE_AMOUNT is null;
--update DEPOSIT_ACCOUNT set AMOUNT_DEPOSIT_LAST = 0 where AMOUNT_DEPOSIT_LAST is null;
--update DEPOSIT_ACCOUNT set LAST_WITHDRAWN_AMOUNT = 0 where LAST_WITHDRAWN_AMOUNT is null;
update DEPOSIT_ACCOUNT set ACCRUED_INTEREST = 0 where ACCRUED_INTEREST is null;
--update DEPOSIT_ACCOUNT set AMOUNT_UNPOSTED_PASSBOOK_ITEMS = 0 where AMOUNT_UNPOSTED_PASSBOOK_ITEMS is null;
--update DEPOSIT_ACCOUNT set NUMBER_UNPOSTED_PASSBOOK_ITEMS = 0 where NUMBER_UNPOSTED_PASSBOOK_ITEMS is null;
--update DEPOSIT_ACCOUNT set INTEREST_FORFIETED = 0 where INTEREST_FORFIETED is null;
--update DEPOSIT_ACCOUNT set TIMES_NSF_CURR_PERIOD = 0 where TIMES_NSF_CURR_PERIOD is null;
--update DEPOSIT_ACCOUNT set TIMES_NSF_YTD = 0 where TIMES_NSF_YTD is null;
--update DEPOSIT_ACCOUNT set TIMES_OD_CURR_PERIOD = 0 where TIMES_OD_CURR_PERIOD is null;
--update DEPOSIT_ACCOUNT set TIMES_OD_YTD = 0 where TIMES_OD_YTD is null;
--update DEPOSIT_ACCOUNT set AMT_OF_DEBITS_CURRENT_PERIOD = 0 where AMT_OF_DEBITS_CURRENT_PERIOD is null;
--update DEPOSIT_ACCOUNT set AMT_OF_CREDITS_CURRENT_PERIOD = 0 where AMT_OF_CREDITS_CURRENT_PERIOD is null;

--UPDATE DEPOSIT_ACCOUNT DA SET INTEREST_CODE = '1'
--WHERE da.INTEREST_CODE is null and account_id IN (SELECT ACC.account_id
--FROM ACCOUNT ACC,PRODUCT_TYPE PT
--WHERE PT.PRODUCT_TYPE_ID IN ('14', '25', '48')
--AND PT.PRODUCT_CATEGORY = '1'
--AND ACC.PRODUCT_ID = PT.UNIQUE_ID
--AND ACC.INSTITUTION_ID = PT.INSTITUTION_ID
--AND ACC.account_id=da.account_id);
--
---- INTEREST CODE TO 3 FOR SAVINGS
--
--UPDATE DEPOSIT_ACCOUNT DA SET INTEREST_CODE = '3'
--WHERE da.INTEREST_CODE is null and account_id IN (SELECT ACC.account_id
--FROM ACCOUNT ACC,PRODUCT_TYPE PT
--WHERE PT.PRODUCT_TYPE_ID IN ('8', '9', '10','11')
--AND PT.PRODUCT_CATEGORY = '1'
--AND ACC.PRODUCT_ID = PT.UNIQUE_ID
--AND ACC.INSTITUTION_ID = PT.INSTITUTION_ID 
--AND ACC.account_id=da.account_id);
--
---- INTEREST CODE TO 4 FOR SAVINGS
--
--UPDATE DEPOSIT_ACCOUNT DA SET INTEREST_CODE = '4'
--WHERE da.INTEREST_CODE is null and account_id IN (SELECT ACC.account_id
--FROM ACCOUNT ACC,PRODUCT_TYPE PT
--WHERE PT.PRODUCT_TYPE_ID IN ('12', '13')
--AND PT.PRODUCT_CATEGORY = '1'
--AND ACC.PRODUCT_ID = PT.UNIQUE_ID
--AND ACC.INSTITUTION_ID = PT.INSTITUTION_ID
--AND ACC.account_id=da.account_id);
--
---- INTEREST CODE TO 5 FOR SAVINGS
--
--UPDATE DEPOSIT_ACCOUNT DA SET INTEREST_CODE = '5'
--WHERE da.INTEREST_CODE is null and account_id IN (SELECT ACC.account_id
--FROM ACCOUNT ACC,PRODUCT_TYPE PT
--WHERE PT.PRODUCT_TYPE_ID IN ('40','43')
--AND PT.PRODUCT_CATEGORY = '1'
--AND ACC.PRODUCT_ID = PT.UNIQUE_ID
--AND ACC.INSTITUTION_ID = PT.INSTITUTION_ID
--AND ACC.account_id=da.account_id);
--
---- INTEREST CODE TO 6 FOR SAVINGS
--
--UPDATE DEPOSIT_ACCOUNT DA SET INTEREST_CODE = '6'
--WHERE da.INTEREST_CODE is null and account_id IN (SELECT ACC.account_id
--FROM ACCOUNT ACC,PRODUCT_TYPE PT
--WHERE PT.PRODUCT_TYPE_ID = '16'
--AND PT.PRODUCT_CATEGORY = '1'
--AND ACC.PRODUCT_ID = PT.UNIQUE_ID
--AND ACC.INSTITUTION_ID = PT.INSTITUTION_ID
--AND ACC.account_id=da.account_id);
--
---- INTEREST CODE FOR CHECKINGS
--
----  Data migration for INTEREST_CODE = '4'
--
--UPDATE DEPOSIT_ACCOUNT_VW DA SET INTEREST_CODE = '4'
--WHERE  (DA.ACCOUNT_NO,DA.INSTITUTION_ID)IN (SELECT
--ACC.ACCOUNT_NO,ACC.INSTITUTION_ID
--FROM ACCOUNT ACC,PRODUCT_TYPE PT
--WHERE PT.PRODUCT_TYPE_ID = '58'
--AND PT.PRODUCT_CATEGORY = '2'
--AND ACC.PRODUCT_ID = PT.UNIQUE_ID
--AND ACC.INSTITUTION_ID = PT.INSTITUTION_ID);
--
--UPDATE DEPOSIT_ACCOUNT DA SET INTEREST_CODE = '2'
--WHERE account_id IN (SELECT ACC.account_id
--FROM ACCOUNT ACC,PRODUCT_TYPE PT
--WHERE PT.PRODUCT_TYPE_ID in ('60','63','88')
--AND PT.PRODUCT_CATEGORY = '2'
--AND ACC.PRODUCT_ID = PT.UNIQUE_ID
--AND ACC.INSTITUTION_ID = PT.INSTITUTION_ID
--AND ACC.account_id=da.account_id);
-- 
--UPDATE DEPOSIT_ACCOUNT DA SET INTEREST_CODE = '3'
--WHERE (DA.ACCOUNT_ID)IN (
--SELECT ACC.ACCOUNT_ID
--FROM ACCOUNT ACC,PRODUCT_TYPE PT
--WHERE DA.ACCOUNT_ID=ACC.ACCOUNT_ID
--AND ACC.PRODUCT_ID = PT.UNIQUE_ID
--AND PT.PRODUCT_TYPE_ID in('66','67','68','69')
--AND PT.PRODUCT_CATEGORY = '2');
-- 
--UPDATE DEPOSIT_ACCOUNT DA SET INTEREST_CODE = '2'
--WHERE (DA.ACCOUNT_ID)IN (
--SELECT ACC.ACCOUNT_ID
--FROM ACCOUNT ACC,PRODUCT_TYPE PT
--WHERE DA.ACCOUNT_ID=ACC.ACCOUNT_ID
--AND ACC.PRODUCT_ID = PT.UNIQUE_ID
--AND PT.PRODUCT_TYPE_ID in('53','54','55')
--AND PT.PRODUCT_CATEGORY = '2');
--
--UPDATE DEPOSIT_ACCOUNT DA SET INTEREST_CODE = '0'
--WHERE (DA.ACCOUNT_ID)IN (
--SELECT ACC.ACCOUNT_ID
--FROM ACCOUNT ACC,PRODUCT_TYPE PT
--WHERE DA.ACCOUNT_ID=ACC.ACCOUNT_ID
--AND ACC.PRODUCT_ID = PT.UNIQUE_ID
--AND PT.PRODUCT_TYPE_ID in('3','4','5','7','16','19','20','21','22','23','24','25','30','89')
--AND PT.PRODUCT_CATEGORY = '2');
--
---- adding interest code for CD'S
--
--UPDATE DEPOSIT_ACCOUNT DA SET INTEREST_CODE =
-- (SELECT distinct PF.DEFAULT_VALUE
-- FROM ACCOUNT ACC,PRODUCT_TYPE PT,PRODUCT_FEATURE PF,PRODUCT P,FEATURE F
-- WHERE DA.ACCOUNT_ID=ACC.ACCOUNT_ID
-- AND ACC.INSTITUTION_ID = PT.INSTITUTION_ID
-- AND ACC.PRODUCT_ID = PT.UNIQUE_ID
-- AND PT.PRODUCT_CATEGORY = '3'
-- AND PT.UNIQUE_ID=P.PRODUCT_TYPE_ID
-- AND P.PRODUCT_UID=PF.PRODUCT_UID
-- AND PF.FEATURE_UID=F.FEATURE_UID
-- AND F.FEATURE_DESC='INTEREST_CODE')
-- WHERE (DA.ACCOUNT_ID)IN (
-- SELECT distinct ACC.ACCOUNT_ID
-- FROM ACCOUNT ACC,PRODUCT_TYPE PT
-- WHERE DA.ACCOUNT_ID=ACC.ACCOUNT_ID
-- AND ACC.PRODUCT_ID = PT.UNIQUE_ID
-- AND ACC.INSTITUTION_ID = PT.INSTITUTION_ID
-- AND PT.PRODUCT_CATEGORY = '3');

 update DEPOSIT_ACCOUNT set NO_DAYS_OVERDRAWN_CURR_PERIOD = 0 where
NO_DAYS_OVERDRAWN_CURR_PERIOD is null;

update DEPOSIT_ACCOUNT set NO_DAYS_OVERDRAWN_YR_TO_DATE = 0 where
NO_DAYS_OVERDRAWN_YR_TO_DATE is null;

--UPDATE DEPOSIT_ACCOUNT   DA1 SET DA1.PROCEEDS_ACCOUNT_ID  =
--(
--SELECT  A.ACCOUNT_ID PROCEEDS_ACCOUNT_ID
-- FROM  DEPOSIT_ACCOUNT_VW DA ,  ACCOUNT A
--          WHERE  LPAD(da1.PROCEEDS_ACCOUNT_NUMBER,12,0) = A.ACCOUNT_NO
--                    AND DA.INSTITUTION_ID = A.INSTITUTION_ID
--                    AND DA1.ACCOUNT_ID = DA.ACCOUNT_ID
-- )
--WHERE da1.PROCEEDS_ACCOUNT_NUMBER   IS NOT NULL AND
--da1.PROCEEDS_ACCOUNT_NUMBER <>0 ;  

update DEPOSIT_ACCOUNT set DAYS_PER_YEAR = '4' where ACCOUNT_ID in 
(select account_id from ACCOUNT where ACCOUNT_TYPE_ID = '22') and DAYS_PER_YEAR in ('1','2');

update DEPOSIT_ACCOUNT set rate_change_code = '2' where rate_change_code = '0' 
and ACCOUNT_ID in (select account_id from account where account_type_id = '22');