ALTER TABLE REGION
ADD IS_OPERATIONAL_CENTER VARCHAR2(1);

ALTER TABLE BRANCH
ADD IS_OPERATIONAL_CENTER VARCHAR2(1);


CREATE TABLE REGION_ADDRESS ( 
	UNIQUE_REGION_ADDRESS_ID	NUMBER(15,0) NOT NULL,
	REGION_ID               	VARCHAR2(60) NOT NULL,
	ADDRESS_USE                  	VARCHAR2(60) NOT NULL,
	ADDRESS_ID                   	NUMBER(10,0) NULL 
	);
  
CREATE SEQUENCE  REGION_ADDRESS_ID_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

ALTER TABLE REGION_ADDRESS ADD CONSTRAINT REGION_ADDR_PK PRIMARY KEY (UNIQUE_REGION_ADDRESS_ID);

ALTER TABLE REGION_ADDRESS ADD CONSTRAINT REGION_ADDR_IID FOREIGN KEY (REGION_ID)
	  REFERENCES REGION (REGION_UNIQUE_ID) ;
 
ALTER TABLE REGION_ADDRESS ADD CONSTRAINT REGION_ADDR_AID FOREIGN KEY (ADDRESS_ID)
	  REFERENCES ADDRESS (ADDRESS_ID) ;
