ALTER TABLE REGD_ACTIVITY_DETAILS ADD STATEMENT_CYCLE_REGD_COUNT NUMBER(10) DEFAULT 0;
ALTER TABLE telecom_address ADD PRIORITY NUMBER(10) DEFAULT 1;
ALTER TABLE WEB_ADDRESS ADD PRIORITY NUMBER(10) DEFAULT 1;

CREATE TABLE "DEFAULT_PROD_CATEGORY_QUES" (
      "UNIQUE_ID" NUMBER(30,0) NOT NULL ENABLE,
      "PRODUCT_CATEGORY" VARCHAR2(50),
      "QUESTION_ID" VARCHAR2(50),
      CONSTRAINT "DEFAULT_PROD_CAT_PK" PRIMARY KEY ("UNIQUE_ID") ENABLE );
      
ALTER TABLE institution ADD TELLER_LAST_PROCESSING_DATE DATE;

ALTER TABLE party ADD OPT_IN_IRA NUMBER DEFAULT 0;

CREATE TABLE "FEATURE_DEFAULT_VALID_VALUES" (
"UNIQUE_ID" NUMBER(30,0) NOT NULL ENABLE,
"FEATURE_UID" NUMBER(30,0),
"VALID_VALUES" VARCHAR2(150),
CONSTRAINT "PROD_FEA_VALID_PK" PRIMARY KEY ("UNIQUE_ID") ENABLE,
CONSTRAINT "FEATURE_FK" FOREIGN KEY ("FEATURE_UID") REFERENCES "FEATURE" ("FEATURE_UID") ENABLE); 