UPDATE PROPERTY_DEFINITION SET DEFAULT_VALUE='com.vsoftcorp.finance.Money:USD 0.00' WHERE PROPERTY_NAME LIKE 'TotalSanctionedLimit';
UPDATE PROPERTY_DEFINITION SET DEFAULT_VALUE='com.vsoftcorp.finance.Money:USD 0.00' WHERE PROPERTY_NAME LIKE 'CreditLineSanctionedLimit';
UPDATE PROPERTY_DEFINITION SET DEFAULT_VALUE='com.vsoftcorp.finance.Money:USD 0.00' WHERE PROPERTY_NAME LIKE 'TermLoanSanctionedLimit';
UPDATE PROPERTY_DEFINITION SET DEFAULT_VALUE='com.vsoftcorp.finance.Money:USD 0.00' WHERE PROPERTY_NAME LIKE 'TotalCreditLineLimitUsed';
UPDATE PROPERTY_DEFINITION SET DEFAULT_VALUE='com.vsoftcorp.finance.Money:USD 0.00' WHERE PROPERTY_NAME LIKE 'TotalTermLoanLimitUsed';
UPDATE PROPERTY_DEFINITION SET DEFAULT_VALUE='com.vsoftcorp.finance.Money:USD 0.00' WHERE PROPERTY_NAME LIKE 'UnusedCreditLineLimit';
UPDATE PROPERTY_DEFINITION SET DEFAULT_VALUE='com.vsoftcorp.finance.Money:USD 0.00' WHERE PROPERTY_NAME LIKE 'UnusedTermLoanLimit';
UPDATE PROPERTY_DEFINITION SET DEFAULT_VALUE='com.vsoftcorp.finance.Money:USD 0.00' WHERE PROPERTY_NAME LIKE 'TotalAvailableAmount';