ALTER TABLE LOAN ADD LEGALCHARGES_FEES_PAID NUMBER(15,5) DEFAULT 0;

ALTER TABLE LOAN ADD NSF_FEES_PAID NUMBER(15,5) DEFAULT 0;

ALTER TABLE LOAN ADD MISCELLANEOUS_FEES_PAID NUMBER(15,5) DEFAULT 0;