create table BANKRUPTCY_RECORD (
    id             NUMBER(10),
    ACCOUNT_NUMBER       VARCHAR2(10),
    DATE_FILED           DATE,
    DATE_APPROVED        DATE,
    DOCKET_NUMBER        VARCHAR(20),
    TRUSTEE              NUMBER(10),
    FEE_AMOUNT           NUMBER(20,5),
    DUE_INSTALLMENTS     NUMBER(10),
    AMT_PAY_PLAN         NUMBER(20,5),
    RECOVERY_START_DATE  DATE,
    FREQUENCY            NUMBER(2),
    FUNDS_FROM_BORROWER  NUMBER(20,5),
    FUNDS_FROM_TRUSTEE   NUMBER(20,5)
 
);

CREATE SEQUENCE BANKRUPTCY_RECORD_ID_SEQ
    INCREMENT BY 1
    START WITH 101
    MAXVALUE 999999999
    NOMINVALUE
    NOCYCLE
    CACHE 20
    NOORDER;


create table TRUSTEE (
    id                  NUMBER(10),
    TRUSTEE_CODE        VARCHAR2(10),
    TRUSTEE_NAME        VARCHAR2(100),
    ADDRESS_1           VARCHAR2(100),
    ADDRESS_2           VARCHAR2(100),
    CITY                VARCHAR2(100),
    STATE               VARCHAR2(100),
    ZIP                 NUMBER(10),
    CONTACT_PERSON      VARCHAR2(100),
    CONTRCT_NUMBER      NUMBER(10)
    
);

CREATE SEQUENCE TRUSTEE_ID_SEQ
    INCREMENT BY 1
    START WITH 101
    MAXVALUE 999999999
    NOMINVALUE
    NOCYCLE
    CACHE 20
    NOORDER;