CREATE TABLE SDB_ACCOUNT
  (
    ACCOUNT_ID          NUMBER(38,0) NOT NULL ENABLE,
    SDB_ACCOUNT_NUMBER  VARCHAR2(40 BYTE),
    SAFE_DEPOSIT_BOX_ID NUMBER(38,0),
    ACCOUNT_STATUS      NUMBER(*,0),
    PARTY_REGISTERD_ID  VARCHAR2(30 BYTE),
    DATE_LAST_MAINTAINED DATE,
    CONSTRAINT SDB_ACCOUNT_PK PRIMARY KEY (ACCOUNT_ID),
    CONSTRAINT FK_SDB_ACCOUNT_PARTY FOREIGN KEY (PARTY_REGISTERD_ID) REFERENCES PARTY (PARTY_ID),
    CONSTRAINT FK_SDB_SDB_ACCOUNT FOREIGN KEY (SAFE_DEPOSIT_BOX_ID) REFERENCES SAFE_DEPOSIT_BOX (SAFE_DEPOSIT_BOX_ID)
  );

CREATE TABLE SAFE_DEPOSIT_CONTRACT
  (
    SAFE_DEPOSIT_CONTRACT_ID NUMBER(38,0) NOT NULL ENABLE,
    CONTRACT_START_DATE DATE,
    CONTRACT_END_DATE DATE,
    AUTO_ROLLOVER                 NUMBER(1,0),
    AUTO_TRANSFER_ACCOUNT_NUMBER  VARCHAR2(40 BYTE),
    PAYMENT_MODE                  VARCHAR2(40 BYTE),
    ANNUAL_AMOUNT                 NUMBER(10,2),
    RENT_WAIVED                   NUMBER(10,2),
    PAYMENT_FREQUENCY             VARCHAR2(40 BYTE),
    RENT_WAIVER_AMOUNT            NUMBER(10,2),
    WAIVER_REMARKS                VARCHAR2(40 BYTE),
    PAID_AMOUNT                   NUMBER(10,2),
    ACCOUNT_ID                    NUMBER(38,0),
    CONTRACT_PERIOD               NUMBER(*,0),
    PRIOR_DAYS_OF_BILL_GENERATION NUMBER(*,0),
    BENEFICIARY_INFORMATION       VARCHAR2(500 BYTE),
    MULTIPLE_BENEFICIARY          VARCHAR2(500 BYTE),
    SUCCESSOR_CUSTODIAN           VARCHAR2(45 BYTE),
    DATE_IF_TRUST DATE,
    GRANTOR_NAMES            VARCHAR2(45 BYTE),
    WHO_IS_THE_SECREATARY    VARCHAR2(45 BYTE),
    WHO_IS_ASSO_SECREATARY   VARCHAR2(45 BYTE),
    HOW_IT_IS_TAXED          VARCHAR2(45 BYTE),
    HOW_LLC_IS_TAXED         VARCHAR2(45 BYTE),
    WHO_IS_DESIGNATED_MEMBER VARCHAR2(45 BYTE),
    OWNERSHIP_DESIGNATION    VARCHAR2(10 BYTE) DEFAULT 0,
    PERSONAL_BANKER          VARCHAR2(50 BYTE),
    ASSIGNED_OFFICER         VARCHAR2(50 BYTE),
    REFERRED_BY_CUSTOMER     VARCHAR2(45 BYTE),
    REFERRED_BY_BANK_USER    VARCHAR2(45 BYTE),
    HOW_DID_YOU_HEAR         VARCHAR2(45 BYTE),
    CONSTRAINT SAFE_DEPOSIT_CONTRACT_PK PRIMARY KEY (SAFE_DEPOSIT_CONTRACT_ID),
    CONSTRAINT FK_SDB_ACCOUNT_CONTRACT FOREIGN KEY (ACCOUNT_ID) REFERENCES SDB_ACCOUNT (ACCOUNT_ID)
  );


CREATE TABLE PAYMENT_DETAILS
  (
    PAYMENT_DETAILS_ID NUMBER(38,0) NOT NULL ENABLE,
    SCHEDULED_PAYMENT_DATE DATE,
    NEXT_PAYMENT_DATE DATE,
    RENT_DUE_STATUS VARCHAR2(30 BYTE),
    RENT_DUE_AMOUNT NUMBER(10,2),
    BILL_GENERATION_DATE DATE,
    SAFE_DEPOSIT_CONTRACT_ID NUMBER(38,0),
    PAYMENT_STATUS           NUMBER(*,0),
    WEEK_END_PROCESSING      VARCHAR2(60 BYTE),
    LAST_BILL_GENERATED_DATE DATE,
    CONSTRAINT PAYMENT_DETAILS_PK PRIMARY KEY (PAYMENT_DETAILS_ID),
    CONSTRAINT FK_PAYMENT_CONTRACT FOREIGN KEY (SAFE_DEPOSIT_CONTRACT_ID) REFERENCES SAFE_DEPOSIT_CONTRACT (SAFE_DEPOSIT_CONTRACT_ID)
  );


CREATE TABLE PAYMENT_BILL_HISTORY
  (
    PAYMENT_BILL_HISTORY_ID NUMBER(38,0) NOT NULL ENABLE,
    GENEARATED_BILL_DDATE DATE,
    CALC_DUE NUMBER(10,2),
    DUE_DATE DATE,
    TOTAL_DUE_AMOUNT NUMBER(10,2),
    LAST_PAYMENT     NUMBER(10,2),
    BILL_STATUS      VARCHAR2(20 BYTE),
    BILL_AMOUNT      NUMBER(10,2),
    PAYMENT_DATE DATE,
    REMARKS                  VARCHAR2(80 BYTE),
    SAFE_DEPOSIT_CONTRACT_ID NUMBER(38,0),
    PAYMENT_DETAILS_ID       NUMBER(38,0),
    CONSTRAINT PAYMENT_BILL_HISTORY_PK PRIMARY KEY (PAYMENT_BILL_HISTORY_ID),
    CONSTRAINT FK_PAY_HISTORY_DETAIL FOREIGN KEY (PAYMENT_DETAILS_ID) REFERENCES PAYMENT_DETAILS (PAYMENT_DETAILS_ID),
    CONSTRAINT FK_PAYMENT_HISTORY_CONTRACT FOREIGN KEY (SAFE_DEPOSIT_CONTRACT_ID) REFERENCES SAFE_DEPOSIT_CONTRACT (SAFE_DEPOSIT_CONTRACT_ID)
  );
 
CREATE TABLE ACCESS_LOG
  (
    ACCESS_LOG_ID NUMBER(38,0) NOT NULL ENABLE,
    IN_TIME       VARCHAR2(30 BYTE),
    OUT_TIME      VARCHAR2(30 BYTE),
    ACCESS_DATE DATE,
    PERSON_NAME    VARCHAR2(30 BYTE),
    RESPONSIBILITY VARCHAR2(30 BYTE),
    REMARKS        VARCHAR2(80 BYTE),
    ACCOUNT_ID     NUMBER(38,0),
    CONSTRAINT ACCESS_LOG_PK PRIMARY KEY (ACCESS_LOG_ID),
    CONSTRAINT FK_ACCESS_LOG_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES SDB_ACCOUNT (ACCOUNT_ID)
  );

CREATE TABLE SAFE_DEPOSIT_BOX_AUD
  (
    SAFE_DEPOSIT_BOX_ID NUMBER(38,0) NOT NULL ENABLE,
    BOX_NUMBER          VARCHAR2(40 BYTE),
    STATUS              VARCHAR2(40 BYTE),
    MASTER_KEY_NUMBER   VARCHAR2(40 BYTE),
    CUSTOMER_KEY_NUMBER VARCHAR2(40 BYTE),
    SDB_TYPE_ID         NUMBER(38,0),
    CABINET_ID          NUMBER(38,0),
    REV_ID              NUMBER(*,0) NOT NULL ENABLE,
    REV_TYPE            NUMBER(*,0),
    CONSTRAINT SDB_PK_AUDI PRIMARY KEY (SAFE_DEPOSIT_BOX_ID, REV_ID) ,
    CONSTRAINT FK_CABINET_AUDI FOREIGN KEY (CABINET_ID) REFERENCES CABINET (CABINET_ID),
    CONSTRAINT FK_BOX_TYPE_AUDI FOREIGN KEY (SDB_TYPE_ID) REFERENCES SAFE_DEPOSIT_BOX_TYPE (SDB_TYPE_ID)
  );
 
CREATE TABLE SDB_ACCOUNT_AUD
  (
    ACCOUNT_ID          NUMBER(38,0) NOT NULL ENABLE,
    SDB_ACCOUNT_NUMBER  VARCHAR2(40 BYTE),
    SAFE_DEPOSIT_BOX_ID NUMBER(38,0),
    PARTY_REGISTERD_ID  VARCHAR2(30 BYTE),
    ACCOUNT_STATUS      NUMBER(*,0),
    REV_ID              NUMBER(*,0) NOT NULL ENABLE,
    REV_TYPE            NUMBER(*,0),
    CONSTRAINT SDB_ACCOUNT_PK_AUDI PRIMARY KEY (ACCOUNT_ID, REV_ID),
    CONSTRAINT FK_SDB_SDB_ACCOUNT_AUDI FOREIGN KEY (SAFE_DEPOSIT_BOX_ID) REFERENCES SAFE_DEPOSIT_BOX (SAFE_DEPOSIT_BOX_ID)
  );
 

CREATE TABLE SAFE_DEPOSIT_CONTRACT_AUD
  (
    SAFE_DEPOSIT_CONTRACT_ID NUMBER(38,0) NOT NULL ENABLE,
    CONTRACT_START_DATE DATE,
    CONTRACT_END_DATE DATE,
    AUTO_ROLLOVER                NUMBER(1,0),
    AUTO_TRANSFER_ACCOUNT_NUMBER VARCHAR2(40 BYTE),
    PAYMENT_MODE                 VARCHAR2(40 BYTE),
    ANNUAL_AMOUNT                NUMBER(10,2),
    RENT_WAIVED                  NUMBER(10,2),
    PAYMENT_FREQUENCY            NUMBER(*,0),
    RENT_WAIVER_AMOUNT           NUMBER(10,2),
    WAIVER_REMARKS               VARCHAR2(40 BYTE),
    PAID_AMOUNT                  NUMBER(10,2),
    ACCOUNT_ID                   NUMBER(38,0),
    REV_ID                       NUMBER(*,0) NOT NULL ENABLE,
    REV_TYPE                     NUMBER(*,0),
    BENEFICIARY_INFORMATION      VARCHAR2(500 BYTE),
    MULTIPLE_BENEFICIARY         VARCHAR2(500 BYTE),
    SUCCESSOR_CUSTODIAN          VARCHAR2(45 BYTE),
    DATE_IF_TRUST DATE,
    GRANTOR_NAMES            VARCHAR2(45 BYTE),
    WHO_IS_THE_SECREATARY    VARCHAR2(45 BYTE),
    WHO_IS_ASSO_SECREATARY   VARCHAR2(45 BYTE),
    HOW_IT_IS_TAXED          VARCHAR2(45 BYTE),
    HOW_LLC_IS_TAXED         VARCHAR2(45 BYTE),
    WHO_IS_DESIGNATED_MEMBER VARCHAR2(45 BYTE),
    OWNERSHIP_DESIGNATION    VARCHAR2(10 BYTE) DEFAULT 0,
    PERSONAL_BANKER          VARCHAR2(50 BYTE),
    ASSIGNED_OFFICER         VARCHAR2(50 BYTE),
    CONSTRAINT SAFE_DEPOSIT_CONTRACT_PK_AUD PRIMARY KEY (SAFE_DEPOSIT_CONTRACT_ID, REV_ID) ,
    CONSTRAINT FK_SDB_ACCOUNT_CONTRACT_AUDI FOREIGN KEY (ACCOUNT_ID) REFERENCES SDB_ACCOUNT (ACCOUNT_ID)
  );


CREATE TABLE PAYMENT_DETAILS_AUD
  (
    PAYMENT_DETAILS_ID NUMBER(38,0) NOT NULL ENABLE,
    SCHEDULED_PAYMENT_DATE DATE,
    NEXT_PAYMENT_DATE DATE,
    RENT_DUE_STATUS VARCHAR2(30 BYTE),
    RENT_DUE_AMOUNT NUMBER(10,2),
    BILL_GENERATION_DATE DATE,
    SAFE_DEPOSIT_CONTRACT_ID NUMBER(38,0),
    PAYMENT_STATUS           NUMBER(*,0),
    REV_ID                   NUMBER(*,0) NOT NULL ENABLE,
    REV_TYPE                 NUMBER(*,0),
    CONSTRAINT PAYMENT_DETAILS_PK_AUD PRIMARY KEY (PAYMENT_DETAILS_ID, REV_ID),
    CONSTRAINT FK_PAYMENT_CONTRACT_AUDI FOREIGN KEY (SAFE_DEPOSIT_CONTRACT_ID) REFERENCES SAFE_DEPOSIT_CONTRACT (SAFE_DEPOSIT_CONTRACT_ID)
  );


CREATE TABLE PAYMENT_BILL_HISTORY_AUD
  (
    PAYMENT_BILL_HISTORY_ID NUMBER(38,0) NOT NULL ENABLE,
    GENEARATED_BILL_DDATE DATE,
    CALC_DUE NUMBER(10,2),
    DUE_DATE DATE,
    TOTAL_DUE_AMOUNT NUMBER(10,2),
    LAST_PAYMENT     NUMBER(10,2),
    BILL_STATUS      VARCHAR2(20 BYTE),
    BILL_AMOUNT      NUMBER(10,2),
    PAYMENT_DATE DATE,
    REMARKS                  VARCHAR2(80 BYTE),
    SAFE_DEPOSIT_CONTRACT_ID NUMBER(38,0),
    PAYMENT_DETAILS_ID       NUMBER(38,0),
    REV_ID                   NUMBER(*,0) NOT NULL ENABLE,
    REV_TYPE                 NUMBER(*,0),
    CONSTRAINT PAYMENT_BILL_HISTORY_PK_AUD PRIMARY KEY (PAYMENT_BILL_HISTORY_ID, REV_ID),
    CONSTRAINT FK_PAY_HISTORY_AUDI FOREIGN KEY (PAYMENT_DETAILS_ID) REFERENCES PAYMENT_DETAILS (PAYMENT_DETAILS_ID),
    CONSTRAINT FK_PAY_HISTORY_CON_AUDI FOREIGN KEY (SAFE_DEPOSIT_CONTRACT_ID) REFERENCES SAFE_DEPOSIT_CONTRACT (SAFE_DEPOSIT_CONTRACT_ID) ENABLE
  );


CREATE TABLE ACCESS_LOG_AUD
  (
    ACCESS_LOG_ID NUMBER(38,0) NOT NULL ENABLE,
    IN_TIME       VARCHAR2(30 BYTE),
    OUT_TIME      VARCHAR2(30 BYTE),
    ACCESS_DATE DATE,
    PERSON_NAME    VARCHAR2(30 BYTE),
    RESPONSIBILITY VARCHAR2(30 BYTE),
    REMARKS        VARCHAR2(80 BYTE),
    ACCOUNT_ID     NUMBER(38,0),
    REV_ID         NUMBER(*,0) NOT NULL ENABLE,
    REV_TYPE       NUMBER(*,0),
    CONSTRAINT ACCESS_LOG_PK_AUD PRIMARY KEY (ACCESS_LOG_ID, REV_ID),
    CONSTRAINT FK_ACC_LOG_ACCOUNT_AUDI FOREIGN KEY (ACCOUNT_ID) REFERENCES SDB_ACCOUNT (ACCOUNT_ID)
  );


CREATE TABLE PAYMENT_DETAILS_HISTORY
  (
    PAYMENT_DETAILS_HISTORY_ID NUMBER(38,0) NOT NULL ENABLE,
    LAST_PAYMENT               NUMBER(10,2),
    PAYMENT_DATE DATE,
    BILL_STATUS        VARCHAR2(20 BYTE),
    PAYMENT_DETAILS_ID NUMBER(38,0),
    CONSTRAINT PYMNT_DETL_HSTY_KEY PRIMARY KEY (PAYMENT_DETAILS_HISTORY_ID)
  );

CREATE TABLE SDB_MAINTENANCE_LOG
  (
    ENTRY_ID      NUMBER(*,0),
    FIELD_CHANGED VARCHAR2(40 BYTE),
    CHANGE_FROM   VARCHAR2(40 BYTE),
    CHANGE_TO     VARCHAR2(40 BYTE),
    ENTRY_DATE DATE,
    ACCOUNT_NUMBER VARCHAR2(40 BYTE),
    BRANCH_NAME    VARCHAR2(40 BYTE),
    USER_NAME      VARCHAR2(40 BYTE)
  );

--ALTER TABLE account_application ADD WEEK_END_PROCESSING VARCHAR2(60);
--ALTER TABLE payment_details ADD WEEK_END_PROCESSING VARCHAR2(60);