CREATE TABLE CABINET
  (
    CABINET_ID   NUMBER(38,0) NOT NULL ENABLE,
    MODEL_NUMBER VARCHAR2(40 BYTE),
    PURCHASE_DATE DATE,
    NO_OF_BOXES    NUMBER(*,0),
    VENDOR_ID      NUMBER(38,0),
    UNIQUE_ID      VARCHAR2(40 BYTE),
    INSTITUTION_ID VARCHAR2(30 BYTE),
    BRANCH_ID      VARCHAR2(30 BYTE),
    CONSTRAINT CABINET_ID_PK PRIMARY KEY (CABINET_ID) ,
    CONSTRAINT FK_VENDOR FOREIGN KEY (VENDOR_ID) REFERENCES VENDOR (VENDOR_ID)
    --CONSTRAINT FK_CABINET_UNIQUE FOREIGN KEY (UNIQUE_ID) REFERENCES BRANCH (UNIQUE_ID)
  );
 

CREATE TABLE SAFE_DEPOSIT_BOX
  (
    SAFE_DEPOSIT_BOX_ID NUMBER(38,0) NOT NULL ENABLE,
    BOX_NUMBER          VARCHAR2(40 BYTE),
    STATUS              VARCHAR2(40 BYTE),
    SDB_TYPE_ID         NUMBER(38,0),
    CABINET_ID          NUMBER(38,0),
    MASTER_KEY_NUMBER   VARCHAR2(40 BYTE),
    CUSTOMER_KEY_NUMBER VARCHAR2(40 BYTE),
    BRANCH              NUMBER(6,0),
    CONSTRAINT SDB_PK PRIMARY KEY (SAFE_DEPOSIT_BOX_ID),
    CONSTRAINT FK__SDB_CABINET FOREIGN KEY (CABINET_ID) REFERENCES CABINET (CABINET_ID),
    CONSTRAINT FK_DEPOSIT_BOX_TYPE FOREIGN KEY (SDB_TYPE_ID) REFERENCES SAFE_DEPOSIT_BOX_TYPE (SDB_TYPE_ID)
  );