CREATE OR REPLACE VIEW "ORDERED_CARDS_REPORT_VW" ("ID", "PARTICIPANT_ID", "CUSTOMER_TYPE", "CUST_ID_NO", "MEMBER_NO", 
 "EXPIRATION_DATE", "NO_OF_ACCOUNTS", "DEFAULT_ACCOUNT_TYPE", "DEFAULT_ACCOUNT_QUALIFIER", "ACCOUNT_TYPE", "ACCOUNT_QUALIFIER",  
"ACCOUNT_NUMBER", "NO_OF_PLASTICS", "REISSUE_VALUE", "SPECIAL_HANDLING_INDICATOR", "BLOCKED_CARD_INDICATOR", "PIN_INDICATOR", "PIN_BLOCK",  
"NO_OF_CHECKS", "EMP_SECURITY_LEVEL", "FEE_GROUP_NAME", "LIMIT_GROUP_NAME", "CH_RESTRICT_TRANS_INDICATOR", "CARD_ACTIVATION_INDICATOR",  
"PRIOR_EXPIRE_DATE", "CAVV_CARD_OPTION", "ENTRY_MODE_RESTRICT", "CUST_LNAME", "CUST_FNAME", "CUST_MIDDLE_INTIAL", "CUST_LNAME2",  
"CUST_FNAME2", "CUST_MIDDLE_INTIAL2", "NO_OF_PLASTICS_TO_ISSUE", "CUST_ADDRESS_LINE1", "CUST_ADDRESS_LINE2", "CUST_CITY", "CUST_STATE", 
 "CUST_ZIP", "COUNTRY_CODE", "CUST_DAYTIME_PHONE", "CUST_EVENING_PHONE", "EMBOSS_NAME", "CUST_REMARKS", "CUST_ACCOUNT_DESC", "SSN", "MOTHER_MAIDEN_NAME", "DOB", "VRU_PASSWORD", "DRIVERS_LICENSE_NO", "DRIVERS_LICENSE_EXP_DATE", "SECOND_EMBOSS_LINE", "ORDERED_TIME", "ORDERED_BY", "ORDERED_FROM", "REJECTED_TIME", "REJECT_REMARKS", "REJECTED_BY_BRANCH", "INSTITUTION_ID" ) 
AS SELECT DISTINCT DS.SUBCRIPTION_ID ID,
  TO_CHAR('537688') PARTICIPANT_ID,
  DST.NAME CUSTOMER_TYPE,
  DS.SUBSCRIPTION_NUMBER CUST_ID_NO,
  TO_CHAR('0000') MEMBER_NO,
  DS.EXPIRATION_DATE EXPIRATION_DATE,
  TO_NUMBER(1) NO_OF_ACCOUNTS ,
  TO_NUMBER(001) DEFAULT_ACCOUNT_TYPE,
  TO_NUMBER(001) DEFAULT_ACCOUNT_QUALIFIER,
  CASE WHEN DAV.ACCOUNT_TYPE_ID=10 THEN 'CHECKING'
       WHEN DAV.ACCOUNT_TYPE_ID=21 THEN 'SAVINGS' END ACCOUNT_TYPE ,
  TO_NUMBER(001 ) ACCOUNT_QUALIFIER,
  DS.PRIMARY_ACCOUNT_NUMBER ACCOUNT_NUMBER ,
  TO_NUMBER(01) NO_OF_PLASTICS,
  DS.REISSUE_TERM REISSUE_VALUE,
  '' SPECIAL_HANDLING_INDICATOR,
  'N' BLOCKED_CARD_INDICATOR ,
  TO_NUMBER(0) PIN_INDICATOR,
  '06' PIN_BLOCK,
  TO_NUMBER(00) NO_OF_CHECKS,
  TO_NUMBER(0) EMP_SECURITY_LEVEL,
  '' FEE_GROUP_NAME,
  LG.NAME LIMIT_GROUP_NAME,
  '' CH_RESTRICT_TRANS_INDICATOR,
  DS.STATUS CARD_ACTIVATION_INDICATOR,
  DS.PRIOR_EXPIRATION_DATE PRIOR_EXPIRE_DATE,
  '' CAVV_CARD_OPTION,
  '' ENTRY_MODE_RESTRICT,
  PE.LAST_NAME CUST_LNAME,
  PE.FIRST_NAME CUST_FNAME,
  SUBSTR(PE.MIDDLE_NAME, 1, 1) CUST_MIDDLE_INTIAL,
  '' CUST_LNAME2,
  '' CUST_FNAME2,
  '' CUST_MIDDLE_INTIAL2,
  TO_NUMBER(0) NO_OF_PLASTICS_TO_ISSUE ,
  GA.LINE_1 CUST_ADDRESS_LINE1,
  GA.LINE_2 CUST_ADDRESS_LINE2,
  GA.CITY CUST_CITY,
  GA.STATE CUST_STATE,
  GA.ZIP_1
  ||' '
  ||GA.ZIP_2 CUST_ZIP,
  GA.COUNTRY COUNTRY_CODE,
  CASE
    WHEN TPH.PHONE IS NOT NULL
    AND TPC.PHONE  IS NOT NULL
    THEN TPH.PHONE
    ELSE TPW.PHONE
  END AS CUST_DAYTIME_PHONE,
  CASE
    WHEN TPC.PHONE IS NOT NULL
    THEN TPC.PHONE
    ELSE TPH.PHONE
  END AS CUST_EVENING_PHONE,
  DU.EMBOSS_LINE1 EMBOSS_NAME,
  '' CUST_REMARKS,
  '' CUST_ACCOUNT_DESC,
  SSN.PARTY_REGISTERD_ID SSN,
  PE. MOTHERS_MAIDEN_NAME MOTHER_MAIDEN_NAME,
  PE.DATE_OF_BIRTH DOB,
  '' VRU_PASSWORD,
  DRL.PARTY_REGISTERD_ID DRIVERS_LICENSE_NO,
  DRL.EFFECTIVE_END_DATE DRIVERS_LICENSE_EXP_DATE,
  DU.EMBOSS_LINE2 SECOND_EMBOSS_LINE,
  DS.ORDERED_TIME,
  DS.ORDERED_BY,
  DS.ORDERED_FROM,
  DS.REJECTED_TIME,
  DS.REJECT_REMARKS,
  DS.REJECTED_BY_BRANCH,
  I.INSTITUTION_ID INSTITUTION_ID
FROM DEBITCARD_SUBSCRIPTION DS,
  DEBITCARD_SUBSCRIPTION_TYPE DST,
  DEPOSIT_ACCOUNT_VW DAV,
  LIMIT_GROUP LG,
  DEBITCARD_USER DU,
  PERSON PE,
  PARTY_ADDRESS PA,
  GEOGRAPHIC_ADDRESS GA,
  ACCOUNT_STATEMENT_ADDRESS ASA,
  ACCOUNT_STATEMENT_GENERATOR ASG,
  (SELECT * FROM PARTY_ADDRESS WHERE ADDRESS_USE='HOME_PHONE'
  ) TH,
  (SELECT * FROM PARTY_ADDRESS WHERE ADDRESS_USE='WORK_PHONE'
  ) TW,
  (SELECT * FROM PARTY_ADDRESS WHERE ADDRESS_USE='CELL_PHONE'
  ) TC,
  TELECOM_ADDRESS TPH,
  TELECOM_ADDRESS TPW,
  TELECOM_ADDRESS TPC,
  (SELECT * FROM PARTY_REGISTERED_IDS WHERE TYPE IN('SSN','ITIN','EIN')
  ) SSN,
  (SELECT * FROM PARTY_REGISTERED_IDS WHERE TYPE LIKE 'DR%'
  ) DRL,
  INSTITUTION I
WHERE DS.TYPE_ID               =DST.TYPE_ID
AND DS.PRIMARY_ACCOUNT_NUMBER  =DAV.ACCOUNT_NO
AND DS.LIMIT_GROUP_ID          =LG.LIMIT_GROUP_ID
AND DS.PRIMARY_USER_ID         =DU.USER_ID
AND DU.CORE_PARTY_ID           =PE.PARTY_ID
AND DAV.ACCOUNT_ID             =ASG.ACCOUNT_ID
AND ASG.UNIQUE_ID              =ASA.UNIQUE_ID
AND ASA.UNIQUE_PARTY_ADDRESS_ID=PA.UNIQUE_PARTY_ADDRESS_ID
AND PA.ADDRESS_ID              =GA.ADDRESS_ID
AND DU.CORE_PARTY_ID           =TH.PARTY_ID(+)
AND DU.CORE_PARTY_ID           =TW.PARTY_ID(+)
AND DU.CORE_PARTY_ID           =TC.PARTY_ID(+)
AND TH.ADDRESS_ID              =TPH.ADDRESS_ID(+)
AND TW.ADDRESS_ID              =TPW.ADDRESS_ID(+)
AND TC.ADDRESS_ID              =TPC.ADDRESS_ID(+)
AND DU.CORE_PARTY_ID           =SSN.PARTY_ID(+)
AND DU.CORE_PARTY_ID           =DRL.PARTY_ID(+)
AND DS.BANK_ID                 =I.INSTITUTION_ID
ORDER BY DS.SUBCRIPTION_ID;