CREATE TABLE VENDOR
  (
    VENDOR_ID    NUMBER(38,0) NOT NULL ENABLE,
    VENDOR_NAME  VARCHAR2(60 BYTE),
    ADDRESS      VARCHAR2(100 BYTE),
    CONTACT_INFO VARCHAR2(100 BYTE),
    CONSTRAINT VENDOR_ID_PK PRIMARY KEY (VENDOR_ID)
  );


CREATE TABLE SAFE_DEPOSIT_BOX_TYPE
  (
    SDB_TYPE_ID NUMBER(38,0) NOT NULL ENABLE,
    SDB_SIZE    VARCHAR2(60 BYTE),
    TYPE_NAME   VARCHAR2(40 BYTE),
    LENGTH      NUMBER(*,0),
    WIDTH       NUMBER(*,0),
    HEIGHT      NUMBER(*,0),
    ANNUAL_RENT NUMBER(10,2),
    CONSTRAINT SDB_TYPE_PK PRIMARY KEY (SDB_TYPE_ID)
  );
