
--Audit table for backupwithholding

CREATE TABLE "BACKUP_WITHHOLDING_AUD" 
   (	"BKP_WITH_HOLD_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"REV_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"REV_TYPE" NUMBER(3,0), 
	"REV_END" NUMBER(10,0), 
	"REV_END_TIMESTAMP" TIMESTAMP (6), 
	
        "CUSTOMER_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"NOTIFICATION_TYPE" VARCHAR2(30), 
	"NOTIFICATION_DATE" DATE, 
	"TAX_YEAR" NUMBER(4,0), 
	"NOTICE_PRINT_DATE" DATE, 
	"STATUS" NUMBER(2,0), 
               
        
	"NOTIFICATIONTYPE_MOD" CHAR(1 CHAR), 
        "NOTIFICATIONDATE_MOD" CHAR(1 CHAR), 
        "TAXYEAR_MOD" CHAR(1 CHAR), 
        "STATUS_MOD" CHAR(1 CHAR), 
        "NOTICEPRINTDATE_MOD" CHAR(1 CHAR), 
                
	 PRIMARY KEY ("BKP_WITH_HOLD_ID", "REV_ID") 
  );
  
--View for Backupwithholding reports
	