ALTER TABLE party_registered_ids MODIFY CHARTER_IND  VARCHAR2(2);
ALTER TABLE ORIGINATOR_MASTER DROP COLUMN TIME;
ALTER TABLE ORIGINATOR_MASTER ADD TIME_AVAILABLE VARCHAR2(50);
ALTER TABLE REQUEST_MASTER ADD EMAIL_NOTIFICATION NUMBER(1) DEFAULT 0;
ALTER TABLE REQUEST_MASTER ADD SEND_EMAIL_TO VARCHAR2(50);