CREATE TABLE TRANSACTION_BATCH_DETAILS (
    BATCH_ID NUMBER(30) NOT NULL ENABLE,
    BATCH_NAME VARCHAR2(50),
    BATCH_AMOUNT NUMBER(30,2),
    BATCH_STATUS NUMBER(1),
    BATCH_REJECT_REASON NUMBER(1),
    BATCH_POST_DATE DATE,
    CHANNEL VARCHAR2(30),
    REQUESTOR_USER_NAME VARCHAR2(30),
    REQUESTOR_IP_ADDRESS VARCHAR2(30),
    REQUESTOR_WEB_BROWSER_AND_VER VARCHAR2(30),
    CONSTRAINT TRAN_BATCH_DETAILS_PK PRIMARY KEY (BATCH_ID) ENABLE);

CREATE SEQUENCE TRAN_BATCH_DETAILS_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1;

CREATE TABLE TRANSACTION_DETAILS (
    UNIQUE_ID NUMBER(30) NOT NULL ENABLE,
    BATCH_ID NUMBER(30) NOT NULL ENABLE,
    GROUP_ID NUMBER(30),
    SOURCE_ACCOUNT_NUMBER VARCHAR2(30),
    TARGET_ACCOUNT_NUMBER VARCHAR2(30),
    TRANSACTION_AMOUNT NUMBER(30,2),
    TRAN_CODE VARCHAR2(30),
    TRANSCTION_STATUS VARCHAR2(30),
    POST_DATE DATE,
    TRANSACTION_REJECT_REASON NUMBER(1),
    SOURCE_RTN VARCHAR2(30),
    TARGET_RTN VARCHAR2(30),
    CONSTRAINT TRAN_DETAILS_PK PRIMARY KEY (UNIQUE_ID) ENABLE,
    CONSTRAINT TRAN_BATCH_DETAILS_FK FOREIGN KEY (BATCH_ID) REFERENCES TRANSACTION_BATCH_DETAILS (BATCH_ID) ENABLE);
    
CREATE SEQUENCE TRANSACTION_DETAILS_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1;

ALTER table TRANSACTION_POSTTODAY add TRANSACTION_GROUP_ID VARCHAR2(30);
ALTER table TRANSACTION_POSTTODAY add BATCH_ID VARCHAR2(30);
ALTER table TRANSACTION_POSTTODAY add ORIGINAL_TXN_ID VARCHAR2(30);
