ALTER TABLE LOAN_APPLICATION_EVENT DROP COLUMN REVOLVING_CREDIT_LINE;

ALTER TABLE LOAN_APPLICATION_EVENT ADD CREDIT_LINE_TYPE NUMBER(10);

UPDATE PROPERTY_DEFINITION SET MANDATORY=0 WHERE PROPERTY_NAME LIKE 'MinimumDrawAmount' AND ENTITY_TYPE_DEFINITION_ID 
IN (SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE 'CreditLine');

UPDATE PROPERTY_DEFINITION SET MANDATORY=0 WHERE PROPERTY_NAME LIKE 'SanctionLimit' AND ENTITY_TYPE_DEFINITION_ID 
IN (SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE 'CreditLine');

UPDATE PROPERTY_DEFINITION SET MANDATORY=0 WHERE PROPERTY_NAME LIKE 'DrawingLimit' AND ENTITY_TYPE_DEFINITION_ID 
IN (SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE 'CreditLine');

UPDATE PROPERTY_DEFINITION SET MANDATORY=0 WHERE PROPERTY_NAME LIKE 'LineExpirationDate' AND ENTITY_TYPE_DEFINITION_ID 
IN (SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE 'CreditLine');

UPDATE PROPERTY_DEFINITION SET MANDATORY=0 WHERE PROPERTY_NAME LIKE 'NumberOfDraws' AND ENTITY_TYPE_DEFINITION_ID 
IN (SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE 'CreditLine');