select PROPDEFID_SEQ.NEXTVAL from dual;
select PROPDEFID_SEQ.NEXTVAL from dual;
-------------------------------------------------------RevolvingCreditLine------------------------------------------------------------------------------------------
INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
VALUES(PROPDEFID_SEQ.nextval,(SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE 'LoanContract'), 'RevolvingCreditLine', 27, 'Revolving Credit Line', 2, 0, 0, 'java.lang.Integer:0', 0, 'java.lang.Integer:{default={0=Regular Loan,1=Regular Credit Type,2=Revolving Credit Type,3=Revolving OD Type}}', 0, 0, 0, 0, 1, 0, 0, 'C', 0, 0);

INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
VALUES(PROPDEFID_SEQ.currval, 1, 1, 1, 1, 'DEFAULT'); 
INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
VALUES(PROPDEFID_SEQ.currval, 1, 1, 1, 1, 'INQUIRY'); 
INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
VALUES(PROPDEFID_SEQ.currval, 1, 1, 1, 1, 'ACCOUNT_CREATED'); 

----------------------------------------------------MasterAgreementNo-------------------------------------------------------------------------------------------------------------------------------
INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
VALUES(PROPDEFID_SEQ.nextval,(SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE 'LoanContract'), 'MasterAgreementNo', 28, 'Master Agreement No', 1, 0, 0, NULL, 0, 'java.lang.String:{default={}}', 0, 0, 0, 0, 1, 0, 0, 'C', 0, 0);

INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
VALUES(PROPDEFID_SEQ.currval, 1, 1, 1, 1, 'DEFAULT'); 
INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
VALUES(PROPDEFID_SEQ.currval, 1, 1, 1, 1, 'INQUIRY'); 
INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
VALUES(PROPDEFID_SEQ.currval, 1, 1, 1, 1, 'ACCOUNT_CREATED');
  
  
ALTER TABLE LOAN_APPLICATION_EVENT ADD REVOLVING_CREDIT_LINE NUMBER(10);

UPDATE PROPERTY_DEFINITION SET MANDATORY=0 WHERE PROPERTY_NAME LIKE 'LoanAmount' AND ENTITY_TYPE_DEFINITION_ID 
IN (SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE 'LoanContract');

UPDATE PROPERTY_DEFINITION SET MANDATORY=0 WHERE PROPERTY_NAME LIKE 'MaturityDate' AND ENTITY_TYPE_DEFINITION_ID 
IN (SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION where type_name like 'LoanContract');

UPDATE PROPERTY_DEFINITION SET MANDATORY=0 WHERE PROPERTY_NAME LIKE 'LoanTerm' AND ENTITY_TYPE_DEFINITION_ID 
IN (SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE 'LoanContract');