UPDATE PROPERTY_DEFINITION SET MANDATORY=0 WHERE PROPERTY_NAME LIKE 'BilledInterest';

UPDATE PROPERTY_PRESENTER_ATTRIBUTES SET HIDDEN=1 ,HIDDEN_OVERRIDEN=1 WHERE PROPERTY_DEFINITION_ID IN
(SELECT PROPERTY_DEFINITION_ID FROM PROPERTY_DEFINITION WHERE PROPERTY_NAME LIKE 'BilledInterest');

UPDATE PROPERTY_DEFINITION SET MANDATORY=0 WHERE PROPERTY_NAME LIKE 'EscrowInterest';

UPDATE PROPERTY_PRESENTER_ATTRIBUTES SET HIDDEN=1 ,HIDDEN_OVERRIDEN=1 WHERE PROPERTY_DEFINITION_ID IN
(SELECT PROPERTY_DEFINITION_ID FROM PROPERTY_DEFINITION WHERE PROPERTY_NAME LIKE 'EscrowInterest');