CREATE TABLE CBI_EXCEPTION (
UNIQUE_ID NUMBER NULL,
ACCOUNT_NO VARCHAR2(20) NULL,
CUSTOMER_NAME VARCHAR2(100) NULL,
EFFECTIVE_DATE VARCHAR2(20) NULL,
REPAYMENT_METHOD VARCHAR2(20) NULL,
REMARKS VARCHAR2(20) NULL,
STATUS VARCHAR2(20) NULL,
CALL_REPORT_CODE VARCHAR2(20) NULL
);

alter table CBI_EXCEPTION modify (REPAYMENT_METHOD  VARCHAR2(100));