CREATE TABLE "CHECK_ISSUE_REGISTER" 
   (	"UNIQUE_ID" NUMBER, 
	"ISSUEDATE" DATE, 
	"PAYEE" VARCHAR2(100 BYTE), 
	"CHECK_NUMBER" VARCHAR2(100 BYTE), 
	"REMITTER" VARCHAR2(100 BYTE), 
	"REMARKS" VARCHAR2(50 BYTE), 
	"AMOUNT" NUMBER(20,5), 
	"STATUS" VARCHAR2(50 BYTE), 
	"ACCOUNT_NO" VARCHAR2(30 BYTE), 
	"INSTITUTION_ID" VARCHAR2(30 BYTE)
   );

 CREATE TABLE "CHECK_PAID_REGISTER" 
   (	"UNIQUE_ID" NUMBER NOT NULL ENABLE, 
	"PAID_DATE" DATE, 
	"PAYEE_NAME" VARCHAR2(100 BYTE), 
	"CHECK_NUMBER" VARCHAR2(100 BYTE), 
	"REMITTER" VARCHAR2(100 BYTE), 
	"REMARKS" VARCHAR2(50 BYTE), 
	"AMOUNT" NUMBER(20,5), 
	"STATUS" VARCHAR2(50 BYTE), 
	"ACCOUNT_NO" VARCHAR2(30 BYTE), 
	"INSTITUTION_ID" VARCHAR2(30 BYTE), 
	"ACCOUNT_HISTORY_ID" NUMBER(20,0), 
	 CONSTRAINT "CHECK_PAID_REGISTER_PK" PRIMARY KEY ("UNIQUE_ID"),
	 CONSTRAINT "CHECK_PAID_REGISTER_ACCOU_FK1" FOREIGN KEY ("ACCOUNT_HISTORY_ID")
	  REFERENCES "ACCOUNT_HISTORY_ITEM" ("TRANSACTION_ID") );

CREATE SEQUENCE  "CHECK_ISSUE_REGISTER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  "CHECK_PAID_REGISTER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

ALTER TABLE ledger_posting_parameters ADD AFFECTS_CHECK_PAID_REGISTER NUMBER default 0;