-----------------------------
ALTER TABLE DEPOSIT add partial_withdrawl_count number(10) DEFAULT '0';

ALTER TABLE DEPOSIT add additional_deposit_count number(10) DEFAULT '0';

ALTER TABLE DEPOSIT ADD Max_partial_withdrawal NUMBER(10) DEFAULT '0';

ALTER TABLE DEPOSIT add Max_additional_deposit number(10) DEFAULT '0';

ALTER TABLE DEPOSIT add Max_rate_change number(10) DEFAULT '0';

ALTER TABLE DEPOSIT add is_partial_witdrawal_allowed number(1) DEFAULT '0';

ALTER TABLE DEPOSIT_ACCOUNT_INSTRUCTION add SECUR_ACCOUNT_NO  VARCHAR2(30);

ALTER TABLE hold_payment_maintenance  add SECUR_ACCOUNT_NUMBER  VARCHAR2(30);

ALTER TABLE LEDGER_POSTING_PARAMETERS add(PARTIAL_WITH_DRAWL_COUNT NUMBER,ADDITIONAL_DEPOSIT_COUNT  NUMBER);

ALTER TABLE DEPOSIT add(RATE_CHANGE_COUNT number);

CREATE TABLE "REGD_ACTIVITY_DETAILS" 
   (	"ACCOUNT_ID" VARCHAR2(30 BYTE), 
	"JAN_COUNT" NUMBER DEFAULT 0, 
	"FEB_COUNT" NUMBER DEFAULT 0, 
	"MAR_COUNT" NUMBER DEFAULT 0, 
	"APR_COUNT" NUMBER DEFAULT 0, 
	"MAY_COUNT" NUMBER DEFAULT 0, 
	"JUN_COUNT" NUMBER DEFAULT 0, 
	"JUL_COUNT" NUMBER DEFAULT 0, 
	"AUG_COUNT" NUMBER DEFAULT 0, 
	"SEP_COUNT" NUMBER DEFAULT 0, 
	"OCT_COUNT" NUMBER DEFAULT 0, 
	"NOV_COUNT" NUMBER DEFAULT 0, 
	"DEC_COUNT" NUMBER DEFAULT 0, 
	"NOTICE_GENERATED_DATE" DATE, 
	"MONTH_TRANSFER_COUNT" NUMBER DEFAULT 0, 
	"QUARTER_TRANSFER_COUNT" NUMBER DEFAULT 0, 
	"SEMI_ANNUALTRANSFER_COUNT" NUMBER DEFAULT 0, 
	"ANNUAL_TRANSFER_COUNT" NUMBER DEFAULT 0, 
	"STATUS" VARCHAR2(100 BYTE), 
	"UNIQUE_ID" NUMBER(10,0)
   );

--alter table REGD_ACTIVITY_DETAILS add NO_VIOLATIONS_YTD NUMBER DEFAULT 0;
   
ALTER TABLE deposit ADD REGD_COMPUTING_PERIOD VARCHAR2(30);

ALTER TABLE deposit ADD MAx_ALLOWED_TRANSFERS_COUNT NUMBER(10);

ALTER TABLE deposit ADD REGD_ALLOWED NUMBER(1,0);

ALTER TABLE LEDGER_POSTING_PARAMETERS ADD REGD_ACTIVITY NUMBER DEFAULT 0;

 CREATE TABLE "SWEEP_ACCOUNTTYPE" 
   (	"ID" NUMBER, 
	"FROM_ACCOUNT" VARCHAR2(100 BYTE), 
	"TO_ACCOUNT" VARCHAR2(100 BYTE)
   );

create sequence SWEEP_ACCOUNTYPE_ID_SEQ start with 100;

CREATE TABLE "SWEEP_INSTRUCTION" 
   (	"SWEEP_ID" NUMBER(20,0), 
	"IS_SWEEP_UP_ENABLED" NUMBER(2,0), 
	"SWEEP_UP_BALANCE_TO_USE" VARCHAR2(30 BYTE), 
	"SWEEP_UP_TRIGGER_BALANCE" NUMBER(20,5), 
	"SWEEP_UP_THRESHHOLD_BALANCE" NUMBER(20,5), 
	"SWEEP_UP_RULE" VARCHAR2(50 BYTE), 
	"SWEEP_UP_INCREMENT_TYPE" VARCHAR2(100 BYTE), 
	"SWEEP_UP_INCREMENT_AMOUNT" NUMBER(20,5), 
	"IS_SWEEP_DOWN_ENABLED" NUMBER(2,0), 
	"SWEEP_DOWN_BALANCE_TO_USE" VARCHAR2(50 BYTE), 
	"SWEEP_DOWN_TRIGGER_BALANCE" NUMBER(20,5), 
	"SWEEP_DOWN_THRESHHOLD_BALANCE" NUMBER(20,5), 
	"SWEEP_DOWN_RULE" VARCHAR2(30 BYTE), 
	"SWEEP_DOWN_INCREMENT_TYPE" VARCHAR2(100 BYTE), 
	"SWEEP_DOWN_INCREMENT_AMOUNT" NUMBER(20,5), 
	"SWEEP_FEE" NUMBER(20,5), 
	"ACCOUNT_ID" VARCHAR2(30 BYTE), 
	"LAST_TRAVERSING_DATE" DATE, 
	"LAST_EXECUTED_DATE" DATE, 
	 CONSTRAINT "SWEEP_INSTRUCTION_PK_DP" PRIMARY KEY ("SWEEP_ID") );

CREATE TABLE "SWEEP_PROTECTING_ACCOUNT" 
   (	"ID" NUMBER(20,0), 
	"PRIORITY" NUMBER(2,0), 
	"SWEEP_INSTRUCTION_ID" NUMBER(20,0), 
	"MINIMUM_SWEEP_AMOUNT" NUMBER(20,5), 
	"MAXIMUM_SWEEP_AMOUNT" NUMBER(20,5), 
	"TARGET_ACCOUNT_CAPACITY" NUMBER(20,5), 
	"SWEEP_VIOLATION_RULE" VARCHAR2(70 BYTE), 
	"ACCOUNT_ID" VARCHAR2(30 BYTE), 
	"LAST_TRAVERSING_DATE" DATE, 
	"LAST_EXECUTED_DATE" DATE, 
	 CONSTRAINT "SWEEP_PROTECTING_ACCOUNT_PK_DP" PRIMARY KEY ("ID"),
	 CONSTRAINT "SWEEP_INSTRUCTION_ID_FK" FOREIGN KEY ("SWEEP_INSTRUCTION_ID")
	  REFERENCES "SWEEP_INSTRUCTION" ("SWEEP_ID") );


CREATE SEQUENCE  "SWEEP_INSTRUCTION_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  "SWEEP_PROTECTION_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

ALTER TABLE ledger_posting_parameters ADD OVER_DRAWN NUMBER default 0;

ALTER TABLE AUTOMATIC_TRANSFER_INSTRUCTION ADD WEEK_END_PROCESSING VARCHAR2(60);

alter table party_address add(ADDITIONAL_NAMES varchar2(1000));

alter table party_address add(SEND_STATEMENT number(1) default 0);

alter table party_address add(PRIMARY_NAME varchar2(100));