DROP TABLE TRANSACTION_POSTTODAY;
-- table for persisting the EntryRecord object
CREATE TABLE TRANSACTION_POSTTODAY(
TRANSACTION_ID          NUMBER(20,0),
AMOUNT                  NUMBER(20,5),
TRANS_CODE              NUMBER(10,0),
INSTITUTION_ID          varchar2(20),
ACCOUNT_NUMBER          varchar2(120),
ACCOUNT_ID              varchar2(120),
ACCOUNT_TYPE_ID         varchar2(3),    
DESCRIPTION             varchar2(400),
EFFECTIVE_DATE          DATE,
ENTRY_DATE              DATE,
POST_STATUS             NUMBER(1),
REASON_ID 		varchar2(10),
REASON_DESCRIPTION 	varchar2(300),
REASON_DETAIL 		varchar2(300),
CHEQUE                  NUMBER(10,0),
LOAN_ENTRY_TYPE_ID      NUMBER(15),   
EVENT_ID                NUMBER(15,0),
FILE_NAME               varchar2(200),
PAYMENT_ID              NUMBER(15,0),
POST_DATE               DATE,
SOURCE_NAME             varchar2(60),
TRACE                   NUMBER(16,0),
BATCH_NUMBER 		varchar2(4),
SERIAL_NUMBER 		NUMBER(8),
COMPANY_NAME 		varchar2(16),
COMPANY_DESCRIPTION 	varchar2(10),
COMPANY_CUST_NUMBER     varchar2(15),
COMPANY_ID              varchar2(10)
);				

ALTER TABLE TRANSACTION_POSTTODAY
	ADD ( CONSTRAINT TRANSACTION_POSTTODAY_PK
	PRIMARY KEY (TRANSACTION_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE );


CREATE SEQUENCE TRANS_ID_SEQ INCREMENT BY 1  START WITH 1  NOMAXVALUE  NOMINVALUE  NOCYCLE  CACHE 20  ORDER;

ALTER TABLE TRANSACTION_POSTTODAY ADD(CONSTRAINT TRANSACTION_POSTDAY_AID_FK FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID));
ALTER TABLE TRANSACTION_POSTTODAY ADD(CONSTRAINT TRANSACTION_POSTDAY_ATID_FK FOREIGN KEY (ACCOUNT_TYPE_ID) REFERENCES ACCOUNT_TYPE_LOOKUP(ACCOUNT_TYPE_ID));
ALTER TABLE TRANSACTION_POSTTODAY ADD(CONSTRAINT TRANSACTION_POSTDAY_ANO_IID_FK FOREIGN KEY (ACCOUNT_NUMBER,INSTITUTION_ID) 
REFERENCES ACCOUNT(ACCOUNT_NO,INSTITUTION_ID));

create index tran_pstdy_dates_iid_ano_idx on transaction_posttoday(EFFECTIVE_DATE, ENTRY_DATE,institution_id,account_number) nologging; 

ALTER TABLE ACCOUNT_HISTORY_ITEM ADD (TRANSACTION_DETAILS varchar2(150));

alter table TRANSACTION_POSTTODAY modify trace varchar2(16);

alter table TRANSACTION_POSTTODAY add (entry_type_id number(10));

alter table TRANSACTION_POSTTODAY drop column LOAN_ENTRY_TYPE_ID;

alter table ENTRY_TYPE add (ACCOUNT_CATEGORY NUMBER(1) default 1);

alter table TRANSACTION_POSTTODAY add REQUIRED_PARAMS varchar2(200);

alter table TRANSACTION_POSTTODAY add (
ACH_TRAN_CODE varchar2(5),
ACH_STANDARD_ENTRY_CLASS_CODE varchar2(15),
ACH_FRABA_ID NUMBER(15,0),
ACH_PROCESSING_DATE DATE,
ACH_DFI_ACCOUNT_NUMBER varchar2(20));

ALTER TABLE PARTY_ASSOC_MAINT_LOG ADD CLAS_TYPE_UPDATE VARCHAR(50);

alter table TRANSACTION_POSTTODAY modify CHEQUE number(20,0);
alter table TRANSACTION_POSTTODAY modify SERIAL_NUMBER number(20,0);
 
alter table ACCOUNT_HISTORY_ITEM modify CHEQUE number(20,0);
