CREATE TABLE "CORESOFT_DEPO_REVISION_ENTITY"
   (	"REV_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"REV_TIMESTAMP" NUMBER(19,0), 
	"USER_NAME" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("REV_ID") );
   
   
CREATE TABLE "CORESOFT_DEPO_REVISION_CHANGES" 
   (	"REV_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ENTITY_NAME" VARCHAR2(255 CHAR), 
	 CONSTRAINT "FK4928130897EBDFCE" FOREIGN KEY ("REV_ID")
	  REFERENCES "CORESOFT_DEPO_REVISION_ENTITY" ("REV_ID") );

CREATE TABLE "STATEMENT_MESSAGE_AUD" 
   (	"STMT_MSG_ID" NUMBER NOT NULL ENABLE, 
	"REV_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"REV_TYPE" NUMBER(3,0), 
	"STMT_MSG_DESC" VARCHAR2(2000 BYTE), 
	"LISTOFSTRINGS_MOD" CHAR(1 CHAR), 
	"REV_END" NUMBER(10,0), 
	"REV_END_TIMESTAMP" TIMESTAMP (6), 
	"STMT_MSG_TYPE" VARCHAR2(50 BYTE), 
	"EFFECTIVE_DATE" DATE, 
	 PRIMARY KEY ("STMT_MSG_ID", "REV_ID") );

CREATE TABLE "PRODUCT_AUD" 
   (	"PRODUCT_UID" NUMBER NOT NULL ENABLE, 
	"REV_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"REV_TYPE" NUMBER(3,0), 
	"REV_END" NUMBER(10,0), 
	"REV_END_TIMESTAMP" TIMESTAMP (6), 
	"PROD_SUB_TYPE_ID" NUMBER(15,0), 
	"PRODUCT_TYPE_ID" NUMBER(15,0), 
	 PRIMARY KEY ("PRODUCT_UID", "REV_ID"));

CREATE TABLE "PRODUCT_FEATURE_AUD" 
   (	"PROD_FEATURE_UID" NUMBER NOT NULL ENABLE, 
	"REV_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"REV_TYPE" NUMBER(3,0), 
	"REV_END" NUMBER(10,0), 
	"REV_END_TIMESTAMP" TIMESTAMP (6), 
	"PRIORITY" NUMBER, 
	"PRODUCT_UID" NUMBER(15,0), 
	"FEATURE_UID" NUMBER(15,0), 
	"PRIORITY_MOD" NUMBER(1,0), 
	"VALID_VALUES" VARCHAR2(2000 BYTE), 
	"IS_MODIFIABLE" NUMBER(1,0), 
	"IS_CONSTANT" NUMBER(1,0), 
	"IS_MANDATORY" NUMBER(1,0), 
	"DEFAULT_VALUE" VARCHAR2(50 BYTE), 
	"DEFAULTVALUE_MOD" CHAR(1 CHAR), 
	"VALIDVALUES_MOD" CHAR(1 CHAR), 
	"MANDATORY_MOD" CHAR(1 CHAR), 
	"CONSTANT_MOD" CHAR(1 CHAR), 
	"OVERRIDABLE_MOD" CHAR(1 CHAR), 
	 PRIMARY KEY ("PROD_FEATURE_UID", "REV_ID") );

CREATE TABLE "PRODUCT_TYPE_AUD" 
   (	"UNIQUE_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"REV_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"REV_TYPE" NUMBER(3,0), 
	"REV_END" NUMBER(10,0), 
	"REV_END_TIMESTAMP" TIMESTAMP (6), 
	"PRODUCT_TYPE_ID" VARCHAR2(30 BYTE), 
	"TYPEID_MOD" CHAR(1 CHAR), 
	"PRODUCT_TYPE_DESC" VARCHAR2(60 BYTE), 
	"DESCRIPTION_MOD" CHAR(1 CHAR), 
	"SHORT_TITLE" VARCHAR2(30 BYTE), 
	"SHORTTITLE_MOD" CHAR(1 CHAR), 
	"CUSTOMER_TYPE" NUMBER(20,0), 
	"IS_NEW_ACCT_ALLOWED" NUMBER(1,0), 
	"NEWACCOUNTALLOWED_MOD" CHAR(1 CHAR), 
	"INSTITUTION_ID" VARCHAR2(30 BYTE), 
	"PRODUCT_CATEGORY" NUMBER(15,0), 
	 PRIMARY KEY ("UNIQUE_ID", "REV_ID") );

 CREATE TABLE "INST_PROD_CAT_CLASS_CODE_AUD" 
   (	"UNIQUE_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"REV_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"REV_TYPE" NUMBER(3,0), 
	"REV_END" NUMBER(10,0), 
	"REV_END_TIMESTAMP" TIMESTAMP (6), 
	"CLASS_CODE" NUMBER(15,0), 
	"CLASSCODE_MOD" CHAR(1 CHAR), 
	"CLASS_CODE_DESC" VARCHAR2(60 BYTE), 
	"CLASSCODEDESCRIPTION_MOD" CHAR(1 CHAR), 
	"INSTITUTION_ID" VARCHAR2(30 BYTE), 
	"PRODUCT_CATEGORY_ID" NUMBER(15,0), 
	 PRIMARY KEY ("UNIQUE_ID", "REV_ID"));

CREATE TABLE "IRA_DISTRIBUTION_REASON_AUD" 
   (	"REASON_ID" NUMBER NOT NULL ENABLE, 
	"REV_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"REV_TYPE" NUMBER(3,0), 
	"REV_END" NUMBER(10,0), 
	"REV_END_TIMESTAMP" TIMESTAMP (6), 
	"REASON_CODE" VARCHAR2(255 CHAR), 
	"REASON_DESC" VARCHAR2(255 CHAR), 
	"CD_DEBIT_TRANCODE" NUMBER(10,0), 
	"CDDEBITTRANCODE_MOD" CHAR(1 CHAR), 
	"SAVINGS_CREDIT_TRANCODE" NUMBER(10,0), 
	"SAVINGSCREDITTRANCODE_MOD" CHAR(1 CHAR), 
	"CHECKING_CREDIT_TRANCODE" NUMBER(10,0), 
	"CHECKINGCREDITTRANCODE_MOD" CHAR(1 CHAR), 
	 PRIMARY KEY ("REASON_ID", "REV_ID") );

CREATE TABLE "ZONE_AUD" 
   (	"ZONE_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"REV_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"REV_TYPE" NUMBER(3,0), 
	"REV_END" NUMBER(10,0), 
	"REV_END_TIMESTAMP" TIMESTAMP (6), 
	"ZONE_NAME" VARCHAR2(50 BYTE), 
	"ZONENAME_MOD" CHAR(1 CHAR), 
	"INSTITUTION_ID" NUMBER(12,0), 
	 PRIMARY KEY ("ZONE_ID", "REV_ID") );

CREATE TABLE "SAVINGS_PLAN_CONTR_CONFIG_AUD" 
   (	"UNIQUE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"REV_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"REV_TYPE" NUMBER(3,0), 
	"REV_END" NUMBER(10,0), 
	"REV_END_TIMESTAMP" TIMESTAMP (6), 
	"ASSESSMENT_YEAR" NUMBER(10,0), 
	"ASSESSMENTYEAR_MOD" CHAR(1 CHAR), 
	"CONTRIBUTION_LIMIT" NUMBER, 
	"CONTRIBUTIONLIMIT_MOD" CHAR(1 CHAR), 
	"MAX_CONT_AMT_GTR_AGE_FOR_CATUP" NUMBER, 
	"MAXCONTAMTGTAGEFORCATUP_MOD" CHAR(1 CHAR), 
	"SAVINGS_PLAN_TYPE_ID" NUMBER, 
	 PRIMARY KEY ("UNIQUE_ID", "REV_ID") );

CREATE TABLE "INSTITUTION_INT_CODES_AUD" 
   (	"REV_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"INTEREST_CODE_HIST_UID" NUMBER NOT NULL ENABLE, 
	"INSTITUTION_ID" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"REV_TYPE" NUMBER(3,0), 
	"REV_END" NUMBER(10,0), 
	"REV_END_TIMESTAMP" TIMESTAMP (6), 
	 PRIMARY KEY ("REV_ID", "INTEREST_CODE_HIST_UID", "INSTITUTION_ID") );

 CREATE TABLE "INTEREST_CODES_HISTORY_AUD" 
   (	"UNIQUE_ID" NUMBER NOT NULL ENABLE, 
	"REV_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"REV_TYPE" NUMBER(3,0), 
	"REV_END" NUMBER(10,0), 
	"REV_END_TIMESTAMP" TIMESTAMP (6), 
	"INTERESTCODESET_MOD" CHAR(1 CHAR), 
	"RECORDED_DATE" DATE, 
	"EFFECTIVE_DATE" DATE, 
	 PRIMARY KEY ("UNIQUE_ID", "REV_ID") );

CREATE TABLE "INTEREST_CODES_AUD" 
   (	"UNIQUE_ID" NUMBER NOT NULL ENABLE, 
	"REV_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"REV_TYPE" NUMBER(3,0), 
	"REV_END" NUMBER(10,0), 
	"REV_END_TIMESTAMP" TIMESTAMP (6), 
	"INTEREST_CODE_HIST_UID" NUMBER, 
	"INTERESTCODERATES_MOD" CHAR(1 CHAR), 
	"PRODUCT_CATEGORY" NUMBER(5,0), 
	"ACCRUAL_OPTIONS_TITLE" VARCHAR2(60 BYTE), 
	"MAXIMUM_NUMBER_CHECKS" NUMBER(15,0), 
	"MAXIMUMNUMBERCHECKS_MOD" NUMBER(15,0), 
	"BALANCE_TO_ACCRUE_ON" VARCHAR2(30 BYTE), 
	"DAYS_IN_YEAR" NUMBER(5,0), 
	"MINIMUM_RATE" NUMBER(20,5), 
	"BALANCETOACCRUEON_MOD" VARCHAR2(30 BYTE), 
	"DAYSINYEAR_MOD" NUMBER(5,0), 
	"MINIMUMRATE_MOD" NUMBER(20,5), 
	"MAXIMUM_CHECK_CHARGE" NUMBER(20,5), 
	"MAXIMUMCHECKCHARGE_MOD" CHAR(1 CHAR), 
	"MINIMUM_AVERAGE_BALANCE" NUMBER(20,5), 
	"MINIMUMAVERAGEBALANCE_MOD" CHAR(1 CHAR), 
	"INTEREST_DEBIT_TRANCODES" NUMBER(20,0), 
	"INTEREST_CREDIT_TRANCODES" NUMBER(20,0), 
	"INTERESTCREDITTRANCODE_MOD" CHAR(1 CHAR), 
	"INTERESTDEBITTRANCODE_MOD" CHAR(1 CHAR), 
	"INTEREST_CODE" VARCHAR2(30 BYTE), 
	 PRIMARY KEY ("UNIQUE_ID", "REV_ID") );

CREATE TABLE "INTEREST_CODE_RATES_AUD" 
   (	"UNIQUE_ID" NUMBER NOT NULL ENABLE, 
	"REV_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"REV_TYPE" NUMBER(3,0), 
	"REV_END" NUMBER(10,0), 
	"REV_END_TIMESTAMP" TIMESTAMP (6), 
	"INTEREST_RATE" NUMBER(19,2), 
	"INTERESTRATE_MOD" CHAR(1 CHAR), 
	"BALANCE" NUMBER(19,2), 
	"BALANCE_MOD" CHAR(1 CHAR), 
	"INTEREST_CODE_UID" NUMBER, 
	 PRIMARY KEY ("UNIQUE_ID", "REV_ID") );

CREATE TABLE "IRA_DISTRIBUTION_INST_AUD" 
   (	"DIST_INST_ID" NUMBER NOT NULL ENABLE, 
	"REV_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"REV_TYPE" NUMBER(3,0), 
	"REV_END" NUMBER(10,0), 
	"REV_END_TIMESTAMP" TIMESTAMP (6), 
	"INSTITUTION_ID" VARCHAR2(255 CHAR), 
	"WITHHELD_STATE" VARCHAR2(255 CHAR), 
	"WITHHELDSTATE_MOD" CHAR(1 CHAR), 
	"TAX_WITHHELD" VARCHAR2(255 CHAR), 
	"WITHHOLDTAX_MOD" CHAR(1 CHAR), 
	"SAVINGS_PLAN_NUMBER" VARCHAR2(255 CHAR), 
	"SAVINGSPLANNUMBER_MOD" CHAR(1 CHAR), 
	"DISTRIBUTION_AMOUNT" NUMBER(19,2), 
	"DISTRIBUTIONAMOUNT_MOD" CHAR(1 CHAR), 
	"EXCESS_CONTRIBUTION_YEAR" VARCHAR2(255 CHAR), 
	"YEAREXCESSCONTRIBUTION_MOD" CHAR(1 CHAR), 
	"EXCESS_CONTRIBUTION_AMOUNT" NUMBER(19,2), 
	"EXCESSCONTRIBUTIONAMOUNT_MOD" CHAR(1 CHAR), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVESTARTDATE_MOD" CHAR(1 CHAR), 
	"NEXT_DISTRIBUTION_DATE" DATE, 
	"NEXTDISTRIBUTIONDATE_MOD" CHAR(1 CHAR), 
	"DISTRIBUTION_FREQUENCY" NUMBER(10,0), 
	"DISTRIBUTIONFREQUENCY_MOD" CHAR(1 CHAR), 
	"DISTRIBUTION_DAY_OF_MONTH" NUMBER(10,0), 
	"DISTRIBUTIONDAYOFMONTH_MOD" CHAR(1 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIEDBY_MOD" CHAR(1 CHAR), 
	"FEDERAL_TAX_RATE" NUMBER(19,2), 
	"FEDERALTAXPERCENTAGE_MOD" CHAR(1 CHAR), 
	"STATE_TAX_RATE" NUMBER(19,2), 
	"STATETAXPERCENTAGE_MOD" CHAR(1 CHAR), 
	"FEDERAL_TAX_AMOUNT" NUMBER(19,2), 
	"FEDINCOMETAXAMOUNT_MOD" CHAR(1 CHAR), 
	"STATE_TAX_AMOUNT" NUMBER(19,2), 
	"STATEINCOMETAXAMOUNT_MOD" CHAR(1 CHAR), 
	"REASON_ID" NUMBER, 
	"DISTRIBUTIONREASON_MOD" CHAR(1 CHAR), 
	"DISTRIBUTION_SEQ_ID" NUMBER, 
	"DISTRIBUTIONSEQUENCE_MOD" CHAR(1 CHAR), 
	 PRIMARY KEY ("DIST_INST_ID", "REV_ID") );

CREATE TABLE "IRA_DISTRIBUTION_SEQUENCE_AUD" 
   (	"SIMPLE_DIST_ID" NUMBER NOT NULL ENABLE, 
	"REV_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"REV_TYPE" NUMBER(3,0), 
	"REV_END" NUMBER(10,0), 
	"REV_END_TIMESTAMP" TIMESTAMP (6), 
	"CDACCOUNTS_MOD" CHAR(1 CHAR), 
	 PRIMARY KEY ("SIMPLE_DIST_ID", "REV_ID") );

CREATE TABLE "IRA_CDORDERING_SEQUENCE_AUD" 
   (	"SEQUENCE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"REV_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"REV_TYPE" NUMBER(3,0), 
	"REV_END" NUMBER(10,0), 
	"REV_END_TIMESTAMP" TIMESTAMP (6), 
	"SEQUENCE_NUMBER" NUMBER, 
	"SEQUENCENUMBER_MOD" CHAR(1 CHAR), 
	"ACCOUNT_ID" NUMBER(19,0), 
	"DIST_SEQ_ID" NUMBER(10,0), 
	"SIMPLEDISTSEQ_MOD" CHAR(1 CHAR), 
	 PRIMARY KEY ("SEQUENCE_ID", "REV_ID") );

CREATE TABLE "PLAN_APPLICABLE_PRODUCTS_AUD" 
   (	"UNIQUE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"REV_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"REV_TYPE" NUMBER(3,0), 
	"REV_END" NUMBER(10,0), 
	"REV_END_TIMESTAMP" TIMESTAMP (6), 
	"MASTER_PRODUCT_UID" NUMBER, 
	"SAVINGSPLANPRODUCT_MOD" CHAR(1 CHAR), 
	"PRODUCT_UID" NUMBER, 
	"CDPRODUCT_MOD" CHAR(1 CHAR), 
	 PRIMARY KEY ("UNIQUE_ID", "REV_ID") );

CREATE TABLE "TPT_TXN_REVIEW_VW_AUD" 
   (	"TRANSACTION_ID" NUMBER NOT NULL ENABLE, 
	"REV_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"REV_TYPE" NUMBER(3,0), 
	"REV_END" NUMBER(10,0), 
	"REV_END_TIMESTAMP" TIMESTAMP (6), 
	"ACCOUNT_NUMBER" VARCHAR2(255 CHAR), 
	"AMOUNT" NUMBER(19,2), 
	"STATE" VARCHAR2(255 CHAR), 
	"STATE_MOD" CHAR(1 CHAR), 
	"REASON_DESCRIPTION" VARCHAR2(255 CHAR), 
	"DECISION_TYPE" NUMBER(10,0), 
	"WAIVE_FEE" NUMBER(10,0), 
	"REMARKS" VARCHAR2(255 CHAR), 
	"DECISION_MOD" CHAR(1 CHAR), 
	"INSTITUTION_ID" VARCHAR2(255 CHAR), 
	"OPERATOR_ID" VARCHAR2(255 CHAR), 
	"BRANCH_NAME" VARCHAR2(255 CHAR), 
	"SOURCE_NAME" VARCHAR2(255 CHAR), 
	"OPERATORID_MOD" CHAR(1 CHAR), 
	"BRANCH_ID" VARCHAR2(30 BYTE), 
	"ACCOUNT_ID" VARCHAR2(30 BYTE), 
	 PRIMARY KEY ("TRANSACTION_ID", "REV_ID") );   
	 
	 CREATE TABLE "PRODUCT_FORM_TEMPLATE_AUD" 
   (	"PROD_FORM_TEMP_UID" NUMBER(15,0) NOT NULL ENABLE, 
	"REV_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"REV_TYPE" NUMBER(3,0), 
	"REV_END" NUMBER(10,0), 
	"REV_END_TIMESTAMP" TIMESTAMP (6), 
	"IS_SCANNABLE" NUMBER(1,0), 
	"SCANNABLE_MOD" CHAR(1 CHAR), 
	"UNIQUE_FORM_ID" NUMBER(15,0), 
	"PRODUCT_UID" NUMBER(15,0), 
	 PRIMARY KEY ("PROD_FORM_TEMP_UID", "REV_ID") );


ALTER TABLE INTEREST_CODES_AUD ADD COMPOUND_INTEREST number(1,0);

ALTER TABLE INTEREST_CODES_AUD ADD INTERESTCODEDESCRIPTION_MOD char(1 char);

ALTER TABLE INTEREST_CODES_AUD ADD INTERESTCOMPOUNDED_MOD char(1 char);


alter table interest_code_rates_aud rename column INTEREST_RATE to INTEREST_RATE_OLD;

alter table interest_code_rates_aud add INTEREST_RATE NUMBER(20,5);

update interest_code_rates_aud set INTEREST_RATE = INTEREST_RATE_OLD;

alter table interest_code_rates_aud drop column INTEREST_RATE_OLD;

alter table interest_code_rates_aud rename column BALANCE to BALANCE_OLD;

alter table interest_code_rates_aud add BALANCE NUMBER(20,5);

update interest_code_rates_aud set BALANCE = BALANCE_OLD;

alter table interest_code_rates_aud drop column BALANCE_OLD;
