 --BACKUP WITHHOLDING SCRIPTS
  
  CREATE TABLE "BACKUP_WITHHOLDING" 
   (	"BKP_WITH_HOLD_ID" NUMBER(15,0) NOT NULL, 
	"CUSTOMER_ID" NUMBER(15,0) NOT NULL , 
        "NOTIFICATION_TYPE" VARCHAR2(30) , 
                
        "NOTIFICATION_DATE" DATE, 
        "TAX_YEAR" NUMBER(4) , 
          
        "NOTICE_PRINT_DATE" DATE, 
        "STATUS" NUMBER(2) DEFAULT 1,
        
	 CONSTRAINT "BACKUP_WITHHOLDING_PK" PRIMARY KEY ("BKP_WITH_HOLD_ID"),
         CONSTRAINT "BACKUP_WITHHOLDING_UAFK" FOREIGN KEY ("CUSTOMER_ID")
         REFERENCES "PARTY_INSTITUTION_ASSOCIATION" ("UNIQUE_ASSOCIATION_ID") 
   );


   CREATE  SEQUENCE BKP_WITH_HOLD_ID_SEQ  START WITH 1  INCREMENT BY 1;

   ALTER TABLE DEPOSIT_ACCOUNT ADD(
	YTD_BKP_WITHHOLDING NUMBER(10,5) DEFAULT 0,
	QTD_BKP_WITHHOLDING NUMBER(10,5)  DEFAULT 0,
	PRIOR_YR_BKP_WITHHOLDING NUMBER(10,5) DEFAULT 0,
	MTD_BKP_WITHHOLDING NUMBER(10,5) DEFAULT 0,
	UNREMITTED_BKP_WTHOLD_AMT NUMBER(10,5) DEFAULT 0,
	LAST_REMITTED_DATE DATE, 
	LAST_REMITTED_AMT NUMBER(10,5) DEFAULT  0);

  ALTER TABLE PARTY_INSTITUTION_ASSOCIATION ADD  BACKUP_WITHHOLDING_STATUS  NUMBER(15,2) DEFAULT 1;

--  UPDATE DEPOSIT_ACCOUNT SET BACKUP_WITH_HOLDING='0'
  
  CREATE SEQUENCE "HIBERNATE_SEQUENCE" MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCYCLE CACHE 20 NOORDER;
 
ALTER TABLE DEPOSIT_ACCOUNT ADD BKP_WITHHOLDING_STATUS  NUMBER(15) DEFAULT 1;