--PRODUCT PARAMETERS SCRIPTS

 CREATE TABLE PROD_CAT_DEF_FEATURES(
	UNIQUE_ID NUMBER(15,0) NOT NULL ,
	FEATURE_UID NUMBER(15,0),
	PRODUCT_CATEGORY  NUMBER(15,0) NOT NULL,
	VALID_VALUES VARCHAR2(2000),
	DEFAULT_VALUE VARCHAR2(50),
	IS_MANDATORY NUMBER(1,0),
	PRIORITY NUMBER(15,0),
	IS_CONSTANT NUMBER(1,0),
	IS_MODIFIABLE NUMBER(1,0),
	
	CONSTRAINT "PROD_CAT_DEF_FEATURES_PK" PRIMARY KEY ("UNIQUE_ID"),
	CONSTRAINT "FK_PROD_CAT_DEF_FEATURES" FOREIGN KEY ("FEATURE_UID")
	REFERENCES FEATURE ("FEATURE_UID")
 );

 CREATE SEQUENCE PROD_CAT_DEF_FEAT_SEQ START WITH 1 INCREMENT BY 1;
