CREATE OR REPLACE FORCE VIEW LOAN_ACCOUNT_HISTORY_ITEM_VW ("TRANSACTION_ID", "AMOUNT", "ACCOUNT_ID", "DESCRIPTION", "POST_DATE", "EFFECTIVE_DATE", "TRAN_CODE", "INSTITUTION_ID", "LOAN_ENTRY_TYPE_ID", "EVENT_TYPE_ID", "ENTRY_DATE", "PARENT_TRANSACTION_ID", "TRANSACTION_DETAILS", "STMT_DESC", "EVENT_ID", "SEQUENCE_NO")
AS
 SELECT TRANSACTION_ID,
   AMOUNT,
   ACCOUNT_ID,
   DESCRIPTION,
   POST_DATE,
   EFFECTIVE_DATE,
   TRAN_CODE,
   INSTITUTION_ID,
   LOAN_ENTRY_TYPE_ID,
   EVENT_TYPE_ID,
   ENTRY_DATE,
   PARENT_TRANSACTION_ID,
   TRANSACTION_DETAILS,
   STMT_DESC,
   EVENT_ID,
   SEQUENCE_NO
 from LOAN_ACCOUNT_HISTORY_ITEM
 where TRAN_CODE in ('1801', '1802', '1803', '1804', '1805', '1806', '1809', '1836', '1901', '1902', '1903', '1904', '1905', '1906', '1909', '1936', '1950', '1850','1841','1941');
