CREATE TABLE "DEBITCARD_ACCOUNTS_AUD"
  (
    "UNIQUE_ID" NUMBER NOT NULL ENABLE,
    "REV_ID"    NUMBER(10,0) NOT NULL ENABLE,
    "REV_TYPE"  NUMBER(3,0),
    "ACCOUNT_NUMBER" VARCHAR2(12 BYTE),
    "SUBCRIPTION_ID" VARCHAR2(20 BYTE),
    "IS_PRIMARY"     NUMBER DEFAULT 0,
    "UPDATED_DATE" DATE,
    PRIMARY KEY ("UNIQUE_ID", "REV_ID")
);


INSERT INTO ACTIVITY_CATEGORY_MAPPING(ACTIVITY_TYPE,ACTIVITY_DESC,ACTIVITY_CATEGORY) VALUES(025,'Delete Account','Account');

ALTER TABLE DEBITCARD_ACCOUNTS ADD UPDATED_DATE DATE; 