--ALTER TABLE DEBITCARD_SUBSCRIPTION DROP COLUMN PRIMARY_ACCOUNT_NUMBER;

ALTER TABLE DEBITCARD_SUBSCRIPTION DROP COLUMN PRIMARY_ACCOUNT_ID;

CREATE TABLE DEBITCARD_ACCOUNTS
("UNIQUE_ID"  NUMBER(12,0) NOT NULL ENABLE,
"ACCOUNT_NUMBER" VARCHAR2(20 BYTE),
"SUBCRIPTION_ID" VARCHAR2(20 BYTE),
"ACCOUNT_TYPE"   VARCHAR2(20 BYTE),
"IS_PRIMARY" NUMBER DEFAULT 0,
CONSTRAINT "DEBITCARD_ACCOUNTS_PK" PRIMARY KEY ("UNIQUE_ID"));

CREATE SEQUENCE "DEBITCRDACCID_SEQ"  INCREMENT BY 1 ;