DELETE FROM ACTIVITY_CATEGORY_MAPPING WHERE ACTIVITY_tYPE='025';

INSERT INTO ACTIVITY_CATEGORY_MAPPING (ACTIVITY_TYPE, ACTIVITY_DESC, ACTIVITY_CATEGORY) 
VALUES('001', 'Add Account','Account');
INSERT INTO ACTIVITY_CATEGORY_MAPPING (ACTIVITY_TYPE, ACTIVITY_DESC, ACTIVITY_CATEGORY) 
VALUES('002', 'Status Account','Account');
INSERT INTO ACTIVITY_CATEGORY_MAPPING(ACTIVITY_TYPE,ACTIVITY_DESC,ACTIVITY_CATEGORY) 
VALUES('025','Delete Account','Account');
INSERT INTO ACTIVITY_CATEGORY_MAPPING (ACTIVITY_TYPE, ACTIVITY_DESC, ACTIVITY_CATEGORY) 
VALUES('050', 'Cardholder Name Change','Card');
INSERT INTO ACTIVITY_CATEGORY_MAPPING (ACTIVITY_TYPE, ACTIVITY_DESC, ACTIVITY_CATEGORY) 
VALUES('051', 'Cardholder Address Line Change','Card');
INSERT INTO ACTIVITY_CATEGORY_MAPPING (ACTIVITY_TYPE, ACTIVITY_DESC, ACTIVITY_CATEGORY) 
VALUES('052', 'Cardholder Phone Number Change','Card');
INSERT INTO ACTIVITY_CATEGORY_MAPPING (ACTIVITY_TYPE, ACTIVITY_DESC, ACTIVITY_CATEGORY) 
VALUES('053', 'Cardholder City/State/Zip/CountryCode','Card');
INSERT INTO ACTIVITY_CATEGORY_MAPPING (ACTIVITY_TYPE, ACTIVITY_DESC, ACTIVITY_CATEGORY) 
VALUES('116', 'Change Limit Group Name','Card');
INSERT INTO ACTIVITY_CATEGORY_MAPPING (ACTIVITY_TYPE, ACTIVITY_DESC, ACTIVITY_CATEGORY) 
VALUES('222', 'Cardholder Phone Number Change','Card');
INSERT INTO ACTIVITY_CATEGORY_MAPPING (ACTIVITY_TYPE, ACTIVITY_DESC, ACTIVITY_CATEGORY) 
VALUES('233', 'Update Emboss Name','Card');
INSERT INTO ACTIVITY_CATEGORY_MAPPING (ACTIVITY_TYPE, ACTIVITY_DESC, ACTIVITY_CATEGORY) 
VALUES('239', 'Update Validation Data - Drivers License','Card');
