-----------------Maximum Num of days for Renewal---------------------
INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
  VALUES(PROPDEFID_SEQ.nextval,(select max(ENTITY_TYPE_DEFINITION_ID) from entity_type_definition where type_name like 'LoanContract'), 'MaxDaysonPostRenewal', 12, 'Max Days Allowed to Post Renewal', 1, 1, 0, NULL, 0, 'java.lang.Integer:{default={}}', 0, 0, 0, 0, 1, 0, 0, 'UC', 0, 0);

INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
  VALUES(PROPDEFID_SEQ.currval, 0, 0, 1, 0, 'DEFAULT'); 
INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
  VALUES(PROPDEFID_SEQ.currval, 0, 0, 0, 0, 'INQUIRY'); 
INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
  VALUES(PROPDEFID_SEQ.currval, 0, 0, 1, 0, 'ACCOUNT_CREATED'); 

--RenewalPostMaturity for LoanRenewal
INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
  VALUES((select max(property_definition_id)+1 from property_definition), (select max(ENTITY_TYPE_DEFINITION_ID) from entity_type_definition where type_name like 'LoanContract'), 'RenewalPostMaturity',13, 'Allow Loan Renewal Post Maturity', 0, 0, 0, 'java.lang.Boolean:true', 0, 'java.lang.Boolean:{default={true=Yes, false=No}}', 0, 0, 0, 0, 1, 0, 0, 'UC', NULL, NULL);

  INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
  VALUES((select max(property_definition_id) from property_definition), 0, 0, 1, 0, 'DEFAULT'); 
INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
  VALUES((select max(property_definition_id) from property_definition), 0, 0, 1, 0, 'INQUIRY');
INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
  VALUES((select max(property_definition_id) from property_definition), 0, 0, 1, 0, 'ACCOUNT_CREATED');
  
  --ADDING COLUMN TO LOAN_RENEWAL_EVENT FOR RENEWAL HISTORY
  ALTER TABLE LOAN_RENEWAL_EVENT ADD RENEWAL_FEES NUMBER(20,5);
  ALTER TABLE RENEWAL_NEW ADD RENEWAL_FEES NUMBER(20,5);
  ALTER TABLE RENEWAL_HISTORY ADD RENEWAL_FEES NUMBER(20,5);
  
  UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_MATURITY_DATE=1 WHERE POSTING_RULE_ID='8843';
  UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_ORG_LOAN_TERM=1 WHERE POSTING_RULE_ID='8843';
  UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_DATE_NEXT_DUE=1 WHERE POSTING_RULE_ID='8843';
  UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_SCHD_PYMNT_DUE_DATE=1 WHERE POSTING_RULE_ID='8843';

  
 --updating the credit or debit value as 1 for LoanRenewal.
  UPDATE LOAN_EVENT_TYPE SET DEBIT_OR_CREDIT=1 WHERE EVENT_TYPE_ID='43';
  
  --Adding Account number column to LoanRenewalEvent
  ALTER TABLE LOAN_RENEWAL_EVENT ADD ACCOUNT_NO VARCHAR2(30);
  