CREATE TABLE LOAN_ACCOUNT_BALANCE_HISTORY (
ID NUMBER(5),
ACCOUNT_NUMBER VARCHAR2(30 BYTE),
ACCOUNT_ID VARCHAR2(30 BYTE),
BALANCE_DATE DATE,
POSTED_DATE DATE,
PRINCIPAL_OUTSTANDING NUMBER(20,5),
ACCRUED_INTEREST_DUE NUMBER(20,5),
CONSTRAINT DAYBAL_PKEY PRIMARY KEY ("ID","ACCOUNT_ID", "BALANCE_DATE", "POSTED_DATE"));

CREATE SEQUENCE DAILY_BALANCE_HISTORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;