CREATE TABLE DEBT_OBLIGATOR_INFO(SSN_TIN VARCHAR2(15),
STATE_PASS_BACK_INFO VARCHAR2(15),
FIRST_NAME VARCHAR2(25),
LAST_NAME VARCHAR2(25),
CASE_PASS_BACK_INFO VARCHAR2(25),
FIPS_PASS_BACK_INFO VARCHAR2(10),
ADD_STATE_BACK_INFO VARCHAR2(30),
MATCH_FLAG_INFO VARCHAR2(10));