--LIMIT_GROUP table create script.
CREATE TABLE LIMIT_GROUP ( 
    LIMIT_GROUP_ID	NUMBER(12,0) NOT NULL,
    NAME          	VARCHAR2(50) NOT NULL,
    DESCRIPTION   	VARCHAR2(50) NOT NULL,
    PRIMARY KEY(LIMIT_GROUP_ID)
);
----DEBITCARD_SUBSCRIPTION_TYPE table create script.
    CREATE TABLE DEBITCARD_SUBSCRIPTION_TYPE ( 
    TYPE_ID       	NUMBER(12,0) NOT NULL,
    NAME          	VARCHAR2(50) NOT NULL,
    DESCRIPTION   	VARCHAR2(50) NOT NULL,
    REISSUE_TERM  	NUMBER(3,0) NULL,
    LIMIT_GROUP_ID	NUMBER(12,0) NOT NULL,
    PRIMARY KEY(TYPE_ID)
);
    
--SUBSCRIBER table Create script
    CREATE TABLE SUBSCRIBER ( 
    SUBSCRIBER_ID	NUMBER(12,0) NOT NULL,
    PARTY_ID     	NUMBER(12,0) NOT NULL,
    PRIMARY KEY(SUBSCRIBER_ID)
);
  
--DEBITCARD_SUBSCRIPTION table create script
 CREATE TABLE DEBITCARD_SUBSCRIPTION ( 
    SUBCRIPTION_ID        	NUMBER(12,0) NOT NULL,
    SUBSCRIPTION_NUMBER   	VARCHAR2(19) NULL,
    TYPE_ID               	NUMBER(12,0) NOT NULL,
    SUBSCRIBER_ID         	NUMBER(12,0) NOT NULL,
    BANK_ID               	VARCHAR2(12) NOT NULL,
    PRIMARY_ACCOUNT_NUMBER	VARCHAR2(12) NOT NULL,
    PRIMARY_USER_ID       	NUMBER(12,0) NULL,
    STATUS                	VARCHAR2(30) NOT NULL,
    STATUS_TIME           	TIMESTAMP(6) NOT NULL,
    EXPIRATION_DATE       	DATE NULL,
    PRIOR_EXPIRATION_DATE 	DATE NULL,
    REISSUE_TERM          	NUMBER(3,0) NULL,
    LIMIT_GROUP_ID        	NUMBER(12,0) NOT NULL,
    DATE_SUBSCRIBED       	DATE NULL,
    LAST_UPDATED_BY       	VARCHAR2(30) NOT NULL,
    LAST_UPDATION_TIME    	TIMESTAMP(6) NOT NULL,
    ACTIVATED             	NUMBER(1,0) NULL,
    ACTIVATION_TIME       	TIMESTAMP(6) NULL,
    ORDERED_TIME          	TIMESTAMP(6) NULL,
    ORDERED_BY            	VARCHAR2(30) NULL,
    ORDERED_FROM          	NUMBER(10,0) NULL,
    PRE_APPROVED          	NUMBER(1,0) NULL,
    PRE_APPROVED_TIME     	TIMESTAMP(6) NULL,
    REJECTED_TIME         	TIMESTAMP(6) NULL,
    REJECT_REMARKS        	VARCHAR2(50) NULL,
    REJECTED_BY_BRANCH    	NUMBER(10,0) NULL,
    LAST_USED_DATE_TIME   	TIMESTAMP(6) NULL,
    BEFORE_GO_LIVE        	NUMBER(1,0) NULL,
    PRIMARY KEY(SUBCRIPTION_ID)
);

--DEBITCARD_USER table

CREATE TABLE DEBITCARD_USER ( 
	USER_ID      	NUMBER(12,0) NOT NULL,
	PARTY_ID     	NUMBER(12,0) NOT NULL,
	EMBOSS_LINE1 	VARCHAR2(100) NULL,
	EMBOSS_LINE2 	VARCHAR2(100) NULL
	);

ALTER TABLE DEBITCARD_USER
	ADD ( CONSTRAINT DBC_USER_PK
	PRIMARY KEY (USER_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE );

--ALTER DEBITCARD_SUBSCRIPTION SCRIPTS

ALTER TABLE DEBITCARD_SUBSCRIPTION ADD PRIMARY_ACCOUNT_ID VARCHAR2(30);
alter table DEBITCARD_SUBSCRIPTION add constraint ACCOUNT_ID_FK foreign key(PRIMARY_ACCOUNT_ID) references account(ACCOUNT_ID);

--Alter for CORE_PARTY_ID
ALTER TABLE DEBITCARD_USER ADD CORE_PARTY_ID VARCHAR2(30);
ALTER TABLE SUBSCRIBER ADD CORE_PARTY_ID VARCHAR2(30);

--ALTER TABLE SUBSCRIBER MODIFY PARTY_ID NULL;

ALTER TABLE SUBSCRIBER MODIFY PARTY_ID NULL;
	
	
--SEQUENCES Create Scripts
CREATE SEQUENCE LIMITGRPID_SEQ START WITH 21 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SUBSCRIPTION_SEQ START WITH 59265 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SUBS_TYPEID_SEQ START WITH 21 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE UZERID_SEQ START WITH 59303 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SUBSCRIBERID_SEQ START WITH 59564 INCREMENT BY 1 NOCACHE NOCYCLE;
