CREATE TABLE PREASSESSMENT_CHECK_MASTER
(UNIQUE_ID NUMBER(30,0) NOT NULL ENABLE,
CHECK_NAME VARCHAR2(100),
CONSTRAINT "PREASSESSMENT_CHECK_MASTER_PK" PRIMARY KEY ("UNIQUE_ID") ENABLE );

CREATE TABLE PREASSESSMENT_CRITERIA_MASTER
(UNIQUE_ID NUMBER(30,0) NOT NULL ENABLE,
CRITERIA_NAME VARCHAR2(100),
CONSTRAINT "PREASS_CRITERIA_MASTER_PK" PRIMARY KEY ("UNIQUE_ID") ENABLE );

CREATE TABLE PREASSESSMENT_CRITERIA_MAPPING
(
   UNIQUE_ID NUMBER(30,0) NOT NULL ENABLE, 
   CHECK_ID NUMBER(30,0),
   CRITERIA_ID NUMBER(30,0),
   CONSTRAINT "PREASS_CRITERIA_MAPPING_PK" PRIMARY KEY ("UNIQUE_ID") ENABLE ,
   CONSTRAINT "PREASS_CHECK_MASTER_FK" FOREIGN KEY ("CHECK_ID") REFERENCES "PREASSESSMENT_CHECK_MASTER" ("UNIQUE_ID") ENABLE,
   CONSTRAINT "PREASS_CRITERIA_MASTER_FK" FOREIGN KEY ("CRITERIA_ID") REFERENCES "PREASSESSMENT_CRITERIA_MASTER" ("UNIQUE_ID") ENABLE);
   
   
create sequence PREASSESSMENT_CHECK_SEQ minvalue 1 maxvalue 9999999999 increment by 1 start with 1;
create sequence PREASSESSMENT_CRITERIA_SEQ minvalue 1 maxvalue 9999999999 increment by 1 start with 1;  
create sequence PREASS_CRITERIA_MAPPING_SEQ minvalue 1 maxvalue 9999999999 increment by 1 start with 1;