
alter table FEE_PACKAGE_PRODUCTS drop column SAVINGS_PRODUCT;
alter table FEE_PACKAGE_PRODUCTS drop column CHECKING_PRODUCT;

alter table FEE_PACKAGE_PRODUCTS add PRODUCT_ID VARCHAR2(30);
alter table FEE_PACKAGE_PRODUCTS add PRODUCT_TYPE VARCHAR2(30);