create table SERVICE_REQUEST_TRANCODE
  ("UNIQUE_ID" NUMBER(30,0) NOT NULL ENABLE,
   "SERVICE_REQUEST_ID" NUMBER(30,0) NOT NULL ENABLE, 
   "TRAN_CODE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
   "TRANCODE_CATEGORY" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
   CONSTRAINT "SER_REQ_ID_FK" FOREIGN KEY ("SERVICE_REQUEST_ID") REFERENCES "SERVICE_REQUEST" ("SERVICE_REQUEST_ID") ENABLE);


create table FEE_PACKAGE_PRODUCTS
  ("UNIQUE_ID" NUMBER(30,0) NOT NULL ENABLE,
   "SAVINGS_PRODUCT" NUMBER(30,0), 
   "CHECKING_PRODUCT" NUMBER(30,0), 
   "FEE_PKG_ID"  NUMBER(30),
   CONSTRAINT "FEE_PACKAGE_PRODUCTS_PK" PRIMARY KEY ("UNIQUE_ID") ENABLE,
   CONSTRAINT "FEE_PKG_ID_PRODS_FK" FOREIGN KEY ("FEE_PKG_ID") REFERENCES "FEE_PACKAGE" ("FEE_PKG_ID") ENABLE);

--alter table package_line_item add SAVINGS_TRAN_CODE NUMBER(10);
--alter table package_line_item add CHEKING_TRAN_CODE NUMBER(10);
--alter table package_line_item add SERVICE_REQUEST_ID NUMBER(10);
alter table package_line_item add PRE_ASSE_CHECK_ID NUMBER(30);
alter table package_line_item add PRE_ASSE_CRITERIA_ID NUMBER(30);
alter table package_line_item add PRE_ASSE_VALUE NUMBER(30);
alter table SRVC_CHRG_ACC_INSTANCE add  EXPIRY_DATE DATE;
alter table SRVC_CHRG_ACC_INSTANCE add  PKG_LINE_ITEM_NAME VARCHAR2(100);
alter table SRVC_CHRG_ACC_INSTANCE add  SERVICE_REQUEST_NAME VARCHAR2(100);
