CREATE TABLE ACCOUNT_ALERT
(
    ACCOUNT_ALERT_ID    VARCHAR2(200) NOT NULL,
    ACCOUNT_OR_CUST_ID  VARCHAR2(30) NOT NULL,
    ALERT_TYPE_ID       NUMBER(38,0),
    DND_FROM            VARCHAR2(30),
    DND_TO              VARCHAR2(30),
    DATE_LAST_SENT      DATE,
    DATE_LAST_MODIFIED  DATE,
    ALERT_TO            NUMBER(38,0),    
    CONSTRAINT "ALERT_PK" PRIMARY KEY ("ACCOUNT_ALERT_ID")
);

CREATE TABLE ALERT_PARAMETER
(
    ALERT_PARAMETER_ID  VARCHAR2(200) NOT NULL,
    ACCOUNT_ALERT_ID    VARCHAR2(200) NOT NULL,
    PARAMETER_VALUE     VARCHAR2(50),
    CONSTRAINT "ALERT_PARAM_PK" PRIMARY KEY ("ALERT_PARAMETER_ID", "ACCOUNT_ALERT_ID"),
    CONSTRAINT "ALERT_PARAM_FK" FOREIGN KEY ("ACCOUNT_ALERT_ID") REFERENCES ACCOUNT_ALERT (ACCOUNT_ALERT_ID)
);

CREATE SEQUENCE ACCOUNT_ALERT_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999999 
INCREMENT BY 1 CACHE 20 NOORDER NOCYCLE;