--script added for following fields effected for LoanPayOff
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_NA_PRINCIPAL_BALANCE=1 WHERE POSTING_RULE_ID='8883';
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_NA_INTEREST_PAID=1 WHERE POSTING_RULE_ID='8883';
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_NA_UNPAID_INTEREST=1 WHERE POSTING_RULE_ID='8883';
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_NA_NET=1 WHERE POSTING_RULE_ID='8883';
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_CHARGE_OFF_PRINCIPAL=1 WHERE POSTING_RULE_ID='8883';
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_CHARGE_OFF_INTEREST=1 WHERE POSTING_RULE_ID='8883';
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_CHARGE_OFF_INTEREST_PAID=1 WHERE POSTING_RULE_ID='8883';
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_CHARGE_OFF_NET=1 WHERE POSTING_RULE_ID='8883';