INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (063,(SELECT unique_id FROM entry_type WHERE ID='1917'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (263,(SELECT unique_id FROM entry_type WHERE ID='1817'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_AMORTIZED_BALANCE=1 WHERE POSTING_RULE_ID=8863;

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (063,(SELECT unique_id FROM entry_type WHERE ID='1932'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (263,(SELECT unique_id FROM entry_type WHERE ID='1832'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_PRINCIPAL_DUE=1 WHERE POSTING_RULE_ID=8863;

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (063,(SELECT unique_id FROM entry_type WHERE ID='1933'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (263,(SELECT unique_id FROM entry_type WHERE ID='1833'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_INTEREST_DUE=1 WHERE POSTING_RULE_ID=8863;

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (063,(SELECT unique_id FROM entry_type WHERE ID='1934'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (263,(SELECT unique_id FROM entry_type WHERE ID='1834'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_ESCROW_DUE=1 WHERE POSTING_RULE_ID=8863;

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (063,(SELECT unique_id FROM entry_type WHERE ID='1935'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (263,(SELECT unique_id FROM entry_type WHERE ID='1835'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_CREDIT_LIFE_DUE=1 WHERE POSTING_RULE_ID=8863;

UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_PAYMENTS_MADE=1 WHERE POSTING_RULE_ID=8863;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_PRNCP_DUE_DATE=1 WHERE POSTING_RULE_ID=8863;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_INT_DUE_DATE=1 WHERE POSTING_RULE_ID=8863;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_DATE_NEXT_DUE=1 WHERE POSTING_RULE_ID=8863;
