UPDATE PROPERTY_DEFINITION SET DEFAULT_VALUE = 'java.lang.String:' WHERE  ENTITY_TYPE_DEFINITION_ID IN (SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE 'ExternalAgency') AND PROPERTY_NAME = 'InCareOf';

UPDATE PROPERTY_DEFINITION SET DEFAULT_VALUE = 'java.lang.String:' WHERE  ENTITY_TYPE_DEFINITION_ID IN (SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE 'ExternalAgency') AND PROPERTY_NAME = 'PhoneNumber';

UPDATE PROPERTY_DEFINITION SET DEFAULT_VALUE = 'java.lang.String:' WHERE  ENTITY_TYPE_DEFINITION_ID IN (SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE 'ExternalAgency') AND PROPERTY_NAME = 'Address1';

UPDATE PROPERTY_DEFINITION SET DEFAULT_VALUE = 'java.lang.String:' WHERE  ENTITY_TYPE_DEFINITION_ID IN (SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE 'ExternalAgency') AND PROPERTY_NAME = 'Address2';

UPDATE PROPERTY_DEFINITION SET DEFAULT_VALUE = 'java.lang.String:' WHERE  ENTITY_TYPE_DEFINITION_ID IN (SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE 'ExternalAgency') AND PROPERTY_NAME = 'City';

UPDATE PROPERTY_DEFINITION SET DEFAULT_VALUE = 'java.lang.String:' WHERE  ENTITY_TYPE_DEFINITION_ID IN (SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE 'ExternalAgency') AND PROPERTY_NAME = 'State';

UPDATE PROPERTY_DEFINITION SET DEFAULT_VALUE = 'java.lang.Integer:' WHERE  ENTITY_TYPE_DEFINITION_ID IN (SELECT ENTITY_TYPE_DEFINITION_ID FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE 'ExternalAgency') AND PROPERTY_NAME = 'ZIP';