ALTER TABLE LOAN_ENTRY_POSTING_RULE ADD AFF_LOAN_MOD_RECORD_STATUS NUMBER(20) DEFAULT 0;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_LOAN_MOD_RECORD_STATUS=1 WHERE POSTING_RULE_ID=9999;


UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_PARTIAL_PAYMENT=1 WHERE POSTING_RULE_ID=8863;

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (063,(SELECT unique_id FROM entry_type WHERE ID='1943'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (263,(SELECT unique_id FROM entry_type WHERE ID='1843'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_CrLineDrawnAmnt=1 WHERE POSTING_RULE_ID=8863;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_PARTIAL_PAYMENT=1 WHERE POSTING_RULE_ID=8863;

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (063,(SELECT unique_id FROM entry_type WHERE ID='1949'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (263,(SELECT unique_id FROM entry_type WHERE ID='1849'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_PAY_OFF_ACR_INT=1 WHERE POSTING_RULE_ID=8863;

UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_FUTURE_PAYMENT_COUNT=1 WHERE POSTING_RULE_ID=8863;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_PRINCIPAL_PAID_TO_DATE=1 WHERE POSTING_RULE_ID=8863;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_LAST_PYMNT_AMOUNT=1 WHERE POSTING_RULE_ID=8863;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_DTNXTDUBFRPSTNG=1 WHERE POSTING_RULE_ID=8863;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_INTEREST_PAID_TO_DATE=1 WHERE POSTING_RULE_ID=8863;


INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (063,(SELECT unique_id FROM entry_type WHERE ID='1945'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (263,(SELECT unique_id FROM entry_type WHERE ID='1845'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_ACCM_SHRT_AMOUNT=1 WHERE POSTING_RULE_ID=8863;


INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (063,(SELECT unique_id FROM entry_type WHERE ID='1950'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (263,(SELECT unique_id FROM entry_type WHERE ID='1850'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_SERVICE_FEE_PAID=1 WHERE POSTING_RULE_ID=8863;


INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (063,(SELECT unique_id FROM entry_type WHERE ID='1954'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (263,(SELECT unique_id FROM entry_type WHERE ID='1854'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_SERVICE_FEE_NET=1 WHERE POSTING_RULE_ID=8863;

UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_SERVICE_FEE=1 WHERE POSTING_RULE_ID=8863;

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (063,(SELECT unique_id FROM entry_type WHERE ID='1888'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (263,(SELECT unique_id FROM entry_type WHERE ID='1988'));
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_TOTAL_PAYMENTS_RECEIVED=1 WHERE POSTING_RULE_ID=8863;


UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_DATE_LAST_ACTIVITY=1 WHERE POSTING_RULE_ID=8863;


UPDATE LOAN_ENTRY_POSTING_RULE SET AFFECTS_LAST_TRAN_AMOUNT=1 WHERE POSTING_RULE_ID=8863;

UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_PCHISTORY=1,AFF_RCHISTORY=1 WHERE posting_rule_id=8863;

