--creating table display all transactions in collection history screen.
CREATE TABLE COLLECTION_MASTER_HISTORY
  (
  	COLLECTION_MASTER_HISTORY_ID 	NUMBER(15,5)  NOT NULL ENABLE,
    ACCOUNT_NO VARCHAR2(20),
    DATE_POSTED DATE,
    TIME_POSTED  VARCHAR2(20),
    NAME         VARCHAR2(20),
    HISTORY_TYPE NUMBER(5),
    NOTES        VARCHAR2(1029),
    DATE_NEXT_CONTACT DATE,
    MODULE        NUMBER(4),
    CUSTOMER_NAME VARCHAR2(30),
    CONSTRAINT COLLECTION_MASTER_HISTORY_PK PRIMARY KEY (COLLECTION_MASTER_HISTORY_ID));
 
--sequence for COLLECTION_MASTER_HISTORY   
    CREATE SEQUENCE COLLECTION_MASTER_HISTORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
    
    CREATE TABLE HISTORY_TYPE_LOOKUP
  (
  	HISTORY_TYPE_LOOKUP_ID 	NUMBER(5)  NOT NULL ENABLE,
    DESCRIPTION VARCHAR2(20),
    PRIMARY KEY (HISTORY_TYPE_LOOKUP_ID));
    
   INSERT INTO HISTORY_TYPE_LOOKUP VALUES(1,'Left Message');
   INSERT INTO HISTORY_TYPE_LOOKUP VALUES(2,'Promise To Pay');
   INSERT INTO HISTORY_TYPE_LOOKUP VALUES(3,'Repo');
   INSERT INTO HISTORY_TYPE_LOOKUP VALUES(4,'Foreclosure');
   INSERT INTO HISTORY_TYPE_LOOKUP VALUES(5,'Comment');
   INSERT INTO HISTORY_TYPE_LOOKUP VALUES(6,'W/O');
   INSERT INTO HISTORY_TYPE_LOOKUP VALUES(7,'W/O Payment');
   INSERT INTO HISTORY_TYPE_LOOKUP VALUES(8,'W/O Comments');
   INSERT INTO HISTORY_TYPE_LOOKUP VALUES(9,'Bankruptcy Comm');
   INSERT INTO HISTORY_TYPE_LOOKUP VALUES(10,'W/O Coll Comment');
   INSERT INTO HISTORY_TYPE_LOOKUP VALUES(99,'Auto Letter');
   