
-- We need to mirgate Last Statement Date,Last Statement Balance,Statement Opening Balance and Statement Opening Date in Loan account Table.

ALTER TABLE LOAN_ACCOUNT ADD(LAST_STATEMENT_DATE DATE);
ALTER TABLE LOAN_ACCOUNT ADD(LAST_STATEMENT_BAL NUMBER(20,5) );
ALTER TABLE LOAN_ACCOUNT ADD(PRE_STATEMENT_BAL NUMBER(20,5) );
ALTER TABLE LOAN_ACCOUNT ADD(PRE_STATEMENT_DATE DATE);
 
-- cycle code for loans

ALTER TABLE LOAN_ACCOUNT ADD(STMT_CYCLE_CODE VARCHAR2(30) );

CREATE or replace VIEW LOAN_ACCOUNT_VW ( ACCOUNT_NO, INSTITUTION_ID, PRODUCT_ID, ACCOUNT_CATEGORY, ACCOUNT_TYPE_ID, BUSINESS_DATE, DATE_OPENED, CREATION_DATE, ACCOUNT_ID, CUSTOMER_ID, NOTE_NUMBER, START_DATE, CURRENT_MATURITY_DATE, CURRENT_INTEREST_RATE, INTEREST_BASE_CODE, LINE_OF_CREDIT, NEXT_PAYMENT_DUE_DATE, SCHEDULED_PAYMENT_DATE, NEXT_PRINCIPLE_DUE, NEXT_INTEREST_AMOUNT_DUE, NEXT_ESCROW_DUE, NEXT_SUBSIDY_AMOUNT, PAST_DUE_AMOUNT, APPROVED_LOAN_AMOUNT, AVAILED_LOAN_AMOUNT, PRINCIPLE_BALANCE, ACCRUED_INTEREST, UNAPPLIED_FUNDS, LOSS_DRAFT_FUNDS, LATE_FEES_DUE, OTHER_FEES_DUE, LOAN_STATUS, NEXT_REVIEW_DATE, LAST_MAINTENANCE_DATE, CLOSED_DATE, OPENING_BRANCH, PRIMARY_OFFICER, CALL_REPORT_CODE, EXAMINER_CLASSIFICATION_CODE, PREVIOUS_OFFICER, COLLECTION_OFFICER, REPAYMENT_MODE, APPLY_PAYMENTS_AS_BILLED, FIRST_PAYMENT_DATE, PAYMENTS_SCHEDULED, PAYMENTS_MADE, PRINT_BILLING_NOTICE, PRINT_COUPON_BOOK, PRINT_PAST_DUE_NOTICE, BALLOON_PAYMENT, MINIMUM_INTEREST_CHARGE, SPECIAL_MAILING_INSTRUCTIONS, CENSUS_TRACK, ORDER_COUPON_BOOK_NOW, CONTINUES_ORDER_OF_COUPON_BOOK, LATE_CHARGE_CODE, AMORTIZED_BALANCE, LAST_ADDL_PRINCIPAL_DATE, LAST_ADDL_PRINCIPAL_AMOUNT, INTEREST_RATE_TYPE, ACCELERATED_RATE_AT_MATURITY, GRACE_DAYS_AT_MATURITY, LINE_OF_CREDIT_ID, ESCROW_ACCOUNT_ID, NON_ACCRUAL, ORIGINAL_MATURITY_DATE, APPROVED_LIMIT, SECONDARY_ACCRUED, PREPAYMENT_PENALTY_CODE, PREPAYMENT_PENALTY, COMMENTS, PARTY_ID, LOAN_TERM, FREQUENCY_PRINCIPAL, FREQUENCY_INTEREST, ANNUAL_PERCENTAGE_RATE, COMBINED_STATEMENT, PARTIAL_PAYMENT, INTEREST_PAID_YTD, INTEREST_PAID_PYTD, INTEREST_PAID_LTD, LATE_FEES_PAID_YTD, LATE_FEES_PAID_PYTD, LATE_FEES_PAID_LTD, POINTS_PAID_YTD, POINTS_PAID_PYTD, POINTS_PAID_LTD, TAXES_PAID_YTD, TAXES_PAID_PYTD, TAXES_PAID_LTD, ORIGINATION_FEES_YTD, ORIGINATION_FEES_PYTD, ORIGINATION_FEES_LTD, ESCROW_INT_PAID_YTD, ESCROW_INT_PAID_PYTD, ESCROW_INT_PAID_LTD, POINTS_PAID_BY_BORROWER, SUBSIDIES_PAID_YTD, PROPERTY_OR_COLLATERAL, LIFE_INSURANCE_REBATE, ACC_INSURANCE_REBATE, LATE_CHRG_INDICATOR, AUTO_DRAFT, INT_BILLING_DATE, PRINCIPAL_BILLING_DATE, CLASS_CODE, LAST_PAYMENT_DATE, IS_AMORTIZED, DAYS_IN_A_YEAR, PAST_PRINCIPLE_DUE, PERCENTAGE_PAYMENT_AMOUNT, MAXIMUM_AMOUNT, MINIMUM_AMOUNT, MAX_LATE_CHARGE_PER_YEAR, GRACE_PERIOD, LATE_CHRG_YTD, AMT_LC_WAIVED, WAIVE_LATE_CHARGE, LATE_CHARGE_FIXED_AMT, LOAN_TYPE_ID, SCHEDULED_PAYMENT_DUE_DATE, EMPLOYEE_CODE, HOLD4_CODE, INTEREST_PAID_TO_DATE, MFHASERVFEE, PRINCIPAL_INTEREST_PAYMENT, MLOTNBR, MPLATNBR, MPAGENBR, LOAN_PURPOSE_CODE, NON_ESCROW_DUE, NON_ESCROW_BALANCE, DATE_LAST_ACTIVITY,BLOCK_ID,
LAST_STATEMENT_DATE,LAST_STATEMENT_BAL,PRE_STATEMENT_BAL,PRE_STATEMENT_DATE ,STMT_CYCLE_CODE)
AS
select A.ACCOUNT_NO,A.INSTITUTION_ID,A.PRODUCT_ID,A.ACCOUNT_CATEGORY,
A.ACCOUNT_TYPE_ID,A.BUSINESS_DATE,A.DATE_OPENED,A.CREATION_DATE, LA."ACCOUNT_ID",LA."CUSTOMER_ID",LA."NOTE_NUMBER",LA."START_DATE",LA."CURRENT_MATURITY_DATE",LA."CURRENT_INTEREST_RATE",LA."INTEREST_BASE_CODE",LA."LINE_OF_CREDIT",LA."NEXT_PAYMENT_DUE_DATE",LA."SCHEDULED_PAYMENT_DATE",LA."NEXT_PRINCIPLE_DUE",LA."NEXT_INTEREST_AMOUNT_DUE",LA."NEXT_ESCROW_DUE",LA."NEXT_SUBSIDY_AMOUNT",LA."PAST_DUE_AMOUNT",LA."APPROVED_LOAN_AMOUNT",LA."AVAILED_LOAN_AMOUNT",LA."PRINCIPLE_BALANCE",LA."ACCRUED_INTEREST",LA."UNAPPLIED_FUNDS",LA."LOSS_DRAFT_FUNDS",LA."LATE_FEES_DUE",LA."OTHER_FEES_DUE",LA."LOAN_STATUS",LA."NEXT_REVIEW_DATE",LA."LAST_MAINTENANCE_DATE",LA."CLOSED_DATE",LA."OPENING_BRANCH",LA."PRIMARY_OFFICER",LA."CALL_REPORT_CODE",LA."EXAMINER_CLASSIFICATION_CODE",LA."PREVIOUS_OFFICER",LA."COLLECTION_OFFICER",LA."REPAYMENT_MODE",LA."APPLY_PAYMENTS_AS_BILLED",LA."FIRST_PAYMENT_DATE",LA."PAYMENTS_SCHEDULED",LA."PAYMENTS_MADE",LA."PRINT_BILLING_NOTICE",LA."PRINT_COUPON_BOOK",LA."PRINT_PAST_DUE_NOTICE",LA."BALLOON_PAYMENT",LA."MINIMUM_INTEREST_CHARGE",LA."SPECIAL_MAILING_INSTRUCTIONS",LA."CENSUS_TRACK",LA."ORDER_COUPON_BOOK_NOW",LA."CONTINUES_ORDER_OF_COUPON_BOOK",LA."LATE_CHARGE_CODE",LA."AMORTIZED_BALANCE",LA."LAST_ADDL_PRINCIPAL_DATE",LA."LAST_ADDL_PRINCIPAL_AMOUNT",LA."INTEREST_RATE_TYPE",LA."ACCELERATED_RATE_AT_MATURITY",LA."GRACE_DAYS_AT_MATURITY",LA."LINE_OF_CREDIT_ID",LA."ESCROW_ACCOUNT_ID",LA."NON_ACCRUAL",LA."ORIGINAL_MATURITY_DATE",LA."APPROVED_LIMIT",LA."SECONDARY_ACCRUED",LA."PREPAYMENT_PENALTY_CODE",LA."PREPAYMENT_PENALTY",LA."COMMENTS",LA."PARTY_ID",LA."LOAN_TERM",LA."FREQUENCY_PRINCIPAL",LA."FREQUENCY_INTEREST",LA."ANNUAL_PERCENTAGE_RATE",LA."COMBINED_STATEMENT",LA."PARTIAL_PAYMENT",LA."INTEREST_PAID_YTD",LA."INTEREST_PAID_PYTD",LA."INTEREST_PAID_LTD",LA."LATE_FEES_PAID_YTD",LA."LATE_FEES_PAID_PYTD",LA."LATE_FEES_PAID_LTD",LA."POINTS_PAID_YTD",LA."POINTS_PAID_PYTD",LA."POINTS_PAID_LTD",LA."TAXES_PAID_YTD",LA."TAXES_PAID_PYTD",LA."TAXES_PAID_LTD",LA."ORIGINATION_FEES_YTD",LA."ORIGINATION_FEES_PYTD",LA."ORIGINATION_FEES_LTD",LA."ESCROW_INT_PAID_YTD",LA."ESCROW_INT_PAID_PYTD",LA."ESCROW_INT_PAID_LTD",LA."POINTS_PAID_BY_BORROWER",LA."SUBSIDIES_PAID_YTD",LA."PROPERTY_OR_COLLATERAL",LA."LIFE_INSURANCE_REBATE",LA."ACC_INSURANCE_REBATE",LA."LATE_CHRG_INDICATOR",LA."AUTO_DRAFT",LA."INT_BILLING_DATE",LA."PRINCIPAL_BILLING_DATE",LA."CLASS_CODE",LA."LAST_PAYMENT_DATE",LA."IS_AMORTIZED",LA."DAYS_IN_A_YEAR",LA."PAST_PRINCIPLE_DUE",LA."PERCENTAGE_PAYMENT_AMOUNT",LA."MAXIMUM_AMOUNT",LA."MINIMUM_AMOUNT",LA."MAX_LATE_CHARGE_PER_YEAR",LA."GRACE_PERIOD",LA."LATE_CHRG_YTD",LA."AMT_LC_WAIVED",LA."WAIVE_LATE_CHARGE",LA."LATE_CHARGE_FIXED_AMT",LA."LOAN_TYPE_ID",LA."SCHEDULED_PAYMENT_DUE_DATE",LA."EMPLOYEE_CODE",LA."HOLD4_CODE",LA."INTEREST_PAID_TO_DATE",LA."MFHASERVFEE",LA."PRINCIPAL_INTEREST_PAYMENT",LA."MLOTNBR",LA."MPLATNBR",LA."MPAGENBR",LA."LOAN_PURPOSE_CODE",LA."NON_ESCROW_DUE",LA."NON_ESCROW_BALANCE",
LA.DATE_LAST_ACTIVITY,LA.BLOCK_ID,LA.LAST_STATEMENT_DATE,LA.LAST_STATEMENT_BAL,LA.PRE_STATEMENT_BAL,LA.PRE_STATEMENT_DATE,LA.STMT_CYCLE_CODE
from ACCOUNT A,LOAN_ACCOUNT LA
where A.ACCOUNT_ID=LA.ACCOUNT_ID
 ;
 
-- We need to migrate LOAN ACCOUNT DAY for Statements.
CREATE TABLE LOAN_ACCOUNT_DAY(
ACCOUNT_ID VARCHAR2(30) NOT NULL,
DAY_START DATE ,
DAY_END DATE ,
OPENING_ACC_DEALER_INT NUMBER(20,5),
OPENING_ACC_INT NUMBER(20,5),
OPENING_AH_DUE NUMBER(20,5),
OPENING_CL_DUE NUMBER(20,5),
OPENING_COLLECTED_LATE_CHARGE NUMBER(20,5),
OPENING_DATE_NEXT_DUE DATE,
OPENING_ESCROW_BALANCE NUMBER(20,5),
OPENING_ESCROW_DUE NUMBER(20,5),
OPENING_FUTURE_PAYMENT_COUNT NUMBER(10),
OPENING_INT_PAID_TO_DATE DATE,
OPENING_NEXT_DISBURSEMENT_DATE DATE,
OPENING_NON_ESCROW_BALANCE NUMBER(20,5),
OPENING_LOAN_AMOUNT NUMBER(20,5),
OPENING_OTHER_FEE_DUE NUMBER(20,5),
OPENING_PARTIAL_PAYMENT NUMBER(20,5),
OPENING_PAST_AH_DUE NUMBER(20,5),
OPENING_PAST_CL_DUE NUMBER(20,5),
OPENING_PAST_DEALER_INT_DUE NUMBER(20,5),
OPENING_PAST_ESCROW_DUE NUMBER(20,5),
OPENING_PAST_INT_DUE NUMBER(20,5),
OPENING_PAST_PRINCIPAL_DUE NUMBER(20,5),
OPENING_PAYMENTS_MADE NUMBER(10),
OPENING_PER_DIEM NUMBER(20,5),
OPENING_PRINCIPLE_BALANCE NUMBER(20,5),
OPENING_PRINCIPAL_BILLING_DATE DATE,
OPENING_PRINCIPAL_DUE NUMBER(20,5),
OPENING_PRINCIPAL_PAID_TO_DATE DATE,
OPENING_RET_CHECK_COUNT NUMBER(10),
OPENING_LATE_CHARGE_DUE NUMBER(20,5),
OPENING_WAIVED_LATE_CHARGE NUMBER(20,5),
OPENING_INT_DUE NUMBER(20,5),
OPENING_NON_ESCROW_DUE NUMBER(20,5),
OPENING_PAST_NON_ESCROW_DUE NUMBER(20,5),
OPENING_LCF_DUE NUMBER(20,5),
OPENING_PAST_LCF_DUE NUMBER(20,5),
OPENING_INT_PAID NUMBER(20,5),
ACC_DEALER_INT NUMBER(20,5),
ACC_INT NUMBER(20,5),
AH_DUE NUMBER(20,5),
CL_DUE NUMBER(20,5),
COLLECTED_LATE_CHARGE NUMBER(20,5),
CREDIT_AMOUNT NUMBER(20,5),
CREDIT_COUNT NUMBER(5),
DATE_NEXT_DUE VARCHAR2(50),
DEBIT_AMOUNT NUMBER(20,5),
DEBIT_COUNT NUMBER(5),
ESCROW_BALANCE NUMBER(20,5),
ESCROW_DUE NUMBER(20,5),
FUTURE_PAYMENT_COUNT NUMBER(10),
INT_PAID_TO_DATE VARCHAR2(50),
NEXT_DISBURSEMENT_DATE VARCHAR2(50),
NON_ESCROW_BALANCE NUMBER(20,5),
LOAN_AMOUNT NUMBER(20,5),
OTHER_FEE_DUE NUMBER(20,5),
PARTIAL_PAYMENT NUMBER(20,5),
PAST_AH_DUE NUMBER(20,5),
PAST_CL_DUE NUMBER(20,5),
PAST_DEALER_INT_DUE NUMBER(20,5),
PAST_ESCROW_DUE NUMBER(20,5),
PAST_INT_DUE NUMBER(20,5),
PAST_PRINCIPAL_DUE NUMBER(20,5),
PAYMENTS_MADE NUMBER(10),
PER_DIEM NUMBER(20,5),
PRINCIPLE_BALANCE NUMBER(20,5),
PRINCIPAL_BILLING_DATE VARCHAR2(50),
PRINCIPAL_DUE NUMBER(20,5),
PRINCIPAL_PAID_TO_DATE VARCHAR2(50),
RET_CHECK_COUNT NUMBER(10),
LATE_CHARGE_DUE NUMBER(20,5),
WAIVED_LATE_CHARGE NUMBER(20,5),
INT_DUE NUMBER(20,5),
NON_ESCROW_DUE NUMBER(20,5),
PAST_NON_ESCROW_DUE NUMBER(20,5),
LCF_DUE NUMBER(20,5),
PAST_LCF_DUE NUMBER(20,5),
INT_PAID NUMBER(20,5),
AGR_PRINCIPLE_BALANCE NUMBER(20,5),
AGR_LOAN_AMOUNT NUMBER(20,5),
AGR_LATE_CHARGE_DUE NUMBER(20,5),
AGR_LATE_CHARGE_PAID NUMBER(20,5),
MTD_LATE_CHARGE_PAID NUMBER(20,5),
MTD_ESCROW_INTEREST_PAID NUMBER(20,5),
MTD_EARNINGS NUMBER(20,5),
MTD_WAIVEDLATE_CHARGE NUMBER(20,5),
MTD_CHECKS_RETURNED NUMBER(20,5),
MTD_INTEREST_PAID NUMBER(20,5),
MTD_AGR_PRINCIPLE_BALANCE NUMBER(20,5),
MTD_AGR_LOAN_AMOUNT NUMBER(20,5),
MTD_AGR_LATE_CHARGE_DUE NUMBER(20,5),
MTD_AGR_LATE_CHARGE_PAID NUMBER(20,5)
);

ALTER TABLE LOAN_ACCOUNT_DAY ADD CONSTRAINT LOAN_ACCT_DAY_AID_FK FOREIGN KEY (ACCOUNT_ID) REFERENCES LOAN_ACCOUNT(ACCOUNT_ID);
-- planning to drop this constraint as we are getting values from CIF  which are not there in the escrow_payee lookup table.	  
ALTER TABLE LOAN_ACCOUNT_TRANSACTION DROP CONSTRAINT LOAN_TRAN_ESCPAY_FK;

ALTER TABLE ESCROW_TRANSACTION drop CONSTRAINT ESCROW_TRAN_ESCPAY_FK;