--Adding column to DEposit_account table.
ALTER TABLE DEPOSIT_ACCOUNT ADD(OWNERSHIP_DESIGNATION NUMBER(5,0));
ALTER TABLE DEPOSIT_ACCOUNT ADD (STATE_TAX_WHELD_YTD NUMBER(20,5));
ALTER TABLE DEPOSIT_ACCOUNT ADD(STMT_OPENING_BAL NUMBER(20,5) );
ALTER TABLE DEPOSIT_ACCOUNT ADD(STMT_OPENING_DATE DATE);

-- To fix the issue "On the EFTPS screen to create the ACH file that Sheri Gregory (ACH Operator) does, when she tries to create the ACH file for the EFTPS for bank 08 (Central) the system displays a blank screen".
--UPDATE TAX_PAYMENT_BUSINESS_EVENT SET BRANCH=100 WHERE BRANCH=880;

-- FRABA
ALTER TABLE INSTITUTION DROP CONSTRAINT INST_FRABA_ID_FK; 
ALTER TABLE ACH_WARE_HOUSE_ENTRY DROP CONSTRAINT FRABA_ID_FK;
ALTER TABLE ACH_FRABA_SUMMARY DROP CONSTRAINT ACH_FRABA_SUMMARY_FK2;
ALTER TABLE FRABA DROP CONSTRAINT FRABA_PK;
--DROP INDEX FRABA_PK;

DELETE FROM FRABA;
ALTER TABLE FRABA MODIFY (INSTITUTION_ID VARCHAR2(30));
alter table fraba add(unique_id VARCHAR2(15));
ALTER TABLE FRABA ADD CONSTRAINT FRABA_PK PRIMARY KEY (UNIQUE_ID);
ALTER TABLE FRABA ADD CONSTRAINT FRABA_IID_FK FOREIGN KEY (INSTITUTION_ID) REFERENCES INSTITUTION(INSTITUTION_ID);
ALTER TABLE FRABA ADD CONSTRAINT FRABA_FID_IID_UK UNIQUE (FRABA_ID,INSTITUTION_ID);


ALTER TABLE INSTITUTION ADD CONSTRAINT INST_FRABA_ID_FK FOREIGN KEY (FRABA_ID) REFERENCES FRABA (UNIQUE_ID); 

-- ACH_WARE_HOUSE_ENTRY
ALTER TABLE ACH_WARE_HOUSE_ENTRY ADD TEMP_FRABA_ID  NUMBER(15);

alter table ACH_WARE_HOUSE_ENTRY drop column temp_FRABA_ID;

ALTER TABLE ACH_WARE_HOUSE_ENTRY ADD CONSTRAINT FRABA_ID_FK FOREIGN KEY (FRABA_ID) REFERENCES FRABA (UNIQUE_ID);

-- New table in place of ACH_FRABA_SUMMARY

CREATE TABLE ACH_INSTITUTION_SUMMARY ( 
    ACH_FILE_ID           	VARCHAR2(20) ,
    COMPUTED_TOTAL_DEBITS 	NUMBER(15,2) ,
    COMPUTED_TOTAL_CREDITS	NUMBER(15,2),
    INSTITUTION_ID        	VARCHAR2(15)  
    );
ALTER TABLE ACH_INSTITUTION_SUMMARY ADD CONSTRAINT ACH_INST_SUMM_INSTID_FK 
FOREIGN KEY (INSTITUTION_ID) REFERENCES INSTITUTION (INSTITUTION_ID);

ALTER TABLE ACH_INSTITUTION_SUMMARY ADD CONSTRAINT ACH_INST_SUMM_ACHFILEID_FK 
FOREIGN KEY (ACH_FILE_ID) REFERENCES ACH_FILE (ACH_FILE_ID);


--For nightly processing..
alter table ACH_WARE_HOUSE_ENTRY add(CORRECTED_ACCOUNT_NUMBER VARCHAR2(15));


alter table ACCOUNTING_EVENT_PAYMENT drop constraint ACC_PAY_ID_FK;
alter table TAX_PAYMENT_MONETARY_EVENT add TAX_PAYMENT_EVENT_ID  number(15);


CREATE TABLE PARTY_TEMP_CORRECTED (
    CUSTOMER_ID        VARCHAR2(30) NULL,
    INSTITUTION_ID    VARCHAR2(30) NULL,
    ADDRESS_LINE1     VARCHAR2(250) NULL,
    ADDRESS_LINE2     VARCHAR2(250) NULL,
    ADDRESS_LINE3     VARCHAR2(250) NULL,
    CITY              VARCHAR2(100) NULL,
    STATE             VARCHAR2(100) NULL,
    ZIPCODE         VARCHAR2(50) NULL
    );
    
create or replace view institution_interest_code_vw as
select iic.INSTITUTION_ID, ich.EFFECTIVE_DATE, ich.EFFECTIVE_END_DATE, ich.RECORDED_DATE,
ic.*
from INTEREST_CODES ic, INSTITUTION_INT_CODES iic,INTEREST_CODES_HISTORY ich 
where  iic.INTEREST_CODE_HIST_UID = ich.UNIQUE_ID and ich.UNIQUE_ID = ic.INTEREST_CODE_HIST_UID
;
 
 
create or replace view branch_interest_code_vw as
select  b.BRANCH_ID, b.INSTITUTION_ID,ich.EFFECTIVE_DATE, ich.EFFECTIVE_END_DATE, ich.RECORDED_DATE,
ic.*,b.BRANCH_NAME, b.UNIQUE_ID branch_UID,b.BRANCH_STATUS,b.ROUTING_TRANSIT_NO
from INTEREST_CODES ic, BRANCH_INT_CODES bic,INTEREST_CODES_HISTORY ich, BRANCH b
where  bic.INTEREST_CODE_HIST_UID = ich.UNIQUE_ID and ich.UNIQUE_ID = ic.INTEREST_CODE_HIST_UID
and b.UNIQUE_ID = bic.BRANCH_ID;



ALTER TABLE ACH_WARE_HOUSE_ENTRY ADD (LAST_PROCESSED_DATE DATE ) ;

--To add anew column COMPANY_IDENTIFICATION
ALTER TABLE ACH_WARE_HOUSE_ENTRY ADD(COMPANY_IDENTIFICATION VARCHAR2(10));

--To increase the length of COMPANY_CUST_NO from 10 to 15.
ALTER TABLE ACH_WARE_HOUSE_ENTRY MODIFY(COMPANY_CUST_NO VARCHAR2(15));

-- dropping the constraint right now. need to handle later.
alter table deposit_account drop constraint dep_acc_procaccid_fk;

-- reverting the NUMBER_DAYS_PENALTY back to number

update PENALTY_PARAMETER set NUMBER_DAYS_PENALTY = replace(NUMBER_DAYS_PENALTY,':4');
update PENALTY_PARAMETER set GRACE_DAYS = replace(GRACE_DAYS,':4');
alter table PENALTY_PARAMETER add(temp number(10));
update PENALTY_PARAMETER set temp = NUMBER_DAYS_PENALTY;
alter table PENALTY_PARAMETER drop column NUMBER_DAYS_PENALTY;
alter table PENALTY_PARAMETER rename column temp to NUMBER_DAYS_PENALTY;

alter table PENALTY_PARAMETER add(temp number(10));
update PENALTY_PARAMETER set temp = GRACE_DAYS;
alter table PENALTY_PARAMETER drop column GRACE_DAYS;
alter table PENALTY_PARAMETER rename column temp to GRACE_DAYS; 

alter table MAINTENANCE_LOG add FIRST_NAME VARCHAR2(50);

alter table MAINTENANCE_LOG add LAST_NAME VARCHAR2(50);

alter table TAX_PAYMENT_BUSINESS_EVENT modify WHO_INITIATED VARCHAR2(100);

alter table TAX_PAYMENT_BUSINESS_EVENT modify AUTHORISED_BY VARCHAR2(100);

CREATE TABLE INVEST_ACCT_POTENTIAL_EVENT(ACCOUNT_ID VARCHAR2(15) 
REFERENCES ACCOUNT(ACCOUNT_ID),
POT_DEPOSIT_EVENT_ID NUMBER(15,0) REFERENCES POTENTIAL_DEPOSIT_EVENT(UNIQUE_ID));

ALTER TABLE BRANCH ADD(BRANCH_ACCOUNT_NUMBER  VARCHAR2(15)); 
ALTER TABLE INSTITUTION ADD(INST_ACCOUNT_NUMBER  VARCHAR2(15)); 
alter table ACH_WARE_HOUSE_ENTRY add (Customer_name VARCHAR2(50));