CREATE  OR REPLACE  VIEW TAX_YEAR_VW AS 
SELECT
	A.ACCOUNT_ID , PFI.PROD_FEATURE_VALUE TAX_YEAR
FROM
	ACCOUNT A,
    DEPOSIT_ACCOUNT DA ,
	PRODUCT P ,
	APPL_PRODUCT AP ,
	PRODUCT_FEATURE PF ,
    PRODUCT_FEATURE_INSTANCE PFI
WHERE A.PRODUCT_INSTANCE_UID  = AP.UNIQUE_ID 
AND AP.PRODUCT_UID  = P.PRODUCT_UID 
AND P.PRODUCT_UID  = PF.PRODUCT_UID 
AND PF.PROD_FEATURE_UID  = PFI.PROD_FEATURE_UID 
AND DA.ACCOUNT_ID = A.ACCOUNT_ID 
AND DA.PLAN_ID IS NOT NULL 
AND PF.FEATURE_UID = 103
AND PFI.APPL_PRODUCT_UID = AP.UNIQUE_ID
and PROD_FEATURE_VALUE  is not null ;



CREATE
	OR
REPLACE
	VIEW CONTRIBUTION_TYPE_VW AS 
SELECT distinct  
	 INV.ACCOUNT_ID ,
	PDE.CONTRIBUTION_TYPE ,
	PES.NAME 
FROM
	INVEST_ACCT_POTENTIAL_EVENT INV ,
	POTENTIAL_DEPOSIT_EVENT PDE ,
	POTENTIAL_EVENT_SOURCE PES ,
	DEPOSIT_ACCOUNT_VW DA 
WHERE
	INV.POT_DEPOSIT_EVENT_ID = PDE.UNIQUE_ID AND
    DA.ACCOUNT_ID = INV.ACCOUNT_ID  AND 
    DA.PLAN_ID   IS NOT NULL AND 
	PDE.EVENT_SOURCE_ID = PES.UNIQUE_ID(+);


CREATE TABLE SAVINGS_PLAN_CONT_TRANSACTIONS 
	(
		TRANSACTION_ID  NUMBER(10) ,
		PLAN_ID  VARCHAR2(30),
		CONTRIBUTION_CODE VARCHAR2(20) ,
		CONTRIBUTION_AMOUNT NUMBER(15,2) ,
		CONTRIBUTION_DATE DATE,
		TAX_YEAR NUMBER(4),
		SOURCE_NAME VARCHAR2(50)
);


ALTER TABLE SAVINGS_PLAN_CONT_TRANSACTIONS  ADD CONSTRAINT  SPCT_PLAN_ID_FK
 FOREIGN KEY(PLAN_ID) REFERENCES SAVINGS_PLAN_DETAILS(PLAN_ID) ;


ALTER TABLE SAVINGS_PLAN_CONT_TRANSACTIONS ADD CONSTRAINT SP_CONT_TRAN_PK PRIMARY 
	KEY (TRANSACTION_ID );
	
CREATE SEQUENCE SP_CONT_TRAN_SEQ START WITH 1 INCREMENT BY 1 ;

alter table POTENTIAL_DEPOSIT_EVENT add TAX_YEAR varchar2(5);

CREATE TABLE MAINTAINABLE_INTEREST_CODES
	(	PRODUCT_CATEGORY  NUMBER(5) ,
		INTEREST_CODE NUMBER(5) ,
		UI_INTEREST_CODE_DESC  VARCHAR2(200) , 
        FREQUENCY  VARCHAR2(20)); 

ALTER TABLE  MAINTAINABLE_INTEREST_CODES  ADD  CONSTRAINT INT_PROD_UNI UNIQUE(PRODUCT_CATEGORY  , INTEREST_CODE);

CREATE SEQUENCE CONVERTED_INST_SEQ  START WITH  1 INCREMENT BY 1 ;

CREATE TABLE CONVERTED_INST_EFFECTIVE_DATES
(ID NUMBER(5) , 
CORE_INST_ID  NUMBER(5) , 
RESEARCH_INST_ID NUMBER(5) , 
EFFECTIVE_DATE DATE); 
