ALTER TABLE DEPOSIT_ACCOUNT   ADD ( TEMP_PROCEEDS_CODE NUMBER(8)) ;

UPDATE  DEPOSIT_ACCOUNT  SET TEMP_PROCEEDS_CODE = PROCEEDS_CODE ;

ALTER TABLE  DEPOSIT_ACCOUNT  DROP COLUMN PROCEEDS_CODE ;

ALTER TABLE DEPOSIT_ACCOUNT   ADD ( PROCEEDS_CODE NUMBER(8)) ;

UPDATE  DEPOSIT_ACCOUNT  SET  PROCEEDS_CODE =TEMP_PROCEEDS_CODE;

ALTER TABLE DEPOSIT_ACCOUNT  DROP COLUMN TEMP_PROCEEDS_CODE;

ALTER TABLE DEPOSIT_ACCOUNT   ADD ( TEMP_FED_WITHHOLDING_CODE NUMBER(8)) ;

UPDATE  DEPOSIT_ACCOUNT  SET TEMP_FED_WITHHOLDING_CODE = FED_WITHHOLDING_CODE ;

ALTER TABLE  DEPOSIT_ACCOUNT  DROP COLUMN FED_WITHHOLDING_CODE ;

ALTER TABLE DEPOSIT_ACCOUNT   ADD ( FED_WITHHOLDING_CODE NUMBER(8)) ;

UPDATE  DEPOSIT_ACCOUNT  SET  FED_WITHHOLDING_CODE =TEMP_FED_WITHHOLDING_CODE;

ALTER TABLE DEPOSIT_ACCOUNT  DROP COLUMN TEMP_FED_WITHHOLDING_CODE;

--CHAGING THE DATA TYPE FOR STATE_WITHHOLDING_CODE  FROM VARCHAR TO NUMBER

ALTER TABLE DEPOSIT_ACCOUNT   ADD ( TEMP_STATE_WITHHOLDING_CODE NUMBER(8)) ;

UPDATE  DEPOSIT_ACCOUNT  SET TEMP_STATE_WITHHOLDING_CODE = STATE_WITHHOLDING_CODE ;

ALTER TABLE  DEPOSIT_ACCOUNT  DROP COLUMN STATE_WITHHOLDING_CODE ;

ALTER TABLE DEPOSIT_ACCOUNT   ADD ( STATE_WITHHOLDING_CODE NUMBER(8)) ;

UPDATE  DEPOSIT_ACCOUNT  SET  STATE_WITHHOLDING_CODE =TEMP_STATE_WITHHOLDING_CODE;

ALTER TABLE DEPOSIT_ACCOUNT  DROP COLUMN TEMP_STATE_WITHHOLDING_CODE;

alter table account add processing_status number(1) default 1;

--//(enum with values 0- cosmetic and 1- significant)
 alter table maintenance_log add change_type number(1); 
 
--(enum with values 0-initiated, 1-authorized,2-not_authorized);
 alter table maintenance_log add authorized_status varchar2(1) ;
 
 alter table maintenance_log add authorized_date date;

-- (Details of the authorized||intitution of the user||branch of the user);  (authorization date); 
 
 alter table maintenance_log add authorized_description varchar2(100);
 
CREATE OR REPLACE
	VIEW PARTY_VW 
	(	PARTY_ID,
		BUSINESS_NAME,
		FIRST_NAME,
		LAST_NAME,
		EMPLOYER_NAME,
		PARTY_TYPE,
		PARTY_NAME 
	)
AS
SELECT
	P.PARTY_ID,
	O.BUSINESS_NAME,
	PE.FIRST_NAME,
	PE.LAST_NAME,
	PE.EMPLOYER_NAME,
	P.PARTY_TYPE,
	NVL(O.BUSINESS_NAME , PE.LAST_NAME||','||PE.FIRST_NAME ) PARTY_NAME 
FROM
	PARTY P,
	PERSON PE,
	ORGANIZATION O 
WHERE
	P.PARTY_ID = PE.PARTY_ID(+) AND
	P.PARTY_ID = O.PARTY_ID (+);
