CREATE TABLE IRA_DIST_CONTRI_TAX_DETAILS ( 
    PLAN_ID                     	VARCHAR2(30) ,
    INVESTMENT_ACCOUNT          	VARCHAR2(60) ,
    BALANCE                     	NUMBER(20,5) ,
    INTEREST_RATE               	NUMBER(20,5) ,
    INTEREST_YTD                	NUMBER(20,5) ,
    PENALTY_AMOUNT              	NUMBER(20,5) ,
    BAL_ON_JAN                  	NUMBER(20,5) ,
    TAX_STATUS_CODE             	VARCHAR2(20) ,
    SSN                         	NUMBER(20,5) ,
    DOB_PRIMARY                 	DATE ,
    ACCOUNT_NO                  	VARCHAR2(30) ,
    SAVINGS_PLAN_TYPE_ID        	VARCHAR2(30) ,
    FIRST_NAME                  	VARCHAR2(100) ,
    LAST_NAME                   	VARCHAR2(100) ,
    LINE1                       	VARCHAR2(50) ,
    LINE2                       	VARCHAR2(50) ,
    LINE3                       	VARCHAR2(50) ,
    ZIP                         	VARCHAR2(10) ,
    RMD_CUSTOMER                	VARCHAR2(3) ,
    RMD_AMOUNT                  	NUMBER(20,5) ,
    CUSTOMER_AGE                	NUMBER(20,2) ,
    DATE_OPENED                 	DATE ,
    CONTTY                      	NUMBER(20,5) ,
    CONTTYLY                    	NUMBER(20,5) ,
    YTD_FED_TAX_WH              	NUMBER(20,5) ,
    STATE_TAX_WH                	NUMBER(20,5) ,
    TRANS_AMOUNT_YTD            	NUMBER(10,2) ,
    TRANSFER_LY                 	NUMBER(20,5) ,
    YTD_ROLLOVER_CONTRIBUTION   	NUMBER(20,5) ,
    YTD_ROLLOVER_CONTRIBUTION_LY	NUMBER(20,5) ,
    EMP_CONT_YTD                	VARCHAR2(30) ,
    EMP_CONT_PRE_YR             	VARCHAR2(30) ,
    TAXABLE_CONT_YR             	VARCHAR2(20) ,
    TAXABLE_CONT_PRE_YR         	VARCHAR2(20) ,
    NON_TAXABLE_CONT_YR         	VARCHAR2(20) ,
    NON_TAXABLE_CONT_PRE_YR     	VARCHAR2(20) ,
    CONT_TAXBALE_TO_DATE        	VARCHAR2(20) ,
    CONT_NON_TAXBLAE_TO_DATE    	VARCHAR2(20) ,
    WITH01                      	NUMBER(20,5) ,
    WITH02                      	NUMBER(20,5) ,
    WITH03                      	NUMBER(20,5) ,
    WITH04                      	NUMBER(20,5) ,
    WITH05                      	NUMBER(20,5) ,
    WITH06                      	NUMBER(20,5) ,
    WITH07                      	NUMBER(20,5) ,
    WITH08                      	NUMBER(20,5) ,
    WITH09                      	NUMBER(20,5) ,
    PENALTY_YTD                 	NUMBER(20,5) ,
    TRANSFER_AMOUNT_YTD         	NUMBER(20,5) ,
    DEATH_CODE                  	VARCHAR2(5) ,
    DISTRIBUTION_AFTER_DEATH    	VARCHAR2(30) ,
    DIST_PERCENTAGE             	NUMBER(20,5)  
    );
 

 ALTER TABLE IRA_DIST_CONTRI_TAX_DETAILS  ADD CONSTRAINT FK_DIST_CONT_TAX_PLANID 
 FOREIGN KEY(PLAN_ID) REFERENCES SAVINGS_PLAN_DETAILS(PLAN_ID);
 
 CREATE TABLE SAVINGS_PLAN_DISTRIB_INSTR 
	(	UNIQUE_ID NUMBER(15),
		PLAN_ID VARCHAR2(30),
		ACCOUNT_ID VARCHAR2(30),
		DISTRIBUTION_CODE VARCHAR2(5),
		AMOUNT NUMBER(20,5),
		INSTRUCTION_DATE DATE,
		STATUS VARCHAR2(1),
		ENTERED_BY VARCHAR2(50),
		BRANCH_ID VARCHAR2(50)
	);

ALTER TABLE SAVINGS_PLAN_DISTRIB_INSTR ADD CONSTRAINT FK_DISTRIB_PLANID FOREIGN 
	KEY(PLAN_ID) REFERENCES SAVINGS_PLAN_DETAILS(PLAN_ID);

ALTER TABLE SAVINGS_PLAN_DISTRIB_INSTR ADD CONSTRAINT FK_DISTRIB_ACCOUNT_ID 
	FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID);

CREATE SEQUENCE SAV_PLAN_DITRIB_INSTR_SEQ START WITH 1 INCREMENT BY 1;

DROP TABLE IRA_DIST_CONTRI_TAX_DETAILS;
CREATE TABLE IRA_DIST_CONTRI_TAX_DETAILS ( 
    PLAN_ID                      VARCHAR2(30) ,
    TAX_STATUS_CODE              NUMBER(20,5) ,
    SSN                          NUMBER(20,5) ,
    DOB_PRIMARY                  DATE ,
    PLAN_NUMBER                  VARCHAR2(30) ,
    INSTITUTION_ID                VARCHAR2(30)  ,
    SAVINGS_PLAN_TYPE_ID         NUMBER(20,5) ,
    FIRST_NAME                   VARCHAR2(100) ,
    LAST_NAME                    VARCHAR2(100) ,
    LINE1                        VARCHAR2(50) ,
    LINE2                        VARCHAR2(50) ,
    LINE3                        VARCHAR2(50) ,
    ZIP                          VARCHAR2(10) ,
    RMD_CUSTOMER                 VARCHAR2(3) ,
    DATE_OPENED                  DATE ,
    CONT_FOR_BLY_MADE_IN_LY  	 NUMBER(20,5) DEFAULT 0,
    CONT_FOR_LY_MADE_IN_LY  	 NUMBER(20,5) DEFAULT 0,
    CONT_FOR_LY_MADE_IN_TY       NUMBER(20,5) DEFAULT 0,
    CONT_FOR_TY_MADE_IN_TY	 NUMBER(20,5)  DEFAULT 0,		
    YTD_FED_TAX_WH               NUMBER(20,5)  DEFAULT 0,
    STATE_TAX_WH                 NUMBER(20,5)  DEFAULT 0,
    TRANS_AMOUNT_IN_YTD             NUMBER(10,2)  DEFAULT 0,
    TRANSFER_LY                  NUMBER(20,5)  DEFAULT 0,
    YTD_ROLLOVER_CONTRIBUTION    NUMBER(20,5) DEFAULT 0,
    YTD_ROLLOVER_CONTRIBUTION_LY NUMBER(20,5) DEFAULT 0,
    EMP_CONT_YTD                 NUMBER(20,5) DEFAULT 0,
    EMP_CONT_PRE_YR               NUMBER(20,5) DEFAULT 0,
    TAXABLE_CONT_YR               NUMBER(20,5) DEFAULT 0,
    TAXABLE_CONT_PRE_YR          NUMBER(20,5)  DEFAULT 0,
    NON_TAXABLE_CONT_YR           NUMBER(20,5)  DEFAULT 0,
    NON_TAXABLE_CONT_PRE_YR      NUMBER(20,5)  DEFAULT 0,
    CONT_TAXBALE_TO_DATE          NUMBER(20,5) DEFAULT 0,
    CONT_NON_TAXBLAE_TO_DATE      NUMBER(20,5) DEFAULT 0,
    WITH01                       NUMBER(20,5)  DEFAULT 0,
    WITH02                       NUMBER(20,5) DEFAULT 0,
    WITH03                       NUMBER(20,5)  DEFAULT 0,
    WITH04                       NUMBER(20,5) DEFAULT 0,
    WITH05                       NUMBER(20,5) DEFAULT 0,
    WITH06                       NUMBER(20,5) DEFAULT 0,
    WITH07                       NUMBER(20,5) DEFAULT 0,
    WITH08                       NUMBER(20,5) DEFAULT 0,
    WITH09                       NUMBER(20,5) DEFAULT 0, 
    WITHD                       NUMBER(20,5) DEFAULT 0,
    WITHG                       NUMBER(20,5) DEFAULT 0,	
    WITHJ                       NUMBER(20,5) DEFAULT 0,
    WITHN                       NUMBER(20,5) DEFAULT 0,
    WITHP                       NUMBER(20,5) DEFAULT 0,
    WITHQ                       NUMBER(20,5) DEFAULT 0,
    WITHR                       NUMBER(20,5) DEFAULT 0,
    WITHT                       NUMBER(20,5) DEFAULT 0,
    PENALTY_YTD                 NUMBER(20,5) DEFAULT 0,
   TRANSFER_AMOUNT_OUT_YTD      NUMBER(20,5) DEFAULT 0,
   TRANSFER_AMOUNT_OUT_YTD_LY   NUMBER(20,5) DEFAULT 0,	
    DEATH_CODE                   NUMBER(20,5) DEFAULT 0,
    DISTRIBUTION_AFTER_DEATH     NUMBER(20,5) DEFAULT 0,
    DIST_PERCENTAGE              NUMBER(20,5) DEFAULT 0,
    TAX_YEAR                            DATE , 
    RE_CHARCTERIZATION_YTD       NUMBER(20,5) DEFAULT 0,
    RE_CHARCTERIZATION_LAST_YEAR NUMBER(20,5) DEFAULT 0
    );
 

 ALTER TABLE IRA_DIST_CONTRI_TAX_DETAILS
 ADD CONSTRAINT FK_DIST_CONT_TAX_PLANID
 FOREIGN KEY(PLAN_ID)
 REFERENCES SAVINGS_PLAN_DETAILS(PLAN_ID);

ALTER TABLE IRA_DIST_CONTRI_TAX_DETAILS
ADD CONSTRAINT PK_DIST_CONT_TAX_PLAN_ID 
UNIQUE (PLAN_ID);

CREATE TABLE IRA_INVEST_DETAILS( 

    INVESTMENT_ACCOUNT           VARCHAR2(60) ,
    INSTITUTION_ID                      VARCHAR2(30) ,   
    PLAN_ID                             VARCHAR2(30) ,
    BALANCE                      NUMBER(20,5) DEFAULT 0,
    INTEREST_RATE                NUMBER(20,5) DEFAULT 0,
    INTEREST_YTD                 NUMBER(20,5) DEFAULT 0,
    PENALTY_AMOUNT               NUMBER(20,5) DEFAULT 0,
    BAL_ON_JAN                   NUMBER(20,5) DEFAULT 0,
    TAX_YEAR                      Date
);

 ALTER TABLE IRA_INVEST_DETAILS
 ADD CONSTRAINT FK_IRA_INV_PLANID
 FOREIGN KEY(PLAN_ID)
 REFERENCES SAVINGS_PLAN_DETAILS(PLAN_ID);

 ALTER TABLE IRA_INVEST_DETAILS
 ADD CONSTRAINT UK_PLANID_INVE_ACC
UNIQUE (INVESTMENT_ACCOUNT , INSTITUTION_ID , PLAN_ID     );

CREATE TABLE IRA60_YEAREND ( 
    INSTITUTION_ID           	VARCHAR2(30) ,
    BRANCH                   	VARCHAR2(20) ,
    ACCOUNT_NO               	VARCHAR2(30) ,
    CURR_YR_CONT             	NUMBER(20,5) DEFAULT 0,
    PREV_YR_CONTR            	NUMBER(20,5) DEFAULT 0,
    CALENDER_YR_CONT         	NUMBER(20,5) DEFAULT 0,
    YTD_ROLLOVER             	NUMBER(20,5) DEFAULT 0,
    PRE_YR_TRANSFER_AMOUNT   	NUMBER(20,5) DEFAULT 0,
    PREV_DISTRIBUTION        	NUMBER(20,5) DEFAULT 0,
    PREV_WITH_CODE1          	NUMBER(20,5) DEFAULT 0,
    PREV_WITH_CODE2          	NUMBER(20,5) DEFAULT 0,
    PREV_WITH_CODE3          	NUMBER(20,5) DEFAULT 0,
    PREV_WITH_CODE4          	NUMBER(20,5) DEFAULT 0,
    PREV_WITH_CODE5          	NUMBER(20,5) DEFAULT 0,
    PREV_WITH_CODE6          	NUMBER(20,5) DEFAULT 0,
    PREV_WITH_CODE7          	NUMBER(20,5) DEFAULT 0,
    PREV_WITH_CODE8          	NUMBER(20,5) DEFAULT 0,
    PREV_WITH_CODE9          	NUMBER(20,5) DEFAULT 0,
    PREV_WITH_CODED          	NUMBER(20,5) DEFAULT 0,
    PREV_WITH_CODEJ          	NUMBER(20,5) DEFAULT 0,
    PREV_WITH_CODEN          	NUMBER(20,5) DEFAULT 0,
    PREV_WITH_CODEP          	NUMBER(20,5) DEFAULT 0,
    PREV_WITH_CODEQ          	NUMBER(20,5) DEFAULT 0,
    PREV_WITH_CODER          	NUMBER(20,5) DEFAULT 0,
    PREV_WITH_CODET          	NUMBER(20,5) DEFAULT 0,
    PRE_YR_PENALTY_AMOUNT    	NUMBER(20,5) DEFAULT 0,
    PRE_YR_SART_BAL          	NUMBER(20,5) DEFAULT 0,
    PRE_YR_END_BAL           	NUMBER(20,5) DEFAULT 0,
    PRE_YR_INT_YTD           	NUMBER(20,5) DEFAULT 0,
    FULL_DIST_CODE           	NUMBER(20,5) DEFAULT 0,
    FED_TAX_WH               	NUMBER(20,5) DEFAULT 0,
    STATE_TAX_WH             	NUMBER(20,5) DEFAULT 0,
    CONTR_FOR_LY_MADE_TY_60  	NUMBER(10,2) DEFAULT 0,
    CONTR_FOR_TY_MADE_TY_60  	NUMBER(10,2) DEFAULT 0,
    CONTR_FOR_TY_MADE_LY_60  	NUMBER(10,2) DEFAULT 0,
    CONTR_FOR_TTY_MADE_TTY_60	NUMBER(10,2) DEFAULT 0,
    ROLL_OVER                	NUMBER(20,5) DEFAULT 0,
    DIST_LYR                 	NUMBER(20,5) DEFAULT 0,
    WITHHELD_LR              	NUMBER(20,5) DEFAULT 0,
    PENALTY                  	NUMBER(20,5) DEFAULT 0,
    TRANSLY                  	NUMBER(20,5) DEFAULT 0,
    INTLY                    	NUMBER(20,5) DEFAULT 0,
    PLAN_ID                  	VARCHAR2(30) DEFAULT 0 , 
    TAX_YEAR                     DATE	
    )
;

CREATE
	TABLE SAVINGS_PLAN_DIST_TRANSACTIONS 
	(
		TRANSACTION_ID  NUMBER(10) ,
		PLAN_ID  VARCHAR2(30),
		DISTRIBUTION_CODE VARCHAR2(20) ,
		DISTRIBUTION_AMOUNT NUMBER(15,2) ,
		STATE_TAX NUMBER(15,2) ,
		FED_TAX NUMBER(15,2) ,
		PENALTY_AMOUNT  NUMBER(15,2), 
        DISTRIBUTION_DATE DATE
);



ALTER TABLE SAVINGS_PLAN_DIST_TRANSACTIONS  ADD CONSTRAINT  SPT_PLAN_ID_FK
 FOREIGN KEY(PLAN_ID) REFERENCES SAVINGS_PLAN_DETAILS(PLAN_ID) ;

ALTER TABLE SAVINGS_PLAN_DIST_TRANSACTIONS ADD CONSTRAINT SP_DIST_TRAN_PK PRIMARY KEY (TRANSACTION_ID );

CREATE SEQUENCE SP_DIST_TRAN_SEQ START WITH 1 INCREMENT BY 1 ;