alter table DEPOSITS_LOANS add (APPLICATION_TYPE number(4) default 0);
alter table DEPOSITS_LOANS add (PRODUCT_CODE number(4) default 0);

CREATE TABLE OVERDRAFT_LOAD_LIMIT
(
ID NUMBER(19, 0) PRIMARY KEY ,
ACCOUNT_NUMBER VARCHAR2(255 BYTE) ,
INSTITUTION_ID VARCHAR2(255 BYTE) ,
OVER_DRAFT_LIMIT NUMBER(10, 0) ,
OVER_DRAFT_CODE VARCHAR2(255 BYTE)
);

CREATE SEQUENCE PAYMENT_DETAILS_HISTORY_SEQ MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 100 ORDER NOCYCLE ;

CREATE TABLE CUSTOMER_ACC_RISK_ASSESMENT (ID NUMBER(10),CUSTOMER_ID VARCHAR2(50),ACCOUNT_NO VARCHAR2(50),SCORE NUMBER(10,2));

CREATE SEQUENCE CUSTOMER_RISK_ASS_ID_SEQ START WITH 1 INCREMENT BY 1;

alter table hold_payment add HOLD_REASON varchar(100);
ALTER TABLE ACCOUNT_HISTORY_ITEM ADD ORIGINAL_TRANCODE_ID VARCHAR2(100) DEFAULT NULL;

ALTER TABLE fee_pkg_maintenance_log ADD PARAMETER_NAME VARCHAR2(60);

ALTER TABLE LEDGER_POSTING_PARAMETERS ADD IS_OD_PROTECTED NUMBER(1);

ALTER TABLE USERS MODIFY PASSWORD VARCHAR2(30) NULL;

ALTER TABLE INSTITUTION_USERS DROP CONSTRAINT IU_PK;

ALTER TABLE INSTITUTION_USERS ADD CONSTRAINT IUS_PK PRIMARY KEY (INSTITUTION_ID,USER_ID);

ALTER TABLE INSTITUTION_USERS MODIFY ROLE_ID VARCHAR2(30) NULL;

CREATE TABLE "DORMANT_MAINTENANCE_LOG" (
    "ENTRY_ID" NUMBER(30,0) NOT NULL ENABLE,
    "ACCOUNT_NUMBER" NUMBER(30),
    "CUSTOMER_NAME" VARCHAR2(50),
    "DATE_OF_DORMANCY" DATE,
    "DATE_OF_ESCHEATMENT" DATE,
    "DATE_OF_CLOSING" DATE,
    "POST_DATE" DATE,
    "AMOUNT_MOVED_TO_GL" NUMBER(30),
    "USER_ID" VARCHAR2(50),
    "TERMINAL" VARCHAR2(50));
    
 alter table product_form_template add OWNERSHIP_TYPE varchar2(50);
 alter table form_template add DISPLAY_NAME varchar2(100);
 
 ALTER TABLE TRANSACTION_POSTTODAY DROP COLUMN ORIGINAL_TRANCODE_ID; 
ALTER TABLE ACCOUNT_HISTORY_ITEM DROP COLUMN ORIGINAL_TRANCODE_ID; 

ALTER TABLE TRANSACTION_POSTTODAY ADD ORIGINAL_TRANSACTION_ID VARCHAR2(100) DEFAULT NULL;
ALTER TABLE ACCOUNT_HISTORY_ITEM ADD ORIGINAL_TRANSACTION_ID VARCHAR2(100) DEFAULT NULL;

ALTER TABLE application ADD PERSONAL_BANKER VARCHAR2(50);
ALTER TABLE deposit ADD PERSONAL_BANKER VARCHAR2(50);

ALTER TABLE account_application ADD PRINT_TITLE2_ON_STATEMENT NUMBER(2) DEFAULT 0;
ALTER TABLE account_application ADD TITLE2 VARCHAR2(45);

ALTER TABLE account ADD PRINT_TITLE2_ON_STATEMENT NUMBER(2) DEFAULT 0;
ALTER TABLE account ADD TITLE2 VARCHAR2(45);

CREATE sequence dynamic_form_edited_fields_seq start with 1;

ALTER TABLE deposit ADD NSF_COUNTER NUMBER default 0;