ALTER TABLE DEPOSIT ADD PERIODIC_DIVIDEND_CAP VARCHAR2(50);
ALTER TABLE DEPOSIT ADD PERIODIC_DIVIDEND_FLOOR VARCHAR2(50);
ALTER TABLE DEPOSIT ADD LIFETIME_DIVIDEND_CAP VARCHAR2(50);
ALTER TABLE DEPOSIT ADD LIFETIME_DIVIDEND_FLOOR VARCHAR2(50);
ALTER TABLE DEPOSIT ADD LIFETIME_DIVIDEND_DIFF_CAP VARCHAR2(50);
ALTER TABLE DEPOSIT ADD LIFETIME_DIVIDEND_DIFF_FLOOR VARCHAR2(50);
alter table originator_master modify ORIGINATOR VARCHAR2(30);