CREATE TABLE AVG_BAL_MTD_HISTORY
  (
     UNIQUE_ID   NUMBER(30,0) NOT NULL ENABLE,
     ACCOUNT_ID  VARCHAR2(30),
     MONTH       NUMBER(10),
     YEAR        NUMBER(10),
     AVG_BALANCE NUMBER(20,5),
    CONSTRAINT MTD_HISTORY_PK PRIMARY KEY ("UNIQUE_ID") ENABLE);
  
CREATE SEQUENCE AVG_BAL_MTD_HISTORY_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1;
  