alter table role_policy_access add FIELD_BEHAVIOR NUMBER;
alter table role_policy_access add USECASE_ID NUMBER(30);

CREATE SEQUENCE TICKLER_USER_SEQ INCREMENT BY 1 NOCYCLE NOCACHE;

CREATE TABLE "TICKLER_GROUP_USERS"
  (
    "UNIQUE_ID"          NUMBER(10,0) NOT NULL ENABLE,
    "TICKLER_GROUP_ID" NUMBER(30),
    "USERID"    VARCHAR2(100),
    CONSTRAINT "TICKLER_GROUP_USERS_PK" PRIMARY KEY ("UNIQUE_ID"),
    CONSTRAINT "TICKLER_GROUP_FK1" FOREIGN KEY ("TICKLER_GROUP_ID") REFERENCES "TICKLER_USER_GROUPS" ("ID") ENABLE
  );