CREATE TABLE HOLIDAY_CALENDAR_MAINT_LOG
  (
    "ENTRY_ID"      NUMBER(30,0) NOT NULL ENABLE,
    "CALENDAR_NAME" VARCHAR2(60 BYTE),
    "FIELD_CHANGED" VARCHAR2(100 BYTE),
    "OLD_VALUE"     VARCHAR2(600 BYTE),
    "NEW_VALUE"     VARCHAR2(600 BYTE),
    "CLASS_TYPE"    VARCHAR2(70 BYTE),
    "BRANCH_NAME"   VARCHAR2(50 BYTE),
    "USER_ID"       VARCHAR2(50 BYTE),
    "ENTRY_DATE" DATE,
    "TERMINAL" VARCHAR2(50 BYTE),
    CONSTRAINT "HOLIDAY_CALENDAR_MAINT_LOG_PK" PRIMARY KEY ("ENTRY_ID")
  );