CREATE TABLE STATE_MASTER (
    ID                      		NUMBER(5),
    STATE_CODE          	   		VARCHAR2(5) NOT NULL,
    STATE_NAME        				VARCHAR2(50),
    COUNTRY_CODE              		VARCHAR2(5),
    COUNTRY_NAME         			VARCHAR2(50),
    ACCURE_PAY_INTEREST   			NUMBER(10),
    PAY_INTEREST_A_ONLY        		NUMBER(10),
    FREQUENCY        				NUMBER(10),
    INTEREST_EARLY_PAY_OFF    		NUMBER(10),
    COMPUTE_CODE    				NUMBER(10),
    RATE_OF_INTEREST    			NUMBER(10,5));
  	
CREATE SEQUENCE STATE_MASTER_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOMINVALUE NOCYCLE ORDER;


CREATE TABLE STATE_ESCROW_MAPPING (

    ID                      		NUMBER(5),
    STATE_CODE          	   		VARCHAR2(10),
    ESCROW_TYPE                     NUMBER(10),
    CUSHION_PERIOD                  VARCHAR2(10));
  	
CREATE SEQUENCE STATE_ESCROW_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOMINVALUE NOCYCLE ORDER;