
ALTER TABLE loan_participation ADD REMIT_YIELD NUMBER(20,5) DEFAULT 0;

INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (060,(SELECT unique_id FROM entry_type WHERE ID='1880'));
INSERT INTO LOAN_EVENT_ENTRY_TYPE_LINK (EVENT_TYPE_ID, ENTRY_TYPE_ID) VALUES (260,(SELECT unique_id FROM entry_type WHERE ID='1980'));
ALTER TABLE LOAN_ENTRY_POSTING_RULE ADD  AFF_REMIT_YIELD_AMT NUMBER(20) DEFAULT 0;
UPDATE LOAN_ENTRY_POSTING_RULE SET AFF_REMIT_YIELD_AMT=1 WHERE POSTING_RULE_ID=8860;