create index DEP_ACC_SUM_INST_AID_PD_IDX ON 
 DEPOSIT_ACCOUNT_SUMMARY(INSTITUTION_ID,ACCRUED_INTEREST_DIFFERECE,PROCESSED_DATE);
 
create index dep_lan_acc_inst_idx on deposits_loans(account_no,institution_id);
 
alter table LEDGER_POSTING_PARAMETERS modify (CORESOFT_ENTRY_TYPE number(5));


CREATE TABLE PAYMENT_AUTHORIZATION (
    ID NUMBER(20),
    PAYMENT_AUTHORIZATION_DATE DATE,
    INSTITUTION_NUMBER varchar2(30),
    PAYEE_ACCOUNT_NUMBER varchar2(30),
    PAYEE_ACCOUNT_ID varchar2(30),
    AUTHORIZED_AMOUNT NUMBER(20,2),
    PAYMENT_DUE_DATE DATE,
    NATURE_OF_PAYMENT NUMBER(3),
    PAID_AMOUNT NUMBER(20,2)
);

ALTER TABLE PAYMENT_AUTHORIZATION ADD ( CONSTRAINT PAYMENT_AUTHORIZATION_PK PRIMARY KEY(ID));

ALTER TABLE PAYMENT_AUTHORIZATION ADD ( CONSTRAINT PAYMENT_AUTHOR_ACCT_ID_FK
	FOREIGN KEY(PAYEE_ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID));

	
CREATE SEQUENCE PAYMENT_AUTHORIZATION_ID_SEQ
    INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    CACHE 20
    ORDER;

CREATE TABLE OFFICIAL_PAYMENT (
    ID NUMBER(20),
    INSTITUTION_NUMBER varchar2(30),
    PAYMENT_DATE DATE,
    AMOUNT NUMBER(20,2),
    PAYMENT_AUTHORIZATION_ID NUMBER(20)    
);

ALTER TABLE OFFICIAL_PAYMENT ADD ( CONSTRAINT OFFICIAL_PAYMENT_PK PRIMARY KEY(ID));

ALTER TABLE OFFICIAL_PAYMENT ADD ( CONSTRAINT OFFICIAL_PAYMENT_AUTHOR_ID_FK
	FOREIGN KEY(PAYMENT_AUTHORIZATION_ID)
	REFERENCES PAYMENT_AUTHORIZATION(ID));

CREATE SEQUENCE OFFICIAL_PAYMENT_ID_SEQ
    INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    CACHE 20
    ORDER;
    
 CREATE TABLE ACCOUNT_CHECK_PAYMENT (
    ID NUMBER(20) PRIMARY KEY,
    INSTITUTION_NUMBER varchar2(30),
    ROUTING_TRANSIT_NUMBER varchar2(15),
    ACCOUNT_NUMBER varchar2(30),
    CHECK_NUMBER NUMBER(20),
    PREPARED_DATE DATE,
    PAYEE_ACCOUNT_NUMBER varchar2(30),
    PAYEE_NAME varchar2(100),
    PAYEE_ADDRESS_1 varchar2(100),
    PAYEE_ADDRESS_2 varchar2(100),
    PAYEE_ADDRESS_3 varchar2(100),
    PAYEE_CITY_NAME varchar2(50),
    PAYEE_STATE_CODE varchar2(20),
    PAYEE_ZIP_CODE varchar2(30),
    STATUS varchar2(20),
    STATUS_DATE DATE
);
--ALTER TABLE ACCOUNT_CHECK_PAYMENT ADD ( CONSTRAINT ACCOUNT_CHECK_PAYMENT_PK PRIMARY KEY(ID));
ALTER TABLE ACCOUNT_CHECK_PAYMENT ADD ( CONSTRAINT ACCOUNT_CHECK_PAYMENT_ID_FK
	FOREIGN KEY(ID)	REFERENCES OFFICIAL_PAYMENT(ID));
	
CREATE TABLE PAYMENT_ACCOUNT (
    ID NUMBER(20),
    INSTITUTION_NUMBER varchar2(30),
    NATURE_OF_PAYMENT NUMBER(3),
    PAYMENT_ACCOUNT_NUMBER varchar2(30)
);

ALTER TABLE PAYMENT_ACCOUNT ADD ( CONSTRAINT PAYMENT_ACCOUNT_PK PRIMARY KEY(ID));

ALTER TABLE PAYMENT_ACCOUNT ADD ( CONSTRAINT PAYMENT_ACCOUNT_UNIQUE_KEY
	UNIQUE (INSTITUTION_NUMBER, NATURE_OF_PAYMENT));
	
alter table LEDGER_POSTING_PARAMETERS rename column AFECTS_ENCLOSURE_DEBIT_COUNT to AFFECTS_ENCLOSURE_COUNT;
alter table LEDGER_POSTING_PARAMETERS drop column AFECTS_ENCLOSURE_CREDIT_COUNT;

ALTER TABLE ACCOUNT_CHECK_PAYMENT MODIFY (PAYEE_NAME VARCHAR2(1500));
ALTER TABLE DEPOSIT_ACCOUNT ADD ( PAID_OUT_DATE DATE NULL );
alter TABLE SAVINGS_PLAN_DETAILS add (CLOSED_DATE DATE);

ALTER TABLE DEPOSIT_ACCOUNT_SUMMARY 
ADD CONSTRAINT DEPOSIT_ACCOUNT_SUMMARY_PK primary key (ACCOUNT_ID,PROCESSED_DATE);

alter table DEPOSIT_ACCOUNT_SUMMARY add (UNIQUE_ID number(30));

CREATE SEQUENCE DEPOSIT_SUMMARY_SEQ	INCREMENT BY 1	START WITH 1;

CREATE INDEX DEP_ACC_SUM_UN_IDX ON DEPOSIT_ACCOUNT_SUMMARY (UNIQUE_ID);