CREATE TABLE DEBITCARD_PAYMENT ( 
    FEE_AMOUNT       	NUMBER(12,0) NULL,
    PAYMENT_ID       	NUMBER(15,0) NULL,
    PAYMENT_METHOD_ID	NUMBER(15,0) NULL 
    );

CREATE TABLE DEBITCARD_PAYMENT_METHOD ( 
    PAYMENT_METHOD_ID	NUMBER(15,0) NOT NULL,
    INSTITUTION_ID   	NUMBER(15,0) NULL,
    CURRENCY         	varchar2(50) NULL,
    AMOUNT           	NUMBER(20,5) NULL,
    ACCOUNT_NO       	VARCHAR2(15) NULL,
    FEE_AMOUNT       	NUMBER(12,0) NULL,
    CONSTRAINT DEBITCARD_PAYMENT_METHOD_PK PRIMARY KEY(PAYMENT_METHOD_ID)
);

ALTER TABLE DEBITCARD_PAYMENT
    ADD ( CONSTRAINT DEBITCARD_PAYMENT_ID_FK
	FOREIGN KEY(PAYMENT_ID)
	REFERENCES PAYMENT(PAYMENT_ID)
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
;

ALTER TABLE DEBITCARD_PAYMENT
    ADD ( CONSTRAINT DC_PAYMENT_METHOD_ID_FK
	FOREIGN KEY(PAYMENT_METHOD_ID)
	REFERENCES DEBITCARD_PAYMENT_METHOD(PAYMENT_METHOD_ID)
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
;

ALTER TABLE DEBITCARD_PAYMENT_METHOD
    ADD ( CONSTRAINT DEBITCARD_PAYMENT_METHOD_ID_FK
	FOREIGN KEY(PAYMENT_METHOD_ID)
	REFERENCES PAYMENT_METHOD(PAYMENT_METHOD_ID)
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
;


CREATE TABLE ADJUSTMENT_EVENT 
(
	EVENT_ID NUMBER(15,0) NOT NULL, 
	CONSTRAINT ADJUSTMENT_EVENT_PK PRIMARY KEY (EVENT_ID)
);
ALTER TABLE ADJUSTMENT_EVENT
	ADD ( CONSTRAINT ADJUSTMENT_EVENT_FK
	FOREIGN KEY(EVENT_ID)
	REFERENCES EVENT(EVENT_ID));

ALTER TABLE PAYMENT ADD (
	PURPOSE varchar2(50) NULL,
	SOURCE_INFO varchar2(1000) NULL,
	RECORD_TIME DATE NULL,
	EFFECTIVE_DATE DATE NULL,
	FORCED NUMBER(1,0) NULL
);

UPDATE PAYMENT SET FORCED = 0;

CREATE TABLE DEPOSIT_PAYMENT 
(
	PAYMENT_ID NUMBER(15,0) NOT NULL, 
	ACCOUNT_ID varchar2(30) NOT NULL, 
	CONSTRAINT DEPOSIT_PAYMENT_PK PRIMARY KEY (PAYMENT_ID)
);

ALTER TABLE DEPOSIT_PAYMENT
	ADD ( CONSTRAINT DEPOSIT_PAYMENT_ACC_FK
	FOREIGN KEY(ACCOUNT_ID)
	REFERENCES ACCOUNT(ACCOUNT_ID));
ALTER TABLE DEPOSIT_PAYMENT
	ADD ( CONSTRAINT DEPOSIT_PAYMENT_PYMNT_FK
	FOREIGN KEY(PAYMENT_ID)
	REFERENCES PAYMENT(PAYMENT_ID));

CREATE TABLE WITHDRAWAL_PAYMENT 
(
	PAYMENT_ID NUMBER(15,0) NOT NULL, 
	ACCOUNT_ID varchar2(30) NOT NULL, 
	CONSTRAINT WITHDRAWAL_PAYMENT_PK PRIMARY KEY (PAYMENT_ID)
);

ALTER TABLE WITHDRAWAL_PAYMENT
	ADD ( CONSTRAINT WITHDRAWAL_PAYMENT_ACC_FK
	FOREIGN KEY(ACCOUNT_ID)
	REFERENCES ACCOUNT(ACCOUNT_ID));
ALTER TABLE WITHDRAWAL_PAYMENT
	ADD ( CONSTRAINT WITHDRAWAL_PAYMENT_PYMNT_FK
	FOREIGN KEY(PAYMENT_ID)
	REFERENCES PAYMENT(PAYMENT_ID));

CREATE TABLE FUNDS_TRANSFER_PAYMENT 
(
	PAYMENT_ID NUMBER(15,0) NOT NULL, 
	FROM_ACCOUNT_ID varchar2(30) NOT NULL, 
	TO_ACCOUNT_ID varchar2(30) NOT NULL, 
	CONSTRAINT FUNDS_TRANSFER_PAYMENT_PK PRIMARY KEY (PAYMENT_ID)
);

ALTER TABLE FUNDS_TRANSFER_PAYMENT
	ADD ( CONSTRAINT FUNDS_TRANSFER_PAYMENT_FACC_FK
	FOREIGN KEY(FROM_ACCOUNT_ID)
	REFERENCES ACCOUNT(ACCOUNT_ID));
ALTER TABLE FUNDS_TRANSFER_PAYMENT
	ADD ( CONSTRAINT FUNDS_TRANSFER_PAYMENT_TACC_FK
	FOREIGN KEY(TO_ACCOUNT_ID)
	REFERENCES ACCOUNT(ACCOUNT_ID));
ALTER TABLE FUNDS_TRANSFER_PAYMENT
	ADD ( CONSTRAINT FUNDS_TRANSFER_PAYMENT_PYMT_FK
	FOREIGN KEY(PAYMENT_ID)
	REFERENCES PAYMENT(PAYMENT_ID));

ALTER TABLE PAYMENT_METHOD ADD (
	ATTRIBUTES varchar2(1000) NULL
);

DROP TABLE DEBITCARD_PAYMENT_METHOD cascade constraint;
DROP TABLE DEBITCARD_PAYMENT cascade constraint;

CREATE TABLE ELECTRONIC_CASH
(
	PAYMENT_METHOD_ID NUMBER(15,0) NOT NULL, 
	FEE_AMOUNT NUMBER(12,0) NULL, 
	CONSTRAINT ELECT_CASH_PK PRIMARY KEY (PAYMENT_METHOD_ID)
);
ALTER TABLE ELECTRONIC_CASH
	ADD ( CONSTRAINT ECASH_PYMTMETH_FK
	FOREIGN KEY(PAYMENT_METHOD_ID)
	REFERENCES PAYMENT_METHOD(PAYMENT_METHOD_ID));

alter table ELECTRONIC_CASH modify (
	FEE_AMOUNT NUMBER(20,5)
);