CREATE TABLE "HOLIDAY_CALENDAR" (
    "CALENDAR_ID" NUMBER(30,0) NOT NULL ENABLE, 
    "CALENDAR_NAME" VARCHAR2(100),
    "CALENDAR_YEAR" VARCHAR2(50),
   CONSTRAINT "HOLIDAY_CALENDAR_PK" PRIMARY KEY ("CALENDAR_ID") ENABLE);
   
create sequence "HOLIDAY_CALENDAR_ID_SEQ" minvalue 1 maxvalue 9999999999 increment by 1 start with 1;

CREATE TABLE "HOLIDAY_DETAILS" (
    "HOLIDAY_ID" NUMBER(30,0) NOT NULL ENABLE, 
	  "HOLIDAY_NAME"  VARCHAR2(50) ,
    "HOLIDAY"  DATE,
    "CALENDAR_ID" NUMBER(30,0) ,
   CONSTRAINT "HOLIDAY_DETAILS_PK" PRIMARY KEY ("HOLIDAY_ID") ENABLE,
   CONSTRAINT "HOLIDAY_CALENDAR_FK" FOREIGN KEY ("CALENDAR_ID") REFERENCES "HOLIDAY_CALENDAR" ("CALENDAR_ID") ENABLE);
 
 create sequence "HOLIDAY_DETAILS_ID_SEQ" minvalue 1 maxvalue 9999999999 increment by 1 start with 1; 
 
 