CREATE TABLE DEPOSITS_INTEREST_CODES
( 
    "UNIQUE_ID" NUMBER(15,0) NOT NULL ENABLE, 
"INTEREST_CODE" VARCHAR2(30 BYTE), 
"INTEREST_CODE_DESCRIPTION" VARCHAR2(30 BYTE), 
CONSTRAINT "DEP_INT_CODES_PK" PRIMARY KEY ("UNIQUE_ID"));

 
CREATE TABLE DEPOSITS_INTEREST_RATES
   ( "UNIQUE_ID" NUMBER(15,0) NOT NULL ENABLE, 
"EFFECTIVE_DATE" DATE, 
"AMOUNT" NUMBER(20,5), 
"PERIOD_IN_DAYS" NUMBER, 
"PERIOD_IN_MONTHS" NUMBER, 
"INTEREST_RATE" NUMBER(20,5), 
"INTEREST_CODE_UID" NUMBER(15,0), 
CONSTRAINT "DEP_INT_RATES_PK" PRIMARY KEY ("UNIQUE_ID"),
    CONSTRAINT "DEP_INT_RATES_FK" FOREIGN KEY ("INTEREST_CODE_UID")
  REFERENCES "DEPOSITS_INTEREST_CODES" ("UNIQUE_ID") ENABLE);