CREATE TABLE "HOW_DID_YOU_HEAR_ABT_US" 
(
      "UNIQUE_ID" NUMBER(30,0) NOT NULL ENABLE, 
	    "INFORMATION" VARCHAR2(100),
      "ENABLE" NUMBER(2),
   CONSTRAINT "HOW_DID_YOU_HEAR_ABT_US_PK" PRIMARY KEY ("UNIQUE_ID") ENABLE);
   
create sequence HOW_DID_YOU_HEAR_ABT_US_SEQ minvalue 1 maxvalue 9999999999 increment by 1 start with 1;
