create index dep_accid_tonum on deposit(to_number(account_id));
alter table LEDGER_POSTING_PARAMETERS add(AFFECTS_DISTRIBUTION number default 0);

CREATE or REPLACE VIEW "ACCOUNT_DETAILS_VW"  ("ACCOUNT_ID", "ACCOUNT_NO", "INSTITUTION_ID", "ACCOUNT_TYPE_ID", "LEDGER_BALANCE", "AVAILABLE_BALANCE", "BUSINESS_DATE", "CURRENT_BALANCE", "UNCOLLECTED_BALANCE", "OVERDRAFT_CODE", "CREATION_DATE", "DATE_LAST_MAINTAINED", "RETURNS_LAST_YR", "TIMES_NSF_CURR_PERIOD", "TIMES_NSF_YTD", "TIMES_OD_CURR_PERIOD", "TIMES_OD_YTD", "OVERDRAFT_LIMIT") AS
  (SELECT acc.account_id,de.ACCOUNT_NO,acc.INSTITUTION_ID,de.account_type_id, de.LEDGER_BALANCE,de.AVAILABLE_BALANCE,de.BUSINESS_DATE,
  de.CURRENT_BALANCE,de.UNCOLLECTED_BALANCE,de.OVERDRAFT_CODE,de.CREATION_DATE,de.DATE_LAST_MAINTAINED,de.RETURNS_LAST_YR,
  de.TIMES_NSF_CURR_PERIOD,de.TIMES_NSF_YTD,
  de.TIMES_OD_CURR_PERIOD,de.TIMES_OD_YTD,de.OVERDRAFT_LIMIT FROM ACCOUNT acc, DEPOSIT de
  WHERE acc.ACCOUNT_ID = de.ACCOUNT_ID
 );