CREATE TABLE SWEEP_DEFINITIONS (
    SWEEP_ID VARCHAR2(120) NOT NULL,
    DEPOSIT VARCHAR2(30) NOT NULL,
    OTHER_DEPOSIT VARCHAR2(30) NOT NULL,
    lower_limit NUMBER(20,5) NOT NULL,
    upper_limit NUMBER(20,5) NOT NULL,
    sweep_type VARCHAR2(30),
    deposit_bank VARCHAR2(10),
    DATE_LAST_SWEPT date,
    DATE_LAST_MAINTAINED DATE,
    PRIMARY KEY (SWEEP_ID)
   );


ALTER TABLE SWEEP_DEFINITIONS
    ADD ( CONSTRAINT SWEEP_DEFINITIONS_acc_FK
    FOREIGN KEY(DEPOSIT)
    REFERENCES deposit_account(account_id));
    
CREATE SEQUENCE SWEEP_ID_SEQ
    INCREMENT BY 1
    START WITH 1;