CREATE TABLE DEPOSIT
AS  
SELECT  DA.ACCOUNT_ID,
PENALTY_ID,
PROCEEDS_ACCOUNT_ID,
LEDGER_BALANCE,
AVAILABLE_BALANCE,
CURRENT_BALANCE,
OPENING_BALANCE,
NO_DEBITS_CURRENT_PERIOD,
AMT_OF_DEBITS_CURRENT_PERIOD,
NO_CREDITS_CURRENT_PERIOD,
AMT_OF_CREDITS_CURRENT_PERIOD,
NO_ACH_DEBITS_CURRENT_PERIOD,
NO_TRANSIT_ITEMS,
NO_OF_CHECKS,
FED_WITHHOLD_AMT_CURR_PERIOD,
NO_DEPOSITS_CURRENT_PERIOD,
NO_ATM_DEBITS,
SRV_CHRG_ACT_CURR_PERIOD,
SRV_CHRG_MAINTCURR_PERIOD,
TIMES_OD_CURR_PERIOD,
TIMES_NSF_CURR_PERIOD,
NO_DAYS_OVERDRAWN_CURR_PERIOD,
INTEREST_PAID_PTD,
RETURNED_ITEM_FEE_PTD,
OD_FEE_PTD,
FED_WITHHOLD_AMT_YEAR_TO_DATE,
YTD_INTEREST,
TIMES_OD_YTD,
TIMES_NSF_YTD,
NO_DAYS_OVERDRAWN_YR_TO_DATE,
RETURNED_ITEM_FEE_YTD,
OD_FEE_YTD,
CONF_STMT_FLAG,
HOLD_CODE,
PROFIT_CENTER,
ACH_POSTING_CODE,
ACH_NOTICE_CODE,
MIS_DATA_CODE,
NEW_ACCOUNT_FLAG,
CALL_REPORT_CODE,
NEW_CLOSED_DAYS_COUNTER,
DATE_LAST_MAINTAINED,
DATE_CLOSED,
DATE_ATM_LAST_USED,
TIMES_KITING_CURR_PERIOD,
AMT_ORIGINAL_OVERDRAFT,
TOT_ACT_CHG_WAV,
AGGR_BALANCE_CURRENT_PERIOD,
NO_PAPER_CREDITS_CURR_PERIOD,
WAIVER_DIRECT_SC,
NO_ENCLOSURE_CURRENT_PERIOD,
AGG_OVERDRAFT_BAL_CURR_PERIOD,
NO_OF_ATM_CASH_WITHDRAWL,
NO_LOCAL_ITEMS_DEP_CURR_PERIOD,
NO_CHECKS_PAID_FLOAT,
NO_ACH_CREDITS,
NO_ATM_CREDITS,
TIMES_ATM_USED_TOTAL,
NO_OF_POSTING_DAYS,
TIMES_OD_PRYR,
NO_DAYS_OVERDRAWN_PRIOR_YEAR,
IS_PAYROLL_ACCOUNT,
IS_PUBLIC_FUND,
TAX_CODE,
AGG_BALANCE_YTD,
STATE_TAX_WHELD_PTD,
DAILY_ACCURAL_FACTOR,
CD_TYPE,
NEGOTIABLE_CODE,
NUMBER_OF_TIMES_RENEWED,
PROCEEDS_ACCOUNT_NUMBER,
PROJECTED_ACCRUED_INTEREST,
EQUAL_INT_PAYMENT_IND,
PENALTY_AMOUNT,
COLLATERAL_PLEDGE_CODE,
DATE_LAST_INTEREST,
SECURED_DEPOSIT_INDICATOR,
RATE_CHANGE_FREQUENCY,
PREMIUM_CD_RATE,
INITIAL_INTEREST_RATE,
RENEWAL_INTEREST_RATE,
AMOUNT_OF_LAST_INTEREST,
ONE_UP,
PYR_INT_REPORTED_NOT_PAID,
PRIOR_YEAR_INTEREST_FORFEITED,
INT_REPORT_NOT_PAID,
AVG_UNCOLLECT_BAL_CURR_PERIOD,
CERTIFICATE_NUMBER,
STATUS_CODE,
FACE_AMOUNT,
INTEREST_RATE,
MATURITY_DATE,
TERM,
DATE_LAST_ACTIVITY,
LAST_CUSTOMER_ACTIVITY,
DATE_LAST_DEPOSIT,
AMOUNT_DEPOSIT_LAST,
DATE_LAST_WITHDRAWAL,
LAST_WITHDRAWN_AMOUNT,
LAST_STMT_DATE,
BAL_FWD_LAST_STMT,
YTD_AVERAGE_BALANCE,
AVG_BALANCE_CURRENT_PERIOD,
OVERDRAFT_CODE,
OVERDRAFT_LIMIT,
ASSIGNED_OFFICER,
ACCRUAL_KEY,
DATE_ACCOUNT_REOPEN,
DATE_OVERDRAWN,
UNCOLLECTED_BALANCE,
ACCRUED_INTEREST,
DAYS_PER_YEAR,
PROCEEDS_CODE,
CLUB_AMOUNT,
CLUB_NUMBER_PAYMENTS,
CLUB_PAYMENT_AMOUNT,
CLUB_PAYMENT_CODE,
DATE_NEXT_INTEREST,
INTEREST_FREQUENCY,
INTEREST_DAY_OF_MONTH,
RATE_CHANGE_CODE,
BAL_SUBJECT_TO_PENALTY,
INTEREST_FORFIETED,
FED_WITHHOLDING_CODE,
STATE_WITHHOLDING_CODE,
INTEREST_CALCULATION,
MATURITY_AUTO_RENEW,
NSF_CHARGE,
OD_CHARGE,
DAU_CHARGE,
LOW_BALANCE_CURRENT_PERIOD,
CURRENT_STATEMENT_CYCLE,
INTEREST_CHANGE_RATE,
DATE_FIRST_OVERDRAWN,
CD_PRE_CHECK_AMOUNT,
RENEWED_AMOUNT,
DATE_LAST_RENEWED,
PREVIOUS_STMT_DATE,
PREVIOUS_BALANCE,
DATE_LAST_EXTERNAL_DEBIT_ACTY,
AVG_BALANCE_PREV_PERIOD,
NO_CHRG_BACK_ITEMS_YR_TO_DATE,
OLD_INTEREST_RATE,
DATE_PREVIOUS_ACTIVITY,
ANTICIPATED_INTEREST,
ACCUM_INTEREST_NOT_PAID,
TIMES_KITING_YTD,
TIMES_KITING_PRYR,
DATE_LAST_KITING,
PREV_KITING_DATE,
INTEREST_EARNED_LIFE,
NO_TIMES_EXCESS_MMA_RPT,
OLD_KITE_DEBITS,
OLD_KITE_CREDITS,
PAID_OUT_DATE,
PREV_NO_DEBITS_CURRENT_PERIOD,
PREV_NO_CREDITS_CURRENT_PERIOD,
PREV_AMT_CREDITS_CURR_PERIOD,
PREV_AMT_DEBITS_CURR_PERIOD,
PREV_NO_ACH_DEBITS_CURR_PERIOD,
PREV_NO_TRANSIT_ITEMS,
PREV_NO_OF_CHECKS,
PREV_FED_WITHOLD_AMT_CURR_PTD,
PREV_NO_DEPOSITS_CURR_PERIOD,
PREV_NO_ATM_DEBITS,
PREV_SRV_CHRG_ACT_CURR_PERIOD,
PREV_SRV_CHRG_MAINTCURR_PERIOD,
PREV_TIMES_OD_CURR_PERIOD,
PREV_TIMES_NSF_CURR_PERIOD,
PREV_NO_DAYS_OD_CURR_PERIOD,
PREV_INTEREST_PAID_PTD,
PREV_RETURNED_ITEM_FEE_PTD,
PREV_OD_FEE_PTD,
PREV_AGGR_BALANCE_CURR_PERIOD,
PREV_NO_ENCLOSURE_CURR_PERIOD,
PREV_TIMES_KITING_CURR_PERIOD,
PREV_NO_OF_POSTING_DAYS,
CYCLE_GROUP_CYCLE_CODE,
PRIOR_YEAR_INTEREST,
RETURNS_LAST_YR,
PRIOR_YEAR_FED_WITHHOLD_AMT,
A.ACCOUNT_NO,A.ACCOUNT_TYPE_ID,A.CREATION_DATE,A.BUSINESS_DATE,A.LAST_PROCESSED_DATE,A.PROCESSING_STATUS 
FROM DEPOSIT_ACCOUNT DA , ACCOUNT A
WHERE DA.ACCOUNT_ID = A.ACCOUNT_ID;

alter TABLE DEPOSIT_account set unused( 
PENALTY_ID,
--PLAN_ID,
--ASSIGNED_BRANCH,
PROCEEDS_ACCOUNT_ID,
LEDGER_BALANCE,
AVAILABLE_BALANCE,
CURRENT_BALANCE,
OPENING_BALANCE,
NO_DEBITS_CURRENT_PERIOD,
AMT_OF_DEBITS_CURRENT_PERIOD,
NO_CREDITS_CURRENT_PERIOD,
AMT_OF_CREDITS_CURRENT_PERIOD,
NO_ACH_DEBITS_CURRENT_PERIOD,
NO_TRANSIT_ITEMS,
NO_OF_CHECKS,
FED_WITHHOLD_AMT_CURR_PERIOD,
NO_DEPOSITS_CURRENT_PERIOD,
NO_ATM_DEBITS,
SRV_CHRG_ACT_CURR_PERIOD,
SRV_CHRG_MAINTCURR_PERIOD,
TIMES_OD_CURR_PERIOD,
TIMES_NSF_CURR_PERIOD,
NO_DAYS_OVERDRAWN_CURR_PERIOD,
INTEREST_PAID_PTD,
RETURNED_ITEM_FEE_PTD,
OD_FEE_PTD,
FED_WITHHOLD_AMT_YEAR_TO_DATE,
YTD_INTEREST,
TIMES_OD_YTD,
TIMES_NSF_YTD,
NO_DAYS_OVERDRAWN_YR_TO_DATE,
RETURNED_ITEM_FEE_YTD,
OD_FEE_YTD,
CONF_STMT_FLAG,
HOLD_CODE,
PROFIT_CENTER,
ACH_POSTING_CODE,
ACH_NOTICE_CODE,
MIS_DATA_CODE,
NEW_ACCOUNT_FLAG,
CALL_REPORT_CODE,
NEW_CLOSED_DAYS_COUNTER,
DATE_LAST_MAINTAINED,
DATE_CLOSED,
DATE_ATM_LAST_USED,
TIMES_KITING_CURR_PERIOD,
AMT_ORIGINAL_OVERDRAFT,
TOT_ACT_CHG_WAV,
AGGR_BALANCE_CURRENT_PERIOD,
NO_PAPER_CREDITS_CURR_PERIOD,
WAIVER_DIRECT_SC,
NO_ENCLOSURE_CURRENT_PERIOD,
AGG_OVERDRAFT_BAL_CURR_PERIOD,
NO_OF_ATM_CASH_WITHDRAWL,
NO_LOCAL_ITEMS_DEP_CURR_PERIOD,
NO_CHECKS_PAID_FLOAT,
NO_ACH_CREDITS,
NO_ATM_CREDITS,
TIMES_ATM_USED_TOTAL,
NO_OF_POSTING_DAYS,
TIMES_OD_PRYR,
NO_DAYS_OVERDRAWN_PRIOR_YEAR,
IS_PAYROLL_ACCOUNT,
IS_PUBLIC_FUND,
TAX_CODE,
AGG_BALANCE_YTD,
STATE_TAX_WHELD_PTD,
DAILY_ACCURAL_FACTOR,
CD_TYPE,
NEGOTIABLE_CODE,
NUMBER_OF_TIMES_RENEWED,
PROCEEDS_ACCOUNT_NUMBER,
PROJECTED_ACCRUED_INTEREST,
EQUAL_INT_PAYMENT_IND,
PENALTY_AMOUNT,
COLLATERAL_PLEDGE_CODE,
DATE_LAST_INTEREST,
SECURED_DEPOSIT_INDICATOR,
RATE_CHANGE_FREQUENCY,
PREMIUM_CD_RATE,
INITIAL_INTEREST_RATE,
RENEWAL_INTEREST_RATE,
AMOUNT_OF_LAST_INTEREST,
ONE_UP,
PYR_INT_REPORTED_NOT_PAID,
PRIOR_YEAR_INTEREST_FORFEITED,
INT_REPORT_NOT_PAID,
AVG_UNCOLLECT_BAL_CURR_PERIOD,
CERTIFICATE_NUMBER,
STATUS_CODE,
FACE_AMOUNT,
INTEREST_RATE,
MATURITY_DATE,
TERM,
DATE_LAST_ACTIVITY,
LAST_CUSTOMER_ACTIVITY,
DATE_LAST_DEPOSIT,
AMOUNT_DEPOSIT_LAST,
DATE_LAST_WITHDRAWAL,
LAST_WITHDRAWN_AMOUNT,
LAST_STMT_DATE,
BAL_FWD_LAST_STMT,
YTD_AVERAGE_BALANCE,
AVG_BALANCE_CURRENT_PERIOD,
OVERDRAFT_CODE,
OVERDRAFT_LIMIT,
ASSIGNED_OFFICER,
ACCRUAL_KEY,
DATE_ACCOUNT_REOPEN,
DATE_OVERDRAWN,
UNCOLLECTED_BALANCE,
ACCRUED_INTEREST,
DAYS_PER_YEAR,
PROCEEDS_CODE,
CLUB_AMOUNT,
CLUB_NUMBER_PAYMENTS,
CLUB_PAYMENT_AMOUNT,
CLUB_PAYMENT_CODE,
DATE_NEXT_INTEREST,
INTEREST_FREQUENCY,
INTEREST_DAY_OF_MONTH,
RATE_CHANGE_CODE,
BAL_SUBJECT_TO_PENALTY,
INTEREST_FORFIETED,
FED_WITHHOLDING_CODE,
STATE_WITHHOLDING_CODE,
INTEREST_CALCULATION,
MATURITY_AUTO_RENEW,
NSF_CHARGE,
OD_CHARGE,
DAU_CHARGE,
LOW_BALANCE_CURRENT_PERIOD,
CURRENT_STATEMENT_CYCLE,
INTEREST_CHANGE_RATE,
DATE_FIRST_OVERDRAWN,
CD_PRE_CHECK_AMOUNT,
RENEWED_AMOUNT,
DATE_LAST_RENEWED,
PREVIOUS_STMT_DATE,
PREVIOUS_BALANCE,
DATE_LAST_EXTERNAL_DEBIT_ACTY,
AVG_BALANCE_PREV_PERIOD,
NO_CHRG_BACK_ITEMS_YR_TO_DATE,
OLD_INTEREST_RATE,
DATE_PREVIOUS_ACTIVITY,
ANTICIPATED_INTEREST,
ACCUM_INTEREST_NOT_PAID,
TIMES_KITING_YTD,
TIMES_KITING_PRYR,
DATE_LAST_KITING,
PREV_KITING_DATE,
INTEREST_EARNED_LIFE,
NO_TIMES_EXCESS_MMA_RPT,
OLD_KITE_DEBITS,
OLD_KITE_CREDITS,
PAID_OUT_DATE,
PREV_NO_DEBITS_CURRENT_PERIOD,
PREV_NO_CREDITS_CURRENT_PERIOD,
PREV_AMT_CREDITS_CURR_PERIOD,
PREV_AMT_DEBITS_CURR_PERIOD,
PREV_NO_ACH_DEBITS_CURR_PERIOD,
PREV_NO_TRANSIT_ITEMS,
PREV_NO_OF_CHECKS,
PREV_FED_WITHOLD_AMT_CURR_PTD,
PREV_NO_DEPOSITS_CURR_PERIOD,
PREV_NO_ATM_DEBITS,
PREV_SRV_CHRG_ACT_CURR_PERIOD,
PREV_SRV_CHRG_MAINTCURR_PERIOD,
PREV_TIMES_OD_CURR_PERIOD,
PREV_TIMES_NSF_CURR_PERIOD,
PREV_NO_DAYS_OD_CURR_PERIOD,
PREV_INTEREST_PAID_PTD,
PREV_RETURNED_ITEM_FEE_PTD,
PREV_OD_FEE_PTD,
PREV_AGGR_BALANCE_CURR_PERIOD,
PREV_NO_ENCLOSURE_CURR_PERIOD,
PREV_TIMES_KITING_CURR_PERIOD,
PREV_NO_OF_POSTING_DAYS,
CYCLE_GROUP_CYCLE_CODE,
PRIOR_YEAR_INTEREST,
RETURNS_LAST_YR,
PRIOR_YEAR_FED_WITHHOLD_AMT
);

ALTER TABLE DEPOSIT_ACCOUNT DROP UNUSED COLUMNS; 

ALTER TABLE DEPOSIT
ADD CONSTRAINT DEP_UK UNIQUE (ACCOUNT_ID);

ALTER TABLE DEPOSIT ADD ( CONSTRAINT D_ACCID_FK FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID));

ALTER TABLE DEPOSIT
    ADD ( CONSTRAINT DA_CRC_FK
	FOREIGN KEY(CALL_REPORT_CODE)
	REFERENCES CALL_REPORT_LKP(CALL_REPORT_CODE)
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

--ALTER TABLE DEPOSIT
--    ADD ( CONSTRAINT DA_ASSBR_FK
--	FOREIGN KEY(ASSIGNED_BRANCH)
--	REFERENCES BRANCH(UNIQUE_ID)
--	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE DEPOSIT
    ADD ( CONSTRAINT DA_PID_FK
	FOREIGN KEY(PENALTY_ID)
	REFERENCES PENALTY_PARAMETER(PENALTY_ID)
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

--ALTER TABLE DEPOSIT
--    ADD ( CONSTRAINT DA_PLANID_FK
--	FOREIGN KEY(PLAN_ID)
--	REFERENCES SAVINGS_PLAN_DETAILS(PLAN_ID)
--	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE DEPOSIT
    ADD ( CONSTRAINT DA_ODCODE_FK
	FOREIGN KEY(OVERDRAFT_CODE)
	REFERENCES OVERDRAFT_LOOKUP(OVERDRAFT_CODE)
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE DEPOSIT
    ADD ( CONSTRAINT DA_CONFSTMTFLAG_FK
	FOREIGN KEY(CONF_STMT_FLAG)
	REFERENCES CONF_STMT_FLAG_LOOKUP(CONF_STMT_FLAG)
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

CREATE INDEX INT_FREQ_IDX ON DEPOSIT(INTEREST_FREQUENCY);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
CREATE INDEX DA_STATUSCODE_IDX ON DEPOSIT(STATUS_CODE);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
CREATE INDEX DEPOSIT_LSTMTDATE_IDX ON DEPOSIT(LAST_STMT_DATE);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
--CREATE INDEX DEP_ACCT_ASSIGNED_BR_IDX ON DEPOSIT(ASSIGNED_BRANCH);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
CREATE INDEX DEP_ACCT_CALL_REP_CODE_IDX ON DEPOSIT(CALL_REPORT_CODE);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
CREATE INDEX DEP_ACCT_CONF_STMT_FLAG_IDX ON DEPOSIT(CONF_STMT_FLAG);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
CREATE INDEX DEP_ACCT_OVERDRAFT_CODE_IDX ON DEPOSIT(OVERDRAFT_CODE);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
CREATE INDEX DEP_ACCT_PENALTY_ID_IDX ON DEPOSIT(PENALTY_ID);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
--CREATE INDEX DEP_ACCT_PL_ID_IDX ON DEPOSIT(PLAN_ID);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
CREATE INDEX DEP_CYCLE_CODE_IDX ON DEPOSIT(CURRENT_STATEMENT_CYCLE);  