CREATE TABLE CHARGE_DEFINITION (CHARGE_DEF_ID NUMBER(10),SERVICE_NAME VARCHAR2(30),CAL_METHOD VARCHAR2(10),RATE_STRATEGY VARCHAR2(10),CHARGE_TYPE VARCHAR2(20),MAX_CHARGE NUMBER(10,2),MIN_CHARGE NUMBER(10,2));

CREATE TABLE SLAB (SLAB_ID NUMBER(10),CHARGE_DEF_ID NUMBER(10),CHARGE_TYPE VARCHAR2(20),BASE_CHARGE NUMBER(10,2), MIN_COUNT NUMBER(10),MAX_COUNT NUMBER(10),MIN_AMOUNT NUMBER(12,2),MAX_AMOUNT NUMBER(12,2),CHARGE_AMOUNT NUMBER(10,2));

CREATE TABLE CHARGE_CONDITIONS (CONDITION_ID NUMBER(10),CHARGE_DEF_ID NUMBER(10),BALANCE_TYPE VARCHAR2(50),CONDTION NUMBER(1),VALUE NUMBER(12,2));


CREATE TABLE CHARGE_CONTEXT (CONTEXT_ID NUMBER(10),ACCOUNT_ID VARCHAR2(30),CHARGE_DEF_ID VARCHAR2(10),CHARGE_TYPE VARCHAR2(20),TXN_COUNT NUMBER(7),CUM_CHARGE_AMOUNT NUMBER(12,2));


CREATE SEQUENCE CHARGE_CTX_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE CHARGE_DEF_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SLAB_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE CONDITION_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;