INSERT INTO ENTITY_TYPE_DEFINITION(ENTITY_TYPE_DEFINITION_ID, TYPE_NAME, TYPE_DESCRIPTION, ENTITY_TYPE_INSTANCE_CLASS, BASE_ENTITY_TYPE_DEF_ID, LOOKUP, SYSTEM, TEMPLATE)
  VALUES((select max(ENTITY_TYPE_DEFINITION_ID)+1 from ENTITY_TYPE_DEFINITION), 'PastDueCounterScheme', 'Past Due Counter Scheme', 'com.vsoftcorp.loan.model.entities.PastDueCounterScheme', NULL, 1, 0, NULL);
INSERT INTO ENTITY_TYPE_DEFINITION(ENTITY_TYPE_DEFINITION_ID, TYPE_NAME, TYPE_DESCRIPTION, ENTITY_TYPE_INSTANCE_CLASS, BASE_ENTITY_TYPE_DEF_ID, LOOKUP, SYSTEM, TEMPLATE)
  VALUES((select max(ENTITY_TYPE_DEFINITION_ID)+1 from ENTITY_TYPE_DEFINITION), 'PastDueRange', 'Past Due Range', 'com.vsoftcorp.loan.model.entities.PastDueRange', NULL, 0, 0, NULL);
INSERT INTO ENTITY_TYPE_DEFINITION(ENTITY_TYPE_DEFINITION_ID, TYPE_NAME, TYPE_DESCRIPTION, ENTITY_TYPE_INSTANCE_CLASS, BASE_ENTITY_TYPE_DEF_ID, LOOKUP, SYSTEM, TEMPLATE)
  VALUES((select max(ENTITY_TYPE_DEFINITION_ID)+1 from ENTITY_TYPE_DEFINITION), 'EscrowBill', 'Escrow Bill', 'com.vsoftcorp.loan.model.entities.EscrowBill', NULL, 0, 0, NULL);
INSERT INTO ENTITY_TYPE_DEFINITION(ENTITY_TYPE_DEFINITION_ID, TYPE_NAME, TYPE_DESCRIPTION, ENTITY_TYPE_INSTANCE_CLASS, BASE_ENTITY_TYPE_DEF_ID, LOOKUP, SYSTEM, TEMPLATE)
  VALUES((select max(ENTITY_TYPE_DEFINITION_ID)+1 from ENTITY_TYPE_DEFINITION), 'EscrowBillingDetails', 'Escrow Billing Details', 'com.vsoftcorp.loan.model.entities.EscrowBillingDetails', NULL, 0, 0, NULL);
INSERT INTO ENTITY_TYPE_DEFINITION(ENTITY_TYPE_DEFINITION_ID, TYPE_NAME, TYPE_DESCRIPTION, ENTITY_TYPE_INSTANCE_CLASS, BASE_ENTITY_TYPE_DEF_ID, LOOKUP, SYSTEM, TEMPLATE)
  VALUES((select max(ENTITY_TYPE_DEFINITION_ID)+1 from ENTITY_TYPE_DEFINITION), 'CollectorAgent', 'Collector Agent', 'com.vsoftcorp.loan.model.entities.CollectorAgent', NULL, 1, 0, NULL);
INSERT INTO ENTITY_TYPE_DEFINITION(ENTITY_TYPE_DEFINITION_ID, TYPE_NAME, TYPE_DESCRIPTION, ENTITY_TYPE_INSTANCE_CLASS, BASE_ENTITY_TYPE_DEF_ID, LOOKUP, SYSTEM, TEMPLATE)
  VALUES((select max(ENTITY_TYPE_DEFINITION_ID)+1 from ENTITY_TYPE_DEFINITION), 'EscrowDisbursmentProjection', 'Escrow Disbursment Projection', 'com.vsoftcorp.loan.model.entities.EscrowDisbursmentProjection', NULL, 0, 0, NULL);
INSERT INTO ENTITY_TYPE_DEFINITION(ENTITY_TYPE_DEFINITION_ID, TYPE_NAME, TYPE_DESCRIPTION, ENTITY_TYPE_INSTANCE_CLASS, BASE_ENTITY_TYPE_DEF_ID, LOOKUP, SYSTEM, TEMPLATE)
  VALUES((select max(ENTITY_TYPE_DEFINITION_ID)+1 from ENTITY_TYPE_DEFINITION), 'SoldLoanContract', 'Sold Loan Contract', 'com.vsoftcorp.loan.model.entities.SoldLoanContract', NULL, 0, 0, NULL);
INSERT INTO ENTITY_TYPE_DEFINITION(ENTITY_TYPE_DEFINITION_ID, TYPE_NAME, TYPE_DESCRIPTION, ENTITY_TYPE_INSTANCE_CLASS, BASE_ENTITY_TYPE_DEF_ID, LOOKUP, SYSTEM, TEMPLATE)
  VALUES((select max(ENTITY_TYPE_DEFINITION_ID)+1 from ENTITY_TYPE_DEFINITION), 'ServicingLoanDetails', 'Servicing Loan Details', 'com.vsoftcorp.loan.model.entities.ServicingLoanDetails', NULL, 0, 0, NULL);
INSERT INTO ENTITY_TYPE_DEFINITION(ENTITY_TYPE_DEFINITION_ID, TYPE_NAME, TYPE_DESCRIPTION, ENTITY_TYPE_INSTANCE_CLASS, BASE_ENTITY_TYPE_DEF_ID, LOOKUP, SYSTEM, TEMPLATE)
  VALUES((select max(ENTITY_TYPE_DEFINITION_ID)+1 from ENTITY_TYPE_DEFINITION), 'Investor', 'Investor', 'com.vsoftcorp.loan.model.entities.ServicingInvestor', NULL, 1, 0, NULL);
INSERT INTO ENTITY_TYPE_DEFINITION(ENTITY_TYPE_DEFINITION_ID, TYPE_NAME, TYPE_DESCRIPTION, ENTITY_TYPE_INSTANCE_CLASS, BASE_ENTITY_TYPE_DEF_ID, LOOKUP, SYSTEM, TEMPLATE)
  VALUES((select max(ENTITY_TYPE_DEFINITION_ID)+1 from ENTITY_TYPE_DEFINITION), 'CreditLifeAHInsurance', 'CreditLife&A/H Insurance', 'com.vsoftcorp.loan.model.entities.CreditLifeAHInsurance', NULL, 0, 0, NULL);
INSERT INTO ENTITY_TYPE_DEFINITION(ENTITY_TYPE_DEFINITION_ID, TYPE_NAME, TYPE_DESCRIPTION, ENTITY_TYPE_INSTANCE_CLASS, BASE_ENTITY_TYPE_DEF_ID, LOOKUP, SYSTEM, TEMPLATE)
  VALUES((select max(ENTITY_TYPE_DEFINITION_ID)+1 from ENTITY_TYPE_DEFINITION), 'FixedAmountBasedInsurance', 'Fixed Amount Based Insurance', 'com.vsoftcorp.loan.model.entities.FixedAmountBasedInsurance', (select entity_type_definition_id from entity_type_definition where type_name='CreditLifeAHInsurance'), 0, 0, NULL);
INSERT INTO ENTITY_TYPE_DEFINITION(ENTITY_TYPE_DEFINITION_ID, TYPE_NAME, TYPE_DESCRIPTION, ENTITY_TYPE_INSTANCE_CLASS, BASE_ENTITY_TYPE_DEF_ID, LOOKUP, SYSTEM, TEMPLATE)
  VALUES((select max(ENTITY_TYPE_DEFINITION_ID)+1 from ENTITY_TYPE_DEFINITION), 'AccrualBasedInsurance', 'Accrual Based Insurance', 'com.vsoftcorp.loan.model.entities.AccrualBasedInsurance', (select entity_type_definition_id from entity_type_definition where type_name='CreditLifeAHInsurance'), 0, 0, NULL);
INSERT INTO ENTITY_TYPE_DEFINITION(ENTITY_TYPE_DEFINITION_ID, TYPE_NAME, TYPE_DESCRIPTION, ENTITY_TYPE_INSTANCE_CLASS, BASE_ENTITY_TYPE_DEF_ID, LOOKUP, SYSTEM, TEMPLATE)
  VALUES((select max(ENTITY_TYPE_DEFINITION_ID)+1 from ENTITY_TYPE_DEFINITION), 'RebateBasedInsurance', 'Rebate Based Insurance', 'com.vsoftcorp.loan.model.entities.RebateBasedInsurance', (select entity_type_definition_id from entity_type_definition where type_name='CreditLifeAHInsurance'), 0, 0, NULL);
INSERT INTO ENTITY_TYPE_DEFINITION(ENTITY_TYPE_DEFINITION_ID, TYPE_NAME, TYPE_DESCRIPTION, ENTITY_TYPE_INSTANCE_CLASS, BASE_ENTITY_TYPE_DEF_ID, LOOKUP, SYSTEM, TEMPLATE)
  VALUES((select max(ENTITY_TYPE_DEFINITION_ID)+1 from ENTITY_TYPE_DEFINITION), 'BankClassificationHistory', 'Bank ClassificationHistory', 'com.vsoftcorp.loan.model.entities.BankClassificationHistory', NULL, 0, 0, NULL);
INSERT INTO ENTITY_TYPE_DEFINITION(ENTITY_TYPE_DEFINITION_ID, TYPE_NAME, TYPE_DESCRIPTION, ENTITY_TYPE_INSTANCE_CLASS, BASE_ENTITY_TYPE_DEF_ID, LOOKUP, SYSTEM, TEMPLATE)
  VALUES((select max(ENTITY_TYPE_DEFINITION_ID)+1 from ENTITY_TYPE_DEFINITION), 'BankDefinedFields', 'Bank Defined Fields', 'com.vsoftcorp.loan.model.entities.BankDefinedFields', NULL, 0, 0, NULL);
INSERT INTO ENTITY_TYPE_DEFINITION(ENTITY_TYPE_DEFINITION_ID, TYPE_NAME, TYPE_DESCRIPTION, ENTITY_TYPE_INSTANCE_CLASS, BASE_ENTITY_TYPE_DEF_ID, LOOKUP, SYSTEM, TEMPLATE)
  VALUES((select max(ENTITY_TYPE_DEFINITION_ID)+1 from ENTITY_TYPE_DEFINITION), 'CreditLifeAHInsuranceCompany', 'CreditLife&A/H Insurance Company', 'com.vsoftcorp.loan.model.entities.ExternalAgency', (select entity_type_definition_id from entity_type_definition where type_name='ExternalAgency'), 1, 0, NULL);

