INSERT INTO PROPERTY_DEFINITION(PROPERTY_DEFINITION_ID, ENTITY_TYPE_DEFINITION_ID, PROPERTY_NAME, PROPERTY_INDEX, PROPERTY_DESCRIPTION, VALUE_TYPE_DEFINITION_ID, DESCRIPTION_FIELD, DESCRIPTION_FIELD_OVERRIDEN, DEFAULT_VALUE, DEFAULT_VALUE_OVERRIDEN, VALID_VALUES, VALID_VALUES_OVERRIDEN, MANDATORY, MANDATORY_OVERRIDEN, INHERITED, CAN_EDIT_DEFINITION, CAN_DELETE_DEFINITION, CATEGORY_OVERRIDEN, CATEGORY, PRIMARY_OVERRIDEN, PRIMARY)
VALUES((SELECT MAX(PROPERTY_DEFINITION_ID)+1 FROM PROPERTY_DEFINITION), (SELECT MAX(ENTITY_TYPE_DEFINITION_ID) FROM ENTITY_TYPE_DEFINITION WHERE TYPE_NAME LIKE 'RegularPaymentSchedule'), 'MonthEndFrequency',14, 'Month End Frequency', 0, 0, 0, 'java.lang.Boolean:false', 0, 'java.lang.Boolean:{default={true=Yes, false=No}}', 0, 0, 0, 0, 1, 0, 0, 'UC', 0, 0);

INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
VALUES((SELECT MAX(PROPERTY_DEFINITION_ID) FROM PROPERTY_DEFINITION), 0, 0, 1, 1, 'DEFAULT'); 
INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
VALUES((SELECT MAX(PROPERTY_DEFINITION_ID) FROM PROPERTY_DEFINITION), 0, 0, 0, 0, 'INQUIRY');
INSERT INTO PROPERTY_PRESENTER_ATTRIBUTES(PROPERTY_DEFINITION_ID, HIDDEN, HIDDEN_OVERRIDEN, EDITABLE, EDITABLE_OVERRIDEN, STATE_NAME)
VALUES((SELECT MAX(PROPERTY_DEFINITION_ID) FROM PROPERTY_DEFINITION), 0, 0, 1, 1, 'ACCOUNT_CREATED');
  
ALTER TABLE LOAN_PERIOD_INTEREST_RATE MODIFY RATE_OF_INTEREST NUMBER(10,3);